// AUD - Auditing and Attestation Questions
// Comprehensive question bank for CPA exam preparation

import { Question } from '../../../types';

export const AUD_QUESTIONS: Question[] = [
  // ==========================================
  // AREA 1: Ethics, Independence, and Professional Responsibilities
  // ==========================================

  {
    id: 'aud-eth-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics and Independence',
    subtopic: 'AICPA Code of Conduct',
    difficulty: 'medium',
    skillLevel: 'Application',
    question:
      'Under the AICPA Code of Professional Conduct, which of the following would impair independence?',
    options: [
      'Having a close relative employed by the client in a non-key position',
      'Providing tax preparation services to an attest client',
      'Providing consulting services unrelated to internal control',
      'Owning an immaterial direct financial interest in an attest client',
    ],
    correctAnswer: 3,
    explanation:
      'Any direct financial interest, regardless of materiality, impairs independence. Indirect financial interests are evaluated for materiality. Tax services and certain consulting services are generally permitted.',
    reference: 'AICPA Code of Conduct ET 1.210',
  },
  {
    id: 'aud-eth-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics and Independence',
    subtopic: 'AICPA Code of Conduct',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A "covered member" for independence purposes includes all of the following EXCEPT:',
    options: [
      'A partner in the office where the lead attest partner practices',
      'An individual on the attest engagement team',
      'An individual in a position to influence the attest engagement',
      'Any partner in any office of the firm',
    ],
    correctAnswer: 3,
    explanation:
      'Covered members include: engagement team, those who influence the engagement, partners in the engagement office, and the firm itself. Not all partners firm-wide are covered members.',
    reference: 'AICPA Code of Conduct ET 0.400.12',
  },
  {
    id: 'aud-eth-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics and Independence',
    subtopic: 'SEC Independence',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under SEC rules, audit partner rotation is required every:',
    options: [
      '5 years',
      '7 years',
      '3 years',
      '10 years',
    ],
    correctAnswer: 0,
    explanation:
      'SEC rules require rotation of the lead audit partner and the concurring review partner every 5 years, with a 5-year cooling off period before returning to that role.',
    reference: 'SEC Regulation S-X Rule 2-01(c)(6)',
  },
  {
    id: 'aud-eth-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics and Independence',
    subtopic: 'Prohibited Services',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following services is prohibited for auditors of SEC registrants?',
    options: [
      'Due diligence services for potential acquisitions',
      'Bookkeeping services',
      'Tax compliance services',
      'Tax planning advice',
    ],
    correctAnswer: 1,
    explanation:
      'SOX prohibits bookkeeping, financial information systems design, appraisal services, internal audit outsourcing, management functions, HR services, broker-dealer services, and certain legal services.',
    reference: 'SOX Section 201',
  },
  {
    id: 'aud-eth-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics and Independence',
    subtopic: 'Integrity and Objectivity',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The integrity principle of the AICPA Code requires CPAs to:',
    options: [
      'Maintain minimum continuing education requirements',
      'Always follow client instructions',
      'Never make errors in professional work',
      'Be honest and candid within confidentiality constraints',
    ],
    correctAnswer: 3,
    explanation:
      'Integrity requires honesty and candidness, not subordinating judgment to others, and not knowingly misrepresenting facts or being associated with misleading information.',
    reference: 'AICPA Code of Conduct ET 1.100',
  },

  // ==========================================
  // AREA 2: Risk Assessment and Planning
  // ==========================================

  {
    id: 'aud-risk-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Audit Risk Model',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The audit risk model is expressed as:',
    options: [
      'AR = IR + CR + DR',
      'AR = (IR + CR) × DR',
      'AR = IR × CR × DR',
      'AR = IR × CR / DR',
    ],
    correctAnswer: 2,
    explanation:
      'Audit Risk = Inherent Risk × Control Risk × Detection Risk. The auditor sets acceptable AR, assesses IR and CR, then determines DR to achieve the desired AR level.',
    reference: 'AU-C 200.A42',
  },
  {
    id: 'aud-risk-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Risk Assessment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When inherent risk and control risk are assessed as high, the auditor should:',
    options: [
      'Set detection risk at a low level',
      'Rely primarily on tests of controls',
      'Withdraw from the engagement',
      'Set detection risk at a high level',
    ],
    correctAnswer: 0,
    explanation:
      'When IR and CR are high, the risk of material misstatement (RMM) is high. To maintain acceptable audit risk, detection risk must be set low, requiring more extensive substantive procedures.',
    reference: 'AU-C 315.A142',
  },
  {
    id: 'aud-risk-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Materiality',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Performance materiality is set at an amount:',
    options: [
      'Determined by management',
      'Equal to overall materiality',
      'Less than overall materiality',
      'Greater than overall materiality',
    ],
    correctAnswer: 2,
    explanation:
      'Performance materiality is set below overall materiality to reduce the risk that the aggregate of uncorrected and undetected misstatements exceeds overall materiality.',
    reference: 'AU-C 320.09',
  },
  {
    id: 'aud-risk-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Understanding the Entity',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: "Understanding the entity's internal control is required primarily to:",
    options: [
      'Prepare the financial statements',
      'Express an opinion on internal control',
      'Determine if the entity should be audited',
      'Identify and assess risks of material misstatement',
    ],
    correctAnswer: 3,
    explanation:
      'The auditor obtains an understanding of internal control to identify types of potential misstatements, factors affecting RMM, and to design appropriate audit procedures.',
    reference: 'AU-C 315.12',
  },
  {
    id: 'aud-risk-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Fraud Risk',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question:
      'The auditor should presume that risks of material misstatement due to fraud exist in:',
    options: ['All account balances', 'Revenue recognition', 'Inventory', 'Cash and investments'],
    correctAnswer: 1,
    explanation:
      'AU-C 240 requires auditors to presume fraud risk in revenue recognition. The auditor should also always consider management override of controls as a fraud risk.',
    reference: 'AU-C 240.27',
  },
  {
    id: 'aud-risk-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Analytical Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Analytical procedures are required during which phases of the audit?',
    options: [
      'Planning only',
      'Planning and final review',
      'All phases of the audit',
      'Substantive testing only',
    ],
    correctAnswer: 1,
    explanation:
      'Analytical procedures are required during planning (risk assessment) and final review (overall conclusion). They are optional but useful during substantive testing.',
    reference: 'AU-C 520.06',
  },

  // ==========================================
  // AREA 3: Internal Control
  // ==========================================

  {
    id: 'aud-ic-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'COSO Framework',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The COSO Internal Control Framework includes how many components?',
    options: [
      'Five',
      'Six',
      'Three',
      'Four',
    ],
    correctAnswer: 0,
    explanation:
      'COSO has five components: (1) Control Environment, (2) Risk Assessment, (3) Control Activities, (4) Information and Communication, and (5) Monitoring Activities.',
    reference: 'COSO Internal Control - Integrated Framework',
  },
  {
    id: 'aud-ic-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'COSO Framework',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which COSO component sets the foundation for all other components?',
    options: ['Risk Assessment', 'Monitoring', 'Control Environment', 'Control Activities'],
    correctAnswer: 2,
    explanation:
      'The Control Environment (tone at the top) is the foundation - it includes integrity, ethical values, management philosophy, organizational structure, and commitment to competence.',
    reference: 'COSO Framework - Control Environment',
  },
  {
    id: 'aud-ic-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Tests of Controls',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Tests of controls are performed when the auditor:',
    options: [
      'Issues a disclaimer of opinion',
      'Performs only substantive procedures',
      'Plans to rely on the operating effectiveness of controls',
      'Assesses control risk at maximum',
    ],
    correctAnswer: 2,
    explanation:
      'Tests of controls are required when the auditor plans to rely on controls to reduce substantive testing, or when substantive procedures alone cannot provide sufficient evidence.',
    reference: 'AU-C 330.08',
  },
  {
    id: 'aud-ic-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Control Deficiencies',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A significant deficiency is:',
    options: [
      'A deficiency that results in a material misstatement',
      'A deficiency, or combination, that is less severe than a material weakness but important enough to merit attention',
      'The same as a material weakness',
      'Any control deficiency',
    ],
    correctAnswer: 1,
    explanation:
      'A significant deficiency is important enough to merit attention by those charged with governance but is less severe than a material weakness. Material weakness = reasonable possibility of material misstatement not prevented/detected.',
    reference: 'AU-C 265.07',
  },
  {
    id: 'aud-ic-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Communication',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The auditor must communicate in writing to management:',
    options: [
      'Control deficiencies only if requested by management',
      'Only material weaknesses',
      'All control deficiencies identified',
      'Significant deficiencies and material weaknesses',
    ],
    correctAnswer: 3,
    explanation:
      'The auditor must communicate in writing significant deficiencies and material weaknesses to those charged with governance. Other deficiencies may be communicated orally.',
    reference: 'AU-C 265.11',
  },

  // ==========================================
  // AREA 4: Evidence and Procedures
  // ==========================================

  {
    id: 'aud-evid-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Sufficiency and Appropriateness',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The appropriateness of audit evidence relates to:',
    options: [
      'The quantity of evidence',
      'The cost of obtaining evidence',
      'The timing of obtaining evidence',
      'The relevance and reliability of evidence',
    ],
    correctAnswer: 3,
    explanation:
      'Appropriateness measures the quality of evidence - its relevance to the assertion being tested and its reliability. Sufficiency measures the quantity of evidence.',
    reference: 'AU-C 500.06',
  },
  {
    id: 'aud-evid-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Reliability',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following sources of evidence is generally most reliable?',
    options: [
      'Documents received directly from independent third parties',
      'Documents generated internally by the client',
      'Oral representations from management',
      'Computations made by the auditor',
    ],
    correctAnswer: 0,
    explanation:
      'External evidence from independent third parties (confirmations, bank statements) is generally more reliable than internal documents or oral representations.',
    reference: 'AU-C 500.A31',
  },
  {
    id: 'aud-evid-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Audit Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Inspection of tangible assets provides evidence primarily about:',
    options: ['Valuation', 'Existence', 'Rights and obligations', 'Completeness'],
    correctAnswer: 1,
    explanation:
      'Physical inspection confirms existence - that the asset is physically present. It does not confirm ownership (rights), value, or completeness.',
    reference: 'AU-C 500.A14',
  },
  {
    id: 'aud-evid-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Confirmations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A positive confirmation requests the recipient to:',
    options: [
      'Respond only if they disagree with the stated amount',
      'Respond in all cases',
      'Contact the auditor by phone',
      'Provide copies of documents',
    ],
    correctAnswer: 1,
    explanation:
      'Positive confirmations request a response in all cases, agreeing or disagreeing. Negative confirmations request a response only if the recipient disagrees.',
    reference: 'AU-C 505.A6',
  },
  {
    id: 'aud-evid-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Substantive Procedures',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Substantive procedures must be performed for:',
    options: [
      'Only high-risk areas',
      'Only material account balances',
      'Only when tests of controls are not performed',
      'All relevant assertions for each material class of transactions, account balance, and disclosure'
    ],
    correctAnswer: 3,
    explanation:
      'Regardless of assessed risk or reliance on controls, substantive procedures are required for all relevant assertions for material transaction classes, balances, and disclosures.',
    reference: 'AU-C 330.18',
  },

  // ==========================================
  // AREA 5: Sampling
  // ==========================================

  {
    id: 'aud-samp-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Sampling Risk',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The risk of assessing control risk too low is a:',
    options: [
      'Risk affecting audit effectiveness',
      'Risk of incorrect rejection',
      'Risk affecting audit efficiency',
      'Risk of incorrect acceptance',
    ],
    correctAnswer: 0,
    explanation:
      'Assessing control risk too low (concluding controls are effective when they are not) affects audit effectiveness - it could lead to failing to detect material misstatements.',
    reference: 'AU-C 530.05',
  },
  {
    id: 'aud-samp-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Sample Size',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'As the tolerable rate of deviation decreases, the required sample size:',
    options: [
      'Remains unchanged',
      'Increases',
      'Decreases',
      'Depends on the population size',
    ],
    correctAnswer: 1,
    explanation:
      'A lower tolerable deviation rate requires a larger sample to provide confidence that the actual rate does not exceed the tolerable rate.',
    reference: 'AU-C 530.A11',
  },
  {
    id: 'aud-samp-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Selection Methods',
    difficulty: 'medium',
    skillLevel: 'Application',
    question:
      'Which sampling method gives every item in the population an equal chance of selection?',
    options: ['Random sampling', 'Judgmental sampling', 'Haphazard sampling', 'Block sampling'],
    correctAnswer: 0,
    explanation:
      'Random sampling provides every item an equal probability of selection. Block sampling selects contiguous items; haphazard has no structured selection; judgmental is non-statistical.',
    reference: 'AU-C 530.A13',
  },

  // ==========================================
  // AREA 6: Completing the Audit
  // ==========================================

  {
    id: 'aud-se-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-completing',
    topic: 'Completing the Audit',
    subtopic: 'Subsequent Events',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Type I subsequent events require:',
    options: [
      'Adjustment to the financial statements',
      'A modified opinion',
      'Disclosure only',
      'No action',
    ],
    correctAnswer: 0,
    explanation:
      'Type I subsequent events provide evidence of conditions existing at the balance sheet date. They require adjustment. Type II events (conditions arising after) require disclosure only.',
    reference: 'AU-C 560.09',
  },
  {
    id: 'aud-se-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-completing',
    topic: 'Completing the Audit',
    subtopic: 'Management Representations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The management representation letter is dated:',
    options: [
      'As of the date of the engagement letter',
      'As of the balance sheet date',
      'As of the date fieldwork begins',
      "As of the date the auditor's report is dated",
    ],
    correctAnswer: 3,
    explanation:
      "The representation letter is dated as of the date of the auditor's report (the last day of fieldwork). It covers the period through that date.",
    reference: 'AU-C 580.14',
  },
  {
    id: 'aud-se-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-completing',
    topic: 'Completing the Audit',
    subtopic: 'Communication with Governance',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which of the following must be communicated to those charged with governance?',
    options: [
      'Names of all staff on the engagement',
      'All adjusting journal entries',
      'Detailed audit procedures performed',
      'Significant findings from the audit',
    ],
    correctAnswer: 3,
    explanation:
      "Required communications include: auditor's responsibilities, planned scope/timing, significant findings, significant difficulties, disagreements with management, and other matters.",
    reference: 'AU-C 260.12',
  },
  {
    id: 'aud-se-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-completing',
    topic: 'Completing the Audit',
    subtopic: 'Documentation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question:
      'Audit documentation should be assembled within how many days after the report release date?',
    options: [
      '60 days',
      '90 days',
      '30 days',
      '45 days',
    ],
    correctAnswer: 0,
    explanation:
      'The audit documentation must be assembled in a final file within 60 days after the report release date. After assembly, no deletions are permitted.',
    reference: 'AU-C 230.14',
  },

  // ==========================================
  // AREA 7: Audit Reports
  // ==========================================

  {
    id: 'aud-rep-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Unmodified Opinion',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An unmodified (clean) opinion states that the financial statements:',
    options: [
      'Are guaranteed to be accurate',
      'Have been verified by the auditor',
      'Are presented fairly in all material respects in accordance with the applicable framework',
      'Contain no errors or misstatements',
    ],
    correctAnswer: 2,
    explanation:
      'An unmodified opinion states the financial statements are presented fairly, in all material respects, in accordance with the applicable financial reporting framework (e.g., U.S. GAAP).',
    reference: 'AU-C 700.35',
  },
  {
    id: 'aud-rep-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Modified Opinions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A qualified opinion is appropriate when:',
    options: [
      'Misstatements are material but not pervasive',
      'The auditor cannot form an opinion',
      'Misstatements are material and pervasive',
      'The entity is not a going concern',
    ],
    correctAnswer: 0,
    explanation:
      'Qualified opinion: material but not pervasive misstatements or scope limitations. Adverse: material AND pervasive misstatements. Disclaimer: material AND pervasive scope limitations.',
    reference: 'AU-C 705.07',
  },
  {
    id: 'aud-rep-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Modified Opinions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When is an adverse opinion appropriate?',
    options: [
      'When misstatements are material and pervasive',
      'When the auditor cannot obtain sufficient evidence',
      'When there is substantial doubt about going concern',
      'When there is a scope limitation',
    ],
    correctAnswer: 0,
    explanation:
      'An adverse opinion is issued when misstatements are both material AND pervasive to the financial statements - they are so significant that the statements are misleading.',
    reference: 'AU-C 705.08',
  },
  {
    id: 'aud-rep-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Emphasis of Matter',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An Emphasis of Matter paragraph is added when:',
    options: [
      'The auditor wants to draw attention to a matter appropriately presented in the financial statements',
      'The auditor wants to modify the opinion',
      'The financial statements depart from GAAP',
      'There is a scope limitation',
    ],
    correctAnswer: 0,
    explanation:
      'Emphasis of Matter draws attention to matters properly presented (e.g., significant uncertainty, subsequent event). It does not modify the opinion. Other Matter relates to non-FS matters.',
    reference: 'AU-C 706.06',
  },
  {
    id: 'aud-rep-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Going Concern',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question:
      'When there is substantial doubt about going concern but disclosure is adequate, the auditor:',
    options: [
      'Issues an adverse opinion',
      'Issues an unmodified opinion with an Emphasis of Matter paragraph',
      'Disclaims an opinion',
      'Issues a qualified opinion',
    ],
    correctAnswer: 1,
    explanation:
      'If going concern disclosure is adequate, an unmodified opinion is issued with an Emphasis of Matter (or separate section for SAS 134) drawing attention to the going concern uncertainty.',
    reference: 'AU-C 570.22',
  },

  // ==========================================
  // AREA 8: Other Engagements
  // ==========================================

  {
    id: 'aud-other-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-other',
    topic: 'Other Engagements',
    subtopic: 'Review Engagements',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A review provides what level of assurance?',
    options: [
      'Reasonable assurance (high)',
      'Absolute assurance',
      'Limited assurance (moderate)',
      'No assurance',
    ],
    correctAnswer: 2,
    explanation:
      'A review provides limited (moderate) assurance - less than an audit (reasonable/high) but more than a compilation (no assurance). The conclusion is negative form.',
    reference: 'AR-C 90.04',
  },
  {
    id: 'aud-other-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-other',
    topic: 'Other Engagements',
    subtopic: 'Review Engagements',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The report on a review engagement expresses:',
    options: [
      'A conclusion that nothing came to attention indicating statements are not fairly presented',
      'An opinion that financial statements are fairly presented',
      'Assurance that internal controls are effective',
      'A guarantee of the accuracy of the financial statements',
    ],
    correctAnswer: 0,
    explanation:
      'Review reports express negative assurance - "nothing came to our attention" rather than positive assurance that statements are fairly presented.',
    reference: 'AR-C 90.36',
  },
  {
    id: 'aud-other-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-other',
    topic: 'Other Engagements',
    subtopic: 'Compilation Engagements',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In a compilation engagement, the accountant:',
    options: [
      'Assists management in presenting financial statements without obtaining assurance',
      'Performs inquiry and analytical procedures',
      'Tests internal controls',
      'Obtains reasonable assurance',
    ],
    correctAnswer: 0,
    explanation:
      'A compilation involves assisting management in presenting financial information without obtaining assurance. No procedures are performed to verify accuracy.',
    reference: 'AR-C 80.04',
  },
  {
    id: 'aud-other-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-other',
    topic: 'Other Engagements',
    subtopic: 'Agreed-Upon Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An agreed-upon procedures (AUP) engagement results in:',
    options: [
      'A conclusion about subject matter',
      'An opinion on the financial statements',
      'A compilation report',
      'A report of findings without a conclusion or opinion',
    ],
    correctAnswer: 3,
    explanation:
      'AUP engagements report the specific procedures performed and findings. No opinion or conclusion is expressed - users draw their own conclusions from the findings.',
    reference: 'AT-C 215.04',
  },
  {
    id: 'aud-other-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-other',
    topic: 'Other Engagements',
    subtopic: 'SOC Reports',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A SOC 1 report is primarily intended for:',
    options: [
      'Regulatory compliance only',
      'User entities and their auditors to evaluate controls affecting financial reporting',
      'The general public',
      'Evaluating cybersecurity',
    ],
    correctAnswer: 1,
    explanation:
      "SOC 1 reports address controls at a service organization relevant to user entities' internal control over financial reporting. SOC 2 covers security, availability, confidentiality, etc.",
    reference: 'AT-C 320',
  },

  // Additional Questions
  {
    id: 'aud-rp-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Related Parties',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Audit procedures for related party transactions should include:',
    options: [
      'Ignoring immaterial related party transactions',
      'Relying solely on inquiry of management',
      "Accepting management's representations without corroboration",
      "Evaluating the business purpose and whether terms are equivalent to arm's length",
    ],
    correctAnswer: 3,
    explanation:
      "The auditor should evaluate the business rationale and whether transactions are at arm's length terms. Special procedures apply due to increased fraud risk.",
    reference: 'AU-C 550.19',
  },
  {
    id: 'aud-rp-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-planning',
    topic: 'Audit Planning and Risk Assessment',
    subtopic: 'Using the Work of Others',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Before using the work of internal auditors, the external auditor must evaluate:',
    options: [
      'Whether internal auditors are CPAs',
      "Only the internal audit department's budget",
      'The objectivity, competence, and work of the internal auditors',
      'Only whether the audit committee approves',
    ],
    correctAnswer: 2,
    explanation:
      'The external auditor evaluates the objectivity, technical competence, and systematic approach of internal auditors before using their work.',
    reference: 'AU-C 610.11',
  },
  {
    id: 'aud-rp-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'IT Controls',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'General IT controls include all of the following EXCEPT:',
    options: [
      'Input validation checks on specific transactions',
      'Program change controls',
      'Computer operations controls',
      'Access security controls',
    ],
    correctAnswer: 0,
    explanation:
      'General IT controls (ITGCs) are pervasive: access security, change management, computer operations, and backup/recovery. Input validation is an application control, specific to a transaction type.',
    reference: 'AU-C 315.A115',
  },
  {
    id: 'aud-rp-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Comparative Statements',
    difficulty: 'medium',
    skillLevel: 'Application',
    question:
      "When a predecessor auditor's report is not reissued with comparative statements, the successor auditor:",
    options: [
      "Makes reference to the predecessor's audit in an Other Matter paragraph",
      'Must audit the prior period',
      'Issues an adverse opinion on comparative statements',
      'Declines the engagement',
    ],
    correctAnswer: 0,
    explanation:
      "If the predecessor's report is not reissued, the successor includes an Other Matter paragraph describing: that prior period was audited by another auditor, date of their report, opinion type, and reasons for modification if any.",
    reference: 'AU-C 700.56',
  },
];

export default AUD_QUESTIONS;
