// AUD World-Class MCQs - Exam Quality Questions
// CPA Exam style with detailed explanations and blueprint alignment

import { Question } from '../../../types';

export const AUD_QUESTIONS_WORLD_CLASS: Question[] = [
  // ==========================================
  // AREA I: ETHICS, INDEPENDENCE, AND PROFESSIONAL CONDUCT (15-25%)
  // ==========================================
  {
    id: 'aud-wc-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics',
    subtopic: 'Independence',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A CPA firm provides audit services to Client A. The CPA firm also provides bookkeeping services and prepares financial statements for Client A. Under AICPA rules, what safeguard is required to maintain independence?',
    options: [
      'Obtain written consent from the client',
      'Assign different partners to each engagement',
      'Independence is automatically impaired; firm must withdraw from audit',
      'Ensure management takes responsibility for the financial statements and has sufficient expertise',
    ],
    correctAnswer: 3,
    explanation: 'Nonattest services (like bookkeeping) for attest clients require: (1) client agrees to assume all management responsibilities, (2) client has member of management with sufficient expertise to oversee the service, (3) CPA does not make management decisions. These are the general requirements under AICPA\'s revised interpretation.',
    reference: 'AICPA Code ET 1.295',
  },
  {
    id: 'aud-wc-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics',
    subtopic: 'Independence Threats',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following creates a self-interest threat to independence?',
    options: [
      'Serving as an expert witness for an audit client',
      'Providing internal audit outsourcing services to an audit client',
      'Providing litigation support services to an audit client',
      'Having a direct financial interest in an audit client',
    ],
    correctAnswer: 3,
    explanation: 'Self-interest threat: member could benefit from a financial interest in the client. Direct financial interest (owning stock) creates a self-interest threat and impairs independence regardless of materiality. Litigation support = advocacy threat. Expert witness depends on context.',
    reference: 'AICPA Conceptual Framework',
  },
  {
    id: 'aud-wc-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-ethics',
    topic: 'Ethics',
    subtopic: 'Covered Members',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which of the following individuals is NOT generally considered a "covered member" under AICPA independence rules?',
    options: [
      'An individual in a position to influence the engagement',
      'A partner in the same office who does not provide services to the client',
      'The engagement partner',
      'A staff accountant on the audit engagement team',
    ],
    correctAnswer: 1,
    explanation: 'Covered members include: individuals on the attest engagement team, those in a position to influence the engagement, partners/managers who provide nonattest services to the client, and the firm. A partner in the same office who has no connection to the client is not automatically a covered member.',
    reference: 'AICPA Code ET 0.400.04',
  },
  {
    id: 'aud-wc-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-professional',
    topic: 'Professional Conduct',
    subtopic: 'PCAOB Independence',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under PCAOB rules for audits of issuers, what is the cooling-off period for a former audit engagement team member before they can accept employment at an audit client in a financial reporting oversight role?',
    options: [
      'One year',
      'No cooling-off period required',
      'Two years',
      'Six months',
    ],
    correctAnswer: 0,
    explanation: 'PCAOB/SEC independence rules: One-year cooling-off period before someone who served on the audit engagement team can be employed by the audit client in a financial reporting oversight role (CEO, CFO, controller, etc.).',
    reference: 'SEC Rule 2-01(c)',
  },
  {
    id: 'aud-wc-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    topicId: 'aud-quality',
    topic: 'Quality Management',
    subtopic: 'SQMS',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under SQMS No. 1, what is the firm required to establish to address quality risks?',
    options: [
      'A single quality control partner',
      'Annual external inspections',
      'Written policies signed by all staff',
      'A system of quality management with responses to quality risks',
    ],
    correctAnswer: 3,
    explanation: 'SQMS No. 1 requires firms to design and implement a system of quality management (SQM) that includes: establishing quality objectives, identifying and assessing quality risks, and designing and implementing responses to address those risks. It\'s a risk-based approach.',
    reference: 'SQMS No. 1',
  },
  // ==========================================
  // AREA II: ASSESSING RISK AND DEVELOPING A PLANNED RESPONSE (20-30%)
  // ==========================================
  {
    id: 'aud-wc-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-planning',
    topic: 'Planning',
    subtopic: 'Materiality',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When establishing performance materiality, the auditor should set it at an amount:',
    options: [
      'Equal to overall materiality',
      'Lower than overall materiality to reduce the risk of undetected misstatements',
      'Based solely on the client\'s request',
      'Higher than overall materiality to reduce audit risk',
    ],
    correctAnswer: 1,
    explanation: 'Performance materiality is set at less than overall materiality to reduce the probability that the aggregate of uncorrected and undetected misstatements exceeds materiality. It accounts for the risk of undetected misstatements.',
    reference: 'AU-C 320.09',
  },
  {
    id: 'aud-wc-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-planning',
    topic: 'Risk Assessment',
    subtopic: 'Significant Risks',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which of the following is automatically considered a significant risk requiring special audit consideration?',
    options: [
      'Prepaid insurance',
      'Accounts receivable balances',
      'Depreciation expense',
      'Revenue recognition',
    ],
    correctAnswer: 3,
    explanation: 'AU-C 240 presumes that revenue recognition is a fraud risk (significant risk). The auditor must specifically address this presumption. Not all revenue recognition involves significant risk, but the auditor must evaluate and document their consideration.',
    reference: 'AU-C 240.27',
  },
  {
    id: 'aud-wc-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Limitations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following is an inherent limitation of internal control?',
    options: [
      'Insufficient documentation',
      'Lack of written policies',
      'Collusion among employees',
      'Inadequate segregation of duties',
    ],
    correctAnswer: 2,
    explanation: 'Inherent limitations of internal control include: human judgment errors, management override, collusion, and cost-benefit constraints. Collusion can circumvent even well-designed controls. Lack of policies or segregation are control deficiencies, not inherent limitations.',
    reference: 'AU-C 315.A54',
  },
  {
    id: 'aud-wc-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Control Deficiencies',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A significant deficiency in internal control is one that:',
    options: [
      'Always requires modification of the audit opinion',
      'Involves fraud by senior management',
      'Results in a material misstatement in the financial statements',
      'Is less severe than a material weakness but merits attention by those charged with governance',
    ],
    correctAnswer: 3,
    explanation: 'Significant deficiency: control deficiency (or combination) that is less severe than a material weakness but important enough to merit attention by those charged with governance. Material weakness: reasonable possibility of material misstatement not being prevented/detected.',
    reference: 'AU-C 265.07',
  },
  {
    id: 'aud-wc-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-fraud',
    topic: 'Fraud',
    subtopic: 'Fraud Triangle',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following is a component of the fraud triangle?',
    options: [
      'Competence',
      'Compliance',
      'Negligence',
      'Opportunity',
    ],
    correctAnswer: 3,
    explanation: 'The fraud triangle consists of: (1) Incentive/Pressure (reason to commit fraud), (2) Opportunity (ability to commit fraud), and (3) Rationalization (justification for the act). Auditors consider these when assessing fraud risk.',
    reference: 'AU-C 240.A1',
  },
  {
    id: 'aud-wc-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-fraud',
    topic: 'Fraud',
    subtopic: 'Fraud Response',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When the auditor suspects fraud involving senior management, the auditor should:',
    options: [
      'Expand testing until the fraud is confirmed or refuted',
      'Notify the SEC directly',
      'Immediately resign from the engagement',
      'Evaluate the implications and communicate with those charged with governance',
    ],
    correctAnswer: 3,
    explanation: 'When senior management may be involved in fraud, the auditor should: (1) evaluate implications for the audit, (2) consider need for legal advice, (3) communicate with those charged with governance (like the audit committee), and (4) consider effect on auditor\'s report.',
    reference: 'AU-C 240.40',
  },
  // ==========================================
  // AREA III: PERFORMING FURTHER PROCEDURES AND OBTAINING EVIDENCE (30-40%)
  // ==========================================
  {
    id: 'aud-wc-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Reliability',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following provides the most reliable audit evidence?',
    options: [
      'Internal documents prepared by the client',
      'Analytical review of trends',
      'Oral inquiry of management',
      'Confirmation from a third party',
    ],
    correctAnswer: 3,
    explanation: 'Audit evidence reliability hierarchy: External evidence > Internal evidence when controls are effective. Confirmations from independent third parties are highly reliable. Oral representations from management are least reliable.',
    reference: 'AU-C 500.A31',
  },
  {
    id: 'aud-wc-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Assertions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Testing whether all inventory that should be recorded has been recorded addresses which assertion?',
    options: [
      'Valuation',
      'Rights and obligations',
      'Existence',
      'Completeness',
    ],
    correctAnswer: 3,
    explanation: 'Completeness = all transactions/items that should be recorded ARE recorded (nothing omitted). Existence = items recorded actually exist. For completeness, test from source documents TO records. For existence, test from records TO supporting evidence.',
    reference: 'AU-C 315.A128',
  },
  {
    id: 'aud-wc-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Procedures',
    subtopic: 'Tests of Details',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which audit procedure would be most effective for testing the completeness assertion for accounts payable?',
    options: [
      'Confirm selected payables with vendors',
      'Review subsequent cash disbursements and match to year-end payables',
      'Vouch recorded payables to supporting invoices',
      'Trace payments after year-end to recorded liabilities',
    ],
    correctAnswer: 1,
    explanation: 'Completeness of payables: Start with UNRECORDED items and trace to records. Reviewing subsequent disbursements (after year-end) for items that should have been recorded as A/P at year-end is effective. Confirmations and vouching test existence, not completeness.',
    reference: 'AU-C 500',
  },
  {
    id: 'aud-wc-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Sample Size',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In an attributes sampling plan, which factor, if increased, would result in a larger required sample size?',
    options: [
      'Risk of assessing control risk too low',
      'Expected population deviation rate',
      'Population size when less than 250 items',
      'Tolerable deviation rate',
    ],
    correctAnswer: 1,
    explanation: 'Larger sample required when: (1) expected deviation rate INCREASES, (2) tolerable rate DECREASES (lower tolerance = more precision needed), (3) risk of assessing control risk too low DECREASES (want more assurance). Higher expected deviation rate means more testing needed.',
    reference: 'AU-C 530.A10',
  },
  {
    id: 'aud-wc-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Substantive Sampling',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In monetary-unit sampling (MUS), what is the primary advantage?',
    options: [
      'It can be used for qualitative testing',
      'It always results in smaller sample sizes',
      'It eliminates the need for stratification',
      'It automatically focuses on larger dollar items',
    ],
    correctAnswer: 3,
    explanation: 'MUS (PPS sampling) uses individual dollars as sampling units. Larger accounts are more likely to be selected (proportional to size). This automatically focuses on higher-risk items without manual stratification. It\'s efficient for testing for overstatement.',
    reference: 'AU-C 530.A14',
  },
  {
    id: 'aud-wc-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Inventory',
    subtopic: 'Observation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The primary purpose of observing inventory counts is to:',
    options: [
      'Detect inventory shortages and shrinkage',
      'Test the client\'s cutoff procedures',
      'Verify the client\'s perpetual inventory records',
      'Obtain evidence about the existence and condition of inventory',
    ],
    correctAnswer: 3,
    explanation: 'Physical observation provides evidence about existence (inventory is there) and condition (quality, obsolescence). While cutoff can be tested simultaneously, the primary purpose is to confirm the inventory physically exists and is in usable condition.',
    reference: 'AU-C 501.04',
  },
  {
    id: 'aud-wc-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Receivables',
    subtopic: 'Confirmations',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a client refuses to allow the auditor to confirm receivables, and alternative procedures cannot provide sufficient appropriate evidence, the auditor should:',
    options: [
      'Accept the client\'s explanation and proceed',
      'Report the client to the SEC',
      'Consider the effect on the auditor\'s report, potentially a qualified or disclaimer',
      'Resign from the engagement immediately',
    ],
    correctAnswer: 2,
    explanation: 'If confirmations cannot be sent and alternative procedures are inadequate, this is a scope limitation. The auditor must evaluate the effect on the opinion—qualified opinion or disclaimer of opinion depending on materiality and pervasiveness.',
    reference: 'AU-C 505.09',
  },
  {
    id: 'aud-wc-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Substantive Analytics',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following conditions must be met for analytical procedures to be used as the principal substantive test for an assertion?',
    options: [
      'The auditor must have low assessed risk of material misstatement',
      'The account balance must be immaterial',
      'The relationship being analyzed must be precise and predictable',
      'Analytical procedures can always be used as the sole source of evidence',
    ],
    correctAnswer: 2,
    explanation: 'Substantive analytical procedures are effective when: (1) the relationship is plausible and predictable, (2) data is reliable, (3) expectation is precise enough to identify misstatements. For assertions with low precision relationships, other substantive tests are needed.',
    reference: 'AU-C 520.05',
  },
  {
    id: 'aud-wc-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-written-rep',
    topic: 'Written Representations',
    subtopic: 'Required Representations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Management\'s written representations are obtained to:',
    options: [
      'Replace other audit evidence',
      'Shift liability from the auditor to management',
      'Guarantee the accuracy of the financial statements',
      'Confirm oral representations and provide evidence about matters not observable',
    ],
    correctAnswer: 3,
    explanation: 'Written reps confirm oral representations made to the auditor and provide evidence about matters that are judgmental or not otherwise directly testable (like intent to hold investments, completeness of related party disclosures). They do NOT replace other evidence.',
    reference: 'AU-C 580.03',
  },
  {
    id: 'aud-wc-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-related-parties',
    topic: 'Related Parties',
    subtopic: 'Procedures',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When the auditor identifies a related party transaction that was not previously disclosed by management, the auditor should:',
    options: [
      'Accept management\'s explanation and continue',
      'Report the finding to the SEC',
      'Immediately issue an adverse opinion',
      'Evaluate why the transaction was not disclosed and whether there may be other undisclosed transactions',
    ],
    correctAnswer: 3,
    explanation: 'Undisclosed related party transactions may indicate: (1) management lack of awareness, (2) deficiency in controls, or (3) intentional concealment. The auditor should evaluate implications, consider if other undisclosed transactions exist, and assess impact on F/S and fraud risk.',
    reference: 'AU-C 550.20',
  },
  // ==========================================
  // AREA IV: FORMING CONCLUSIONS AND REPORTING (15-25%)
  // ==========================================
  {
    id: 'aud-wc-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Opinion Types',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An auditor should express a qualified opinion when:',
    options: [
      'There is substantial doubt about going concern',
      'The auditor lacks independence',
      'There is a material and pervasive departure from GAAP',
      'There is a material but not pervasive departure from GAAP or scope limitation',
    ],
    correctAnswer: 3,
    explanation: 'Qualified: material but NOT pervasive. Uses "except for" language. Adverse: material AND pervasive misstatement. Disclaimer: unable to obtain sufficient evidence AND pervasive scope limitation. Going concern doubt with proper disclosure may result in emphasis paragraph, not modification.',
    reference: 'AU-C 705.07',
  },
  {
    id: 'aud-wc-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Adverse Opinion',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When issuing an adverse opinion, where does the auditor describe the reasons for the adverse opinion?',
    options: [
      'In the basis for adverse opinion paragraph',
      'In the opinion paragraph only',
      'In a separate letter to management',
      'In an emphasis of matter paragraph',
    ],
    correctAnswer: 0,
    explanation: 'For modified opinions (qualified, adverse, disclaimer), the report includes a "Basis for [Qualified/Adverse/Disclaimer of] Opinion" paragraph that describes the matter(s) giving rise to the modification. This precedes the opinion paragraph.',
    reference: 'AU-C 705.22',
  },
  {
    id: 'aud-wc-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Group Audits',
    subtopic: 'Component Auditors',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a group engagement team uses the work of a component auditor, the group auditor:',
    options: [
      'Can disclaim responsibility for the component auditor\'s work',
      'Must re-perform all of the component auditor\'s work',
      'Is not required to communicate with the component auditor',
      'Remains responsible for the overall audit opinion',
    ],
    correctAnswer: 3,
    explanation: 'The group engagement partner is responsible for the group audit opinion. The group auditor must evaluate component auditor competence, supervise or review their work, and be involved in risk assessment. The group auditor cannot disclaim responsibility for components.',
    reference: 'AU-C 600.11',
  },
  {
    id: 'aud-wc-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Subsequent Events',
    subtopic: 'Types',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A customer who was a defendant in a lawsuit settled the case for a significant amount after year-end but the lawsuit was filed before year-end. This is:',
    options: [
      'A Type II subsequent event—disclose only',
      'Not a subsequent event',
      'Requires a disclaimer of opinion',
      'A Type I subsequent event—adjust the financial statements',
    ],
    correctAnswer: 3,
    explanation: 'Type I (recognized): Condition existed at balance sheet date. The lawsuit was pending at year-end; the settlement provides additional evidence about the conditions that existed. Adjust F/S. Type II (non-recognized): Condition arose after balance sheet date—disclose only.',
    reference: 'AU-C 560.09',
  },
  {
    id: 'aud-wc-026',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Going Concern',
    subtopic: 'Substantial Doubt',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If management\'s plans are expected to mitigate substantial doubt about going concern, but a material uncertainty remains, what should the auditor do?',
    options: [
      'Resign from the engagement',
      'Issue an unmodified opinion with no additional paragraphs',
      'Issue a qualified opinion',
      'Issue an unmodified opinion with an emphasis of matter paragraph',
    ],
    correctAnswer: 3,
    explanation: 'If substantial doubt is alleviated by management\'s plans but material uncertainty remains: Unmodified opinion with emphasis of matter paragraph highlighting the going concern uncertainty. If doubt is NOT alleviated and disclosure adequate: same treatment. If inadequate disclosure: modify opinion.',
    reference: 'AU-C 570.24',
  },
  {
    id: 'aud-wc-027',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-other',
    topic: 'Review Engagements',
    subtopic: 'Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In a review of financial statements, the accountant\'s primary procedures consist of:',
    options: [
      'Detailed testing and sampling',
      'Tests of controls and substantive tests',
      'Inquiry and analytical procedures',
      'Confirmation and observation',
    ],
    correctAnswer: 2,
    explanation: 'Review engagements primarily use: (1) inquiry of company personnel and (2) analytical procedures. Reviews provide limited (negative) assurance: "nothing came to our attention." Less extensive than an audit; more than a compilation.',
    reference: 'AR-C 90.24',
  },
  {
    id: 'aud-wc-028',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-IV',
    topic: 'Compilation',
    subtopic: 'Requirements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which statement accurately describes the level of assurance provided by a compilation engagement versus a review engagement?',
    options: [
      'Both provide the same limited assurance',
      'A compilation provides no assurance; a review provides limited (negative) assurance',
      'A compilation provides limited assurance; a review provides reasonable assurance',
      'Neither provides any assurance',
    ],
    correctAnswer: 1,
    explanation: 'A compilation engagement provides no assurance on the financial statements — the CPA assists in presenting financial information without verifying it. A review provides limited (negative) assurance through inquiry and analytical procedures. An audit provides reasonable (positive) assurance. These represent an assurance hierarchy: compilation < review < audit.',
    reference: 'AR-C 80.07',
  },
  {
    id: 'aud-wc-029',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-attestation',
    topic: 'Attestation',
    subtopic: 'Agreed-Upon Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In an agreed-upon procedures (AUP) engagement, the practitioner:',
    options: [
      'Provides negative assurance',
      'Must perform all procedures contemplated by GAAS',
      'Expresses an opinion on the subject matter',
      'Reports findings without providing an opinion or conclusion',
    ],
    correctAnswer: 3,
    explanation: 'AUP: Practitioner performs specific procedures agreed upon by specified parties and reports findings. No opinion or conclusion. Use is restricted to participating parties. The practitioner makes no representations about sufficiency of procedures.',
    reference: 'AT-C 215.02',
  },
  {
    id: 'aud-wc-030',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-attestation',
    topic: 'SOC Reports',
    subtopic: 'SOC 1 Reports',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A SOC 1 Type 2 report includes:',
    options: [
      'General use seal of approval',
      'Trust services criteria compliance only',
      'Description of controls and opinion on design only',
      'Description, design, and operating effectiveness over a period of time',
    ],
    correctAnswer: 3,
    explanation: 'SOC 1 Type 2: Report on controls at a service organization relevant to user entities\' internal control over financial reporting. Includes description of system, service auditor\'s opinion on design AND operating effectiveness over a specified period (usually 6-12 months).',
    reference: 'AT-C 320',
  },
  // Additional AUD questions
  {
    id: 'aud-wc-031',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-it',
    topic: 'IT Auditing',
    subtopic: 'IT General Controls',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following is an example of an IT general control?',
    options: [
      'Batch total verification',
      'Program change management procedures',
      'Three-way match for accounts payable',
      'Credit limit checks on customer orders',
    ],
    correctAnswer: 1,
    explanation: 'IT General Controls (ITGCs) are broad controls over the IT environment: access controls, program change management, operations, system development. Application controls are specific to transactions: three-way match, credit limits, batch totals.',
    reference: 'AU-C 315.A109',
  },
  {
    id: 'aud-wc-032',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-estimates',
    topic: 'Accounting Estimates',
    subtopic: 'Auditing Estimates',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When auditing an accounting estimate, which approach does NOT specifically address estimation uncertainty?',
    options: [
      'Evaluating management\'s estimate and the methods, assumptions, and data used',
      'Examining subsequent events that provide evidence about the estimate',
      'Agreeing the estimate to a third-party quote',
      'Developing an independent expectation of the estimate',
    ],
    correctAnswer: 2,
    explanation: 'Three approaches to auditing estimates: (1) test how management made the estimate, (2) develop an auditor\'s point estimate or range, (3) review subsequent events/transactions. Agreeing to a quote might be helpful but doesn\'t specifically address estimation uncertainty.',
    reference: 'AU-C 540.13',
  },
  {
    id: 'aud-wc-033',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-communication',
    topic: 'Communications',
    subtopic: 'TCWG',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which matter is the auditor required to communicate to those charged with governance?',
    options: [
      'Minor control deficiencies',
      'Significant findings from the audit, including qualitative aspects of accounting practices',
      'Names of audit team members',
      'All audit adjustments, whether recorded or not considered material',
    ],
    correctAnswer: 1,
    explanation: 'Required communications to TCWG include: auditor\'s responsibilities, planned scope/timing, significant findings, significant difficulties, disagreements with management, significant control deficiencies, and matters affecting independence.',
    reference: 'AU-C 260.12',
  },
  {
    id: 'aud-wc-034',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-I',
    topic: 'Professional Skepticism',
    subtopic: 'Application',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'During planning, an auditor determines that the client has a significant concentration of credit risk — 70% of accounts receivable comes from a single government agency. How should this affect the audit plan?',
    options: [
    'No effect — government agencies are low risk',
    'Increase the assessed risk for the receivables balance, confirm the receivable directly with the agency, evaluate the contract terms and payment history, and consider the impact on the going concern evaluation',
    'Reduce testing because government receivables rarely default',
    'Only disclose the concentration in the management letter',
    ],
    correctAnswer: 1,
    explanation: 'A concentration of credit risk (70% from one customer) is a significant risk factor regardless of the counterparty\'s creditworthiness. The auditor should: (1) assess heightened risk of material misstatement for collectibility, (2) directly confirm the balance, (3) review the contract and appropriation status, (4) evaluate payment history and aging, (5) consider going concern if the relationship is at risk, and (6) ensure adequate disclosure under ASC 825.',
    reference: 'AU-C 200.16',
  },
  {
    id: 'aud-wc-035',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Documentation',
    subtopic: 'Assembly',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under SAS requirements, the auditor must assemble the final audit documentation file within:',
    options: [
      '90 days after the report release date',
      '30 days after the report release date',
      '60 days after the report release date',
      '45 days after the report release date',
    ],
    correctAnswer: 2,
    explanation: 'AICPA standards: 60 days after report release date to assemble final file. PCAOB standards for issuers: 45 days. Administrative completion only; no new conclusions or evidence added during this period.',
    reference: 'AU-C 230.14',
  },
  {
    id: 'aud-wc-036',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-II',
    topic: 'Engagement Acceptance',
    subtopic: 'Predecessor Auditor',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An auditor is testing the existence of fixed assets at a large manufacturing facility with thousands of individual items. The fixed asset register shows 4,500 items totaling $85 million. Which direction of testing is most appropriate for the existence assertion?',
    options: [
    'Select items from the physical location and trace to the fixed asset register',
    'Select items from the fixed asset register and physically inspect them at the facility',
    'Analytically compare the total fixed asset balance to the prior year',
    'Confirm fixed asset balances with the company\'s insurance provider',
    ],
    correctAnswer: 1,
    explanation: 'Testing existence requires verifying that recorded items actually exist. The proper direction is from the records (fixed asset register) to the physical assets — selecting recorded items and physically inspecting them. Going from physical items to the register tests completeness (whether all items are recorded), not existence. This directional testing concept is fundamental to substantive audit procedures.',
    reference: 'AU-C 210.11',
  },
  {
    id: 'aud-wc-037',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-reporting',
    topic: 'Comparative Statements',
    subtopic: 'Different Auditors',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When prior period comparative financial statements were audited by a predecessor auditor whose report is not reissued, what should the current auditor do?',
    options: [
      'Re-audit the prior period statements',
      'Omit the comparative statements',
      'Issue a disclaimer on the prior period',
      'Reference the predecessor\'s report in an other matter paragraph',
    ],
    correctAnswer: 3,
    explanation: 'If predecessor\'s report is not reissued, the current auditor should include an other matter paragraph stating: prior period was audited by predecessor, date of predecessor\'s report, opinion type, and any modification reasons. The current auditor does not take responsibility for prior period.',
    reference: 'AU-C 700.36',
  },
  {
    id: 'aud-wc-038',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Legal Letters',
    subtopic: 'Attorney Letters',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When an attorney refuses to respond to an inquiry letter for a litigation, claims, and assessments audit inquiry, the auditor should:',
    options: [
      'Omit any reference to litigation in the financial statements',
      'Report the attorney to the state bar association',
      'Accept management\'s representations as sufficient',
      'Consider the effect on the audit, potentially issuing a scope limitation',
    ],
    correctAnswer: 3,
    explanation: 'Attorney letter is key audit evidence for litigation/claims. Refusal to respond (or significantly limited response) is a scope limitation. The auditor must evaluate the effect on the opinion—may require qualification or disclaimer depending on materiality.',
    reference: 'AU-C 501.11',
  },
  {
    id: 'aud-wc-039',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Tests of Controls',
    subtopic: 'Nature',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Tests of controls are performed to:',
    options: [
      'Determine the reasonableness of accounting estimates',
      'Confirm account balances with third parties',
      'Detect material misstatements in account balances',
      'Evaluate the operating effectiveness of controls in preventing or detecting misstatements',
    ],
    correctAnswer: 3,
    explanation: 'Tests of controls evaluate whether controls are operating effectively. If controls are effective, auditor can reduce substantive testing. Tests of controls focus on HOW controls were applied, BY WHOM, and CONSISTENCY of application.',
    reference: 'AU-C 330.08',
  },
  {
    id: 'aud-wc-040',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Risk of Material Misstatement',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The auditor assesses the risk of material misstatement (RMM) at the financial statement level when:',
    options: [
      'The risk only affects revenue recognition',
      'The client has strong controls over financial reporting',
      'The risk relates to a specific account balance',
      'The risk is pervasive and potentially affects many assertions',
    ],
    correctAnswer: 3,
    explanation: 'Financial statement level risks are pervasive: affect multiple assertions/accounts, may not be attributable to specific assertions. Examples: management override, financial difficulties, poor control environment. Addressed through overall responses (more experienced staff, increased skepticism).',
    reference: 'AU-C 315.27',
  },
];

export default AUD_QUESTIONS_WORLD_CLASS;
