// AUD Depth Questions - Batch 3
// Focus: AUD-II (risk assessment), AUD-III (audit evidence & procedures), AUD-IV (reports)
// More easy/medium for balance

import { Question } from '../../../types';

export const AUD_QUESTIONS_DEPTH_3: Question[] = [
  // AUD-II: RISK ASSESSMENT
  {
    id: 'aud-d3-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Inherent Risk vs. Control Risk',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Inherent risk is the susceptibility of an assertion to a misstatement that could be material, assuming:',
    options: [
      'Internal controls are effective',
      'The financial statements have been audited',
      'There are no related internal controls (i.e., before considering internal control)',
      'The auditor has tested the controls',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §315 (Audit Risk Model): Audit Risk = Inherent Risk × Control Risk × Detection Risk. Inherent risk: susceptibility to material misstatement BEFORE considering internal controls. Factors: complexity of transactions, estimation uncertainty, susceptibility to fraud, industry factors, economic conditions. Control risk: risk that internal controls will NOT prevent or detect a material misstatement. Detection risk: risk that the auditor\'s procedures will NOT detect a material misstatement. The auditor controls detection risk by adjusting the nature, timing, and extent of substantive procedures.',
    reference: 'AU-C §315; AU-C §200',
  },
  {
    id: 'aud-d3-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Understanding Internal Control',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'COSO identifies five components of internal control. They are:',
    options: [
      'Authorization, recording, safeguarding, reconciliation, reporting',
      'Planning, executing, monitoring, reporting, concluding',
      'Control environment, risk assessment, control activities, information and communication, and monitoring activities',
      'Budgeting, staffing, training, compensation, evaluation',
    ],
    correctAnswer: 2,
    explanation: 'COSO Internal Control Framework (2013): (1) Control Environment — "tone at the top," integrity, ethics, governance, organizational structure, accountability. (2) Risk Assessment — identifying and assessing risks to objectives (including fraud risk). (3) Control Activities — policies and procedures: authorizations, verifications, reconciliations, segregation of duties, IT controls. (4) Information and Communication — generating relevant, quality information and communicating it internally and externally. (5) Monitoring Activities — ongoing evaluations, separate evaluations, and remediation of deficiencies. These are the basis for auditor\'s understanding of internal control (AU-C §315).',
    reference: 'COSO Framework (2013); AU-C §315',
  },
  {
    id: 'aud-d3-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Fraud Risk Factors',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C §240, the "fraud triangle" consists of three conditions generally present when fraud occurs:',
    options: [
      'Incentive/pressure, opportunity, and rationalization/attitude',
      'Intent, knowledge, and capability',
      'Greed, opportunity, rationalization',
      'Motive, means, and access',
    ],
    correctAnswer: 0,
    explanation: 'AU-C §240 (Fraud): Fraud triangle: (1) Incentive/Pressure — management or employees have a reason to commit fraud (financial pressure, bonus targets, debt covenants). (2) Opportunity — conditions allow fraud to be committed (weak internal controls, override by management, complex transactions). (3) Rationalization/Attitude — the fraudster justifies the behavior ("I\'ll pay it back," "I deserve it"). Two types of fraud relevant to the audit: (a) Fraudulent financial reporting — intentional misstatement (e.g., revenue overstatement), (b) Misappropriation of assets — theft. Revenue recognition is a presumed fraud risk. Management override of controls is always a significant risk.',
    reference: 'AU-C §240.25',
  },
  {
    id: 'aud-d3-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Materiality',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Performance materiality is set by the auditor:',
    options: [
      'At zero',
      'At an amount less than overall materiality to reduce the risk that the aggregate of undetected and uncorrected misstatements exceeds overall materiality',
      'Equal to overall materiality',
      'Higher than overall materiality',
    ],
    correctAnswer: 1,
    explanation: 'AU-C §320 (Materiality): Performance materiality = one or more amounts set at less than overall materiality. Purpose: reduce the probability that the total of undetected misstatements + uncorrected known misstatements exceeds overall materiality. Typically 50-75% of overall materiality. Example: if overall materiality is $100K, performance materiality might be $60K-$75K. The auditor uses performance materiality to: (1) determine the nature, timing, and extent of further audit procedures, (2) select items for testing, (3) evaluate misstatements identified. Materiality benchmarks: 5% of pre-tax income, 0.5-1% of revenue, 1-2% of total assets.',
    reference: 'AU-C §320',
  },

  // AUD-III: AUDIT EVIDENCE
  {
    id: 'aud-d3-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Sufficiency and Appropriateness',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The two dimensions of audit evidence are:',
    options: [
      'Cost and benefit',
      'Sufficiency (quantity — enough evidence) and appropriateness (quality — relevance and reliability)',
      'Primary and secondary',
      'Internal and external',
    ],
    correctAnswer: 1,
    explanation: 'AU-C §500 (Audit Evidence): Sufficiency = quantity (enough evidence). Affected by: (1) Risk of material misstatement (higher risk → more evidence), (2) Quality of evidence (higher quality → less needed). Appropriateness = quality, comprising: (1) Relevance — relates to the assertion being tested, (2) Reliability — factors: source (external > internal), nature (documentary > oral), conditions under which obtained (internal controls effective → more reliable), direct auditor knowledge > indirect. Evidence generated externally is generally more reliable than internally generated evidence. Evidence obtained directly by the auditor (e.g., inspection, observation) is more reliable than indirectly obtained (e.g., inquiry).',
    reference: 'AU-C §500',
  },
  {
    id: 'aud-d3-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Confirmation Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A positive confirmation request asks the respondent to:',
    options: [
      'Respond in ALL cases — either agreeing or disagreeing with the information provided (or providing the requested information)',
      'Respond only if they disagree with the balance',
      'Send payment directly to the auditor',
      'Call the auditor if there is a problem',
    ],
    correctAnswer: 0,
    explanation: 'AU-C §505 (External Confirmations): Positive confirmation: respondent must reply in ALL cases. Two forms: (1) Blank form — respondent fills in the balance (more reliable but lower response rate), (2) Balance included — respondent agrees/disagrees with stated amount. Negative confirmation: respondent replies ONLY if they disagree (less reliable — non-response could mean agreement or ignoring the request). Used when: assessed risk of material misstatement is low, large number of small balances, low exception rate expected. Positive confirmations provide stronger evidence than negative. If no response to positive confirmation: perform alternative procedures.',
    reference: 'AU-C §505',
  },
  {
    id: 'aud-d3-007',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-III',
    topic: 'Audit Evidence',
    subtopic: 'Analytical Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An auditor notices that a client\'s gross margin is 42% while the industry average is 35%. Which type of analytical procedure would the auditor most likely use to investigate this difference?',
    options: [
      'Vouching sales invoices to customer purchase orders',
      'Comparing disaggregated revenue and cost data by product line or business segment',
      'Sending confirmations to all major customers',
      'Performing a physical inventory count',
    ],
    correctAnswer: 1,
    explanation: 'Analytical procedures at the disaggregated level (by product line, segment, or location) are more effective at identifying unusual relationships than company-wide ratios. A higher-than-industry gross margin could stem from product mix, pricing strategy, or potential revenue overstatement. Disaggregated analysis helps the auditor narrow the investigation to specific areas.',
    reference: 'AU-C §315, §520',
  },

  // AUD-III: SPECIFIC PROCEDURES
  {
    id: 'aud-d3-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Audit Evidence',
    subtopic: 'Inventory Observation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For inventory, the auditor is required to:',
    options: [
      'Count all inventory items personally',
      'Skip inventory if it is immaterial',
      'Attend the physical inventory count, observe count procedures, inspect inventory, and perform test counts to evaluate the completeness and accuracy of the entity\'s count records',
      'Only review management\'s records',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §501 (Inventory): If inventory is material: (1) Attend the physical inventory count (unless impracticable — then alternative procedures), (2) Observe management\'s count procedures, (3) Inspect inventory (condition, existence), (4) Perform test counts — select items from the count sheets and locate in inventory (completeness), and select items from the floor and trace to count sheets (existence), (5) Evaluate count instructions and procedures. If the auditor cannot attend (e.g., inventory at a remote warehouse): alternative procedures (subsequent count, rollback testing, third-party confirmation). First-year audit: may need to observe a physical count even for beginning inventory.',
    reference: 'AU-C §501.03-.10',
  },
  {
    id: 'aud-d3-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Audit Evidence',
    subtopic: 'Related Parties',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'AU-C §550 requires the auditor to:',
    options: [
      'Ignore related-party transactions if management says they are immaterial',
      'Report all related parties to the SEC',
      'Identify related parties and related-party transactions, evaluate whether they have been properly accounted for and disclosed, and assess risks of material misstatement arising from related-party relationships',
      'Only ask management if there are related parties',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §550 (Related Parties): Risk assessment: understand the entity\'s related-party relationships and transactions. Procedures: (1) Inquire of management regarding related parties (identification), (2) Review board/committee minutes, (3) Review SEC filings (10-K proxy), (4) Review large/unusual transactions, (5) Review confirmations for related-party transactions, (6) Review accounting records for previously unidentified related parties. Evaluate: proper accounting treatment, adequate disclosure (names of parties, nature of relationship, amounts, terms). Related-party transactions may not be at arm\'s length — elevated fraud risk.',
    reference: 'AU-C §550',
  },

  // AUD-II: IT CONTROLS
  {
    id: 'aud-d3-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-it',
    topic: 'Risk Assessment',
    subtopic: 'IT General Controls',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'IT general controls (ITGCs) typically include controls over:',
    options: [
      'Only email communication',
      'Only payroll processing',
      'Program change management, logical access (user access and security), computer operations (job scheduling, backup/recovery), and program development',
      'Only physical access to the building',
    ],
    correctAnswer: 2,
    explanation: 'ITGCs (IT General Controls): Foundational controls that support the reliable functioning of IT application controls. Categories: (1) Program change management — ensuring changes to applications are properly authorized, tested, and implemented, (2) Logical access/security — user authentication, authorization, password policies, segregation of duties in IT systems, (3) Computer operations — job scheduling, backup/restoration, incident management, (4) Program development — SDLC controls, testing, approval. If ITGCs are weak: cannot rely on IT application controls (automated controls within applications, like three-way match in AP). ITGCs affect ALL applications — pervasive impact on the audit.',
    reference: 'AU-C §315; COSO ICIF',
  },

  // AUD-III: SAMPLING
  {
    id: 'aud-d3-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Evidence',
    subtopic: 'Statistical vs. Non-Statistical Sampling',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The key difference between statistical and non-statistical sampling in auditing is that statistical sampling:',
    options: [
      'Always provides better results',
      'Does not require professional judgment',
      'Uses random selection and probability theory to evaluate results, allowing the auditor to quantify sampling risk; non-statistical uses professional judgment for selection and evaluation',
      'Is required by GAAS for all audits',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §530 (Audit Sampling): Statistical sampling: (1) Random selection (every item has a known, non-zero probability of selection), (2) Probability theory to evaluate results (quantify sampling risk). Non-statistical sampling: (1) Judgmental selection (haphazard, block, etc.), (2) Professional judgment to evaluate results (cannot quantify sampling risk). Both are acceptable under GAAS. Sampling risk: risk that the auditor\'s conclusion based on a sample differs from the conclusion if the entire population were tested. Non-sampling risk: risk of incorrect conclusion for reasons other than sampling (e.g., applying wrong procedure, failing to recognize a misstatement).',
    reference: 'AU-C §530',
  },
  {
    id: 'aud-d3-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Evidence',
    subtopic: 'Attribute Sampling',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In tests of controls, attribute sampling is used to estimate:',
    options: [
      'The inherent risk of an assertion',
      'The rate of deviation (departure) from a prescribed control procedure in a population',
      'The dollar amount of misstatements in a population',
      'The net present value of a control',
    ],
    correctAnswer: 1,
    explanation: 'Attribute sampling: used in tests of controls. Goal: estimate the deviation rate (how often the control fails). Key concepts: (1) Expected population deviation rate — the rate the auditor expects based on prior experience, (2) Tolerable rate of deviation — maximum rate the auditor can accept while still relying on the control, (3) Allowable risk of overreliance — risk that the sample deviation rate is less than the actual population rate (typically 5% or 10%). If the sample deviation rate < tolerable rate = control is effective (can rely). If sample deviation rate ≥ tolerable rate = control is not effective (increase substantive testing). Variables sampling is used for substantive testing (dollars).',
    reference: 'AU-C §530',
  },

  // AUD-II: ENGAGEMENT PLANNING
  {
    id: 'aud-d3-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-planning',
    topic: 'Risk Assessment',
    subtopic: 'Engagement Letter',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An audit engagement letter should include:',
    options: [
      'The objective and scope of the audit, the responsibilities of the auditor and management, the applicable financial reporting framework, the expected form and content of reports, and a reference to the inherent limitations of an audit',
      'A guarantee that fraud will be detected',
      'Only the fee',
      'Only the start date',
    ],
    correctAnswer: 0,
    explanation: 'AU-C §210 (Terms of Engagement): Required contents of the engagement letter: (1) Objective and scope of the audit, (2) Auditor\'s responsibilities (GAAS, reasonable assurance, not absolute), (3) Management\'s responsibilities (preparation of financial statements, internal control, access to information), (4) Identification of the applicable financial reporting framework (GAAP, IFRS, etc.), (5) Expected form and content of reports, (6) Statement that the audit is not designed to detect all fraud or error. Also typically includes: fee arrangement, timing, access to records. New engagement letters are recommended each year but can be renewed/updated.',
    reference: 'AU-C §210',
  },

  // AUD-III: USING SPECIALISTS
  {
    id: 'aud-d3-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-specialist',
    topic: 'Audit Evidence',
    subtopic: 'Using the Work of a Specialist',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When the auditor uses the work of an auditor\'s specialist (AU-C §620), the auditor should:',
    options: [
      'Evaluate the specialist\'s competency, capabilities, and objectivity; evaluate the adequacy of the specialist\'s work for the auditor\'s purposes; the auditor remains responsible for the opinion',
      'Blindly accept the specialist\'s findings',
      'Delegate the audit opinion to the specialist',
      'Include the specialist\'s name in the audit report',
    ],
    correctAnswer: 0,
    explanation: 'AU-C §620 (Using an Auditor\'s Specialist): The auditor may use a specialist when expert knowledge is needed (e.g., actuaries for pension liabilities, appraisers for FMV, engineers for environmental remediation). Auditor\'s responsibilities: (1) Evaluate competence, capabilities, and objectivity of the specialist, (2) Obtain understanding of the specialist\'s field, (3) Evaluate the adequacy and reasonableness of the specialist\'s work and conclusions, (4) The auditor is SOLELY responsible for the audit opinion — using a specialist does not reduce that responsibility, (5) The specialist\'s name should NOT be referenced in the auditor\'s report (unless modified opinion and reference is relevant).',
    reference: 'AU-C §620',
  },

  // AUD-II: SIGNIFICANT RISKS
  {
    id: 'aud-d3-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Significant Risks',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A significant risk is an identified risk of material misstatement that:',
    options: [
      'Is always quantitatively material',
      'Requires special audit consideration because of its nature — such as fraud risk, complex transactions, high estimation uncertainty, or unusual significant transactions',
      'Requires no additional audit procedures',
      'Is always immaterial',
    ],
    correctAnswer: 1,
    explanation: 'AU-C §315.28-.30 (Significant Risks): Identified risks that require special audit consideration. Factors: (1) Risk of fraud, (2) Related to recent significant economic/accounting developments, (3) Complexity of transactions, (4) Significant transactions with related parties, (5) High degree of subjectivity (fair value estimates, revenue recognition). For significant risks: (1) The auditor must obtain an understanding of the entity\'s controls related to the risk, (2) Substantive procedures must be specifically responsive to the risk, (3) Cannot rely solely on prior-period evidence. Revenue recognition and management override of controls are PRESUMED significant risks.',
    reference: 'AU-C §315.28-.30; AU-C §240',
  },

  // AUD-III: JOURNAL ENTRY TESTING
  {
    id: 'aud-d3-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-fraud',
    topic: 'Audit Evidence',
    subtopic: 'Testing Journal Entries',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'To address the presumed risk of management override of controls, the auditor must:',
    options: [
      'Only review the trial balance',
      'Test the appropriateness of journal entries (including adjusting entries and entries made through the consolidation process), review accounting estimates for bias, and evaluate business rationale for significant unusual transactions',
      'Only test automated entries',
      'Ask management if they committed fraud',
    ],
    correctAnswer: 1,
    explanation: 'AU-C §240.32-.34 (Management Override): Three required procedures: (1) Test journal entries — select journal entries and adjustments (especially those made at the end of the period, entries by unusual users, non-standard entries, round-number entries), (2) Review accounting estimates for bias — retrospective review of significant estimates (compare prior estimates to actual results, look for systematic bias), (3) Evaluate business rationale for significant unusual transactions — outside the normal course of business, or appear unusual given the auditor\'s understanding of the entity. These three procedures are required regardless of the assessed risk of material misstatement because management override is always a significant risk.',
    reference: 'AU-C §240.32-.34',
  },

  // AUD-III: AUDIT ASSERTIONS
  {
    id: 'aud-d3-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-assertions',
    topic: 'Audit Evidence',
    subtopic: 'Financial Statement Assertions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The assertion of "completeness" means that:',
    options: [
      'All calculations are mathematically correct',
      'All disclosures are exactly correct',
      'All transactions, events, assets, liabilities, and equity interests that should have been recorded and disclosed have been included in the financial statements',
      'The financial statements are free of fraud',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §315 — Assertions: Categories: (1) Transactions & Events: Occurrence (it happened), Completeness (all recorded), Accuracy (correct amounts), Cutoff (correct period), Classification (proper accounts). (2) Account Balances at Period End: Existence (it exists), Rights & Obligations (entity owns/owes it), Completeness (all included), Valuation & Allocation (proper amounts). (3) Presentation & Disclosure: Occurrence & Rights, Completeness, Classification & Understandability, Accuracy & Valuation. Completeness is often tested by tracing from source documents TO the accounting records (vs. existence which vouches FROM records to support).',
    reference: 'AU-C §315.A128',
  },

  // AUD-II: PREDECESSOR AUDITOR
  {
    id: 'aud-d3-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-planning',
    topic: 'Risk Assessment',
    subtopic: 'Communication with Predecessor Auditor',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Before accepting a new audit engagement, the successor auditor is required to:',
    options: [
      'File a report with the SEC about the change',
      'Review all prior workpapers',
      'Communicate with the predecessor auditor (with client permission) to inquire about matters relevant to the acceptance decision, such as disagreements with management, integrity issues, or reasons for the change',
      'Accept the engagement without any inquiries',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §210.10 / AU-C §510 (Opening Balances): Before acceptance: (1) The successor MUST communicate with the predecessor (requires client\'s consent), (2) Inquire about: reasons for the change, disagreements with management on accounting/auditing issues, management integrity, audit problems in prior engagements. If the client refuses to grant permission: the successor should consider the implications for accepting the engagement. After acceptance: (1) Review predecessor\'s workpapers (if access granted), (2) Consider the impact of prior-year opinion on current-year financial statements (especially opening balances). The predecessor should respond promptly and fully (unless legal restrictions).',
    reference: 'AU-C §210; AU-C §510',
  },

  // AUD-III: SUBSEQUENT EVENTS PROCEDURES
  {
    id: 'aud-d3-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-subsequent',
    topic: 'Audit Evidence',
    subtopic: 'Procedures for Subsequent Events',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'To identify subsequent events, the auditor should perform which procedures through the date of the auditor\'s report?',
    options: [
      'No specific procedures are required',
      'Only inquire of management',
      'Read minutes of board meetings, inquire of management about subsequent events, review latest interim financial statements, read entity\'s latest available information, and obtain written representations',
      'Only read the minutes',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §560 (Subsequent Events): Required procedures performed through the report date: (1) Read minutes of meetings of owners, management, and those charged with governance held after the balance sheet date (and inquire about minutes of meetings for which minutes are not yet available), (2) Inquire of management about: new commitments/borrowings/guarantees, sales/dispositions/acquisitions of assets, increases in capital/debt, unusual adjustments, (3) Read latest available interim financial statements (if available), (4) Inquire of entity\'s legal counsel about litigation/claims, (5) Obtain written representations (management rep letter dated on the report date).',
    reference: 'AU-C §560.09-.10',
  },

  // AUD-II: AUDIT STRATEGY
  {
    id: 'aud-d3-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-planning',
    topic: 'Risk Assessment',
    subtopic: 'Overall Audit Strategy vs. Audit Plan',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The overall audit strategy differs from the audit plan in that the strategy:',
    options: [
      'Contains all detailed testing procedures',
      'Replaces the need for an audit plan',
      'Sets the scope, timing, and direction of the audit and guides the development of the more detailed audit plan; the audit plan describes the nature, timing, and extent of specific audit procedures',
      'Is only prepared for large engagements',
    ],
    correctAnswer: 2,
    explanation: 'AU-C §300 (Planning): Overall audit strategy: high-level document that sets: (1) Scope of the audit, (2) Timing of the audit (interim vs. year-end procedures), (3) Direction — overall approach, significant areas, use of specialists, resource allocation, supervision. Audit plan: more detailed than the strategy — describes: (1) Nature, timing, and extent of risk assessment procedures, (2) Nature, timing, and extent of further audit procedures (tests of controls and substantive procedures) at the assertion level, (3) Other planned procedures required by GAAS. Both may be updated and changed as the audit progresses. Planning is iterative — it continues throughout the engagement.',
    reference: 'AU-C §300',
  },

  // AUD-III: TESTING DIRECTIONS
  {
    id: 'aud-d3-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Directional Testing — Existence vs. Completeness',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'To test the existence/occurrence assertion for accounts receivable, the auditor would:',
    options: [
      'Select items FROM the accounts receivable listing (or general ledger) and vouch to supporting documentation (invoices, shipping documents, customer confirmations)',
      'Only review the allowance for doubtful accounts',
      'Trace from shipping documents to the sales journal',
      'Select items from shipping documents and trace to the ledger',
    ],
    correctAnswer: 0,
    explanation: 'Directional testing: Existence/Occurrence: Start FROM the financial statement item (the recorded balance or transaction) and go BACK to supporting evidence. Goal: are recorded amounts real? (Overstatement concern.) For AR: select from the AR listing → confirm with customers or vouch to invoices/shipping documents. Completeness: Start FROM source documents and trace FORWARD to the financial statements. Goal: are all items included? (Understatement concern.) For AR: select from shipping documents → trace to sales journal → trace to AR listing. Rights & Obligations: verify the entity owns or is obligated for the amount (title documents, contracts).',
    reference: 'AU-C §500; AU-C §505',
  },

  // AUD-II: LAWS & REGULATIONS
  {
    id: 'aud-d3-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-compliance',
    topic: 'Risk Assessment',
    subtopic: 'Consideration of Laws and Regulations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C §250, when the auditor becomes aware of noncompliance with laws and regulations, the auditor must:',
    options: [
      'Obtain an understanding of the nature of the act and circumstances, evaluate the effect on the financial statements, discuss with management and those charged with governance, and consider the implications for the audit',
      'Resign immediately',
      'Immediately report to law enforcement',
      'Ignore it if it does not affect the financial statements',
    ],
    correctAnswer: 0,
    explanation: 'AU-C §250 (Laws and Regulations): Two categories: (1) Laws with a direct and material effect on financial statement amounts (e.g., tax laws, pension laws) — auditor must obtain evidence of compliance, (2) Other laws — auditor is not responsible for detecting noncompliance but must be alert to information suggesting noncompliance. When noncompliance identified: (1) Understand the nature, (2) Evaluate financial statement impact, (3) Discuss with management/governance, (4) Consider legal advice, (5) Evaluate implications for the audit (reliability of management representations, fraud risk), (6) Consider reporting obligations (may have legal requirement to report, e.g., to regulators).',
    reference: 'AU-C §250',
  },

  // AUD-III: WORKING PAPERS
  {
    id: 'aud-d3-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Evidence',
    subtopic: 'Audit Documentation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Audit documentation (working papers) should be sufficient to enable:',
    options: [
      'Only the SEC to review the work',
      'An experienced auditor, having no previous connection with the audit, to understand the nature, timing, and extent of procedures performed, evidence obtained, and conclusions reached',
      'Only the engagement partner to understand the work',
      'Only the client to review the work',
    ],
    correctAnswer: 1,
    explanation: 'AU-C §230 (Audit Documentation): Documentation must enable an experienced auditor with no prior connection to understand: (1) Nature, timing, and extent of procedures performed, (2) Results of procedures and evidence obtained, (3) Significant matters arising and conclusions reached, (4) Who performed the work and when, and who reviewed the work and when. Assembly/archival: complete the final audit file within 60 days after the report release date (PCAOB: 45 days). Retention: 5 years for non-issuers (AICPA), 7 years for issuers (PCAOB). After assembly, documents cannot be deleted or discarded (but additions with documentation of the reasons are permitted).',
    reference: 'AU-C §230',
  },

  // AUD-II: INTERNAL AUDIT
  {
    id: 'aud-d3-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal',
    topic: 'Risk Assessment',
    subtopic: 'Using the Work of Internal Auditors',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When the external auditor plans to use the work of internal auditors, the external auditor should evaluate:',
    options: [
      'Nothing — internal auditor work can always be used',
      'The competence, objectivity, and systematic/disciplined approach of the internal audit function, then determine the nature and extent of the internal auditor\'s work that can be used',
      'Only the internal audit budget',
      'Only the internal auditors\' educational background',
    ],
    correctAnswer: 1,
    explanation: 'AU-C §610 (Using the Work of Internal Auditors): The external auditor may use internal auditor work for: (1) Obtaining audit evidence (risk assessment, tests of controls, substantive procedures), (2) Direct assistance (performing procedures under external auditor supervision). Evaluation factors: (1) Organizational status — reporting level (to audit committee = more objective), (2) Competence — qualifications, training, experience, (3) Objectivity — policies to maintain objectivity, (4) Systematic and disciplined approach — quality control, planning/documenting. The external auditor must evaluate and test the internal audit work being used. The external auditor is SOLELY responsible for the audit opinion.',
    reference: 'AU-C §610',
  },

  // AUD-III: ACCOUNTS PAYABLE COMPLETENESS
  {
    id: 'aud-d3-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Audit Evidence',
    subtopic: 'Search for Unrecorded Liabilities',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A "search for unrecorded liabilities" is an audit procedure that tests the _____ assertion for accounts payable:',
    options: [
      'Completeness',
      'Existence',
      'Valuation',
      'Rights and obligations',
    ],
    correctAnswer: 0,
    explanation: 'The primary risk for accounts payable is understatement (completeness). The search for unrecorded liabilities includes: (1) Examine subsequent cash disbursements — review checks/payments after year-end to determine if they relate to year-end liabilities, (2) Examine unmatched receiving reports — goods received before year-end without a corresponding recorded payable, (3) Examine unmatched vendor invoices received after year-end for pre-year-end charges, (4) Confirm payables (especially with known or significant vendors showing zero/low balances), (5) Inquire of management about unpaid bills. Compare to AR where the primary risk is overstatement (existence).',
    reference: 'AU-C §500, §330',
  },
];
