// AUD Depth Questions - Batch 7
// Focus: AUD-II (Assessing Risk and Developing a Response)
// Topics: Understanding the Entity, Internal Control, Risk Assessment Procedures  
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const AUD_QUESTIONS_DEPTH_7: Question[] = [
  {
    id: 'aud-d7-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-understanding-entity',
    topic: 'Understanding the Entity',
    subtopic: 'Required Understanding',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 315, the auditor is required to obtain an understanding of the entity and its environment, including all of the following EXCEPT:',
    options: [
      'The entity\'s industry, regulatory, and other external factors',
      'The entity\'s marketing campaign effectiveness metrics',
      'The entity\'s selection and application of accounting policies',
      'The entity\'s internal control relevant to the audit',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.11 requires the auditor to obtain an understanding of: (1) the entity\'s industry, regulatory, and other external factors; (2) the nature of the entity (operations, ownership, governance, investments, financing, financial reporting); (3) the entity\'s selection and application of accounting policies; (4) the entity\'s objectives, strategies, and related business risks; and (5) the measurement and review of the entity\'s financial performance. Internal control understanding is also required per AU-C 315.12. Marketing campaign effectiveness metrics are specific operational data, not part of the required understanding for risk assessment purposes.',
    reference: 'AU-C 315.11',
  },
  {
    id: 'aud-d7-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Components of Internal Control',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under the COSO framework referenced in AU-C 315, the five interrelated components of internal control are:',
    options: [
      'Planning, directing, controlling, staffing, organizing',
      'Control environment, risk assessment, control activities, information and communication, and monitoring activities',
      'Authorization, recording, custody, reconciliation, verification',
      'Prevention, detection, correction, compensation, direction',
    ],
    correctAnswer: 1,
    explanation: 'The COSO Internal Control — Integrated Framework (2013), referenced in AU-C 315, identifies five components: (1) Control environment — the tone at the top, organizational structure, commitment to integrity and ethical values; (2) Risk assessment — the entity\'s process for identifying and analyzing risks; (3) Control activities — policies and procedures to ensure directives are carried out (approvals, authorizations, reconciliations, segregation of duties); (4) Information and communication — systems that capture and exchange information; (5) Monitoring activities — ongoing evaluations and separate evaluations to assess internal control effectiveness.',
    reference: 'AU-C 315.A77; COSO 2013',
  },
  {
    id: 'aud-d7-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Control Environment',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following is the MOST important element of the control environment?',
    options: [
      'The physical security of the building',
      'Management\'s integrity, ethical values, and the tone at the top (including the board of directors\' oversight)',
      'The entity\'s accounting software',
      'The number of employees in the accounting department',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.A78 emphasizes that the control environment is the foundation for all other components of internal control. The most critical element is the tone at the top — management\'s commitment to integrity and ethical values, the board\'s active oversight, management\'s philosophy and operating style, organizational structure, and human resource policies. A weak control environment (e.g., management override, lack of board oversight, fraud by high-level executives) can undermine even well-designed control activities. The auditor assesses the control environment to determine whether it provides an appropriate foundation for the other components.',
    reference: 'AU-C 315.A78 through A84',
  },
  {
    id: 'aud-d7-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Segregation of Duties',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Proper segregation of duties requires that the functions of authorization, custody of assets, and recordkeeping be assigned to different individuals. Which situation represents a segregation of duties weakness?',
    options: [
      'The accounts payable clerk records transactions while the CFO approves payments',
      'The employee who receives cash also records the receipts in the accounting system and prepares the bank reconciliation',
      'The purchasing agent orders goods while the receiving department accepts delivery',
      'The payroll department processes payroll while HR approves timesheets',
    ],
    correctAnswer: 1,
    explanation: 'Having the same employee receive cash (custody), record receipts (recordkeeping), and prepare the bank reconciliation (authorization/review) violates all three elements of segregation of duties. This individual could misappropriate cash and conceal the theft by manipulating records and reconciliations. Proper segregation would assign cash handling to one person, recording to another, and bank reconciliation to a third. The other options describe appropriate segregation — separating the ordering function from receiving, and separating payroll processing from approval.',
    reference: 'AU-C 315.A100',
  },
  {
    id: 'aud-d7-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Inherent Risk vs. Control Risk',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 315, inherent risk is defined as:',
    options: [
      'The risk that the auditor\'s procedures will not detect a misstatement',
      'The susceptibility of an assertion to a misstatement that could be material, before considering any related controls',
      'The risk that a control will fail to prevent or detect a misstatement',
      'The overall risk of material misstatement in the financial statements',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.04(n) defines inherent risk as the susceptibility of a relevant assertion about a class of transactions, account balance, or disclosure to a misstatement that could be material, either individually or when aggregated, before consideration of any related controls. Inherent risk factors include complexity of transactions, degree of judgment involved, susceptibility to theft or fraud, and related party transactions. Control risk is the risk that a misstatement will not be prevented or detected by the entity\'s controls. Detection risk is the risk that the auditor\'s procedures will not detect a material misstatement.',
    reference: 'AU-C 315.04(n)',
  },
  {
    id: 'aud-d7-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Audit Risk Model',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The audit risk model is expressed as AR = IR × CR × DR. If auditors assess inherent risk at 80% and control risk at 50%, and desire an overall audit risk of 5%, what level of detection risk can be tolerated?',
    options: [
      '25.0%',
      '12.5%',
      '6.25%',
      '50.0%',
    ],
    correctAnswer: 1,
    explanation: 'Using the audit risk model: AR = IR × CR × DR. Solving for DR: DR = AR / (IR × CR) = 0.05 / (0.80 × 0.50) = 0.05 / 0.40 = 0.125 or 12.5%. This means the auditor must design substantive procedures to achieve a detection risk of 12.5% or less. A lower tolerable detection risk means the auditor needs more persuasive audit evidence (larger sample sizes, more procedures). The inverse relationship between the risk of material misstatement (IR × CR) and detection risk is fundamental — higher assessed RMM requires more extensive substantive testing.',
    reference: 'AU-C 315; AU-C 330',
  },
  {
    id: 'aud-d7-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Significant Risks',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 315, a significant risk is a risk of material misstatement that requires special audit consideration. Which of the following is presumed to be a significant risk?',
    options: [
      'Depreciation of fixed assets',
      'Revenue recognition',
      'Office supplies expense',
      'Prepaid insurance',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.26 and AU-C 315.28 establish a presumption that risks of material misstatement due to fraud include risks related to revenue recognition. This is a rebuttable presumption — the auditor must specifically evaluate whether revenue recognition gives rise to significant risks and document the basis for any conclusion that it does not. Other areas frequently identified as significant risks include: management override of controls (always a significant risk), related party transactions, unusual or complex transactions, significant estimates with high measurement uncertainty, and going concern considerations.',
    reference: 'AU-C 315.28; AU-C 240.26',
  },
  {
    id: 'aud-d7-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'IT General Controls',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'IT general controls (ITGCs) are controls over the information technology environment that support the effective functioning of application controls. ITGCs include all of the following EXCEPT:',
    options: [
      'Program change management controls',
      'Access security (logical and physical access to programs and data)',
      'Input validation controls that check data entry for completeness and accuracy',
      'Computer operations and system development controls',
    ],
    correctAnswer: 2,
    explanation: 'IT general controls (ITGCs) are broad controls that apply to the overall IT environment. They include: (1) program change management — ensuring changes to programs are properly authorized, tested, and approved; (2) access security — restricting logical and physical access to programs, data, and computer resources; (3) computer operations — job scheduling, backup/recovery, incident management; (4) system development — SDLC controls and program acquisition. Input validation controls (data entry edits, reasonableness checks) are application controls, not ITGCs. Application controls operate at the transaction level, while ITGCs support the reliability of application controls.',
    reference: 'AU-C 315.A111 through A116',
  },
  {
    id: 'aud-d7-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Risk Assessment Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 315, risk assessment procedures that the auditor must perform include:',
    options: [
      'Only inquiries of management',
      'Inquiries of management and others, analytical procedures, and observation and inspection',
      'Only analytical procedures',
      'Only testing of controls',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.06 requires the auditor to perform ALL THREE types of risk assessment procedures: (1) Inquiries of management and others within the entity (including those involved in the financial reporting process, internal audit, and legal counsel); (2) Analytical procedures (comparing financial data with expectations, identifying unusual trends or ratios); (3) Observation and inspection (observing entity operations, inspecting documents, reports, and records). These procedures are designed to provide a basis for identifying and assessing risks of material misstatement. They are required — the auditor cannot skip any of these categories.',
    reference: 'AU-C 315.06',
  },
  {
    id: 'aud-d7-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-materiality',
    topic: 'Materiality',
    subtopic: 'Performance Materiality',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 320, performance materiality is set at an amount:',
    options: [
      'Equal to overall materiality',
      'Lower than overall materiality, to reduce to an appropriately low level the probability that the aggregate of uncorrected and undetected misstatements exceeds overall materiality',
      'Higher than overall materiality',
      'Equal to the tolerable misstatement for individual accounts',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 320.09 defines performance materiality as the amount(s) set by the auditor at less than materiality for the financial statements as a whole, to reduce to an appropriately low level the probability that the aggregate of uncorrected and undetected misstatements exceeds materiality. Performance materiality recognizes that auditors test individual accounts and assertions — even if each individual misstatement is below account-level materiality, their sum could exceed overall materiality. Performance materiality is typically set at 50-75% of overall materiality, depending on the auditor\'s assessment of risk and experience with the client.',
    reference: 'AU-C 320.09',
  },
  {
    id: 'aud-d7-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-materiality',
    topic: 'Materiality',
    subtopic: 'Revision During Audit',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 320, if the auditor becomes aware of information during the audit that would have caused a different materiality amount to be established initially, the auditor should:',
    options: [
      'Ignore the new information and use the original materiality',
      'Revise materiality for the financial statements as a whole (and performance materiality) and evaluate whether additional audit procedures are necessary',
      'Withdraw from the engagement',
      'Issue a qualified opinion automatically',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 320.12 requires the auditor to revise materiality for the financial statements as a whole when the auditor becomes aware of information that would have caused a different amount to be established initially. This may occur when actual financial results differ significantly from preliminary estimates used to set materiality (e.g., revenue is much higher or lower than expected). If materiality is revised downward, the auditor must assess whether performance materiality needs revision and whether the nature, timing, and extent of further audit procedures remain appropriate — additional procedures may be required.',
    reference: 'AU-C 320.12 through 13',
  },
  {
    id: 'aud-d7-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Limitations of Internal Control',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Internal control, no matter how well designed, can only provide reasonable assurance of achieving the entity\'s objectives because of inherent limitations. Which of the following is an inherent limitation of internal control?',
    options: [
      'Controls can be designed to prevent all errors',
      'The possibility of management override of controls',
      'Controls eliminate the need for an audit',
      'Technology always prevents unauthorized access',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.A53 identifies inherent limitations of internal control that prevent even well-designed systems from providing absolute assurance: (1) Management override — management can circumvent controls they established; (2) Human error — mistakes in judgment, misunderstandings, carelessness, fatigue; (3) Collusion — individuals acting together to circumvent segregation of duties; (4) Cost-benefit constraints — the cost of a control should not exceed the benefit; (5) Unusual or nonroutine transactions may not be addressed by existing controls. Management override is considered the most significant limitation because it is difficult to detect through standard audit procedures.',
    reference: 'AU-C 315.A53',
  },
  {
    id: 'aud-d7-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-fraud',
    topic: 'Fraud Risk',
    subtopic: 'Fraud Triangle',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 240, the three conditions generally present when fraud occurs (the fraud triangle) are:',
    options: [
      'Opportunity, capability, and willingness',
      'Incentive/pressure, opportunity, and rationalization/attitude',
      'Motive, means, and method',
      'Planning, execution, and concealment',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.A1 describes the fraud triangle — three conditions that are generally present when fraud occurs: (1) Incentive/pressure — a reason to commit fraud (financial pressures, unrealistic performance targets, management compensation tied to aggressive targets); (2) Opportunity — circumstances that allow fraud to be committed (weak controls, lack of segregation of duties, management override, complex transactions); (3) Rationalization/attitude — the ability to justify the fraudulent behavior (entitlement mentality, "borrowing" funds, everyone does it). The auditor must inquire about these conditions during risk assessment and design procedures responsive to identified fraud risks.',
    reference: 'AU-C 240.A1',
  },
  {
    id: 'aud-d7-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-fraud',
    topic: 'Fraud Risk',
    subtopic: 'Management Override',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 240, the auditor must perform which procedures to address the presumed risk of management override of controls, regardless of the assessment of other fraud risks?',
    options: [
      'No specific procedures are required',
      'Test the appropriateness of journal entries and other adjustments, review accounting estimates for bias, and evaluate the business rationale for significant unusual transactions',
      'Only review the minutes of board meetings',
      'Only confirm receivables',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.32 requires three specific procedures to address the risk of management override, which is always present: (1) Test the appropriateness of journal entries recorded in the general ledger and other adjustments (especially those made at the end of the reporting period) — select entries based on characteristics of fraudulent entries; (2) Review accounting estimates for biases (hindsight review of prior-year estimates, assessment of current estimates for management bias); (3) Evaluate the business rationale for significant unusual transactions outside the normal course of business. These procedures are mandatory regardless of the auditor\'s overall fraud risk assessment.',
    reference: 'AU-C 240.32 through 34',
  },
  {
    id: 'aud-d7-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Assertions',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 315, financial statement assertions for classes of transactions and events include all of the following EXCEPT:',
    options: [
      'Occurrence',
      'Completeness',
      'Valuation and allocation',
      'Accuracy',
    ],
    correctAnswer: 2,
    explanation: 'AU-C 315.A124 categorizes assertions into three groups: (1) Transactions and Events: occurrence, completeness, accuracy, cutoff, classification; (2) Account Balances: existence, rights and obligations, completeness, valuation and allocation; (3) Presentation and Disclosure: occurrence and rights and obligations, completeness, classification and understandability, accuracy and valuation. Valuation and allocation is an assertion for account BALANCES (at period end), not for transactions and events during the period. For transactions, the analogous assertion is accuracy (amounts and data are recorded appropriately).',
    reference: 'AU-C 315.A124 through A127',
  },
  {
    id: 'aud-d7-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Communication of Control Deficiencies',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 265, the auditor must communicate significant deficiencies and material weaknesses in internal control to:',
    options: [
      'Only management',
      'Those charged with governance in writing, and management in writing (including both significant deficiencies and material weaknesses)',
      'The SEC directly',
      'Only the external legal counsel',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 265.09 through 11 requires the auditor to communicate: (1) Material weaknesses — in writing to those charged with governance (e.g., audit committee). (2) Significant deficiencies — in writing to those charged with governance. (3) Material weaknesses and significant deficiencies — also in writing to management. The written communication must be made no later than 60 days following the report release date. A material weakness is a deficiency where there is a reasonable possibility that a material misstatement will not be prevented or detected on a timely basis. A significant deficiency is less severe but important enough to merit attention.',
    reference: 'AU-C 265.09 through 11',
  },
  {
    id: 'aud-d7-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Response to Assessed Risks',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 330, overall responses to assessed risks of material misstatement at the financial statement level include:',
    options: [
      'Only increasing sample sizes',
      'Assigning more experienced staff, increasing professional skepticism, incorporating more unpredictability into audit procedures, and making changes to timing or nature of procedures',
      'Only performing more inquiries of management',
      'Reducing the scope of the audit',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 330.05 describes overall responses to assessed risks at the financial statement level (pervasive risks). These include: (1) emphasizing professional skepticism during the audit; (2) assigning more experienced staff or using specialists; (3) providing more supervision; (4) incorporating additional elements of unpredictability in selecting procedures (e.g., performing procedures at different locations or at unexpected times); (5) making general changes to the nature, timing, and extent of procedures (e.g., performing more procedures at year-end rather than at interim, using substantive procedures rather than tests of controls). These responses address broad-level risks that affect multiple assertions.',
    reference: 'AU-C 330.05',
  },
  {
    id: 'aud-d7-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Entity-Level Controls',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Entity-level controls that operate at a level of precision sufficient to prevent or detect material misstatements can:',
    options: [
      'Replace all substantive testing',
      'Allow the auditor to reduce the extent of transaction-level control testing and substantive procedures, though some substantive procedures are always required for significant account balances',
      'Eliminate the need for further audit procedures',
      'Serve as the sole basis for the audit opinion',
    ],
    correctAnswer: 1,
    explanation: 'Strong entity-level controls (such as a highly effective internal audit function, robust monitoring, strong control environment, and detailed management review of financial results) that operate at sufficient precision can reduce the extent of detailed testing. However, AU-C 330.18 requires that regardless of control risk assessment, the auditor must perform substantive procedures for each material class of transactions, account balance, and disclosure. Entity-level controls provide a foundation that supports (or undermines) transaction-level controls, but they cannot entirely replace substantive audit evidence for significant assertions.',
    reference: 'AU-C 330.18; AU-C 315',
  },
  {
    id: 'aud-d7-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-fraud',
    topic: 'Fraud Risk',
    subtopic: 'Fraud Inquiries',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 240, the auditor is required to make inquiries about fraud to:',
    options: [
      'Only the CEO',
      'Management (including appropriate levels), those charged with governance, and others within the entity (such as employees in areas with higher fraud risk)',
      'Only the internal auditors',
      'Only the entity\'s legal counsel',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.17 through 22 requires fraud inquiries of multiple parties: (1) Management — about their assessment of fraud risk, their knowledge of actual or suspected fraud, and fraud prevention programs; (2) Those charged with governance — about their oversight of management\'s fraud risk assessment and controls; (3) Internal auditors (if applicable) — about their knowledge of fraud or fraud risk; (4) Others within the entity — employees in areas with higher fraud risk, legal counsel, ethics officers, or others identified during the audit. This multi-level inquiry approach increases the likelihood of identifying fraud or fraud indicators that management alone might not disclose.',
    reference: 'AU-C 240.17 through 22',
  },
  {
    id: 'aud-d7-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Walkthroughs',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A walkthrough of a transaction processing system involves:',
    options: [
      'Observing the physical plant layout',
      'Tracing one or more transactions through the system from origination to recording in the financial records, including the related control points',
      'Reviewing only the IT system architecture diagram',
      'Reading the entity\'s policies and procedures manual only',
    ],
    correctAnswer: 1,
    explanation: 'A walkthrough involves tracing a transaction from inception (origination of a sales order, purchase requisition, etc.) through the entire processing cycle to its ultimate recording in the general ledger and financial statements. At each stage, the auditor identifies the controls in place, confirms the understanding of the transaction flow, and evaluates whether controls are designed effectively. Walkthroughs combine inquiry, observation, inspection, and reperformance. They are an efficient method for confirming the auditor\'s understanding of the transaction processing system and identifying where misstatements might occur.',
    reference: 'AU-C 315.A78',
  },
  {
    id: 'aud-d7-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Business Risks vs. Fraud Risks',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under AU-C 315, the auditor\'s understanding of business risks is important because:',
    options: [
      'All business risks create fraud risk',
      'Business risks may result in risks of material misstatement — management responses to business risks (or failure to address them) can give rise to misstatements or fraudulent activity',
      'Business risks are reported in the auditor\'s report',
      'Business risks determine the audit fee',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.A41 through A44 explains that business risks — risks resulting from conditions, events, or circumstances that could adversely affect the entity\'s ability to achieve its objectives — can lead to financial statement misstatements. For example: aggressive growth targets (business risk) may pressure management to overstate revenue (fraud risk); declining industry (business risk) may impair inventories or goodwill (misstatement risk); new regulatory requirements (business risk) may affect accounting treatments. The auditor identifies business risks to understand how they might translate into risks of material misstatement at the assertion level.',
    reference: 'AU-C 315.A41 through A44',
  },
  {
    id: 'aud-d7-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Monitoring Component',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The monitoring component of internal control involves:',
    options: [
      'Setting up new controls',
      'Ongoing and/or separate evaluations to assess whether each component of internal control is present and functioning, including the internal audit function',
      'Only external audit procedures',
      'Only management\'s review of financial statements',
    ],
    correctAnswer: 1,
    explanation: 'Under COSO 2013 and AU-C 315.A108 through A110, monitoring involves evaluating the quality of internal control performance over time. It includes: (1) Ongoing monitoring activities — built into normal operations (supervisory reviews of transaction processing, management reporting, automated system alerts); (2) Separate evaluations — periodic assessments by internal audit, self-assessments by management, or external evaluations. The internal audit function is a key monitoring mechanism. The entity should evaluate and communicate deficiencies identified through monitoring to those responsible for taking corrective action.',
    reference: 'AU-C 315.A108 through A110',
  },
  {
    id: 'aud-d7-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Linking Risks to Assertions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under AU-C 315.26, after identifying risks of material misstatement, the auditor must:',
    options: [
      'Immediately design substantive tests',
      'Relate the identified risks to what can go wrong at the relevant assertion level and consider whether the risks are significant enough to result in material misstatement',
      'Report the risks to the SEC',
      'Withdraw from the engagement if risks are high',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.26 requires the auditor to relate identified risks to assertions — determining which specific assertions (existence, completeness, accuracy, valuation, etc.) are affected. For example, a risk related to complex revenue contracts affects the occurrence, accuracy, and cutoff assertions for revenue. The auditor then assesses whether these risks are significant enough to result in a material misstatement — either individually or in aggregate. This linkage is essential because audit procedures (substantive tests and tests of controls) are designed and performed at the assertion level, not at the financial-statement level.',
    reference: 'AU-C 315.26 through 28',
  },
  {
    id: 'aud-d7-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-materiality',
    topic: 'Materiality',
    subtopic: 'Materiality Benchmarks',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'When determining overall materiality, auditors commonly use a percentage of an appropriate benchmark. Which is the most common benchmark for a for-profit entity?',
    options: [
      'Total assets',
      'Income from continuing operations before tax',
      'Total liabilities',
      'Number of employees',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 320.A7 through A10 identifies common benchmarks for determining materiality. For for-profit entities, the most common benchmark is income from continuing operations before tax (pretax income). Common percentages range from 3-7% of pretax income. Other benchmarks used include: total revenue (0.5-2%), total assets (0.5-2%), or total equity (1-5%). The selection depends on the entity\'s circumstances: revenue may be appropriate for entities with volatile earnings; total assets for capital-intensive industries; equity for financial institutions. The benchmark and percentage selected require professional judgment and should be documented.',
    reference: 'AU-C 320.A7 through A10',
  },
  {
    id: 'aud-d7-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk-assessment',
    topic: 'Risk Assessment',
    subtopic: 'Documentation of Risk Assessment',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 315.32, the auditor must document:',
    options: [
      'Only the final audit opinion',
      'The identified and assessed risks of material misstatement at the financial statement level and assertion level, and the basis for those assessments',
      'Only significant findings',
      'Only the materiality calculation',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 315.32 requires documentation of: (1) key elements of the understanding of the entity and its environment, including each COSO component of internal control; (2) the sources of information used; (3) risk assessment procedures performed; (4) the identified and assessed risks of material misstatement at both the financial statement level and the assertion level; and (5) the significant risks identified and whether the related controls have been evaluated. This documentation provides the foundation for designing further audit procedures (tests of controls and substantive procedures) and is essential for engagement quality review and regulatory inspection.',
    reference: 'AU-C 315.32',
  },
];
