// AUD Depth Questions - Batch 8
// Focus: AUD-II (Assessing Risk and Developing a Response)
// Topics: Audit Sampling, Analytical Procedures, Tests of Controls
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const AUD_QUESTIONS_DEPTH_8: Question[] = [
  {
    id: 'aud-d8-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Statistical vs. Nonstatistical',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 530, when using audit sampling, the auditor may use either statistical or nonstatistical sampling. The key distinction is:',
    options: [
      'Statistical sampling is always more accurate',
      'Statistical sampling uses probability theory to evaluate sample results and measure sampling risk; nonstatistical sampling uses the auditor\'s judgment',
      'Nonstatistical sampling is prohibited for public company audits',
      'Statistical sampling requires no judgment',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 530.05 distinguishes between statistical and nonstatistical sampling. Statistical sampling uses mathematical probability theory to design the sample and evaluate results, allowing the auditor to quantify sampling risk. Nonstatistical sampling relies on the auditor\'s professional judgment for sample selection and evaluation. Both approaches are acceptable under auditing standards — neither is inherently superior. Both require judgment in defining the population, selecting items, and evaluating results. The main advantage of statistical sampling is the ability to quantify confidence levels and precision.',
    reference: 'AU-C 530.05',
  },
  {
    id: 'aud-d8-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Sampling Risk',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Sampling risk is the risk that:',
    options: [
      'The auditor will make computational errors',
      'The auditor\'s conclusion based on a sample may differ from the conclusion that would be reached if the entire population were tested',
      'The sample will not be random',
      'The population is too small to sample',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 530.05(h) defines sampling risk as the risk that the auditor\'s conclusion based on a sample may be different from the conclusion if the same procedure were applied to the entire population. There are two types: (1) Risk of incorrect acceptance (beta risk) — concluding that a material misstatement does not exist when it actually does (affects audit effectiveness); (2) Risk of incorrect rejection (alpha risk) — concluding that a misstatement exists when it does not (affects audit efficiency). Sampling risk is distinct from non-sampling risk, which includes risks such as using inappropriate procedures, misinterpreting results, or failing to recognize misstatements.',
    reference: 'AU-C 530.05(h)',
  },
  {
    id: 'aud-d8-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Attribute Sampling',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Attribute sampling is primarily used for:',
    options: [
      'Estimating the dollar amount of account balances',
      'Tests of controls — to estimate the rate of deviation from a prescribed control procedure',
      'Measuring account balance overstatements',
      'Estimating inventory values',
    ],
    correctAnswer: 1,
    explanation: 'Attribute sampling is used in tests of controls to estimate the rate of deviation (error rate) from a prescribed control procedure in a population. The auditor: (1) determines the expected deviation rate; (2) sets the tolerable deviation rate (the maximum rate the auditor is willing to accept while still relying on the control); (3) sets the acceptable risk of overreliance; (4) determines the sample size; (5) evaluates whether the sample deviation rate exceeds the tolerable rate. If the sample deviation rate exceeds the tolerable rate, the auditor cannot rely on the control and must increase substantive testing. Variables sampling is used for substantive tests of account balances.',
    reference: 'AU-C 530.A14 through A17',
  },
  {
    id: 'aud-d8-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Sample Size Factors',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following would cause the auditor to INCREASE the sample size for a test of controls?',
    options: [
      'A higher tolerable deviation rate',
      'A lower tolerable deviation rate (the auditor can tolerate fewer control failures)',
      'A higher acceptable risk of overreliance',
      'A smaller population',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 530.A14, sample size for tests of controls is affected by: (1) Tolerable deviation rate — a LOWER tolerable rate requires a LARGER sample (the auditor needs more evidence to conclude the deviation rate is below the tight threshold); (2) Expected population deviation rate — a higher expected rate requires a larger sample; (3) Acceptable risk of overreliance — a LOWER risk (seeking more confidence) requires a larger sample; (4) Population size — generally has minimal effect unless the population is small. The inverse relationship between tolerable deviation rate and sample size is a key testing concept.',
    reference: 'AU-C 530.A14',
  },
  {
    id: 'aud-d8-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Variables Sampling',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The auditor uses monetary unit sampling (MUS) to test accounts receivable. MUS is particularly effective for detecting:',
    options: [
      'Understatement of balances',
      'Overstatement of balances, because larger items (higher dollar amounts) have a proportionally higher chance of selection',
      'Classification errors only',
      'Timing differences only',
    ],
    correctAnswer: 1,
    explanation: 'Monetary unit sampling (MUS, also called probability-proportional-to-size sampling) treats each individual dollar as a sampling unit. This means every dollar has an equal chance of selection, and larger accounts automatically have a higher probability of inclusion. This makes MUS particularly effective for testing existence/overstatement — large overstatements are likely to be caught because the overstated dollars have a higher selection probability. MUS is less effective for understatement testing because understated items have fewer dollars and a lower chance of selection. MUS is commonly used for receivables, inventory, and other asset accounts.',
    reference: 'AU-C 530.A20 through A22',
  },
  {
    id: 'aud-d8-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Required Phases',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under auditing standards, analytical procedures are required during which phases of the audit?',
    options: [
      'Only during planning',
      'During both planning (risk assessment) and as a final overall review near the end of the audit; they are optional as substantive procedures',
      'Only during the concluding phase',
      'During all three phases — planning, testing, and concluding — as mandatory procedures',
    ],
    correctAnswer: 1,
    explanation: 'Analytical procedures are REQUIRED at two points: (1) Planning/risk assessment (AU-C 315.06) — to identify unusual relationships and potential risks of material misstatement; (2) Final overall review (AU-C 520.06) — to assess whether the financial statements are consistent with the auditor\'s understanding of the entity (a final "smell test"). Analytical procedures used as substantive procedures during fieldwork (AU-C 520.05) are OPTIONAL — the auditor may choose to use them, but tests of details are an equally acceptable substantive approach.',
    reference: 'AU-C 315.06; AU-C 520.05 through 06',
  },
  {
    id: 'aud-d8-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Substantive Analytical Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When using substantive analytical procedures under AU-C 520, the auditor develops an expectation and investigates differences from that expectation. The expectation should be:',
    options: [
      'Based solely on the prior year\'s amounts',
      'Sufficiently precise to identify potential material misstatements, using reliable data and incorporating knowledge of the entity, industry, and relationships among accounts',
      'Based on management\'s budget only',
      'An exact replicate of the recorded amount',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 520.05 requires that when performing substantive analytical procedures, the auditor must: (1) develop an expectation of the recorded amount or ratio that is sufficiently precise to detect potential material misstatements; (2) determine the amount of difference from expectation that is acceptable (threshold); (3) compare the expectation to the recorded amount; (4) investigate differences exceeding the threshold. The expectation should use reliable data from independent sources (industry data, historical trends, interrelationships) and incorporate the auditor\'s understanding of the entity and its environment. Greater reliance on substantive analytical procedures requires greater precision in the expectation.',
    reference: 'AU-C 520.05',
  },
  {
    id: 'aud-d8-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'When Required',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 330, the auditor is required to test the operating effectiveness of controls when:',
    options: [
      'On every audit engagement',
      'When the auditor\'s risk assessment includes an expectation that controls are operating effectively (i.e., the auditor intends to rely on controls), OR when substantive procedures alone cannot provide sufficient appropriate audit evidence at the assertion level',
      'Only when the entity requests it',
      'Only for public companies',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 330.08 requires tests of controls in two situations: (1) When the auditor\'s risk assessment includes an expectation that controls are operating effectively — if the auditor plans to reduce the nature, timing, or extent of substantive procedures based on the effectiveness of controls, the auditor must test those controls; (2) When substantive procedures alone are insufficient — for certain assertions (e.g., completeness of revenue in automated systems), the auditor may be unable to obtain sufficient evidence without testing controls. If the auditor assesses control risk at maximum and performs only substantive procedures, tests of controls are not required.',
    reference: 'AU-C 330.08 through 09',
  },
  {
    id: 'aud-d8-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Types of Control Tests',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Tests of controls may include all of the following procedures EXCEPT:',
    options: [
      'Inquiry of entity personnel combined with other procedures',
      'Observation of the application of controls',
      'Confirmation of accounts receivable balances with third parties',
      'Reperformance of controls by the auditor',
    ],
    correctAnswer: 2,
    explanation: 'Tests of controls involve: (1) Inquiry — asking personnel how controls are performed (generally insufficient alone); (2) Observation — watching the control being applied; (3) Inspection — examining documents and records for evidence of control operation (e.g., verifying initials, approvals, reconciliation marks); (4) Reperformance — the auditor independently performs the control procedure to confirm it works as described. Confirmation of receivable balances is a substantive test of details (testing the existence/valuation assertion for an account balance), not a test of controls. Tests of controls evaluate whether controls are operating effectively; substantive tests evaluate account balances for misstatement.',
    reference: 'AU-C 330.10',
  },
  {
    id: 'aud-d8-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Interim Testing',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If the auditor tests controls at an interim date, the auditor must:',
    options: [
      'Assume the controls continued to operate effectively through year-end',
      'Obtain evidence about significant changes in controls after the interim date and determine additional evidence to cover the remaining period',
      'Repeat all control tests at year-end',
      'Issue a qualified opinion for the gap period',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 330.12 states that when controls are tested at an interim date, the auditor must: (1) obtain evidence about any significant changes in those controls subsequent to the interim period; (2) determine what additional audit evidence to obtain for the remaining period (from the interim date to period end). The auditor may extend the testing to cover the remaining period, make inquiries combined with observation or inspection, test controls for the remaining period, or determine whether the interim results remain relevant. The length of the remaining period, nature and extent of changes, and risk assessment all affect the approach.',
    reference: 'AU-C 330.12 through 13',
  },
  {
    id: 'aud-d8-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Final Overall Review',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The purpose of analytical procedures performed during the final overall review of the audit is to:',
    options: [
      'Replace substantive testing',
      'Assist the auditor in forming an overall conclusion about whether the financial statements are consistent with the auditor\'s understanding of the entity',
      'Identify all remaining adjustments',
      'Determine the exact amount of unrecorded misstatements',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 520.06 requires analytical procedures near the end of the audit to assist the auditor in forming an overall conclusion. These procedures are a "big picture" review — comparing financial statements to expectations and identifying any unusual relationships or unexpected fluctuations not previously addressed. If the analytical procedures identify material inconsistencies or unexpected results, the auditor must investigate and may need to perform additional procedures. This is NOT a substitute for substantive testing already performed — it serves as a final reasonableness check before issuing the opinion.',
    reference: 'AU-C 520.06',
  },
  {
    id: 'aud-d8-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Selection Methods',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 530, acceptable sample selection methods include all of the following EXCEPT:',
    options: [
      'Random selection',
      'Systematic selection (every nth item)',
      'Selecting only the largest items',
      'Haphazard selection',
    ],
    correctAnswer: 2,
    explanation: 'AU-C 530.A13 identifies acceptable sample selection methods: (1) Random selection — every item has a known probability of selection (e.g., using random number generators); (2) Systematic selection — selecting every nth item after a random starting point; (3) Haphazard selection — selecting items without any conscious bias (no structured selection but attempting to give all items a chance). Selecting ONLY the largest items is NOT sampling — it is a judgmental selection of specific items. While testing high-value items is a valid audit procedure, it is distinct from sampling because it does not allow the auditor to project results to the entire population.',
    reference: 'AU-C 530.A13',
  },
  {
    id: 'aud-d8-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Dual-Purpose Tests',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A dual-purpose test is one that:',
    options: [
      'Tests two different client locations simultaneously',
      'Simultaneously serves as a test of controls (evaluating operating effectiveness) and a substantive test of details (evaluating the correctness of a dollar amount)',
      'Uses two different sampling methods',
      'Is performed by two auditors independently',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 330.A20, a dual-purpose test combines a test of controls and a substantive test of details in a single procedure applied to the same sample. For example, inspecting a sales invoice to: (1) verify that proper credit approval was obtained (test of control — authorization control); AND (2) verify the accuracy of the recorded amount (substantive test — accuracy assertion). Dual-purpose tests are efficient but the auditor must consider the objectives of each test separately when evaluating results. A control deviation does not necessarily mean a monetary misstatement, and vice versa.',
    reference: 'AU-C 330.A20',
  },
  {
    id: 'aud-d8-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Tolerable Misstatement',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In substantive testing, tolerable misstatement for a specific account is typically set at an amount:',
    options: [
      'Equal to overall materiality',
      'No larger than performance materiality, to allow for undetected misstatements in other accounts',
      'Higher than overall materiality',
      'Equal to zero',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 530.A3 notes that tolerable misstatement for an individual account is the application of performance materiality to a particular sampling procedure. It should not exceed performance materiality (which is already set below overall materiality). The reason: the auditor tests multiple accounts, and each may contain some misstatement. Tolerable misstatement must be set low enough that the sum of all undetected misstatements across all accounts does not exceed overall materiality. The tolerable misstatement for a specific account may be equal to or less than performance materiality, depending on the auditor\'s judgment about the account\'s risk.',
    reference: 'AU-C 530.A3',
  },
  {
    id: 'aud-d8-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Predictive Value and Precision',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The precision of a substantive analytical procedure depends on several factors. Which of the following would INCREASE the precision (and therefore the audit evidence value) of the procedure?',
    options: [
      'Using aggregated annual data rather than monthly data',
      'Using disaggregated data (by segment, product line, or month) and developing expectations using independent, reliable data sources',
      'Using only management\'s representations as the basis for the expectation',
      'Performing the procedure at a high level without investigating differences',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 520.A5 identifies factors that increase precision: (1) Disaggregation — breaking data into smaller components (by segment, location, product line, month) produces more precise expectations because unusual amounts are more visible; (2) Independent data sources — expectations based on independent external data (industry statistics, market data) are more reliable than entity-prepared data; (3) Predictable relationships — some relationships (e.g., commission expense ÷ revenue) are inherently more predictable; (4) More detailed analysis — using multiple financial and non-financial variables increases precision. Aggregated annual data reduces precision because misstatements can be obscured by offsetting amounts.',
    reference: 'AU-C 520.A5',
  },
  {
    id: 'aud-d8-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Impact on Substantive Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'If the auditor\'s tests of controls reveal a higher-than-expected deviation rate, the auditor should:',
    options: [
      'Issue a qualified opinion immediately',
      'Increase the assessed risk of material misstatement and modify the nature, timing, and extent of substantive procedures accordingly',
      'Accept the higher deviation rate and continue as planned',
      'Report the deficiency to the SEC',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 330.16, if tests of controls indicate that controls are not operating as effectively as initially assumed (higher deviation rate than tolerable), the auditor must revise the assessed risk of material misstatement upward. This requires modifying the planned substantive procedures — typically: (1) increasing the extent (larger sample sizes); (2) changing the nature (testing details rather than using analytical procedures); (3) changing the timing (more testing at year-end rather than interim). The auditor may also need to communicate control deficiencies under AU-C 265 if the deviation represents a significant deficiency or material weakness.',
    reference: 'AU-C 330.16 through 17',
  },
  {
    id: 'aud-d8-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Evaluating Results',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'After completing a substantive test using sampling, the auditor finds misstatements in the sample. The auditor should:',
    options: [
      'Only report the misstatements found in the sample',
      'Project the misstatements found in the sample to the population, evaluate whether the projected misstatement (plus an allowance for sampling risk) exceeds tolerable misstatement, and consider the qualitative aspects of the misstatements',
      'Ignore the misstatements if they are individually immaterial',
      'Expand the sample until zero misstatements are found',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 530.14 through 15, after testing, the auditor must: (1) Project sample misstatements to the population (e.g., if the sample represents 10% of the population and contains $5,000 in misstatements, the projected misstatement is $50,000); (2) Consider the sampling risk — the projected misstatement plus an allowance for sampling risk is compared to tolerable misstatement; (3) Evaluate qualitative aspects (nature of misstatements, whether they indicate fraud, potential pattern); (4) If projected misstatement exceeds tolerable misstatement, the auditor either expands testing or requests that management adjust. Individually immaterial items cannot be ignored because they may indicate systematic problems.',
    reference: 'AU-C 530.14 through 15',
  },
  {
    id: 'aud-d8-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Common Ratios',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'When performing analytical procedures, which ratio would be most useful for assessing the reasonableness of bad debt expense?',
    options: [
      'Debt-to-equity ratio',
      'Ratio of bad debt expense to credit sales (or to accounts receivable), compared to prior years and industry benchmarks',
      'Current ratio',
      'Inventory turnover',
    ],
    correctAnswer: 1,
    explanation: 'The ratio of bad debt expense to credit sales (or to accounts receivable) provides a direct and logical relationship for assessing reasonableness. If this ratio changes significantly from prior years or differs from industry norms, it may indicate a potential misstatement. Analytical procedures are most useful when they exploit predictable relationships between related accounts. Bad debt expense is directly related to credit sales and receivables. The debt-to-equity ratio, current ratio, and inventory turnover address different assertions and accounts (capital structure, liquidity, and inventory management respectively).',
    reference: 'AU-C 520',
  },
  {
    id: 'aud-d8-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Rotation of Control Testing',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under AU-C 330, the auditor may use evidence about the operating effectiveness of controls obtained in prior audits. If the auditor plans to rely on controls tested in a prior period:',
    options: [
      'No additional work is needed',
      'The auditor must test the controls at least once every third audit and must evaluate whether changes have occurred since the controls were last tested',
      'The controls must be retested every year without exception',
      'The auditor can rely on prior-year results indefinitely',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 330.14 allows the auditor to use evidence from prior audits about control effectiveness, but with limitations: (1) Controls should be tested at least once every three audits — some controls must be tested in the current period; (2) The auditor must obtain evidence about whether significant changes have occurred in those controls since they were last tested (through inquiry, observation, or inspection); (3) For significant risks, controls must be tested in the current period — prior-period evidence alone is insufficient; (4) The rotation approach should test some controls each year, not defer all testing to one year. If changes have occurred, the controls must be retested.',
    reference: 'AU-C 330.14',
  },
  {
    id: 'aud-d8-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Stratification',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Stratification of a population before sampling is used to:',
    options: [
      'Increase sampling risk',
      'Reduce the variability of items within each stratum, thereby potentially reducing the overall sample size needed to achieve the desired precision',
      'Eliminate the need for sampling',
      'Make the sample less representative',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 530.A8 describes stratification as dividing a population into subpopulations (strata) with similar characteristics. Common stratification approaches include dividing by dollar value (high, medium, low), by location, or by type of transaction. Stratification reduces the variability within each stratum, which can result in a smaller overall sample size to achieve the same level of precision. For example, accounts receivable might be stratified into large (test 100%), medium (sample), and small (sample) balances. This ensures that high-risk or high-value items receive appropriate attention.',
    reference: 'AU-C 530.A8',
  },
  {
    id: 'aud-d8-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Automated Controls',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When testing the operating effectiveness of an automated (IT-dependent) control, the auditor typically:',
    options: [
      'Tests every transaction processed by the control',
      'Tests the control once and also tests the related IT general controls (ITGCs), because a properly functioning automated control performs consistently',
      'Relies solely on management\'s testing',
      'Cannot gain assurance from automated controls',
    ],
    correctAnswer: 1,
    explanation: 'Automated controls, by their nature, perform consistently each time they execute — they do not suffer from human fatigue, judgment errors, or inconsistency. Therefore, once the auditor confirms that an automated control is properly designed and implemented (by testing one or a few instances), the key question becomes whether the control has remained unchanged. This is addressed by testing the IT general controls (ITGCs) — specifically, program change management and access security controls. If ITGCs are effective (ensuring no unauthorized changes to programs or data), the auditor can rely on a limited test of the automated control itself.',
    reference: 'AU-C 330.A28',
  },
  {
    id: 'aud-d8-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Investigation Threshold',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When performing substantive analytical procedures, the auditor establishes a threshold (amount of acceptable difference from expectation). If the recorded amount exceeds this threshold:',
    options: [
      'The auditor automatically issues a qualified opinion',
      'The auditor investigates the difference by inquiring of management and performing additional procedures to determine whether it represents a misstatement',
      'The difference is ignored as immaterial',
      'The auditor accepts management\'s explanation without further investigation',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 520.07 requires the auditor to investigate differences between the recorded amount and the expectation that exceed the established threshold. Investigation procedures include: (1) inquiring of management about the cause of the difference; (2) evaluating management\'s explanation for reasonableness; (3) corroborating the explanation with additional audit evidence (documents, third-party data); (4) performing additional procedures as necessary. The auditor should not accept management\'s explanation at face value — the explanation should be consistent with the auditor\'s understanding of the entity and supported by other evidence. Unexplained differences may indicate misstatements.',
    reference: 'AU-C 520.07',
  },
  {
    id: 'aud-d8-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Non-Sampling Risk',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Non-sampling risk includes all of the following EXCEPT:',
    options: [
      'Using inappropriate audit procedures',
      'Drawing a sample that is not perfectly representative of the population',
      'Failing to recognize misstatements in documents examined',
      'Misinterpreting audit evidence',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 530.05(g) defines non-sampling risk as the risk that the auditor reaches an erroneous conclusion for any reason NOT related to sampling risk. Non-sampling risk includes: (1) selecting inappropriate audit procedures for the objective; (2) failing to recognize misstatements in items examined (e.g., not noticing a forged signature); (3) misinterpreting audit results; (4) directing procedures toward the wrong objective. Drawing a sample that is not perfectly representative IS sampling risk — it is the inherent risk that any sample may not perfectly reflect the population. Non-sampling risk can be reduced through proper training, supervision, and quality control; sampling risk is managed through sample design.',
    reference: 'AU-C 530.05(g)',
  },
  {
    id: 'aud-d8-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-tests-of-controls',
    topic: 'Tests of Controls',
    subtopic: 'Sample Size for Controls',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When testing a daily control procedure, an auditor typically needs a sample of approximately 25-60 items for a moderate-risk control. If the same control operated weekly instead of daily, the appropriate sample size would be:',
    options: [
      'The same 25-60 items',
      'Smaller — approximately 5-15 items, because there are only about 52 occurrences in a year',
      'Larger — 100 items',
      'Zero — weekly controls cannot be tested through sampling',
    ],
    correctAnswer: 1,
    explanation: 'The frequency of control operation directly affects sample size. Common guidance suggests: daily controls (250+ occurrences/year): test 25-60+ items; weekly controls (52 occurrences/year): test 5-15 items; monthly controls (12 occurrences/year): test 2-5 items; quarterly controls (4 occurrences/year): test 1-2 items. The sample size is influenced by the population size (number of times the control operates) and the tolerable and expected deviation rates. For a weekly control with only 52 occurrences, a sample of 5-15 provides reasonable coverage while being practical.',
    reference: 'AU-C 530.A14; AICPA Audit Sampling Guide',
  },
  {
    id: 'aud-d8-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Types of Analytical Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following is an example of an analytical procedure?',
    options: [
      'Confirming a receivable balance with a customer',
      'Comparing the current-year gross margin percentage with the prior year and investigating any significant change',
      'Physically counting inventory',
      'Examining a canceled check',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 520.04 defines analytical procedures as evaluations of financial information through analysis of plausible relationships among both financial and non-financial data. Comparing the current-year gross margin percentage with the prior year is a classic analytical procedure — it analyzes the relationship between revenue and cost of goods sold over time. Confirming receivables (tests of details), counting inventory (observation/inspection), and examining canceled checks (inspection of documents) are all substantive tests of details, not analytical procedures. Analytical procedures focus on relationships and trends rather than examining individual transactions.',
    reference: 'AU-C 520.04',
  },
];
