// AUD Depth Questions - Batch 11
// Focus: AUD-III (Performing Further Procedures and Obtaining Evidence)
// Topics: Fair Value Estimates, Going Concern, Journal Entry Testing, Related Parties
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const AUD_QUESTIONS_DEPTH_11: Question[] = [
  {
    id: 'aud-d11-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-fair-value',
    topic: 'Fair Value Estimates',
    subtopic: 'Auditor Responsibilities',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When auditing fair value measurements under AU-C 540, the auditor should:',
    options: [
      'Accept management\'s fair value estimate without testing',
      'Evaluate the appropriateness of the valuation method, the reasonableness of significant assumptions, and whether the data used is relevant and reliable',
      'Hire an appraiser for every fair value measurement',
      'Only test fair values reported by third-party pricing services',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 540.12 through 13 requires the auditor to evaluate: (1) the appropriateness of the valuation method — is it consistent with the applicable financial reporting framework (ASC 820)? Is it appropriate for the specific asset/liability? (2) the reasonableness of significant assumptions — are management\'s assumptions consistent with market participant assumptions? Are they internally consistent? Are they supported by evidence? (3) the relevance and reliability of the underlying data; (4) mathematical accuracy of the calculations; (5) whether the fair value measurement and disclosures comply with the applicable framework. The auditor may develop an independent estimate, review subsequent events, or use a specialist when necessary.',
    reference: 'AU-C 540.12 through 13; ASC 820',
  },
  {
    id: 'aud-d11-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-fair-value',
    topic: 'Fair Value Estimates',
    subtopic: 'Level 3 Inputs',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Fair value measurements using Level 3 inputs (unobservable inputs) under ASC 820 present the HIGHEST audit risk because:',
    options: [
      'Level 3 inputs are the most common',
      'They involve the greatest degree of management judgment and subjectivity, making them more susceptible to estimation uncertainty and potential management bias',
      'They use quoted market prices',
      'They involve no estimation uncertainty',
    ],
    correctAnswer: 1,
    explanation: 'Level 3 inputs are unobservable inputs that reflect management\'s own assumptions about what market participants would use. They are used when observable market data is not available (e.g., complex derivatives, intangible assets, goodwill impairment models). The high degree of management judgment creates: (1) greater estimation uncertainty — a wide range of reasonable values; (2) greater risk of management bias — management may select assumptions to achieve desired outcomes; (3) greater audit complexity — the auditor may need specialists, must develop independent expectations, and must carefully evaluate assumptions and models. AU-C 540.15 requires the auditor to evaluate whether disclosures adequately convey the estimation uncertainty for Level 3 measurements.',
    reference: 'AU-C 540.15; ASC 820-10-35',
  },
  {
    id: 'aud-d11-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-going-concern',
    topic: 'Going Concern',
    subtopic: 'Auditor Evaluation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 570, the auditor has a responsibility to:',
    options: [
      'Predict whether the entity will continue for the next 10 years',
      'Evaluate whether there are conditions or events that raise substantial doubt about the entity\'s ability to continue as a going concern within one year after the financial statement date',
      'Guarantee the entity\'s survival',
      'Only consider going concern if management raises the issue',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 570.10 requires the auditor to evaluate whether substantial doubt exists about the entity\'s ability to continue as a going concern for a reasonable period of time (one year beyond the financial statement date or, for entities applying ASC 205-40, one year from the date the financial statements are issued/available to be issued). The auditor should: (1) consider whether the results of procedures performed throughout the audit identify conditions/events raising doubt (e.g., negative trends, loan defaults, loss of key customers); (2) if such conditions exist, evaluate management\'s plans to mitigate the concern; (3) conclude whether substantial doubt is alleviated by management\'s plans.',
    reference: 'AU-C 570.10 through 13',
  },
  {
    id: 'aud-d11-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-going-concern',
    topic: 'Going Concern',
    subtopic: 'Indicators of Going Concern Doubt',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following conditions or events would most likely raise substantial doubt about an entity\'s ability to continue as a going concern?',
    options: [
      'A 5% increase in revenue',
      'Recurring operating losses, negative cash flows from operations, working capital deficiencies, and loan covenant violations',
      'Hiring of a new CEO',
      'Opening a new branch office',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 570.A3 provides examples of conditions that may indicate going concern doubt: Financial indicators: recurring operating losses, negative cash flows from operations, working capital deficiencies, adverse key financial ratios, loan defaults or covenant violations, inability to pay debts as they mature. Operating indicators: loss of key management without replacement, loss of a major customer or supplier, labor difficulties. Other indicators: noncompliance with capital requirements, pending legal proceedings that could threaten the entity, changes in legislation. A 5% revenue increase, new CEO, and new branch office are generally positive indicators, not conditions of concern.',
    reference: 'AU-C 570.A3',
  },
  {
    id: 'aud-d11-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-going-concern',
    topic: 'Going Concern',
    subtopic: 'Management Plans',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When the auditor identifies substantial doubt about going concern, the auditor evaluates management\'s plans. If management\'s plans include borrowing additional funds, the auditor should:',
    options: [
      'Accept the plan at face value',
      'Evaluate the feasibility of the plan by considering whether debt or equity financing is available (committed credit facilities, term sheets), whether the entity can meet the terms, and whether the plans effectively mitigate the doubt',
      'Automatically issue a going concern opinion',
      'Ignore the plan because it involves future events',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 570.16 requires the auditor to evaluate management\'s plans for feasibility and effectiveness. For financing plans, the auditor should: (1) evaluate whether the financing is probable — are there signed commitments, term sheets, or credit agreements? Mere intentions are not sufficient; (2) assess whether the entity can meet the terms and conditions of the financing; (3) consider whether the amount of financing is sufficient to address the entity\'s needs; (4) evaluate whether the overall plan effectively mitigates the going concern doubt. Other plan elements (disposing of assets, reducing costs, restructuring debt) are similarly evaluated for feasibility. If management\'s plans do not adequately mitigate the doubt, the auditor\'s report must include an emphasis-of-matter paragraph.',
    reference: 'AU-C 570.16 through 18',
  },
  {
    id: 'aud-d11-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-journal-entries',
    topic: 'Journal Entry Testing',
    subtopic: 'Management Override',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 240, the auditor must test journal entries as a response to the presumed risk of management override of controls. The procedures include:',
    options: [
      'Only reviewing automated journal entries',
      'Selecting journal entries and other adjustments for testing, particularly those entries made at the end of a reporting period, and evaluating whether they are supported by appropriate documentation and are for a valid business purpose',
      'Reviewing all journal entries in detail',
      'Only testing entries above materiality',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.32 requires the auditor to: (1) obtain an understanding of the financial reporting process and controls over journal entries and other adjustments; (2) design and perform tests of journal entries — selecting entries for testing based on risk characteristics (end-of-period entries, unusual amounts or accounts, entries by personnel who do not typically make entries, entries with round numbers, entries with no explanation); (3) evaluate the entries for valid business purpose and proper support; (4) consider testing throughout the period, not just at year-end. This procedure is mandatory regardless of the auditor\'s otherwise assessed fraud risk because management override cannot be fully controlled — management has the ability to circumvent any control they designed.',
    reference: 'AU-C 240.32 through 33',
  },
  {
    id: 'aud-d11-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-journal-entries',
    topic: 'Journal Entry Testing',
    subtopic: 'High-Risk Entry Characteristics',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When selecting journal entries for testing under AU-C 240, the auditor should focus on entries with which characteristics?',
    options: [
      'Only entries made in the standard course of business',
      'Entries made at or near the end of the period, entries made by senior management who do not normally make entries, entries that involve unusual accounts or round amounts, and entries with little or no explanation',
      'Only entries affecting cash',
      'Only entries above $1 million',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.A51 identifies characteristics that increase the risk of fraudulent journal entries: (1) entries made at or near the end of the reporting period — year-end and quarter-end entries are more likely to be used for earnings management; (2) entries made by individuals who do not ordinarily make entries (senior management, executives); (3) entries recorded in seldom-used accounts or involving unusual account combinations; (4) entries with round dollar amounts; (5) entries with little or no supporting explanation; (6) entries processed outside the normal course of business; (7) entries posted directly to the general ledger rather than through subsidiary ledgers. CAATs (computer-assisted audit techniques) can be used to efficiently identify and select high-risk entries.',
    reference: 'AU-C 240.A51',
  },
  {
    id: 'aud-d11-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Accounts Payable - Completeness',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A search for unrecorded liabilities typically involves:',
    options: [
      'Confirming all vendor balances',
      'Examining cash disbursements after year-end, reviewing unmatched receiving reports and vendor invoices received after year-end, and inquiring of management about unpaid obligations',
      'Only reviewing the accounts payable aging',
      'Testing only recorded payables for existence',
    ],
    correctAnswer: 1,
    explanation: 'A search for unrecorded liabilities is designed to test the completeness assertion for payables. Common procedures include: (1) examining cash disbursements made after year-end — payments for goods/services received before year-end should have been accrued; (2) examining unmatched receiving reports — goods received before year-end without a corresponding recorded payable indicate an omission; (3) reviewing vendor invoices received after year-end for goods/services provided before year-end; (4) inspecting purchase orders and contracts for obligations at year-end; (5) inquiring of management about unpaid bills, accruals, and commitments. This procedure uses the source-to-records direction of testing (starting from reality, tracing to the books).',
    reference: 'AU-C 330; AU-C 501',
  },
  {
    id: 'aud-d11-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'PP&E Testing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When testing fixed assets (property, plant, and equipment), the auditor is primarily concerned with which assertions?',
    options: [
      'Only presentation',
      'Existence (assets physically exist), valuation (properly recorded at cost less accumulated depreciation, tested for impairment), completeness (all assets are recorded), and rights (the entity owns or controls the assets)',
      'Only cutoff',
      'Only classification',
    ],
    correctAnswer: 1,
    explanation: 'Fixed asset testing addresses multiple assertions: (1) Existence — physical inspection of selected assets, comparison of asset listing to physical assets; (2) Valuation — testing depreciation calculations, reviewing useful life estimates, evaluating impairment indicators (ASC 360), testing capitalization vs. expense decisions (thresholds, nature); (3) Completeness — tracing from physical assets to the records, reviewing repair and maintenance accounts for items that should have been capitalized; (4) Rights — examining titles, deeds, purchase agreements, lease contracts to confirm ownership or control; (5) Presentation — proper classification between categories, adequate disclosure of depreciation methods and pledged assets.',
    reference: 'AU-C 330; ASC 360',
  },
  {
    id: 'aud-d11-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Payroll Testing',
    difficulty: 'easy',
    skillLevel: 'Application',
    question: 'Substantive tests of payroll expenses commonly include:',
    options: [
      'Only comparing the total payroll expense to the prior year',
      'Testing a sample of payroll payments by verifying authorization (hiring approval, pay rates), recalculating gross and net pay, and verifying that employees exist (existence of employees on the payroll)',
      'Only inspecting the payroll bank statement',
      'Only confirming payroll amounts with employees',
    ],
    correctAnswer: 1,
    explanation: 'Comprehensive payroll testing includes: (1) Existence — verifying that employees on the payroll actually exist and are currently employed (reviewing HR records, observing employees); (2) Authorization — verifying that pay rates, deductions, and payroll changes are properly authorized; (3) Accuracy — recalculating gross pay (hours × rate), deductions (taxes, benefits, other), and net pay; (4) Occurrence — verifying that employees actually worked the time recorded (reviewing timecards, attendance records); (5) Completeness — analytical comparison to prior periods, analyzing payroll trends by department; (6) Classification — proper coding of payroll expenses to accounts and departments. Ghost employee fraud is a key risk that existence testing addresses.',
    reference: 'AU-C 330',
  },
  {
    id: 'aud-d11-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Contradictory Evidence',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If the auditor obtains audit evidence that is contradictory to other evidence obtained, the auditor should:',
    options: [
      'Discard the contradictory evidence and accept the majority view',
      'Determine what modifications or additions to audit procedures are necessary to resolve the matter, and consider the effect on other aspects of the audit',
      'Accept both pieces of evidence simultaneously',
      'Ignore the contradiction if the amounts are immaterial',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 500.11 requires the auditor to resolve contradictory evidence. If evidence from different sources is inconsistent, the auditor must: (1) consider what additional procedures are needed to resolve the inconsistency (additional inquiry, testing, inspection); (2) evaluate the reliability of each piece of evidence (considering source, nature, and circumstances); (3) consider whether the contradiction suggests a broader problem (possible error, fraud, or inappropriate accounting); (4) evaluate the effect on other aspects of the audit — if evidence in one area is unreliable, it may affect conclusions in related areas. The auditor cannot simply ignore contradictions — professional skepticism requires investigation.',
    reference: 'AU-C 500.11; AU-C 200.17',
  },
  {
    id: 'aud-d11-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-fair-value',
    topic: 'Fair Value Estimates',
    subtopic: 'Auditor\'s Range',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When auditing a significant fair value measurement, the auditor may develop an independent point estimate or a range. If the auditor establishes a range and management\'s estimate falls outside the auditor\'s range:',
    options: [
      'The auditor accepts management\'s estimate',
      'This suggests a potential misstatement; the auditor should investigate why the difference exists, request management to reconsider, and if management refuses to adjust, treat the difference as a likely misstatement',
      'The auditor automatically issues an adverse opinion',
      'The auditor\'s range is irrelevant',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 540.13 states that if the auditor develops a range and management\'s estimate falls outside the range, this is an indicator of potential misstatement. The auditor should: (1) investigate the reason for the difference (different assumptions, data, methodology); (2) discuss with management and request that management provide additional support or reconsider the estimate; (3) if the difference cannot be explained and management refuses to adjust, treat the difference from the nearest point in the auditor\'s range as a likely misstatement; (4) aggregate this misstatement with other audit findings to evaluate whether the financial statements as a whole are materially misstated. The auditor\'s range should be narrowed sufficiently so that it is useful for evaluation.',
    reference: 'AU-C 540.13 through 14',
  },
  {
    id: 'aud-d11-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Investment Testing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When auditing investments in debt and equity securities, the auditor typically:',
    options: [
      'Only reviews the investment schedule',
      'Confirms investments held by custodians, verifies fair value/market prices from independent sources, evaluates the classification (trading, AFS, HTM), and tests for impairment',
      'Only inspects the securities physically',
      'Relies solely on management\'s valuation',
    ],
    correctAnswer: 1,
    explanation: 'Investment testing includes: (1) Existence — confirming securities held by custodians (banks, brokers) through direct confirmation; if held by the entity, inspecting the certificates; (2) Valuation — verifying fair values using independent pricing sources (published market quotes for Level 1, dealer quotes or pricing services for Level 2, model-based valuations for Level 3); (3) Classification — evaluating management\'s classification (trading, available-for-sale, held-to-maturity for debt, equity method vs. fair value) and whether it is appropriate under ASC 320/321; (4) Impairment — evaluating whether declines in value are credit-related and require recognition under ASC 326 (CECL for debt securities); (5) Rights — verifying the entity\'s ownership through confirmations and records.',
    reference: 'AU-C 330; ASC 320; ASC 321; ASC 326',
  },
  {
    id: 'aud-d11-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-going-concern',
    topic: 'Going Concern',
    subtopic: 'Reporting Effects',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'If substantial doubt about going concern exists after considering management\'s plans, the auditor should:',
    options: [
      'Issue an adverse opinion',
      'Include an emphasis-of-matter paragraph (separate paragraph) in the audit report that refers to the entity\'s disclosures about the going concern uncertainty, while still issuing an unmodified opinion if the disclosures are adequate',
      'Withdraw from the engagement',
      'Issue a disclaimer of opinion',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 570.19 through 20 provides the reporting guidance: when substantial doubt remains after evaluating management\'s plans, the auditor includes an emphasis-of-matter paragraph in the audit report. This paragraph: (1) uses the heading "Going Concern" or similar; (2) refers to the relevant disclosures in the financial statements; (3) states that conditions exist that raise substantial doubt about the entity\'s ability to continue as a going concern; (4) the opinion itself remains unmodified if the financial statements, including going concern disclosures, are presented fairly. If management does not make adequate disclosure about going concern, the auditor considers a qualified or adverse opinion for the departure from the framework.',
    reference: 'AU-C 570.19 through 20',
  },
  {
    id: 'aud-d11-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Expense Testing',
    difficulty: 'easy',
    skillLevel: 'Application',
    question: 'When testing operating expenses like rent, insurance, or utilities for reasonableness, the most effective procedure is typically:',
    options: [
      'Reviewing the general ledger listing only',
      'Performing a substantive analytical procedure — such as comparing monthly rent expense to the lease agreement terms, or comparing insurance expense by month and investigating unexpected fluctuations',
      'Confirming all expenses with vendors',
      'Testing every expense transaction',
    ],
    correctAnswer: 1,
    explanation: 'Certain operating expenses have predictable relationships that make substantive analytical procedures highly effective. For example: (1) Rent expense — should equal the monthly lease payment × number of months, per the lease agreement; significant deviations suggest errors or unrecorded items; (2) Insurance expense — should correspond to the policy premiums spread over the coverage period; (3) Utilities — should correlate with historical patterns, seasonality, and production levels; (4) Depreciation — should be calculable from the asset schedule. These analytical procedures are efficient because they provide high-quality evidence for accounts with predictable patterns. Tests of details are more appropriate for accounts with less predictable relationships.',
    reference: 'AU-C 520; AU-C 330',
  },
  {
    id: 'aud-d11-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-related-parties',
    topic: 'Related Party Transactions',
    subtopic: 'Previously Undisclosed',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If the auditor discovers a significant related party transaction that management did not previously disclose, the auditor should:',
    options: [
      'Ignore it if the amount is small',
      'Communicate the finding to the engagement team, request management\'s explanation, reassess the risk of material misstatement (including fraud risk), evaluate whether the omission was intentional, and determine the implications for the audit',
      'Immediately notify the SEC',
      'Accept management\'s initial assessment',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 550.18 through 22 provides detailed guidance: (1) communicate the information to the engagement team to ensure awareness; (2) request management\'s explanation for the prior non-disclosure and evaluate whether the omission was intentional (which may indicate fraud risk); (3) perform procedures to identify other undisclosed related party transactions; (4) reassess the risk of material misstatement — previously undisclosed related parties may require revision of the risk assessment and additional audit procedures; (5) evaluate the transaction\'s business rationale; (6) consider whether the related party relationship and transaction have been properly accounted for and disclosed; (7) reconsider whether management\'s representations about completeness are reliable.',
    reference: 'AU-C 550.18 through 22',
  },
  {
    id: 'aud-d11-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-estimates',
    topic: 'Accounting Estimates',
    subtopic: 'Estimation Uncertainty Disclosure',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When an accounting estimate is subject to a high degree of estimation uncertainty, the auditor should evaluate whether the financial statement disclosures:',
    options: [
      'Simply disclose the existence of the estimate',
      'Adequately describe the nature and extent of the estimation uncertainty, including the range of possible outcomes and the assumptions used, to allow users to understand the potential variability',
      'Only disclose the point estimate',
      'Are optional since estimates are always uncertain',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 540.19 through 20 requires the auditor to evaluate disclosure adequacy for estimates with high uncertainty. The applicable framework (ASC 275 and other standards) typically requires disclosure of: (1) the nature of the estimate and the factors that make it uncertain; (2) the range of reasonably possible outcomes (where applicable); (3) the significant assumptions and methods used; (4) sensitivity to changes in assumptions (for some estimates). Users need this information to make informed decisions — a point estimate alone may give a false sense of precision. If disclosures are inadequate, the auditor should request additional disclosures and, if management refuses, consider modifying the opinion for a departure from the framework.',
    reference: 'AU-C 540.19 through 20; ASC 275-10-50',
  },
  {
    id: 'aud-d11-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Receivables - Existence vs. Completeness',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Sending positive confirmations to a sample of recorded accounts receivable primarily tests which assertion?',
    options: [
      'Completeness',
      'Existence — confirming that the recorded receivables actually exist and the debtor acknowledges the obligation',
      'Classification',
      'Presentation',
    ],
    correctAnswer: 1,
    explanation: 'Confirmation of recorded receivables primarily tests the existence assertion — the auditor selects items from the receivables listing and asks the debtor to confirm the balance. If the debtor confirms, the receivable exists. The direction of testing determines the assertion tested: starting from the RECORDS and verifying with an external source tests existence/occurrence. To test completeness, the auditor would need to start from outside the accounting records (e.g., review delivery records, subsequent cash receipts that weren\'t in the receivables listing). Confirmations also provide evidence about rights (the entity is owed the money) and valuation (the amount is correctly stated), but existence is the primary assertion addressed.',
    reference: 'AU-C 505; AU-C 330',
  },
  {
    id: 'aud-d11-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-journal-entries',
    topic: 'Journal Entry Testing',
    subtopic: 'Significant Unusual Transactions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under AU-C 240, in response to the risk of management override, the auditor must also evaluate:',
    options: [
      'Only the general ledger',
      'Significant unusual transactions, particularly those outside the normal course of business or that appear unusual given the auditor\'s understanding of the entity, for proper business rationale and appropriate accounting treatment',
      'Only routine transactions',
      'Only transactions below materiality',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.32(c) specifically requires the auditor to evaluate significant unusual transactions. The auditor should: (1) identify transactions that are outside the normal course of business or appear otherwise unusual given the auditor\'s understanding of the entity; (2) evaluate the business rationale — do they make economic sense? Could they be designed to engage in fraudulent financial reporting or conceal misappropriation?; (3) evaluate whether the accounting treatment is appropriate; (4) understand the terms and purpose by reviewing contracts, agreements, and correspondence. Examples of unusual transactions include: complex sales arrangements near period-end, sales with undisclosed side agreements, transactions with related parties, round-trip transactions, and transactions with entities that appear to lack substance.',
    reference: 'AU-C 240.32(c)',
  },
  {
    id: 'aud-d11-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Debt Testing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When auditing long-term debt, the auditor should perform all of the following procedures EXCEPT:',
    options: [
      'Confirming loan balances with lenders',
      'Reviewing loan agreements for covenants and evaluating compliance',
      'Determining the entity\'s optimal capital structure',
      'Recalculating interest expense based on stated interest rates',
    ],
    correctAnswer: 2,
    explanation: 'Long-term debt testing includes: (1) Confirmation — sending confirmations directly to lenders to verify balances, interest rates, terms, maturity dates, collateral, and covenant terms; (2) Covenant compliance — reviewing loan agreements for financial covenants (debt/equity ratios, minimum net worth, interest coverage) and evaluating whether the entity is in compliance (violations may require current classification or trigger going concern considerations); (3) Interest expense recalculation — independently computing interest expense using the stated rate, balance, and time period; (4) Classification — evaluating whether debt is properly classified as current or noncurrent based on maturity and refinancing arrangements. Determining the optimal capital structure is a financial advisory/management function, not an audit procedure.',
    reference: 'AU-C 330; AU-C 505',
  },
  {
    id: 'aud-d11-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-estimates',
    topic: 'Accounting Estimates',
    subtopic: 'Retrospective Review',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The purpose of a retrospective review of prior-year accounting estimates under AU-C 540 is to:',
    options: [
      'Restate prior-year financial statements',
      'Obtain information about the effectiveness of management\'s estimation process and identify possible bias in management\'s assumptions',
      'Verify that all estimates were mathematically correct',
      'Satisfy a quality control requirement only',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 540.09 requires the auditor to review the outcome of prior-period accounting estimates (or their subsequent re-estimation). Purposes include: (1) understanding the effectiveness of management\'s estimation process — if prior estimates consistently differ significantly from outcomes, the process may be unreliable; (2) identifying possible management bias — a pattern of over- or under-estimating in a particular direction suggests intentional bias; (3) identifying changes in circumstances — if the environment has changed, prior-year estimation approaches may need modification; (4) risk assessment — the review informs the current-year risk assessment for estimates. This is a risk assessment procedure, not an attempt to retroactively correct prior statements.',
    reference: 'AU-C 540.09',
  },
  {
    id: 'aud-d11-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Interim Testing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'If the auditor performs substantive procedures at an interim date (before year-end), additional procedures are needed for the remaining period. The auditor should:',
    options: [
      'Assume no material changes occurred between interim and year-end',
      'Perform substantive procedures (tests of details and/or substantive analytical procedures) covering the remaining period from the interim date to period end',
      'Only perform analytical procedures at year-end',
      'Reperform all interim procedures at year-end',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 330.22 through 23 provides guidance when substantive procedures are performed at an interim date. The auditor must: (1) perform additional substantive procedures (tests of details, analytical procedures, or a combination) covering the remaining period from the interim date through year-end; (2) the combination of interim procedures and remaining-period procedures should provide a reasonable basis for extending audit conclusions to the period end; (3) consider whether the assessed risk of material misstatement has changed; (4) if the risk is higher, more work is needed for the remaining period. Factors affecting the approach include: the assessed risk level, the account\'s susceptibility to misstatement, availability of evidence, and the length of the remaining period.',
    reference: 'AU-C 330.22 through 23',
  },
  {
    id: 'aud-d11-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Using the Work of Others',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Regardless of evaluated competence, the auditor should NOT use the work of others for areas involving:',
    options: [
      'Routine transaction testing',
      'Significant judgments related to the audit, assessment of significant risks, or evaluation of the sufficiency of work performed by others',
      'Confirmation procedures',
      'Inventory observation',
    ],
    correctAnswer: 1,
    explanation: 'Areas requiring the auditor\'s own professional judgment and expertise should not be delegated: (1) significant audit judgments — determining materiality, evaluating going concern, assessing overall audit risk, forming the audit opinion; (2) significant risk assessment — identifying and evaluating significant risks of material misstatement; (3) evaluating the sufficiency and appropriateness of evidence — the auditor must personally assess whether enough high-quality evidence supports the audit conclusion. Routine procedures (confirmations, inventory observation, transaction testing) can be delegated to others under appropriate supervision, but the judgment functions that form the core of the audit opinion must remain with the engagement team.',
    reference: 'AU-C 610; AU-C 220',
  },
  {
    id: 'aud-d11-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Equity Testing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When auditing stockholders\' equity, the auditor\'s procedures typically include:',
    options: [
      'Only reviewing the equity section of the balance sheet',
      'Reviewing articles of incorporation and bylaws, examining authorization for stock issuances and dividends (board minutes), confirming shares outstanding with the transfer agent, and testing the mathematical accuracy of equity computations',
      'Only confirming with stockholders',
      'Only testing dividend payments',
    ],
    correctAnswer: 1,
    explanation: 'Equity testing procedures include: (1) reviewing legal documents — articles of incorporation, bylaws, share agreements to understand authorized shares, par values, classes of stock, and any restrictions; (2) examining authorization — reviewing board minutes for approvals of stock issuances, repurchases, dividends, and stock splits; (3) confirming outstanding shares — with the independent transfer agent and registrar; (4) testing computations — recalculating additional paid-in capital, retained earnings (beginning balance + net income − dividends ± adjustments), treasury stock transactions, and other comprehensive income; (5) evaluating disclosures — proper disclosure of rights, preferences, restrictions, dividends per share, and subsequent events related to equity.',
    reference: 'AU-C 330',
  },
  {
    id: 'aud-d11-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-going-concern',
    topic: 'Going Concern',
    subtopic: 'Communication of Going Concern',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 260, the auditor\'s communication of going concern matters to those charged with governance should include:',
    options: [
      'Nothing — going concern matters are only for the audit report',
      'The conditions that gave rise to the substantial doubt, management\'s plans, the adequacy of disclosures, and the effect on the auditor\'s report',
      'Only the auditor\'s fee for the going concern evaluation',
      'Only a reference to relevant accounting standards',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 260.13 and AU-C 570.24 require the auditor to communicate to those charged with governance: (1) the events, conditions, or circumstances identified that raise substantial doubt; (2) whether the conditions represent a close call (conditions are mitigated but barely) or significant going concern risk; (3) management\'s plans to address the conditions and the auditor\'s evaluation of those plans; (4) the adequacy of related financial statement disclosures; (5) the effect on the auditor\'s report (whether an emphasis-of-matter paragraph will be included). This communication ensures those charged with governance are informed and can exercise their oversight responsibility regarding the entity\'s financial viability and disclosures.',
    reference: 'AU-C 260.13; AU-C 570.24',
  },
];
