// AUD Depth Questions - Batch 12
// Focus: AUD-III (Performing Further Procedures and Obtaining Evidence)
// Topics: Misstatement Evaluation, Audit Documentation, Communication with Governance
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const AUD_QUESTIONS_DEPTH_12: Question[] = [
  {
    id: 'aud-d12-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-misstatements',
    topic: 'Evaluating Misstatements',
    subtopic: 'Accumulation and Evaluation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 450, the auditor must accumulate misstatements identified during the audit. Accumulated misstatements include:',
    options: [
      'Only known (factual) misstatements',
      'Known (factual) misstatements, likely (projected) misstatements from sampling, and further possible misstatements such as differences in management\'s judgments about estimates that the auditor considers unreasonable',
      'Only immaterial misstatements',
      'Only misstatements that exceed materiality individually',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 450.05 through 06 requires the auditor to accumulate all identified misstatements: (1) Known (factual) misstatements — specific errors found during testing that are not subject to uncertainty (e.g., an incorrect computation); (2) Likely (projected) misstatements — the auditor\'s best estimate of misstatements in the population based on sample results (projected from the sample to the population); (3) Judgmental misstatements — differences arising from management\'s estimates or selections of accounting policies that the auditor considers unreasonable. The auditor evaluates whether the aggregate of uncorrected misstatements (all three types) is material. Even individually immaterial misstatements must be accumulated because multiple small misstatements may be material in aggregate.',
    reference: 'AU-C 450.05 through 06',
  },
  {
    id: 'aud-d12-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-misstatements',
    topic: 'Evaluating Misstatements',
    subtopic: 'Communication of Misstatements',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 450, the auditor should communicate accumulated misstatements to management and request correction. If management refuses to correct certain misstatements:',
    options: [
      'The auditor ignores them',
      'The auditor obtains an understanding of management\'s reasons, evaluates whether uncorrected misstatements are material individually or in aggregate, and considers the effect on the audit opinion',
      'The auditor adjusts the financial statements directly',
      'The auditor must withdraw from the engagement',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 450.08 through 11 provides the process: (1) communicate all accumulated misstatements (other than those that are clearly trivial) to management and request correction; (2) if management refuses to correct certain misstatements, obtain an understanding of management\'s reasons for not making corrections; (3) evaluate whether the uncorrected misstatements, individually or in aggregate, are material — considering both quantitative and qualitative factors (nature, cause, effect on trends, effect on ratios, regulatory implications); (4) document the uncorrected misstatements in the summary of audit differences; (5) communicate uncorrected misstatements to those charged with governance (AU-C 260); (6) determine the effect on the audit opinion.',
    reference: 'AU-C 450.08 through 11',
  },
  {
    id: 'aud-d12-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-misstatements',
    topic: 'Evaluating Misstatements',
    subtopic: 'Qualitative Considerations',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When evaluating whether uncorrected misstatements are material, the auditor considers qualitative factors. An otherwise quantitatively immaterial misstatement might be material if it:',
    options: [
      'Affects only the footnotes',
      'Involves fraud, masks a change in earnings trend, affects compliance with loan covenants, or converts a reported loss into income',
      'Was discovered early in the audit',
      'Involves an area that management considers unimportant',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 450.A16 identifies qualitative factors that may make a quantitatively small misstatement material: (1) the misstatement is the result of fraud (even a small fraud indicates a control environment problem and may suggest larger undetected fraud); (2) the misstatement masks a change in earnings trend (e.g., turning a decline into growth); (3) the misstatement affects compliance with debt covenants or regulatory requirements; (4) the misstatement converts a reported loss into income (or vice versa); (5) the misstatement affects key ratios or benchmarks used by analysts; (6) the misstatement affects management compensation calculations; (7) the misstatement relates to items involving related parties; (8) the misstatement involves concealment of an unlawful transaction.',
    reference: 'AU-C 450.A16',
  },
  {
    id: 'aud-d12-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Purpose and Requirements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'According to AU-C 230, audit documentation should be sufficient to enable:',
    options: [
      'Only the engagement partner to understand the work',
      'An experienced auditor with no previous connection to the engagement to understand the nature, timing, and extent of procedures performed, the evidence obtained, and the conclusions reached',
      'Only regulators to review the work',
      'Only the client to understand the work performed',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 230.08 establishes the overarching documentation requirement: documentation should be sufficient to enable an experienced auditor, having no previous connection with the engagement, to understand: (1) the nature, timing, and extent of audit procedures performed; (2) the results of procedures and the audit evidence obtained; (3) significant matters arising during the audit and the conclusions reached; (4) the identity of who performed and reviewed the work. This "experienced auditor" standard ensures documentation is comprehensive enough for peer review, quality control inspection, regulatory review, and potential litigation support. It is NOT intended solely for the engagement team or the client.',
    reference: 'AU-C 230.08',
  },
  {
    id: 'aud-d12-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Completion and Assembly',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 230, the audit documentation file should be assembled within:',
    options: [
      '30 days after the report release date',
      '60 days after the report release date',
      '90 days after the report release date',
      '120 days after the report release date',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 230.15 requires the auditor to assemble the final audit file on a timely basis, no later than 60 days after the report release date (the documentation completion date). During this 60-day period, the auditor may: (1) assemble and organize workpapers; (2) add administrative items (cross-references, sign-off sheets); (3) delete superseded drafts. After the 60-day period, the auditor should not delete or discard existing documentation. Additions after the documentation completion date must be documented with the date, by whom, and the reasons. For PCAOB engagements (issuers), the period is 45 days. The assembled file should be retained for the applicable retention period (generally 5 years for non-issuers, 7 years for issuers).',
    reference: 'AU-C 230.15 through 17',
  },
  {
    id: 'aud-d12-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Significant Matters',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'AU-C 230.09 requires documentation of significant matters. This includes:',
    options: [
      'Only the engagement letter',
      'Significant findings or issues, how they were addressed, significant professional judgments made, and consultations with others on difficult or contentious matters',
      'Only quantitative test results',
      'Only the management representation letter',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 230.09 through 12 requires documentation of: (1) significant findings or issues — including the nature of the matter, results of procedures performed, audit evidence obtained, and conclusions reached; (2) significant professional judgments — particularly in areas of high estimation uncertainty, significant risks, or disagreements with management; (3) consultations on difficult or contentious matters — the nature of the issue, with whom consulted, and conclusions; (4) discussions with management and those charged with governance about significant matters; (5) the basis for changes in planned procedures; (6) how inconsistencies in audit evidence were resolved. Documentation should capture the auditor\'s reasoning, not just the conclusion.',
    reference: 'AU-C 230.09 through 12',
  },
  {
    id: 'aud-d12-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Required Communications',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 260, the auditor must communicate to those charged with governance all of the following EXCEPT:',
    options: [
      'Significant audit findings, including significant accounting policies and practices',
      'Difficulties encountered during the audit',
      'The detailed audit program and specific procedures planned for each account',
      'Uncorrected misstatements',
    ],
    correctAnswer: 2,
    explanation: 'AU-C 260.12 through 17 requires communication of: (1) the auditor\'s responsibilities; (2) the planned scope and timing (at a high level, not the detailed procedures for every account); (3) significant accounting policies and practices (including changes, critical estimates, and sensitive disclosures); (4) significant audit findings (material adjustments, uncorrected misstatements, disagreements with management, difficulties encountered, fraud or illegal acts); (5) supplementary information (management advisory comments). The DETAILED audit program (specific procedures, sample sizes, accounts targeted) is an internal working document — sharing it at that level of detail could compromise audit effectiveness and is not required by AU-C 260.',
    reference: 'AU-C 260.12 through 17',
  },
  {
    id: 'aud-d12-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Internal Control Deficiencies',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 265, the auditor must communicate in writing to those charged with governance and management:',
    options: [
      'All control deficiencies, regardless of severity',
      'Significant deficiencies and material weaknesses identified during the audit',
      'Only material weaknesses',
      'No control deficiencies unless specifically requested',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 265.09 through 11 requires the auditor to communicate in writing: (1) Material weaknesses — deficiencies that create a reasonable possibility that a material misstatement will not be prevented or detected on a timely basis. These must be communicated to both those charged with governance and management; (2) Significant deficiencies — deficiencies that are important enough to merit attention by those charged with governance. Also communicated in writing to both parties. Other control deficiencies that are not significant deficiencies or material weaknesses may be communicated at the auditor\'s discretion. The written communication should be made no later than 60 days following the report release date.',
    reference: 'AU-C 265.09 through 11',
  },
  {
    id: 'aud-d12-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Retention',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AICPA quality control standards, audit documentation for non-issuers should generally be retained for:',
    options: [
      'One year',
      'Five years from the report release date',
      'Indefinitely',
      'Three years',
    ],
    correctAnswer: 1,
    explanation: 'SQCS (Statement on Quality Control Standards) requires non-issuer audit documentation to be retained for a period sufficient to meet the needs of the firm and satisfy legal and regulatory retention requirements — generally five years from the report release date. For SEC issuers under PCAOB standards, the retention period is seven years. During the retention period, documentation should be maintained securely with appropriate access controls. After the retention period, the firm may destroy the documentation in accordance with its policies. Some firms retain documentation longer due to litigation risk or specialized industry requirements.',
    reference: 'SQCS; AU-C 230',
  },
  {
    id: 'aud-d12-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Fraud Communication',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 240, if the auditor identifies fraud or obtains information indicating that fraud may exist, the auditor should communicate to:',
    options: [
      'Only law enforcement',
      'Management at the appropriate level, and directly to those charged with governance when the fraud involves senior management or when the fraud results in a material misstatement',
      'Only the entity\'s internal auditors',
      'Only the entity\'s external legal counsel',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.39 through 41 establishes communication requirements: (1) communicate fraud to management at an appropriate level — at minimum, one level above the person involved; (2) communicate directly to those charged with governance if the fraud involves senior management (even if the amount is immaterial — fraud by senior management indicates a control environment problem); (3) communicate if the fraud results in a material misstatement, regardless of who committed it; (4) communicate if the findings indicate a material weakness in internal control related to the fraud. The auditor should also consider legal and regulatory requirements regarding reporting to external parties (e.g., government audit requirements, bank regulatory requirements).',
    reference: 'AU-C 240.39 through 41',
  },
  {
    id: 'aud-d12-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-misstatements',
    topic: 'Evaluating Misstatements',
    subtopic: 'Effect on Audit Opinion',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If the aggregate of uncorrected misstatements approaches materiality, the auditor should:',
    options: [
      'Ignore the aggregate since individual misstatements are immaterial',
      'Consider whether there is greater than a low risk that undetected misstatements, when added to uncorrected misstatements, could exceed materiality, and determine whether to request further corrections or perform additional procedures',
      'Automatically issue a qualified opinion',
      'Reduce materiality retroactively',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 450.11 addresses this situation: when uncorrected misstatements approach materiality, the auditor must consider: (1) there may be additional undetected misstatements (because the auditor tests samples, not entire populations) — the sum of uncorrected known misstatements plus potential undetected misstatements could exceed materiality; (2) whether to request management to record additional corrections to reduce the aggregate; (3) whether to perform additional audit procedures to determine whether the financial statements are materially misstated; (4) whether to modify the audit opinion if the aggregate of uncorrected misstatements is material. This requires careful professional judgment — the auditor cannot simply hope that undetected misstatements will happen to offset known ones.',
    reference: 'AU-C 450.11; AU-C 320',
  },
  {
    id: 'aud-d12-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Departures from Standards',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'If the auditor departs from a relevant AU-C section requirement, the documentation must include:',
    options: [
      'Nothing special',
      'The reasons for the departure, how the alternative audit procedures performed were sufficient to achieve the objectives of the requirement, and the auditor\'s justification',
      'Only a note that the departure occurred',
      'A legal opinion from counsel',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 230.13 and AU-C 200 address departures: in rare circumstances, the auditor may judge it necessary to depart from a relevant requirement. Documentation must include: (1) the requirement from which the auditor departed; (2) the reason for the departure; (3) what alternative procedures were performed and how they achieved the objective of the requirement; (4) evidence that the alternative approach was sufficient (the "comply or explain" principle). Departures should be rare and well-justified — auditing standards are designed to work together, and departing from one requirement may affect the achievement of overall audit objectives. The auditor cannot simply skip a requirement without documented justification.',
    reference: 'AU-C 230.13; AU-C 200.23',
  },
  {
    id: 'aud-d12-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Unpredictability',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 240, as a response to the risk of management override, the auditor should incorporate an element of unpredictability. This means:',
    options: [
      'Performing the same procedures as every prior year',
      'Varying the nature, timing, or extent of procedures from year to year or performing procedures that management would not expect, such as testing low-risk areas that are not normally tested or visiting locations on an unannounced basis',
      'Randomly selecting which assertions to test',
      'Issuing the report at unpredictable times',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 240.30 requires incorporating unpredictability to address management override risk. Examples include: (1) performing substantive testing on accounts or assertions not otherwise tested based on materiality (e.g., testing a normally immaterial account); (2) adjusting the timing of procedures from prior years; (3) using different sampling methods; (4) performing procedures at different locations or on different dates than management expects; (5) testing journal entries at unexpected times. The purpose: if management knows exactly what the auditor will test, they can focus fraudulent activity on areas not subject to audit scrutiny. Unpredictability disrupts this calculus.',
    reference: 'AU-C 240.30',
  },
  {
    id: 'aud-d12-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Two-Way Communication',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Communication between the auditor and those charged with governance should be:',
    options: [
      'One-way — from the auditor to governance',
      'Two-way — the auditor provides information to governance and also obtains information relevant to the audit from governance',
      'One-way — from governance to the auditor',
      'Only in writing and only at year-end',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 260.05 emphasizes two-way communication: (1) The auditor TO governance — communicating required matters such as audit scope, significant findings, audit difficulties, independence, and significant accounting policies; (2) Governance TO the auditor — governance may communicate matters relevant to the audit such as their awareness of fraud, concerns about management integrity, concerns about internal control, or strategic and operational matters that could affect risk. Effective two-way communication helps the auditor obtain relevant information, builds mutual understanding, and develops a constructive working relationship. Some communications must be in writing (significantly deficiencies, material weaknesses), but oral communication is also appropriate.',
    reference: 'AU-C 260.05',
  },
  {
    id: 'aud-d12-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-misstatements',
    topic: 'Evaluating Misstatements',
    subtopic: 'Clearly Trivial',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 450, the auditor may designate a threshold below which misstatements are considered "clearly trivial." This threshold:',
    options: [
      'Is the same as materiality',
      'Is set at an amount below which misstatements would not need to be accumulated because they are inconsequential both individually and in aggregate',
      'Is always zero',
      'Is set by the client',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 450.A2 allows the auditor to set a "clearly trivial" threshold — an amount below which individual misstatements need not be accumulated. This is NOT the same as materiality or performance materiality — it is well below both. The concept recognizes that accumulating very small errors adds no value and creates administrative burden. However, the threshold should be conservative — misstatements are "clearly trivial" only if there is no circumstance in which they could be material (even considering aggregation with other misstatements). A common practice is to set the clearly trivial threshold at 3-5% of overall materiality, though this varies by firm methodology. Misstatements above this threshold must be accumulated.',
    reference: 'AU-C 450.A2',
  },
  {
    id: 'aud-d12-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Inventory Valuation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When testing inventory valuation, the auditor should evaluate:',
    options: [
      'Only whether the physical count is accurate',
      'Whether inventory is properly stated at the lower of cost and net realizable value (or market), whether cost methods are appropriate and consistently applied, and whether obsolete or slow-moving inventory has been properly written down',
      'Only the FIFO calculation',
      'Only the physical condition of inventory',
    ],
    correctAnswer: 1,
    explanation: 'Inventory valuation testing under AU-C 330 and ASC 330 includes: (1) verifying the cost flow assumption (FIFO, weighted average, or specific identification) is appropriate and consistently applied; (2) testing cost accumulation — raw materials cost to purchase orders/invoices, labor and overhead allocation methods for manufactured inventory; (3) lower of cost and NRV (LCNRV) testing — comparing carrying amounts to estimated selling prices less costs to complete and sell; (4) obsolescence evaluation — reviewing slow-moving and obsolete inventory, age of items, management\'s write-down methodology; (5) testing standard cost variances (if applicable); (6) evaluating overhead allocation reasonableness. Physical count accuracy is part of existence testing, not valuation.',
    reference: 'AU-C 330; ASC 330',
  },
  {
    id: 'aud-d12-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Auditor Independence',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 260, the auditor must communicate to those charged with governance regarding independence:',
    options: [
      'Nothing about independence',
      'All relationships between the firm and the entity that could reasonably be thought to bear on independence, any safeguards applied, and the total fees charged for audit and non-audit services',
      'Only if independence is actually impaired',
      'Only in the engagement letter',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 260.15 requires communication about: (1) all relationships between the firm (including network firms) and the entity or its management that, in the auditor\'s professional judgment, could reasonably be thought to bear on independence; (2) related safeguards applied to eliminate or reduce threats to independence; (3) for non-issuers, this communication usually occurs in the engagement letter and through discussions. For issuers (under PCAOB rules), the auditor must communicate in writing: all critical audit matters, relationships that may affect independence, total fees (audit fees, audit-related fees, tax fees, all other fees). This transparency allows those charged with governance to evaluate whether the auditor\'s independence is appropriate.',
    reference: 'AU-C 260.15',
  },
  {
    id: 'aud-d12-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Income Tax Testing',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When auditing the income tax provision (ASC 740), the auditor must evaluate:',
    options: [
      'Only the tax return',
      'Current and deferred tax calculations, the realizability of deferred tax assets (including the valuation allowance), uncertain tax positions (ASC 740-10), and the tax rate reconciliation',
      'Only whether the entity paid its taxes',
      'Only the current tax payable',
    ],
    correctAnswer: 1,
    explanation: 'Income tax testing is complex and covers: (1) Current provision — taxable income computation, applicable tax rates, credits, and carryforwards; (2) Deferred tax — identifying temporary differences, applying appropriate tax rates, evaluating the scheduling of reversal; (3) Valuation allowance — evaluating whether it is "more likely than not" that some or all deferred tax assets will not be realized (requires judgment about future taxable income, tax planning strategies, expiration of carryforwards); (4) Uncertain tax positions — ASC 740-10-25 requires a two-step process (recognition threshold: more likely than not, then measurement at largest cumulative probability >50%); (5) Rate reconciliation — reconciling the effective tax rate to the statutory rate; (6) Disclosures — adequacy of tax-related footnotes.',
    reference: 'AU-C 330; ASC 740',
  },
  {
    id: 'aud-d12-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Oral Explanations',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 230, oral explanations by the auditor:',
    options: [
      'Are sufficient to support the audit opinion on their own',
      'Do not represent adequate support for audit conclusions, but may be used to clarify or explain information contained in the audit documentation',
      'Replace the need for written documentation',
      'Are never acceptable',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 230.A8 clarifies that oral explanations alone are not adequate support for the work the auditor performed or conclusions reached. Written documentation is always required. However, oral explanations may be used to clarify information already contained in the documentation (e.g., explaining the reasoning behind a judgment documented in a workpaper). The principle: if it isn\'t documented, it wasn\'t done. This ensures that the audit trail exists regardless of staff turnover, memory fading, or legal proceedings. Documentation should stand on its own — an experienced auditor should be able to understand the work without needing oral clarification from the engagement team.',
    reference: 'AU-C 230.A8',
  },
  {
    id: 'aud-d12-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Disagreements with Management',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'If the auditor has significant disagreements with management about accounting principles, the auditor should:',
    options: [
      'Accept management\'s position to maintain the relationship',
      'Communicate the disagreements to those charged with governance, whether or not they have been resolved, and evaluate the implications for the audit',
      'Immediately withdraw from the engagement',
      'Only document the disagreement internally',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 260.A31 and AU-C 260.17 require the auditor to communicate to those charged with governance significant difficulties encountered during the audit, including substantive disagreements with management. This includes: (1) disagreements about accounting principles or their application; (2) disagreements about the basis of management\'s judgments on accounting estimates; (3) disagreements about the scope of the audit; (4) potential modifications to the audit report. Communication occurs whether or not the disagreement has been satisfactorily resolved. This enables those charged with governance to exercise their oversight responsibility and, if necessary, intervene. The auditor should not simply acquiesce to management to avoid conflict.',
    reference: 'AU-C 260.17; AU-C 260.A31',
  },
  {
    id: 'aud-d12-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Prepaid and Accrued Expenses',
    difficulty: 'easy',
    skillLevel: 'Application',
    question: 'The most effective approach to testing prepaid insurance for valuation is typically:',
    options: [
      'Confirming with the insurance company',
      'Examining the insurance policy to verify coverage dates and premiums, and recalculating the amount that should be prepaid at year-end by prorating the annual premium over the remaining coverage period',
      'Reviewing only the cash disbursement for the premium payment',
      'Only comparing to the prior-year balance',
    ],
    correctAnswer: 1,
    explanation: 'Prepaid insurance testing for valuation involves: (1) examining the insurance policy or invoice — to determine the total premium amount, coverage period (start and end dates), and type of coverage; (2) recalculating the prepaid amount — prorating the total premium over the remaining coverage period at year-end (e.g., if a $12,000 annual policy effective July 1 has 6 months remaining at December 31, the prepaid balance should be $6,000); (3) verifying payment — examining the canceled check or bank statement for premium payment; (4) evaluating completeness — determining whether all policies are included in the prepaid schedule. This is a predictable balance that lends itself well to recalculation as a substantive procedure.',
    reference: 'AU-C 330',
  },
  {
    id: 'aud-d12-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-misstatements',
    topic: 'Evaluating Misstatements',
    subtopic: 'Prior-Period Misstatements',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When evaluating uncorrected misstatements, the auditor should consider the effect of prior-period uncorrected misstatements on the current period because:',
    options: [
      'Prior-period misstatements automatically self-correct',
      'Some prior-period misstatements affect the current period (e.g., an inventory overstatement at the prior year-end understates current-year cost of goods sold), so the auditor must evaluate the cumulative effect on current-year financial statements',
      'Prior-period misstatements are irrelevant to the current audit',
      'GAAP prohibits considering prior-period misstatements',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 450.A7 addresses the "rollover" effect: some prior-period misstatements reverse and affect the current period. For example: (1) an overstatement of accrued expenses at the prior year-end reduces current-year expenses when reversed; (2) an overstatement of ending inventory at the prior year-end (which carried forward as beginning inventory) will understate current-year cost of goods sold. The auditor must consider both the "rollover" approach (evaluating solely the current-period effect of misstatements) and the "iron curtain" approach (evaluating the cumulative balance sheet effect). SEC guidance (SAB 99/108) requires considering both approaches. The interaction between prior and current period misstatements can be complex and requires careful analysis.',
    reference: 'AU-C 450.A7; SAB 108',
  },
  {
    id: 'aud-d12-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-documentation',
    topic: 'Audit Documentation',
    subtopic: 'Modifications After Report Date',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'After the documentation completion date (60 days after report release), if the auditor needs to add documentation for a matter that existed at the report date but was not documented at the time:',
    options: [
      'The auditor cannot add any documentation',
      'The auditor documents the date the information was added, who made the addition, the specific reasons for the addition, and the effect on the auditor\'s conclusions; existing documentation must not be deleted',
      'The auditor should destroy the existing file and create a new one',
      'Only the engagement partner can authorize additions',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 230.16 through 17 provides strict requirements for post-completion modifications: (1) existing documentation must NOT be deleted or discarded; (2) any additions must document: the date of the addition, who made it, the reasons for the addition, and the specific circumstances; (3) the effect of the new information on the auditor\'s conclusions must be documented; (4) additions after the completion date are rare and should be carefully controlled. This protects the integrity of the audit documentation — it must remain a reliable record of what was known and what work was performed at the time of the original engagement. Tampering with documentation after the fact raises serious professional and legal concerns.',
    reference: 'AU-C 230.16 through 17',
  },
  {
    id: 'aud-d12-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-substantive',
    topic: 'Substantive Procedures',
    subtopic: 'Revenue Recognition Testing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 606, revenue recognition involves a five-step model. When testing revenue recognition, the auditor should evaluate:',
    options: [
      'Only whether cash was received',
      'Whether contracts are properly identified, performance obligations are distinct, transaction prices are correctly determined, prices are properly allocated to performance obligations, and revenue is recognized when performance obligations are satisfied',
      'Only whether invoices were sent to customers',
      'Only the total revenue figure',
    ],
    correctAnswer: 1,
    explanation: 'ASC 606 requires a five-step revenue recognition process that the auditor must evaluate: (1) identify the contract with the customer; (2) identify the performance obligations in the contract; (3) determine the transaction price (including variable consideration, significant financing components, noncash consideration); (4) allocate the transaction price to performance obligations (using standalone selling prices); (5) recognize revenue when (or as) each performance obligation is satisfied (at a point in time or over time). The auditor evaluates management\'s application of each step, particularly for complex arrangements (bundled services, licensing, variable pricing, bill-and-hold, consignment). This is high-risk testing given the presumed fraud risk related to revenue recognition.',
    reference: 'AU-C 240; ASC 606',
  },
  {
    id: 'aud-d12-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-communication',
    topic: 'Communication with Governance',
    subtopic: 'Noncompliance with Laws',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 250, if the auditor becomes aware of possible noncompliance with laws or regulations:',
    options: [
      'The auditor ignores it unless it affects the financial statements',
      'The auditor should obtain an understanding of the nature and circumstances, evaluate the possible effect on the financial statements, communicate the matter to management and those charged with governance, and consider the implications for the audit',
      'The auditor must immediately contact law enforcement',
      'The auditor should accept management\'s assessment without investigation',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 250.16 through 21 outlines the auditor\'s response: (1) obtain an understanding of the nature of the noncompliance and the circumstances, including possible consequences; (2) evaluate whether the noncompliance has a material effect on the financial statements (either directly through fines/penalties or indirectly through contingent liabilities, going concern implications); (3) discuss with management at an appropriate level; (4) communicate with those charged with governance (unless they are involved in the noncompliance); (5) evaluate the effect on the audit opinion; (6) consider whether to report to parties outside the entity (certain statutes or regulations may require external reporting, e.g., Government Auditing Standards, banking regulators). The auditor is not expected to detect all noncompliance but must respond appropriately to identified or suspected noncompliance.',
    reference: 'AU-C 250.16 through 21',
  },
];
