// AUD Depth Questions - Batch 6
// Focus: AUD-II (Assessing Risk) and AUD-III (Performing Further Procedures)
// Topics: Risk response, substantive procedures, sampling, tests of controls
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const AUD_QUESTIONS_DEPTH_6: Question[] = [
  {
    id: 'aud-d6-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Related Parties',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 550, when the auditor identifies a significant related party transaction outside the entity\'s normal course of business, the auditor should:',
    options: [
      'Ignore it if management approves',
      'Evaluate whether the business rationale suggests the transaction may have been entered into for fraudulent financial reporting or concealment of misappropriation',
      'Automatically issue a qualified opinion',
      'Withdraw from the engagement',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 550.18, the auditor must evaluate significant related party transactions outside the normal course of business to determine: (1) Whether the business rationale (or lack thereof) suggests the transaction may have been entered into to engage in fraudulent financial reporting or to CONCEAL misappropriation of assets. (2) Whether the terms are consistent with management\'s explanations. (3) Whether the transaction is properly accounted for and disclosed. Unusual related party transactions are FRAUD RISK INDICATORS. The auditor should obtain evidence about the nature, terms, and business purpose. The auditor should also be alert to related parties or transactions not previously identified or disclosed by management.',
    reference: 'AU-C 550.18',
  },
  {
    id: 'aud-d6-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Analytical Procedures in Risk Assessment',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Analytical procedures performed during the planning/risk assessment phase are:',
    options: [
      'Optional and rarely used',
      'REQUIRED — they help identify unusual relationships and unexpected differences that may indicate risks of material misstatement',
      'Only used for review engagements, not audits',
      'Performed only by senior partners',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 315.06(b) and AU-C 520.06, analytical procedures are REQUIRED at two points in an audit: (1) During PLANNING/RISK ASSESSMENT — to understand the entity and identify areas of potential risk. These help the auditor identify unusual fluctuations, relationships, and trends that may indicate misstatement risk. (2) At the OVERALL REVIEW stage (near the end of the audit) — to assess whether the financial statements are consistent with the auditor\'s understanding. Analytical procedures are also OPTIONALLY used as SUBSTANTIVE procedures during fieldwork (substantive analytical procedures). Planning-phase analytics are typically "high-level" — comparing current-year data to prior year, budget, industry, and nonfinancial data.',
    reference: 'AU-C 315.06(b); AU-C 520.06',
  },
  {
    id: 'aud-d6-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Sufficient Appropriate Audit Evidence',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 500, audit evidence must be both sufficient and appropriate. "Sufficiency" refers to:',
    options: [
      'The quality and relevance of evidence',
      'The QUANTITY of audit evidence — enough evidence to support the auditor\'s conclusions',
      'The source of the evidence',
      'The persuasiveness of the evidence',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 500.05: SUFFICIENCY = the QUANTITY of audit evidence. The quantity needed is affected by: (a) the assessed risk of misstatement (higher risk → more evidence), (b) the quality/appropriateness of evidence (higher quality → less quantity needed). APPROPRIATENESS = the QUALITY of audit evidence — its relevance and reliability. Reliability factors include: (1) Source (external > internal), (2) Internal controls over preparation (effective controls → more reliable), (3) Direct auditor knowledge (inspection/observation > inquiry), (4) Documentary form (written > oral), (5) Original documents > copies. Both sufficiency and appropriateness are needed — one cannot compensate for a deficiency in the other.',
    reference: 'AU-C 500.05',
  },
  {
    id: 'aud-d6-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Types of Audit Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 500, which of the following is NOT a type of audit procedure for obtaining evidence?',
    options: [
      'Inspection of records and documents',
      'Observation',
      'Estimation',
      'External confirmation',
    ],
    correctAnswer: 2,
    explanation: 'Under AU-C 500.A18, audit procedures for obtaining evidence include: (1) INSPECTION — examining records, documents, or tangible assets. (2) OBSERVATION — watching a process or procedure performed by others. (3) EXTERNAL CONFIRMATION — obtaining a direct response from a third party. (4) RECALCULATION — checking mathematical accuracy. (5) REPERFORMANCE — independently executing a control or procedure. (6) ANALYTICAL PROCEDURES — evaluating financial information through analysis of relationships. (7) INQUIRY — seeking information from knowledgeable persons. ESTIMATION is not an audit procedure — it is an activity performed by MANAGEMENT (the auditor evaluates management\'s estimates, but "estimation" itself is a management responsibility, not an audit evidence-gathering technique).',
    reference: 'AU-C 500.A18',
  },
  {
    id: 'aud-d6-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'External Confirmations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A "positive" confirmation request asks the respondent to:',
    options: [
      'Respond only if they disagree with the stated amount',
      'Respond in ALL cases — either by confirming the information is correct OR by providing the correct information',
      'Provide a bank statement',
      'Sign a management representation letter',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 505: POSITIVE confirmation: the auditor asks the respondent to reply in ALL cases — either confirming the balance or providing a different amount. Types: (a) Blank form — asks respondent to fill in the amount (more reliable but lower response rate). (b) Amount-included — states the balance and asks for confirmation or correction. NEGATIVE confirmation: asks the respondent to reply ONLY if they DISAGREE with the stated information. Negative confirmations provide less reliable evidence because nonresponse could mean either agreement or that the respondent merely did not reply. Positive confirmations are required for: (1) Significant individual items, (2) Higher assessed risk of misstatement, (3) Situations where negative confirmations would not be appropriate.',
    reference: 'AU-C 505.A7-.A8',
  },
  {
    id: 'aud-d6-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Tests of Controls vs. Substantive Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 330, tests of controls are performed to:',
    options: [
      'Detect material misstatements in account balances',
      'Evaluate the OPERATING EFFECTIVENESS of internal controls in preventing or detecting material misstatements',
      'Determine the fair value of assets',
      'Verify the mathematical accuracy of the trial balance',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 330.08, tests of controls evaluate whether controls are OPERATING EFFECTIVELY (not just designed effectively). The auditor tests controls when: (1) The risk assessment includes an expectation that controls are operating effectively (i.e., the auditor plans to RELY on controls). (2) Substantive procedures alone cannot provide sufficient evidence at the assertion level. Techniques include: inquiry, observation, inspection of documents showing control performance, and REPERFORMANCE. For controls the auditor intends to rely on, the auditor tests those controls in the CURRENT period. In contrast, SUBSTANTIVE procedures (tests of details and substantive analytical procedures) directly test whether misstatements exist in account balances, transactions, or disclosures.',
    reference: 'AU-C 330.08',
  },
  {
    id: 'aud-d6-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Statistical vs. Nonstatistical Sampling',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 530, audit sampling may be either statistical or nonstatistical. A key difference is that statistical sampling:',
    options: [
      'Is always superior to nonstatistical',
      'Involves random selection and allows the auditor to measure sampling risk mathematically',
      'Eliminates nonsampling risk',
      'Does not require professional judgment',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 530.05: STATISTICAL sampling uses random (probability) selection methods and probability theory to evaluate results, allowing the auditor to QUANTIFY the sampling risk (the risk that the sample conclusion differs from what would have been reached by examining the entire population). NONSTATISTICAL sampling uses auditor judgment for sample selection and evaluation — sampling risk cannot be quantified. Both approaches can produce effective results when properly designed. Neither eliminates non-sampling risk (e.g., applying inappropriate procedures, failing to recognize an error in a sample item). The choice between statistical and nonstatistical is a matter of auditor JUDGMENT — GAAS does not require one over the other.',
    reference: 'AU-C 530.05',
  },
  {
    id: 'aud-d6-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Management Representations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 580, management representations (the management representation letter) are:',
    options: [
      'Optional and used only for review engagements',
      'REQUIRED written representations from management confirming certain matters — including that the financial statements are presented fairly and that management has provided all relevant information to the auditor',
      'Verbal representations given during the planning phase',
      'Provided by the external legal counsel',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 580.06-.09, written management representations are REQUIRED for every audit. The letter must: (1) Be addressed to the auditor. (2) Be dated the same date as the auditor\'s report. (3) Be signed by the CEO and CFO (or equivalents). Required representations include: (a) Management\'s responsibility for the FS. (b) Completeness of information provided. (c) All transactions have been recorded. (d) All known fraud or suspected fraud has been disclosed. (e) Subsequent events have been addressed. (f) Related party transactions are properly disclosed. If management REFUSES to provide written representations, it is a SCOPE LIMITATION — the auditor should consider disclaiming an opinion or withdrawing from the engagement.',
    reference: 'AU-C 580.06-.09',
  },
  {
    id: 'aud-d6-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Substantive Analytical Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When using substantive analytical procedures to test an assertion, the auditor must:',
    options: [
      'Only compare current year to prior year amounts',
      'Develop an independent expectation with a reasonable degree of precision and investigate significant differences between the expectation and recorded amounts',
      'Use the same analytical procedures as the planning phase',
      'Rely solely on management\'s explanations without further investigation',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 520.A16, when using substantive analytical procedures: (1) Develop an INDEPENDENT EXPECTATION — what the auditor expects the balance or ratio to be, based on financial data, nonfinancial data, industry trends, budgets, or other sources. (2) Define the THRESHOLD for significant differences (considering materiality and desired assurance level). (3) COMPARE the expectation to recorded amounts and identify differences exceeding the threshold. (4) INVESTIGATE significant differences by obtaining corroborative evidence/explanations and evaluating whether they indicate a misstatement. The reliability of the expectation depends on: data reliability, independence of the data source, predictability of the relationship, and precision of the expectation. More precise expectations provide stronger evidence.',
    reference: 'AU-C 520.A16',
  },
  {
    id: 'aud-d6-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Inventory Observation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 501, when inventory is material, the auditor should:',
    options: [
      'Accept management\'s count without independent verification',
      'Attend the physical inventory count to observe the counting procedures and perform test counts, unless impracticable',
      'Only review the perpetual records',
      'Hire a third-party specialist to count all inventory',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 501.04, when inventory is material, the auditor should: (1) ATTEND the physical inventory counting to: (a) evaluate management\'s instructions and procedures, (b) OBSERVE the performance of management\'s count procedures, (c) INSPECT the inventory, and (d) perform TEST COUNTS. (2) Perform procedures over the entity\'s final inventory records to determine whether they accurately reflect the actual count. If attendance at the count is IMPRACTICABLE (e.g., inventory at remote locations), the auditor performs alternative procedures or considers the effect on the opinion. If the entity uses perpetual inventory records, the auditor also evaluates whether those records are reliable. The count date need not be the year-end date if controls over inventory movements between the count date and year-end are tested.',
    reference: 'AU-C 501.04',
  },
  {
    id: 'aud-d6-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Sampling Risk vs. Nonsampling Risk',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 530, sampling risk is:',
    options: [
      'The risk that the auditor selects a biased sample',
      'The risk that the auditor\'s conclusion based on a sample differs from the conclusion that would be reached by examining the entire population',
      'The risk of testing too many items',
      'The risk of a computer error in the sampling software',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 530.05, SAMPLING RISK is the risk that the auditor\'s conclusion based on a SAMPLE may differ from the conclusion that would have been reached if the auditor had tested the ENTIRE population. Sampling risk can be reduced by increasing sample size. Two types: (1) Risk of OVERRELIANCE (Type II): concluding controls are effective when they are not, or that a material misstatement does not exist when it does. (2) Risk of UNDERRELIANCE (Type I): concluding controls are ineffective when they are effective, or that a material misstatement exists when it does not. NONSAMPLING risk includes all other causes of error — applying wrong procedures, failing to recognize errors in samples, or misinterpreting results. Nonsampling risk is reduced through training, supervision, and quality review — NOT by increasing sample size.',
    reference: 'AU-C 530.05',
  },
  {
    id: 'aud-d6-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Accounting Estimates',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under AU-C 540, when evaluating management\'s accounting estimates, the auditor does all of the following EXCEPT:',
    options: [
      'Evaluates the reasonableness of assumptions and methods used',
      'Tests the data on which the estimate is based',
      'Develops their own independent estimate and replaces management\'s estimate with it',
      'Considers subsequent events that may provide evidence about the estimate',
    ],
    correctAnswer: 2,
    explanation: 'Under AU-C 540, the auditor evaluates management\'s estimates through one or more approaches: (1) Reviewing and testing the process used by management — methods, assumptions, data. (2) Developing an independent expectation (point estimate or range) for comparison. (3) Reviewing subsequent events/transactions that may provide evidence. The auditor does NOT simply REPLACE management\'s estimate with their own. If management\'s estimate is reasonable within a range of acceptable outcomes, the auditor accepts it. If the auditor develops a different point estimate, the resulting difference from management\'s estimate is evaluated for whether it represents a misstatement. The auditor also evaluates estimates for MANAGEMENT BIAS — per AU-C 240, biased estimates are a fraud indicator.',
    reference: 'AU-C 540.08-.13',
  },
  {
    id: 'aud-d6-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Using the Work of an Auditor\'s Specialist',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 620, when the auditor uses the work of an auditor\'s specialist (e.g., an actuary for pension valuations), the auditor:',
    options: [
      'Can delegate full responsibility to the specialist',
      'Remains responsible for the audit opinion — the auditor must evaluate the specialist\'s competence, capabilities, objectivity, and the adequacy and reasonableness of their findings',
      'Must be qualified as a specialist in that field',
      'Must disclose the specialist\'s name in the audit report',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 620.06-.11, the auditor is SOLELY responsible for the audit opinion, regardless of using a specialist. The auditor must: (1) Evaluate the specialist\'s COMPETENCE, capabilities, and OBJECTIVITY (including potential threats such as financial interest in the client). (2) Obtain an understanding of the specialist\'s field sufficient to determine the nature, scope, and objectives of the work. (3) Evaluate the ADEQUACY of the specialist\'s work — including assumptions, methods, and findings. (4) Evaluate the relevance and reasonableness of the specialist\'s findings as audit evidence. The auditor\'s report should NOT reference the specialist unless required to explain a modification to the opinion. The specialist\'s name is generally not mentioned to avoid the impression of shared responsibility.',
    reference: 'AU-C 620.06-.11',
  },
  {
    id: 'aud-d6-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Audit Documentation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 230, audit documentation (workpapers) should be sufficient to enable:',
    options: [
      'Only the engagement partner to understand the work',
      'An experienced auditor, having no previous connection with the audit, to understand the nature, timing, extent of procedures, evidence obtained, and conclusions reached',
      'The client to verify the auditor\'s work',
      'Only regulatory agencies to review the audit',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 230.08, audit documentation must be sufficient to: (1) Enable an EXPERIENCED AUDITOR with NO PREVIOUS CONNECTION to the audit to understand: (a) the nature, timing, and extent of audit procedures performed, (b) the results of procedures and evidence obtained, and (c) significant matters arising and conclusions reached. (2) Demonstrate compliance with GAAS. (3) Serve as a basis for planning future audits. The documentation completion date is typically 60 days after the report release date (AU-C 230.16). After the documentation completion date, existing documentation should not be deleted/discarded but may be supplemented. Common documentation includes audit programs, confirmations, analyses, schedules, and memoranda.',
    reference: 'AU-C 230.08',
  },
  {
    id: 'aud-d6-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Inquiry as Evidence',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 500, inquiry alone is generally:',
    options: [
      'Sufficient evidence to support an assertion',
      'INSUFFICIENT evidence on its own — inquiry must be corroborated with other audit procedures',
      'Not an acceptable audit procedure',
      'The strongest form of evidence',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 500.A25, inquiry consists of seeking information from knowledgeable persons — both financial and nonfinancial — within or outside the entity. While inquiry is important and can provide valuable information, it generally DOES NOT provide SUFFICIENT APPROPRIATE evidence on its own to: (1) Detect material misstatements, or (2) Test the operating effectiveness of controls. Inquiry must be CORROBORATED with other procedures such as: inspection, observation, recalculation, or external confirmation. However, inquiry is the ONLY required procedure for certain matters (e.g., inquiring of legal counsel about litigation under AU-C 501, inquiring about subsequent events under AU-C 560). Even then, the responses are evaluated and may require corroboration.',
    reference: 'AU-C 500.A25',
  },
  {
    id: 'aud-d6-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Understanding Services Organizations (SOC Reports)',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'When a client uses a service organization that is significant to the audit, the user auditor may obtain a SOC 1 Type 2 report. This report includes:',
    options: [
      'Only management\'s description of the service organization\'s system',
      'A description of the system AND the service auditor\'s opinion on whether controls were suitably designed AND operating effectively during the specified period',
      'Only the operating effectiveness of controls',
      'The service organization\'s financial statements',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 402 and SSAE 18 (AT-C 320): SOC 1 Type 1 report: (1) Management\'s description of the service organization\'s system. (2) Service auditor\'s opinion on whether controls are SUITABLY DESIGNED as of a specified date. (3) Does NOT test operating effectiveness. SOC 1 Type 2 report: (1) Description of the system. (2) Service auditor\'s opinion on the DESIGN and OPERATING EFFECTIVENESS of controls over a specified PERIOD (e.g., Oct 1 – Sep 30). (3) Includes test results and control objectives tested. The user auditor evaluates the SOC report\'s: coverage period, scope/complementary user entity controls, any exceptions/deviations noted, and whether the report covers the relevant period. SOC 2 and SOC 3 reports focus on trust services criteria (security, availability, etc.) and are generally NOT relevant for financial statement audits.',
    reference: 'AU-C 402; SSAE 18 (AT-C 320)',
  },
  {
    id: 'aud-d6-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Litigation, Claims, and Assessments',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 501, the auditor obtains evidence about litigation, claims, and assessments primarily through:',
    options: [
      'Reading industry publications',
      'Inquiry of management and a letter of audit inquiry sent to the client\'s external legal counsel',
      'Physical observation of court proceedings',
      'Recalculation of potential liability amounts',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 501.09-.11, the auditor\'s procedures for litigation/claims: (1) INQUIRY of management — about pending/threatened litigation, claims, and assessments. (2) Review of MINUTES of board meetings. (3) Review of legal invoices and documents. (4) Obtain a list of legal matters from management and send a LETTER OF AUDIT INQUIRY to the client\'s EXTERNAL LEGAL COUNSEL (the "legal letter"). The legal letter asks counsel to corroborate management\'s representations about: pending/threatened litigation, evaluation of likelihood of unfavorable outcome, and estimated amounts. Counsel is expected to respond with: confirmation of matters listed, comment on their status, and may indicate inability to evaluate certain matters. If counsel REFUSES to respond, it is a scope limitation.',
    reference: 'AU-C 501.09-.11',
  },
  {
    id: 'aud-d6-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Subsequent Events Procedures',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 560, the auditor\'s responsibility for subsequent events extends through:',
    options: [
      'The balance sheet date',
      'The date of the auditor\'s report (the date the auditor has obtained sufficient appropriate audit evidence to support the opinion)',
      'Three months after year-end',
      'The date the financial statements are filed with the SEC',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 560.06, the auditor has an ACTIVE responsibility to perform procedures to identify subsequent events that require adjustment or disclosure through the DATE OF THE AUDITOR\'S REPORT. After the report date but before issuance: the auditor has no obligation to perform procedures, but if facts become known that might have caused a modification, the auditor discusses with management and considers whether the FS need revision (AU-C 560.10). After issuance: if the auditor becomes aware of facts existing at the report date that would have affected the report, the auditor takes action under AU-C 560.14. Subsequent event procedures include: inquiries of management, reading minutes, reviewing latest interim FS, and making inquiries of legal counsel.',
    reference: 'AU-C 560.06-.10',
  },
  {
    id: 'aud-d6-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Attribute Sampling',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Attribute sampling is most commonly used for:',
    options: [
      'Estimating the dollar value of an account balance',
      'Testing the RATE of control deviations (determining if the rate of departures from a prescribed control exceeds a tolerable rate)',
      'Projecting total account balance errors',
      'Sending confirmations',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 530, ATTRIBUTE sampling is used for TESTS OF CONTROLS. It estimates the RATE (percentage) of deviations from a prescribed control procedure in the population. Key concepts: Expected deviation rate: the rate of deviations the auditor expects to find (based on prior experience). Tolerable deviation rate: the maximum deviation rate the auditor will accept while still relying on the control (typically 5%–10%). Allowance for sampling risk: the margin for error. If the sample deviation rate + allowance for sampling risk ≤ tolerable rate: the auditor can conclude the control is effective. If it exceeds: the control cannot be relied upon. VARIABLES sampling (MUS, classical) is used for substantive testing — estimating the dollar amount of misstatement in a population.',
    reference: 'AU-C 530.A9',
  },
  {
    id: 'aud-d6-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Reliability of Evidence — Source Hierarchy',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under AU-C 500, audit evidence is generally MORE reliable when:',
    options: [
      'It is obtained verbally from management',
      'It is obtained from EXTERNAL sources independent of the entity, in documentary form, and generated under effective internal controls',
      'It is photographic evidence',
      'It is obtained from the internet',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 500.A5-.A10, reliability generalizations: (1) EXTERNAL evidence (from third parties) > INTERNAL evidence (from the entity). (2) Evidence is more reliable when internal controls over its preparation are EFFECTIVE. (3) Evidence obtained DIRECTLY by the auditor (observation, inspection, recalculation) > evidence obtained indirectly (inquiry). (4) DOCUMENTARY evidence (written/electronic) > ORAL evidence. (5) ORIGINAL documents > copies. (6) Formal professional or institutional confirmations > informal responses. These are general rules — the auditor applies judgment considering the specific circumstances. Corroborating evidence from multiple sources increases overall reliability. Contradictory evidence requires additional investigation.',
    reference: 'AU-C 500.A5-.A10',
  },
  {
    id: 'aud-d6-021',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Planned Detection Risk',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When the auditor assesses inherent risk and control risk as HIGH for a particular assertion, planned detection risk is:',
    options: [
      'Also set high',
      'Set LOW — the auditor must design more extensive substantive procedures to reduce detection risk to an acceptably low level',
      'Set at the same level as inherent risk',
      'Irrelevant to planning',
    ],
    correctAnswer: 1,
    explanation: 'Under the audit risk model: AR = IR × CR × DR. Audit risk (AR) is set at an acceptable level (typically low). If IR and CR are HIGH, detection risk (DR) must be LOW to keep overall AR at the desired level. DR = AR / (IR × CR). When DR is low, the auditor must design MORE EXTENSIVE substantive procedures: (1) Larger sample sizes. (2) More persuasive evidence. (3) Tests performed closer to year-end (rather than at interim). (4) Greater reliance on tests of details rather than analytical procedures. Conversely, if IR and CR are low (e.g., strong controls in a low-risk area), DR can be higher, allowing less extensive substantive testing. The inverse relationship between assessed risk and planned detection risk is FUNDAMENTAL to audit planning.',
    reference: 'AU-C 330.07; AU-C 200.A44',
  },
  {
    id: 'aud-d6-022',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Using the Work of Internal Auditors',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under AU-C 610, when the external auditor uses the work of internal auditors, the external auditor:',
    options: [
      'Can outsource all testing to internal audit',
      'Must evaluate internal audit\'s competence, objectivity, and systematic/disciplined approach, and then REPERFORM some of the work to evaluate its adequacy',
      'Accepts internal audit\'s conclusions without review',
      'Must perform all procedures independently without using internal audit',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 610.07-.09, the external auditor may use internal auditors\' work but must: (1) Evaluate the internal audit function\'s: COMPETENCE (qualifications, training), OBJECTIVITY (reporting structure, freedom from conflicting responsibilities), and APPLICATION OF A SYSTEMATIC AND DISCIPLINED APPROACH (quality control, documentation). (2) Evaluate the ADEQUACY of specific internal audit work for the external audit\'s purposes — including REPERFORMING some of the work. (3) Not use internal audit to perform procedures in areas of: significant judgment, higher risk of material misstatement, or where the external auditor\'s own procedures are needed. The external auditor remains SOLELY RESPONSIBLE for the audit opinion. Internal auditors may also provide DIRECT ASSISTANCE under specific circumstances (AU-C 610.24).',
    reference: 'AU-C 610.07-.09',
  },
  {
    id: 'aud-d6-023',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Monetary Unit Sampling (MUS)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Monetary unit sampling (MUS) is a variables sampling technique particularly useful for:',
    options: [
      'Testing control deviation rates',
      'Testing for OVERSTATEMENT — it selects individual dollar units, giving larger items a proportionally greater chance of selection',
      'Testing only understated amounts',
      'Selecting audit team members',
    ],
    correctAnswer: 1,
    explanation: 'Monetary Unit Sampling (MUS, also called probability-proportional-to-size or PPS) is a variables sampling technique: (1) The sampling UNIT is an individual dollar rather than an individual transaction. (2) Larger dollar items have a HIGHER probability of selection (proportional to their size). (3) Zero/negative balances receive NO chance of selection. (4) Most effective for detecting OVERSTATEMENTS — since larger items are more likely selected, overstatements are efficiently detected. (5) Advantages: simple to apply, automatically stratifies the population, can be used with smaller sample sizes. (6) Limitations: not effective for UNDERSTATEMENT testing (zero balances are never selected), assumption of zero misstatement may overstate required sample size, and results can be difficult to evaluate when many misstatements are found.',
    reference: 'AU-C 530.A22',
  },
  {
    id: 'aud-d6-024',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Control Deficiency vs. Significant Deficiency vs. Material Weakness',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under AU-C 265, a MATERIAL WEAKNESS in internal control is defined as:',
    options: [
      'Any deficiency in internal control',
      'A deficiency (or combination of deficiencies) such that there is a REASONABLE POSSIBILITY that a material misstatement of the financial statements will not be prevented or detected on a timely basis',
      'A deficiency that management considers unimportant',
      'A deficiency that has already resulted in a misstatement',
    ],
    correctAnswer: 1,
    explanation: 'Under AU-C 265.07: Control DEFICIENCY: design or operation of a control does not allow management or employees to prevent/detect misstatements on a timely basis. SIGNIFICANT DEFICIENCY: a deficiency (or combination) that is less severe than a material weakness but important enough to merit attention by those charged with governance. MATERIAL WEAKNESS: a deficiency (or combination) such that there is a REASONABLE POSSIBILITY that a MATERIAL misstatement will NOT be prevented or detected on a timely basis. "Reasonable possibility" means more than remote. The auditor must communicate: (1) Material weaknesses — in WRITING to management AND those charged with governance. (2) Significant deficiencies — in WRITING to those charged with governance. The auditor is not required to search for deficiencies but must evaluate any that come to attention.',
    reference: 'AU-C 265.07-.09',
  },
  {
    id: 'aud-d6-025',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Cash — Proof of Cash (Bank Reconciliation)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A "proof of cash" (four-column bank reconciliation) helps the auditor detect all of the following EXCEPT:',
    options: [
      'Deposits in transit not recorded',
      'Outstanding checks omitted from the reconciliation',
      'Cash receipts recorded in the books but not deposited',
      'Unauthorized purchases made with company credit cards',
    ],
    correctAnswer: 3,
    explanation: 'A proof of cash reconciles BOTH the beginning and ending bank balances to book balances AND the receipts and disbursements for the period. It has four columns: (1) Beginning balance reconciliation, (2) Receipts (per bank vs. per books), (3) Disbursements (per bank vs. per books), (4) Ending balance reconciliation. This procedure is effective for detecting: (a) Deposits in transit not recorded in the books. (b) Outstanding checks omitted. (c) Cash receipts recorded in books but not deposited (lapping/skimming). (d) Unauthorized or unrecorded disbursements. It does NOT directly detect unauthorized CREDIT CARD purchases, because those do not flow through the bank account (they flow through accounts payable/credit card statements). Credit card fraud requires separate procedures on credit card statements.',
    reference: 'AU-C 330; Audit practice guidance',
  },
];
