// AUD - Auditing Elite Questions
// 2026 CPA Exam Blueprint Compliant
// World-Class expansion - Elite batch (Final Push)

import { Question } from '../../../types';

export const AUD_QUESTIONS_ELITE: Question[] = [
  {
    id: 'aud-elite-001',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Component Auditor',
    difficulty: 'hard',
    blueprintArea: 'AUD-II',
    skillLevel: 'Evaluation',
    question: 'When using the work of a component auditor, the group auditor must:',
    options: [
      'Obtain written guarantee',
      'Accept all component work without review',
      'Evaluate component auditor competence, communicate involvement, and evaluate sufficiency of evidence',
      'Perform all audit procedures directly',
    ],
    correctAnswer: 2,
    explanation: 'Component auditor (AS 1205/AU-C 600): group auditor evaluates independence and competence, determines involvement level, communicates requirements, evaluates sufficiency of work and evidence for group opinion.',
    reference: 'AU-C 600',
  },
  {
    id: 'aud-elite-003',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'IT General Controls',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Analysis',
    question: 'IT general controls (ITGCs) include:',
    options: [
      'Access security, change management, operations, and backup/recovery controls',
      'Financial statement preparation',
      'Only password requirements',
      'Transaction processing only',
    ],
    correctAnswer: 0,
    explanation: 'ITGCs: pervasive controls supporting application controls. Categories: access to programs/data, program changes, computer operations, program development, backup/recovery. Weakness may affect multiple applications.',
    reference: 'COSO IT Framework',
  },
  {
    id: 'aud-elite-004',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Tolerable Rate of Deviation',
    difficulty: 'hard',
    blueprintArea: 'AUD-III',
    skillLevel: 'Analysis',
    question: 'Tolerable rate of deviation in control testing is:',
    options: [
      'Allowable risk',
      'Sample size',
      'Expected rate of deviation',
      'Maximum control failure rate auditor can accept and still rely on the control',
    ],
    correctAnswer: 3,
    explanation: 'Tolerable rate: maximum rate of deviation from control auditor willing to accept. Based on planned reliance on control. Lower tolerable rate = larger sample needed. Consider planned reduction in substantive procedures.',
    reference: 'AU-C 530',
  },
  {
    id: 'aud-elite-005',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-procedures',
    topic: 'Audit Procedures',
    subtopic: 'Subsequent Events Procedures',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Application',
    question: 'Subsequent events procedures include:',
    options: [
      'Physical inventory count',
      'Inquiries, reading minutes, reviewing subsequent financial data, and obtaining written representations',
      'Only reading minutes',
      'Confirming receivables again',
    ],
    correctAnswer: 1,
    explanation: 'Subsequent events procedures (AU-C 560): read minutes through date of report, inquire of management about subsequent events, obtain written representations, read subsequent interim financial statements, review legal correspondence.',
    reference: 'AU-C 560',
  },
  {
    id: 'aud-elite-006',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Critical Audit Matters',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Evaluation',
    question: 'Critical Audit Matters (CAMs) are:',
    options: [
      'Matters communicated to audit committee involving challenging judgment or complex estimates arising from the audit',
      'Going concern issues',
      'All material accounts',
      'Control deficiencies',
    ],
    correctAnswer: 0,
    explanation: 'CAMs (AS 3101): matters communicated to audit committee that (1) relate to material accounts/disclosures, (2) involve especially challenging, subjective, or complex auditor judgment. Describe matter and audit response.',
    reference: 'AS 3101',
  },
  {
    id: 'aud-elite-008',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-procedures',
    topic: 'Audit Procedures',
    subtopic: 'Related Party Transactions',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Analysis',
    question: 'Auditing related party transactions requires:',
    options: [
      'Understanding relationships, evaluating business purpose, and testing authorization and disclosure',
      'Standard substantive procedures',
      'Management inquiry sufficient',
      'Confirmation only',
    ],
    correctAnswer: 0,
    explanation: 'Related party procedures (AU-C 550): understand nature of relationships, evaluate business purpose, test authorization, obtain management representations, evaluate disclosure adequacy. Higher risk of manipulation.',
    reference: 'AU-C 550',
  },
  {
    id: 'aud-elite-009',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'External Confirmation Exceptions',
    difficulty: 'hard',
    blueprintArea: 'AUD-III',
    skillLevel: 'Analysis',
    question: 'When confirmation exceptions occur, the auditor must:',
    options: [
      'Investigate the nature and cause, including determining if indicative of misstatement',
      'Ignore small differences',
      'Adjust financial statements',
      'Confirm again',
    ],
    correctAnswer: 0,
    explanation: 'Confirmation exceptions (AU-C 505): investigate cause - timing differences, amounts actually different, confirmation process issues. Determine if misstatement exists. May indicate fraud risk. Document resolution.',
    reference: 'AU-C 505',
  },
  {
    id: 'aud-elite-010',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Other Information',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Application',
    question: 'The auditor\'s responsibility for "Other Information" in documents containing audited F/S is to:',
    options: [
      'Audit the other information',
      'Read and consider whether it is materially inconsistent with F/S or auditor\'s knowledge',
      'Provide separate opinion',
      'Ignore it',
    ],
    correctAnswer: 1,
    explanation: 'Other information (AU-C 720): read for material inconsistency with F/S or auditor\'s knowledge. Not required to audit. If inconsistency exists: discuss with management, consider impact on audit report.',
    reference: 'AU-C 720',
  },
  {
    id: 'aud-elite-011',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Monitoring Activities',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Analysis',
    question: 'The monitoring component of COSO includes:',
    options: [
      'Ongoing evaluations, separate evaluations, and evaluation of deficiencies',
      'Control activities',
      'Only external audits',
      'Risk assessment only',
    ],
    correctAnswer: 0,
    explanation: 'COSO monitoring: ongoing evaluations (built into processes), separate evaluations (periodic), and reporting deficiencies. Provides assurance IC operating effectively. Internal audit often performs this function.',
    reference: 'COSO Framework - Monitoring',
  },
  {
    id: 'aud-elite-012',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-II',
    topic: 'Risk Assessment',
    subtopic: 'Fraud Risk Factors',
    difficulty: 'hard',
    skillLevel: 'Evaluation',
    question: 'An auditor identifies significant risk of material misstatement due to fraud in revenue recognition. Under AU-C 240, which of the following audit responses would be LEAST effective?',
    options: [
      'Performing substantive analytical procedures on revenue using disaggregated data',
      'Assigning more experienced staff to audit revenue',
      'Relying on management\'s representations that revenue recognition policies comply with GAAP',
      'Examining a sample of customer contracts for evidence that performance obligations were satisfied before revenue was recognized',
    ],
    correctAnswer: 2,
    explanation: 'When significant fraud risk is identified, relying on management\'s representations alone is insufficient because management could be the perpetrator. Effective responses include: substantive testing at the assertion level (contract examination), analytical procedures with precise expectations, use of experienced staff, and unpredictable audit procedures. Management representations complement but never replace testing for significant risks.',
    reference: 'AU-C 240',
  },
  {
    id: 'aud-elite-013',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-procedures',
    topic: 'Audit Procedures',
    subtopic: 'Management Representations',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Application',
    question: 'Written representations from management:',
    options: [
      'Are required, cover specific matters, and are dated as of report date',
      'Substitute for other evidence',
      'Only cover fraud',
      'Are optional',
    ],
    correctAnswer: 0,
    explanation: 'Representations (AU-C 580): required audit evidence. Dated as of auditor\'s report date. Specific and general matters. Signed by CEO and CFO (or equivalent). Refusal = scope limitation (withdraw or disclaim).',
    reference: 'AU-C 580',
  },
  {
    id: 'aud-elite-014',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-IV',
    topic: 'Attestation Engagements',
    subtopic: 'Agreed-Upon Procedures',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'An entity engages a CPA to perform agreed-upon procedures on compliance with debt covenant requirements. Two banks are the specified parties. During the engagement, the CPA discovers a covenant violation the entity was unaware of. What is the CPA\'s obligation?',
    options: [
      'Report the violation to the banks immediately',
      'Include the finding in the AUP report as a factual result of applying the agreed-upon procedures',
      'Recommend corrective action to management and withhold the finding from the report',
      'Withdraw from the engagement because a violation creates a conflict of interest',
    ],
    correctAnswer: 1,
    explanation: 'In an AUP engagement, the CPA reports factual findings resulting from performing the agreed procedures. If a procedure reveals a covenant violation, it is reported as a finding. The CPA does not act as an advocate for either party, does not provide assurance or recommendations, and does not unilaterally notify third parties. The specified parties draw their own conclusions from the findings.',
    reference: 'AT-C 215',
  },
  {
    id: 'aud-elite-015',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Emphasis of Matter',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Application',
    question: 'An Emphasis-of-Matter paragraph is used when:',
    options: [
      'Fraud is discovered',
      'Auditor wishes to draw attention to a matter appropriately presented that is fundamental to users\' understanding',
      'Opinion is qualified',
      'Going concern exists',
    ],
    correctAnswer: 1,
    explanation: 'EOM (AU-C 706): draw attention to matter presented/disclosed that is fundamental to understanding. Not for uncertainties affecting opinion. Examples: significant related party transactions, subsequent events. Placed after opinion.',
    reference: 'AU-C 706',
  },
  {
    id: 'aud-elite-016',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-ethics',
    topic: 'Professional Responsibilities',
    subtopic: 'Audit Documentation Retention',
    difficulty: 'hard',
    blueprintArea: 'AUD-I',
    skillLevel: 'Application',
    question: 'Audit documentation for issuers must be retained for:',
    options: [
      '5 years',
      '10 years',
      '7 years from report release date',
      '3 years',
    ],
    correctAnswer: 2,
    explanation: 'PCAOB retention: 7 years from report date. AICPA (non-issuers): 5 years. Documentation completion deadline: 45 days (PCAOB) or 60 days (AICPA) from report release. Changes after completion require addendum.',
    reference: 'AS 1215',
  },
  {
    id: 'aud-elite-017',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Monetary Unit Sampling',
    difficulty: 'hard',
    blueprintArea: 'AUD-III',
    skillLevel: 'Analysis',
    question: 'Monetary unit sampling (MUS) is designed to:',
    options: [
      'Give larger items higher selection probability and project misstatements to population',
      'Test all transactions equally',
      'Sample physical inventory',
      'Test controls only',
    ],
    correctAnswer: 0,
    explanation: 'MUS/PPS: probability proportional to size. Each dollar = sampling unit. Larger items more likely selected. Good for overstatement testing. Project misstatements using tainting percentage. Assumes low error rates.',
    reference: 'AU-C 530',
  },
  {
    id: 'aud-elite-018',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Service Organization Controls',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Evaluation',
    question: 'When a client uses a service organization, the auditor:',
    options: [
      'Requires direct testing only',
      'Must always obtain SOC report',
      'Considers impact on IC, may use SOC 1 report, and evaluates CUECs at user entity',
      'Can ignore service organization',
    ],
    correctAnswer: 2,
    explanation: 'Service organizations (AU-C 402): understand how services affect client IC. May use SOC 1 report (Type I or Type II). Evaluate relevance, scope, auditor competence. Test complementary user entity controls (CUECs).',
    reference: 'AU-C 402',
  },
  {
    id: 'aud-elite-019',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Analytical Procedures as Substantive',
    difficulty: 'hard',
    blueprintArea: 'AUD-III',
    skillLevel: 'Analysis',
    question: 'Substantive analytical procedures are effective when:',
    options: [
      'Always appropriate',
      'Account is immaterial',
      'Control risk is high',
      'Plausible relationships exist, data is reliable, and expectation is sufficiently precise',
    ],
    correctAnswer: 3,
    explanation: 'Substantive analytics (AU-C 520): requires plausible relationship, reliable data, precise expectation, and defined threshold for investigation. Less effective for volatile or complex accounts. Document expectation and basis.',
    reference: 'AU-C 520',
  },
  {
    id: 'aud-elite-020',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Comparative Financial Statements',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Application',
    question: 'When reporting on comparative financial statements:',
    options: [
      'Report covers all periods presented, updating previous opinions if circumstances changed',
      'Separate reports required',
      'Only current year covered',
      'Prior year automatically unmodified',
    ],
    correctAnswer: 0,
    explanation: 'Comparatives (AU-C 700): report covers all periods presented. Update prior opinion if necessary. If different auditor: reference in current report or predecessor reissues. Address continuing modifications.',
    reference: 'AU-C 700',
  },
  {
    id: 'aud-elite-021',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-ethics',
    topic: 'Professional Responsibilities',
    subtopic: 'Communication with Those Charged with Governance',
    difficulty: 'hard',
    blueprintArea: 'AUD-I',
    skillLevel: 'Application',
    question: 'Required communications with those charged with governance include:',
    options: [
      'Nothing unless deficiencies found',
      'Only significant findings',
      'Fee arrangements only',
      'Auditor responsibilities, planned scope/timing, significant findings, and independence',
    ],
    correctAnswer: 3,
    explanation: 'Required communications (AU-C 260): auditor responsibilities, overview of scope/timing, significant audit findings (accounting policies, estimates, difficulties, disagreements), independence matters. Usually written.',
    reference: 'AU-C 260',
  },
  {
    id: 'aud-elite-022',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-procedures',
    topic: 'Audit Procedures',
    subtopic: 'Estimates Audit Procedures',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Analysis',
    question: 'Auditing accounting estimates requires the auditor to:',
    options: [
      'Obtain specialist for all',
      'Understand how management developed estimates and evaluate reasonableness of methods, assumptions, and data',
      'Accept management estimates',
      'Recalculate all estimates',
    ],
    correctAnswer: 1,
    explanation: 'Estimates (AU-C 540): understand estimation process, assess risks, evaluate: method appropriateness, significant assumptions, data reliability, management bias indicators. Develop point estimate or range.',
    reference: 'AU-C 540',
  },
  {
    id: 'aud-elite-023',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-risk',
    topic: 'Risk Assessment',
    subtopic: 'Significant Risks',
    difficulty: 'hard',
    blueprintArea: 'AUD-II',
    skillLevel: 'Evaluation',
    question: 'Significant risks require:',
    options: [
      'Management inquiry only',
      'Special audit consideration including understanding related controls and substantive procedures responsive to assessed risks',
      'No special attention',
      'Only analytical procedures',
    ],
    correctAnswer: 1,
    explanation: 'Significant risks (AU-C 315): risks requiring special audit attention. Understand controls specifically related to the risk. Substantive procedures responsive to the specific risk. Cannot rely solely on controls.',
    reference: 'AU-C 315',
  },
  {
    id: 'aud-elite-024',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-attestation',
    topic: 'Attestation Engagements',
    subtopic: 'Examination vs. Review',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Evaluation',
    question: 'An examination engagement differs from a review in that examination:',
    options: [
      'Provides reasonable assurance and opinion while review provides limited assurance and conclusion',
      'Is for internal use only',
      'Costs less',
      'Has no standards',
    ],
    correctAnswer: 0,
    explanation: 'Examination (AT-C 205): reasonable assurance, opinion on subject matter. Review (AT-C 210): limited assurance, conclusion stated negatively. Examination requires more extensive procedures than review.',
    reference: 'AT-C 205, AT-C 210',
  },
  {
    id: 'aud-elite-025',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-reporting',
    topic: 'Audit Reports',
    subtopic: 'Adverse Opinion',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Application',
    question: 'An auditor is evaluating the design effectiveness of a client\'s segregation of duties in the revenue cycle. The auditor learns that the same employee handles customer orders, approves credit, ships goods, and records revenue. What level of control deficiency does this represent?',
    options: [
      'A deficiency that need not be communicated',
      'A significant deficiency because the risk of error exists but is unlikely to result in material misstatement',
      'A material weakness because the lack of segregation of duties creates a reasonable possibility that a material misstatement would not be prevented or detected on a timely basis',
      'No deficiency because small companies commonly have limited segregation of duties',
    ],
    correctAnswer: 2,
    explanation: 'When one individual controls the entire transaction cycle from initiation through recording, no compensating controls can effectively replace the oversight that segregation provides. This creates a reasonable possibility that material misstatement would not be prevented or detected. Under AU-C 265, this rises to the level of a material weakness.',
    reference: 'AU-C 705',
  },
  {
    id: 'aud-elite-026',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Reliability of Evidence',
    difficulty: 'hard',
    blueprintArea: 'AUD-III',
    skillLevel: 'Evaluation',
    question: 'An auditor evaluates the operating effectiveness of an entity\'s IT general controls and discovers that access controls over the financial reporting application are deficient — terminated employees retain system access for up to 90 days after departure. What is the most appropriate audit response?',
    options: [
      'Report the finding as a significant deficiency and take no further action',
      'Assess whether compensating controls exist (such as transaction monitoring logs), expand substantive testing of transactions processed during the period of weak access controls, and evaluate whether unauthorized transactions occurred',
      'Rely on management\'s assurance that no unauthorized transactions occurred',
      'Withdraw from the audit due to pervasive control weaknesses',
    ],
    correctAnswer: 1,
    explanation: 'Deficient IT access controls create elevated risk of unauthorized transactions. The auditor should: (1) assess compensating controls, (2) expand substantive testing for the affected period, (3) review access logs for terminated employees, (4) test whether unauthorized transactions were processed, and (5) evaluate the severity of the deficiency for communication purposes.',
    reference: 'AU-C 500',
  },
  {
    id: 'aud-elite-027',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Material Weakness',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Evaluation',
    question: 'A material weakness in internal control:',
    options: [
      'Is same as significant deficiency',
      'Must be reported to SEC',
      'Is a deficiency where reasonable possibility exists that material misstatement won\'t be prevented or detected timely',
      'Requires qualified opinion',
    ],
    correctAnswer: 2,
    explanation: 'Material weakness (AU-C 265): deficiency or combination where reasonable possibility exists that material misstatement of F/S won\'t be prevented/detected on timely basis. Must communicate in writing to governance.',
    reference: 'AU-C 265',
  },
  {
    id: 'aud-elite-028',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-procedures',
    topic: 'Audit Procedures',
    subtopic: 'Revenue Recognition Procedures',
    difficulty: 'hard',
    blueprintArea: 'AUD-IV',
    skillLevel: 'Analysis',
    question: 'Key audit procedures for revenue recognition include:',
    options: [
      'Understanding revenue recognition policies, testing cutoff, analyzing contracts for proper accounting',
      'Recalculating sales tax',
      'Only confirming receivables',
      'Management inquiry only',
    ],
    correctAnswer: 0,
    explanation: 'Revenue procedures: understand policies and 5-step model, test cutoff (both over and under), analyze contract terms, test variable consideration estimates, verify performance obligation satisfaction, test presentation/disclosure.',
    reference: 'AU-C 330, ASC 606 Auditing',
  },
  {
    id: 'aud-elite-029',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-ethics',
    topic: 'Professional Responsibilities',
    subtopic: 'Noncompliance with Laws',
    difficulty: 'hard',
    blueprintArea: 'AUD-I',
    skillLevel: 'Evaluation',
    question: 'When the auditor identifies or suspects noncompliance with laws and regulations:',
    options: [
      'Withdraw immediately',
      'Ignore if immaterial',
      'Report directly to authorities',
      'Obtain understanding of nature, evaluate effect on F/S, discuss with management and governance',
    ],
    correctAnswer: 3,
    explanation: 'NOCLAR (AU-C 250): obtain understanding of facts, evaluate F/S effect, discuss with management and governance. Consider impact on audit report. Legal obligations may require disclosure (SAR). Document.',
    reference: 'AU-C 250',
  },
  {
    id: 'aud-elite-030',
    section: 'AUD',
    courseId: 'cpa',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Evaluation of Results',
    difficulty: 'hard',
    blueprintArea: 'AUD-III',
    skillLevel: 'Analysis',
    question: 'When evaluating sample results, the auditor must:',
    options: [
      'Project misstatements to population, consider sampling risk, and evaluate qualitative aspects',
      'Recalculate sample size',
      'Accept if under tolerable misstatement',
      'Only count errors',
    ],
    correctAnswer: 0,
    explanation: 'Sample evaluation (AU-C 530): project sample misstatements to population, add anomalous (not projected), consider sampling risk, evaluate nature and cause of misstatements (fraud indicators, systemic errors).',
    reference: 'AU-C 530',
  },
];
