/**
 * CPA BAR Section - Questions Depth Batch 6
 * Blueprint Area: BAR-I (Business Analysis)
 * Topics: Forecasting, Regression, Transfer Pricing, Economic Concepts, WACC
 */

import { Question } from '../../../types';

export const BAR_QUESTIONS_DEPTH_6: Question[] = [
  {
    id: 'bar-d6-001',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-forecasting',
    topic: 'Forecasting Techniques',
    subtopic: 'Regression Analysis',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a simple linear regression model Y = a + bX used for cost estimation, the coefficient "b" represents:',
    options: [
      'The fixed cost component',
      'The variable cost per unit of the cost driver — the slope of the regression line indicating how much Y changes for each one-unit increase in X',
      'The coefficient of determination',
      'The standard error of the estimate',
    ],
    correctAnswer: 1,
    explanation: 'In Y = a + bX, "b" is the slope coefficient representing the variable cost per unit of the cost driver X. For every one-unit increase in X, Y increases by b. The "a" is the y-intercept representing estimated fixed costs (when X = 0). For example, if maintenance cost = $10,000 + $5 × machine hours, then fixed cost = $10,000 and variable cost = $5 per machine hour. The coefficient of determination (R²) measures how well the model fits the data — an R² of 0.85 means 85% of the variation in Y is explained by X.',
    reference: 'Quantitative Methods — Regression Analysis',
  },
  {
    id: 'bar-d6-002',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-forecasting',
    topic: 'Forecasting Techniques',
    subtopic: 'Coefficient of Determination',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The coefficient of determination (R²) in regression analysis:',
    options: [
      'Measures the total cost of production',
      'Represents the proportion of the variation in the dependent variable that is explained by the independent variable(s) in the regression model',
      'Equals the slope of the regression line',
      'Measures the accuracy of the y-intercept',
    ],
    correctAnswer: 1,
    explanation: 'R² ranges from 0 to 1 (or 0% to 100%). An R² of 0.92 means 92% of the variation in the dependent variable (Y) is explained by the regression model. The remaining 8% is unexplained (residual) variation. Higher R² indicates a better fit. However, a high R² alone does not prove causation — correlation is not causation. In multiple regression (more than one independent variable), the adjusted R² is preferred because R² always increases when adding variables, even irrelevant ones. Adjusted R² penalizes for adding variables that do not improve explanatory power.',
    reference: 'Quantitative Methods — Regression Analysis',
  },
  {
    id: 'bar-d6-003',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-transfer-pricing',
    topic: 'Transfer Pricing',
    subtopic: 'General Transfer Pricing Rule',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The general rule for setting a minimum transfer price is:',
    options: [
      'Market price minus a fixed discount',
      'Variable cost per unit plus opportunity cost per unit (contribution margin foregone on lost external sales)',
      'Full absorption cost only',
      'Negotiated price set by senior management',
    ],
    correctAnswer: 1,
    explanation: 'Minimum transfer price = Variable cost per unit + Opportunity cost per unit. If the selling division has excess capacity (no lost external sales), opportunity cost = $0, so the minimum is simply variable cost. If the selling division is at full capacity, the opportunity cost equals the contribution margin per unit on forgone external sales. Maximum transfer price should not exceed the external market price (the buying division would not pay more than it could buy externally). The optimal range: Variable cost + Opportunity cost ≤ Transfer price ≤ Market price. This ensures both divisions benefit from the internal transfer.',
    reference: 'Managerial Accounting — Transfer Pricing',
  },
  {
    id: 'bar-d6-004',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-economics',
    topic: 'Economic Concepts',
    subtopic: 'Elasticity of Demand',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'If the price elasticity of demand for a product is −2.0, this means:',
    options: [
      'Supply decreases by 2% for every 1% increase in demand',
      'A 1% increase in price leads to a 2% decrease in quantity demanded — demand is elastic',
      'A 2% increase in price leads to a 1% decrease in quantity demanded',
      'Total revenue is unaffected by price changes',
    ],
    correctAnswer: 1,
    explanation: 'Price elasticity of demand = % change in quantity demanded ÷ % change in price. An elasticity of −2.0 means quantity demanded falls by 2% for every 1% increase in price (elastic demand). When |elasticity| > 1: demand is elastic — a price increase leads to a proportionately larger decrease in quantity demanded, reducing total revenue. When |elasticity| < 1: demand is inelastic — a price increase leads to a proportionately smaller decrease in quantity, increasing total revenue. When |elasticity| = 1: unit elastic — total revenue is maximized.',
    reference: 'Economics — Elasticity',
  },
  {
    id: 'bar-d6-005',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-wacc',
    topic: 'Weighted Average Cost of Capital',
    subtopic: 'WACC Components',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'A company\'s capital structure is 60% equity (cost 12%) and 40% debt (cost 8%, tax rate 25%). The weighted average cost of capital (WACC) is:',
    options: [
      '10.80%',
      '9.60%',
      '10.40%',
      '8.80%',
    ],
    correctAnswer: 1,
    explanation: 'WACC = (Weight of equity × Cost of equity) + (Weight of debt × After-tax cost of debt). After-tax cost of debt = 8% × (1 − 0.25) = 6%. WACC = (0.60 × 12%) + (0.40 × 6%) = 7.20% + 2.40% = 9.60%. The after-tax cost of debt is used because interest is tax-deductible, creating a tax shield. WACC serves as the hurdle rate for capital budgeting decisions — projects with returns exceeding WACC create shareholder value. The cost of equity is higher than the cost of debt because equity holders bear more risk (residual claimants).',
    reference: 'Corporate Finance — Cost of Capital',
  },
  {
    id: 'bar-d6-006',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-ratios',
    topic: 'Financial Ratio Analysis',
    subtopic: 'DuPont Analysis',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the DuPont model, return on equity (ROE) is decomposed into:',
    options: [
      'Revenue growth × Cost efficiency',
      'Profit margin × Asset turnover × Equity multiplier (financial leverage)',
      'Current ratio × Debt-to-equity ratio',
      'Gross margin × Operating margin × Net margin',
    ],
    correctAnswer: 1,
    explanation: 'DuPont formula: ROE = (Net Income ÷ Sales) × (Sales ÷ Average Total Assets) × (Average Total Assets ÷ Average Total Equity). This decomposes ROE into three drivers: (1) Profit margin — operational efficiency (profitability), (2) Asset turnover — asset utilization (efficiency), (3) Equity multiplier — financial leverage. If ROE increases, the DuPont analysis identifies why: higher profitability, better asset utilization, or increased leverage. Increased leverage boosts ROE but also increases financial risk. The 5-factor DuPont further decomposes profit margin into tax burden, interest burden, and operating margin.',
    reference: 'Financial Statement Analysis — DuPont Analysis',
  },
  {
    id: 'bar-d6-007',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cost-accounting',
    topic: 'Cost Accounting',
    subtopic: 'Absorption vs Variable Costing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When production exceeds sales (inventory increases), absorption costing reports:',
    options: [
      'Lower net income than variable costing',
      'Higher net income than variable costing, because fixed overhead is deferred in ending inventory rather than expensed immediately',
      'The same net income as variable costing',
      'Higher cost of goods sold than variable costing',
    ],
    correctAnswer: 1,
    explanation: 'Under absorption costing, fixed manufacturing overhead is included in product costs and allocated to inventory. When production > sales, some fixed overhead remains in ending inventory (deferred to future periods), resulting in lower COGS and higher income. Under variable costing, all fixed manufacturing overhead is expensed as a period cost in the period incurred, regardless of production level. The income difference = Change in inventory units × Fixed overhead rate per unit. When production = sales, both methods yield the same income. When production < sales (inventory decreases), absorption costing reports lower income.',
    reference: 'Managerial Accounting — Absorption vs Variable Costing',
  },
  {
    id: 'bar-d6-008',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-economics',
    topic: 'Economic Concepts',
    subtopic: 'Marginal Analysis',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A firm maximizes profit at the output level where:',
    options: [
      'Total revenue is maximized',
      'Marginal revenue equals marginal cost',
      'Average total cost is minimized',
      'Total cost is minimized',
    ],
    correctAnswer: 1,
    explanation: 'Profit is maximized where marginal revenue (MR) = marginal cost (MC). At this point, the revenue from producing one additional unit exactly equals its cost. If MR > MC, producing more units adds to profit. If MR < MC, reducing output increases profit. This is true for all market structures (perfect competition, monopoly, oligopoly, monopolistic competition). Note: profit maximization and revenue maximization are not the same — revenue is maximized where MR = 0, but profit is maximized where MR = MC. Also, ATC minimization determines productive efficiency, not profit maximization.',
    reference: 'Microeconomics — Profit Maximization',
  },
  {
    id: 'bar-d6-009',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cvp',
    topic: 'Cost-Volume-Profit Analysis',
    subtopic: 'Margin of Safety',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has budgeted sales of $500,000 and a breakeven point of $350,000. The margin of safety percentage is:',
    options: [
      '70%',
      '30%',
      '43%',
      '150%',
    ],
    correctAnswer: 1,
    explanation: 'Margin of safety = (Budgeted sales − Breakeven sales) ÷ Budgeted sales = ($500,000 − $350,000) ÷ $500,000 = $150,000 ÷ $500,000 = 30%. This means sales could decline by 30% before the company reaches its breakeven point and begins incurring losses. A higher margin of safety indicates lower risk. In dollar terms, the margin of safety is $150,000. The margin of safety in units = (Budgeted units − Breakeven units). It is a key risk indicator in CVP analysis.',
    reference: 'Managerial Accounting — CVP Analysis',
  },
  {
    id: 'bar-d6-010',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-capital-budget',
    topic: 'Capital Budgeting',
    subtopic: 'Relevant Cash Flows',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In capital budgeting analysis, which of the following should be INCLUDED as a relevant cash flow?',
    options: [
      'Sunk costs already spent on a feasibility study',
      'Incremental cash flows, including opportunity costs of using existing resources that have alternative uses',
      'Allocated corporate overhead that will not change regardless of the project',
      'Financing costs (interest payments), since these are captured in the discount rate',
    ],
    correctAnswer: 1,
    explanation: 'Relevant cash flows in capital budgeting are incremental — they occur only if the project is undertaken. Include: (1) opportunity costs (e.g., rent income forgone from using a building), (2) incremental working capital changes, (3) salvage value, (4) tax effects (including depreciation tax shield). Exclude: (1) sunk costs (already incurred regardless), (2) non-incremental allocated overhead, (3) financing costs (interest/dividends — captured in WACC used as the discount rate, avoiding double-counting). If a resource has an alternative use, its opportunity cost must be included even if no cash payment is made.',
    reference: 'Corporate Finance — Capital Budgeting',
  },
  {
    id: 'bar-d6-011',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cost-accounting',
    topic: 'Cost Accounting',
    subtopic: 'Joint Costs',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The decision to sell a joint product at the split-off point or process further should be based on:',
    options: [
      'Comparing total joint costs to revenues at the split-off point',
      'Comparing the incremental revenue from further processing to the incremental cost of further processing — joint costs are irrelevant because they are sunk at split-off',
      'Allocating joint costs to each product and comparing to selling price',
      'Selecting the product with the highest sales volume',
    ],
    correctAnswer: 1,
    explanation: 'Joint costs are incurred before the split-off point and are common to all joint products. At the split-off point, they become sunk costs and are irrelevant to the sell-or-process-further decision. The correct approach: compare (1) incremental revenue from further processing (selling price after further processing − selling price at split-off) to (2) incremental costs of further processing (separable costs beyond split-off). Process further only if incremental revenue > incremental cost. Joint cost allocation methods (sales value at split-off, NRV, physical measure) are used for financial reporting, not for decision-making.',
    reference: 'Managerial Accounting — Joint Cost Analysis',
  },
  {
    id: 'bar-d6-012',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-ratios',
    topic: 'Financial Ratio Analysis',
    subtopic: 'Receivables Turnover',
    difficulty: 'easy',
    skillLevel: 'Application',
    question: 'A company has net credit sales of $1,200,000 and average accounts receivable of $150,000. The accounts receivable turnover is:',
    options: [
      '6.0 times',
      '8.0 times',
      '12.5 times',
      '10.0 times',
    ],
    correctAnswer: 1,
    explanation: 'Accounts receivable turnover = Net credit sales ÷ Average accounts receivable = $1,200,000 ÷ $150,000 = 8.0 times. Days sales outstanding (DSO) = 365 ÷ AR turnover = 365 ÷ 8 = 45.6 days. This means the company collects its receivables approximately every 46 days. The AR turnover should be compared to the company\'s credit terms — if terms are net 30, a DSO of 46 days suggests collections are slower than expected. Higher turnover (lower DSO) generally indicates more effective credit and collection policies.',
    reference: 'Financial Statement Analysis — Activity Ratios',
  },
  {
    id: 'bar-d6-013',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-risk',
    topic: 'Risk Assessment',
    subtopic: 'Financial Leverage',
    difficulty: 'medium',
    skillLevel: 'Analysis',
    question: 'Degree of financial leverage (DFL) measures:',
    options: [
      'The percentage change in sales needed to cover fixed costs',
      'The sensitivity of earnings per share to changes in operating income (EBIT) — higher DFL means more interest expense relative to EBIT',
      'The ratio of current assets to current liabilities',
      'The change in revenue from a change in price',
    ],
    correctAnswer: 1,
    explanation: 'DFL = EBIT ÷ EBT = EBIT ÷ (EBIT − Interest expense). A DFL of 2.0 means a 10% increase in EBIT produces a 20% increase in EPS. Higher DFL occurs when a company has significant interest expense relative to operating income. Degree of total leverage (DTL) = DOL × DFL, measuring the combined effect of operating and financial leverage on EPS from a change in sales. Higher total leverage magnifies both gains and losses — increasing risk alongside potential return. Companies should balance the tax benefits of debt against the increased financial risk.',
    reference: 'Corporate Finance — Financial Leverage',
  },
  {
    id: 'bar-d6-014',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-budgeting',
    topic: 'Budgeting',
    subtopic: 'Master Budget Components',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'The starting point for preparing the master budget is typically the:',
    options: [
      'Production budget',
      'Sales budget, because all other budgets depend on the anticipated level of sales',
      'Cash budget',
      'Capital expenditure budget',
    ],
    correctAnswer: 1,
    explanation: 'The master budget sequence begins with the sales budget because production, purchases, staffing, and cash flows all derive from expected sales volume. Typical sequence: Sales budget → Production budget (units to produce = expected sales + desired ending inventory − beginning inventory) → Direct materials purchases budget → Direct labor budget → Manufacturing overhead budget → Selling & administrative expense budget → Budgeted income statement → Capital expenditure budget → Cash budget → Budgeted balance sheet. The cash budget brings together all cash inflows and outflows and identifies financing needs.',
    reference: 'Managerial Accounting — Budgeting',
  },
  {
    id: 'bar-d6-015',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-variance',
    topic: 'Variance Analysis',
    subtopic: 'Sales Price Variance',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company sold 5,000 units at $48 each. The budgeted price was $50. The sales price variance is:',
    options: [
      '$10,000 favorable',
      '$10,000 unfavorable',
      '$2 unfavorable per unit',
      '$240,000 unfavorable',
    ],
    correctAnswer: 1,
    explanation: 'Sales price variance = (Actual price − Budgeted price) × Actual quantity sold = ($48 − $50) × 5,000 = −$2 × 5,000 = $10,000 Unfavorable. The actual selling price is $2 less than budgeted, resulting in $10,000 less revenue than expected for this volume. The sales volume variance addresses the effect of selling more or fewer units than budgeted. Total sales variance = (Actual sales − Budgeted sales) = (5,000 × $48) − (budgeted units × $50). Sales variances help management understand whether revenue differences are due to pricing or volume.',
    reference: 'Managerial Accounting — Sales Variances',
  },
  {
    id: 'bar-d6-016',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cost-behavior',
    topic: 'Cost Behavior',
    subtopic: 'Relevant Range',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The relevant range is best described as:',
    options: [
      'The range of prices a company charges customers',
      'The range of activity or volume over which the assumptions about cost behavior (fixed and variable) are expected to hold true',
      'The range of production possible in a factory',
      'The range of acceptable quality levels',
    ],
    correctAnswer: 1,
    explanation: 'The relevant range is the band of normal activity within which cost behavior assumptions are valid. Within this range, fixed costs remain constant and variable costs per unit remain constant. Outside the relevant range, fixed costs may change (e.g., need a new facility if production exceeds current capacity) and variable cost per unit may change (e.g., quantity discounts at higher volumes, overtime premiums). CVP analysis, budgeting, and standard costing all assume operations within the relevant range. Step costs are fixed within a narrow range but increase in steps as activity increases beyond certain thresholds.',
    reference: 'Managerial Accounting — Cost Behavior',
  },
  {
    id: 'bar-d6-017',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-capital-budget',
    topic: 'Capital Budgeting',
    subtopic: 'Depreciation Tax Shield',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'The annual depreciation tax shield from an asset costing $500,000, depreciated straight-line over 5 years (no salvage), with a 25% tax rate is:',
    options: [
      '$100,000',
      '$25,000',
      '$125,000',
      '$375,000',
    ],
    correctAnswer: 1,
    explanation: 'Annual depreciation = $500,000 ÷ 5 years = $100,000. Depreciation tax shield = Depreciation × Tax rate = $100,000 × 25% = $25,000 per year. The depreciation tax shield is the reduction in income taxes resulting from the depreciation expense deduction (a non-cash expense). In capital budgeting, the after-tax cash flow from operations = Pre-tax cash flow × (1 − tax rate) + Depreciation × tax rate. Accelerated depreciation methods (MACRS) provide larger tax shields in early years, increasing the NPV of the tax benefit due to the time value of money.',
    reference: 'Corporate Finance — Capital Budgeting',
  },
  {
    id: 'bar-d6-018',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cost-accounting',
    topic: 'Cost Accounting',
    subtopic: 'Spoilage — Normal vs Abnormal',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In process costing, normal spoilage is treated as:',
    options: [
      'A period expense on the income statement',
      'A product cost allocated to good units produced, because it is an expected and inherent part of the production process',
      'A reduction in revenue',
      'An extraordinary item',
    ],
    correctAnswer: 1,
    explanation: 'Normal spoilage is the expected amount of waste inherent in the production process that cannot be eliminated under efficient operating conditions. It is a product cost included in the cost of good units. In process costing, normal spoilage costs are allocated to good units completed and to ending WIP (if spoilage occurs after the WIP inspection point). Abnormal spoilage, by contrast, exceeds normal expectations and is recognized as a loss (period cost) on the income statement — it is not allocated to inventory. The distinction is important: normal spoilage is inventoriable; abnormal spoilage is expensed immediately.',
    reference: 'Managerial Accounting — Spoilage Accounting',
  },
  {
    id: 'bar-d6-019',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-economics',
    topic: 'Economic Concepts',
    subtopic: 'Supply and Demand Shifts',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'If a new technology reduces the production cost of a good, the supply curve will:',
    options: [
      'Shift to the left (decrease in supply)',
      'Shift to the right (increase in supply), resulting in a lower equilibrium price and higher equilibrium quantity',
      'Not change, but the demand curve will shift',
      'Become more inelastic',
    ],
    correctAnswer: 1,
    explanation: 'A decrease in production costs increases profitability at every price level, causing producers to supply more at each price — the supply curve shifts right (increase in supply). With demand unchanged, the new equilibrium has: lower price (consumers benefit) and higher quantity (more units traded). Factors that shift supply: (1) input prices (decrease → right shift), (2) technology improvements (→ right shift), (3) number of sellers, (4) expectations, (5) government policies (taxes, subsidies, regulations). Movement ALONG the curve = change in quantity supplied (due to price change). Shift OF the curve = change in supply (due to non-price factors).',
    reference: 'Microeconomics — Supply and Demand',
  },
  {
    id: 'bar-d6-020',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cost-behavior',
    topic: 'Cost Behavior',
    subtopic: 'Special Order Decisions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company with excess capacity receives a special order for 1,000 units at $35 per unit. Its regular price is $50, variable cost is $30, and fixed cost is $15 per unit (based on normal volume). Should the company accept?',
    options: [
      'No, because the special order price ($35) is below total cost ($45)',
      'Yes, because the special order price ($35) exceeds variable cost ($30), and the company has excess capacity — the order contributes $5,000 toward fixed costs',
      'No, because it would reduce the profit margin',
      'Yes, only if the order covers full fixed and variable costs',
    ],
    correctAnswer: 1,
    explanation: 'With excess capacity, fixed costs are already being incurred and will not increase. The relevant comparison is: special order price ($35) vs. incremental (variable) cost ($30). Since $35 > $30, each unit contributes $5 toward fixed costs and profit. Total incremental contribution = 1,000 × $5 = $5,000. The order should be accepted (quantitatively). Qualitative considerations include: (1) will it affect regular customer pricing, (2) is it truly incremental (no opportunity cost of capacity), (3) antitrust/legal issues, (4) long-term customer expectations.',
    reference: 'Managerial Accounting — Relevant Costing',
  },
  {
    id: 'bar-d6-021',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-variance',
    topic: 'Variance Analysis',
    subtopic: 'Variable Overhead Efficiency Variance',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The variable overhead efficiency variance is caused by:',
    options: [
      'Paying a different rate for overhead items than planned',
      'Using more or fewer allocation base units (e.g., labor hours or machine hours) than the standard allows for actual production',
      'A change in fixed overhead costs',
      'Producing more units than budgeted',
    ],
    correctAnswer: 1,
    explanation: 'Variable overhead efficiency variance = (Actual hours − Standard hours allowed) × Standard variable overhead rate. It mirrors the direct labor efficiency variance and measures the impact of using more or fewer hours than expected. If variable overhead is applied based on direct labor hours, then any labor inefficiency also creates a variable overhead efficiency variance. A favorable variance means fewer hours were used than the standard. Note: the variable overhead spending variance = (Actual rate − Standard rate) × Actual hours, which measures the per-hour spending on variable overhead items.',
    reference: 'Managerial Accounting — Overhead Variances',
  },
  {
    id: 'bar-d6-022',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-ratios',
    topic: 'Financial Ratio Analysis',
    subtopic: 'Gross Margin Ratio',
    difficulty: 'easy',
    skillLevel: 'Application',
    question: 'A company has sales of $2,000,000 and cost of goods sold of $1,400,000. The gross margin ratio is:',
    options: [
      '70%',
      '30%',
      '43%',
      '142%',
    ],
    correctAnswer: 1,
    explanation: 'Gross margin ratio = Gross profit ÷ Sales = ($2,000,000 − $1,400,000) ÷ $2,000,000 = $600,000 ÷ $2,000,000 = 30%. This means 30 cents of every revenue dollar remains after covering cost of goods sold to cover operating expenses and generate profit. A higher gross margin indicates either higher pricing, lower production costs, or a favorable product mix. The gross margin should be compared across time periods and against industry peers. Declining gross margins may signal competitive pricing pressure, rising input costs, or unfavorable sales mix shifts.',
    reference: 'Financial Statement Analysis — Profitability Ratios',
  },
  {
    id: 'bar-d6-023',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-wacc',
    topic: 'Weighted Average Cost of Capital',
    subtopic: 'Cost of Equity — CAPM',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'Using the Capital Asset Pricing Model (CAPM) with risk-free rate = 4%, market return = 10%, and beta = 1.3, the cost of equity is:',
    options: [
      '13%',
      '11.8%',
      '14.3%',
      '7.8%',
    ],
    correctAnswer: 1,
    explanation: 'CAPM: Cost of equity = Risk-free rate + Beta × (Market return − Risk-free rate) = 4% + 1.3 × (10% − 4%) = 4% + 1.3 × 6% = 4% + 7.8% = 11.8%. Beta measures systematic (market) risk relative to the overall market (beta = 1 equals market risk). A beta of 1.3 means the stock is 30% more volatile than the market. The market risk premium (Rm − Rf = 6%) compensates investors for bearing systematic risk above the risk-free rate. CAPM assumes well-diversified investors whose only relevant risk is systematic (non-diversifiable) risk.',
    reference: 'Corporate Finance — Cost of Equity',
  },
  {
    id: 'bar-d6-024',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-forecasting',
    topic: 'Forecasting Techniques',
    subtopic: 'Expected Value',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A project has three possible outcomes: 30% chance of $100,000 profit, 50% chance of $50,000 profit, and 20% chance of $20,000 loss. The expected value is:',
    options: [
      '$50,000',
      '$51,000',
      '$43,333',
      '$130,000',
    ],
    correctAnswer: 1,
    explanation: 'Expected value = Σ (probability × outcome). EV = (0.30 × $100,000) + (0.50 × $50,000) + (0.20 × −$20,000) = $30,000 + $25,000 − $4,000 = $51,000. Expected value represents the weighted-average outcome and is used for decision-making under uncertainty. It assumes the decision-maker is risk-neutral. Risk-averse decision-makers may also consider the variance or standard deviation of outcomes. Decision trees often use expected values to evaluate sequential decisions under uncertainty.',
    reference: 'Quantitative Methods — Expected Value',
  },
  {
    id: 'bar-d6-025',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-cost-behavior',
    topic: 'Cost Behavior',
    subtopic: 'Constraint Analysis',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a company faces a single binding constraint (bottleneck), it should prioritize production of the product with the:',
    options: [
      'Highest selling price',
      'Highest contribution margin per unit of the scarce resource (constraint)',
      'Lowest variable cost',
      'Highest overall contribution margin per unit (regardless of constraint use)',
    ],
    correctAnswer: 1,
    explanation: 'When a constraint (bottleneck) limits production, the optimal strategy is to maximize contribution margin per unit of the scarce resource. For example, if machine hours are the constraint: Product A ($20 CM, uses 4 machine hours → $5/hour) vs. Product B ($12 CM, uses 2 machine hours → $6/hour). Prioritize B despite lower unit CM because it generates more per scarce hour. Steps: (1) compute CM per unit of constraint for each product, (2) rank products, (3) allocate constraint capacity to highest-ranked first until demand is met. This is the Theory of Constraints (TOC) approach to short-term product-mix decisions.',
    reference: 'Managerial Accounting — Constraint Analysis',
  },
];
