/**
 * CPA BAR Section - Questions Depth Batch 10
 * Blueprint Area: BAR-II (Technical Accounting and Reporting)
 * Topics: Foreign Currency, Segment Reporting, Subsequent Events, Contingencies, EPS
 */

import { Question } from '../../../types';

export const BAR_QUESTIONS_DEPTH_10: Question[] = [
  {
    id: 'bar-d10-001',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Functional Currency Determination',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 830, the functional currency of a foreign entity is determined primarily by considering:',
    options: [
      'The currency in which the parent company reports',
      'The currency of the primary economic environment in which the entity operates — indicators include the currency of cash flows, sales prices, expenses, financing, and intercompany transactions',
      'The strongest world currency',
      'The currency selected by management',
    ],
    correctAnswer: 1,
    explanation: 'ASC 830-10-55 provides indicators for determining functional currency, which is the currency of the primary economic environment. Key indicators: (1) Cash flow — in what currency do cash flows primarily occur? (2) Sales prices — are prices determined by local competition or world markets? (3) Sales market — where is the principal market? (4) Expenses — are costs primarily in local currency? (5) Financing — in what currency is debt denominated? (6) Intercompany — high volume of parent transactions suggests parent\'s currency. If the functional currency is the local currency, use the current rate method (translation). If it is the parent\'s currency (reporting currency), use the remeasurement method (temporal). Translation adjustments go to OCI; remeasurement gains/losses go to income.',
    reference: 'ASC 830 — Foreign Currency Matters',
  },
  {
    id: 'bar-d10-002',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Translation vs Remeasurement',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the current rate method (translation) per ASC 830, which exchange rate is used for revenue and expense items?',
    options: [
      'Historical rates at the date of each transaction',
      'The exchange rate at the date of the transaction, or a weighted-average rate for the period as a practical expedient',
      'The year-end (current) rate',
      'The rate at the beginning of the year',
    ],
    correctAnswer: 1,
    explanation: 'Current rate method (translation, when functional currency = local currency): Assets and liabilities = current rate (balance sheet date). Revenue and expenses = exchange rate at the transaction date (or weighted-average rate for the period as a practical expedient). Equity accounts (common stock, APIC) = historical rates. Dividends = rate on declaration date. The resulting translation adjustment goes to CTA (cumulative translation adjustment) in accumulated other comprehensive income. Temporal method (remeasurement, when functional currency = reporting currency): Monetary items = current rate. Nonmonetary items = historical rates. Revenue/expenses = transaction date rates (or weighted average). Gains/losses go to net income.',
    reference: 'ASC 830-10-45 — Translation',
  },
  {
    id: 'bar-d10-003',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Foreign Currency Transactions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A U.S. company purchases goods from a German supplier for €100,000 when the exchange rate is $1.10/€. At the balance sheet date, the rate is $1.15/€. The company should recognize:',
    options: [
      'No foreign currency gain or loss until payment',
      'A foreign exchange loss of $5,000 because the payable increased in dollar terms from $110,000 to $115,000',
      'A foreign exchange gain of $5,000',
      'Revenue of $5,000',
    ],
    correctAnswer: 1,
    explanation: 'Foreign currency transaction accounting (ASC 830-20): At purchase: Record payable at spot rate = €100,000 × $1.10 = $110,000. At balance sheet date: Remeasure payable at new spot rate = €100,000 × $1.15 = $115,000. The payable increased by $5,000 in dollar terms. Since the U.S. company must pay more dollars to settle the obligation, this is a foreign exchange loss of $5,000. Transaction gains/losses on foreign-currency-denominated monetary items (receivables, payables, debt) are recognized in current-period earnings. If the dollar had strengthened (rate dropped to $1.05), the company would have recognized a $5,000 gain.',
    reference: 'ASC 830-20 — Foreign Currency Transactions',
  },
  {
    id: 'bar-d10-004',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-segment',
    topic: 'Segment Reporting',
    subtopic: 'Reportable Segments — Quantitative Thresholds',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 280, an operating segment is a reportable segment if it meets any of the following quantitative thresholds EXCEPT:',
    options: [
      'Its reported revenue (including intersegment sales) is 10% or more of combined revenue of all operating segments',
      'Its profit or loss is 10% or more of the greater of (a) combined profit of all profitable segments or (b) combined loss of all loss segments',
      'Its assets are 10% or more of combined assets of all operating segments',
      'Its number of employees is 10% or more of the total workforce',
    ],
    correctAnswer: 3,
    explanation: 'ASC 280 quantitative thresholds (any ONE makes a segment reportable): (1) Revenue test: Segment revenue (internal + external) ≥ 10% of total combined revenue of all segments, (2) Profit/loss test: Segment profit/loss ≥ 10% of the greater of combined profit of profitable segments or combined loss of loss-reporting segments (in absolute value), (3) Asset test: Segment assets ≥ 10% of combined assets of all segments. Employee count is NOT a threshold. Additionally, all reportable segments together must account for at least 75% of total external (consolidated) revenue. If not, additional segments must be identified as reportable until the 75% threshold is met.',
    reference: 'ASC 280 — Segment Reporting',
  },
  {
    id: 'bar-d10-005',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-subsequent',
    topic: 'Subsequent Events',
    subtopic: 'Type I vs Type II',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 855, a recognized (Type I) subsequent event is one that:',
    options: [
      'Occurs after the financial statements are issued',
      'Provides additional evidence about conditions that existed at the balance sheet date — the financial statements should be adjusted',
      'Provides evidence about conditions that arose after the balance sheet date',
      'Never requires disclosure',
    ],
    correctAnswer: 1,
    explanation: 'ASC 855 — Type I (recognized) subsequent events: provide additional evidence about conditions that EXISTED at the balance sheet date. Example: a customer declares bankruptcy shortly after year-end, confirming the receivable was impaired at year-end → adjust the allowance. Settlement of litigation for an amount different from the accrual, confirming year-end estimates → adjust. Type II (nonrecognized) subsequent events: evidence of conditions that AROSE after the balance sheet date. Example: fire destroys a facility after year-end, major acquisition announced → do NOT adjust financial statements but DISCLOSE the nature and financial effect. Entities evaluate events through the date financial statements are issued (SEC filers) or available to be issued (others).',
    reference: 'ASC 855 — Subsequent Events',
  },
  {
    id: 'bar-d10-006',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-contingencies',
    topic: 'Contingencies',
    subtopic: 'Loss Contingency Accrual',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 450-20, a loss contingency is accrued (recorded as a liability) if:',
    options: [
      'A loss is merely possible',
      'It is probable that a loss has been incurred AND the amount can be reasonably estimated',
      'The loss amount is known with certainty',
      'It is reasonably possible that a loss has been incurred',
    ],
    correctAnswer: 1,
    explanation: 'ASC 450-20 loss contingency recognition requires BOTH: (1) It is probable (likely to occur) that a liability has been incurred at the balance sheet date, AND (2) The amount of the loss can be reasonably estimated. If probable but cannot be estimated: disclose (no accrual). If reasonably possible (more than remote but less than probable): disclose but do not accrue. If remote: generally neither accrue nor disclose (except for guarantees, which must always be disclosed). If a range of loss is estimated and no amount within the range is more likely than any other, accrue the minimum of the range (under GAAP; IFRS would accrue the midpoint). Gain contingencies are NEVER accrued, only disclosed.',
    reference: 'ASC 450-20 — Loss Contingencies',
  },
  {
    id: 'bar-d10-007',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-eps',
    topic: 'Earnings Per Share',
    subtopic: 'Diluted EPS — Treasury Stock Method',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'Under the treasury stock method for diluted EPS, stock options are assumed to be exercised and the proceeds are:',
    options: [
      'Added to net income',
      'Used to repurchase shares at the average market price — the net incremental shares (shares issued − shares repurchased) are added to the denominator',
      'Used to retire debt',
      'Ignored if the options are out of the money',
    ],
    correctAnswer: 1,
    explanation: 'Treasury stock method for diluted EPS: (1) Assume all dilutive options/warrants are exercised at the beginning of the period (or grant date if later), (2) Assume the entity receives the exercise price, (3) Use those proceeds to buy back shares at the average market price for the period, (4) The difference (shares issued − shares repurchased) represents the incremental dilutive shares added to the denominator. Options are dilutive only when the exercise price < average market price (in the money). If exercise price > average market price (out of the money), the options are antidilutive and excluded from diluted EPS. The numerator is NOT adjusted under the treasury stock method.',
    reference: 'ASC 260 — Earnings Per Share',
  },
  {
    id: 'bar-d10-008',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-leases',
    topic: 'Leases',
    subtopic: 'Lessor Accounting',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 842, a lessor classifies a lease as a sales-type lease if it meets any of the finance lease criteria AND:',
    options: [
      'The lease payments are fixed',
      'Both of the following are met: collection of lease payments is probable AND the lessor can reasonably determine the fair value of the underlying asset',
      'The asset has a remaining useful life of less than one year',
      'The lessee is a publicly traded company',
    ],
    correctAnswer: 1,
    explanation: 'ASC 842 lessor classification: If ANY of the five finance lease criteria (same as lessee criteria) are met, the lease is classified as either: (a) Sales-type lease — if both: (i) collectibility of payments is probable AND (ii) the lessor can reasonably estimate fair value. The lessor derecognizes the asset, recognizes a net investment, and records profit/loss at commencement. (b) Direct financing lease — if the criteria above are met but the fair value of the underlying asset does NOT equal its carrying amount (and the lease does not meet the transfer or purchase option criteria). (c) If none of the five criteria are met: operating lease (lessor keeps the asset, recognizes lease income straight-line).',
    reference: 'ASC 842-30 — Lessor Classification',
  },
  {
    id: 'bar-d10-009',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-consolidation',
    topic: 'Consolidation',
    subtopic: 'Variable Interest Entities',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 810, an entity is a variable interest entity (VIE) if:',
    options: [
      'It has publicly traded equity',
      'The equity investors as a group lack the characteristics of a controlling financial interest — insufficient equity at risk, lack of decision-making rights, or lack of obligation to absorb losses/right to receive returns',
      'It is a wholly owned subsidiary',
      'It operates in a foreign country',
    ],
    correctAnswer: 1,
    explanation: 'A VIE exists when equity investors as a group lack ANY ONE of: (1) Sufficient equity at risk to finance activities without additional subordinated financial support, (2) Decision-making ability (governing power through voting or similar rights), (3) Obligation to absorb expected losses and right to receive expected residual returns. The primary beneficiary of a VIE must consolidate it. The primary beneficiary has: (a) power to direct the activities most significantly impacting the VIE\'s economic performance, AND (b) obligation to absorb losses or right to receive benefits that could be significant to the VIE. The VIE model overrides the voting interest model when applicable.',
    reference: 'ASC 810-10-15 — Variable Interest Entities',
  },
  {
    id: 'bar-d10-010',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Contract Modifications',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 606, a contract modification is treated as a separate contract if:',
    options: [
      'The modification changes the delivery schedule',
      'The scope of the contract increases because of the addition of distinct goods or services AND the contract price increases by an amount that reflects standalone selling prices of the additional goods or services',
      'The customer requests any change',
      'The modification reduces the contract price',
    ],
    correctAnswer: 1,
    explanation: 'ASC 606-10-25: A contract modification is accounted for as a separate (new) contract if BOTH: (1) the scope increases due to addition of promised goods/services that are distinct, AND (2) the price increases by an amount that appropriately reflects the entity\'s standalone selling prices (adjusted for contract circumstances). This essentially treats the modification as a new contract "layered on top of" the original. If the modification does NOT meet both criteria, it is accounted for either as: (a) a termination of the old contract and creation of a new one (prospective, if remaining goods are distinct), or (b) a cumulative catch-up adjustment (if remaining goods are not distinct and form part of a single performance obligation).',
    reference: 'ASC 606-10-25 — Contract Modifications',
  },
  {
    id: 'bar-d10-011',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-pensions',
    topic: 'Pensions and OPEB',
    subtopic: 'Funded Status Presentation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 715, the funded status of a defined benefit pension plan is presented on the balance sheet as:',
    options: [
      'Off-balance-sheet in the notes only',
      'A net asset (if overfunded) or net liability (if underfunded), measured as the difference between plan assets at fair value and the projected benefit obligation',
      'The accumulated benefit obligation only',
      'The expected return on plan assets',
    ],
    correctAnswer: 1,
    explanation: 'ASC 715 requires recognition of the funded status on the balance sheet. Funded status = Fair value of plan assets − Projected benefit obligation (PBO). If plan assets > PBO: noncurrent asset (prepaid pension). If PBO > plan assets: current liability (to the extent of next year\'s expected contributions) and noncurrent liability (remainder). Items not yet recognized as components of net periodic pension cost (prior service cost, actuarial gains/losses) are recorded in AOCI. The PBO is used (not the ABO) because it includes future salary increases in the benefit formula — providing a more complete measure of the obligation.',
    reference: 'ASC 715-20-45 — Pension Balance Sheet',
  },
  {
    id: 'bar-d10-012',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-income-tax',
    topic: 'Income Tax Accounting',
    subtopic: 'Uncertain Tax Positions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 740-10 (formerly FIN 48), a tax benefit from an uncertain tax position is recognized only if:',
    options: [
      'The company intends to file a tax return',
      'It is more likely than not (greater than 50% likelihood) that the tax position will be sustained upon examination by the taxing authority, based on its technical merits',
      'The auditor approves the position',
      'The tax return has been filed',
    ],
    correctAnswer: 1,
    explanation: 'Two-step process: (1) Recognition — determine if the tax position meets the "more likely than not" threshold (>50% probability) of being sustained upon examination based on technical merits. If yes, proceed to measurement. If no, no benefit is recognized. (2) Measurement — measure the benefit as the largest amount that is greater than 50% likely to be realized upon ultimate settlement. This means the entity evaluates the cumulative probability of possible settlement outcomes. Unrecognized tax benefits (UTBs) are classified as liabilities (or reductions of DTAs/NOLs). Interest and penalties on UTBs may be classified as income tax expense or interest expense (accounting policy election).',
    reference: 'ASC 740-10-25 — Uncertain Tax Positions',
  },
  {
    id: 'bar-d10-013',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-business-combo',
    topic: 'Business Combinations',
    subtopic: 'Contingent Consideration',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 805, contingent consideration (e.g., an earnout agreement) in a business combination is:',
    options: [
      'Recognized only when the contingency is resolved',
      'Recognized and measured at fair value at the acquisition date as part of the consideration transferred, with subsequent fair value changes recognized in earnings (if classified as a liability or asset)',
      'Excluded from goodwill calculation',
      'Always classified as equity',
    ],
    correctAnswer: 1,
    explanation: 'ASC 805 requires contingent consideration to be recognized at fair value at the acquisition date as part of the consideration transferred. Classification determines subsequent treatment: (1) If classified as a liability (or asset): subsequent changes in fair value are recognized in earnings each reporting period. (2) If classified as equity: not remeasured; settlement differences are recorded within equity. Most earnout arrangements are classified as liabilities because they are settled in cash or variable numbers of shares. The acquisition-date fair value is included in the calculation of goodwill. Changes after the measurement period that result from events after the acquisition date are NOT measurement period adjustments — they go to earnings.',
    reference: 'ASC 805-30 — Contingent Consideration',
  },
  {
    id: 'bar-d10-014',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Net Investment Hedge',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 815, the effective portion of the gain or loss on a hedging instrument designated as a hedge of a net investment in a foreign operation is reported in:',
    options: [
      'Net income immediately',
      'Other comprehensive income (as part of the cumulative translation adjustment), and reclassified to earnings upon sale or substantial liquidation of the foreign operation',
      'Retained earnings directly',
      'As an adjustment to the carrying value of the investment',
    ],
    correctAnswer: 1,
    explanation: 'A net investment hedge protects against foreign currency exposure of the entity\'s investment in a foreign subsidiary (or equity method investee). The effective portion of the hedging gain/loss is reported in the cumulative translation adjustment (CTA) within accumulated other comprehensive income — the same location where translation adjustments from the subsidiary\'s financial statements are reported. This provides offset. Amounts remain in AOCI until the foreign operation is sold, substantially liquidated, or otherwise disposed of, at which point accumulated CTA (including hedging gains/losses) is reclassified to earnings. Eligible instruments include foreign currency forward contracts, options, and foreign-currency-denominated debt.',
    reference: 'ASC 815-35 — Net Investment Hedges',
  },
  {
    id: 'bar-d10-015',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-leases',
    topic: 'Leases',
    subtopic: 'Short-Term Lease Exception',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 842, a lessee may elect not to recognize a right-of-use asset and lease liability for:',
    options: [
      'All operating leases',
      'Short-term leases with a lease term of 12 months or less (at commencement) that do not include a purchase option the lessee is reasonably certain to exercise',
      'Any lease with payments under $5,000',
      'Leases of low-value assets only',
    ],
    correctAnswer: 1,
    explanation: 'ASC 842 provides a practical expedient: Leases with a term of 12 months or less at commencement (and no purchase option reasonably certain to be exercised) may be excluded from balance sheet recognition. The lessee recognizes lease expense on a straight-line basis over the lease term. The election is made by asset class (must be applied consistently). A lease that contains a renewal option is NOT short-term if the lessee is reasonably certain to exercise the renewal, causing the total term to exceed 12 months. Note: IFRS 16 also provides a low-value asset exemption (not in US GAAP).',
    reference: 'ASC 842-20-25 — Short-Term Leases',
  },
  {
    id: 'bar-d10-016',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Recurring vs Nonrecurring',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 820, fair value measurements are classified as recurring or nonrecurring. Which is an example of a nonrecurring fair value measurement?',
    options: [
      'Trading securities measured at fair value each period',
      'An impaired long-lived asset written down to fair value',
      'Derivatives reported at fair value every quarter',
      'Available-for-sale debt securities at each reporting date',
    ],
    correctAnswer: 1,
    explanation: 'Recurring measurements are required at every reporting period (e.g., trading securities, AFS debt securities, derivatives, pension plan assets). Nonrecurring measurements are triggered by specific events or circumstances — they are not measured at fair value every period. Examples: (1) long-lived assets impaired and written down to fair value, (2) assets acquired in a business combination (measured at fair value on the acquisition date), (3) assets held for sale at lower of carrying amount or fair value less costs to sell, (4) goodwill impairment. Both recurring and nonrecurring measurements require disclosure of the fair value hierarchy level and, for Level 3, the valuation techniques and inputs used.',
    reference: 'ASC 820-10-50 — Fair Value Disclosures',
  },
  {
    id: 'bar-d10-017',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-consolidation',
    topic: 'Consolidation',
    subtopic: 'Equity Method',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An investor with significant influence (typically 20-50% ownership) accounts for its investment using the equity method under ASC 323. Under this method, the investment is initially recorded at cost and subsequently adjusted for:',
    options: [
      'Fair value changes each period',
      'The investor\'s share of the investee\'s net income or loss, reduced by dividends received',
      'Dividends received only',
      'Market price fluctuations',
    ],
    correctAnswer: 1,
    explanation: 'Equity method: Investment is initially recorded at cost. Subsequent adjustments: (1) Increase for the investor\'s share of investee net income (Dr Investment, Cr Equity in earnings of investee). (2) Decrease for investee losses (investor\'s proportionate share). (3) Decrease for dividends received (Dr Cash, Cr Investment — dividends are a return OF investment, not return ON investment). (4) Amortization of basis difference (excess of cost over book value allocated to specific assets/liabilities). (5) Other comprehensive income items of the investee. The investment is tested for impairment (other-than-temporary) but is NOT adjusted to fair value each period (unlike the FV option or trading securities).',
    reference: 'ASC 323 — Equity Method Investments',
  },
  {
    id: 'bar-d10-018',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Warranties',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 606, a warranty that provides a service beyond assurance that the product complies with agreed-upon specifications is accounted for as:',
    options: [
      'Part of the product cost',
      'A separate performance obligation, with a portion of the transaction price allocated to the warranty service obligation',
      'An expense when warranty claims are received',
      'A contingent liability only',
    ],
    correctAnswer: 1,
    explanation: 'ASC 606 distinguishes two types of warranties: (1) Assurance-type warranty — provides assurance that the product complies with agreed-upon specifications (standard warranty). This is NOT a separate performance obligation — accounted for under ASC 450 (accrue estimated warranty costs). (2) Service-type warranty — provides a service beyond the assurance warranty (e.g., extended warranty, additional coverage). This IS a separate performance obligation under ASC 606 — a portion of the transaction price is allocated to it and recognized over the warranty service period. If a warranty is sold separately or is optional, it is generally a service-type warranty.',
    reference: 'ASC 606-10-55 — Warranties',
  },
  {
    id: 'bar-d10-019',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-eps',
    topic: 'Earnings Per Share',
    subtopic: 'If-Converted Method',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'For diluted EPS, convertible bonds are evaluated using the if-converted method. If the bonds are dilutive, the adjustment to the numerator is:',
    options: [
      'Deduct the face value of bonds',
      'Add back the after-tax interest expense on the convertible bonds (since if converted, interest would not have been paid)',
      'Subtract dividends',
      'Add the face value of bonds',
    ],
    correctAnswer: 1,
    explanation: 'If-converted method for convertible bonds: Assume conversion at the beginning of the period (or issuance date if later). Numerator adjustment: add back after-tax interest expense on the convertible bonds (interest saved because bonds were "converted" and no longer outstanding). After-tax interest = Interest expense × (1 − tax rate). Denominator adjustment: add the shares that would be issued upon conversion. The conversion is included in diluted EPS ONLY if it is dilutive (reduces EPS below basic EPS). If including the conversion would increase EPS (antidilutive), it is excluded. For convertible preferred stock: add back preferred dividends to the numerator and shares from conversion to the denominator.',
    reference: 'ASC 260-10-45 — Diluted EPS',
  },
  {
    id: 'bar-d10-020',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-income-tax',
    topic: 'Income Tax Accounting',
    subtopic: 'Intraperiod Tax Allocation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Intraperiod tax allocation under ASC 740 requires:',
    options: [
      'Allocating total income tax expense entirely to continuing operations',
      'Allocating total income tax expense among continuing operations, discontinued operations, other comprehensive income, and items charged directly to equity',
      'Deferring all tax effects to future periods',
      'Reporting taxes only in the footnotes',
    ],
    correctAnswer: 1,
    explanation: 'Intraperiod tax allocation distributes total income tax expense across the components that generated taxable income or deductions within the same period. The tax effect is allocated to: (1) Continuing operations (using a computed effective rate on pre-tax income from continuing operations), (2) Discontinued operations, (3) Other comprehensive income (e.g., unrealized gains/losses on AFS securities, pension adjustments, translation adjustments, cash flow hedge gains/losses), (4) Items charged/credited directly to equity (e.g., prior period adjustments, certain stock compensation items). This ensures each component reflects its own tax impact, providing meaningful after-tax presentation for each.',
    reference: 'ASC 740-20 — Intraperiod Tax Allocation',
  },
  {
    id: 'bar-d10-021',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-stock-comp',
    topic: 'Stock-Based Compensation',
    subtopic: 'Performance Conditions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 718, how are performance conditions handled in recognizing compensation expense for stock awards?',
    options: [
      'They are ignored completely',
      'If the performance condition is probable of being achieved, expense is recognized over the requisite service period; the probability assessment is updated each period, and cumulative expense is adjusted accordingly',
      'Expense is recognized only after the performance target is met',
      'The grant-date fair value is adjusted for performance probability',
    ],
    correctAnswer: 1,
    explanation: 'Performance conditions (e.g., achieving a target EPS, revenue, or EBITDA) affect vesting but do NOT affect the grant-date fair value of the award. Instead, expense recognition depends on the probability that the condition will be achieved. Each period, management assesses whether achievement is probable. If probable: recognize expense over the requisite service period (with cumulative catch-up if the assessment changes). If not probable: do not recognize expense (and reverse any previously recognized expense). This differs from market conditions (e.g., stock price targets), which ARE incorporated into the grant-date fair value and affect expense regardless of whether the condition is met.',
    reference: 'ASC 718-10-25 — Performance Conditions',
  },
  {
    id: 'bar-d10-022',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-segment',
    topic: 'Segment Reporting',
    subtopic: 'Chief Operating Decision Maker',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 280, operating segments are identified based on:',
    options: [
      'Legal entity structure',
      'The way the chief operating decision maker (CODM) organizes and evaluates the entity\'s components for purposes of allocating resources and assessing performance',
      'Product line profitability only',
      'Geographic location only',
    ],
    correctAnswer: 1,
    explanation: 'ASC 280 uses a management approach: segments are identified based on how the entity is organized and evaluated internally by the CODM. The CODM is a function (not necessarily a specific title) — it could be the CEO, COO, or a group of executives who make key resource allocation decisions. An operating segment must: (1) engage in business activities that may earn revenues and incur expenses, (2) have operating results regularly reviewed by the CODM, and (3) have discrete financial information available. Segmentation may be by product lines, geographic areas, customer types, or any other basis used internally. This aligns external reporting with internal management reporting.',
    reference: 'ASC 280-10-10 — Segment Identification',
  },
  {
    id: 'bar-d10-023',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-business-combo',
    topic: 'Business Combinations',
    subtopic: 'Intangible Assets Recognized Separately from Goodwill',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a business combination, which of the following intangible assets must be recognized separately from goodwill?',
    options: [
      'Only goodwill is recognized for all intangible value acquired',
      'Identifiable intangible assets that arise from contractual or legal rights OR are separable from the entity (can be sold, transferred, licensed, etc.) — examples include customer lists, trade names, and patents',
      'Only assets with infinite useful lives',
      'Only regulatory licenses',
    ],
    correctAnswer: 1,
    explanation: 'ASC 805 requires intangible assets acquired in a business combination to be recognized separately from goodwill if they meet either: (1) Contractual-legal criterion — arise from contractual or legal rights (patents, licenses, trademarks, franchise agreements, broadcasting rights), OR (2) Separability criterion — can be separated from the entity and sold, transferred, licensed, rented, or exchanged (customer lists, databases, unpatented technology, trade secrets). Common categories: customer-related (customer relationships, customer lists), marketing-related (trademarks, trade names), technology-based (patents, software), contract-based (licensing, franchise). These are measured at fair value and amortized over useful life (or tested for impairment if indefinite-lived).',
    reference: 'ASC 805-20-55 — Intangible Assets',
  },
  {
    id: 'bar-d10-024',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Highly Inflationary Economies',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 830, a foreign entity operating in a highly inflationary economy (cumulative inflation >100% over 3 years) must:',
    options: [
      'Continue using the local currency as its functional currency',
      'Use the parent company\'s reporting currency as its functional currency, requiring remeasurement (temporal method) rather than translation',
      'Use any stable currency of its choice',
      'Report all amounts at historical cost without conversion',
    ],
    correctAnswer: 1,
    explanation: 'ASC 830-10-45-11: When a foreign entity operates in a highly inflationary economy (cumulative inflation of approximately 100% or more over a 3-year period), the entity\'s functional currency is considered the reporting currency (parent\'s currency) rather than the local currency. The financial statements are remeasured using the temporal method: monetary items at current rates, nonmonetary items at historical rates. Remeasurement gains/losses are reported in net income (not OCI). This avoids the distortion that would occur from translating severely inflated local currency financials. Examples have included Venezuela, Argentina, Turkey, and Zimbabwe during hyperinflationary periods.',
    reference: 'ASC 830-10-45 — Highly Inflationary Economies',
  },
  {
    id: 'bar-d10-025',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Standalone Selling Price Allocation',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'Under ASC 606, when allocating the transaction price to performance obligations, the best evidence of standalone selling price (SSP) is:',
    options: [
      'The cost of producing the good or service',
      'The observable price when the entity sells that good or service separately in similar circumstances to similar customers',
      'The price charged by competitors',
      'The contract price divided equally among obligations',
    ],
    correctAnswer: 1,
    explanation: 'ASC 606-10-32: The transaction price is allocated to performance obligations based on their relative standalone selling prices (SSPs). Best evidence of SSP: the observable price when the entity sells identical goods/services separately. If not directly observable, estimate using: (1) Adjusted market assessment approach (what the market would pay), (2) Expected cost plus a margin approach (forecast costs + appropriate margin), (3) Residual approach (only permitted when the SSP is highly variable or uncertain — total transaction price minus observable SSPs of other obligations). A discount in the overall arrangement price is generally allocated to all performance obligations proportionally unless there is observable evidence that the discount relates to specific obligations.',
    reference: 'ASC 606-10-32 — Allocating the Transaction Price',
  },
];
