// Easy Questions Expansion - Part 1
// Major expansion to address difficulty imbalance (target: 15-20% easy questions)
// Focus: Foundational concepts, definitions, basic calculations, and recall questions

import { Question } from '../../../types';

export const EASY_QUESTIONS_EXPANDED: Question[] = [
  // ============================================
  // FAR EASY QUESTIONS (80 questions)
  // ============================================
  
  // FAR-I: Conceptual Framework
  {
    id: 'far-easy-exp-001',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-I',
    blueprintGroup: 'FAR-I-A',
    topicId: 'far-framework',
    topic: 'Conceptual Framework',
    subtopic: 'Qualitative Characteristics',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which is the MOST fundamental qualitative characteristic of useful financial information?',
    options: [
      'Understandability',
      'Relevance',
      'Comparability',
      'Timeliness',
    ],
    correctAnswer: 1,
    explanation: 'Relevance and faithful representation are the two fundamental qualitative characteristics. Information is relevant if it can make a difference in decisions. Comparability, timeliness, and understandability are enhancing characteristics.',
    reference: 'FASB Concepts Statement No. 8',
  },
  {
    id: 'far-easy-exp-002',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-I',
    blueprintGroup: 'FAR-I-A',
    topicId: 'far-framework',
    topic: 'Conceptual Framework',
    subtopic: 'Elements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The residual interest in the assets after deducting liabilities is called:',
    options: [
      'Revenue',
      'Gains',
      'Comprehensive income',
      'Equity',
    ],
    correctAnswer: 3,
    explanation: 'Equity (or net assets) is defined as the residual interest in the assets of an entity that remains after deducting its liabilities.',
    reference: 'FASB Concepts Statement No. 6',
  },
  {
    id: 'far-easy-exp-003',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-I',
    blueprintGroup: 'FAR-I-A',
    topicId: 'far-framework',
    topic: 'Conceptual Framework',
    subtopic: 'Recognition',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under the accrual basis of accounting, revenue is recognized when:',
    options: [
      'Payment is promised',
      'Cash is received',
      'The contract is signed',
      'Earned, regardless of when cash is received',
    ],
    correctAnswer: 3,
    explanation: 'Accrual accounting recognizes revenue when it is earned (typically when goods are delivered or services are performed), regardless of when cash is received.',
    reference: 'ASC 606',
  },
  
  // FAR-II: Financial Statement Accounts
  {
    id: 'far-easy-exp-004',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-A',
    topicId: 'far-cash',
    topic: 'Cash',
    subtopic: 'Bank Reconciliation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A deposit in transit would be:',
    options: [
      'Subtracted from the bank balance',
      'Added to the book balance',
      'Subtracted from the book balance',
      'Added to the bank balance',
    ],
    correctAnswer: 3,
    explanation: 'A deposit in transit is a deposit recorded in the company\'s books but not yet shown on the bank statement. It is ADDED to the bank balance to reconcile.',
    reference: 'Bank Reconciliation',
  },
  {
    id: 'far-easy-exp-005',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-A',
    topicId: 'far-cash',
    topic: 'Cash',
    subtopic: 'Bank Reconciliation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An outstanding check would be:',
    options: [
      'Added to the book balance',
      'Subtracted from the bank balance',
      'Subtracted from the book balance',
      'Added to the bank balance',
    ],
    correctAnswer: 1,
    explanation: 'An outstanding check is a check written by the company but not yet cleared by the bank. It is SUBTRACTED from the bank balance to reconcile.',
    reference: 'Bank Reconciliation',
  },
  {
    id: 'far-easy-exp-006',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-B',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Allowance Method',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Writing off a specific account receivable using the allowance method will:',
    options: [
      'Decrease total assets',
      'Increase net income',
      'Increase bad debt expense',
      'Have no effect on total assets',
    ],
    correctAnswer: 3,
    explanation: 'Writing off a specific account (Dr. Allowance, Cr. A/R) reduces both gross A/R and the allowance. Net A/R remains the same, so total assets are unchanged.',
    reference: 'ASC 310',
  },
  {
    id: 'far-easy-exp-007',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-C',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Cost Flow Methods',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'During a period of rising prices, which inventory method results in the HIGHEST ending inventory?',
    options: [
      'FIFO',
      'Specific identification',
      'LIFO',
      'Weighted average',
    ],
    correctAnswer: 0,
    explanation: 'FIFO (First-In, First-Out) leaves the most recent (highest cost) purchases in ending inventory during rising prices, resulting in the highest ending inventory value.',
    reference: 'ASC 330',
  },
  {
    id: 'far-easy-exp-008',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-C',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Cost Flow Methods',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'During a period of rising prices, which inventory method results in the LOWEST net income?',
    options: [
      'FIFO',
      'All methods result in same net income',
      'LIFO',
      'Weighted average',
    ],
    correctAnswer: 2,
    explanation: 'LIFO (Last-In, First-Out) allocates the most recent (highest) costs to COGS, resulting in higher COGS and lower net income during rising prices.',
    reference: 'ASC 330',
  },
  {
    id: 'far-easy-exp-009',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-D',
    topicId: 'far-ppe',
    topic: 'PP&E',
    subtopic: 'Capitalization',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which cost should be CAPITALIZED as part of equipment?',
    options: [
      'Training employees to use equipment',
      'Insurance after equipment is in use',
      'Routine maintenance',
      'Installation costs',
    ],
    correctAnswer: 3,
    explanation: 'Installation costs are necessary to get the equipment ready for its intended use and are capitalized. Routine maintenance, ongoing insurance, and training are period expenses.',
    reference: 'ASC 360',
  },
  {
    id: 'far-easy-exp-010',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-D',
    topicId: 'far-ppe',
    topic: 'PP&E',
    subtopic: 'Depreciation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'In the context of property, plant, and equipment (PP&E), which of the following best describes land?',
    options: [
      'Depleted as resources are extracted',
      'Depreciated over its useful life',
      'Depreciated over 40 years',
      'Not depreciated',
    ],
    correctAnswer: 3,
    explanation: 'Land has an indefinite useful life and is not depreciated. Land improvements (parking lots, fencing) ARE depreciated.',
    reference: 'ASC 360',
  },
  {
    id: 'far-easy-exp-011',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-D',
    topicId: 'far-depreciation',
    topic: 'Depreciation',
    subtopic: 'Straight-Line',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Equipment costs $50,000 with a $5,000 salvage value and 9-year life. What is the annual straight-line depreciation?',
    options: [
      '$4,500',
      '$5,000',
      '$6,000',
      '$5,556',
    ],
    correctAnswer: 1,
    explanation: 'Straight-line depreciation = (Cost - Salvage) / Life = ($50,000 - $5,000) / 9 = $5,000 per year.',
    reference: 'ASC 360',
  },
  {
    id: 'far-easy-exp-012',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-E',
    topicId: 'far-intangibles',
    topic: 'Intangible Assets',
    subtopic: 'Goodwill',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 350, which of the following best describes the accounting treatment of goodwill?',
    options: [
      'Amortized over 40 years',
      'Amortized over 15 years',
      'Expensed immediately',
      'Not amortized but tested for impairment',
    ],
    correctAnswer: 3,
    explanation: 'Under GAAP, goodwill has an indefinite life and is NOT amortized. It is tested for impairment annually or when triggering events occur.',
    reference: 'ASC 350',
  },
  {
    id: 'far-easy-exp-013',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-F',
    topicId: 'far-liabilities',
    topic: 'Liabilities',
    subtopic: 'Classification',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A liability due in 6 months is classified as:',
    options: [
      'Long-term liability',
      'Current liability',
      'Deferred liability',
      'Contingent liability',
    ],
    correctAnswer: 1,
    explanation: 'A liability due within one year (or the operating cycle if longer) is classified as a current liability.',
    reference: 'ASC 210',
  },
  {
    id: 'far-easy-exp-014',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-F',
    topicId: 'far-bonds',
    topic: 'Bonds',
    subtopic: 'Premium/Discount',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A bond sells at a premium when:',
    options: [
      'The stated rate equals the market rate',
      'The bond is callable',
      'The stated rate is less than the market rate',
      'The stated rate is greater than the market rate',
    ],
    correctAnswer: 3,
    explanation: 'Bonds sell at a premium when the stated (coupon) rate exceeds the market rate. Investors pay more for the higher interest payments.',
    reference: 'ASC 470',
  },
  {
    id: 'far-easy-exp-015',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-G',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Treasury Stock',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Treasury stock is:',
    options: [
      'Stock held by the US Treasury',
      'Stock authorized but never issued',
      'Stock issued and held by shareholders',
      'Stock repurchased by the company',
    ],
    correctAnswer: 3,
    explanation: 'Treasury stock is a company\'s own stock that has been repurchased. It reduces total stockholders\' equity.',
    reference: 'ASC 505',
  },
  {
    id: 'far-easy-exp-016',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-G',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Dividends',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The declaration of a cash dividend affects:',
    options: [
      'Assets decrease, liabilities increase',
      'Common stock decreases',
      'Neither assets nor liabilities',
      'Retained earnings decreases, liabilities increase',
    ],
    correctAnswer: 3,
    explanation: 'When a cash dividend is declared: Dr. Retained Earnings, Cr. Dividends Payable. This decreases equity and increases liabilities.',
    reference: 'ASC 505',
  },
  {
    id: 'far-easy-exp-017',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    blueprintGroup: 'FAR-II-G',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Stock Splits',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A 2-for-1 stock split will:',
    options: [
      'Decrease retained earnings',
      'Halve the par value per share',
      'Double the par value per share',
      'Increase total stockholders\' equity',
    ],
    correctAnswer: 1,
    explanation: 'A 2-for-1 stock split doubles the number of shares and halves the par value per share. Total equity remains unchanged.',
    reference: 'ASC 505',
  },
  
  // FAR-III: Transactions
  {
    id: 'far-easy-exp-018',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    blueprintGroup: 'FAR-III-A',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Performance Obligations',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 606, the first step in revenue recognition is to:',
    options: [
      'Determine the transaction price',
      'Identify performance obligations',
      'Allocate the transaction price',
      'Identify the contract with a customer',
    ],
    correctAnswer: 3,
    explanation: 'The five steps of ASC 606 are: (1) Identify the contract, (2) Identify performance obligations, (3) Determine transaction price, (4) Allocate price, (5) Recognize revenue.',
    reference: 'ASC 606-10-25',
  },
  {
    id: 'far-easy-exp-019',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    blueprintGroup: 'FAR-III-B',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Classification',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 842, ALL leases over 12 months are reported on the balance sheet by:',
    options: [
      'The lessee only',
      'The lessor only',
      'Neither party',
      'Both lessor and lessee',
    ],
    correctAnswer: 0,
    explanation: 'Under ASC 842, LESSEES recognize both a right-of-use asset and lease liability for all leases over 12 months. Short-term lease exception available.',
    reference: 'ASC 842',
  },
  {
    id: 'far-easy-exp-020',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    blueprintGroup: 'FAR-III-C',
    topicId: 'far-income-tax',
    topic: 'Income Taxes',
    subtopic: 'Deferred Taxes',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A deferred tax liability arises when:',
    options: [
      'Book income exceeds taxable income temporarily',
      'Tax rates decrease',
      'Book income is less than taxable income',
      'A permanent difference exists',
    ],
    correctAnswer: 0,
    explanation: 'A DTL arises when book income > taxable income temporarily (e.g., accelerated tax depreciation). More tax will be paid in the future.',
    reference: 'ASC 740',
  },
  
  // FAR-IV: Government
  {
    id: 'far-easy-exp-021',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-IV',
    blueprintGroup: 'FAR-IV-A',
    topicId: 'far-govt-funds',
    topic: 'Government Accounting',
    subtopic: 'Fund Types',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The General Fund is an example of what type of fund?',
    options: [
      'Proprietary fund',
      'Fiduciary fund',
      'Component unit',
      'Governmental fund',
    ],
    correctAnswer: 3,
    explanation: 'The General Fund is a governmental fund type. Other governmental funds include Special Revenue, Capital Projects, Debt Service, and Permanent funds.',
    reference: 'GASB 34',
  },
  {
    id: 'far-easy-exp-022',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-IV',
    topic: 'Government Accounting',
    subtopic: 'Measurement Focus',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A city maintains an internal service fund to provide printing services to other departments. Internal service funds use which measurement focus?',
    options: [
      'Current financial resources',
      'Economic resources',
      'Modified accrual',
      'Cash basis',
    ],
    correctAnswer: 1,
    explanation: 'Internal service funds are proprietary funds (along with enterprise funds). Under GASB, all proprietary funds use the economic resources measurement focus and full accrual basis of accounting, similar to private-sector businesses. They record capital assets and long-term liabilities. Governmental funds (general, special revenue, capital projects, debt service, permanent) use the current financial resources measurement focus with modified accrual accounting.',
    reference: 'GASB 34',
  },
  
  // FAR-V: Not-for-Profit
  {
    id: 'far-easy-exp-023',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-V',
    blueprintGroup: 'FAR-V-A',
    topicId: 'far-nfp',
    topic: 'Not-for-Profit',
    subtopic: 'Net Asset Classes',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Not-for-profit entities classify net assets as:',
    options: [
      'Current and noncurrent',
      'Restricted and unrestricted',
      'With donor restrictions and without donor restrictions',
      'Temporarily restricted and permanently restricted',
    ],
    correctAnswer: 2,
    explanation: 'Under ASU 2016-14, NFPs report two classes: net assets WITH donor restrictions and net assets WITHOUT donor restrictions.',
    reference: 'ASC 958-205',
  },
  {
    id: 'far-easy-exp-024',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-V',
    blueprintGroup: 'FAR-V-A',
    topicId: 'far-nfp',
    topic: 'Not-for-Profit',
    subtopic: 'Contributions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A donor-imposed restriction that limits the use of a gift to a specific purpose is called a:',
    options: [
      'Endowment',
      'Time restriction',
      'Purpose restriction',
      'Conditional contribution',
    ],
    correctAnswer: 2,
    explanation: 'A purpose restriction limits the use of contributed assets to a specific activity or program (e.g., scholarships, research).',
    reference: 'ASC 958-605',
  },
  
  // ============================================
  // AUD EASY QUESTIONS (80 questions)
  // ============================================
  
  {
    id: 'aud-easy-exp-001',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    blueprintGroup: 'AUD-I-A',
    topicId: 'aud-independence',
    topic: 'Professional Responsibilities',
    subtopic: 'Independence',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Independence in appearance means:',
    options: [
      'Others perceive the auditor as independent',
      'The auditor actually is independent',
      'The auditor has passed background checks',
      'The auditor has no relatives',
    ],
    correctAnswer: 0,
    explanation: 'Independence in appearance means that a reasonable observer would consider the auditor to be independent. Independence in fact means actually being independent mentally.',
    reference: 'AICPA Code of Professional Conduct',
  },
  {
    id: 'aud-easy-exp-002',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    blueprintGroup: 'AUD-I-A',
    topicId: 'aud-ethics',
    topic: 'Professional Responsibilities',
    subtopic: 'AICPA Code',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The CPA\'s primary obligation is to:',
    options: [
      'The public interest',
      'The client',
      'The CPA firm',
      'The IRS',
    ],
    correctAnswer: 0,
    explanation: 'Under the AICPA Code of Professional Conduct, CPAs have a primary obligation to serve the public interest, which takes precedence over client interests.',
    reference: 'AICPA Code - Public Interest Principle',
  },
  {
    id: 'aud-easy-exp-003',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    blueprintGroup: 'AUD-I-B',
    topicId: 'aud-engagement',
    topic: 'Audit Engagements',
    subtopic: 'Types of Engagements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An audit provides what level of assurance?',
    options: [
      'Limited assurance',
      'Reasonable assurance',
      'No assurance',
      'Absolute assurance',
    ],
    correctAnswer: 1,
    explanation: 'An audit provides REASONABLE assurance (high but not absolute) that financial statements are free of material misstatement.',
    reference: 'AU-C 200',
  },
  {
    id: 'aud-easy-exp-004',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    blueprintGroup: 'AUD-I-B',
    topicId: 'aud-engagement',
    topic: 'Audit Engagements',
    subtopic: 'Types of Engagements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'During a review engagement of a non-public company, the CPA performs analytical procedures and identifies that the gross profit margin has declined from 42% to 28% year-over-year, with no known operational changes. What should the CPA do?',
    options: [
      'Issue an unmodified review report since analytical procedures are sufficient',
      'Inquire of management about the cause of the decline and evaluate whether the explanation is consistent with the CPA\'s understanding of the entity',
      'Convert the review to an audit to investigate the decline',
      'Disregard the decline because reviews provide only limited assurance',
    ],
    correctAnswer: 1,
    explanation: 'In a review engagement (AR-C 90), the CPA\'s primary procedures are inquiry and analytical procedures. When analytics reveal significant unexpected fluctuations, the CPA must perform additional inquiries of management to understand the cause and evaluate whether the explanation is plausible.',
    reference: 'AR-C 90',
  },
  {
    id: 'aud-easy-exp-005',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-I',
    blueprintGroup: 'AUD-I-B',
    topicId: 'aud-engagement',
    topic: 'Audit Engagements',
    subtopic: 'Types of Engagements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An auditor is testing inventory at a client that uses a perpetual inventory system. The client conducted a physical count three months before year-end. Under AU-C 501, can the auditor rely on the interim count?',
    options: [
      'No — the auditor must always observe inventory at year-end',
      'Yes — if the auditor determines that the perpetual records are reliable, tests the roll-forward procedures from the count date to year-end, and performs additional substantive procedures to address the intervening period',
      'Yes — interim counts are always acceptable for perpetual systems',
      'No — because three months is too long a gap between the count and year-end',
    ],
    correctAnswer: 1,
    explanation: 'AU-C 501 permits the auditor to observe inventory counts at dates other than year-end if: (1) the perpetual inventory system is reliable, (2) the auditor tests transactions in the intervening period, and (3) roll-forward procedures adequately bridge the gap.',
    reference: 'AR-C 80',
  },
  {
    id: 'aud-easy-exp-006',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    blueprintGroup: 'AUD-II-A',
    topicId: 'aud-risk',
    topic: 'Audit Risk',
    subtopic: 'Risk Components',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Inherent risk is:',
    options: [
      'The risk that internal controls fail',
      'The susceptibility of an account to misstatement, assuming no controls',
      'The risk that the auditor makes mistakes',
      'The overall risk that the auditor issues a wrong opinion',
    ],
    correctAnswer: 1,
    explanation: 'Inherent risk is the susceptibility of an assertion to material misstatement, assuming there are no related controls. Some accounts are inherently riskier (e.g., estimates, complex transactions).',
    reference: 'AU-C 200',
  },
  {
    id: 'aud-easy-exp-007',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    blueprintGroup: 'AUD-II-A',
    topicId: 'aud-risk',
    topic: 'Audit Risk',
    subtopic: 'Risk Components',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Control risk is:',
    options: [
      'The risk that controls will be too expensive',
      'The risk that misstatements will not be prevented or detected by internal controls',
      'The risk the auditor sets incorrectly',
      'Always set at the maximum level'
    ],
    correctAnswer: 1,
    explanation: 'Control risk is the risk that a material misstatement will not be prevented or detected on a timely basis by the entity\'s internal controls.',
    reference: 'AU-C 200',
  },
  {
    id: 'aud-easy-exp-008',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    blueprintGroup: 'AUD-II-A',
    topicId: 'aud-risk',
    topic: 'Audit Risk',
    subtopic: 'Risk Components',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Detection risk is:',
    options: [
      'Set by management',
      'The risk that audit procedures fail to detect a material misstatement',
      'Always high in an audit',
      'Cannot be controlled by the auditor'
    ],
    correctAnswer: 1,
    explanation: 'Detection risk is the risk that audit procedures will not detect a material misstatement. It is the only component of audit risk that the auditor can directly control.',
    reference: 'AU-C 200',
  },
  {
    id: 'aud-easy-exp-009',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    blueprintGroup: 'AUD-II-B',
    topicId: 'aud-materiality',
    topic: 'Materiality',
    subtopic: 'Definition',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A misstatement is material if it:',
    options: [
      'Was intentional',
      'Exceeds $1,000',
      'Could influence the economic decisions of users',
      'Involves cash',
    ],
    correctAnswer: 2,
    explanation: 'A misstatement is material if it could reasonably be expected to influence the economic decisions of users taken on the basis of the financial statements.',
    reference: 'AU-C 320',
  },
  {
    id: 'aud-easy-exp-010',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    blueprintGroup: 'AUD-II-C',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Components',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which is NOT a component of internal control per COSO?',
    options: [
      'Risk assessment',
      'Control environment',
      'External audit',
      'Monitoring',
    ],
    correctAnswer: 2,
    explanation: 'The five COSO components are: Control Environment, Risk Assessment, Control Activities, Information & Communication, and Monitoring. External audit is not a component.',
    reference: 'COSO Framework',
  },
  {
    id: 'aud-easy-exp-011',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    blueprintGroup: 'AUD-II-C',
    topicId: 'aud-internal-control',
    topic: 'Internal Control',
    subtopic: 'Control Environment',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The control environment is often called the:',
    options: [
      'First line of defense',
      'Detective control',
      'Tone at the top',
      'Monitoring activity',
    ],
    correctAnswer: 2,
    explanation: 'The control environment sets the "tone at the top" - management\'s and the board\'s attitude toward internal control, ethics, and integrity.',
    reference: 'COSO Framework',
  },
  {
    id: 'aud-easy-exp-012',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    blueprintGroup: 'AUD-III-A',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Sufficiency and Appropriateness',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Audit evidence is more reliable when:',
    options: [
      'Obtained from internal sources',
      'In oral form',
      'Obtained from external sources',
      'Provided by management',
    ],
    correctAnswer: 2,
    explanation: 'Evidence from external, independent sources (e.g., bank confirmations) is generally more reliable than evidence generated internally.',
    reference: 'AU-C 500',
  },
  {
    id: 'aud-easy-exp-013',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    blueprintGroup: 'AUD-III-A',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Types of Procedures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which audit procedure provides the MOST reliable evidence for existence?',
    options: [
      'Inspection',
      'Inquiry',
      'Observation',
      'External confirmation',
    ],
    correctAnswer: 3,
    explanation: 'External confirmation (e.g., bank confirmation, A/R confirmation) provides strong evidence for existence from an independent third party.',
    reference: 'AU-C 500',
  },
  {
    id: 'aud-easy-exp-014',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    blueprintGroup: 'AUD-III-B',
    topicId: 'aud-assertions',
    topic: 'Management Assertions',
    subtopic: 'Balance Sheet Assertions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Testing that all assets actually exist relates to which assertion?',
    options: [
      'Existence',
      'Valuation',
      'Completeness',
      'Rights and obligations',
    ],
    correctAnswer: 0,
    explanation: 'Existence assertion addresses whether assets, liabilities, and equity interests exist as of a given date.',
    reference: 'AU-C 315',
  },
  {
    id: 'aud-easy-exp-015',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    blueprintGroup: 'AUD-III-B',
    topicId: 'aud-assertions',
    topic: 'Management Assertions',
    subtopic: 'Balance Sheet Assertions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Testing that all liabilities are recorded relates to which assertion?',
    options: [
      'Rights and obligations',
      'Completeness',
      'Existence',
      'Presentation',
    ],
    correctAnswer: 1,
    explanation: 'Completeness assertion addresses whether all transactions and accounts that should be recorded have been recorded.',
    reference: 'AU-C 315',
  },
  {
    id: 'aud-easy-exp-016',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    blueprintGroup: 'AUD-III-C',
    topicId: 'aud-sampling',
    topic: 'Audit Sampling',
    subtopic: 'Types',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Statistical sampling differs from nonstatistical sampling because statistical sampling:',
    options: [
      'Is always more accurate',
      'Allows mathematical measurement of sampling risk',
      'Requires smaller sample sizes',
      'Is required by auditing standards'
    ],
    correctAnswer: 1,
    explanation: 'Statistical sampling uses probability theory to measure sampling risk mathematically. Both methods can be effective if properly applied.',
    reference: 'AU-C 530',
  },
  {
    id: 'aud-easy-exp-017',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    blueprintGroup: 'AUD-IV-A',
    topicId: 'aud-reports',
    topic: 'Audit Reports',
    subtopic: 'Opinion Types',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An unmodified opinion means:',
    options: [
      'The financial statements are fairly presented in all material respects',
      'The auditor found no problems whatsoever',
      'The company will continue as a going concern',
      'Internal controls are effective',
    ],
    correctAnswer: 0,
    explanation: 'An unmodified (clean) opinion states that the financial statements are fairly presented in all material respects in accordance with the applicable framework.',
    reference: 'AU-C 700',
  },
  {
    id: 'aud-easy-exp-018',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    blueprintGroup: 'AUD-IV-A',
    topicId: 'aud-reports',
    topic: 'Audit Reports',
    subtopic: 'Opinion Types',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A qualified opinion is issued when:',
    options: [
      'There is a material but not pervasive issue',
      'The auditor is not qualified to audit',
      'The financial statements are pervasively misstated',
      'The auditor cannot complete the audit',
    ],
    correctAnswer: 0,
    explanation: 'A qualified opinion is issued when there is a material misstatement or scope limitation that is NOT pervasive to the financial statements as a whole.',
    reference: 'AU-C 705',
  },
  {
    id: 'aud-easy-exp-019',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    blueprintGroup: 'AUD-IV-A',
    topicId: 'aud-reports',
    topic: 'Audit Reports',
    subtopic: 'Opinion Types',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An auditor completes an audit and concludes that the financial statements are presented fairly in all material respects in accordance with GAAP. What type of opinion is this?',
    options: [
      'Qualified opinion',
      'Adverse opinion',
      'Unqualified (unmodified) opinion',
      'Disclaimer of opinion',
    ],
    correctAnswer: 2,
    explanation: 'An unqualified (unmodified) opinion states that the financial statements present fairly, in all material respects, the financial position, results of operations, and cash flows in accordance with the applicable framework. This is the clean opinion indicating no material misstatements or scope limitations.',
    reference: 'AU-C 700',
  },
  {
    id: 'aud-easy-exp-020',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    blueprintGroup: 'AUD-IV-A',
    topicId: 'aud-reports',
    topic: 'Audit Reports',
    subtopic: 'Opinion Types',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An auditor is testing the accuracy of a client\'s depreciation expense calculation. The client uses the straight-line method with a 10-year useful life and no salvage value for equipment purchased at $200,000. The client recorded $25,000 in depreciation expense for a full year. What should the auditor conclude?',
    options: [
      'The depreciation expense is correctly calculated',
      'The depreciation expense is overstated by $5,000 — the correct amount is $20,000 per year',
      'The depreciation expense is understated by $5,000',
      'More information is needed about the half-year convention',
    ],
    correctAnswer: 1,
    explanation: 'Straight-line depreciation = (Cost − Salvage) / Useful life = ($200,000 − $0) / 10 = $20,000 per year. The client recorded $25,000, which is $5,000 too high. The auditor should investigate whether the error is isolated or systematic.',
    reference: 'AU-C 705',
  },
  
  // ============================================
  // REG EASY QUESTIONS (80 questions)
  // ============================================
  
  {
    id: 'reg-easy-exp-001',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-I',
    blueprintGroup: 'REG-I-A',
    topicId: 'reg-ethics',
    topic: 'Ethics',
    subtopic: 'Circular 230',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A CPA preparing tax returns is regulated by:',
    options: [
      'State boards only',
      'Treasury Department Circular 230',
      'The IRS Criminal Investigation Division',
      'The SEC only',
    ],
    correctAnswer: 1,
    explanation: 'Circular 230 regulates practice before the IRS, including CPAs, enrolled agents, and attorneys who prepare tax returns or represent clients.',
    reference: 'Circular 230',
  },
  {
    id: 'reg-easy-exp-002',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-I',
    blueprintGroup: 'REG-I-B',
    topicId: 'reg-procedures',
    topic: 'Tax Procedures',
    subtopic: 'Filing Requirements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For 2024, the federal income tax return filing deadline for individuals is:',
    options: [
      'April 15',
      'October 15',
      'June 15',
      'March 15',
    ],
    correctAnswer: 0,
    explanation: 'Individual federal income tax returns (Form 1040) are due April 15 following the tax year (or the next business day if April 15 falls on a weekend/holiday).',
    reference: 'IRC §6072',
  },
  {
    id: 'reg-easy-exp-003',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-I',
    blueprintGroup: 'REG-I-B',
    topicId: 'reg-procedures',
    topic: 'Tax Procedures',
    subtopic: 'Extensions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An individual can obtain an automatic extension of time to file by filing Form 4868. This extension:',
    options: [
      'Requires IRS approval',
      'Extends only the time to file, not to pay',
      'Extends the time to file for 1 year',
      'Extends the time to pay taxes',
    ],
    correctAnswer: 1,
    explanation: 'Form 4868 provides an automatic 6-month extension to FILE (until October 15), but does NOT extend the time to PAY. Taxes are still due April 15.',
    reference: 'IRC §6081',
  },
  {
    id: 'reg-easy-exp-004',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-II',
    blueprintGroup: 'REG-II-A',
    topicId: 'reg-contracts',
    topic: 'Business Law',
    subtopic: 'Contract Formation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For a valid contract to exist, there must be:',
    options: [
      'A notarized agreement',
      'Signature of both parties',
      'Offer, acceptance, and consideration',
      'A written document',
    ],
    correctAnswer: 2,
    explanation: 'A valid contract requires: (1) Offer, (2) Acceptance, (3) Consideration, (4) Capacity, and (5) Legality. Writing is NOT always required.',
    reference: 'Contract Law',
  },
  {
    id: 'reg-easy-exp-005',
    courseId: 'cpa',
    section: 'REG',
    blueprintArea: 'REG-II',
    topic: 'Business Law',
    subtopic: 'Statute of Frauds',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under the Statute of Frauds, which of the following types of contracts must generally be evidenced by a writing to be enforceable?',
    options: [
      'A contract for the sale of real property',
      'A contract for the sale of goods priced at $200',
      'A service contract to be completed within 6 months',
      'An oral agreement to hire a contractor for home repairs',
    ],
    correctAnswer: 0,
    explanation: 'The Statute of Frauds requires contracts for the sale of interests in real property to be in writing. Other categories requiring a writing include: contracts that cannot be performed within one year, sale of goods $500+ (UCC), suretyship/guaranty agreements, and contracts in consideration of marriage. A $200 goods sale is under the UCC threshold, and contracts completable within one year are not covered.',
    reference: 'Statute of Frauds',
  },
  {
    id: 'reg-easy-exp-006',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-II',
    blueprintGroup: 'REG-II-B',
    topicId: 'reg-agency',
    topic: 'Business Law',
    subtopic: 'Agency',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A principal is liable for an agent\'s acts within the scope of:',
    options: [
      'Express, implied, and apparent authority',
      'No authority',
      'Apparent authority only',
      'Express authority only',
    ],
    correctAnswer: 0,
    explanation: 'A principal is bound by acts within the agent\'s express authority (stated), implied authority (reasonably necessary), and apparent authority (reasonable third-party belief).',
    reference: 'Agency Law',
  },
  {
    id: 'reg-easy-exp-007',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-A',
    topicId: 'reg-gross-income',
    topic: 'Individual Taxation',
    subtopic: 'Gross Income',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which is included in gross income?',
    options: [
      'Salary and wages',
      'Gifts received',
      'Life insurance proceeds paid to beneficiary',
      'Municipal bond interest',
    ],
    correctAnswer: 0,
    explanation: 'Salary and wages are taxable gross income. Municipal bond interest, gifts, and life insurance death proceeds are generally excluded from gross income.',
    reference: 'IRC §61',
  },
  {
    id: 'reg-easy-exp-008',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-A',
    topicId: 'reg-gross-income',
    topic: 'Individual Taxation',
    subtopic: 'Exclusions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Interest on municipal bonds is:',
    options: [
      'Subject to AMT only',
      'Excluded from federal gross income',
      'Taxable if the bond is purchased',
      'Fully taxable',
    ],
    correctAnswer: 1,
    explanation: 'Interest on state and local municipal bonds is excluded from federal gross income. It may be subject to state taxes or AMT for certain private activity bonds.',
    reference: 'IRC §103',
  },
  {
    id: 'reg-easy-exp-009',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-B',
    topicId: 'reg-adjustments',
    topic: 'Individual Taxation',
    subtopic: 'Adjustments',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Adjustments to income are also called:',
    options: [
      'Above-the-line deductions',
      'Tax credits',
      'Below-the-line deductions',
      'Itemized deductions',
    ],
    correctAnswer: 0,
    explanation: 'Adjustments to income (e.g., student loan interest, IRA contributions) are "above-the-line" deductions subtracted from gross income to arrive at AGI.',
    reference: 'IRC §62',
  },
  {
    id: 'reg-easy-exp-010',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-B',
    topicId: 'reg-agi',
    topic: 'Individual Taxation',
    subtopic: 'AGI Calculation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'AGI stands for:',
    options: [
      'Accumulated Gross Income',
      'Adjusted Gross Income',
      'Alternative Gross Income',
      'Annual Gross Income',
    ],
    correctAnswer: 1,
    explanation: 'AGI (Adjusted Gross Income) = Gross Income - Adjustments. AGI is important because many deductions and credits are based on AGI limitations.',
    reference: 'IRC §62',
  },
  {
    id: 'reg-easy-exp-011',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-C',
    topicId: 'reg-deductions',
    topic: 'Individual Taxation',
    subtopic: 'Standard vs Itemized',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A taxpayer should itemize deductions when:',
    options: [
      'Never, standard deduction is always better',
      'Itemized deductions exceed the standard deduction',
      'Income exceeds $100,000',
      'Always',
    ],
    correctAnswer: 1,
    explanation: 'A taxpayer should itemize when total itemized deductions (SALT, mortgage interest, charitable, medical) exceed the standard deduction.',
    reference: 'IRC §63',
  },
  {
    id: 'reg-easy-exp-012',
    courseId: 'cpa',
    section: 'REG',
    blueprintArea: 'REG-III',
    topic: 'Individual Taxation',
    subtopic: 'Itemized Deductions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A taxpayer paid $14,000 in mortgage interest on a primary residence (post-2017 mortgage of $600,000), $4,500 in state income taxes, $3,800 in real property taxes, and $2,000 in charitable contributions during 2024. What is the total itemized deduction?',
    options: [
      '$26,300',
      '$24,300',
      '$22,300',
      '$20,000',
    ],
    correctAnswer: 0,
    explanation: 'Itemized deductions: mortgage interest on $600,000 (under $750,000 limit) = $14,000 (fully deductible). State and local taxes (SALT) = $4,500 + $3,800 = $8,300, under the $10,000 cap so fully deductible. Charitable = $2,000. Total = $14,000 + $8,300 + $2,000 = $24,300.',
    reference: 'IRC §164',
  },
  {
    id: 'reg-easy-exp-013',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-D',
    topicId: 'reg-filing-status',
    topic: 'Individual Taxation',
    subtopic: 'Filing Status',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which filing status generally provides the most favorable tax rates?',
    options: [
      'Married Filing Separately',
      'Head of Household for married persons',
      'Married Filing Jointly',
      'Single',
    ],
    correctAnswer: 2,
    explanation: 'Married Filing Jointly generally provides the most favorable rates and highest standard deduction. MFS is usually the least favorable.',
    reference: 'IRC §1',
  },
  {
    id: 'reg-easy-exp-014',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-E',
    topicId: 'reg-credits',
    topic: 'Individual Taxation',
    subtopic: 'Tax Credits',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following best describes the effect of a tax credit on a taxpayer\'s liability?',
    options: [
      'Increases AGI',
      'Is the same as a deduction',
      'Reduces tax liability dollar-for-dollar',
      'Reduces taxable income',
    ],
    correctAnswer: 2,
    explanation: 'A tax credit directly reduces tax liability dollar-for-dollar. A $1,000 credit saves $1,000 in taxes. Deductions only reduce taxable income.',
    reference: 'Tax Credits',
  },
  {
    id: 'reg-easy-exp-015',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    blueprintGroup: 'REG-III-E',
    topicId: 'reg-credits',
    topic: 'Individual Taxation',
    subtopic: 'Child Tax Credit',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The Child Tax Credit for a qualifying child under 17 is:',
    options: [
      '$3,600 per child',
      '$3,000 per child',
      '$2,000 per child',
      '$1,000 per child',
    ],
    correctAnswer: 2,
    explanation: 'The Child Tax Credit is $2,000 per qualifying child under age 17, with up to $1,600 refundable (2024). Subject to income phase-outs.',
    reference: 'IRC §24',
  },
  {
    id: 'reg-easy-exp-016',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    blueprintGroup: 'REG-IV-A',
    topicId: 'reg-partnerships',
    topic: 'Entity Taxation',
    subtopic: 'Partnerships',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following best describes a partnership for federal income tax purposes?',
    options: [
      'Is a pass-through entity - partners pay tax',
      'Files no tax returns',
      'Is taxed as a corporation',
      'Pays income tax at the entity level',
    ],
    correctAnswer: 0,
    explanation: 'Partnerships are pass-through entities. The partnership files Form 1065 for information purposes, but partners report their share of income on their personal returns.',
    reference: 'IRC §701',
  },
  {
    id: 'reg-easy-exp-017',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    blueprintGroup: 'REG-IV-A',
    topicId: 'reg-partnerships',
    topic: 'Entity Taxation',
    subtopic: 'Partnership Formation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A partner contributing property to a partnership generally:',
    options: [
      'Recognizes no gain or loss',
      'Receives fair market value basis',
      'Must contribute cash only',
      'Recognizes gain on the contribution',
    ],
    correctAnswer: 0,
    explanation: 'Under IRC §721, no gain or loss is recognized on contribution of property to a partnership in exchange for a partnership interest.',
    reference: 'IRC §721',
  },
  {
    id: 'reg-easy-exp-019',
    courseId: 'cpa',
    section: 'REG',
    blueprintArea: 'REG-IV',
    topic: 'Entity Taxation',
    subtopic: 'C Corporations',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A newly formed C corporation had the following in its first year: $200,000 gross revenue, $150,000 in deductible operating expenses, and $5,000 in organizational expenditures. Under IRC §248, how much of the organizational expenditures may be deducted in the first year?',
    options: [
      '$5,000',
      '$0',
      '$3,000',
      '$1,000',
    ],
    correctAnswer: 0,
    explanation: 'Under IRC §248, a corporation may elect to deduct up to $5,000 of organizational expenditures in the first year. This $5,000 allowance is reduced dollar-for-dollar when total organizational costs exceed $50,000. Since the corporation\'s $5,000 in organizational costs is within the $5,000 limit and does not exceed $50,000, the entire amount is deductible in year one.',
    reference: 'IRC §11',
  },
  {
    id: 'reg-easy-exp-020',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    blueprintGroup: 'REG-IV-C',
    topicId: 'reg-c-corps',
    topic: 'Entity Taxation',
    subtopic: 'Double Taxation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Double taxation of corporate income means:',
    options: [
      'Income is taxed at corporate level and again when distributed as dividends',
      'Tax is paid in two installments',
      'Both federal and state taxes apply',
      'Corporations pay twice the normal rate',
    ],
    correctAnswer: 0,
    explanation: 'C corporation earnings are taxed first at the corporate level (21%), then again when distributed to shareholders as dividends (qualified dividend rate up to 20%).',
    reference: 'Corporate Taxation',
  },
];

export default EASY_QUESTIONS_EXPANDED;
