// FAR Depth Questions - Batch 19
// Focus: FAR-II (Select Financial Statement Accounts)
// Topics: Leases (ASC 842), Fair Value (ASC 820), Subsequent Events, Segment Reporting
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const FAR_QUESTIONS_DEPTH_19: Question[] = [
  {
    id: 'far-d19-001',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lessee Classification',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 842, a lessee classifies a lease as a finance lease if any of the following criteria are met EXCEPT:',
    options: [
      'The lease transfers ownership at the end of the lease term',
      'The lease contains a purchase option the lessee is reasonably certain to exercise',
      'The lease term is less than 12 months',
      'The present value of lease payments equals or exceeds substantially all of the fair value of the asset',
    ],
    correctAnswer: 2,
    explanation: 'Under ASC 842-10-25-2, a lessee classifies a lease as a finance lease if ANY one of five criteria is met: (1) transfer of ownership, (2) purchase option reasonably certain to be exercised, (3) lease term is for major part of economic life, (4) PV of payments equals substantially all of fair value, (5) the asset is specialized with no alternative use. A lease term of less than 12 months is not a classification criterion — it triggers the short-term lease exemption, which allows the lessee to NOT recognize a right-of-use asset or lease liability.',
    reference: 'ASC 842-10-25-2',
  },
  {
    id: 'far-d19-002',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Operating Lease — Lessee',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 842, a lessee with an operating lease records on its balance sheet:',
    options: [
      'Nothing — operating leases are off-balance sheet',
      'A right-of-use (ROU) asset and a lease liability, both initially measured at the present value of lease payments',
      'Only a lease liability',
      'Only a right-of-use asset',
    ],
    correctAnswer: 1,
    explanation: 'ASC 842 fundamentally changed operating lease accounting for lessees by requiring recognition of BOTH a right-of-use (ROU) asset and a lease liability on the balance sheet for virtually all leases with terms greater than 12 months. Both are initially measured at the present value of future lease payments using the rate implicit in the lease (if determinable) or the lessee\'s incremental borrowing rate. The lease liability is reduced as payments are made. The ROU asset is reduced through straight-line lease expense (for operating leases). This differs from finance leases where amortization and interest are recognized separately.',
    reference: 'ASC 842-20-30-1',
  },
  {
    id: 'far-d19-003',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Finance Lease — Lessee Expense Pattern',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'For a finance lease, the lessee recognizes expense that is:',
    options: [
      'Straight-line (single lease cost) over the lease term',
      'Front-loaded — amortization of the ROU asset plus interest on the lease liability, resulting in higher total expense in earlier years',
      'Recognized only at the end of the lease',
      'Deferred until the asset is returned',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-20-25-5, a finance lease results in a front-loaded expense pattern because two components are recognized separately: (1) amortization of the ROU asset (typically straight-line), and (2) interest on the lease liability (using the effective interest method — higher in early years when the balance is larger). Total expense = amortization + interest, which is higher in the beginning and decreases over time. This contrasts with an operating lease, where a single lease cost is recognized on a straight-line basis (the ROU asset is adjusted to achieve straight-line total expense).',
    reference: 'ASC 842-20-25-5; ASC 842-20-35-1',
  },
  {
    id: 'far-d19-004',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lessor — Sales-Type Lease',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A lessor classifies a lease as a sales-type lease and has a cost basis of $80,000 in the underlying asset with a fair value of $100,000. At lease commencement, the lessor recognizes:',
    options: [
      'Only a lease receivable of $100,000',
      'A net investment in the lease (lease receivable) of $100,000, revenue of $100,000, and cost of goods sold of $80,000 — resulting in a $20,000 gross profit',
      'Rental income of $100,000 over the lease term',
      'No profit at commencement',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-30-25-1, a lessor in a sales-type lease derecognizes the underlying asset and recognizes a net investment in the lease (present value of lease payments plus unguaranteed residual value). At commencement: revenue is recognized equal to the fair value of the asset ($100,000), COGS equals the carrying amount adjusted for any retained residual ($80,000), and a selling profit of $20,000 is recognized. The lease receivable is subsequently measured using the effective interest method. This treatment mirrors the economics of a sale.',
    reference: 'ASC 842-30-25-1 through 5',
  },
  {
    id: 'far-d19-005',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lease Modifications',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A lessee modifies an operating lease to extend the term by 3 years and increase annual payments from $50,000 to $60,000. The modification grants the lessee an additional right of use not included in the original lease. Under ASC 842, the modification is treated as:',
    options: [
      'A continuation of the original lease with no adjustments',
      'A separate contract if the additional right of use is priced commensurate with its standalone price; otherwise, a remeasurement of the existing lease',
      'An immediate gain or loss',
      'A new lease from inception',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-10-25-8, a lease modification that grants an additional right of use not in the original lease is treated as a separate contract if: (1) the modification increases the scope by adding the right to use one or more underlying assets, AND (2) the consideration is commensurate with the standalone price for the additional right of use adjusted for the contract circumstances. If both criteria are met, it\'s a separate lease. If not, the lessee remeasures the lease liability using a revised discount rate and adjusts the ROU asset accordingly.',
    reference: 'ASC 842-10-25-8 through 15',
  },
  {
    id: 'far-d19-006',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Variable Lease Payments',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 842, variable lease payments that are based on an index or rate (such as CPI-linked payments) are:',
    options: [
      'Excluded from the lease liability measurement',
      'Included in the initial measurement of the lease liability using the index or rate as of the commencement date',
      'Expensed as incurred',
      'Included only if they exceed a cap',
    ],
    correctAnswer: 1,
    explanation: 'ASC 842-10-30-5 distinguishes between two types of variable lease payments: (1) those dependent on an index or rate (e.g., CPI adjustments) — these ARE included in the initial measurement using the index or rate as of commencement and are remeasured when the lease liability is remeasured; and (2) those dependent on performance or usage (e.g., percentage rent based on sales) — these are NOT included in the lease liability and are expensed as incurred. The distinction is critical because it affects the initial ROU asset and lease liability measurement.',
    reference: 'ASC 842-10-30-5',
  },
  {
    id: 'far-d19-007',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Sale-Leaseback',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a sale-leaseback transaction under ASC 842, if the transfer of the asset qualifies as a sale under ASC 606:',
    options: [
      'The seller-lessee recognizes the full gain on sale immediately',
      'The seller-lessee recognizes a gain only for the amount attributable to the rights transferred (not the rights retained through the leaseback)',
      'No gain is recognized; the asset stays on the seller-lessee\'s books',
      'The transaction is treated as a financing arrangement',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-40-25-4, if the transfer of the asset qualifies as a sale (meets the ASC 606 control transfer criteria), the seller-lessee: (1) derecognizes the asset, (2) accounts for the leaseback as any other lease (ROU asset and lease liability), and (3) recognizes only the gain or loss attributable to the rights transferred to the buyer-lessor — NOT the portion retained through the leaseback. If the transfer does NOT qualify as a sale, both parties account for the transaction as a financing arrangement (the asset remains on the seller-lessee\'s books).',
    reference: 'ASC 842-40-25-4',
  },
  {
    id: 'far-d19-008',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Fair Value Hierarchy',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 820, Level 1 inputs in the fair value hierarchy are:',
    options: [
      'Unobservable inputs based on management assumptions',
      'Quoted prices in active markets for identical assets or liabilities',
      'Observable inputs other than Level 1 prices (e.g., quoted prices for similar assets)',
      'Entity-specific valuations',
    ],
    correctAnswer: 1,
    explanation: 'ASC 820-10-35-40 through 56 establishes a three-level fair value hierarchy: Level 1: Quoted prices (unadjusted) in active markets for identical assets or liabilities — the most reliable inputs. Level 2: Observable inputs other than Level 1 prices — quoted prices for similar assets, interest rates, yield curves, credit spreads, etc. Level 3: Unobservable inputs — management\'s own assumptions about what market participants would use, including entity-specific data. The hierarchy prioritizes Level 1 inputs over Level 2, and Level 2 over Level 3.',
    reference: 'ASC 820-10-35-40 through 56',
  },
  {
    id: 'far-d19-009',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Principal Market',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 820, fair value is measured based on the price in the:',
    options: [
      'Market that gives the entity the best price',
      'Principal market (the market with the greatest volume and level of activity for the asset or liability), or the most advantageous market if no principal market exists',
      'Entity\'s home jurisdiction only',
      'Most recent market transaction',
    ],
    correctAnswer: 1,
    explanation: 'ASC 820-10-35-5 specifies that fair value is measured based on the price in the principal market — the market with the greatest volume and level of activity for the asset or liability. If there is no principal market, the most advantageous market is used (the market that maximizes the amount received for an asset or minimizes the amount paid for a liability, after considering transaction and transportation costs). Transaction costs are excluded from the fair value measurement itself but are considered when determining the most advantageous market.',
    reference: 'ASC 820-10-35-5',
  },
  {
    id: 'far-d19-010',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Valuation Approaches',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The income approach to fair value measurement under ASC 820 involves:',
    options: [
      'Comparing to recent sales of similar assets',
      'Converting future amounts (such as cash flows or income) to a single present value using discounting techniques',
      'Determining the current replacement cost of the asset',
      'Using the original purchase price',
    ],
    correctAnswer: 1,
    explanation: 'ASC 820-10-35-32 identifies three valuation approaches: (1) Market approach — uses prices and other relevant information from market transactions involving identical or comparable assets (comparables method); (2) Income approach — converts future amounts to a single present value using discounting, option pricing models, or multi-period excess earnings methods; (3) Cost approach — determines the current replacement cost to replace the service capacity of the asset (adjusted for obsolescence). The income approach is commonly used for Level 3 measurements, intangible assets, and businesses.',
    reference: 'ASC 820-10-35-32',
  },
  {
    id: 'far-d19-011',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Highest and Best Use',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When measuring the fair value of a nonfinancial asset, ASC 820 requires the measurement to reflect:',
    options: [
      'The asset\'s current use by the entity',
      'The highest and best use of the asset from a market participant\'s perspective',
      'The asset\'s historical cost',
      'The lowest possible value (conservatism)',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 820-10-35-10, the fair value of a nonfinancial asset is based on its highest and best use as determined by market participants. Highest and best use considers what is physically possible, legally permissible, and financially feasible. The current use is presumed to be highest and best use unless market evidence suggests otherwise. For financial assets and liabilities, highest and best use is not relevant since they are fungible. This concept is particularly important for real estate and specialized assets.',
    reference: 'ASC 820-10-35-10',
  },
  {
    id: 'far-d19-012',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-subsequent-events',
    topic: 'Subsequent Events',
    subtopic: 'Recognized vs. Nonrecognized',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 855, a subsequent event that provides additional evidence about conditions that existed at the balance sheet date is classified as:',
    options: [
      'A nonrecognized subsequent event — disclosed only',
      'A recognized subsequent event — the financial statements are adjusted',
      'Not relevant to the financial statements',
      'An extraordinary item',
    ],
    correctAnswer: 1,
    explanation: 'ASC 855-10-25-1 classifies subsequent events into two types: (1) Recognized (Type I): Events that provide additional evidence about conditions existing at the balance sheet date — the financial statements are adjusted for these events. Examples: settlement of litigation outstanding at year-end, collection of a receivable that confirms it was uncollectible at year-end. (2) Nonrecognized (Type II): Events that are indicative of conditions arising after the balance sheet date — disclosure is required but no adjustment is made. Examples: fire, flood, business combination, or stock issuance after year-end.',
    reference: 'ASC 855-10-25-1 through 3',
  },
  {
    id: 'far-d19-013',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-subsequent-events',
    topic: 'Subsequent Events',
    subtopic: 'Evaluation Period',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'An entity must evaluate subsequent events through the date the financial statements are:',
    options: [
      'Prepared by the accounting department',
      'Issued (for SEC filers) or available to be issued (for non-SEC filers)',
      'Audited',
      'Filed with the SEC',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 855-10-25-1A, the subsequent event evaluation period depends on the type of filer: SEC filers evaluate events through the date the financial statements are issued (filed with the SEC). Non-SEC filers evaluate through the date the financial statements are available to be issued (when all information is obtainable and the statements are in a form ready for distribution). The entity must disclose the date through which subsequent events have been evaluated in the notes to the financial statements.',
    reference: 'ASC 855-10-25-1A',
  },
  {
    id: 'far-d19-014',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Short-Term Lease Exemption',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 842, a lessee may elect not to recognize a right-of-use asset and lease liability for leases with a term of:',
    options: [
      '24 months or less',
      '12 months or less at commencement, provided the lease does not contain a purchase option the lessee is reasonably certain to exercise',
      '36 months or less',
      '6 months or less',
    ],
    correctAnswer: 1,
    explanation: 'ASC 842-20-25-2 provides a practical expedient allowing lessees to elect, by class of underlying asset, not to recognize ROU assets and lease liabilities for short-term leases — defined as leases with a term of 12 months or less at the commencement date that do not include a purchase option the lessee is reasonably certain to exercise. If elected, lease payments are recognized as expense on a straight-line basis over the lease term. The election is made by class of underlying asset (not lease-by-lease).',
    reference: 'ASC 842-20-25-2',
  },
  {
    id: 'far-d19-015',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lessee Discount Rate',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A lessee should discount future lease payments using:',
    options: [
      'The lessee\'s weighted-average cost of capital',
      'The rate implicit in the lease if readily determinable; otherwise, the lessee\'s incremental borrowing rate',
      'The prime rate published by the Federal Reserve',
      'The risk-free rate',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-20-30-3, the lessee uses the rate implicit in the lease as the discount rate if it is readily determinable. The rate implicit in the lease is the rate at which the present value of lease payments plus the PV of the unguaranteed residual value equals the fair value of the underlying asset plus any deferred initial direct costs of the lessor. In practice, this rate is often not readily determinable for lessees, so the lessee\'s incremental borrowing rate (the rate the lessee would pay to borrow over a similar term, on a collateralized basis) is used as a practical alternative.',
    reference: 'ASC 842-20-30-3',
  },
  {
    id: 'far-d19-016',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-segment',
    topic: 'Segment Reporting',
    subtopic: 'Quantitative Thresholds',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 280, an operating segment is a reportable segment if it meets any of the 10% quantitative thresholds. Which of the following is one of these tests?',
    options: [
      'The segment\'s employees are at least 10% of total employees',
      'The segment\'s reported revenue (external + intersegment) is 10% or more of combined revenue of all operating segments',
      'The segment has been in existence for at least 10% of the entity\'s life',
      'The segment\'s assets are at least 10% of total entity assets excluding goodwill',
    ],
    correctAnswer: 1,
    explanation: 'ASC 280-10-50-12 specifies three 10% quantitative thresholds for reportable segments: (1) Revenue test: the segment\'s revenue (including intersegment revenue) is 10% or more of combined revenue of ALL operating segments; (2) Profit or loss test: the absolute amount of the segment\'s profit or loss is 10% or more of the greater (in absolute amount) of combined profit of all profitable segments or combined loss of all loss segments; (3) Asset test: the segment\'s assets are 10% or more of combined assets of all operating segments. Meeting any ONE threshold makes the segment reportable.',
    reference: 'ASC 280-10-50-12',
  },
  {
    id: 'far-d19-017',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-segment',
    topic: 'Segment Reporting',
    subtopic: '75% Test',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 280, after applying the 10% thresholds, reportable segments must represent at least what percentage of consolidated external revenue?',
    options: [
      '50%',
      '75% of total consolidated external revenue',
      '90%',
      '100%',
    ],
    correctAnswer: 1,
    explanation: 'ASC 280-10-50-15 requires that reportable segments represent at least 75% of total consolidated external revenue. If the reportable segments identified by the 10% thresholds do not meet this 75% test, additional operating segments must be identified as reportable segments until the 75% threshold is met. Any remaining operating segments that are not separately reportable are combined and disclosed in an "all other" category. This ensures that substantial revenue concentration is visible to financial statement users.',
    reference: 'ASC 280-10-50-15',
  },
  {
    id: 'far-d19-018',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Blockage Factor',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 820, when measuring fair value of a financial asset with a Level 1 (quoted price) input, may the entity apply a blockage factor (discount due to holding a large block)?',
    options: [
      'Yes, the entity should adjust for the size of its holding',
      'No — ASC 820 prohibits adjustments to Level 1 quoted prices, including blockage factors',
      'Only for illiquid securities',
      'Only if the block exceeds 50% of the outstanding shares',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 820-10-35-36B, when a Level 1 quoted price is used, the entity must use that price WITHOUT adjustment, even if the entity holds a large enough position that selling the block at once might affect the market price (blockage factor). The rationale is that Level 1 inputs are the most reliable and should not be adjusted. The unit of account for financial assets is typically the individual instrument, not the position as a whole. Blockage factors may, however, be considered when using Level 2 or Level 3 inputs where the position size is relevant to pricing.',
    reference: 'ASC 820-10-35-36B',
  },
  {
    id: 'far-d19-019',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lease Incentives',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 842, lease incentives received by the lessee (such as tenant improvement allowances) are:',
    options: [
      'Recognized as revenue by the lessee',
      'Deducted from the initial measurement of the ROU asset',
      'Added to the lease liability',
      'Expensed immediately',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-10-30-2, lease incentives received by the lessee reduce the initial measurement of the ROU asset. Common lease incentives include tenant improvement allowances, moving cost reimbursements, and rent-free periods. The lease liability is measured at the present value of the lease payments (not affected by incentives already received at or before commencement). The reduced ROU asset is then amortized over the lease term (through the single lease cost for operating leases, or through amortization for finance leases).',
    reference: 'ASC 842-10-30-2',
  },
  {
    id: 'far-d19-020',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-bonds',
    topic: 'Bonds Payable',
    subtopic: 'Callable Bonds',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has outstanding bonds with a carrying amount of $1,020,000 (issued at a premium). The bonds are called at 102% of the $1,000,000 face value. The gain or loss on extinguishment is:',
    options: [
      'No gain or loss',
      'A loss of $20,000',
      'A gain of $20,000',
      'A loss of $1,020,000',
    ],
    correctAnswer: 0,
    explanation: 'The call price = $1,000,000 × 102% = $1,020,000. The carrying amount = $1,020,000 (face value plus unamortized premium). Gain/loss = carrying amount – reacquisition price = $1,020,000 – $1,020,000 = $0. In this case, the premium has been amortized to the exact amount matching the call price, resulting in no gain or loss. In practice, the amounts rarely match exactly, and a gain or loss is recognized as the difference between the call price and the carrying amount of the bonds (including any unamortized premium/discount and debt issuance costs).',
    reference: 'ASC 470-50-40-2',
  },
  {
    id: 'far-d19-021',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-income-tax',
    topic: 'Income Taxes',
    subtopic: 'Book-Tax Differences — Common Temporary',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following creates a temporary difference for income tax purposes?',
    options: [
      'Fines and penalties paid to the government',
      'Depreciation when MACRS tax depreciation exceeds straight-line book depreciation',
      'Tax-exempt municipal bond interest',
      'Meals and entertainment disallowed portion',
    ],
    correctAnswer: 1,
    explanation: 'Depreciation differences between tax (MACRS — accelerated) and book (straight-line) create a temporary (timing) difference. In early years, tax depreciation exceeds book depreciation, reducing taxable income below book income — creating a deferred tax liability (future taxable amount). In later years, the pattern reverses. Fines and penalties, tax-exempt interest, and the disallowed portion of meals and entertainment are permanent differences — they never reverse and do NOT create deferred taxes.',
    reference: 'ASC 740-10-25-20',
  },
  {
    id: 'far-d19-022',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Recurring vs. Nonrecurring',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 820, fair value measurements required at each reporting period (such as trading securities) are classified as:',
    options: [
      'Nonrecurring fair value measurements',
      'Recurring fair value measurements',
      'One-time measurements',
      'Periodic estimates',
    ],
    correctAnswer: 1,
    explanation: 'ASC 820 distinguishes between recurring and nonrecurring fair value measurements for disclosure purposes. Recurring measurements are required at each reporting period (e.g., trading securities, AFS debt securities, derivative instruments, pension plan assets). Nonrecurring measurements are required only when specific events or circumstances occur (e.g., impairment of goodwill, long-lived assets measured at fair value less costs to sell when classified as held for sale). Both types require the same fair value hierarchy disclosures, but recurring measurements require additional disclosures about transfers between levels.',
    reference: 'ASC 820-10-50',
  },
  {
    id: 'far-d19-023',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lessor — Direct Financing Lease',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a direct financing lease, unlike a sales-type lease, the lessor:',
    options: [
      'Derecognizes the underlying asset and recognizes selling profit at commencement',
      'Derecognizes the underlying asset but defers any selling profit and recognizes it over the lease term as interest income',
      'Does not derecognize the underlying asset',
      'Recognizes rental income on a straight-line basis',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-30-25-7, in a direct financing lease, the lessor derecognizes the underlying asset and recognizes a net investment in the lease, similar to a sales-type lease. However, any selling profit is deferred and recognized over the lease term by adjusting the effective interest rate used to accrete the net investment. This differs from a sales-type lease where selling profit is recognized at commencement. A direct financing lease arises when the lease meets one of the first four classification criteria AND the lessor has a third-party residual value guarantee or the lessee has a purchase option it is reasonably certain to exercise.',
    reference: 'ASC 842-30-25-7 through 10',
  },
  {
    id: 'far-d19-024',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-segment',
    topic: 'Segment Reporting',
    subtopic: 'CODM and Segment Identification',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 280, operating segments are identified based on:',
    options: [
      'Legal entity structure',
      'The internal reports regularly reviewed by the chief operating decision maker (CODM) for allocating resources and assessing performance',
      'Product lines as reported to customers',
      'Geographic locations only',
    ],
    correctAnswer: 1,
    explanation: 'ASC 280-10-50-1 uses a management approach to segment identification. Operating segments are components of an entity: (1) that engage in business activities from which revenues and expenses are incurred, (2) whose operating results are regularly reviewed by the CODM for resource allocation and performance assessment, and (3) for which discrete financial information is available. The CODM is a function, not a title — it may be the CEO, COO, or a group of executives. This approach aligns external reporting with how management actually views and manages the business.',
    reference: 'ASC 280-10-50-1',
  },
  {
    id: 'far-d19-025',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Day 1 Gain or Loss',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An entity enters into a derivative contract and determines that the transaction price differs from the fair value calculated using a model with significant unobservable inputs (Level 3). Under ASC 820, the entity should:',
    options: [
      'Recognize the Day 1 gain or loss in net income immediately',
      'Defer the Day 1 gain or loss and recognize it only when the valuation inputs become observable, the instrument is settled, or otherwise can be validated',
      'Record the instrument at the model price',
      'Disclose the difference but take no action',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 820-10-30-3 and 4, a Day 1 gain or loss arises when the transaction price differs from fair value at inception. If fair value is based on Level 1 or Level 2 inputs (observable), the difference is recognized immediately. However, if fair value is based on Level 3 inputs (unobservable), the instrument is initially measured at the transaction price, and the Day 1 gain or loss is deferred. It is subsequently recognized when the valuation can be corroborated by observable market data, or as the inputs become observable, or upon settlement. This prevents premature recognition of model-dependent profits.',
    reference: 'ASC 820-10-30-3 through 4',
  },
];
