// FAR Depth Questions - Batch 14
// Focus: FAR-III (Select Transactions)
// Topics: Additional coverage — Business Combinations, Consolidation, Foreign Currency, EPS, Fair Value, Derivatives, Misc.
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const FAR_QUESTIONS_DEPTH_14: Question[] = [
  {
    id: 'far-d14-001',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-business-combinations',
    topic: 'Business Combinations',
    subtopic: 'Measurement Period Adjustments',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 805, measurement period adjustments to the provisional amounts recognized in a business combination can be made for up to:',
    options: [
      'Six months from the acquisition date',
      'One year from the acquisition date, upon obtaining new information about facts and circumstances that existed at the acquisition date',
      'Two years from the acquisition date',
      'Until the next annual audit is completed',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 805-10-25-17, the measurement period is the period after the acquisition date during which the acquirer may adjust the provisional amounts recognized. This period ends as soon as the acquirer receives the needed information or learns that more information is not obtainable, but cannot exceed ONE YEAR from the acquisition date. Adjustments reflect new information about FACTS AND CIRCUMSTANCES that EXISTED at the acquisition date (not subsequent events). Measurement period adjustments are recognized retrospectively — comparative period financial statements are revised as if the adjustments had been recognized at the acquisition date. After ASU 2015-16, measurement period adjustments are recognized in the reporting period determined, with catch-up depreciation/amortization.',
    reference: 'ASC 805-10-25-17; ASU 2015-16',
  },
  {
    id: 'far-d14-002',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-business-combinations',
    topic: 'Business Combinations',
    subtopic: 'Business vs. Asset Acquisition',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASU 2017-01, a set of activities and assets is NOT a business if:',
    options: [
      'It includes employees',
      'Substantially all of the fair value of the gross assets acquired is concentrated in a single identifiable asset or a group of similar identifiable assets (the "screen" test is met)',
      'It generates revenue',
      'It has multiple components',
    ],
    correctAnswer: 1,
    explanation: 'Under ASU 2017-01 (ASC 805-10-55-5A), a simplified "screen" test was introduced: If substantially all of the fair value of the GROSS ASSETS acquired is concentrated in a single identifiable asset (or group of similar assets), the set is NOT a business — it is treated as an ASSET ACQUISITION. The screen test is optional; if not applied (or not met), a more detailed framework analysis is used that considers whether the set has inputs AND substantive processes that contribute to the ability to create outputs. The distinction matters because asset acquisitions: (1) allocate costs (including transaction costs) to individual assets, (2) do NOT recognize goodwill (any premium is allocated), and (3) do NOT record deferred taxes on initial differences.',
    reference: 'ASU 2017-01; ASC 805-10-55-5A',
  },
  {
    id: 'far-d14-003',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-consolidation',
    topic: 'Consolidation',
    subtopic: 'Elimination Entries — Investment Account',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In the consolidation worksheet for the year of acquisition, what is the purpose of the basic elimination entry?',
    options: [
      'To adjust for intercompany sales',
      'To eliminate the parent\'s investment account against the subsidiary\'s equity accounts and recognize any differential (goodwill or gain on bargain purchase)',
      'To eliminate the parent\'s dividend income',
      'To eliminate the subsidiary\'s revenue',
    ],
    correctAnswer: 1,
    explanation: 'The basic elimination entry in a consolidation eliminates the PARENT\'S INVESTMENT account against the SUBSIDIARY\'S EQUITY accounts (common stock, APIC, retained earnings) and recognizes any differences. If the parent paid MORE than book value: the excess is allocated to identifiable assets at fair value (e.g., land, equipment, intangibles) and any remaining excess is goodwill. If the parent paid LESS than fair value of net assets: a bargain purchase gain is recognized. A typical entry: Debit Common Stock (Sub), Debit APIC (Sub), Debit Retained Earnings (Sub), Debit FV adjustments & Goodwill, Credit Investment in Subsidiary. NCI is credited for the NCI\'s share. This entry is on the WORKSHEET only — it does not appear in either entity\'s books.',
    reference: 'ASC 810-10-45-1',
  },
  {
    id: 'far-d14-004',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Foreign Currency Transactions — Two-Transaction Method',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A U.S. company sells goods to a Canadian customer for 500,000 CAD on October 1 when the exchange rate is $0.80 USD/CAD. Payment is received December 31 when the rate is $0.82 USD/CAD. The transaction gain recognized is:',
    options: [
      '$10,000 (500,000 × ($0.82 − $0.80))',
      '$0 — the sale was in CAD so no gain exists',
      '$410,000',
      '$500,000',
    ],
    correctAnswer: 0,
    explanation: 'Under ASC 830-20 (two-transaction method): October 1 (sale date): Record A/R and Sales at spot rate: 500,000 × $0.80 = $400,000. December 31 (settlement date): A/R is remeasured at the current rate: 500,000 × $0.82 = $410,000. Cash received = $410,000. Transaction GAIN = $410,000 − $400,000 = $10,000. This gain is recognized in net income in the period of remeasurement/settlement. The two-transaction approach treats the sale as one transaction (recorded at the rate on the sale date) and the foreign exchange effect as a SEPARATE transaction (gain/loss from exchange rate movements). U.S. GAAP requires the two-transaction method — the one-transaction method is not permitted.',
    reference: 'ASC 830-20',
  },
  {
    id: 'far-d14-005',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-eps',
    topic: 'Earnings Per Share',
    subtopic: 'If-Converted Method — Preferred Stock',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has 200,000 common shares, net income of $800,000, and 10,000 shares of 8% convertible preferred stock ($100 par). Each preferred share converts to 5 common shares. The diluted EPS using the if-converted method is:',
    options: [
      '$3.20 (Numerator: $800,000 / Denominator: 200,000 + 50,000 = 250,000)',
      '$3.50',
      '$4.00',
      '$2.80',
    ],
    correctAnswer: 0,
    explanation: 'Under the if-converted method (ASC 260-10-45-40): Step 1 — Basic EPS: Numerator = $800,000 − preferred dividends ($1,000,000 × 8% = $80,000) = $720,000. Denominator = 200,000 shares. Basic EPS = $720,000 / 200,000 = $3.60. Step 2 — Diluted EPS (if-converted): Assume conversion at beginning of period. Numerator: ADD BACK preferred dividends → $800,000 (full net income, since preferred dividends would not be paid if converted). Denominator: Add converted shares → 200,000 + (10,000 × 5) = 250,000. Diluted EPS = $800,000 / 250,000 = $3.20. Since $3.20 < $3.60 (basic EPS), the conversion IS dilutive and is included. If diluted EPS exceeded basic EPS, the conversion would be antidilutive and excluded.',
    reference: 'ASC 260-10-45-40',
  },
  {
    id: 'far-d14-006',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-consolidation',
    topic: 'Consolidation',
    subtopic: 'Intercompany Bond Holdings',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Subsidiary issues $1,000,000 bonds to external parties at par. Parent later purchases the bonds on the open market for $960,000. In the consolidation, this results in:',
    options: [
      'No adjustment needed',
      'A constructive retirement gain of $40,000 recognized in consolidated net income',
      'An increase in bonds payable of $40,000',
      'A loss of $40,000',
    ],
    correctAnswer: 1,
    explanation: 'When a parent (or affiliate) acquires the outstanding bonds of a subsidiary from an external party, from the CONSOLIDATED entity\'s perspective, the bonds have been effectively retired (constructive retirement). The subsidiary\'s bonds payable ($1,000,000) and the parent\'s investment in bonds ($960,000) are both eliminated in consolidation. The difference represents a CONSTRUCTIVE GAIN of $40,000 ($1,000,000 − $960,000), recognized in consolidated net income. This gain appears ONLY in the consolidated statements — neither the parent nor subsidiary individually recognize the gain. In the worksheet, the elimination entry debits Bonds Payable $1,000,000, credits Investment in Bonds $960,000, and credits Gain on Constructive Retirement $40,000.',
    reference: 'ASC 810-10-45-1',
  },
  {
    id: 'far-d14-007',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Principal vs. Most Advantageous Market',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 820, when the principal market and the most advantageous market differ, the entity should measure fair value using the price in the:',
    options: [
      'Most advantageous market (highest price)',
      'Principal market (the market with the greatest volume and level of activity for the asset or liability)',
      'The market selected by management',
      'The market with the lowest transaction costs',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 820-10-35-5, an entity must measure fair value using the price in the PRINCIPAL MARKET — the market with the greatest volume and level of activity for the asset or liability. If no principal market exists, the entity uses the MOST ADVANTAGEOUS market (the market that maximizes the amount received for an asset or minimizes the amount paid for a liability, after considering transaction costs). Transaction costs are used to identify the most advantageous market but do NOT adjust the fair value measurement itself. Transport costs are included if location is a characteristic of the asset. The entity does not need to exhaustively search all markets — it is presumed that the market where it normally transacts is the principal market.',
    reference: 'ASC 820-10-35-5',
  },
  {
    id: 'far-d14-008',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-business-combinations',
    topic: 'Business Combinations',
    subtopic: 'Assembled Workforce',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'In a business combination, the value of the acquiree\'s assembled workforce is:',
    options: [
      'Recognized as a separate intangible asset',
      'Included in goodwill and NOT recognized as a separate intangible, because an assembled workforce is not an identifiable asset',
      'Expensed immediately',
      'Classified as a contingent liability',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 805-20-55-6, an assembled workforce is NOT identifiable because it does not meet EITHER the contractual-legal criterion or the separability criterion (employees cannot be "sold, transferred, or licensed" separately). Therefore, the value of an assembled workforce is subsumed within GOODWILL. While the acquiree\'s employees may have significant value, they are not separable from the entity and do not arise from contractual or legal rights in the same way as customer contracts, patents, or trademarks. Noncompete agreements, however, ARE recognized separately because they arise from contractual rights.',
    reference: 'ASC 805-20-55-6',
  },
  {
    id: 'far-d14-009',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Remeasurement — Nonmonetary Assets',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the temporal (remeasurement) method, which of the following items is translated at HISTORICAL exchange rates?',
    options: [
      'Accounts payable',
      'Inventory carried at cost',
      'Cash and cash equivalents',
      'Accounts receivable',
    ],
    correctAnswer: 1,
    explanation: 'Under the temporal (remeasurement) method (ASC 830-10-55): MONETARY items (cash, receivables, payables, debt) → CURRENT rate. NONMONETARY items carried at HISTORICAL COST (inventories at cost, PP&E, prepaid expenses, equity investments at cost) → HISTORICAL rate. Nonmonetary items carried at fair value (inventories written down to market) → rate at the date FV was determined. Revenues and expenses → rates at date of transaction (or weighted-average as practical expedient), EXCEPT depreciation and COGS, which use historical rates consistent with the related assets. Inventory carried at COST uses the historical rate — the rate in effect when the inventory was purchased. Remeasurement gains/losses are recognized in net income.',
    reference: 'ASC 830-10-55',
  },
  {
    id: 'far-d14-010',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-consolidation',
    topic: 'Consolidation',
    subtopic: 'Midyear Acquisition — Partial Year Income',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Parent acquires 100% of Subsidiary on April 1. Subsidiary had net income of $600,000 for the full year (earned evenly). What amount of Subsidiary\'s income is included in the consolidated income statement?',
    options: [
      '$600,000 for the full year',
      '$450,000 ($600,000 × 9/12 months from April 1 through December 31)',
      '$150,000',
      '$300,000',
    ],
    correctAnswer: 1,
    explanation: 'When a subsidiary is acquired midyear, the consolidated income statement includes the subsidiary\'s revenues and expenses ONLY FROM THE ACQUISITION DATE forward. Since the acquisition occurred on April 1, and net income is earned evenly: Income included = $600,000 × 9/12 = $450,000 (April through December). The pre-acquisition income ($150,000, January through March) is NOT included in consolidated income. The subsidiary\'s pre-acquisition equity (including pre-acquisition income) is eliminated against the investment account in the basic elimination entry. Pro forma disclosures may present what combined revenue and earnings would have been if the acquisition had occurred at the beginning of the year.',
    reference: 'ASC 805-10-50-2',
  },
  {
    id: 'far-d14-011',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Comprehensive Income Presentation — Hedges',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASU 2017-12, for a qualifying cash flow hedge, the ENTIRE change in fair value of the hedging instrument is initially recorded in:',
    options: [
      'Net income',
      'OCI (both the effective and excluded components, with subsequent reclassification to net income when the hedged item affects earnings)',
      'Goodwill',
      'The hedged item\'s carrying amount',
    ],
    correctAnswer: 1,
    explanation: 'ASU 2017-12 simplified hedge accounting by allowing entities to record the ENTIRE change in fair value of the hedging instrument in OCI for cash flow hedges. Previously (pre-ASU 2017-12), the ineffective portion had to be measured and immediately recognized in earnings. Under the new guidance, entities may elect to: (1) Record the entire change (effective + ineffective) in OCI, then reclassify to earnings when the hedged item affects earnings. (2) For excluded components (e.g., time value of options, forward points), either amortize systematically to earnings or recognize changes in fair value in earnings. This reduces earnings volatility and simplifies effectiveness testing. Hedge ineffectiveness is still disclosed but does not require separate income statement recognition.',
    reference: 'ASU 2017-12',
  },
  {
    id: 'far-d14-012',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-eps',
    topic: 'Earnings Per Share',
    subtopic: 'EPS Disclosure Requirements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 260, which entities are required to present earnings per share on the face of the income statement?',
    options: [
      'All entities',
      'Only public entities (those with publicly traded common stock or potential common stock)',
      'Only entities with more than $100 million in assets',
      'Only entities listed on the NYSE',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 260-10-15-2, EPS presentation is required ONLY for public entities — those with common stock or potential common stock (convertible securities, options, warrants) traded in a public market (domestic or foreign exchanges, OTC markets including OTCBB and local/regional markets). Private companies are NOT required to present EPS but may voluntarily do so. If EPS is presented voluntarily, it must follow all ASC 260 requirements. Public entities must present both basic and diluted EPS on the face of the income statement for: (1) Income from continuing operations, and (2) Net income. EPS for discontinued operations may be presented on the face or in the notes.',
    reference: 'ASC 260-10-15-2',
  },
  {
    id: 'far-d14-013',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-accounting-changes',
    topic: 'Accounting Changes and Error Corrections',
    subtopic: 'Impracticability Exception',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 250, if retrospective application of a change in accounting principle is impracticable because the entity cannot determine the cumulative effect at the beginning of the earliest period presented, the entity:',
    options: [
      'Must not make the change',
      'Applies the new principle prospectively from the earliest date practicable',
      'Recognizes the change as an error correction',
      'Discloses the change but makes no adjustments',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 250-10-45-9, retrospective application is impracticable if any of the following exist: (1) The entity cannot determine the cumulative effect despite making every reasonable effort. (2) Assumptions about management\'s intent in a prior period are required. (3) Significant estimates are required and it is impossible to objectively distinguish whether the information was available at the time. When retrospective application is impracticable for ALL prior periods, the entity applies the new principle PROSPECTIVELY from the earliest date practicable. This may mean applying the change as of the beginning of the current period or an earlier period for which data is available. The entity discloses why retrospective application was impracticable.',
    reference: 'ASC 250-10-45-9',
  },
  {
    id: 'far-d14-014',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-consolidation',
    topic: 'Consolidation',
    subtopic: 'NCI Measurement at Acquisition',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 805, at the acquisition date, the noncontrolling interest (NCI) in the acquiree can be measured at:',
    options: [
      'Only the NCI\'s proportionate share of the acquiree\'s identifiable net assets',
      'EITHER fair value of the NCI OR the NCI\'s proportionate share of the acquiree\'s identifiable net assets (an accounting policy election made on a transaction-by-transaction basis)',
      'Always at fair value',
      'The NCI\'s proportionate share of the acquiree\'s book value',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 805-20-30-2, NCI can be measured using TWO methods (accounting policy election made per transaction): (1) FULL GOODWILL method: NCI at FAIR VALUE → goodwill reflects both the parent\'s and NCI\'s shares. (2) PARTIAL GOODWILL method: NCI at proportionate share of identifiable net assets at fair value → goodwill reflects ONLY the parent\'s excess. Example: Subsidiary FV net assets = $1M, NCI = 20%. Method 1: NCI = FV (e.g., $220,000 — may include premium). Goodwill includes full entity premium. Method 2: NCI = 20% × $1M = $200,000. Goodwill reflects only parent\'s excess. The choice affects the goodwill amount and subsequent impairment testing.',
    reference: 'ASC 805-20-30-2',
  },
  {
    id: 'far-d14-015',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Translation Adjustment Reclassification',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The cumulative translation adjustment (CTA) accumulated in OCI for a foreign subsidiary is reclassified to net income when:',
    options: [
      'At the end of each fiscal year',
      'Upon sale or upon substantially complete liquidation of the investment in the foreign entity',
      'When the exchange rate returns to the original rate',
      'Whenever the CTA balance exceeds 10% of total equity',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-30-40-1, the CTA accumulated in AOCI is reclassified (recycled) to net income ONLY upon: (1) SALE of the investment in the foreign entity (total or partial sale resulting in loss of controlling financial interest). (2) SUBSTANTIALLY COMPLETE LIQUIDATION of the investment. (3) Loss of significant influence over a foreign investee (equity method). A partial sale that does NOT result in loss of control results in a pro rata CTA reclassification. Substantially complete liquidation means the parent has received substantially all of the net assets of the subsidiary. The CTA remains in AOCI during ongoing ownership — it is NOT reclassified based on time, exchange rate movements, or balance thresholds.',
    reference: 'ASC 830-30-40-1',
  },
  {
    id: 'far-d14-016',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-business-combinations',
    topic: 'Business Combinations',
    subtopic: 'Acquisition Method — Consideration Transferred',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 805, the consideration transferred in a business combination is measured at:',
    options: [
      'Book value of the assets given',
      'Fair value at the acquisition date, including cash, assets transferred, liabilities incurred, and equity interests issued',
      'Historical cost',
      'The acquiree\'s book value of net assets',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 805-30-30-7, the consideration transferred in a business combination is measured at FAIR VALUE at the acquisition date. Consideration includes: (1) Cash or cash equivalents. (2) Other assets transferred (at fair value). (3) Liabilities incurred by the acquirer to former owners of the acquiree. (4) Equity interests issued by the acquirer (at fair value). (5) Contingent consideration (at fair value). If equity interests are issued, the fair value is typically based on the quoted market price of the acquirer\'s shares. Consideration does NOT include pre-existing relationships, employee arrangements that are compensation for future services, or acquisition-related costs (those are expensed).',
    reference: 'ASC 805-30-30-7',
  },
  {
    id: 'far-d14-017',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Hedge Documentation Requirements',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 815, formal hedge documentation must be prepared:',
    options: [
      'Within 30 days of entering the hedge',
      'At inception of the hedging relationship (or shortly thereafter per ASU 2017-12), including identification of the hedging instrument, hedged item/transaction, risk being hedged, and effectiveness assessment method',
      'At the end of the reporting period',
      'Only when hedge ineffectiveness occurs',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-20-25-3, hedge accounting requires FORMAL DOCUMENTATION at inception of the hedging relationship. The documentation must include: (1) The hedging RELATIONSHIP (the entity\'s risk management objective and strategy). (2) The hedging INSTRUMENT (including the specific derivative). (3) The hedged ITEM or transaction (the specific asset, liability, firm commitment, or forecasted transaction). (4) The nature of the risk being hedged. (5) How the entity will assess hedge EFFECTIVENESS (including the method and frequency). (6) For cash flow hedges of forecasted transactions: the probability and timing. ASU 2017-12 allows a "reasonable period" after designation to complete documentation but retains the inception requirement for designation.',
    reference: 'ASC 815-20-25-3; ASU 2017-12',
  },
  {
    id: 'far-d14-018',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-consolidation',
    topic: 'Consolidation',
    subtopic: 'Intercompany Inventory — Subsequent Year',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In Year 1, Parent sold inventory to Subsidiary for $150,000 (cost of $100,000). All inventory remained unsold at Year 1 end but was sold externally by Subsidiary in Year 2. What consolidation adjustment is needed in Year 2?',
    options: [
      'No adjustment needed in Year 2',
      'Debit Beginning Retained Earnings $50,000, Credit COGS $50,000 to realize the previously deferred intercompany profit',
      'Debit COGS $50,000, Credit Inventory $50,000',
      'Debit Sales $150,000, Credit COGS $100,000, Credit Inventory $50,000',
    ],
    correctAnswer: 1,
    explanation: 'In Year 1, unrealized intercompany profit of $50,000 ($150,000 − $100,000) was eliminated: Debit Sales $150,000, Credit COGS $100,000, Credit Inventory $50,000. In Year 2, the beginning retained earnings of the consolidated entity still contain the Year 1 elimination (which reduced consolidated income by $50,000). Since the inventory was sold to external parties in Year 2, the profit is NOW REALIZED. Entry: Debit Beginning Retained Earnings $50,000 (to reverse the prior-year deferral), Credit COGS $50,000 (to reduce Year 2 COGS to the original $100,000 cost). This ensures that over two years, total consolidated gross profit = $50,000 (external selling price − $100,000 original cost).',
    reference: 'ASC 810-10-45-1',
  },
  {
    id: 'far-d14-019',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-segment',
    topic: 'Segment Reporting',
    subtopic: 'Entity-Wide Disclosures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 280, entity-wide disclosures required regardless of the number of reportable segments include information about:',
    options: [
      'Only revenue by segment',
      'Products and services, geographic areas (revenue and long-lived assets), and major customers (≥ 10% of revenue)',
      'Only major customers',
      'Employee headcount by region',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 280-10-50-38 through 50-42, entity-wide disclosures are required even if the entity has ONLY ONE reportable segment. These include: (1) Products and services: Revenue from external customers for each product/service (or group). (2) Geographic areas: Revenue from external customers attributed to the entity\'s country of domicile vs. all foreign countries (with individual country disclosure if material). Long-lived assets by domicile country and foreign countries. (3) Major customers: If revenue from any single external customer is ≥ 10% of total revenue, disclose that fact plus the total revenue from each such customer and the segment(s) reporting that revenue. The customer\'s identity need not be disclosed.',
    reference: 'ASC 280-10-50-38; ASC 280-10-50-42',
  },
  {
    id: 'far-d14-020',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-accounting-changes',
    topic: 'Accounting Changes and Error Corrections',
    subtopic: 'Change in Principle Inseparable from Estimate',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 250, when a change in accounting principle is inseparable from a change in estimate (e.g., switching from the deferral method to straight-line for depreciation), the change is reported:',
    options: [
      'Retrospectively as a change in principle',
      'Prospectively as a change in estimate — the prospective treatment takes precedence',
      'As a prior period adjustment',
      'As an extraordinary item',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 250-10-45-18, when a change in accounting principle is INSEPARABLE from a change in accounting estimate (such as changing a depreciation method, which reflects a change in both the pattern of future benefit consumption (estimate) and the method used (principle)), the change is accounted for PROSPECTIVELY as a change in estimate. The prospective treatment takes precedence because the change inherently involves revised estimates about future events. Example: Changing from double-declining-balance to straight-line depreciation midway through an asset\'s life. The undepreciated balance is allocated over the remaining life using the new method, with no restatement of prior periods.',
    reference: 'ASC 250-10-45-18',
  },
  {
    id: 'far-d14-021',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-consolidation',
    topic: 'Consolidation',
    subtopic: 'Consolidation Scope — Voting Interest Model',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under the voting-interest model (ASC 810-10-15), a parent generally consolidates a subsidiary when it owns:',
    options: [
      'Any ownership percentage',
      'A majority voting interest (> 50% of outstanding voting shares)',
      'Exactly 50%',
      'At least 20%',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 810-10-15-8 (voting-interest model), a parent entity consolidates a subsidiary when it has a controlling financial interest, which is generally evidenced by ownership of a MAJORITY VOTING INTEREST (more than 50% of outstanding voting shares). This presumption can be overcome in rare cases — for example, when the subsidiary is in legal reorganization, in bankruptcy, or when a foreign government severely restricts the parent\'s control. Conversely, consolidation may be required with <50% ownership if the parent has effective control through other means (e.g., contractual arrangements). The VIE model (ASC 810-10-15-14) applies to entities where the equity holders do not have sufficient equity at risk or lack the characteristics of a controlling financial interest.',
    reference: 'ASC 810-10-15-8',
  },
  {
    id: 'far-d14-022',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-business-combinations',
    topic: 'Business Combinations',
    subtopic: 'Reverse Acquisition',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a reverse acquisition (where the legal acquirer is the accounting acquiree), under ASC 805, the financial statements after the combination are issued under the name of the:',
    options: [
      'Accounting acquirer (legal acquiree)',
      'Legal acquirer (accounting acquiree), but the financial statements reflect the continuation of the accounting acquirer\'s (legal acquiree\'s) financial statements',
      'Both entities equally',
      'A newly formed entity',
    ],
    correctAnswer: 1,
    explanation: 'In a reverse acquisition, the legal acquirer (the entity that issues shares) is determined to be the ACCOUNTING ACQUIREE, while the legal acquiree (the entity whose former shareholders control the combined entity) is the ACCOUNTING ACQUIRER. Under ASC 805-40-45-2, the post-combination financial statements are issued under the name of the LEGAL PARENT (legal acquirer/accounting acquiree), but they are a CONTINUATION of the accounting acquirer\'s (legal acquiree\'s) financial statements. The accounting acquirer\'s assets and liabilities are at carrying value; the legal acquirer\'s assets and liabilities are measured at fair value. Reverse acquisitions are common in "reverse mergers" where a private company merges into a public shell company.',
    reference: 'ASC 805-40-45-2',
  },
  {
    id: 'far-d14-023',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-fair-value',
    topic: 'Fair Value Measurement',
    subtopic: 'Unit of Account vs. Level of Aggregation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 820, an entity holds a large block of shares (10% of a publicly traded company\'s outstanding stock). A "blockage factor" that reduces the per-share price because of the block size:',
    options: [
      'Is applied to adjust the Level 1 price',
      'Is NOT applied — the fair value is the quoted price × number of shares, with no blockage discount for Level 1 measurements',
      'Is required for all equity investments',
      'Is applied only to Level 3 measurements',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 820-10-35-36B, a BLOCKAGE FACTOR is NOT applied to Level 1 fair value measurements. When a quoted price exists in an active market (Level 1), fair value is calculated as: Quoted price per unit × quantity held. Even if the block is large relative to normal trading volume and selling the entire block would depress the price, no discount is applied. This is because the "unit of account" is the individual share (not the block), and the Level 1 price reflects the per-share value. The entity may have a different unit of account for financial reporting purposes (e.g., the investment as a whole), but the fair value measurement must use the unadjusted Level 1 price per unit multiplied by quantity.',
    reference: 'ASC 820-10-35-36B',
  },
  {
    id: 'far-d14-024',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-subsequent-events',
    topic: 'Subsequent Events',
    subtopic: 'Type II — Nonrecognized Events',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A natural disaster occurs after the balance sheet date but before the financial statements are issued, destroying a significant production facility. Under ASC 855, this is classified as:',
    options: [
      'Type I (recognized) — the financial statements are adjusted',
      'Type II (nonrecognized) — the event is disclosed in the notes but the financial statements are NOT adjusted',
      'Not a subsequent event',
      'An error correction',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 855-10-25-3, a Type II (nonrecognized/nonadjusting) subsequent event reflects conditions that arose AFTER the balance sheet date. A natural disaster occurring after year-end is a new event — the condition (the disaster) did not exist at the balance sheet date. The financial statements are NOT adjusted, but DISCLOSURE is required if the event is significant enough that without disclosure, the financial statements would be misleading. Disclosure includes: the nature of the event and an estimate of the financial effect (or a statement that an estimate cannot be made). Compare this to Type I events, which provide evidence of conditions existing AT the balance sheet date (e.g., settlement of litigation where the loss was probable at year-end).',
    reference: 'ASC 855-10-25-3',
  },
  {
    id: 'far-d14-025',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-eps',
    topic: 'Earnings Per Share',
    subtopic: 'EPS for Discontinued Operations',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 260, when a company reports discontinued operations, EPS must be presented for:',
    options: [
      'Only income from continuing operations',
      'Income from continuing operations AND net income (EPS for discontinued operations may be on the face of the statement or in the notes)',
      'Only net income',
      'Only discontinued operations',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 260-10-45-3, an entity that reports a discontinued operation must present basic and diluted EPS for: (1) Income from continuing operations (REQUIRED on the face of the income statement). (2) Net income (REQUIRED on the face of the income statement). Per share data for discontinued operations may be presented either on the face of the income statement OR in the notes to the financial statements. The entity has flexibility in placement of the discontinued operations EPS, but the two amounts (continuing operations EPS and net income EPS) must appear on the face. The same weighted-average share count and diluted share count is used for all EPS calculations in a given period.',
    reference: 'ASC 260-10-45-3',
  },
];
