// FAR Depth Questions - Batch 6
// Focus: FAR-II (Select Financial Statement Accounts) continued
// Topics: Revenue Recognition advanced, Leases lessor, PP&E impairment, Equity compensation, Income taxes
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const FAR_QUESTIONS_DEPTH_6: Question[] = [
  {
    id: 'far-d6-001',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Contract Costs',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 340-40, incremental costs of obtaining a contract (such as sales commissions) should be:',
    options: [
      'Expensed immediately in all cases',
      'Capitalized as an asset if the entity expects to recover them, and amortized consistent with the transfer of goods or services',
      'Recorded as a reduction to revenue',
      'Included in cost of goods sold',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 340-40-25-1, incremental costs of obtaining a contract are capitalized if the entity expects to recover those costs. Incremental costs are those that would not have been incurred if the contract had not been obtained (e.g., sales commissions). The capitalized asset is amortized on a systematic basis consistent with the pattern of transfer of goods or services. A practical expedient allows immediate expensing if the amortization period would be one year or less. Costs to fulfill a contract are capitalized under ASC 340-40-25-5 if they relate directly to the contract, generate or enhance resources, and are expected to be recovered.',
    reference: 'ASC 340-40-25-1',
  },
  {
    id: 'far-d6-002',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Over-Time Recognition',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A construction company has a $10,000,000 fixed-price contract. At year end, costs incurred to date are $3,600,000 and estimated total costs are $8,000,000. Using the input method (cost-to-cost), how much revenue is recognized to date?',
    options: [
      '$3,600,000',
      '$4,500,000',
      '$10,000,000',
      '$6,400,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 606-10-55-17 through 55-21, revenue recognized over time using the cost-to-cost input method is calculated as: Percentage complete = costs incurred to date ÷ estimated total costs = $3,600,000 ÷ $8,000,000 = 45%. Revenue to date = 45% × $10,000,000 = $4,500,000. Gross profit to date = $4,500,000 - $3,600,000 = $900,000. The input method measures progress based on the entity\'s efforts or inputs to the satisfaction of a performance obligation relative to the total expected inputs.',
    reference: 'ASC 606-10-55-17',
  },
  {
    id: 'far-d6-003',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Anticipated Contract Loss',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A company has a $5,000,000 contract recognized over time. Costs to date are $2,000,000 and estimated remaining costs are $4,500,000 (total estimated costs of $6,500,000). What is the total loss recognized in the current period?',
    options: [
      '$0 — losses are only recognized upon contract completion',
      '$500,000 — the loss to date based on percentage of completion',
      '$1,500,000 — the entire expected contract loss must be recognized immediately',
      '$1,000,000',
    ],
    correctAnswer: 2,
    explanation: 'Under ASC 606-10-25-2 (and legacy ASC 605-35-25-45), when a contract is expected to result in a loss, the ENTIRE anticipated loss must be recognized immediately in the period it becomes evident, regardless of the percentage of completion. Expected loss = total estimated costs ($6,500,000) - contract price ($5,000,000) = $1,500,000. The loss is recognized as an increase to cost of revenue (or via a provision for estimated losses). This conservative approach reflects the loss contingency provisions and prevents deferral of known losses.',
    reference: 'ASC 606-10-25-2',
  },
  {
    id: 'far-d6-004',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Principal vs. Agent',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An online marketplace facilitates sales between third-party sellers and customers, collecting 15% commission. The marketplace does not take title to goods. Revenue should be recognized by the marketplace at:',
    options: [
      'The gross amount of sales (full selling price)',
      'The net amount (the 15% commission), because the marketplace is acting as an agent',
      'The cost of goods sold',
      'No revenue — only the sellers recognize revenue',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 606-10-55-36 through 55-40, an entity is a principal if it controls the good or service before it is transferred to the customer; otherwise it is an agent. Indicators of agent status include: (1) another party is primarily responsible for fulfilling the promise, (2) the entity does not have inventory risk, (3) the entity does not have discretion in establishing the price. A marketplace that does not take title, bears no inventory risk, and merely facilitates transactions is an agent. Agents report revenue at the net amount (commission or fee earned).',
    reference: 'ASC 606-10-55-36',
  },
  {
    id: 'far-d6-005',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lessor — Sales-Type Lease',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A manufacturer-lessor leases equipment (cost $400,000, fair value $600,000) under a sales-type lease with a 5-year term and annual payments of $142,000. The implicit rate is 6%. What profit does the lessor recognize at lease commencement?',
    options: [
      '$0 — profit is recognized over the lease term',
      'Selling profit of $200,000 (fair value minus cost) at commencement',
      '$600,000 sales revenue',
      'Profit of $110,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-30-25-1, for a sales-type lease, the lessor recognizes at commencement: (1) a net investment in the lease (PV of lease payments + PV of unguaranteed residual value), (2) derecognizes the underlying asset, (3) recognizes selling profit or loss as the difference between the asset\'s fair value and its carrying amount. Selling profit = $600,000 (fair value) - $400,000 (cost) = $200,000. The lessor subsequently recognizes interest income over the lease term on the net investment. Initial direct costs are expensed if there is a selling profit.',
    reference: 'ASC 842-30-25-1',
  },
  {
    id: 'far-d6-006',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Sale-Leaseback',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A company sells a building with a carrying amount of $2,000,000 for $3,000,000 and immediately leases it back under a 3-year operating lease (the building has a 30-year remaining life). The transfer qualifies as a sale under ASC 606. What gain is recognized?',
    options: [
      '$1,000,000 recognized immediately',
      '$0 — gain is deferred over the lease term',
      '$100,000 — only the portion attributable to the off-market terms is recognized',
      '$1,000,000, but only if the leaseback is at fair market rent; otherwise the gain is adjusted for any above/below-market terms',
    ],
    correctAnswer: 3,
    explanation: 'Under ASC 842-40-25, if the transfer of the asset qualifies as a sale under ASC 606, the seller-lessee recognizes the transaction as a sale and leaseback. The gain on sale ($3,000,000 - $2,000,000 = $1,000,000) is recognized only to the extent it relates to the rights transferred. If the sale price or lease terms are not at fair value, adjustments are made: above-market sale price → portion treated as additional financing (liability); below-market lease payments → portion treated as prepaid rent. If everything is at fair value, the full $1,000,000 gain is recognized.',
    reference: 'ASC 842-40-25',
  },
  {
    id: 'far-d6-007',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-ppe',
    topic: 'Property, Plant, and Equipment',
    subtopic: 'Impairment of Long-Lived Assets',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 360-10, a long-lived asset held for use is tested for impairment when events suggest carrying amount may not be recoverable. The impairment test involves:',
    options: [
      'Comparing carrying amount to fair value directly',
      'First, a recoverability test comparing carrying amount to undiscounted expected future cash flows; if carrying amount exceeds undiscounted cash flows, then measuring the impairment as the excess of carrying amount over fair value',
      'Comparing carrying amount to replacement cost',
      'Comparing net book value to liquidation value',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 360-10-35-17, the impairment process for long-lived assets held for use is a two-step process: Step 1 (Recoverability test): Compare the carrying amount to the sum of undiscounted expected future net cash flows from the asset\'s use and eventual disposition. If carrying amount ≤ undiscounted cash flows, no impairment exists. Step 2 (Measurement): If carrying amount > undiscounted cash flows, the impairment loss equals carrying amount minus fair value. Note: this differs from goodwill impairment (ASC 350), which uses fair value directly without the recoverability screen.',
    reference: 'ASC 360-10-35-17',
  },
  {
    id: 'far-d6-008',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-ppe',
    topic: 'Property, Plant, and Equipment',
    subtopic: 'Nonmonetary Exchanges',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Company A exchanges equipment (cost $100,000, accumulated depreciation $60,000, fair value $50,000) for equipment from Company B. The exchange has commercial substance. What amount does Company A record for the new equipment?',
    options: [
      '$40,000 (book value of old equipment)',
      '$50,000 (fair value of old equipment given up)',
      '$100,000 (cost of old equipment)',
      '$60,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 845-10-30, nonmonetary exchanges with commercial substance are recorded at fair value. The new asset is recorded at the fair value of the asset given up (or received, if more clearly evident): $50,000. Company A recognizes a gain or loss on the exchange: Fair value given ($50,000) - Book value given ($100,000 - $60,000 = $40,000) = $10,000 gain. Entry: Dr New Equipment $50,000, Dr Accumulated Depreciation $60,000, Cr Old Equipment $100,000, Cr Gain $10,000. If the exchange lacks commercial substance, the new asset is recorded at book value (no gain recognized).',
    reference: 'ASC 845-10-30',
  },
  {
    id: 'far-d6-009',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Notes Receivable Impairment',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the CECL model, a bank holds a loan with an amortized cost of $500,000. Based on historical data, current conditions, and forecasts, the bank estimates lifetime expected credit losses of $25,000. The journal entry to record the allowance is:',
    options: [
      'Dr Bad Debt Expense $25,000, Cr Allowance for Credit Losses $25,000',
      'Dr Credit Loss Expense $25,000, Cr Allowance for Credit Losses $25,000',
      'Dr Notes Receivable $25,000, Cr Revenue $25,000',
      'No entry until the loss is confirmed',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 326-20, the CECL model requires recognition of lifetime expected credit losses at initial recognition (Day 1). The allowance is a contra-asset that reduces the net carrying amount. The entry: Dr Credit Loss Expense (or Provision for Credit Losses) $25,000, Cr Allowance for Credit Losses $25,000. The net carrying amount is $475,000 ($500,000 - $25,000). The allowance is reassessed each reporting period, with changes flowing through credit loss expense. The term "credit loss expense" is preferred under CECL over "bad debt expense."',
    reference: 'ASC 326-20-30',
  },
  {
    id: 'far-d6-010',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Pledging and Assignment',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'When receivables are pledged as collateral for a loan, the receivables:',
    options: [
      'Are removed from the balance sheet',
      'Remain on the pledgor\'s balance sheet with disclosure of the pledge in the notes',
      'Are transferred to the lender\'s balance sheet',
      'Are written off',
    ],
    correctAnswer: 1,
    explanation: 'When receivables are pledged (or assigned) as collateral for a loan, the borrower retains the receivables on its balance sheet because the transfer does not meet the criteria for a sale under ASC 860. The borrower records the loan proceeds as a liability. Disclosure of the pledge is required in the financial statement notes, including the carrying amount of receivables pledged and the terms of the borrowing arrangement. This differs from factoring without recourse, where the receivables are derecognized.',
    reference: 'ASC 860-30-25',
  },
  {
    id: 'far-d6-011',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-investments',
    topic: 'Investments',
    subtopic: 'Equity Securities Without Readily Determinable Fair Value',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 321, equity securities without a readily determinable fair value may be measured at:',
    options: [
      'Historical cost with no adjustments',
      'Cost minus impairment plus/minus observable price changes (measurement alternative)',
      'Fair value through OCI',
      'Net asset value of the investee',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 321-10-35-2, equity investments without readily determinable fair values may use the measurement alternative: cost minus impairment plus or minus changes resulting from observable price changes in orderly transactions for the identical or a similar investment of the same issuer. Impairment is assessed qualitatively each reporting period. If impairment exists, the investment is written down to fair value (the impairment loss is recognized in net income). This measurement alternative replaced the previous cost method under ASC 325.',
    reference: 'ASC 321-10-35-2',
  },
  {
    id: 'far-d6-012',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-investments',
    topic: 'Investments',
    subtopic: 'Equity Method — Excess Fair Value',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An investor purchases a 25% interest in Company B for $1,200,000 when B\'s net assets have a book value of $4,000,000. The excess is attributable to equipment with 10 years remaining life (fair value exceeds book value by $400,000) and goodwill. What is the annual equity method amortization adjustment?',
    options: [
      '$0 — no amortization is required under the equity method',
      '$10,000 (25% of $400,000 ÷ 10 years)',
      '$40,000',
      '$120,000',
    ],
    correctAnswer: 1,
    explanation: 'Purchase price: $1,200,000. Share of book value: 25% × $4,000,000 = $1,000,000. Excess: $200,000. Of this excess: 25% × $400,000 depreciable equipment excess = $100,000 allocated to equipment, amortized over 10 years = $10,000/year. Remaining excess: $200,000 - $100,000 = $100,000 allocated to goodwill (not amortized but reviewed for impairment). Each year, the investor reduces equity income by $10,000 and reduces the investment account by $10,000. This process is called "basis difference" amortization.',
    reference: 'ASC 323-10-35-13',
  },
  {
    id: 'far-d6-013',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-debt',
    topic: 'Long-Term Debt',
    subtopic: 'Convertible Bonds',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASU 2020-06 (ASC 470-20), a convertible bond that does not require cash settlement is accounted for as:',
    options: [
      'Bifurcated into debt and equity components',
      'A single liability measured at amortized cost (no longer bifurcated into debt and equity)',
      'Entirely as equity',
      'At fair value through net income',
    ],
    correctAnswer: 1,
    explanation: 'ASU 2020-06 simplified the accounting for convertible instruments by eliminating the beneficial conversion feature (BCF) model and the cash conversion feature model. Under the simplified guidance, most convertible debt instruments are accounted for as a single liability at amortized cost, unless they: (1) contain an embedded derivative that requires bifurcation, (2) are issued at a substantial premium, or (3) are in the scope of ASC 815 (derivatives). This means the conversion feature is no longer separately valued in equity, resulting in lower interest expense and higher reported debt.',
    reference: 'ASU 2020-06; ASC 470-20',
  },
  {
    id: 'far-d6-014',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-debt',
    topic: 'Long-Term Debt',
    subtopic: 'Troubled Debt Restructuring',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASU 2022-02 (effective for most entities in 2023), the concept of troubled debt restructuring (TDR):',
    options: [
      'Remains unchanged from previous GAAP',
      'Was eliminated — creditors now assess modifications under the general loan modification framework and apply CECL for credit losses',
      'Was expanded to cover more debt types',
      'Was eliminated for public entities only',
    ],
    correctAnswer: 1,
    explanation: 'ASU 2022-02 eliminated the accounting guidance for TDRs by creditors in ASC 310-40. Instead, creditors evaluate whether a modification to a borrower experiencing financial difficulty is a new loan or a continuation of the existing loan under the general loan modification framework (ASC 310-20). Credit losses are measured under the CECL model (ASC 326). Enhanced disclosures about modifications to borrowers experiencing financial difficulty are required, including the financial effect of the modifications and the performance of modified loans. This aligned the TDR guidance with the current expected credit loss model.',
    reference: 'ASU 2022-02; ASC 310-40',
  },
  {
    id: 'far-d6-015',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Stock Splits',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'When a company declares a 2-for-1 stock split on 100,000 shares with a $10 par value, the result is:',
    options: [
      '200,000 shares with $10 par value; total par value doubles',
      '200,000 shares with $5 par value; total par value remains the same',
      '100,000 shares with $20 par value',
      '200,000 shares with $10 par value; retained earnings is debited',
    ],
    correctAnswer: 1,
    explanation: 'A stock split increases the number of shares outstanding and proportionally decreases the par value per share, with no change in total equity. After a 2-for-1 split: shares increase from 100,000 to 200,000, par value decreases from $10 to $5. Total par value remains $1,000,000. No journal entry is required — only a memorandum entry noting the change. This differs from a large stock dividend, which requires a debit to retained earnings. Stock splits do not change stockholders\' equity components.',
    reference: 'ASC 505-20-25',
  },
  {
    id: 'far-d6-016',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-compensation',
    topic: 'Employee Benefits',
    subtopic: 'Defined Benefit Pension — Funded Status',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company\'s defined benefit pension plan has a projected benefit obligation (PBO) of $5,000,000 and plan assets at fair value of $4,200,000. How is this reported on the balance sheet?',
    options: [
      'A net pension asset of $800,000',
      'A net pension liability (underfunded status) of $800,000',
      'Only a footnote disclosure — no balance sheet recognition',
      'Pension expense of $800,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 715-30 (as amended by SFAS 158), the funded status of a defined benefit plan must be reported on the balance sheet. Funded status = Fair value of plan assets - PBO. $4,200,000 - $5,000,000 = ($800,000), meaning the plan is underfunded. This underfunded amount is reported as a net pension liability (noncurrent or current based on expected payments). If plan assets exceed PBO, a net pension asset is reported. Amounts in AOCI (unrecognized prior service cost, net actuarial gains/losses) are disclosed in the notes.',
    reference: 'ASC 715-30-25; SFAS 158',
  },
  {
    id: 'far-d6-017',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-compensation',
    topic: 'Share-Based Compensation',
    subtopic: 'Restricted Stock Units',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company grants 5,000 restricted stock units (RSUs) on January 1 with a grant-date fair value of $20 per unit and a 4-year graded vesting schedule (25% per year). No forfeitures are expected. Using straight-line attribution, Year 1 compensation expense is:',
    options: [
      '$100,000',
      '$25,000',
      '$50,000',
      '$20,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 718, RSUs are measured at the grant-date fair value. Total compensation cost = 5,000 units × $20 = $100,000. With graded vesting and straight-line attribution (an acceptable method), the total cost is recognized evenly over the longest vesting period (4 years): $100,000 ÷ 4 = $25,000 per year. Alternatively, companies may use the accelerated attribution method, which treats each vesting tranche as a separate award with its own requisite service period — this results in higher expense in earlier years.',
    reference: 'ASC 718-10-35',
  },
  {
    id: 'far-d6-018',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-income-tax',
    topic: 'Income Taxes',
    subtopic: 'Uncertain Tax Positions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 740-10-25-6 (FIN 48), a tax position is recognized in the financial statements only when:',
    options: [
      'The IRS has approved the position',
      'It is more likely than not (>50% probability) that the position will be sustained upon examination, based solely on the technical merits',
      'The company\'s tax advisor provides a written opinion',
      'The statute of limitations has expired',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 740-10-25-6, a tax position must meet the more-likely-than-not (MLTN) recognition threshold — a greater than 50% likelihood that the position will be sustained upon examination by the relevant taxing authority, based solely on the technical merits. Step 1: Recognition — does the position meet MLTN? If yes, proceed. If no, do not recognize any benefit. Step 2: Measurement — if recognized, the benefit is measured as the largest amount that has a greater than 50% cumulative probability of being realized upon ultimate settlement. Unrecognized tax benefits are recorded as a liability.',
    reference: 'ASC 740-10-25-6',
  },
  {
    id: 'far-d6-019',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-income-tax',
    topic: 'Income Taxes',
    subtopic: 'Intra-Period Tax Allocation',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Under intra-period tax allocation, income tax expense is allocated to all of the following EXCEPT:',
    options: [
      'Income from continuing operations',
      'Discontinued operations',
      'Other comprehensive income',
      'Cash flows from operating activities on the statement of cash flows',
    ],
    correctAnswer: 3,
    explanation: 'Intra-period tax allocation requires the total income tax expense for the period to be allocated among: (1) continuing operations, (2) discontinued operations, (3) other comprehensive income, and (4) items charged or credited directly to stockholders\' equity (e.g., prior period adjustments). The statement of cash flows is not a component of intra-period tax allocation. The purpose is to match the tax effects with the related item so that users can assess the after-tax impact of each component of comprehensive income.',
    reference: 'ASC 740-20-45',
  },
  {
    id: 'far-d6-020',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Dollar-Value LIFO',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the dollar-value LIFO method, inventory is measured by:',
    options: [
      'Tracking the specific quantity of each item',
      'Converting ending inventory to base-year dollars using a price index, comparing to the prior year layer in base-year dollars, and then converting any new layer back to current-year dollars',
      'Using the weighted-average cost',
      'Applying the retail inventory method',
    ],
    correctAnswer: 1,
    explanation: 'Dollar-value LIFO aggregates inventory into pools measured in dollars rather than tracking specific quantities. Steps: (1) Convert ending inventory at current prices to base-year dollars using a price index: Ending at base = Ending at current ÷ Price index. (2) Compare to prior year\'s ending inventory at base-year dollars to determine if a new layer exists. (3) If a new layer exists, convert it to current-year dollars (layer at base × current-year price index). (4) Total DV-LIFO = sum of all layers, each at the price index of the year it was added. This method handles changes in product mix and prices more effectively than unit LIFO.',
    reference: 'ASC 330-10-30',
  },
  {
    id: 'far-d6-021',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-intangibles',
    topic: 'Intangible Assets',
    subtopic: 'Research and Development Costs',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under U.S. GAAP (ASC 730), research and development costs are generally:',
    options: [
      'Capitalized and amortized over the expected benefit period',
      'Expensed as incurred',
      'Deferred until the product is commercially viable',
      'Capitalized only if a patent is expected',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 730-10-25-1, research and development costs are expensed as incurred because their future economic benefits are uncertain. R&D costs include: materials, equipment/facilities used in R&D, personnel costs, purchased intangibles for R&D with no alternative future use, and contract services. Exceptions: (1) software development costs after technological feasibility (ASC 985-20), (2) internal-use software in the application development stage (ASC 350-40), and (3) acquired in-process R&D in a business combination (capitalized as an intangible). IFRS permits capitalization of development costs if specific criteria are met.',
    reference: 'ASC 730-10-25-1',
  },
  {
    id: 'far-d6-022',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-intangibles',
    topic: 'Intangible Assets',
    subtopic: 'Software Development Costs',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 985-20, costs of developing software to be sold or leased are capitalized beginning when:',
    options: [
      'The project is approved by management',
      'Technological feasibility has been established',
      'The first sale occurs',
      'A working model exists',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 985-20, software development costs follow a three-stage model: (1) Before technological feasibility is established: expense as R&D. (2) After technological feasibility through general release: capitalize. (3) After general release: expense as maintenance/support. Technological feasibility is established upon completion of a detailed program design or, if no detailed design, a working model. Capitalized costs are amortized using the greater of: (a) straight-line over estimated economic life, or (b) ratio of current-period revenue to total expected revenue. Each period, capitalized costs are also evaluated for NRV impairment.',
    reference: 'ASC 985-20-25',
  },
  {
    id: 'far-d6-023',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-contingencies',
    topic: 'Contingencies',
    subtopic: 'Loss Contingencies',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 450-20, a loss contingency is accrued (recorded as a liability) when:',
    options: [
      'The loss is possible and can be reasonably estimated',
      'The loss is probable and the amount can be reasonably estimated',
      'The loss is remote',
      'The loss is certain and has been paid',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 450-20-25-2, a loss contingency is accrued when two conditions are met: (1) it is probable that a liability has been incurred (or an asset has been impaired) at the date of the financial statements, and (2) the amount of the loss can be reasonably estimated. If only one condition is met, or if the loss is reasonably possible, disclosure in the notes is required but no accrual is made. If the loss is remote, neither accrual nor disclosure is generally required (except for certain guarantees). "Probable" means the future event or events are likely to occur.',
    reference: 'ASC 450-20-25-2',
  },
  {
    id: 'far-d6-024',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Right of Return',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company sells 1,000 units at $100 each with a right of return within 30 days. Based on experience, the company expects 5% returns. Under ASC 606, revenue recognized at the time of sale is:',
    options: [
      '$100,000 with no adjustments',
      '$95,000, with a refund liability of $5,000 and an asset for the right to recover products',
      '$0 until the return period expires',
      '$100,000 minus estimated warranty costs',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 606-10-55-22 through 55-27, when a customer has a right of return, revenue is recognized for the amount of consideration to which the entity expects to be entitled (i.e., excluding products expected to be returned). Revenue = 950 units × $100 = $95,000. The company also recognizes: (1) a refund liability of $5,000 (50 units × $100) for the expected returns, and (2) an asset for the right to recover products from customers (at the former carrying amount, less any expected cost to recover). The refund liability and asset are updated each reporting period.',
    reference: 'ASC 606-10-55-22',
  },
  {
    id: 'far-d6-025',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Comprehensive Income',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following is included in other comprehensive income (OCI) under U.S. GAAP?',
    options: [
      'Depreciation expense',
      'Unrealized gains on available-for-sale debt securities',
      'Cost of goods sold',
      'Interest expense',
    ],
    correctAnswer: 1,
    explanation: 'Other comprehensive income includes items that bypass the income statement but affect stockholders\' equity. The four main OCI components are: (1) unrealized gains/losses on available-for-sale debt securities, (2) foreign currency translation adjustments, (3) pension and OPEB adjustments (prior service cost, actuarial gains/losses), and (4) gains/losses on certain cash flow hedging instruments. These amounts accumulate in Accumulated Other Comprehensive Income (AOCI) in the equity section. Comprehensive income = Net income + OCI.',
    reference: 'ASC 220-10-45',
  },
];
