// FAR Depth Questions - Batch 21
// Focus: FAR-III (Select Transactions)
// Topics: Foreign Currency (ASC 830), Derivatives & Hedging (ASC 815)
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const FAR_QUESTIONS_DEPTH_21: Question[] = [
  {
    id: 'far-d21-001',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Functional Currency',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 830, the functional currency of a foreign entity is:',
    options: [
      'Always the U.S. dollar',
      'The currency of the primary economic environment in which the entity operates',
      'The currency of the parent company',
      'The currency with the highest exchange rate',
    ],
    correctAnswer: 1,
    explanation: 'ASC 830-10-45-2 defines the functional currency as the currency of the primary economic environment in which the entity operates — normally, the currency in which the entity primarily generates and expends cash. Determining the functional currency requires judgment based on economic indicators including: cash flows, sales prices, sales markets, expenses, financing, and intercompany transactions. The functional currency determination is fact-specific and may differ from the local currency or the reporting (parent) currency.',
    reference: 'ASC 830-10-45-2',
  },
  {
    id: 'far-d21-002',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Translation Method',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'When translating the financial statements of a foreign subsidiary whose functional currency is the local currency (not the U.S. dollar), assets and liabilities are translated at:',
    options: [
      'Historical exchange rates',
      'The current exchange rate as of the balance sheet date',
      'The average exchange rate for the period',
      'A weighted-average of current and historical rates',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-10-45-17, when translating from the functional currency to the reporting currency (current rate method): assets and liabilities are translated at the current exchange rate at the balance sheet date. Revenue and expense items are translated at the exchange rates in effect when the transactions occur (or a weighted-average rate for the period as a practical expedient). Equity accounts are translated at historical rates. The resulting translation adjustment is reported in other comprehensive income (OCI) as a cumulative translation adjustment (CTA), not in net income.',
    reference: 'ASC 830-10-45-17',
  },
  {
    id: 'far-d21-003',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Remeasurement Method',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When the functional currency of a foreign subsidiary is the U.S. dollar (the reporting currency), financial statements denominated in the local currency are remeasured using the temporal method. Under this method, monetary assets and liabilities are remeasured at:',
    options: [
      'Historical exchange rates',
      'The current exchange rate at the balance sheet date, with remeasurement gains and losses recognized in net income',
      'The average exchange rate for the period',
      'No remeasurement is necessary',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-10-45-17 through 20, when the functional currency is the reporting currency (U.S. dollar) and the books are maintained in the local currency, the temporal method (remeasurement) is used. Monetary items (cash, receivables, payables, debt) are remeasured at the current rate. Nonmonetary items carried at historical cost (inventory, PP&E, intangibles, equity) are remeasured at historical rates. Revenue and expenses are generally at the average rate, except those related to nonmonetary items (depreciation, COGS) which use historical rates. Remeasurement gains and losses are included in net income — unlike translation adjustments which go to OCI.',
    reference: 'ASC 830-10-45-17 through 20',
  },
  {
    id: 'far-d21-004',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Foreign Currency Transactions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A U.S. company purchases goods from a German supplier for €100,000 when the exchange rate is $1.10/€. At year-end, the rate is $1.15/€. The company records:',
    options: [
      'No adjustment — the payable remains at $110,000',
      'An exchange loss of $5,000, adjusting the payable to $115,000',
      'An exchange gain of $5,000',
      'A deferred exchange loss in OCI',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-20-35-1, foreign currency transactions are initially recorded at the spot rate on the transaction date: €100,000 × $1.10 = $110,000 payable. At each balance sheet date, monetary items denominated in a foreign currency are remeasured at the current rate: €100,000 × $1.15 = $115,000. The change of $5,000 ($115,000 – $110,000) is an exchange loss because the dollar weakened (each euro now costs more dollars), increasing the U.S. dollar cost of paying the euro-denominated liability. Transaction gains and losses are recognized in net income in the period of the change.',
    reference: 'ASC 830-20-35-1',
  },
  {
    id: 'far-d21-005',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Cumulative Translation Adjustment',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a parent company disposes of its entire investment in a foreign subsidiary, the cumulative translation adjustment (CTA) previously recorded in AOCI is:',
    options: [
      'Left in AOCI permanently',
      'Reclassified from AOCI to net income as part of the gain or loss on disposal',
      'Charged directly to retained earnings',
      'Reversed against the investment account',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-30-40-1, upon the complete or substantially complete liquidation or sale of an investment in a foreign entity, the cumulative translation adjustment (CTA) component of AOCI attributable to that entity is removed from equity and reclassified into net income, included as part of the gain or loss on disposal. For partial disposals that result in loss of control, the entire CTA is reclassified. For partial disposals where control is retained (equity transactions), no CTA is reclassified. This is analogous to the recycling of OCI items upon disposal of AFS securities.',
    reference: 'ASC 830-30-40-1',
  },
  {
    id: 'far-d21-006',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Derivative Definition',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 815, a derivative instrument has all of the following characteristics EXCEPT:',
    options: [
      'It has one or more underlyings and one or more notional amounts',
      'It requires a large initial net investment relative to the exposure',
      'It requires no initial net investment or a smaller net investment than would be required for other contracts with similar exposure',
      'It can be net settled',
    ],
    correctAnswer: 1,
    explanation: 'ASC 815-10-15-83 defines a derivative as having three characteristics: (1) one or more underlyings (price, rate, index) and one or more notional amounts (units, shares, bushels) or payment provisions; (2) requires no initial net investment or an initial net investment smaller than would be required for contracts with the same response to market factors; (3) terms require or permit net settlement (can be settled net, there is a market mechanism for net settlement, or the asset delivered is readily convertible to cash). A derivative specifically does NOT require a large initial investment — that would be a characteristic of the underlying asset itself.',
    reference: 'ASC 815-10-15-83',
  },
  {
    id: 'far-d21-007',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Fair Value Hedge',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 815, in a qualifying fair value hedge, changes in fair value of the hedging instrument and the hedged item attributable to the hedged risk are:',
    options: [
      'Both recognized in OCI',
      'Both recognized in net income in the current period, with the goal of offsetting each other',
      'The hedging instrument in OCI and the hedged item in income',
      'Deferred until the hedged item is sold',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-25-35-1, in a fair value hedge, changes in the fair value of the hedging instrument are recognized in current earnings. The carrying amount of the hedged item is adjusted for the change in fair value attributable to the hedged risk, and this adjustment is also recognized in current earnings. Since both amounts are in earnings simultaneously, they offset each other if the hedge is effective. The net income impact reflects only hedge ineffectiveness. Common fair value hedges include hedging fixed-rate debt with an interest rate swap, or hedging firm commitments with currency forwards.',
    reference: 'ASC 815-25-35-1',
  },
  {
    id: 'far-d21-008',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Cash Flow Hedge',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 815, the effective portion of the gain or loss on a derivative designated as a cash flow hedge is reported in:',
    options: [
      'Net income immediately',
      'Other comprehensive income (OCI), and reclassified to earnings in the same period the hedged forecasted transaction affects earnings',
      'Retained earnings',
      'A separate hedge reserve account on the balance sheet',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-30-35-3, in a cash flow hedge (hedging variability of future cash flows), the effective portion of the change in fair value of the hedging instrument is recognized in OCI and accumulated in AOCI. When the hedged forecasted transaction occurs and affects earnings (e.g., when the hedged sale or interest payment occurs), the amount in AOCI is reclassified to earnings. Any ineffective portion is immediately recognized in current-period earnings. Common cash flow hedges include hedging variable-rate debt, forecasted sales in foreign currency, and anticipated commodity purchases.',
    reference: 'ASC 815-30-35-3',
  },
  {
    id: 'far-d21-009',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Net Investment Hedge',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'A hedge of the foreign currency exposure of a net investment in a foreign operation is accounted for by recognizing the effective portion of the gain or loss in:',
    options: [
      'Net income',
      'OCI — as part of the cumulative translation adjustment',
      'Cost of goods sold',
      'A separate hedging account',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-35-35-1, in a net investment hedge, the effective portion of the hedging instrument\'s gain or loss is reported in OCI within the cumulative translation adjustment (CTA) — the same location where translation adjustments from the foreign subsidiary are reported. This provides a natural offset in AOCI. The amount in CTA is not reclassified to earnings until the foreign operation is sold or substantially liquidated. The ineffective portion (including any amount excluded from the hedge effectiveness assessment, if applicable) is recognized in current-period earnings.',
    reference: 'ASC 815-35-35-1',
  },
  {
    id: 'far-d21-010',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Balance Sheet Presentation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 815, all derivative instruments must be measured and reported on the balance sheet at:',
    options: [
      'Historical cost',
      'Fair value, recognized as either assets or liabilities',
      'Notional amount',
      'Intrinsic value only',
    ],
    correctAnswer: 1,
    explanation: 'ASC 815-10-35-1 requires ALL derivative instruments to be measured at fair value and recognized on the balance sheet as either assets (when fair value is positive) or liabilities (when fair value is negative). This applies regardless of whether the derivative qualifies for hedge accounting. The fair value measurement follows ASC 820 (Fair Value Measurement). Derivatives not designated as hedging instruments have their changes in fair value recognized immediately in net income. The notional amount is not the carrying value — it is used only to calculate settlements.',
    reference: 'ASC 815-10-35-1',
  },
  {
    id: 'far-d21-011',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Hedge Effectiveness',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 815 (as updated by ASU 2017-12), to qualify for hedge accounting, a hedging relationship must be:',
    options: [
      'Perfectly effective (zero ineffectiveness)',
      'Highly effective, with documentation specifying the hedging relationship, the risk management objective, and the method of assessing effectiveness at inception',
      'Simply documented, with no effectiveness assessment required',
      'Approved by the SEC',
    ],
    correctAnswer: 1,
    explanation: 'ASC 815-20-25 requires that at inception, the hedging relationship must be formally documented, including: the hedging instrument, the hedged item or transaction, the nature of the risk being hedged, the method for assessing effectiveness, and the risk management objective. ASU 2017-12 simplified effectiveness requirements — it eliminated the requirement for quantitative retrospective effectiveness testing and allows qualitative assessments after initial quantitative assessment. However, the hedge must still be highly effective (i.e., the hedging relationship is expected to be highly effective at achieving offsetting changes in fair value or cash flows).',
    reference: 'ASC 815-20-25; ASU 2017-12',
  },
  {
    id: 'far-d21-012',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Highly Inflationary Economy',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 830, if a foreign subsidiary operates in a highly inflationary economy (cumulative inflation of approximately 100% or more over 3 years), the subsidiary\'s financial statements are:',
    options: [
      'Translated using the current rate method',
      'Remeasured as if the functional currency were the reporting currency (U.S. dollar) using the temporal method',
      'Not included in consolidation',
      'Reported in the local currency without adjustment',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-10-45-11, if the cumulative inflation rate in a foreign country is approximately 100% or more over a 3-year period, the economy is considered highly inflationary. In this case, the functional currency is considered to be the reporting currency (U.S. dollar), regardless of the economic indicators. The temporal method (remeasurement) is used, and remeasurement gains and losses are recognized in net income. This prevents the distortion that would occur if a rapidly depreciating currency were used as the functional currency under the current rate method.',
    reference: 'ASC 830-10-45-11',
  },
  {
    id: 'far-d21-013',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Intercompany Foreign Currency Transactions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A U.S. parent has a long-term intercompany receivable from its foreign subsidiary that is denominated in the subsidiary\'s local currency. This balance is not expected to be settled in the foreseeable future. Exchange gains and losses on this balance are reported in:',
    options: [
      'Net income, as a foreign currency transaction gain or loss',
      'OCI, as part of the cumulative translation adjustment, because the transaction is of a long-term investment nature',
      'Retained earnings directly',
      'Not recorded — intercompany balances are eliminated',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-20-35-3, exchange gains and losses on intercompany foreign currency transactions that are of a long-term investment nature (settlement is not planned or anticipated in the foreseeable future) are reported in OCI as part of the cumulative translation adjustment — not in net income. This is an exception to the general rule that transaction gains/losses go to income. The rationale is that these long-term intercompany balances are essentially part of the net investment in the foreign subsidiary. Note: while the receivable/payable is eliminated in consolidation, the CTA effect remains.',
    reference: 'ASC 830-20-35-3',
  },
  {
    id: 'far-d21-014',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Embedded Derivatives',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 815, an embedded derivative in a host contract must be separated (bifurcated) and accounted for as a standalone derivative if:',
    options: [
      'The host contract is a financial instrument',
      'The combined instrument is not measured at fair value with changes in earnings, the embedded derivative meets the definition of a derivative, and the economic characteristics of the embedded derivative are not clearly and closely related to the host',
      'The embedded derivative has a notional amount exceeding $1 million',
      'The host contract is with a foreign counterparty',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-15-25-1, an embedded derivative must be bifurcated from the host contract and accounted for at fair value as a derivative if ALL three conditions are met: (1) the combined instrument is not remeasured at fair value with changes recognized in earnings; (2) the embedded component, if freestanding, would meet the definition of a derivative under ASC 815-10-15-83; and (3) the economic characteristics and risks of the embedded derivative are not clearly and closely related to those of the host contract. Common examples include conversion features in debt, put/call features in debt at other than par, and equity-indexed interest rates.',
    reference: 'ASC 815-15-25-1',
  },
  {
    id: 'far-d21-015',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Interest Rate Swap',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has a $10 million variable-rate loan and enters into an interest rate swap to receive variable and pay fixed. This swap is designated as a cash flow hedge. The swap has a fair value gain of $200,000 at year-end. The company records:',
    options: [
      'A $200,000 gain in net income',
      'A derivative asset of $200,000 with the gain in OCI',
      'No entry until the swap is settled',
      'A reduction in the loan balance of $200,000',
    ],
    correctAnswer: 1,
    explanation: 'Since the swap qualifies as a cash flow hedge of the variable-rate interest payments, the effective portion of the change in fair value is recognized in OCI per ASC 815-30-35-3. The derivative is recognized on the balance sheet at fair value ($200,000 asset). The offsetting credit goes to OCI (AOCI on the balance sheet). As interest payments are made, amounts are reclassified from AOCI to earnings (interest expense) in the same period the hedged transaction affects earnings. The net effect is that the company\'s interest expense reflects the fixed rate from the swap rather than the variable rate on the loan.',
    reference: 'ASC 815-30-35-3',
  },
  {
    id: 'far-d21-016',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Speculative Derivatives',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A company enters into a commodity futures contract but does not designate it as a hedge. Changes in fair value of this derivative are:',
    options: [
      'Deferred in OCI until settlement',
      'Recognized in net income in each period',
      'Not recorded until settlement',
      'Capitalized as part of inventory cost',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-10-35-2, derivatives not designated as hedging instruments (speculative or trading derivatives) are recognized at fair value on the balance sheet, with all changes in fair value recognized in net income currently. There is no deferral mechanism — gains and losses flow through earnings each reporting period. This applies to all types of derivatives (forwards, futures, options, swaps) that are either not designated or do not qualify for hedge accounting under ASC 815-20.',
    reference: 'ASC 815-10-35-2',
  },
  {
    id: 'far-d21-017',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Translation — Revenue and Expenses',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'When translating a foreign subsidiary\'s income statement using the current rate method (ASC 830), revenue and expense items are typically translated at:',
    options: [
      'The closing (year-end) exchange rate',
      'The weighted-average exchange rate for the period',
      'The rate on the date of each individual transaction',
      'The historical exchange rate from the subsidiary\'s formation',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-10-45-19, revenue and expense items are translated at the exchange rate in effect when the item was recognized. However, as a practical matter and in accordance with ASC 830-10-45-21, a weighted-average rate for the period may be used (and is commonly used in practice) when exchange rates do not fluctuate significantly during the period. This differs from the temporal method (remeasurement), where revenue and expenses related to nonmonetary items (e.g., depreciation, COGS from historical-cost inventory) must use historical rates.',
    reference: 'ASC 830-10-45-19 through 21',
  },
  {
    id: 'far-d21-018',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Hedge Discontinuation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If a cash flow hedge is discontinued because the hedging relationship no longer meets the effectiveness criteria, the amount accumulated in AOCI is:',
    options: [
      'Immediately reclassified to earnings',
      'Remains in AOCI and is reclassified to earnings when the hedged forecasted transaction affects earnings (if still probable), or immediately if the forecasted transaction is no longer probable',
      'Charged to retained earnings',
      'Added to the carrying amount of the hedged item',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-30-40-1, when a cash flow hedge is discontinued: (1) if the forecasted transaction is still probable, the net gain or loss in AOCI is not immediately reclassified — it remains in AOCI until the forecasted transaction affects earnings, at which point it is reclassified; (2) if the forecasted transaction is no longer probable of occurring, the amount in AOCI is immediately reclassified to earnings. The derivative is no longer designated but is still measured at fair value with changes in earnings going forward (as an undesignated derivative).',
    reference: 'ASC 815-30-40-1 through 4',
  },
  {
    id: 'far-d21-019',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Forward Exchange Contracts',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A U.S. company enters into a 90-day forward contract to buy €500,000 to hedge a firm commitment to purchase equipment from a European vendor. This forward contract is a:',
    options: [
      'Speculative derivative',
      'Fair value hedge of a firm commitment denominated in a foreign currency',
      'Cash flow hedge of a forecasted transaction',
      'Net investment hedge',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-20-25-1, a forward contract used to hedge an existing firm commitment (a binding agreement to buy/sell at a specific price and date) denominated in a foreign currency qualifies as a fair value hedge. The firm commitment creates an exposure to changes in foreign currency rates that affect the fair value of the commitment. Both the forward contract and the firm commitment are adjusted to fair value, with offsetting gains and losses in earnings. If the transaction were a forecasted transaction (anticipated but not yet committed), it would qualify as a cash flow hedge instead.',
    reference: 'ASC 815-20-25-1',
  },
  {
    id: 'far-d21-020',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Excluded Components — ASU 2017-12',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASU 2017-12, an entity may elect to exclude certain components (such as time value or forward points) from the assessment of hedge effectiveness. Excluded components may be recognized in earnings using:',
    options: [
      'Only the mark-to-market approach',
      'Either the mark-to-market approach (recorded in earnings immediately) or a systematic and rational amortization approach (amortized over the life of the hedging instrument)',
      'Only amortization over the hedged item\'s useful life',
      'Through AOCI without ever recycling to earnings',
    ],
    correctAnswer: 1,
    explanation: 'ASU 2017-12 (codified in ASC 815-20-25-83A) allows entities to exclude certain components of the hedging instrument (e.g., time value of options, forward points on forwards, cross-currency basis spreads) from the assessment of hedge effectiveness. The excluded components can be recognized using either: (1) a mark-to-market approach — changes in fair value of the excluded component are recognized in current earnings each period; or (2) an amortization approach — the initial value of the excluded component is amortized on a systematic and rational basis over the life of the hedging instrument, with the difference between the change in fair value and the amortization amount recorded in OCI.',
    reference: 'ASC 815-20-25-83A; ASU 2017-12',
  },
  {
    id: 'far-d21-021',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Translation vs. Remeasurement Comparison',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The primary difference between translation (current rate method) and remeasurement (temporal method) regarding exchange gains and losses is:',
    options: [
      'Translation creates larger gains and losses',
      'Translation adjustments go to OCI, while remeasurement gains and losses go to net income',
      'Both methods report adjustments in net income',
      'Both methods report adjustments in OCI',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830, the key reporting difference is: Translation (current rate method) — used when the foreign currency is the functional currency — produces a cumulative translation adjustment (CTA) reported in other comprehensive income (AOCI). Remeasurement (temporal method) — used when the reporting currency (USD) is the functional currency — produces remeasurement gains and losses reported in net income. This distinction exists because translation adjustments are considered unrealized (related to a long-term investment) while remeasurement adjustments represent real economic effects on the dollar-functional entity.',
    reference: 'ASC 830-10-45',
  },
  {
    id: 'far-d21-022',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Scope Exceptions',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following is specifically excluded from the scope of ASC 815 (derivative accounting)?',
    options: [
      'Interest rate swaps',
      'Regular-way security trades (purchase or sale of a security with delivery within the customary settlement period)',
      'Currency forwards',
      'Commodity futures',
    ],
    correctAnswer: 1,
    explanation: 'ASC 815-10-15-100 provides several scope exceptions. Regular-way security trades (contracts for purchase/sale of securities that require delivery within the customary settlement period for the market) are excluded from derivative accounting and are accounted for on the trade date or settlement date consistent with the entity\'s policy. Other scope exceptions include: insurance contracts (ASC 944), certain financial guarantee contracts, certain contracts indexed to an entity\'s own equity (ASC 815-40), and leases (ASC 842). Interest rate swaps, currency forwards, and commodity futures all fall within the scope of ASC 815.',
    reference: 'ASC 815-10-15-100',
  },
  {
    id: 'far-d21-023',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Equity Accounts in Translation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When translating foreign subsidiary financial statements using the current rate method, common stock and additional paid-in capital are translated at:',
    options: [
      'The current exchange rate at the balance sheet date',
      'The historical exchange rate(s) in effect when the stock was issued',
      'The weighted-average rate for the current period',
      'The spot rate at the reporting date',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-10-45-17, equity accounts (common stock, APIC, beginning retained earnings) are translated at historical exchange rates — the rates in effect at the time the equity transactions occurred. Common stock issued at subsidiary formation is translated at the rate on that date. Subsequent stock issuances use the rate on the date of each issuance. This contrasts with assets and liabilities (current rate) and revenue/expenses (average rate). The difference between the translated net assets using current rates for assets/liabilities and historical rates for equity creates the cumulative translation adjustment (CTA) in AOCI.',
    reference: 'ASC 830-10-45-17',
  },
  {
    id: 'far-d21-024',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-derivatives',
    topic: 'Derivatives and Hedging',
    subtopic: 'Fair Value Hedge — Basis Adjustment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a fair value hedge of inventory, the carrying amount of the inventory is adjusted for the change in fair value attributable to the hedged risk. When the inventory is subsequently sold, the basis adjustment:',
    options: [
      'Is reversed',
      'Is included in cost of goods sold, since the adjusted carrying amount of the inventory becomes the new cost basis',
      'Is deferred in AOCI',
      'Is written off as a loss',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 815-25-35-1, in a fair value hedge, the hedged item (inventory) is adjusted for the change in fair value attributable to the hedged risk. This basis adjustment permanently changes the carrying amount of the inventory. When the inventory is subsequently sold, the adjusted carrying amount — including the cumulative basis adjustment — flows through cost of goods sold. There is no separate reversal or recycling. This ensures that the hedge impacts are recognized in the same period as the underlying transaction. For example, if a commodity hedge increased inventoryʼs carrying amount by $5,000, COGS will be $5,000 higher when sold.',
    reference: 'ASC 815-25-35-1',
  },
  {
    id: 'far-d21-025',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-foreign-currency',
    topic: 'Foreign Currency',
    subtopic: 'Two-Transaction Approach',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 830, U.S. GAAP uses the "two-transaction" approach for foreign currency transactions. This means:',
    options: [
      'The purchase and payment are treated as a single event at the payment date rate',
      'The original purchase (or sale) is recorded at the spot rate on transaction date, and any exchange rate change upon settlement or at year-end is a separate transaction gain or loss',
      'Two journal entries are required for every foreign currency transaction',
      'The transaction is recorded at both the forward and spot rate',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 830-20-25-1, the two-transaction approach treats the operating transaction (purchase/sale) and the financing/exchange component as separate events. The purchase or sale is recorded at the spot rate on the transaction date. Subsequently, any change in the exchange rate between the transaction date and the settlement (or reporting) date creates a separate transaction gain or loss reported in net income. This contrasts with the one-transaction approach (not permitted under U.S. GAAP) that would adjust the cost of the underlying item for exchange rate changes.',
    reference: 'ASC 830-20-25-1 through 5',
  },
];
