// FAR Depth Questions - Batch 8
// Focus: FAR-II (Select Financial Statement Accounts) — continued
// Topics: Revenue Recognition advanced, Leases advanced, Investments, Debt
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const FAR_QUESTIONS_DEPTH_8: Question[] = [
  {
    id: 'far-d8-001',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Contract Modifications',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A software company enters into a contract to deliver two modules for $100,000 each ($200,000 total). After delivering Module 1, the contract is modified to add Module 3 for $80,000 (standalone selling price is $100,000). Module 3 is distinct. How is the modification treated?',
    options: [
      'As a separate contract for Module 3',
      'A cumulative catch-up adjustment with total consideration of $280,000',
      'Prospective modification — remaining consideration of $180,000 allocated to Modules 2 and 3',
      'The entire original contract is restated',
    ],
    correctAnswer: 2,
    explanation: 'Under ASC 606-10-25-12, a contract modification is treated as a separate contract only if BOTH conditions are met: (1) the additional goods/services are distinct, AND (2) the price reflects the standalone selling price. Here, Module 3 is distinct, but $80,000 ≠ $100,000 standalone selling price, so it does NOT qualify as a separate contract. Since Module 1 is already delivered and distinct from Modules 2 and 3, the modification is treated prospectively: remaining consideration ($100,000 for Module 2 + $80,000 for Module 3 = $180,000) is allocated to the remaining performance obligations (Modules 2 and 3).',
    reference: 'ASC 606-10-25-12',
  },
  {
    id: 'far-d8-002',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Significant Financing Component',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company enters a contract to deliver equipment in 24 months for $1,210,000. The cash selling price today would be $1,000,000, reflecting a 10% annual rate. Under ASC 606, how is the $210,000 difference treated?',
    options: [
      'Reported entirely as revenue when equipment is delivered',
      'Separated as interest income ($100,000 in Year 1 and $110,000 in Year 2) and revenue of $1,000,000',
      'Deferred and amortized over the useful life of the equipment',
      'Reported as a contract liability',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 606-10-32-15, if the timing of payments provides a significant financing benefit, the transaction price must be adjusted to reflect the time value of money. The $210,000 difference represents a significant financing component. The entity recognizes: (1) Revenue of $1,000,000 (the cash selling price) when control of the equipment transfers. (2) Interest income of $100,000 in Year 1 ($1,000,000 × 10%) and $110,000 in Year 2 ($1,100,000 × 10%), using the effective interest method. A practical expedient allows ignoring the financing component if the period between transfer and payment is one year or less.',
    reference: 'ASC 606-10-32-15',
  },
  {
    id: 'far-d8-003',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Bill-and-Hold Arrangements',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 606, revenue is recognized in a bill-and-hold arrangement (goods billed but not yet shipped) when ALL of the following criteria are met EXCEPT:',
    options: [
      'The reason for the bill-and-hold arrangement is substantive (e.g., the customer requested it)',
      'The product is separately identified as belonging to the customer',
      'The customer must have taken physical possession of the goods',
      'The product is currently ready for physical transfer to the customer',
    ],
    correctAnswer: 2,
    explanation: 'Under ASC 606-10-55-81, a bill-and-hold arrangement allows revenue recognition BEFORE physical delivery if ALL criteria are met: (1) The reason for the arrangement is substantive (e.g., the customer lacks warehouse space). (2) The product is separately identified as belonging to the customer. (3) The product is currently ready for physical transfer. (4) The entity cannot use the product or direct it to another customer. The customer does NOT need to take physical possession — that is the entire point of a bill-and-hold. Control transfers even though the product remains at the seller\'s location.',
    reference: 'ASC 606-10-55-81',
  },
  {
    id: 'far-d8-004',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Short-Term Lease Exemption',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 842, a lessee may elect not to recognize a right-of-use asset and lease liability for leases with a term of:',
    options: [
      '3 years or less',
      '12 months or less at commencement (with no purchase option the lessee is reasonably certain to exercise)',
      '6 months or less',
      'Any operating lease regardless of term',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-20-25-2, a lessee may elect the short-term lease exemption for leases with a term of 12 months or less at the commencement date, provided the lease does not include a purchase option that the lessee is reasonably certain to exercise. If elected, the lessee recognizes lease payments on a straight-line basis over the lease term (similar to the old operating lease treatment). This is a practical expedient that avoids the need to capitalize small, short-term leases on the balance sheet.',
    reference: 'ASC 842-20-25-2',
  },
  {
    id: 'far-d8-005',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Lease Incentives',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A lessor offers a lessee $50,000 in lease incentives (reimbursement for leasehold improvements). Under ASC 842, the lessee should treat the incentive as:',
    options: [
      'Income recognized immediately at lease commencement',
      'A reduction of the right-of-use asset, amortized over the lease term',
      'A deferred credit amortized over the useful life of the improvements',
      'A reduction of lease expense only in the first year',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-10-30-2, lease incentives paid or payable by the lessor to the lessee reduce the measurement of the right-of-use (ROU) asset. The ROU asset is initially measured as: lease liability + initial direct costs + prepaid lease payments − lease incentives received. The reduced ROU asset is then amortized over the lease term (for operating leases) as part of the single lease cost. This approach effectively spreads the benefit of the incentive over the entire lease term rather than recognizing it immediately.',
    reference: 'ASC 842-10-30-2',
  },
  {
    id: 'far-d8-006',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-leases',
    topic: 'Leases',
    subtopic: 'Variable Lease Payments',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 842, a lease calls for monthly payments of $5,000 plus 2% of sales exceeding $500,000. How are the variable payments (the 2% of excess sales) treated by the lessee?',
    options: [
      'Included in the lease liability at commencement using an estimate',
      'Excluded from the lease liability and recognized as expense in the period incurred',
      'Capitalized as part of the right-of-use asset',
      'Deferred until total sales are known at year end',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 842-20-55-1, variable lease payments that depend on an index or a rate (e.g., CPI) are included in the initial measurement of the lease liability. However, variable payments that depend on performance or usage (such as a percentage of sales) are NOT included in the lease liability — they are recognized as variable lease expense in the period in which the performance or use occurs. The $5,000 fixed payment is included in the lease liability measurement, while the 2% of excess sales is expensed when incurred.',
    reference: 'ASC 842-20-55-1',
  },
  {
    id: 'far-d8-007',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-investments',
    topic: 'Investments',
    subtopic: 'Equity Securities — Fair Value',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 321, equity securities with readily determinable fair values that are not accounted for under the equity method are measured at:',
    options: [
      'Historical cost',
      'Fair value with changes recognized in net income',
      'Fair value with changes recognized in OCI',
      'Lower of cost or market',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 321-10-35-1 (as amended by ASU 2016-01), equity securities with readily determinable fair values are measured at fair value, with unrealized gains and losses recognized in NET INCOME (not OCI). This differs from the previous standard, which classified equity securities as trading or available-for-sale. The only exception is equity securities accounted for under the equity method (ASC 323) or those qualifying for the measurement alternative (without readily determinable fair values). This treatment increases income statement volatility for entities holding equity portfolios.',
    reference: 'ASC 321-10-35-1; ASU 2016-01',
  },
  {
    id: 'far-d8-008',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-investments',
    topic: 'Investments',
    subtopic: 'Held-to-Maturity Securities',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company purchases $500,000 face value bonds classified as held-to-maturity at a premium of $20,000. At the first interest date, the effective interest is $22,000 and the stated interest received is $25,000. What is the amortized cost after the first interest period?',
    options: [
      '$520,000',
      '$517,000 (premium reduced by $3,000)',
      '$522,000',
      '$500,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 320, held-to-maturity (HTM) debt securities are carried at amortized cost. Initial cost = $500,000 + $20,000 premium = $520,000. Premium amortization = Cash received - Interest income = $25,000 - $22,000 = $3,000. The premium is reduced by $3,000: new carrying amount = $520,000 - $3,000 = $517,000. The effective interest method allocates interest income based on the carrying amount × effective rate, and the difference between cash received and interest income amortizes the premium toward face value over the life of the bond.',
    reference: 'ASC 320-10-35-4',
  },
  {
    id: 'far-d8-009',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-investments',
    topic: 'Investments',
    subtopic: 'Available-for-Sale Impairment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A company holds an available-for-sale (AFS) debt security with an amortized cost of $100,000 and a fair value of $85,000. The entity does not intend to sell and will likely not be required to sell before recovery. Of the $15,000 decline, $6,000 is due to credit deterioration. Under ASC 326, how is the impairment recorded?',
    options: [
      '$15,000 loss in net income',
      '$6,000 credit loss in net income (through allowance) and $9,000 in OCI',
      '$15,000 in OCI with no income statement impact',
      '$6,000 in OCI and $9,000 in net income',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 326-30 (CECL for AFS debt securities), when an AFS security is impaired: (1) If the entity intends to sell or will be required to sell, the entire decline ($15,000) is recognized in net income. (2) If NOT intending to sell, the credit-related loss ($6,000) is recognized in net income through an allowance for credit losses (not a direct write-down), and the noncredit portion ($9,000) is recognized in OCI. This bifurcation preserves the ability to reverse the credit loss through the allowance if credit conditions improve, unlike the previous OTTI model which required direct write-downs.',
    reference: 'ASC 326-30-35-3',
  },
  {
    id: 'far-d8-010',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-debt',
    topic: 'Debt',
    subtopic: 'Notes Issued at Below-Market Rate',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company issues a $500,000, 3-year, zero-interest-bearing note to purchase equipment. The market rate for similar notes is 8%. The present value of $500,000 due in 3 years at 8% is $396,916. At what amount is the equipment recorded?',
    options: [
      '$500,000',
      '$396,916 (present value of the note)',
      '$443,458',
      '$103,084',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 835-30, when a note is exchanged for property and the stated rate of interest is not reasonable (or there is no stated rate, as in a zero-interest note), the note is recorded at its present value. The difference between the face amount ($500,000) and the present value ($396,916) is discount of $103,084, which represents interest. The equipment is recorded at $396,916 (the fair value of the note). Over the 3-year term, the $103,084 discount is amortized as interest expense using the effective interest method. The note\'s carrying amount increases from $396,916 to $500,000 at maturity.',
    reference: 'ASC 835-30',
  },
  {
    id: 'far-d8-011',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-debt',
    topic: 'Debt',
    subtopic: 'Debt Issuance Costs',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under current GAAP, debt issuance costs (e.g., legal fees, underwriting fees) incurred when issuing bonds are:',
    options: [
      'Expensed immediately as incurred',
      'Presented as a direct deduction from the carrying amount of the related debt liability and amortized over the life of the debt',
      'Capitalized as an asset on the balance sheet',
      'Recorded as a component of equity',
    ],
    correctAnswer: 1,
    explanation: 'Under ASU 2015-03 (ASC 835-30-45-1A), debt issuance costs are presented as a direct deduction from the carrying amount of the debt (similar to a debt discount), rather than as a deferred asset. The costs are amortized to interest expense over the term of the debt using the effective interest method. This presentation aligns with the treatment of debt discounts and premiums. For revolving credit arrangements, however, debt issuance costs may be reported as an asset and amortized ratably.',
    reference: 'ASC 835-30-45-1A; ASU 2015-03',
  },
  {
    id: 'far-d8-012',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-equity',
    topic: 'Equity',
    subtopic: 'Conversion of Preferred Stock',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has 10,000 shares of $100 par convertible preferred stock (total $1,000,000) with additional paid-in capital of $200,000. Each preferred share converts to 5 shares of $10 par common stock. Upon conversion, using the book value method, what is the credit to Common Stock?',
    options: [
      '$100,000',
      '$500,000 (50,000 shares × $10 par)',
      '$1,000,000',
      '$1,200,000',
    ],
    correctAnswer: 1,
    explanation: 'Under the book value method: (1) Remove preferred stock: Debit Preferred Stock $1,000,000 and Debit APIC-Preferred $200,000 (total book value = $1,200,000). (2) Issue common stock: 10,000 × 5 = 50,000 common shares × $10 par = $500,000 credit to Common Stock. (3) Remaining balance: $1,200,000 - $500,000 = $700,000 credit to APIC-Common Stock. No gain or loss is recognized under the book value method — the entire carrying amount of the preferred stock is transferred to the common stock accounts. The market value of the common stock is irrelevant.',
    reference: 'ASC 505-10-25',
  },
  {
    id: 'far-d8-013',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-equity',
    topic: 'Equity',
    subtopic: 'Quasi-Reorganization',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a quasi-reorganization, a company with a deficit in retained earnings:',
    options: [
      'Must file for bankruptcy protection',
      'Eliminates the deficit by reducing additional paid-in capital (and possibly writing down assets to fair value), providing a fresh start without formal reorganization',
      'Issues new stock to cover the deficit',
      'Reclassifies the deficit to accumulated OCI',
    ],
    correctAnswer: 1,
    explanation: 'A quasi-reorganization (ASC 852-20) allows a company with a large accumulated deficit to get a "fresh start" without going through formal bankruptcy proceedings. The process involves: (1) Restating assets and liabilities to fair values (usually writing them down, which may increase the deficit). (2) Eliminating the accumulated deficit by offsetting it against additional paid-in capital (APIC). (3) If APIC is insufficient, the par or stated value of stock may be reduced. After the quasi-reorganization, retained earnings starts at zero, and the entity must disclose the date of the quasi-reorganization for 10 years.',
    reference: 'ASC 852-20',
  },
  {
    id: 'far-d8-014',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-income-taxes',
    topic: 'Income Taxes',
    subtopic: 'Deferred Tax on Undistributed Earnings',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A parent company uses the equity method for a 30% investment in a domestic investee. The investee reports $1,000,000 in earnings. The parent expects to receive dividends (not capital gains). The dividend-received deduction is 65%. At a 21% tax rate, what deferred tax liability must the parent recognize on undistributed earnings of $300,000?',
    options: [
      '$63,000',
      '$22,050 — tax on undistributed earnings net of the DRD',
      '$0 — no DTL required for domestic investees',
      '$105,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 740-10-25-18, a deferred tax liability must be recognized on the undistributed earnings of an investee (unless an exception applies). For domestic investees, the DRD reduces the taxable portion. Parent\'s equity pickup = 30% × $1,000,000 = $300,000. With a 65% DRD, the taxable amount = $300,000 × (1 - 0.65) = $300,000 × 0.35 = $105,000. DTL = $105,000 × 21% = $22,050. The indefinite reversal exception under ASC 740-30-25-18 only applies to foreign corporate joint ventures and certain other specific situations — it does not apply to domestic investees.',
    reference: 'ASC 740-10-25-18; ASC 740-30-25-18',
  },
  {
    id: 'far-d8-015',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-income-taxes',
    topic: 'Income Taxes',
    subtopic: 'Tax Rate Change Effect on DTAs/DTLs',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has a deferred tax asset of $350,000 measured at the current enacted rate of 35%. Congress enacts a new rate of 21% effective next year. What is the adjusted DTA and where is the adjustment recognized?',
    options: [
      '$350,000 — DTAs are not adjusted for rate changes',
      '$210,000 — reduced by $140,000 recognized as income tax expense in the period of enactment',
      '$210,000 — reduced by $140,000 recognized in OCI',
      '$280,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 740-10-35-4, deferred tax assets and liabilities are measured at the enacted rate expected to apply when the temporary difference reverses. When a rate change is enacted, all existing DTAs and DTLs must be immediately adjusted. The DTA is remeasured: underlying temporary difference = $350,000 ÷ 0.35 = $1,000,000. New DTA = $1,000,000 × 0.21 = $210,000. The reduction of $140,000 ($350,000 - $210,000) is recognized as income tax expense in the period the rate change is enacted — not when it becomes effective. This can significantly affect the company\'s effective tax rate in the enactment year.',
    reference: 'ASC 740-10-35-4',
  },
  {
    id: 'far-d8-016',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-employee-benefits',
    topic: 'Employee Benefits',
    subtopic: 'Postretirement Benefits Other Than Pensions',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 715-60, the accumulated postretirement benefit obligation (APBO) for other postretirement benefits (e.g., retiree health care) is analogous to which pension obligation?',
    options: [
      'Vested benefit obligation',
      'Projected benefit obligation (PBO)',
      'Accumulated benefit obligation (ABO)',
      'Expected benefit obligation',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 715-60, the APBO is the present value of future benefits attributed to employee service rendered to date. It is analogous to the projected benefit obligation (PBO) for pensions, as both represent the actuarial present value considering expected future events. However, unlike pensions, postretirement health care benefits are often not funded (no plan assets). The expected postretirement benefit obligation (EPBO) is the total future benefits expected — the APBO is the portion of the EPBO that has been attributed to service to date. Net postretirement benefit cost includes: service cost, interest cost, expected return on plan assets (if any), and amortization of prior service cost and gains/losses.',
    reference: 'ASC 715-60',
  },
  {
    id: 'far-d8-017',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-compensation',
    topic: 'Share-Based Compensation',
    subtopic: 'Performance Conditions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A company grants 10,000 stock options with a grant-date fair value of $15 each, vesting only if cumulative revenue exceeds $50 million over a 3-year service period (a performance condition). At the end of Year 1, management estimates it is probable the target will be met. What is Year 1 compensation expense?',
    options: [
      '$0 — performance conditions prevent recognition until the target is actually met',
      '$50,000 (1/3 × 10,000 × $15)',
      '$150,000',
      '$25,000',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 718-10-25-20, compensation cost for awards with performance conditions is recognized if and when it becomes probable the condition will be achieved. Once probable, the cost is recognized over the requisite service period. At the end of Year 1, since management estimates the performance condition will probably be met, cumulative compensation cost = 1/3 (one year of three-year service period) × 10,000 options × $15 = $50,000. If in a later period the estimate changes to "not probable," previously recognized cost is reversed. Market conditions (e.g., stock price targets) are treated differently — they are incorporated into the grant-date fair value and not subsequently adjusted.',
    reference: 'ASC 718-10-25-20',
  },
  {
    id: 'far-d8-018',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Gross Profit Method',
    difficulty: 'easy',
    skillLevel: 'Application',
    question: 'A company needs to estimate ending inventory after a fire. Beginning inventory was $200,000, net purchases were $500,000, and net sales were $600,000. The historical gross profit percentage is 30%. What is the estimated ending inventory?',
    options: [
      '$280,000',
      '$280,000 (Goods available $700,000 − Estimated COGS $420,000)',
      '$220,000',
      '$100,000',
    ],
    correctAnswer: 1,
    explanation: 'Under the gross profit method: (1) Goods available for sale = Beginning inventory ($200,000) + Net purchases ($500,000) = $700,000. (2) Estimated COGS = Net sales × (1 − Gross profit %) = $600,000 × 70% = $420,000. (3) Estimated ending inventory = $700,000 − $420,000 = $280,000. This method is used for interim reporting and estimating inventory losses from casualties. It is NOT acceptable for annual financial reporting under GAAP — a physical count or perpetual system is required. The method assumes a stable gross profit percentage.',
    reference: 'ASC 270; Gross Profit Method (estimation technique)',
  },
  {
    id: 'far-d8-019',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Purchase Commitments',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has a noncancelable purchase commitment to buy raw materials for $200,000. At year end, the market value of the materials has declined to $170,000. Under GAAP, the company should:',
    options: [
      'Do nothing until the purchase occurs',
      'Recognize a $30,000 loss and accrue a liability in the current period',
      'Write down the purchase commitment to $170,000 and record the loss when inventory is purchased',
      'Disclose the commitment but record no loss',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 330-10-35-17, if the market price of goods subject to a firm, noncancelable purchase commitment declines below the commitment price, the expected loss should be recognized in the current period. The entry: Debit Loss on Purchase Commitments $30,000, Credit Accrued Liability on Purchase Commitments $30,000. This follows the conservatism principle — losses are recognized when probable, not when realized. When the goods are eventually purchased, the cost is recorded at the commitment price minus the previously recognized loss. If prices recover before purchase, the recovery is recognized as a gain (limited to the loss previously recorded).',
    reference: 'ASC 330-10-35-17',
  },
  {
    id: 'far-d8-020',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-ppe',
    topic: 'Property, Plant, and Equipment',
    subtopic: 'Component Depreciation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company purchases a manufacturing plant for $5,000,000. The major components include the building structure ($3,500,000, 40-year life), HVAC system ($500,000, 15-year life), and roof ($1,000,000, 20-year life). Under component depreciation, Year 1 straight-line depreciation is:',
    options: [
      '$125,000 ($5,000,000 ÷ 40 years)',
      '$170,833 ($3,500,000/40 + $500,000/15 + $1,000,000/20)',
      '$250,000',
      '$200,000',
    ],
    correctAnswer: 1,
    explanation: 'Component depreciation (permitted under GAAP, required under IFRS IAS 16) depreciates each significant component separately based on its own useful life. Building: $3,500,000 ÷ 40 = $87,500. HVAC: $500,000 ÷ 15 = $33,333. Roof: $1,000,000 ÷ 20 = $50,000. Total Year 1 depreciation = $87,500 + $33,333 + $50,000 = $170,833. This provides a more accurate matching of expense to the consumption of each component. When a component is replaced, its remaining carrying amount is derecognized, and the new component is capitalized and depreciated over its own useful life.',
    reference: 'ASC 360-10-35; IAS 16',
  },
  {
    id: 'far-d8-021',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-ppe',
    topic: 'Property, Plant, and Equipment',
    subtopic: 'Assets Held for Sale',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 360-10-45, a long-lived asset classified as held for sale is measured at:',
    options: [
      'Historical cost',
      'The lower of its carrying amount or fair value less cost to sell',
      'Fair value only',
      'Net realizable value',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 360-10-35-43, when a long-lived asset is classified as held for sale, it is measured at the LOWER of its carrying amount or fair value less cost to sell. Depreciation ceases once the asset is classified as held for sale. If fair value less cost to sell is lower than carrying amount, an impairment loss is recognized. Criteria for held-for-sale classification include: (1) management has committed to a plan to sell, (2) the asset is available for immediate sale, (3) active program to locate a buyer, (4) sale is probable within one year, (5) the asset is actively marketed at a reasonable price, (6) the plan is unlikely to be significantly changed.',
    reference: 'ASC 360-10-35-43; ASC 360-10-45-9',
  },
  {
    id: 'far-d8-022',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-intangibles',
    topic: 'Intangible Assets',
    subtopic: 'Customer-Related Intangibles',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In a business combination, a company acquires an identifiable customer list intangible asset with a fair value of $300,000 and estimated useful life of 5 years. How is this asset accounted for after the acquisition?',
    options: [
      'Expensed immediately as there is no contractual right',
      'Amortized straight-line over 5 years and tested for impairment when events indicate',
      'Tested for impairment annually but not amortized',
      'Written off at the end of the first year',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 350-30-35, an intangible asset with a finite useful life is amortized over that useful life. The customer list ($300,000, 5-year life) would be amortized at $60,000 per year (straight-line) or another systematic method reflecting the pattern of economic benefits. Finite-lived intangibles are NOT tested for impairment annually — they are tested only when events or changes in circumstances indicate the carrying amount may not be recoverable (trigger-based impairment under ASC 360-10). This contrasts with goodwill and indefinite-lived intangibles, which require annual impairment testing.',
    reference: 'ASC 350-30-35; ASC 805-20-55',
  },
  {
    id: 'far-d8-023',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Notes Receivable Impairment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A bank holds a $1,000,000 loan receivable at 6% interest. Due to the borrower\'s financial difficulty, the bank agrees to restructure the loan by reducing the interest rate to 3% for the remaining 3 years. The present value of restructured cash flows at the original 6% rate is $920,000. Under CECL, the bank should:',
    options: [
      'Continue to carry the loan at $1,000,000',
      'Recognize an $80,000 credit loss through the allowance for credit losses',
      'Write the loan down to $920,000 with a direct charge to the loan',
      'Recognize a $30,000 loss each year for 3 years',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 326-20 (CECL model, as amended by ASU 2022-02 which eliminated TDR classification for SEC filers), loan modifications due to borrower financial difficulty are evaluated under the general CECL framework. The bank measures the expected credit loss using the discounted cash flow method: present value of expected cash flows at the original effective interest rate ($920,000) vs. amortized cost ($1,000,000). The $80,000 difference is recognized through the allowance for credit losses (not a direct write-down). This allows for potential reversal if the borrower\'s condition improves. The allowance approach preserves the gross carrying amount of the loan on the balance sheet.',
    reference: 'ASC 326-20; ASU 2022-02',
  },
  {
    id: 'far-d8-024',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Licensing Revenue',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under ASC 606, a software company grants a 3-year license that provides the customer with a right to use the company\'s intellectual property as it exists at the point in time the license is granted. The $300,000 license fee is payable upfront. When is revenue recognized?',
    options: [
      'Ratably over 3 years',
      'At the point in time when the license is transferred to the customer',
      'Based on usage over the 3-year term',
      'At the end of the 3-year term',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 606-10-55-58, licenses are classified as either "right to access" (recognized over time) or "right to use" (recognized at a point in time). A right-to-use license provides the customer with IP as it exists at the grant date — the entity is not required to provide updates, upgrades, or ongoing support. Revenue is recognized at the point in time the license is transferred. The full $300,000 is recognized when the customer can begin using the software. A "right to access" license (which provides ongoing access to the entity\'s IP that changes significantly) is recognized over time because the customer simultaneously receives and consumes the benefit of the entity\'s ongoing activities.',
    reference: 'ASC 606-10-55-58',
  },
  {
    id: 'far-d8-025',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-contingencies',
    topic: 'Contingencies',
    subtopic: 'Gain Contingencies',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under ASC 450-30, a gain contingency is:',
    options: [
      'Recognized when it is probable and can be reasonably estimated',
      'Not recognized until realized, but may be disclosed if the likelihood of realization is high',
      'Recognized at fair value when probable',
      'Always disclosed in the footnotes regardless of likelihood',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 450-30-25, gain contingencies are NOT recognized in the financial statements until the gain is realized. This reflects the conservatism principle — losses are accrued when probable and estimable, but gains are deferred until realized to avoid premature income recognition. However, adequate disclosure may be made of a gain contingency, with care to avoid misleading implications about the likelihood of realization. Examples of gain contingencies: pending lawsuits where the entity is the plaintiff, possible refunds from the government, tax claims. The asymmetric treatment of gains vs. losses is a hallmark of conservatism in GAAP.',
    reference: 'ASC 450-30-25',
  },
];
