// FAR - Financial Accounting Expanded Questions
// 2026 CPA Exam Blueprint Compliant
// World-Class expansion - Second batch

import { Question } from '../../../types';

export const FAR_QUESTIONS_EXPANDED: Question[] = [
  // ==========================================
  // AREA I: Conceptual Framework
  // ==========================================
  {
    id: 'far-exp-001',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-framework',
    topic: 'Conceptual Framework',
    subtopic: 'Qualitative Characteristics',
    difficulty: 'medium',
    blueprintArea: 'FAR-I',
    skillLevel: 'Application',
    question: 'The fundamental qualitative characteristics of useful financial information are:',
    options: [
      'Comparability and timeliness',
      'Consistency and verifiability',
      'Materiality and cost constraint',
      'Relevance and faithful representation'
    ],
    correctAnswer: 3,
    explanation: 'Fundamental characteristics: Relevance (predictive/confirmatory value, materiality) and Faithful Representation (complete, neutral, free from error). Enhancing characteristics: comparability, verifiability, timeliness, understandability.',
    reference: 'FASB Concepts Statement No. 8',
  },
  {
    id: 'far-exp-002',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-framework',
    topic: 'Conceptual Framework',
    subtopic: 'Recognition',
    difficulty: 'hard',
    blueprintArea: 'FAR-I',
    skillLevel: 'Analysis',
    question: 'An item is recognized in financial statements when it:',
    options: [
      'Meets the definition of an element, is measurable, and is relevant and faithfully represented',
      'Is mentioned in the notes',
      'Has been paid for',
      'Management decides to include it',
    ],
    correctAnswer: 0,
    explanation: 'Recognition criteria: (1) meets definition of element (asset, liability, etc.), (2) can be measured with sufficient reliability, (3) information is relevant and represents faithfully what it purports to represent.',
    reference: 'FASB Concepts Statement No. 5',
  },
  {
    id: 'far-exp-003',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-framework',
    topic: 'Conceptual Framework',
    subtopic: 'Elements',
    difficulty: 'easy',
    blueprintArea: 'FAR-I',
    skillLevel: 'Remembering and Understanding',
    question: 'Under GAAP, an asset is defined as:',
    options: [
      'Something the company owns',
      'A present right to an economic benefit',
      'Cash and equivalents only',
      'Property, plant, and equipment',
    ],
    correctAnswer: 1,
    explanation: 'Asset definition: a present right of an entity to an economic benefit. Key aspects: present (not future), controlled by entity, result of past transaction, probable future economic benefit.',
    reference: 'FASB Concepts Statement No. 8',
  },

  // ==========================================
  // AREA II: Financial Statement Presentation
  // ==========================================
  {
    id: 'far-exp-004',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-presentation',
    topic: 'Balance Sheet',
    subtopic: 'Current Assets',
    difficulty: 'medium',
    blueprintArea: 'FAR-II',
    skillLevel: 'Application',
    question: 'Current assets are those expected to be converted to cash or used within:',
    options: [
      '30 days',
      'Six months',
      'One year or the operating cycle, whichever is longer',
      'The fiscal quarter',
    ],
    correctAnswer: 2,
    explanation: 'Current assets: cash and assets expected to be converted to cash, sold, or consumed within one year OR the operating cycle, whichever is longer. Operating cycle = time from cash to inventory to receivables to cash.',
    reference: 'ASC 210-10-45',
  },
  {
    id: 'far-exp-005',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-presentation',
    topic: 'Income Statement',
    subtopic: 'Discontinued Operations',
    difficulty: 'hard',
    blueprintArea: 'FAR-II',
    skillLevel: 'Analysis',
    question: 'Discontinued operations presentation requires:',
    options: [
      'Any disposed component',
      'Disposal of a component representing a strategic shift with major effect on operations and results',
      'Only unprofitable segments',
      'All asset sales',
    ],
    correctAnswer: 1,
    explanation: 'Discontinued operations (ASC 205-20): disposal must represent strategic shift that has/will have major effect on operations and financial results. Examples: major line of business, geographical area, major equity method investment.',
    reference: 'ASC 205-20-45',
  },
  {
    id: 'far-exp-006',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-presentation',
    topic: 'Cash Flow Statement',
    subtopic: 'Classification',
    difficulty: 'medium',
    blueprintArea: 'FAR-II',
    skillLevel: 'Application',
    question: 'Interest paid is classified as which activity under US GAAP?',
    options: [
      'Investing',
      'Financing',
      'Operating',
      'Either operating or financing',
    ],
    correctAnswer: 2,
    explanation: 'US GAAP: Interest paid and received = Operating. Dividends received = Operating. Dividends paid = Financing. IFRS allows more flexibility (operating or financing for interest).',
    reference: 'ASC 230-10-45',
  },
  {
    id: 'far-exp-007',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-presentation',
    topic: 'Cash Flow Statement',
    subtopic: 'Indirect Method',
    difficulty: 'hard',
    blueprintArea: 'FAR-II',
    skillLevel: 'Analysis',
    question: 'Under the indirect method, an increase in accounts receivable is:',
    options: [
      'Subtracted from net income (sales exceeded cash collections)',
      'Shown in investing',
      'Added to net income',
      'Not adjusted',
    ],
    correctAnswer: 0,
    explanation: 'Indirect method adjustments: AR increase = subtract (revenue recognized > cash collected). AP increase = add (expense recognized > cash paid). Depreciation = add (non-cash expense). Gain on sale = subtract.',
    reference: 'ASC 230-10-45',
  },

  // ==========================================
  // AREA III: Assets
  // ==========================================
  {
    id: 'far-exp-008',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Impairment - CECL',
    difficulty: 'hard',
    blueprintArea: 'FAR-III',
    skillLevel: 'Analysis',
    question: 'Under the Current Expected Credit Losses (CECL) model:',
    options: [
      'No allowance is recorded until default',
      'Expected credit losses are recognized at origination based on lifetime expectations',
      'Losses are recognized only when probable',
      'Only historical losses are considered',
    ],
    correctAnswer: 1,
    explanation: 'CECL requires recording expected credit losses at origination (day 1) based on lifetime expected losses. Consider: historical experience, current conditions, reasonable forecasts. No threshold (like "probable") required.',
    reference: 'ASC 326-20',
  },
  {
    id: 'far-exp-009',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Factoring',
    difficulty: 'hard',
    blueprintArea: 'FAR-III',
    skillLevel: 'Analysis',
    question: 'Factoring of receivables with recourse is treated as a sale when:',
    options: [
      'Always a sale regardless of terms',
      'Management elects sale treatment',
      'The factor agrees',
      'The transferor surrenders control over the receivables'
    ],
    correctAnswer: 3,
    explanation: 'Sale treatment requires: (1) assets isolated from transferor (legal), (2) transferee can pledge/exchange, (3) no agreement to repurchase. With recourse often fails #1 or #3, treated as secured borrowing.',
    reference: 'ASC 860-10-40',
  },
  {
    id: 'far-exp-010',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Lower of Cost or Net Realizable Value',
    difficulty: 'medium',
    blueprintArea: 'FAR-III',
    skillLevel: 'Application',
    question: 'Under US GAAP, inventory is measured at:',
    options: [
      'Historical cost always',
      'Fair value',
      'Lower of cost or net realizable value (cost or market for LIFO/retail)',
      'Replacement cost',
    ],
    correctAnswer: 2,
    explanation: 'ASC 330: Lower of cost or NRV for most inventory. LIFO/retail inventory uses lower of cost or market (market = replacement cost, bounded by NRV ceiling and NRV-margin floor).',
    reference: 'ASC 330-10-35',
  },
  {
    id: 'far-exp-011',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'LIFO Reserve',
    difficulty: 'hard',
    blueprintArea: 'FAR-III',
    skillLevel: 'Analysis',
    question: 'The LIFO reserve represents:',
    options: [
      'The difference between inventory at LIFO and inventory at FIFO (or current cost)',
      'Cash set aside for inventory',
      'Expected inventory losses',
      'Prepaid inventory costs'
    ],
    correctAnswer: 0,
    explanation: 'LIFO reserve = Inventory at FIFO (or current cost) - Inventory at LIFO. During inflation, LIFO inventory is lower. The reserve enables comparison with FIFO companies and calculation of LIFO liquidation effects.',
    reference: 'ASC 330 Disclosure Requirements',
  },
  {
    id: 'far-exp-012',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-ppe',
    topic: 'Fixed Assets',
    subtopic: 'Capitalized Costs',
    difficulty: 'medium',
    blueprintArea: 'FAR-III',
    skillLevel: 'Application',
    question: 'Costs capitalized as part of property, plant, and equipment include:',
    options: [
      'Purchase price plus all costs to bring the asset to its intended use and location',
      'Only the purchase price',
      'Operating costs for the first year',
      'Repairs and maintenance'
    ],
    correctAnswer: 0,
    explanation: 'Capitalize: purchase price, sales tax, freight, installation, testing, legal fees for acquisition. Expense: repairs, maintenance, training, operating costs after asset is ready for use.',
    reference: 'ASC 360-10-30',
  },
  {
    id: 'far-exp-013',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-ppe',
    topic: 'Fixed Assets',
    subtopic: 'Asset Retirement Obligations',
    difficulty: 'hard',
    blueprintArea: 'FAR-III',
    skillLevel: 'Analysis',
    question: 'An asset retirement obligation (ARO) is recognized at:',
    options: [
      'Acquisition date at fair value of the expected future retirement cost',
      'Retirement date',
      'When cash is paid',
      'Only if legally required',
    ],
    correctAnswer: 0,
    explanation: 'ARO recognized when incurred (usually acquisition) at fair value of expected future retirement cost. Dr. Asset, Cr. Liability. Liability accretes over time; asset cost depreciated. Legal obligation required (statutory, contractual).',
    reference: 'ASC 410-20',
  },
  {
    id: 'far-exp-014',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-III',
    topic: 'Intangible Assets',
    subtopic: 'Goodwill Impairment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Barton Corp. acquired 100% of Wallace Inc. for $5 million. On the acquisition date, Wallace\'s identifiable net assets had a fair value of $4.2 million. At year-end, the reporting unit\'s carrying amount (including goodwill) is $5.3 million and its fair value is $4.9 million. What goodwill impairment loss should Barton recognize?',
    options: [
      '$800,000',
      '$400,000',
      '$300,000',
      '$100,000',
    ],
    correctAnswer: 1,
    explanation: 'Goodwill at acquisition = $5,000,000 − $4,200,000 = $800,000. Under ASC 350-20-35 (simplified impairment test), impairment loss = Carrying amount of reporting unit − Fair value of reporting unit = $5,300,000 − $4,900,000 = $400,000. The loss is capped at the carrying amount of goodwill ($800,000), so the full $400,000 is recognized. This eliminates the old Step 2 implied fair value calculation.',
    reference: 'ASC 350-20-35',
  },
  {
    id: 'far-exp-015',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-III',
    topic: 'Intangible Assets',
    subtopic: 'R&D Costs',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Halston Co. spent $350,000 on basic research to develop a new manufacturing technique and $200,000 on the design and testing of pre-production prototypes. Under ASC 730, how much should Halston expense as R&D costs?',
    options: [
      '$200,000',
      '$350,000',
      '$550,000',
      '$0 — both are capitalized',
    ],
    correctAnswer: 2,
    explanation: 'Under ASC 730-10-25, all research and development costs are expensed as incurred. Both basic research ($350,000) and the design/testing of pre-production prototypes ($200,000) qualify as R&D activities. Total R&D expense = $550,000. Only software development costs after technological feasibility (ASC 985-20) and certain development costs under IFRS may be capitalized.',
    reference: 'ASC 730-10-25',
  },

  // ==========================================
  // AREA IV: Liabilities
  // ==========================================
  {
    id: 'far-exp-016',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-IV',
    topic: 'Contingencies',
    subtopic: 'Loss Contingencies',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'GreenTech Corp. is a defendant in an environmental cleanup lawsuit. Legal counsel believes it is probable GreenTech will lose and estimates damages between $2 million and $5 million, with $3.5 million being the most likely outcome. Under ASC 450, what amount should be accrued?',
    options: [
      '$2,000,000',
      '$3,500,000',
      '$5,000,000',
      '$0 — disclose only',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 450-20-30, when a loss contingency is probable and the amount can be reasonably estimated, it is accrued. If a range is given and one amount within the range is a better estimate than any other, that amount is accrued. Here, $3.5 million is the most likely outcome and should be accrued. If no amount in the range were more likely, the minimum ($2 million) would be accrued.',
    reference: 'ASC 450-20-25',
  },
  {
    id: 'far-exp-017',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-liabilities',
    topic: 'Contingencies',
    subtopic: 'Gain Contingencies',
    difficulty: 'medium',
    blueprintArea: 'FAR-IV',
    skillLevel: 'Application',
    question: 'Gain contingencies are:',
    options: [
      'Always recorded at fair value',
      'Not recognized until realized, but may be disclosed if probable',
      'Recorded when probable',
      'Ignored in all cases',
    ],
    correctAnswer: 1,
    explanation: 'Gain contingencies are NOT recognized until realized (conservatism). May disclose if probable, but avoid misleading implications about likelihood of realization.',
    reference: 'ASC 450-30',
  },
  {
    id: 'far-exp-018',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-bonds',
    topic: 'Bonds Payable',
    subtopic: 'Effective Interest Method',
    difficulty: 'hard',
    blueprintArea: 'FAR-IV',
    skillLevel: 'Analysis',
    question: 'Under the effective interest method, interest expense equals:',
    options: [
      'Face amount × stated rate',
      'Cash paid',
      'Carrying amount of the bond × market rate at issuance',
      'Premium amortization only',
    ],
    correctAnswer: 2,
    explanation: 'Effective interest: Interest expense = Carrying value × effective (market) rate at issuance. Cash interest = Face × stated rate. Difference amortizes premium (expense < cash) or discount (expense > cash).',
    reference: 'ASC 835-30',
  },
  {
    id: 'far-exp-019',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-bonds',
    topic: 'Bonds Payable',
    subtopic: 'Debt Extinguishment',
    difficulty: 'hard',
    blueprintArea: 'FAR-IV',
    skillLevel: 'Analysis',
    question: 'When bonds are retired early, the gain or loss equals:',
    options: [
      'Cash paid minus face value',
      'Reacquisition price minus carrying amount at retirement',
      'Face value minus original issue price',
      'No gain or loss is recognized',
    ],
    correctAnswer: 1,
    explanation: 'Early extinguishment gain/loss = Reacquisition price - Net carrying amount (face ± unamortized premium/discount - unamortized issue costs). Reported in income, not as extraordinary item.',
    reference: 'ASC 470-50-40',
  },

  // ==========================================
  // AREA V: Equity
  // ==========================================
  {
    id: 'far-exp-020',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Treasury Stock',
    difficulty: 'medium',
    blueprintArea: 'FAR-V',
    skillLevel: 'Application',
    question: 'Under the cost method, treasury stock is:',
    options: [
      'A contra-equity account at cost',
      'An asset',
      'Retired immediately',
      'Shown as a liability'
    ],
    correctAnswer: 0,
    explanation: 'Cost method: Dr. Treasury Stock (contra-equity) at cost. On reissuance: Cr. Treasury Stock at cost, with difference to APIC-Treasury Stock (or retained earnings if APIC-TS exhausted for losses).',
    reference: 'ASC 505-30-30',
  },
  {
    id: 'far-exp-021',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Stock Splits',
    difficulty: 'medium',
    blueprintArea: 'FAR-V',
    skillLevel: 'Application',
    question: 'A 2-for-1 stock split results in:',
    options: [
      'Doubling of common stock account',
      'Doubling shares outstanding, halving par value, no change to total equity',
      'Transfer from retained earnings',
      'Increase in total equity',
    ],
    correctAnswer: 1,
    explanation: 'Stock split: increase shares, decrease par proportionally. Total equity unchanged. No journal entry required (memo only). Stock dividend: transfer from RE to paid-in capital, shares increase.',
    reference: 'ASC 505-20',
  },
  {
    id: 'far-exp-022',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-equity',
    topic: 'Stockholders\' Equity',
    subtopic: 'Comprehensive Income',
    difficulty: 'hard',
    blueprintArea: 'FAR-V',
    skillLevel: 'Analysis',
    question: 'Other comprehensive income (OCI) includes:',
    options: [
      'Dividends declared',
      'All revenues and expenses',
      'Only operating income',
      'Unrealized gains/losses on AFS securities, foreign currency translation, pension adjustments, cash flow hedges',
    ],
    correctAnswer: 3,
    explanation: 'OCI items: unrealized gains/losses on AFS debt securities, foreign currency translation adjustments, pension/OPEB prior service cost and actuarial gains/losses, effective cash flow hedge gains/losses.',
    reference: 'ASC 220-10-45',
  },

  // ==========================================
  // Additional Areas: Government/NFP
  // ==========================================
  {
    id: 'far-exp-023',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-govt',
    topic: 'Government Accounting',
    subtopic: 'Fund Types',
    difficulty: 'hard',
    blueprintArea: 'FAR-V',
    skillLevel: 'Analysis',
    question: 'The General Fund is classified as a:',
    options: [
      'Proprietary fund',
      'Governmental fund',
      'Fiduciary fund',
      'Enterprise fund',
    ],
    correctAnswer: 1,
    explanation: 'Governmental funds (current financial resources, modified accrual): General, Special Revenue, Capital Projects, Debt Service, Permanent. Proprietary (economic resources, full accrual): Enterprise, Internal Service. Fiduciary: Trust, Custodial.',
    reference: 'GASB Statement 34',
  },
  {
    id: 'far-exp-024',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-govt',
    topic: 'Government Accounting',
    subtopic: 'Modified Accrual',
    difficulty: 'hard',
    blueprintArea: 'FAR-V',
    skillLevel: 'Analysis',
    question: 'Under modified accrual accounting for governmental funds, revenues are recognized when:',
    options: [
      'Measurable and available (collected within 60 days of year-end)',
      'Cash is received',
      'Earned',
      'Appropriated',
    ],
    correctAnswer: 0,
    explanation: 'Modified accrual: revenues recognized when measurable and available (typically collected within 60 days). Expenditures recognized when fund liability incurred (generally when goods/services received).',
    reference: 'GASB Statement 33',
  },
  {
    id: 'far-exp-025',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-govt',
    topic: 'Government Accounting',
    subtopic: 'Budgetary Accounting',
    difficulty: 'medium',
    blueprintArea: 'FAR-V',
    skillLevel: 'Application',
    question: 'The budgetary entry for estimated revenues in governmental accounting:',
    options: [
      'Credits Appropriations',
      'Debits Cash',
      'Credits Estimated Revenues',
      'Debits Estimated Revenues Control and credits Budgetary Fund Balance',
    ],
    correctAnswer: 3,
    explanation: 'Budget entry: Dr. Estimated Revenues Control, Cr. Appropriations Control, Dr/Cr Budgetary Fund Balance (for difference). This integrates budget into accounting records for control purposes.',
    reference: 'GASB Budgetary Accounting',
  },
  {
    id: 'far-exp-026',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-V',
    topic: 'Not-for-Profit Accounting',
    subtopic: 'Net Asset Classes',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A not-for-profit organization receives a $500,000 donation restricted by the donor for the purchase of lab equipment. When the equipment is purchased 6 months later, how should the release of restriction be reported?',
    options: [
      'As a transfer from net assets with donor restrictions to net assets without donor restrictions',
      'As a deduction from both restricted and unrestricted contributions',
      'As a capital contribution directly to the equipment account',
      'No reclassification is needed until the equipment is fully depreciated',
    ],
    correctAnswer: 0,
    explanation: 'Under ASC 958-205, when a donor-imposed restriction is satisfied (here, by purchasing the specified equipment), the NFP reclassifies the amount from net assets with donor restrictions to net assets without donor restrictions. This is reported as \'net assets released from restrictions\' on the statement of activities, increasing unrestricted net assets and decreasing restricted net assets by the same amount.',
    reference: 'ASC 958-205',
  },
  {
    id: 'far-exp-027',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-nfp',
    topic: 'Not-for-Profit Accounting',
    subtopic: 'Contributions',
    difficulty: 'hard',
    blueprintArea: 'FAR-V',
    skillLevel: 'Analysis',
    question: 'An unconditional promise to give (pledge) is recognized as:',
    options: [
      'A liability',
      'Revenue when the promise is made, at present value if due in more than one year',
      'Only when cash is received',
      'An expense',
    ],
    correctAnswer: 1,
    explanation: 'Unconditional pledges: revenue when promise made. Multi-year pledges at present value with discount amortized as contribution revenue. Conditional pledges recognized when conditions met. Allowance for uncollectible pledges required.',
    reference: 'ASC 958-605',
  },
  {
    id: 'far-exp-028',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-nfp',
    topic: 'Not-for-Profit Accounting',
    subtopic: 'Functional Expenses',
    difficulty: 'medium',
    blueprintArea: 'FAR-V',
    skillLevel: 'Application',
    question: 'NFPs must report expenses by:',
    options: [
      'Natural classification only',
      'Both functional (program, management, fundraising) and natural classification',
      'Functional classification only',
      'No specific requirement',
    ],
    correctAnswer: 1,
    explanation: 'ASC 958-720 requires presenting expenses by both: function (program services, management/general, fundraising) and nature (salaries, rent, depreciation). Statement or notes matrix format.',
    reference: 'ASC 958-720',
  },

  // Additional comprehensive questions
  {
    id: 'far-exp-029',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Bill-and-Hold',
    difficulty: 'hard',
    blueprintArea: 'FAR-II',
    skillLevel: 'Analysis',
    question: 'Revenue is recognized for bill-and-hold arrangements when:',
    options: [
      'Invoice is sent',
      'Substantive reason exists, product is identified, ready for transfer, and entity cannot use or direct to another customer',
      'Cash is received',
      'Customer requests delivery',
    ],
    correctAnswer: 1,
    explanation: 'Bill-and-hold revenue recognition requires: (1) substantive reason for arrangement, (2) product separately identified as customer\'s, (3) product ready for transfer, (4) cannot be used by entity or directed elsewhere.',
    reference: 'ASC 606-10-55-83',
  },
  {
    id: 'far-exp-030',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Principal vs Agent',
    difficulty: 'hard',
    blueprintArea: 'FAR-II',
    skillLevel: 'Evaluation',
    question: 'An entity is a principal (records gross revenue) if it:',
    options: [
      'Receives a commission',
      'Controls the goods or services before transfer to the customer',
      'Never takes title',
      'Acts only as an intermediary',
    ],
    correctAnswer: 1,
    explanation: 'Principal controls goods/services before transfer: reports gross revenue, cost of goods. Agent arranges for principal to provide: reports net commission revenue. Control indicators: primary obligation, inventory risk, pricing discretion.',
    reference: 'ASC 606-10-55-36',
  },
  {
    id: 'far-exp-031',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-investments',
    topic: 'Investments',
    subtopic: 'Equity Securities',
    difficulty: 'medium',
    blueprintArea: 'FAR-III',
    skillLevel: 'Application',
    question: 'Equity securities with readily determinable fair values are measured at:',
    options: [
      'Cost',
      'Fair value with changes in net income',
      'Lower of cost or market',
      'Amortized cost',
    ],
    correctAnswer: 1,
    explanation: 'Equity securities: fair value through net income (FV-NI). No OCI option for equity (unlike AFS debt). Equity method investments (20-50% ownership, significant influence) are exceptions - not fair value.',
    reference: 'ASC 321-10-35',
  },
  {
    id: 'far-exp-032',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-III',
    topic: 'Investments',
    subtopic: 'Debt Securities',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Quinn Corp. holds AFS debt securities with an amortized cost of $200,000. At year-end, fair value is $185,000, and Quinn determines $10,000 of the decline is due to credit loss. Under ASC 326, how is the impairment reported?',
    options: [
      '$15,000 loss in net income',
      '$10,000 allowance against the security with the remaining $5,000 in OCI',
      '$15,000 loss in other comprehensive income',
      '$10,000 in OCI and $5,000 in net income',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 326-30 (CECL for AFS debt securities), total unrealized loss is $15,000 ($200,000 − $185,000). The credit-related portion ($10,000) is recognized through an allowance for credit losses charged to net income. The non-credit portion ($5,000) is recognized in other comprehensive income. This allows reversals if credit improves, unlike the previous OTTI model.',
    reference: 'ASC 320-10-35',
  },
  {
    id: 'far-exp-033',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-leases',
    topic: 'Lease Accounting',
    subtopic: 'Short-Term Leases',
    difficulty: 'medium',
    blueprintArea: 'FAR-IV',
    skillLevel: 'Application',
    question: 'An entity may elect to not recognize lease assets and liabilities for:',
    options: [
      'Only operating leases',
      'All leases',
      'Leases over $100,000',
      'Leases with a term of 12 months or less (without purchase option likely to be exercised)',
    ],
    correctAnswer: 3,
    explanation: 'Short-term lease exemption: term ≤12 months (at commencement), no purchase option reasonably certain to exercise. Recognize lease expense straight-line. Election by class of underlying asset.',
    reference: 'ASC 842-20-25-2',
  },
  {
    id: 'far-exp-034',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-IV',
    topic: 'Lease Accounting',
    subtopic: 'Operating Lease - Lessee',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'On January 1, Year 1, Nelson Corp. (lessee) enters a 5-year operating lease with annual payments of $50,000 made at year-end. The discount rate is 6%. The present value of the lease payments is $210,618. What is Nelson\'s total lease expense in Year 1?',
    options: [
      '$50,000',
      '$42,124',
      '$12,637',
      '$62,637',
    ],
    correctAnswer: 0,
    explanation: 'Under ASC 842-20-25, for an operating lease, the lessee recognizes a single lease cost on a straight-line basis over the lease term. Total lease payments = 5 × $50,000 = $250,000. Annual straight-line lease expense = $250,000 ÷ 5 = $50,000. Although the journal entry separately debits lease expense (for the straight-line amount), credits the lease liability (for interest accretion), and adjusts the ROU asset, the net effect is a single $50,000 lease cost each year.',
    reference: 'ASC 842-20-35',
  },
  {
    id: 'far-exp-035',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-errors',
    topic: 'Accounting Changes',
    subtopic: 'Prior Period Errors',
    difficulty: 'hard',
    blueprintArea: 'FAR-I',
    skillLevel: 'Analysis',
    question: 'Material prior period errors are corrected by:',
    options: [
      'Current period adjustment',
      'Disclosure only',
      'Prospective adjustment',
      'Restating prior period financial statements',
    ],
    correctAnswer: 3,
    explanation: 'Error correction: restate prior periods presented. Adjust beginning retained earnings of earliest period presented. Disclose nature, effect on each line item. Immaterial errors may be corrected currently.',
    reference: 'ASC 250-10-45',
  },
  {
    id: 'far-exp-036',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-errors',
    topic: 'Accounting Changes',
    subtopic: 'Change in Estimate',
    difficulty: 'medium',
    blueprintArea: 'FAR-I',
    skillLevel: 'Application',
    question: 'Grant Corp. has been using a 10-year useful life for its production machinery. In Year 5, new information indicates the remaining useful life is 3 years instead of the original 5 years remaining. How should this change be reported?',
    options: [
      'Retrospectively by restating Years 1–4 depreciation',
      'Prospectively by adjusting depreciation over the remaining 3 years',
      'As a prior-period adjustment to retained earnings',
      'As an extraordinary item in the current year income statement',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 250-10-45-17, a change in accounting estimate (such as useful life of an asset) is accounted for prospectively — in the period of change and future periods if applicable. The remaining book value (after 4 years of depreciation) is depreciated over the new remaining useful life of 3 years. No restatement of prior periods is required.',
    reference: 'ASC 250-10-45-17',
  },
  {
    id: 'far-exp-037',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-forex',
    topic: 'Foreign Currency',
    subtopic: 'Remeasurement',
    difficulty: 'hard',
    blueprintArea: 'FAR-V',
    skillLevel: 'Analysis',
    question: 'Remeasurement is used when the functional currency differs from the recording currency. Remeasurement gains/losses are recorded in:',
    options: [
      'Retained earnings directly',
      'Other comprehensive income',
      'Net income',
      'A separate equity account',
    ],
    correctAnswer: 2,
    explanation: 'Remeasurement: convert to functional currency when recording currency ≠ functional currency. Monetary items at current rate, non-monetary at historical. Gains/losses to income. Translation (functional to reporting) goes to OCI.',
    reference: 'ASC 830-10-45',
  },
  {
    id: 'far-exp-038',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-related',
    topic: 'Related Parties',
    subtopic: 'Disclosure',
    difficulty: 'medium',
    blueprintArea: 'FAR-I',
    skillLevel: 'Application',
    question: 'Archer Corp.\'s CEO owns 60% of a supplier company that provides raw materials to Archer. During the year, Archer purchased $1.2 million from this supplier on normal credit terms. What disclosures are required under ASC 850?',
    options: [
      'No disclosure is needed because the transactions are at arm\'s length',
      'The nature of the relationship, a description of the transactions, and dollar amounts',
      'Only the dollar amounts of the transactions need to be disclosed',
      'Disclosure is required only if the terms differ from arm\'s-length pricing',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 850-10-50, related party disclosures are required regardless of whether transactions are at arm\'s length. Disclosures must include: (1) the nature of the relationship, (2) a description of transactions, (3) the dollar amount, (4) amounts due to/from related parties, and (5) the terms and manner of settlement.',
    reference: 'ASC 850-10-50',
  },
  {
    id: 'far-exp-039',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-subsequent',
    topic: 'Subsequent Events',
    subtopic: 'Types',
    difficulty: 'hard',
    blueprintArea: 'FAR-I',
    skillLevel: 'Analysis',
    question: 'A subsequent event providing evidence about conditions existing at the balance sheet date:',
    options: [
      'Is disclosed only',
      'Requires adjustment to the financial statements (recognized)',
      'Is ignored',
      'Results in qualification of audit opinion',
    ],
    correctAnswer: 1,
    explanation: 'Type 1 (recognized): conditions existed at B/S date, adjust F/S. Type 2 (non-recognized): conditions arose after B/S date, disclose if material. Period: B/S date through F/S issuance/availability.',
    reference: 'ASC 855-10-25',
  },
  {
    id: 'far-exp-040',
    section: 'FAR',
    courseId: 'cpa',
    topicId: 'far-segment',
    topic: 'Segment Reporting',
    subtopic: 'Aggregation',
    difficulty: 'hard',
    blueprintArea: 'FAR-I',
    skillLevel: 'Evaluation',
    question: 'Titan Corp. has four operating segments. Which of the following quantitative thresholds, if met by a single segment, requires separate segment disclosure under ASC 280?',
    options: [
      'The segment\'s assets are 5% or more of combined assets',
      'The segment\'s revenue is 10% or more of combined revenue of all segments',
      'The segment has more than 50 employees',
      'The segment operates in more than one geographic region',
    ],
    correctAnswer: 1,
    explanation: 'Under ASC 280-10-50-12, an operating segment is separately reportable if it meets any one of three 10% quantitative thresholds: (1) revenue (including intersegment) ≥ 10% of combined revenue, (2) absolute profit or loss ≥ 10% of the greater of combined reported profit or combined reported loss, or (3) assets ≥ 10% of combined assets.',
    reference: 'ASC 280-10-50-12',
  },
];
