// ISC - Information Systems Elite Questions
// 2026 CPA Exam Blueprint Compliant
// World-Class expansion - Elite batch (Final Push)

import { Question } from '../../../types';

export const ISC_QUESTIONS_ELITE: Question[] = [
  {
    id: 'isc-elite-001',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-systems',
    topic: 'Information Systems',
    subtopic: 'Database Normalization',
    difficulty: 'hard',
    blueprintArea: 'ISC-I',
    skillLevel: 'Analysis',
    question: 'Third Normal Form (3NF) in database design requires:',
    options: [
      'No repeating groups',
      'Flat file structure',
      'Foreign keys only',
      'All attributes depend on the key, the whole key, and nothing but the key (no transitive dependencies)'
    ],
    correctAnswer: 3,
    explanation: '3NF: 2NF + no transitive dependencies (non-key attributes depending on other non-key attributes). "Depends on key, whole key, nothing but key." Reduces data anomalies. Higher normal forms exist but 3NF often sufficient.',
    reference: 'Database Design - Normalization',
  },
  {
    id: 'isc-elite-002',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-systems',
    topic: 'Information Systems',
    subtopic: 'Microservices Architecture',
    difficulty: 'hard',
    blueprintArea: 'ISC-I',
    skillLevel: 'Evaluation',
    question: 'Microservices architecture differs from monolithic by:',
    options: [
      'Single deployment unit',
      'Shared database',
      'Decomposing application into independently deployable services with their own data stores',
      'Tighter coupling'
    ],
    correctAnswer: 2,
    explanation: 'Microservices: small, independent services, own data, own deployment, communicate via APIs. Benefits: scalability, flexibility, fault isolation. Challenges: distributed complexity, data consistency, operational overhead.',
    reference: 'Software Architecture - Microservices',
  },
  {
    id: 'isc-elite-003',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Cybersecurity',
    subtopic: 'Penetration Testing',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Evaluation',
    question: 'Penetration testing phases typically include:',
    options: [
      'Reconnaissance, scanning, exploitation, maintaining access, and reporting',
      'Only vulnerability scanning',
      'Installing patches',
      'User training only',
    ],
    correctAnswer: 0,
    explanation: 'Pen test phases: reconnaissance (info gathering), scanning (vulnerability identification), exploitation (attempting access), post-exploitation (maintaining access, lateral movement), reporting (findings, remediation). Rules of engagement critical.',
    reference: 'Penetration Testing Methodology',
  },
  {
    id: 'isc-elite-004',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Cryptography',
    subtopic: 'Digital Certificates',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Analysis',
    question: 'A digital certificate issued by a Certificate Authority contains:',
    options: [
      'Password',
      'Private key',
      'Public key, identity information, CA signature, validity period, and certificate serial number',
      'Encryption algorithm only',
    ],
    correctAnswer: 2,
    explanation: 'X.509 certificate contains: version, serial number, signature algorithm, issuer (CA), validity dates, subject (identity), subject public key, extensions, CA digital signature. Enables PKI trust model.',
    reference: 'PKI - Digital Certificates',
  },
  {
    id: 'isc-elite-005',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-controls',
    topic: 'IT Controls',
    subtopic: 'Segregation of Duties in IT',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'Critical IT segregation of duties separates:',
    options: [
      'Development, operations, and security administration roles',
      'Only management',
      'All functions',
      'Only programmers',
    ],
    correctAnswer: 0,
    explanation: 'IT SoD: developers should not deploy to production (ops), operators should not modify code, security admin separate from both. Database admin, system admin, application support also segregated. Compensating controls when not feasible.',
    reference: 'IT Controls - Segregation of Duties',
  },
  {
    id: 'isc-elite-006',
    courseId: 'cpa',
    section: 'ISC',
    blueprintArea: 'ISC-III',
    topic: 'IT General Controls',
    subtopic: 'Change Management',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A financial institution implements an intrusion detection system (IDS) to monitor network traffic to its core banking and financial reporting systems. The IDS operates in passive mode (detection only, no blocking). During a 6-month review period, the IDS detected 23 confirmed intrusion attempts, but the security team only responded to 5 because the alerts were buried among 50,000 other notifications. What should the auditor assess?',
    options: [
      'Passive mode IDS is sufficient because it detects intrusions',
      'The IDS detected threats but the response process failed — 18 confirmed intrusion attempts went uninvestigated, indicating that the detective control identifies threats but the organization lacks the capacity to respond, making the overall control ineffective',
      '23 intrusion attempts over 6 months is an acceptable level of risk',
      'The IDS should be turned off to reduce alert noise',
    ],
    correctAnswer: 1,
    explanation: 'A detective control has two components: detection and response. When 78% of confirmed intrusions go uninvestigated, the control chain is broken. The auditor should assess: (1) what happened with the 18 uninvestigated intrusions (were systems compromised?), (2) whether the security team is adequately staffed, (3) whether alert prioritization could improve response rates, (4) whether an intrusion prevention system (IPS) would provide automated blocking, and (5) the potential impact on financial data integrity.',
    reference: 'ITGC - Change Management',
  },
  {
    id: 'isc-elite-007',
    courseId: 'cpa',
    section: 'ISC',
    blueprintArea: 'ISC-III',
    topic: 'Data Privacy',
    subtopic: 'Data Subject Rights',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'An organization is subject to both GDPR (due to EU customers) and CCPA (due to California customers). The company\'s privacy policy states data is retained for 3 years, but the auditor discovers that customer data from 7 years ago remains in the financial reporting database. What is the combined regulatory risk?',
    options: [
      'Data retention policies are aspirational and non-compliance has no consequences',
      'Both GDPR and CCPA establish data minimization and retention principles — retaining data beyond the stated policy period violates privacy commitments to data subjects, creates regulatory exposure for fines (up to 4% of global revenue under GDPR), and increases the data breach impact surface',
      'GDPR and CCPA do not apply to financial reporting data',
      'The auditor should defer to the IT department on data retention without further analysis',
    ],
    correctAnswer: 1,
    explanation: 'Retaining personal data beyond stated retention periods violates both GDPR\'s data minimization principle (Article 5) and CCPA\'s requirements for reasonable data practices. The 4-year overretention increases: (1) regulatory fine exposure (GDPR: up to 4% of global revenue), (2) breach impact (more records affected), (3) litigation risk, and (4) compliance costs. The auditor should assess the financial exposure and consider whether contingent liability disclosure is needed.',
    reference: 'GDPR Articles 15-22',
  },
  {
    id: 'isc-elite-008',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-soc',
    topic: 'SOC Reporting',
    subtopic: 'Trust Services Criteria',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'The Trust Services Criteria used in SOC 2 reports include:',
    options: [
      'ISO 27001 only',
      'Financial reporting criteria',
      'COSO only',
      'Security (required), plus availability, processing integrity, confidentiality, and privacy (optional)',
    ],
    correctAnswer: 3,
    explanation: 'Trust Services Criteria: Security (required for all SOC 2), Availability, Processing Integrity, Confidentiality, Privacy (each optional based on scope). Security = common criteria. Maps to COSO principles.',
    reference: 'AICPA Trust Services Criteria',
  },
  {
    id: 'isc-elite-009',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-emerging',
    topic: 'Emerging Technologies',
    subtopic: 'AI/ML in Accounting',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Evaluation',
    question: 'AI/ML applications in accounting include:',
    options: [
      'Only chatbots',
      'Simple calculations only',
      'Replacing all accountants',
      'Anomaly detection, predictive analytics, document processing, and automated reconciliation'
    ],
    correctAnswer: 3,
    explanation: 'AI in accounting: anomaly/fraud detection, predictive forecasting, invoice processing (OCR/NLP), automated reconciliations, audit analytics, risk assessment. Augments human judgment. Governance and explainability important.',
    reference: 'AI in Accounting Applications',
  },
  {
    id: 'isc-elite-010',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-emerging',
    topic: 'Cloud Computing',
    subtopic: 'Cloud Shared Responsibility',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'An organization implements a cloud access security broker (CASB) to monitor and control access to cloud-based financial applications. The CASB identifies that employees are using 47 unsanctioned cloud applications (shadow IT) to store and share financial data, including customer account information and internal financial reports. The IT department was unaware of these applications. What should the auditor assess?',
    options: [
      'Shadow IT does not create risk because employees choose applications that meet their needs',
      'The 47 unsanctioned cloud applications represent unmanaged risk \u2014 financial data stored in uncontrolled cloud services may lack encryption, access controls, backup, and compliance with data retention policies, and the organization has no visibility into how this data is being used or shared',
      'The CASB should block all cloud applications to eliminate shadow IT',
      'Shadow IT is the employees\' responsibility, not the organization\'s'
    ],
    correctAnswer: 1,
    explanation: 'Shadow IT creates significant risk: (1) financial data in unmanaged services may violate data classification policies, (2) no access controls means anyone with the link may access data, (3) no backup or retention controls, (4) data may be stored in non-compliant jurisdictions, (5) the organization cannot respond to data subject access requests for data it doesn\'t know about. The auditor should assess the sensitivity of exposed data and recommend a shadow IT governance program.',
    reference: 'Cloud Security - Shared Responsibility',
  },
  {
    id: 'isc-elite-011',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Security Operations',
    subtopic: 'SIEM Systems',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Analysis',
    question: 'Security Information and Event Management (SIEM) provides:',
    options: [
      'Log aggregation, correlation, real-time alerting, and compliance reporting',
      'Antivirus only',
      'Backup services',
      'User training',
    ],
    correctAnswer: 0,
    explanation: 'SIEM: centralized log collection from multiple sources, correlation rules, real-time threat detection and alerting, dashboards, compliance reporting. Machine learning enhances detection. Requires tuning to reduce false positives.',
    reference: 'Security Operations - SIEM',
  },
  {
    id: 'isc-elite-012',
    courseId: 'cpa',
    section: 'ISC',
    blueprintArea: 'ISC-II',
    topic: 'Network Security',
    subtopic: 'Network Segmentation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An organization\'s network architecture places the financial reporting database server on the same network segment as the general employee network with no segmentation. The IT auditor identifies that any employee workstation can directly connect to the database server. What is the primary risk?',
    options: [
      'Increased network latency for database queries',
      'Insufficient network segmentation exposes the financial database to threats from any compromised endpoint on the network, increasing the risk of unauthorized access, data exfiltration, or lateral movement attacks',
      'The database server needs more storage',
      'No risk exists because the database requires authentication',
    ],
    correctAnswer: 1,
    explanation: 'Without network segmentation, a compromised employee workstation (through phishing, malware, etc.) can directly attack the database server. Defense-in-depth principles require critical financial systems to be segmented into protected zones with firewalls and access controls limiting connectivity. Database authentication alone is insufficient because credential theft, SQL injection, and exploitation of database vulnerabilities are all facilitated by direct network access.',
    reference: 'Network Security - Segmentation',
  },
  {
    id: 'isc-elite-013',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-bcp',
    topic: 'Business Continuity',
    subtopic: 'Recovery Strategies',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'Hot, warm, and cold sites differ in:',
    options: [
      'Location only',
      'Cost only',
      'Size',
      'Readiness level: hot is immediately operational, warm needs some setup, cold requires full setup',
    ],
    correctAnswer: 3,
    explanation: 'Hot site: fully equipped, data synced, immediate failover. Warm site: equipment ready, needs data restore. Cold site: facility only, requires hardware, software, data. Cost vs. RTO tradeoff. Cloud enables more flexibility.',
    reference: 'Disaster Recovery - Site Types',
  },
  {
    id: 'isc-elite-014',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-sdlc',
    topic: 'Systems Development',
    subtopic: 'DevSecOps',
    difficulty: 'hard',
    blueprintArea: 'ISC-I',
    skillLevel: 'Evaluation',
    question: 'DevSecOps integrates security into DevOps by:',
    options: [
      'Embedding security practices throughout the development pipeline from planning through operations',
      'Removing security checks',
      'Adding security review at the end',
      'Outsourcing security',
    ],
    correctAnswer: 0,
    explanation: 'DevSecOps: shift left security. Security in requirements, design threat modeling, secure coding, SAST/DAST in CI/CD, container security, infrastructure as code scanning, continuous monitoring. Automation key.',
    reference: 'DevSecOps Practices',
  },
  {
    id: 'isc-elite-015',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-audit',
    topic: 'IT Audit',
    subtopic: 'Continuous Auditing',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'Continuous auditing enables:',
    options: [
      'Annual audits only',
      'Eliminating auditors',
      'Automated, frequent or real-time testing of transactions and controls',
      'Less testing',
    ],
    correctAnswer: 2,
    explanation: 'Continuous auditing: automated audit procedures run frequently/continuously. Immediate exception identification. Requires: data access, automated rules, dashboard reporting. Distinct from continuous monitoring (management function).',
    reference: 'IT Audit - Continuous Auditing',
  },
  {
    id: 'isc-elite-016',
    courseId: 'cpa',
    section: 'ISC',
    blueprintArea: 'ISC-III',
    topic: 'Data Management',
    subtopic: 'Data Quality Dimensions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A financial institution implements a data loss prevention (DLP) system to monitor outbound emails containing sensitive customer information. During testing, the auditor finds that the DLP system generated 15,000 alerts in the past month, but only 200 were reviewed by the security team. What should the auditor conclude?',
    options: [
      'The DLP system is functioning properly because it generated alerts',
      'The DLP control has a design deficiency — if the alert volume overwhelms the review capacity, the control is not operating effectively because legitimate data exfiltration could go undetected',
      'The 200 reviewed alerts are sufficient if they represent a statistical sample',
      'DLP systems are detective controls and do not require timely review',
    ],
    correctAnswer: 1,
    explanation: 'A control that generates alerts without adequate review capacity has an effectiveness gap. If 98.7% of alerts go unreviewed, the control fails to achieve its objective of preventing data loss. The auditor should evaluate: (1) alert tuning and false positive rates, (2) staffing adequacy for review, (3) risk-based prioritization of alerts, and (4) whether unreviewed alerts contained actual incidents. This represents a significant deficiency in the data protection control environment.',
    reference: 'Data Governance - Quality',
  },
  {
    id: 'isc-elite-017',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-frameworks',
    topic: 'Control Frameworks',
    subtopic: 'NIST Cybersecurity Framework',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'An organization\'s security architecture includes a demilitarized zone (DMZ) between the internet and the internal network. The financial reporting web application is hosted in the DMZ. The auditor discovers that the DMZ server also hosts the financial database, which should be on the internal network behind an additional firewall layer. What architecture concern exists?',
    options: [
      'Hosting the database in the DMZ is acceptable because the DMZ has firewall protection',
      'Placing the financial database in the DMZ exposes it to internet-facing threats \u2014 the database should be on the internal network behind a second firewall layer, with only the web application tier in the DMZ, following a tiered architecture that limits the blast radius of a DMZ compromise',
      'DMZ and internal network placement does not affect database security',
      'A single firewall layer provides adequate protection for database servers'
    ],
    correctAnswer: 1,
    explanation: 'A tiered security architecture separates presentation (DMZ), application (DMZ or internal), and database (internal) layers. Placing the database in the DMZ: (1) exposes financial data to internet-adjacent attacks, (2) if the web server is compromised, the attacker has direct access to the database without crossing additional security boundaries, (3) violates defense-in-depth principles. The database should be behind an additional firewall layer on the internal network.',
    reference: 'NIST Cybersecurity Framework',
  },
  {
    id: 'isc-elite-018',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Application Security',
    subtopic: 'OWASP Top 10',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Analysis',
    question: 'The OWASP Top 10 represents:',
    options: [
      'Ten best security tools',
      'Network threats',
      'Database vulnerabilities',
      'Most critical web application security risks'
    ],
    correctAnswer: 3,
    explanation: 'OWASP Top 10: critical web security risks. 2021 version: Broken Access Control, Cryptographic Failures, Injection, Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Integrity Failures, Logging Failures, SSRF.',
    reference: 'OWASP Top 10',
  },
  {
    id: 'isc-elite-019',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-controls',
    topic: 'IT Controls',
    subtopic: 'Input Validation',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Application',
    question: 'Input validation controls include:',
    options: [
      'Range checks, format checks, reasonableness tests, and existence checks',
      'Output verification only',
      'User training only',
      'Physical controls',
    ],
    correctAnswer: 0,
    explanation: 'Input controls: validity (check against master file), limit/range (within acceptable values), reasonableness (logical), format/field (correct type/size), completeness (required fields), check digit (calculated verification). Prevent bad data entry.',
    reference: 'Application Controls - Input',
  },
  {
    id: 'isc-elite-020',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-emerging',
    topic: 'Emerging Technologies',
    subtopic: 'Blockchain Consensus',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'Proof of Work (PoW) and Proof of Stake (PoS) are:',
    options: [
      'Database queries',
      'Blockchain consensus mechanisms for validating transactions and adding blocks',
      'Encryption algorithms',
      'Network protocols',
    ],
    correctAnswer: 1,
    explanation: 'Consensus mechanisms: PoW = computational puzzles (Bitcoin), energy intensive. PoS = validators stake tokens, selected to validate (Ethereum 2.0). Others: DPoS, PBFT. Balance: security, decentralization, scalability.',
    reference: 'Blockchain Consensus Mechanisms',
  },
  {
    id: 'isc-elite-021',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-privacy',
    topic: 'Data Privacy',
    subtopic: 'Privacy by Design',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Evaluation',
    question: 'An organization\'s privacy impact assessment (PIA) reveals that its customer analytics platform profiles individuals using data from multiple sources including purchase history, browsing behavior, and third-party data brokers. The platform was deployed without approval from the data protection officer (DPO). Under GDPR Article 35, what compliance issue exists?',
    options: [
      'PIAs are optional and the lack of DPO approval is inconsequential',
      'The profiling activity likely triggers a mandatory Data Protection Impact Assessment (DPIA) requirement — systematic profiling of individuals, combined with lack of DPO involvement, represents a compliance failure that could result in supervisory authority enforcement actions',
      'Analytics platforms are exempt from GDPR if they serve financial purposes',
      'The DPO role is advisory only and has no authority over platform deployment',
    ],
    correctAnswer: 1,
    explanation: 'GDPR Article 35 requires a DPIA for processing that is likely to result in high risk to individuals, including systematic profiling. Large-scale profiling combining multiple data sources meets this threshold. Deploying without DPO involvement violates Article 38 (DPO must be involved in all data protection matters). The auditor should assess: (1) compliance with DPIA requirements, (2) whether individuals were informed, (3) lawful basis for processing, and (4) financial exposure for non-compliance.',
    reference: 'Privacy by Design Principles',
  },
  {
    id: 'isc-elite-022',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Identity Management',
    subtopic: 'Federated Identity',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Analysis',
    question: 'Federated identity management allows:',
    options: [
      'Separate credentials everywhere',
      'No authentication',
      'Users to access multiple systems across organizations with single credentials through trust relationships',
      'Password sharing',
    ],
    correctAnswer: 2,
    explanation: 'Federation: trust relationships between identity providers and service providers. Users authenticate once (IdP), access multiple services (SPs). Standards: SAML, OAuth, OIDC. Enables SSO across organizations. Requires trust agreements.',
    reference: 'Identity Federation',
  },
  {
    id: 'isc-elite-023',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-audit',
    topic: 'IT Audit',
    subtopic: 'GRC Platforms',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'GRC (Governance, Risk, Compliance) platforms integrate:',
    options: [
      'Policy management, risk assessment, compliance monitoring, audit management, and reporting',
      'Only compliance tracking',
      'Financial systems only',
      'HR functions',
    ],
    correctAnswer: 0,
    explanation: 'GRC platforms: centralized governance, risk, compliance management. Features: policy library, risk registers, control mapping, compliance tracking, audit workflow, issue management, reporting/dashboards. Reduces silos.',
    reference: 'GRC Technology',
  },
  {
    id: 'isc-elite-024',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Incident Response',
    subtopic: 'CIRT/CSIRT',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Application',
    question: 'A Computer Security Incident Response Team (CSIRT):',
    options: [
      'Only investigates crime',
      'Develops software',
      'Handles security incidents including detection, containment, eradication, and recovery',
      'Manages networks',
    ],
    correctAnswer: 2,
    explanation: 'CSIRT functions: incident triage, analysis, containment, eradication, recovery, lessons learned. May include: threat intelligence, vulnerability coordination, security awareness. Internal team or outsourced MSSP. Clear escalation procedures.',
    reference: 'Incident Response - CSIRT',
  },
  {
    id: 'isc-elite-025',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-controls',
    topic: 'Application Controls',
    subtopic: 'Three-Way Match',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Application',
    question: 'In procurement, a three-way match compares:',
    options: [
      'Three vendors',
      'Three signatures',
      'Three invoices',
      'Purchase order, receiving report, and vendor invoice before payment',
    ],
    correctAnswer: 3,
    explanation: 'Three-way match: PO (what was ordered), receiving report (what was received), invoice (what vendor claims). Prevents: paying for unordered items, paying without receipt, overpayment. Automated in ERP systems with tolerances.',
    reference: 'Procurement Controls',
  },
  {
    id: 'isc-elite-026',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-emerging',
    topic: 'Emerging Technologies',
    subtopic: 'Edge Computing',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'Edge computing processes data:',
    options: [
      'Only in central cloud',
      'Manually',
      'In data warehouses',
      'Near the data source to reduce latency and bandwidth, with local processing before cloud transmission'
    ],
    correctAnswer: 3,
    explanation: 'Edge computing: process data near source (devices, gateways). Benefits: reduced latency (critical for IoT, real-time), bandwidth savings, local resilience. Challenges: management, security, consistency. Complements cloud.',
    reference: 'Edge Computing',
  },
  {
    id: 'isc-elite-027',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-soc',
    topic: 'SOC Reporting',
    subtopic: 'Bridge Letter',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Application',
    question: 'A SOC report bridge letter:',
    options: [
      'Provides management assertion about controls for period after SOC report end date',
      'Replaces SOC report',
      'Is issued by auditor',
      'Covers five years',
    ],
    correctAnswer: 0,
    explanation: 'Bridge letter: management representation about control operation between SOC report end date and user\'s reporting date. Not audited. States no significant changes or describes changes. Supplements but doesn\'t replace SOC report.',
    reference: 'SOC Reports - Bridge Letters',
  },
  {
    id: 'isc-elite-028',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-data',
    topic: 'Data Management',
    subtopic: 'Data Lineage',
    difficulty: 'hard',
    blueprintArea: 'ISC-III',
    skillLevel: 'Analysis',
    question: 'Data lineage tracks:',
    options: [
      'User access',
      'Origin, movement, transformation, and destination of data throughout its lifecycle',
      'Data deletion',
      'Backup schedules',
    ],
    correctAnswer: 1,
    explanation: 'Data lineage: trace data from source through transformations to consumption. Supports: regulatory compliance, impact analysis, data quality, debugging, audit. Tools automate discovery. Critical for data governance.',
    reference: 'Data Governance - Lineage',
  },
  {
    id: 'isc-elite-029',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-systems',
    topic: 'Information Systems',
    subtopic: 'ERP Integration',
    difficulty: 'hard',
    blueprintArea: 'ISC-I',
    skillLevel: 'Analysis',
    question: 'ERP system benefits include:',
    options: [
      'Isolated systems',
      'Increased manual work',
      'Integrated data, standardized processes, real-time reporting, and single source of truth',
      'Multiple databases',
    ],
    correctAnswer: 2,
    explanation: 'ERP benefits: integrated modules (finance, HR, supply chain), centralized database, standardized processes, real-time visibility, reduced data duplication, improved controls. Challenges: complexity, cost, change management.',
    reference: 'Enterprise Systems - ERP',
  },
  {
    id: 'isc-elite-030',
    section: 'ISC',
    courseId: 'cpa',
    topicId: 'isc-security',
    topic: 'Cybersecurity',
    subtopic: 'Threat Intelligence',
    difficulty: 'hard',
    blueprintArea: 'ISC-II',
    skillLevel: 'Analysis',
    question: 'Threat intelligence feeds provide:',
    options: [
      'Compliance checklists',
      'Generic security tips',
      'Indicators of compromise (IOCs), threat actor TTPs, and contextual information for proactive defense',
      'User training content',
    ],
    correctAnswer: 2,
    explanation: 'Threat intelligence: IOCs (IPs, hashes, domains), TTPs (tactics, techniques, procedures), vulnerability info, threat actor profiles. Levels: strategic, operational, tactical, technical. Feeds integrated with SIEM, firewall, EDR.',
    reference: 'Threat Intelligence',
  },
];
