/**
 * CPA ISC Section - Questions Depth Batch 8
 * Blueprint Area: ISC-I (Information Systems)
 * Topics: IT Audit, Virtualization, Emerging Tech, IT Controls Assessment, Vendor Management
 */

import { Question } from '../../../types';

export const ISC_QUESTIONS_DEPTH_8: Question[] = [
  {
    id: 'isc-d8-001',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-audit',
    topic: 'IT Audit Techniques',
    subtopic: 'Computer-Assisted Audit Techniques (CAATs)',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Computer-Assisted Audit Techniques (CAATs) enable auditors to:',
    options: [
      'Eliminate the need for professional judgment',
      'Analyze large volumes of electronic data to identify anomalies, test controls, recalculate balances, and perform substantive testing more efficiently and comprehensively than manual sampling',
      'Only verify physical inventory',
      'Replace the need for internal controls',
    ],
    correctAnswer: 1,
    explanation: 'CAATs include: (1) Generalized audit software (GAS) — tools like ACL/Galvanize, IDEA, or Excel that allow auditors to query, analyze, and test large datasets. Functions: aging, stratification, gap detection, duplicate detection, Benford\'s Law analysis, recalculation, joining/matching files. (2) Test data — auditor submits fabricated transactions to the live or copied system to verify processing logic (valid and invalid transactions), (3) Integrated test facility (ITF) — creates a dummy entity (department, employee) within the live system; auditor submits test transactions alongside real ones, (4) Parallel simulation — auditor develops a program to process actual data and compares results to production output, (5) Embedded audit modules — continuous auditing routines built into the application (SCARF, snapshots). Benefits: 100% population testing (not just samples), pattern detection, efficiency for recurring audits.',
    reference: 'AICPA; IIA IPPF',
  },
  {
    id: 'isc-d8-002',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-systems',
    topic: 'Enterprise Systems',
    subtopic: 'Virtualization',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Server virtualization allows multiple virtual machines (VMs) to run on a single physical server. A key security risk of virtualization is:',
    options: [
      'Reduced server count',
      'VM escape — an attack where a threat actor breaks out of a guest VM to access the hypervisor or other VMs on the same host, potentially compromising all workloads on that physical server',
      'Faster application loading',
      'Lower electricity costs',
    ],
    correctAnswer: 1,
    explanation: 'Virtualization security risks: (1) VM escape — attacker gains access to the hypervisor from within a VM, enabling access to all VMs on that host, (2) VM sprawl — uncontrolled proliferation of VMs, leading to unpatched, unmonitored, or forgotten VMs with security vulnerabilities, (3) Hypervisor attacks — compromising the hypervisor layer gives control over all VMs, (4) Side-channel attacks — VMs on the same host may leak information through shared hardware resources (CPU cache, memory), (5) Snapshot/image risks — VM snapshots may contain sensitive data and may not be properly secured or deleted. Controls: (1) Patch hypervisor promptly, (2) Restrict hypervisor admin access, (3) Separate sensitive workloads (don\'t co-locate high-security and low-security VMs), (4) Monitor VM inventory (prevent sprawl), (5) Encrypt VM disk images, (6) Network segmentation between VM tiers.',
    reference: 'NIST SP 800-125; CIS Benchmarks',
  },
  {
    id: 'isc-d8-003',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-emerging',
    topic: 'Emerging Technologies',
    subtopic: 'Artificial Intelligence in Accounting',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Artificial intelligence (AI) and machine learning are increasingly used in accounting for:',
    options: [
      'Replacing all accountants',
      'Automating routine tasks (transaction classification, invoice processing, anomaly detection), enhancing audit analytics, predictive forecasting, and natural language processing for contract analysis',
      'Only generating random numbers',
      'Printing financial statements',
    ],
    correctAnswer: 1,
    explanation: 'AI/ML in accounting: (1) Transaction classification — ML algorithms automatically categorize transactions to the correct GL accounts, (2) Invoice processing — OCR + AI extracts data from invoices, matches to POs, and processes payments, (3) Anomaly detection — identifies unusual transactions (potential fraud, errors) by learning normal patterns, (4) Audit analytics — AI analyzes entire populations of transactions to identify risk areas for focused testing, (5) Predictive analytics — forecasting revenue, cash flows, bad debts, (6) NLP (Natural Language Processing) — analyzing contracts for revenue recognition terms, lease classification, (7) Chatbots — answering routine accounting queries. Risks: (1) Bias in training data, (2) Lack of explainability (black box models), (3) Over-reliance without human oversight, (4) Data privacy concerns. Governance: (1) Model validation and testing, (2) Human-in-the-loop for critical decisions, (3) Audit trail of AI decisions, (4) Regular model performance monitoring.',
    reference: 'AICPA; COSO AI Risk',
  },
  {
    id: 'isc-d8-004',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-vendor',
    topic: 'Vendor Management',
    subtopic: 'Third-Party Risk Management',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When an organization outsources a critical financial system to a third-party cloud provider, the organization:',
    options: [
      'Transfers all responsibility for controls to the provider',
      'Retains ultimate responsibility for the controls over its financial data — the organization must perform due diligence, obtain SOC reports, define contractual requirements, and implement complementary user entity controls (CUECs)',
      'Has no need for audit',
      'Should avoid cloud computing entirely',
    ],
    correctAnswer: 1,
    explanation: 'Third-party risk management: (1) Due diligence — evaluate vendor\'s financial stability, security practices, compliance history, business continuity plans before contracting, (2) SOC reports — obtain SOC 1 Type 2 (financial reporting controls) or SOC 2 Type 2 (security, availability, etc.) from the provider, (3) CUECs — Complementary User Entity Controls specified in the SOC report that the user organization must implement for the service provider\'s controls to be effective (e.g., restricting admin access at the user end), (4) Contract provisions — SLAs, right to audit, data ownership, breach notification, exit strategy/data portability, (5) Ongoing monitoring — regular review of SOC reports (check for exceptions, modifications, new subservice organizations), monitoring provider performance against SLAs, (6) Fourth-party risk — provider\'s subcontractors (carve-out vs. inclusive SOC reports). Regulatory principle: "You can outsource the function, but not the responsibility."',
    reference: 'AICPA SOC; FFIEC Guidance',
  },
  {
    id: 'isc-d8-005',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-controls',
    topic: 'Application Controls',
    subtopic: 'Automated vs Manual Controls',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Compared to manual controls, automated (programmed) application controls provide which advantage?',
    options: [
      'They are always cheaper to implement',
      'They operate consistently without human error — once properly configured and tested, they perform the same check every time, reducing the risk of inconsistency that exists with manual controls',
      'They never need testing',
      'They can operate without any IT general controls',
    ],
    correctAnswer: 1,
    explanation: 'Automated vs manual controls: Automated controls advantages: (1) Consistency — perform identically every time (no human variability, fatigue, or bias), (2) Timeliness — operate in real-time as transactions are processed, (3) Scalability — can handle large transaction volumes without additional resources, (4) Audit efficiency — if ITGCs are effective, automated controls need testing only once (benchmark testing) vs. manual controls tested throughout the period. Automated controls limitations: (1) Depend on ITGCs (change management, access controls) — if ITGCs are weak, automated controls may not be reliable, (2) Can be circumvented by unauthorized changes or access, (3) Fixed logic — may not address exceptions requiring judgment. Manual controls: better for: (1) Judgmental decisions (estimates, valuations), (2) Exception handling, (3) Situations requiring context/qualitative assessment. Best practice: combination of automated preventive controls and manual detective controls.',
    reference: 'PCAOB AS 2201; AICPA',
  },
  {
    id: 'isc-d8-006',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-sdlc',
    topic: 'Systems Development',
    subtopic: 'Post-Implementation Review',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A post-implementation review (PIR) in systems development evaluates:',
    options: [
      'Only whether the project was completed under budget',
      'Whether the system meets its intended business objectives, the project was delivered on time and within budget, lessons learned are documented, and any needed enhancements or fixes are identified',
      'The system\'s future decommission date',
      'Only the quality of the code',
    ],
    correctAnswer: 1,
    explanation: 'Post-Implementation Review (PIR) objectives: (1) Business objective assessment — does the system deliver expected business benefits? (2) Technical evaluation — does the system perform as designed? Are there reliability or performance issues? (3) User satisfaction — are users able to work effectively with the system? Was training adequate? (4) Budget/schedule review — compare actual cost and timeline to initial estimates and explain variances, (5) Lessons learned — document what went well and what could be improved for future projects, (6) Outstanding issues — identify and prioritize remaining defects, enhancement requests, and technical debt. Timing: typically 3-6 months after go-live (long enough for stabilization). Governance: results reported to the IT steering committee. CPA/audit relevance: PIR demonstrates project management discipline and supports the evaluation of IT investments for financial reporting purposes.',
    reference: 'COBIT BAI; ISA; ISACA',
  },
  {
    id: 'isc-d8-007',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-it-governance',
    topic: 'IT Governance',
    subtopic: 'IT Performance Metrics',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Key Performance Indicators (KPIs) for IT service delivery commonly include:',
    options: [
      'The number of employees in the IT department',
      'System uptime/availability percentages, mean time to repair (MTTR), incident resolution time, SLA compliance rates, and change success rates',
      'The color scheme of the company website',
      'The price of IT equipment',
    ],
    correctAnswer: 1,
    explanation: 'IT KPIs (aligned with ITIL/COBIT): Availability/reliability: (1) System uptime: percentage of time system is operational (e.g., 99.99% = 52 min downtime/year), (2) MTBF (Mean Time Between Failures) — average time between system failures, (3) MTTR (Mean Time To Repair) — average time to restore service after failure. Service management: (4) First-call resolution rate — percentage of incidents resolved on first contact, (5) SLA compliance — percentage of services meeting agreed service levels, (6) Customer satisfaction (CSAT) — user feedback scores. Change management: (7) Change success rate — percentage of changes deployed without incidents, (8) Emergency change percentage — lower is better (indicates good planning). Security: (9) Mean time to detect (MTTD) — time to identify a security incident, (10) Mean time to respond (MTTR-security) — time to contain/remediate. CPA relevance: KPIs indicate reliability of systems supporting financial reporting.',
    reference: 'ITIL 4; COBIT 2019',
  },
  {
    id: 'isc-d8-008',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-cloud',
    topic: 'Cloud Computing',
    subtopic: 'Cloud Security Controls',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a Software-as-a-Service (SaaS) cloud model, the customer\'s responsibility for security includes:',
    options: [
      'Managing the physical data center',
      'Configuring user access controls, managing data classification and protection, ensuring proper data governance, and implementing any required complementary user entity controls (CUECs) specified in the provider\'s SOC report',
      'Patching the operating system',
      'Managing the virtualization hypervisor',
    ],
    correctAnswer: 1,
    explanation: 'Shared responsibility in SaaS: CSP (Cloud Service Provider) responsible for: physical security, networking, storage, servers, virtualization, OS, runtime, application code, infrastructure patching. Customer responsible for: (1) Access management — user provisioning, role assignment, periodic access reviews, MFA enforcement, (2) Data governance — classification, retention, privacy compliance, encryption of sensitive data at rest/in transit (if customer-managed), (3) Configuration — security settings within the application (e.g., session timeouts, password policies, sharing settings), (4) CUECs — controls the customer must implement for the overall control environment to be effective, (5) Training — user security awareness, (6) Monitoring — reviewing audit logs, anomaly alerts provided by the SaaS application. Common SaaS mistake: assuming the CSP handles everything. The customer retains significant responsibility, especially for data and access.',
    reference: 'CSA Cloud Controls Matrix; NIST 800-145',
  },
  {
    id: 'isc-d8-009',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-emerging',
    topic: 'Emerging Technologies',
    subtopic: 'Robotic Process Automation (RPA)',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Robotic Process Automation (RPA) in accounting automates:',
    options: [
      'Only physical paper handling',
      'Repetitive, rule-based tasks (data entry, reconciliation, report generation, transaction posting) by using software bots that mimic human interactions with applications, improving speed and reducing manual errors',
      'Creative decision-making',
      'Physical robot movements',
    ],
    correctAnswer: 1,
    explanation: 'RPA in accounting: Common use cases: (1) Accounts payable — invoice data extraction, 3-way matching, payment processing, (2) Accounts receivable — cash application, dunning notices, (3) Bank reconciliation — matching bank transactions to GL entries, (4) Journal entries — posting recurring entries, intercompany eliminations, (5) Regulatory reporting — data compilation and formatting, (6) Expense report processing — receipt validation, policy compliance checking. RPA types: (1) Attended — bot works alongside user, triggered by user action, (2) Unattended — bot runs autonomously on scheduled triggers. Benefits: speed, accuracy (no human typing errors), consistency, audit trail (detailed logging). Risks: (1) Bots may propagate errors if logic is wrong, (2) Access control for bot credentials (bots need system access), (3) Change management — when underlying applications change, bots may break, (4) Exception handling — bots may not handle unexpected scenarios well.',
    reference: 'AICPA; Deloitte RPA Guide',
  },
  {
    id: 'isc-d8-010',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-audit',
    topic: 'IT Audit Techniques',
    subtopic: 'Continuous Auditing and Monitoring',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Continuous auditing differs from continuous monitoring in that continuous auditing:',
    options: [
      'Is performed by management',
      'Is performed by internal or external auditors using automated techniques to evaluate controls and transactions on a real-time or near-real-time basis, while continuous monitoring is a management responsibility to ensure ongoing control effectiveness',
      'Only occurs annually',
      'Does not use technology',
    ],
    correctAnswer: 1,
    explanation: 'Continuous auditing (CA) vs continuous monitoring (CM): Continuous Monitoring (CM): (1) Performed by management, (2) Ongoing evaluation of control effectiveness and risk, (3) Part of governance and compliance functions, (4) Tools: automated control testing, KRI dashboards, exception reporting. Continuous Auditing (CA): (1) Performed by auditors (internal or external), (2) Automated audit procedures that run frequently (daily, weekly), (3) Identifies control deficiencies, anomalies, and exceptions for auditor investigation, (4) Examples: automated journal entry testing (Benford\'s law, weekend/round number analysis), segregation of duties violation detection, three-way match exception monitoring. Relationship: CM provides first line assurance; CA provides independent assurance. Both rely on data analytics and automation. Maturity model: periodic audits → CAATs during annual audit → continuous auditing → continuous assurance. Benefits: earlier detection of issues, more efficient audits, broader coverage.',
    reference: 'IIA GTAG; AICPA',
  },
  {
    id: 'isc-d8-011',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-network',
    topic: 'Network Architecture',
    subtopic: 'DNS and Domain Name Security',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'DNS (Domain Name System) translates domain names to IP addresses. A DNS-related attack where an attacker corrupts DNS cache to redirect users to malicious websites is called:',
    options: [
      'SQL injection',
      'DNS cache poisoning (also called DNS spoofing) — the attacker inserts fraudulent DNS records into a resolver\'s cache, redirecting legitimate domain name queries to malicious IP addresses',
      'Cross-site scripting (XSS)',
      'Buffer overflow',
    ],
    correctAnswer: 1,
    explanation: 'DNS attacks: (1) DNS cache poisoning — attacker injects false DNS records into a resolver\'s cache, so users querying that domain are sent to a malicious server (e.g., fake banking site), (2) DNS hijacking — attacker changes the domain\'s DNS settings (e.g., by compromising the domain registrar account), (3) DNS amplification DDoS — attacker sends small DNS queries with spoofed source IP, and the DNS server sends large responses to the victim. Defenses: (1) DNSSEC (DNS Security Extensions) — digitally signs DNS records to prevent tampering, (2) DNS-over-HTTPS (DoH) or DNS-over-TLS (DoT) — encrypts DNS queries to prevent eavesdropping, (3) Randomized source ports and transaction IDs — makes cache poisoning harder, (4) Regular monitoring of DNS records for unauthorized changes. CPA relevance: DNS attacks can redirect financial transactions, intercept credentials, or enable phishing.',
    reference: 'NIST; RFC 4033 (DNSSEC)',
  },
  {
    id: 'isc-d8-012',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-controls',
    topic: 'Application Controls',
    subtopic: 'Processing Controls — Edit Checks',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A run-to-run total is a processing control that:',
    options: [
      'Limits the number of active users',
      'Verifies data integrity during each stage of processing by comparing control totals calculated at one processing stage to the expected totals at the next stage',
      'Counts the number of servers in a data center',
      'Monitors CPU utilization',
    ],
    correctAnswer: 1,
    explanation: 'Run-to-run totals: used to verify that data is processed completely and accurately through each stage. Process: (1) Calculate a control total at the end of one processing stage (e.g., total debits after input), (2) After the next processing stage, recalculate the total, (3) Compare — if totals don\'t match, investigate the discrepancy. Example: beginning balance (from prior run) + transactions processed − adjustments = ending balance (for next run). If ending balance doesn\'t match expected total, data may have been lost, duplicated, or altered during processing. Related concepts: (1) Batch control totals — totals calculated before processing; compared to totals after processing, (2) Hash totals — sum of a non-financial field (e.g., sum of account numbers) used solely for control purposes, (3) Record counts — number of records in a batch, verified at each stage.',
    reference: 'AICPA IT Controls',
  },
  {
    id: 'isc-d8-013',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-it-governance',
    topic: 'IT Governance',
    subtopic: 'IT Steering Committee',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'An IT steering committee is typically composed of:',
    options: [
      'Only IT department staff',
      'Senior representatives from both business and IT functions, responsible for prioritizing IT investments, approving major projects, and ensuring IT strategy aligns with business strategy',
      'External consultants only',
      'Junior developers',
    ],
    correctAnswer: 1,
    explanation: 'IT steering committee: governance body overseeing IT direction. Composition: (1) Senior business executives (CFO, COO, business unit leaders), (2) CIO/CTO and IT leadership, (3) Possibly the chief risk officer and chief information security officer (CISO). Responsibilities: (1) Approve IT strategy and policy, (2) Prioritize IT projects and resource allocation based on business value, (3) Review major IT investments and benefits realization, (4) Oversee IT risks and compliance, (5) Resolve conflicts between business and IT priorities, (6) Monitor IT performance (budget, timelines, KPIs). Meeting frequency: typically monthly or quarterly. CPA/audit relevance: (1) Existence and effectiveness of an IT steering committee is a governance control, (2) Demonstrates tone at the top for IT governance, (3) Auditors review steering committee minutes for evidence of oversight, (4) Absence of such governance may indicate a control deficiency.',
    reference: 'COBIT 2019 EDM; ISACA',
  },
  {
    id: 'isc-d8-014',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-data-analytics',
    topic: 'Data Analytics',
    subtopic: 'Benford\'s Law in Auditing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Benford\'s Law is used in auditing to detect potential fraud by:',
    options: [
      'Encrypting financial data',
      'Comparing the distribution of leading digits in financial data to the expected mathematical distribution — significant deviations may indicate fabricated or manipulated data',
      'Counting the total number of transactions',
      'Verifying user passwords',
    ],
    correctAnswer: 1,
    explanation: 'Benford\'s Law: in naturally occurring numerical datasets, the leading digit is not uniformly distributed. Expected frequencies: 1 (30.1%), 2 (17.6%), 3 (12.5%), 4 (9.7%), 5 (7.9%), 6 (6.7%), 7 (5.8%), 8 (5.1%), 9 (4.6%). Application in auditing: (1) Analyze leading digits of transaction amounts (expenses, revenue, journal entries), (2) Statistical comparison to expected distribution (chi-square test, z-score), (3) Significant spikes at specific digits may indicate: fabricated data, round-number estimates, amounts just below approval thresholds (e.g., many transactions at $9,999 to avoid $10,000 approval limit), duplicated transactions. Works well for: (1) Large, naturally occurring datasets (transaction amounts, check amounts, expense reports), (2) Data spanning multiple orders of magnitude. Does not work well for: assigned numbers (ZIP codes, SSNs), data with artificial constraints (fixed-price items, minimum values).',
    reference: 'AICPA; ACL Analytics',
  },
  {
    id: 'isc-d8-015',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-systems',
    topic: 'Enterprise Systems',
    subtopic: 'Electronic Data Interchange (EDI)',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Electronic Data Interchange (EDI) is the electronic exchange of business documents between organizations. A key control in an EDI environment is:',
    options: [
      'Requiring hand-signed paper copies',
      'Trading partner agreements that define authorized partners, message formats, security requirements, and dispute resolution procedures, combined with authentication and non-repudiation controls',
      'Using fax machines for backup',
      'Verbal confirmation of each transaction',
    ],
    correctAnswer: 1,
    explanation: 'EDI controls: (1) Trading partner agreements (TPAs) — legal contracts defining: authorized partners, transaction types, message standards (ANSI X12, EDIFACT), security requirements, liability, error handling, dispute resolution, (2) Authentication — verify the identity of the sending party (digital signatures, certificates), (3) Non-repudiation — prevent sender from denying transmission (digital signatures, audit trails), (4) Access controls — restrict EDI transmission/receipt to authorized systems and users, (5) Logging and audit trails — record all transmissions (sent, received, acknowledgments), (6) Functional acknowledgments — receiving system sends automated confirmation of receipt, (7) Exception handling — procedures for rejected or failed transmissions. EDI in modern context: increasingly replaced or supplemented by API-based integrations, but EDI remains prevalent in healthcare (HIPAA X12), retail, manufacturing, and government. Audit focus: verify controls over authorization, completeness, and accuracy of automated transactions.',
    reference: 'AICPA; ISACA',
  },
  {
    id: 'isc-d8-016',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-emerging',
    topic: 'Emerging Technologies',
    subtopic: 'Blockchain for Financial Reporting',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Blockchain technology could impact financial reporting and auditing by:',
    options: [
      'Eliminating all need for financial reporting',
      'Providing an immutable, distributed ledger that enhances transaction transparency and traceability — potentially enabling real-time audit confirmation, reducing reconciliation needs, and creating a verifiable trail of transactions',
      'Making all financial data public',
      'Replacing all databases with spreadsheets',
    ],
    correctAnswer: 1,
    explanation: 'Blockchain in accounting/audit: Potential impacts: (1) Immutable audit trail — once recorded, transactions cannot be altered or deleted (supporting evidence integrity), (2) Smart contracts — self-executing contracts that automatically process transactions when conditions are met (automated revenue recognition, payment processing), (3) Three-way matching — blockchain records enable automated verification across parties, (4) Reduced reconciliation — shared ledger between trading partners eliminates the need to reconcile separate records, (5) Real-time auditing — auditors could access the blockchain in real-time for continuous auditing. Challenges: (1) Garbage in, garbage out — blockchain ensures immutability of records, not accuracy of initial data, (2) Privacy — public blockchains vs. permissioned blockchains for confidential financial data, (3) Scalability — current blockchain throughput limitations, (4) Regulatory uncertainty — accounting standards for crypto-assets still evolving (ASU 2023-08 for crypto measured at fair value), (5) Integration with existing ERP systems.',
    reference: 'AICPA Blockchain; ASU 2023-08',
  },
  {
    id: 'isc-d8-017',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-sdlc',
    topic: 'Systems Development',
    subtopic: 'Project Management',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In IT project management, "scope creep" refers to:',
    options: [
      'Completing the project ahead of schedule',
      'Uncontrolled expansion of the project scope beyond the original objectives — typically caused by poor requirements management, stakeholder additions, or lack of formal change control, leading to budget overruns and delays',
      'Reducing the number of project team members',
      'Improving project documentation',
    ],
    correctAnswer: 1,
    explanation: 'Scope creep: gradual, uncontrolled expansion of project requirements. Causes: (1) Poorly defined initial requirements (ambiguous, incomplete), (2) Stakeholders adding features without formal change process, (3) Developer "gold plating" (adding features not requested), (4) Weak project management oversight. Consequences: (1) Budget overruns — more work costs more, (2) Schedule delays — more scope takes more time, (3) Quality issues — rushed delivery of expanded scope, (4) Team burnout — constantly moving targets. Prevention: (1) Clear requirements documentation (sign-off from stakeholders), (2) Formal change control process — any scope change requires documented request, impact analysis, approval, (3) Project governance — steering committee oversight, (4) Agile approaches — manage scope through prioritized backlogs and sprint commitments. Audit concern: scope creep on financial system implementations can lead to inadequately tested controls and missed deadlines for compliance (e.g., SOX implementations).',
    reference: 'PMI PMBOK; ISACA',
  },
  {
    id: 'isc-d8-018',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-data-management',
    topic: 'Data Management',
    subtopic: 'Data Retention and Destruction',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A data retention policy should specify:',
    options: [
      'That all data should be kept forever',
      'The types of data retained, retention periods based on legal and business requirements, storage locations and methods, access controls during retention, and secure destruction procedures when data reaches end of life',
      'Only the location of backup tapes',
      'That data should be deleted immediately after creation',
    ],
    correctAnswer: 1,
    explanation: 'Data retention policy elements: (1) Classification — categorize data types (financial records, PII, email, contracts) with different retention requirements, (2) Legal requirements — statutory retention periods (IRS requires 7 years for financial records, SOX requires 7 years for audit workpapers), (3) Business requirements — data needed for operations beyond legal minimums, (4) Retention schedule — specific retention periods for each data category, (5) Storage — secure storage during retention (encryption, access controls), (6) Legal holds — suspend normal destruction when litigation is anticipated (e-discovery obligations), (7) Destruction — secure methods (physical shredding for media, cryptographic erasure for encrypted data, degaussing for magnetic media, certificate of destruction), (8) Documentation — records of what was destroyed, when, by whom. Audit focus: (1) Are retention periods compliant with regulations? (2) Is destruction documented? (3) Are legal holds properly managed?',
    reference: 'NIST SP 800-88; IRS Retention Rules',
  },
  {
    id: 'isc-d8-019',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-controls',
    topic: 'Application Controls',
    subtopic: 'Segregation of Duties in IT',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Proper segregation of duties in an IT environment requires separation between:',
    options: [
      'Managers and their assistants',
      'Development, operations (production support), and security administration functions — developers should not have access to production systems, and security administrators should be independent from both',
      'Day shift and night shift employees',
      'Full-time and part-time workers',
    ],
    correctAnswer: 1,
    explanation: 'IT segregation of duties (SoD): Key separations: (1) Development vs Operations — developers should NOT have direct access to production systems or data (prevents unauthorized code changes, data manipulation), (2) Security administration vs development/operations — the person granting access should be independent from those needing access, (3) Database administration vs application programming — DBA manages data; programmers manage applications, (4) IT operations vs end users — operators execute jobs but don\'t initiate transactions. In small IT organizations: compensating controls when SoD is not feasible — (1) Enhanced logging and monitoring, (2) Independent review of change logs, (3) Code review before deployment, (4) Management review of privileged access activity. ERP-specific SoD: role-based access design with SoD conflict monitoring tools. Audit procedures: (1) Review access rights for conflicting roles, (2) Test for users with production access who also have development access, (3) Review activity logs for privileged users.',
    reference: 'PCAOB AS 2201; COBIT',
  },
  {
    id: 'isc-d8-020',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-network',
    topic: 'Network Architecture',
    subtopic: 'Wireless Network Security',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The most secure wireless encryption protocol currently recommended for enterprise Wi-Fi networks is:',
    options: [
      'WEP (Wired Equivalent Privacy)',
      'WPA3-Enterprise — which uses 192-bit encryption, Simultaneous Authentication of Equals (SAE), and Protected Management Frames (PMF) to prevent brute-force attacks and eavesdropping',
      'No encryption (open network)',
      'WPA (first version)',
    ],
    correctAnswer: 1,
    explanation: 'Wireless encryption evolución: (1) WEP — obsolete, easily cracked (uses RC4 with weak IV), (2) WPA — improvement over WEP (TKIP), but still vulnerable, (3) WPA2 — AES-CCMP encryption, mandatory since 2006. Enterprise mode uses 802.1X authentication (RADIUS server), (4) WPA3 — latest standard (2018+). WPA3-Personal: SAE (Dragonfly handshake) replaces pre-shared key exchange, eliminating offline dictionary attacks, forward secrecy. WPA3-Enterprise: 192-bit cryptographic suite (CNSA), mandatory PMF (protects management frames from deauthentication attacks). Additional wireless controls: (1) 802.1X authentication (user/device certificates), (2) Network segmentation (guest Wi-Fi on separate VLAN), (3) Rogue AP detection, (4) Disable SSID broadcasting (minor security), (5) MAC filtering (not strong but supplementary). CPA relevance: weak wireless security could allow unauthorized access to financial systems.',
    reference: 'Wi-Fi Alliance; NIST SP 800-153',
  },
  {
    id: 'isc-d8-021',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-audit',
    topic: 'IT Audit Techniques',
    subtopic: 'Integrated Test Facility',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An Integrated Test Facility (ITF) differs from a test data approach because:',
    options: [
      'ITF does not use test transactions',
      'ITF creates a fictional entity (dummy department, employee, or vendor) within the live production system, processes test transactions alongside real transactions, and then verifies results — whereas test data typically uses a copy of the system',
      'ITF only works with spreadsheets',
      'ITF requires no auditor involvement',
    ],
    correctAnswer: 1,
    explanation: 'ITF (Integrated Test Facility): (1) Setup — create a dummy entity within the production system (fake department, employee, vendor, customer), (2) Processing — submit auditor-designed test transactions targeting the dummy entity; these transactions are processed by the production system alongside real transactions, (3) Verification — compare actual output to expected results to verify processing logic accuracy, (4) Cleanup — reverse/remove test transactions to avoid contaminating production data and financial statements. Advantages: (1) Tests the actual production system (not a copy), (2) Tests concurrent processing with real transactions, (3) Can be run routinely without disrupting operations. Risks: (1) Test data may contaminate production data if not properly removed (e.g., test transactions included in financial totals), (2) Requires careful planning and controls to prevent accidental impact on real data. Comparison: Test data approach uses test transactions on a copy of the system (safer but doesn\'t test the live environment). Parallel simulation uses the auditor\'s program on production data.',
    reference: 'AICPA; IIA Audit Techniques',
  },
  {
    id: 'isc-d8-022',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-systems',
    topic: 'Enterprise Systems',
    subtopic: 'Legacy System Risks',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Legacy systems (older systems still in use) present audit risks including:',
    options: [
      'They are always the most secure systems',
      'Outdated technology that may lack vendor support, security patches, modern access controls, and audit logging capabilities — increasing vulnerability to cyberattacks and complicating integration with newer systems',
      'They are too expensive to operate',
      'They process transactions faster than modern systems',
    ],
    correctAnswer: 1,
    explanation: 'Legacy system risks: (1) End of life/end of support — vendor no longer provides security patches or updates (e.g., Windows Server 2012, older ERP versions), increasing vulnerability to exploits, (2) Limited security controls — older systems may lack modern features: multi-factor authentication, encryption, granular access controls, comprehensive audit logging, (3) Integration challenges — difficulty connecting to modern APIs, cloud services, and compliance tools, (4) Knowledge risk — few staff may understand the legacy codebase (often in older languages like COBOL, RPG), (5) Compliance gaps — may not meet current regulatory requirements (GDPR, PCI DSS), (6) Data quality — older data models may have inconsistencies. Mitigation: (1) Compensating controls — additional monitoring, network segmentation (isolate legacy systems), (2) Migration planning — phased approach to replace/modernize, (3) Virtual patching via WAF or IPS, (4) Enhanced monitoring and logging via SIEM. Audit approach: assess compensating controls, evaluate migration plans, consider as a risk factor.',
    reference: 'ISACA; GAO IT Assessment',
  },
  {
    id: 'isc-d8-023',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-cloud',
    topic: 'Cloud Computing',
    subtopic: 'Multitenancy Risks',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a multi-tenant cloud environment, the primary risk is:',
    options: [
      'Lower costs',
      'Data isolation failure — where a flaw in the cloud architecture could allow one tenant\'s data to be accessed by another tenant, compromising confidentiality of financial and customer data',
      'Better scalability',
      'Increased storage capacity',
    ],
    correctAnswer: 1,
    explanation: 'Multi-tenancy: multiple customers (tenants) share the same cloud infrastructure (compute, storage, network). Risks: (1) Data isolation — logical separation between tenants must be robust; failure could expose one tenant\'s data to another (side-channel attacks, misconfiguraton), (2) Noisy neighbor — one tenant\'s heavy resource usage affects performance for others, (3) Shared vulnerability — a vulnerability in the shared infrastructure could affect all tenants, (4) Compliance concerns — data co-located with other organizations may raise regulatory issues (financial services, healthcare). Controls: (1) Strong logical isolation (separate databases/schemas, encryption with tenant-specific keys), (2) Regular penetration testing by CSP, (3) SOC reports covering multi-tenant controls, (4) Encryption at rest with customer-managed keys (BYOK), (5) Network isolation between tenants (VPC, private endpoints). Audit approach: review CSP\'s SOC 2 report for multi-tenancy controls, especially the security and confidentiality criteria.',
    reference: 'CSA; ENISA Cloud Computing',
  },
  {
    id: 'isc-d8-024',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-databases',
    topic: 'Database Management',
    subtopic: 'Database Audit Trails',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Database audit trails (logging) are important because they:',
    options: [
      'Increase database storage requirements without benefit',
      'Provide a chronological record of who accessed data, what changes were made, when they occurred, and from where — enabling accountability, forensic investigation, and detection of unauthorized data modifications',
      'Prevent all database errors',
      'Automatically fix data quality issues',
    ],
    correctAnswer: 1,
    explanation: 'Database audit trails: (1) What to log: SELECT (read access to sensitive data), INSERT/UPDATE/DELETE (data modifications), DDL changes (schema modifications), login attempts (successful and failed), privilege changes (GRANT/REVOKE), (2) Log contents: timestamp, user identity, action performed, table/object affected, before/after values (for modifications), source IP address, (3) Fine-grained auditing — audit specific columns or conditions (e.g., only log access to salary data), (4) Storage — logs stored separately from the database (prevent tampering), write-once storage or SIEM integration. Benefits: (1) Accountability — trace data changes to specific users, (2) Fraud detection — identify unauthorized modifications to financial data, (3) Compliance — SOX, HIPAA, PCI DSS require audit logging, (4) Forensics — investigate security incidents. CPA relevance: audit trails provide evidence that data integrity is maintained; auditors test whether logging is enabled and reviewed for financial applications.',
    reference: 'AICPA; ISACA DB Controls',
  },
  {
    id: 'isc-d8-025',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-it-governance',
    topic: 'IT Governance',
    subtopic: 'IT Budget and Value Delivery',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'IT value delivery, as defined in COBIT, ensures that:',
    options: [
      'IT spending is minimized regardless of business needs',
      'IT investments deliver the expected benefits to the organization — value is measured by business outcomes achieved, not just technology deployed',
      'All IT projects are completed under budget',
      'IT operates without any budget constraints',
    ],
    correctAnswer: 1,
    explanation: 'IT value delivery (COBIT EDM02: Ensure Benefits Delivery): (1) Benefits realization — IT initiatives must deliver agreed-upon business benefits (revenue growth, cost reduction, risk reduction, competitive advantage), (2) Value measurement — track ROI, NPV, total cost of ownership (TCO), payback period for IT investments, (3) Portfolio management — prioritize IT investments based on strategic alignment and expected value, (4) Cost optimization — IT spending should be optimized (not minimized — underspending can be as harmful as overspending), (5) Benefits register — document expected benefits, assign owners, track realization post-implementation. Common metrics: (1) IT spend as % of revenue, (2) % of IT projects delivering benefits on time, (3) Business satisfaction with IT services, (4) Cost per transaction/user. CPA relevance: understanding IT value delivery helps assess whether IT investments support reliable financial reporting and business operations.',
    reference: 'COBIT 2019 EDM02',
  },
];
