/**
 * CPA REG Section - Questions Depth Batch 9
 * Blueprint Area: REG-V (Federal Taxation of Property Transactions)
 * Topics: §1031 Advanced, §1033 Condemnation, Passive Activity Loss Rules, At-Risk Rules, OID
 */

import { Question } from '../../../types';

export const REG_QUESTIONS_DEPTH_9: Question[] = [
  {
    id: 'reg-d9-001',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-passive',
    topic: 'Passive Activity Loss Rules',
    subtopic: 'Material Participation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §469, a taxpayer materially participates in an activity if the taxpayer satisfies any of the seven tests. Which of the following is one of the material participation tests?',
    options: [
      'The taxpayer invests at least $100,000 in the activity',
      'The taxpayer participates in the activity for more than 500 hours during the taxable year',
      'The taxpayer owns more than 50% of the activity',
      'The taxpayer has held the investment for more than 2 years',
    ],
    correctAnswer: 1,
    explanation: 'Under Treas. Reg. §1.469-5T, a taxpayer materially participates if any of the seven tests is met: (1) more than 500 hours of participation, (2) the taxpayer\'s participation constitutes substantially all participation, (3) at least 100 hours AND no other individual participates more, (4) the activity is a "significant participation activity" and the aggregate of all such activities exceeds 500 hours, (5) the taxpayer materially participated in any 5 of the prior 10 years, (6) the activity is a personal service activity and the taxpayer participated in any 3 prior years, or (7) based on all facts and circumstances, the taxpayer participates on a regular, continuous, and substantial basis.',
    reference: 'IRC §469; Treas. Reg. §1.469-5T',
  },
  {
    id: 'reg-d9-002',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-passive',
    topic: 'Passive Activity Loss Rules',
    subtopic: 'Real Estate Professional Exception',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A taxpayer qualifies as a "real estate professional" under IRC §469(c)(7) and may treat rental real estate losses as nonpassive if:',
    options: [
      'They own at least one rental property',
      'More than 50% of personal services performed during the year are in real property trades or businesses, AND the taxpayer performs more than 750 hours of services in such activities',
      'They earn more than $150,000 from rental activities',
      'They have a real estate license',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §469(c)(7), a taxpayer is a real estate professional if: (1) more than 50% of the personal services performed during the tax year are in real property trades or businesses in which the taxpayer materially participates, AND (2) the taxpayer performs more than 750 hours of services during the year in real property trades or businesses in which they materially participate. If both tests are met, rental real estate activities are not automatically treated as passive, but the taxpayer must still materially participate in each rental activity (or elect to aggregate all rental activities as one). This overrides the general rule that rental activities are per se passive.',
    reference: 'IRC §469(c)(7)',
  },
  {
    id: 'reg-d9-003',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-passive',
    topic: 'Passive Activity Loss Rules',
    subtopic: '$25,000 Rental Loss Allowance',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the special allowance of IRC §469(i), an individual who actively participates in a rental real estate activity may deduct up to $25,000 of rental losses against nonpassive income. This allowance is phased out:',
    options: [
      'For taxpayers with AGI above $50,000',
      'By 50% of the amount by which AGI exceeds $100,000, and is fully eliminated at $150,000 AGI',
      'For taxpayers with AGI above $200,000',
      'It is never phased out',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §469(i), the $25,000 special allowance for rental real estate losses permits active participants (a lower standard than material participation) to deduct up to $25,000 of rental losses against nonpassive income. The allowance is phased out by 50 cents for each dollar of AGI exceeding $100,000, so it is fully eliminated at $150,000 AGI. For married filing separately (living apart for the entire year), the allowance is $12,500 and begins phasing out at $50,000 AGI. This allowance also applies to the low-income housing credit and rehabilitation credit, with a $25,000 equivalent.',
    reference: 'IRC §469(i)',
  },
  {
    id: 'reg-d9-004',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-at-risk',
    topic: 'At-Risk Rules',
    subtopic: 'Amounts At Risk',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the at-risk rules of IRC §465, a taxpayer\'s amount at risk includes:',
    options: [
      'All borrowed amounts regardless of recourse',
      'Cash and adjusted basis of property contributed to the activity, plus amounts borrowed for which the taxpayer is personally liable (recourse) or has pledged property as security (excluding property used in the activity)',
      'Only cash invested in the activity',
      'The fair market value of all assets in the activity',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §465, the amount at risk includes: (1) cash contributed, (2) adjusted basis of property contributed, (3) amounts borrowed for which the taxpayer is personally liable (recourse debt), and (4) amounts borrowed secured by property NOT used in the activity. Nonrecourse financing is generally NOT included in the at-risk amount, except for qualified nonrecourse financing secured by real property used in the activity (from qualified lenders or government entities). Losses deductible are limited to the amount at risk; excess losses are suspended and carried forward.',
    reference: 'IRC §465',
  },
  {
    id: 'reg-d9-005',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1031',
    topic: 'Like-Kind Exchanges',
    subtopic: 'Reverse Exchanges',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a reverse like-kind exchange, the replacement property is acquired before the relinquished property is transferred. This is permitted if:',
    options: [
      'Both properties are exchanged on the same day',
      'A qualified exchange accommodation arrangement (QEAA) is used, and the parked property is transferred within 180 days',
      'The buyer agrees to hold the property for the taxpayer',
      'Reverse exchanges are not permitted under any circumstances',
    ],
    correctAnswer: 1,
    explanation: 'Under Revenue Procedure 2000-37, a reverse exchange is permitted through a Qualified Exchange Accommodation Arrangement (QEAA). An exchange accommodation titleholder (EAT) acquires and "parks" either the replacement property or the relinquished property. The taxpayer must identify the relinquished property within 45 days of the EAT acquiring the replacement property, and the exchange must be completed within 180 days. The EAT must hold the property under a written agreement, and the taxpayer cannot have owned the parked property at any time during the arrangement. This safe harbor eliminates the risk of the IRS challenging the exchange.',
    reference: 'Rev. Proc. 2000-37',
  },
  {
    id: 'reg-d9-006',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-oid',
    topic: 'Original Issue Discount',
    subtopic: 'OID Inclusion',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Original issue discount (OID) on a bond is:',
    options: [
      'Recognized entirely in the year of purchase',
      'Included in the holder\'s gross income annually over the life of the bond using the constant yield method, even though no cash is received until maturity',
      'Tax-exempt until the bond matures',
      'Deductible by the holder',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1272, OID (the excess of a bond\'s stated redemption price at maturity over its issue price) must be included in the holder\'s gross income annually over the life of the bond using the constant yield (effective interest) method. This is sometimes called "phantom income" because the holder must report income without receiving cash. As OID is included in income, the holder\'s basis in the bond increases by the same amount. OID rules do not apply to tax-exempt bonds, U.S. savings bonds (if election made), or bonds with de minimis OID (less than 0.25% × years to maturity × stated redemption price).',
    reference: 'IRC §§1271-1275',
  },
  {
    id: 'reg-d9-007',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1244',
    topic: 'Small Business Stock',
    subtopic: '§1244 Stock Loss',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §1244, losses on the sale of qualified small business stock are treated as:',
    options: [
      'Capital losses subject to the $3,000 annual limit',
      'Ordinary losses up to $50,000 ($100,000 for married filing jointly) per year, with excess treated as capital loss',
      'Nondeductible losses',
      'Passive activity losses',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1244, losses on the disposition of qualified small business stock are treated as ordinary losses (rather than capital losses) up to $50,000 per year ($100,000 for married filing jointly). Excess losses are treated as capital losses. To qualify: (1) the stock must be issued by a domestic small business corporation with aggregate capital of $1 million or less at the time of issuance, (2) the stock must be issued for money or property (not services or other stock), (3) the taxpayer must be the original holder (not a transferee), and (4) the corporation must derive more than 50% of gross receipts from active business operations during the prior 5 years.',
    reference: 'IRC §1244',
  },
  {
    id: 'reg-d9-008',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1202',
    topic: 'Qualified Small Business Stock',
    subtopic: '§1202 Exclusion',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §1202, a noncorporate taxpayer who holds qualified small business stock (QSBS) for more than 5 years may exclude:',
    options: [
      '50% of gain',
      '100% of gain (for stock acquired after September 27, 2010), subject to the greater of $10 million or 10 times the adjusted basis of the stock',
      '75% of gain',
      '25% of gain',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1202, as amended by the PATH Act, a noncorporate taxpayer may exclude 100% of gain from the sale of QSBS acquired after September 27, 2010, and held for more than 5 years. The exclusion is limited to the greater of $10 million of gain or 10 times the taxpayer\'s adjusted basis in the stock. To qualify: (1) the stock must be in a C corporation with aggregate gross assets of $50 million or less at the time of issuance, (2) the corporation must use at least 80% of assets in active qualified trades or businesses (excluding certain professional services, banking, hospitality, and farming), (3) the stock must be acquired at original issuance for money, property, or services.',
    reference: 'IRC §1202',
  },
  {
    id: 'reg-d9-009',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-passive',
    topic: 'Passive Activity Loss Rules',
    subtopic: 'Disposition of Passive Activity',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a taxpayer disposes of an entire interest in a passive activity in a fully taxable transaction:',
    options: [
      'Suspended losses are permanently disallowed',
      'All suspended passive activity losses from that activity are released and may be deducted against any income (passive or nonpassive)',
      'Suspended losses can only offset future passive income',
      'Suspended losses are carried over to the buyer',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §469(g)(1), when a taxpayer makes a fully taxable disposition of an entire interest in a passive activity, all previously suspended passive activity losses from that activity are released and may be deducted in full against any type of income (ordinary, capital, passive, or nonpassive). The losses are first applied against net income or loss from the activity in the year of disposition, then against net income or loss from all other passive activities, and finally against nonpassive income. A "fully taxable" disposition means the entire interest is disposed of in a transaction where gain or loss is fully recognized (not a gift, related party sale under §267, or installment sale).',
    reference: 'IRC §469(g)(1)',
  },
  {
    id: 'reg-d9-010',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-related-party',
    topic: 'Related Party Transactions',
    subtopic: 'Constructive Ownership §318',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the constructive ownership rules of IRC §318, an individual is deemed to own stock owned by:',
    options: [
      'Siblings, aunts, uncles, and cousins',
      'Spouse, children, grandchildren, and parents (but NOT siblings) — plus entity attribution from/to partnerships, estates, trusts, and corporations',
      'All blood relatives',
      'Only the individual\'s spouse',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §318(a), stock ownership is attributed from/to: (1) FAMILY — spouse, children, grandchildren, and parents (NOT siblings, aunts, uncles, or cousins); (2) PARTNERSHIPS — proportionate attribution between partner and partnership; (3) ESTATES/TRUSTS — beneficiary owns proportionate share, and entity owns beneficiary\'s share; (4) CORPORATIONS — attribution from 50%+ shareholders to corporation and from corporation to 50%+ shareholders (proportionate). The §318 rules apply for purposes of stock redemptions (§302), constructive dividends (§304), controlled groups (§1563), and other provisions. Note: §267 (related party loss disallowance) uses DIFFERENT attribution rules that include siblings.',
    reference: 'IRC §318(a)',
  },
  {
    id: 'reg-d9-011',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Section 1231 Property Definition',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Section 1231 property includes:',
    options: [
      'Personal-use assets such as a personal residence',
      'Depreciable property and real property used in a trade or business and held for more than one year',
      'Inventory held for sale to customers',
      'Stocks and bonds held for investment',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1231(b), §1231 property includes depreciable property and real property used in a trade or business and held for more than one year. This specifically EXCLUDES: (1) inventory or property held primarily for sale to customers, (2) copyrights, literary/musical compositions held by the creator, (3) U.S. government publications. Section 1231 provides beneficial treatment: net §1231 gains are treated as long-term capital gains (favorable rates), while net §1231 losses are treated as ordinary losses (fully deductible). Personal-use assets are capital assets, not §1231 property.',
    reference: 'IRC §1231(b)',
  },
  {
    id: 'reg-d9-012',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-installment',
    topic: 'Installment Sales',
    subtopic: 'Depreciation Recapture in Installment Sales',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When §1245 property is sold on the installment method, the §1245 recapture income is:',
    options: [
      'Spread proportionately over the installment payments',
      'Recognized in full in the year of sale, regardless of the amount of payments received that year',
      'Deferred until the final payment is received',
      'Converted to capital gain',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §453(i), all depreciation recapture (§1245 and §1250) must be recognized in full in the year of sale, even if the installment method is used for the remaining gain. The recapture amount is added to the selling price payments received in the year of sale for purposes of computing gain. Only the §1231 gain (gain in excess of recapture) can be reported on the installment method. Example: if a machine sold for $100,000 has $40,000 of §1245 recapture and $20,000 of §1231 gain, the $40,000 recapture is fully recognized in year 1, while the $20,000 §1231 gain is spread over the installment period.',
    reference: 'IRC §453(i)',
  },
  {
    id: 'reg-d9-013',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-gift-basis',
    topic: 'Basis of Gifted Property',
    subtopic: 'Gift Tax Adjustment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When property is gifted and the donor pays gift tax, the donee\'s basis includes an adjustment for gift tax paid. The adjustment is:',
    options: [
      'The full amount of gift tax paid',
      'The portion of gift tax attributable to the net appreciation in the property (the excess of FMV over the donor\'s basis at the time of gift)',
      'Zero — gift tax never affects basis',
      '50% of the gift tax paid',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1015(d)(6), for gifts made after 1976, the donee\'s basis is increased by the portion of gift tax paid that is attributable to the net appreciation in the property. The formula is: basis increase = gift tax paid × (net appreciation ÷ amount of gift). Net appreciation = FMV at date of gift − donor\'s adjusted basis. However, the total basis (donor\'s basis + gift tax adjustment) cannot exceed the FMV at the date of gift. For gifts made before 1977, the entire gift tax paid was added to basis (not limited to the appreciation portion).',
    reference: 'IRC §1015(d)(6)',
  },
  {
    id: 'reg-d9-014',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1031',
    topic: 'Like-Kind Exchanges',
    subtopic: 'Mortgage Boot',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a like-kind exchange, a taxpayer transfers property with a $200,000 mortgage and receives property with a $150,000 mortgage. Regarding the mortgage differences:',
    options: [
      'Mortgages are ignored in like-kind exchanges',
      'The taxpayer is treated as receiving $50,000 of "mortgage boot" (net debt relief), which triggers gain recognition to the extent of the lesser of boot or realized gain',
      'The taxpayer must pay $50,000 in cash to avoid gain recognition',
      'Both properties must have equal mortgages',
    ],
    correctAnswer: 1,
    explanation: 'In a like-kind exchange, if the taxpayer is relieved of a larger mortgage than assumed, the net debt relief is treated as boot received. Here, the taxpayer transferred a $200,000 mortgage (relief) and assumed a $150,000 mortgage, resulting in net mortgage boot of $50,000 ($200,000 − $150,000). This $50,000 of boot triggers gain recognition equal to the lesser of the boot or the realized gain. The taxpayer could offset mortgage boot by paying additional cash — cash given can offset mortgage boot received (but mortgage boot given cannot offset cash boot received under the netting rules of Treas. Reg. §1.1031(b)-1).',
    reference: 'Treas. Reg. §1.1031(b)-1; §1.1031(d)-2',
  },
  {
    id: 'reg-d9-015',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Worthless Securities',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §165(g), a loss from a security that becomes completely worthless is treated as:',
    options: [
      'An ordinary loss deductible in full',
      'A capital loss deemed to have occurred on the last day of the taxable year in which the security became worthless',
      'A casualty loss',
      'A nondeductible personal loss',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §165(g), if a security (stock or bond) becomes completely worthless during the taxable year, the loss is treated as a capital loss deemed to occur on the LAST DAY of the taxable year. This timing rule matters for determining whether the loss is short-term or long-term based on the holding period. The taxpayer must demonstrate that the security became completely worthless during the year (partial worthlessness is generally not deductible for securities). A special 7-year statute of limitations applies for refund claims related to worthless securities (§6511(d)(1)).',
    reference: 'IRC §165(g)',
  },
  {
    id: 'reg-d9-016',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-121',
    topic: 'Sale of Principal Residence',
    subtopic: 'Nonqualified Use',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §121(b)(5), gain from the sale of a principal residence that was used as rental or investment property (nonqualified use) before becoming the taxpayer\'s principal residence:',
    options: [
      'Is fully excludable under §121',
      'Must be allocated between qualified and nonqualified use — the portion attributable to nonqualified use periods after 2008 is not eligible for the §121 exclusion',
      'Is completely taxable',
      'Is deferred under §1031',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §121(b)(5), enacted by the Housing Assistance Tax Act of 2008, gain from the sale of a principal residence must be allocated between periods of qualified use (as principal residence) and nonqualified use (any other use, such as rental). The gain attributable to nonqualified use AFTER January 1, 2009 does not qualify for the §121 exclusion. However, certain periods are NOT treated as nonqualified use: (1) any period AFTER the last use as a principal residence, (2) temporary absences of up to 2 years, (3) military service absences up to 10 years. Nonqualified use BEFORE the property becomes a principal residence generates nonexcludable gain.',
    reference: 'IRC §121(b)(5)',
  },
  {
    id: 'reg-d9-017',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-at-risk',
    topic: 'At-Risk Rules',
    subtopic: 'Qualified Nonrecourse Financing',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the at-risk rules, qualified nonrecourse financing is included in the taxpayer\'s at-risk amount. To qualify, the financing must be:',
    options: [
      'From any lender, secured by any property',
      'Secured by real property used in the activity, borrowed from a qualified lender (bank, government, or unrelated person regularly in the lending business), and no person is personally liable',
      'From a related party',
      'Unsecured financing from a commercial bank',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §465(b)(6), qualified nonrecourse financing is an exception to the general rule that nonrecourse debt is excluded from the at-risk amount. To qualify: (1) the financing must be secured by real property used in the activity, (2) the lender must be a "qualified person" — a bank, savings institution, government entity, or person regularly engaged in the lending business (excluding the seller or a person related to the seller), (3) no person may be personally liable for repayment. This exception ensures that typical commercial real estate lending (mortgages on real property from institutional lenders) is included in the at-risk amount.',
    reference: 'IRC §465(b)(6)',
  },
  {
    id: 'reg-d9-018',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Capital Asset Definition',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following is NOT a capital asset under IRC §1221?',
    options: [
      'Personal-use automobile',
      'Inventory or property held primarily for sale to customers in the ordinary course of business',
      'Stock held for investment',
      'Jewelry held for personal use',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1221(a), a capital asset is defined as ALL property held by the taxpayer EXCEPT: (1) inventory or property held primarily for sale to customers, (2) depreciable property and real property used in a trade or business (these are §1231 property instead), (3) copyrights, literary, or artistic compositions held by the creator (or certain donees), (4) accounts or notes receivable from services or inventory sales, (5) U.S. government publications received below normal cost, (6) commodities derivative financial instruments held by dealers, (7) hedging transactions, and (8) supplies used in business. Personal-use items (auto, jewelry, furniture) and investment property (stocks, bonds) ARE capital assets.',
    reference: 'IRC §1221(a)',
  },
  {
    id: 'reg-d9-019',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-related-party',
    topic: 'Related Party Transactions',
    subtopic: 'Constructive Sale §1259',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §1259, a "constructive sale" requiring immediate gain recognition occurs when a taxpayer holding an appreciated financial position enters into:',
    options: [
      'Any hedging transaction',
      'A short sale of the same or substantially identical property, an offsetting notional principal contract, or a futures/forward contract to deliver the same or substantially identical property',
      'A covered call option',
      'A purchase of a put option',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1259, a constructive sale occurs when a taxpayer holding an appreciated financial position enters into certain transactions that eliminate substantially all risk of loss and opportunity for gain. These include: (1) a short sale of the same or substantially identical property, (2) an offsetting notional principal contract with respect to the same or substantially identical property, and (3) a futures or forward contract to deliver the same or substantially identical property. The constructive sale triggers recognition of gain as if the position were sold at FMV. An exception exists if the offsetting position is closed within 30 days and the original position is held for 60 more days.',
    reference: 'IRC §1259',
  },
  {
    id: 'reg-d9-020',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-oid',
    topic: 'Market Discount Bonds',
    subtopic: 'Market Discount Inclusion',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a taxpayer purchases a bond at a market discount (below the bond\'s stated redemption price or adjusted issue price), the market discount recognized on disposition is treated as:',
    options: [
      'Capital gain',
      'Ordinary income to the extent of accrued market discount',
      'Tax-exempt income',
      'A reduction in basis',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1276, gain recognized on the disposition of a market discount bond is treated as ordinary income to the extent of the accrued market discount. Market discount accrues ratably (straight-line) or, at the taxpayer\'s election, under the constant yield method. The taxpayer may also elect to include market discount in income currently (§1278(b)) rather than deferring it to disposition. If the election is made, the bond\'s basis is increased by the amount included. The market discount rules apply to bonds acquired after April 30, 1993. De minimis market discount (less than 0.25% × remaining years to maturity × stated redemption price) is disregarded.',
    reference: 'IRC §§1276-1278',
  },
  {
    id: 'reg-d9-021',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-passive',
    topic: 'Passive Activity Loss Rules',
    subtopic: 'Grouping Activities',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §469 and the regulations, a taxpayer may group multiple trade or business activities into a single activity for passive activity purposes if:',
    options: [
      'The activities are in different geographic locations',
      'The activities form an appropriate economic unit based on facts and circumstances, considering factors such as similarities in business types, common control, organizational interdependence, and geographic proximity',
      'The taxpayer simply elects to group them',
      'All activities are passive',
    ],
    correctAnswer: 1,
    explanation: 'Under Treas. Reg. §1.469-4, one or more trade or business activities or rental activities may be treated as a single activity if they constitute an appropriate economic unit for measuring gain or loss. Factors include: (1) similarities and differences in types of trades or businesses, (2) the extent of common control, (3) the extent of common ownership, (4) geographic location, and (5) interdependencies between activities. However, a rental activity and a non-rental activity generally cannot be grouped together unless they form an appropriate economic unit and the rental is insubstantial, the non-rental is insubstantial, or the activities are owned through the same §469(c)(3)(B) entity. Once made, a grouping election is generally binding.',
    reference: 'Treas. Reg. §1.469-4',
  },
  {
    id: 'reg-d9-022',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1245',
    topic: 'Depreciation Recapture',
    subtopic: 'Exceptions to §1245 Recapture',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Section 1245 depreciation recapture does NOT apply to which of the following dispositions?',
    options: [
      'Sale to an unrelated party at a gain',
      'Transfers at death (the heir receives a stepped-up basis, and no recapture occurs)',
      'Exchange of §1245 property in a taxable transaction',
      'Abandonment of §1245 property',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1245(b), certain dispositions are exempt from §1245 recapture: (1) transfers at death — the heir receives a stepped-up basis under §1014, and no depreciation recapture occurs; (2) gifts — the donee takes a carryover basis and will face recapture on later sale; (3) certain tax-free exchanges (§351, §721, §1031) — recapture is deferred but not eliminated; (4) charitable contributions — the deduction is reduced instead of recapture. For §1031 exchanges, recapture applies to any boot received. The death exemption from recapture is one of the most significant tax benefits of the stepped-up basis rule.',
    reference: 'IRC §1245(b)',
  },
  {
    id: 'reg-d9-023',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-installment',
    topic: 'Installment Sales',
    subtopic: 'Related Party Resale Rule',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §453(e), if a taxpayer sells property to a related party on the installment method, and the related party resells the property within 2 years:',
    options: [
      'No additional tax consequences arise',
      'The original seller must recognize the remaining deferred gain on the date of the related party\'s resale, to the extent of the proceeds from the second sale',
      'The related party must pay the original seller\'s tax',
      'The original installment sale is automatically voided',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §453(e), when property is sold to a related party on installments and the related party resells within 2 years, the amount realized on the second sale is treated as received by the original seller as of the second sale date. This acceleration rule is designed to prevent using installment sales to related parties as a device to defer gain while the related party immediately receives cash. Exceptions exist for: (1) involuntary conversions, (2) dispositions after the death of the seller or buyer, and (3) sales where the taxpayer can demonstrate that neither transaction had tax avoidance as one of its principal purposes. The 2-year period does not apply to marketable securities.',
    reference: 'IRC §453(e)',
  },
  {
    id: 'reg-d9-024',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains Tax Rates',
    subtopic: 'Preferential Rates',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For 2024, the maximum tax rate on net long-term capital gains for individuals (other than collectibles and unrecaptured §1250 gain) is:',
    options: [
      '15%',
      '20% (for taxpayers in the highest income bracket)',
      '25%',
      '28%',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1(h), the maximum tax rate on adjusted net capital gain (net LTCG minus collectibles gain and unrecaptured §1250 gain) is: (1) 0% for taxpayers in the lower brackets (taxable income up to $47,025 single / $94,050 MFJ for 2024), (2) 15% for middle brackets, and (3) 20% for taxpayers with taxable income exceeding $518,900 single / $583,750 MFJ for 2024. The 3.8% NIIT under §1411 may also apply, bringing the maximum effective rate on LTCG to 23.8%. Collectibles are taxed at max 28%, and unrecaptured §1250 gain at max 25%.',
    reference: 'IRC §1(h)',
  },
  {
    id: 'reg-d9-025',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1033',
    topic: 'Involuntary Conversions',
    subtopic: 'Severance Damages',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a government condemns part of a taxpayer\'s property and pays severance damages for the decline in value of the retained portion:',
    options: [
      'Severance damages are always taxable as ordinary income',
      'Severance damages reduce the basis of the retained property; if they exceed the basis, the excess is recognized as gain (which may qualify for §1033 deferral)',
      'Severance damages are tax-free',
      'The entire property is treated as condemned',
    ],
    correctAnswer: 1,
    explanation: 'When a government condemns part of a property, the condemnation proceeds for the condemned portion follow normal §1033 rules. However, severance damages — compensation for the decline in value of the retained portion — are treated differently: they reduce the basis of the retained property. If severance damages exceed the adjusted basis of the retained property, the excess is recognized as gain. The gain from excess severance damages may be eligible for §1033 deferral if the taxpayer reinvests the proceeds. Special restoration payments (used to restore the retained property) are offset against the severance damages rather than reducing basis.',
    reference: 'Rev. Rul. 68-37; IRC §1033',
  },
];
