/**
 * CPA REG Section - Questions Depth Batch 8
 * Blueprint Area: REG-V (Federal Taxation of Property Transactions)
 * Topics: Like-Kind Exchanges §1031, Involuntary Conversions §1033, Installment Sales, Gain Exclusions
 */

import { Question } from '../../../types';

export const REG_QUESTIONS_DEPTH_8: Question[] = [
  {
    id: 'reg-d8-001',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1031',
    topic: 'Like-Kind Exchanges',
    subtopic: 'Qualifying Property',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §1031 as amended by the TCJA, like-kind exchange treatment is available for:',
    options: [
      'Any property held for productive use or investment, including personal property and real property',
      'Real property held for productive use in a trade or business or for investment only',
      'Stock, bonds, and partnership interests',
      'Inventory and dealer property',
    ],
    correctAnswer: 1,
    explanation: 'After the Tax Cuts and Jobs Act (effective for exchanges after December 31, 2017), IRC §1031 applies ONLY to real property held for productive use in a trade or business or for investment. Personal property (equipment, vehicles, artwork, collectibles) no longer qualifies. Additionally, stock, bonds, notes, partnership interests, inventory, and property held primarily for sale are specifically excluded. Real property includes land, buildings, and structural components. Foreign real property and domestic real property are NOT like-kind to each other.',
    reference: 'IRC §1031(a)',
  },
  {
    id: 'reg-d8-002',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1031',
    topic: 'Like-Kind Exchanges',
    subtopic: 'Boot Recognition',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In a like-kind exchange, if a taxpayer receives both like-kind property and $30,000 cash (boot), the taxpayer must:',
    options: [
      'Defer all gain',
      'Recognize gain equal to the lesser of the realized gain or the boot received ($30,000)',
      'Recognize the entire realized gain',
      'Pay tax on the FMV of the like-kind property received',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1031(b), if boot (cash or non-like-kind property) is received in an otherwise qualifying like-kind exchange, gain is recognized to the extent of the boot received, but limited to the total realized gain. In other words: recognized gain = lesser of (boot received) or (realized gain). Loss is never recognized in a like-kind exchange, even if boot is received (§1031(c)). The basis of the new property is calculated as: FMV of new property − deferred gain (or + deferred loss).',
    reference: 'IRC §1031(b)(c)',
  },
  {
    id: 'reg-d8-003',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1031',
    topic: 'Like-Kind Exchanges',
    subtopic: 'Deferred Exchange Timelines',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'In a deferred (Starker) like-kind exchange, the replacement property must be identified within what time period, and the exchange must be completed within what time period?',
    options: [
      'Identified within 30 days and completed within 90 days',
      'Identified within 45 days and completed within 180 days (or the due date of the tax return, including extensions, if earlier)',
      'Identified within 60 days and completed within 1 year',
      'Identified within 90 days and completed within 2 years',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1031(a)(3) and Treas. Reg. §1.1031(k)-1, in a deferred exchange: (1) the replacement property must be identified in writing within 45 days after the transfer of the relinquished property, and (2) the replacement property must be received within the earlier of 180 days after the transfer or the due date (including extensions) of the taxpayer\'s return for the year of the transfer. The taxpayer may identify up to 3 properties regardless of value (3-property rule) or any number of properties if their aggregate FMV does not exceed 200% of the relinquished property\'s FMV (200% rule).',
    reference: 'IRC §1031(a)(3); Treas. Reg. §1.1031(k)-1',
  },
  {
    id: 'reg-d8-004',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1033',
    topic: 'Involuntary Conversions',
    subtopic: 'Replacement Period',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §1033, a taxpayer who receives insurance proceeds from the involuntary conversion of property generally must replace the property within:',
    options: [
      '1 year from the end of the tax year in which gain is first realized',
      '2 years from the close of the first taxable year in which any part of the gain is realized (3 years for real property condemned by a government)',
      '180 days from the date of the conversion',
      '5 years from the conversion',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1033(a)(2)(B), the replacement period for involuntary conversions ends 2 years after the close of the first taxable year in which any part of the gain upon the conversion is realized. For real property (including real property held for business or investment) condemned or sold under threat of condemnation, the replacement period is extended to 3 years. The replacement property must be similar or related in service or use (a narrower standard than like-kind). For condemned real property used in business or held for investment, the broader like-kind standard applies.',
    reference: 'IRC §1033(a)(2)(B); §1033(g)',
  },
  {
    id: 'reg-d8-005',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-installment',
    topic: 'Installment Sales',
    subtopic: 'Gross Profit Percentage',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A taxpayer sells property for $200,000, with an adjusted basis of $120,000 and selling expenses of $10,000. The buyer pays $40,000 down and will pay the remaining $160,000 in installments. The gross profit percentage is:',
    options: [
      '40%',
      '35%',
      '60%',
      '80%',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §453, the gross profit percentage = gross profit ÷ contract price. Gross profit = selling price − adjusted basis − selling expenses = $200,000 − $120,000 − $10,000 = $70,000. Contract price = selling price = $200,000. Gross profit percentage = $70,000 ÷ $200,000 = 35%. Each installment received is multiplied by this percentage to determine the gain recognized: $40,000 × 35% = $14,000 recognized in year 1. The remaining $160,000 × 35% = $56,000 gain recognized over the installment period.',
    reference: 'IRC §453',
  },
  {
    id: 'reg-d8-006',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-installment',
    topic: 'Installment Sales',
    subtopic: 'Ineligible Property',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Which of the following types of property is NOT eligible for installment sale reporting under IRC §453?',
    options: [
      'Rental real estate sold at a gain',
      'Dealer property (inventory or property held for sale to customers in the ordinary course of business)',
      'Vacant land held for investment',
      'A business building sold at a gain',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §453(b)(2), the installment method is NOT available for: (1) sales of inventory or property held for sale to customers (dealer dispositions), (2) sales of depreciable property to related parties (§453(g)), (3) sales of publicly traded stocks and securities, and (4) sales resulting in a loss (installment method applies only to gains). Additionally, all depreciation recapture (§1245/§1250) must be recognized in full in the year of sale regardless of installments received. The installment method is the default for qualifying sales — taxpayers must elect out if they want to recognize all gain in the year of sale.',
    reference: 'IRC §453(b)(2); §453(g)',
  },
  {
    id: 'reg-d8-007',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1245',
    topic: 'Depreciation Recapture',
    subtopic: 'Section 1245 Property',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Section 1245 recapture requires that on the disposition of §1245 property at a gain:',
    options: [
      'All gain is treated as capital gain',
      'Gain is treated as ordinary income to the extent of all depreciation previously allowed or allowable, with any remaining gain treated as §1231 gain',
      'Only straight-line depreciation is recaptured',
      'Gain is always treated as §1231 gain',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1245(a), when §1245 property (personal property, certain real property placed in service before 1987, and §179 property) is sold at a gain, gain is treated as ordinary income to the extent of ALL depreciation (including §179 and bonus depreciation) previously allowed or allowable. Any gain in excess of the total depreciation taken is treated as §1231 gain (potentially long-term capital gain). Section 1245 applies to tangible personal property (machinery, equipment, vehicles) and certain intangibles (patents, copyrights). Unlike §1250, §1245 recaptures ALL depreciation, not just excess depreciation.',
    reference: 'IRC §1245(a)',
  },
  {
    id: 'reg-d8-008',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1250',
    topic: 'Depreciation Recapture',
    subtopic: 'Section 1250 and Unrecaptured §1250 Gain',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a taxpayer sells §1250 real property (e.g., a building depreciated using the straight-line method), the depreciation recapture is:',
    options: [
      'All depreciation is recaptured as ordinary income under §1250',
      'Under current law, §1250 recapture of excess depreciation is usually zero (since straight-line is required), but the gain attributable to straight-line depreciation is taxed as "unrecaptured §1250 gain" at a maximum rate of 25%',
      'Depreciation is not recaptured on real property',
      'All gain is taxed at 15% capital gain rate',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1250, recapture as ordinary income applies only to the excess of accelerated depreciation over straight-line depreciation. Since MACRS requires straight-line depreciation for real property placed in service after 1986, the §1250 recapture is usually zero. However, under IRC §1(h)(1)(E), the gain attributable to straight-line depreciation on real property (called "unrecaptured §1250 gain") is taxed at a maximum rate of 25% (rather than the regular 15%/20% LTCG rate). Any remaining gain above total depreciation is regular §1231 gain eligible for the standard LTCG rate.',
    reference: 'IRC §1250; IRC §1(h)(1)(E)',
  },
  {
    id: 'reg-d8-009',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-related-party',
    topic: 'Related Party Transactions',
    subtopic: 'Loss Disallowance §267',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §267, a loss on the sale of property between related parties is:',
    options: [
      'Deductible in full',
      'Disallowed to the seller, but the buyer may use the disallowed loss to offset gain on a subsequent sale of the property to an unrelated party',
      'Deferred until the property is sold to an unrelated party',
      'Permanently disallowed with no benefit to either party',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §267(a)(1), losses on sales between related parties (as defined in §267(b) — siblings, spouses, ancestors, lineal descendants, controlled entities, etc.) are disallowed to the seller. However, under §267(d), the buyer receives a partial benefit: if the buyer subsequently sells the property at a gain to an unrelated party, the gain is reduced (but not below zero) by the previously disallowed loss. If the buyer sells at a loss, the disallowed loss provides no benefit. Related parties under §267 include family members, a corporation and its >50% owner, and commonly controlled entities.',
    reference: 'IRC §267(a)(1); §267(d)',
  },
  {
    id: 'reg-d8-010',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-121',
    topic: 'Sale of Principal Residence',
    subtopic: 'Exclusion Requirements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under IRC §121, a taxpayer may exclude up to what amount of gain from the sale of a principal residence?',
    options: [
      '$125,000 for single filers',
      '$250,000 for single filers ($500,000 for married filing jointly if both spouses meet the requirements)',
      '$500,000 for all filers',
      '$1,000,000 for married filing jointly',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §121, a taxpayer may exclude up to $250,000 of gain ($500,000 for married filing jointly if both spouses meet the use test) from the sale of a principal residence if: (1) the taxpayer owned the home for at least 2 of the last 5 years (ownership test), and (2) the taxpayer used the home as a principal residence for at least 2 of the last 5 years (use test). The exclusion may be used only once every 2 years. A reduced exclusion is available if the taxpayer fails to meet the full requirements due to a change in employment, health, or unforeseen circumstances.',
    reference: 'IRC §121',
  },
  {
    id: 'reg-d8-011',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-wash-sale',
    topic: 'Wash Sales',
    subtopic: 'Wash Sale Rule',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the wash sale rule of IRC §1091, a loss on the sale of stock or securities is disallowed if substantially identical securities are purchased within:',
    options: [
      '15 days before or after the sale',
      '30 days before or 30 days after the sale (a 61-day window)',
      '60 days after the sale only',
      '90 days before or after the sale',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1091, a loss on the sale of stock or securities is disallowed if the taxpayer acquires (or enters into a contract to acquire) substantially identical stock or securities within 30 days before or 30 days after the sale date (creating a 61-day window: 30 days before + sale date + 30 days after). The disallowed loss is added to the basis of the replacement securities, effectively deferring (not permanently disallowing) the loss. The holding period of the replacement securities includes the holding period of the securities sold.',
    reference: 'IRC §1091',
  },
  {
    id: 'reg-d8-012',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1231',
    topic: 'Section 1231 Assets',
    subtopic: '5-Year Lookback Rule',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the §1231 lookback rule, net §1231 gains are recharacterized as ordinary income to the extent of:',
    options: [
      'Prior year §1231 gains not offset by losses',
      'Unrecaptured net §1231 losses from the prior 5 tax years that have not been applied against net §1231 gains',
      'All prior year depreciation deductions',
      'The accumulated earnings of the taxpayer',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1231(c), the lookback rule requires net §1231 gains to be recharacterized as ordinary income to the extent of unrecaptured net §1231 losses from the prior 5 taxable years. The purpose is to prevent selective recognition — without the lookback, a taxpayer could obtain ordinary loss treatment in one year and capital gain treatment in another. Net §1231 losses in a year are fully deductible as ordinary losses. If the taxpayer has net §1231 gain in a subsequent year, it is treated as ordinary income to the extent of the unrecaptured §1231 losses from the prior 5 years. Once recaptured, those losses are no longer subject to the lookback.',
    reference: 'IRC §1231(c)',
  },
  {
    id: 'reg-d8-013',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Net Capital Loss Limitations',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For an individual taxpayer, net capital losses in excess of capital gains may offset ordinary income up to:',
    options: [
      '$1,000 per year',
      '$3,000 per year ($1,500 for married filing separately)',
      '$5,000 per year',
      'There is no limit — all capital losses offset ordinary income',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1211(b), individual taxpayers may deduct net capital losses against ordinary income up to $3,000 per year ($1,500 for married filing separately). Any excess net capital loss is carried forward indefinitely and retains its character as short-term or long-term. Corporations, by contrast, cannot deduct net capital losses against ordinary income at all — they may only carry capital losses back 3 years and forward 5 years to offset capital gains.',
    reference: 'IRC §1211(b); §1212(b)',
  },
  {
    id: 'reg-d8-014',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1031',
    topic: 'Like-Kind Exchanges',
    subtopic: 'Basis Calculation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A taxpayer exchanges an office building (adjusted basis $300,000, FMV $500,000) for another office building (FMV $450,000) plus $50,000 cash. The taxpayer\'s basis in the new building is:',
    options: [
      '$450,000',
      '$300,000 (the old basis carries over since gain is partially deferred)',
      '$250,000',
      '$350,000',
    ],
    correctAnswer: 1,
    explanation: 'In a like-kind exchange with boot: (1) Realized gain = $500,000 − $300,000 = $200,000. (2) Recognized gain = lesser of boot ($50,000) or realized gain ($200,000) = $50,000. (3) Basis in new property = adjusted basis of old property − boot received + gain recognized = $300,000 − $50,000 + $50,000 = $300,000. Alternatively: FMV of new property − deferred gain = $450,000 − $150,000 = $300,000. The deferred gain of $150,000 is preserved in the lower basis of the replacement property.',
    reference: 'IRC §1031(d)',
  },
  {
    id: 'reg-d8-015',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Holding Period',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'To qualify for long-term capital gain treatment, a capital asset must be held for more than:',
    options: [
      '6 months',
      '1 year (more than 12 months)',
      '18 months',
      '2 years',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1222, a capital asset must be held for more than 1 year (more than 12 months) to qualify for long-term capital gain or loss treatment. The holding period begins on the day after acquisition and includes the day of disposition. For property received in a like-kind exchange or involuntary conversion, the holding period of the replacement property includes the holding period of the exchanged property (tacking). For gifted property, the holding period includes the donor\'s holding period if the basis is a carryover basis.',
    reference: 'IRC §1222; §1223',
  },
  {
    id: 'reg-d8-016',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-qoz',
    topic: 'Qualified Opportunity Zones',
    subtopic: 'QOZ Deferral',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §1400Z-2, a taxpayer who invests capital gains into a Qualified Opportunity Fund within 180 days of realizing the gain:',
    options: [
      'Permanently excludes the gain from taxation',
      'Defers recognition of the original gain until the earlier of the date the QOF investment is sold or December 31, 2026, and may exclude gain on appreciation in the QOF investment if held at least 10 years',
      'Receives a dollar-for-dollar tax credit',
      'Converts the gain to ordinary income',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1400Z-2, a taxpayer may elect to defer capital gains by investing in a Qualified Opportunity Fund (QOF) within 180 days. The deferred gain is recognized on the earlier of the sale of the QOF investment or December 31, 2026. Previously, basis step-ups of 10%/15% were available for investments held 5/7 years, but those deadlines have passed. For investments held at least 10 years, any additional appreciation in the QOF investment (above the deferred gain) may be permanently excluded from taxation by electing to increase basis to FMV at sale.',
    reference: 'IRC §1400Z-2',
  },
  {
    id: 'reg-d8-017',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1033',
    topic: 'Involuntary Conversions',
    subtopic: 'Basis of Replacement Property',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A taxpayer\'s warehouse (adjusted basis $200,000) is destroyed by fire. Insurance proceeds of $350,000 are received, and the taxpayer purchases a replacement warehouse for $320,000 within the replacement period. If the taxpayer elects §1033, the basis of the replacement warehouse is:',
    options: [
      '$320,000',
      '$170,000 ($320,000 cost − $150,000 deferred gain)',
      '$200,000',
      '$350,000',
    ],
    correctAnswer: 2,
    explanation: 'Under §1033: (1) Realized gain = $350,000 − $200,000 = $150,000. (2) Recognized gain = proceeds not reinvested = $350,000 − $320,000 = $30,000. (3) Deferred gain = $150,000 − $30,000 = $120,000. (4) Basis of replacement property = cost − deferred gain = $320,000 − $120,000 = $200,000. The cost basis reduction by the deferred gain preserves the $120,000 of deferred gain in the replacement property\'s lower basis. When the replacement property is eventually sold, the deferred gain will be recognized.',
    reference: 'IRC §1033(b)',
  },
  {
    id: 'reg-d8-018',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-related-party',
    topic: 'Related Party Transactions',
    subtopic: 'Related Party Installment Sales',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'If a taxpayer sells depreciable property to a related party (as defined under §1239), any gain is:',
    options: [
      'Treated as long-term capital gain',
      'Treated entirely as ordinary income, regardless of the character of the property',
      'Deferred until the related party disposes of the property',
      'Split equally between ordinary income and capital gain',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1239, gain on the sale of depreciable property (property subject to depreciation in the hands of the buyer) between related parties is treated as ordinary income rather than capital gain or §1231 gain. Related parties under §1239 include: (1) a person and all entities in which that person owns (directly or indirectly) more than 50% in value, and (2) two entities with more than 50% common ownership. The purpose is to prevent taxpayers from selling depreciated property to a related party to generate capital gain for the seller while the buyer claims new depreciation deductions at ordinary income rates.',
    reference: 'IRC §1239',
  },
  {
    id: 'reg-d8-019',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Netting Process',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When an individual taxpayer has both net short-term capital losses and net long-term capital gains, the netting process results in:',
    options: [
      'All gains and losses are netted together and treated as short-term',
      'The net short-term capital loss offsets the net long-term capital gain, and the remaining net gain retains its long-term character',
      'Short-term and long-term items are kept completely separate',
      'All items are treated as ordinary income and loss',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1222, the netting process for individuals works in steps: (1) Net all short-term gains and losses = net STCG or net STCL, (2) Net all long-term gains and losses = net LTCG or net LTCL, (3) If the results are opposite (one net gain, one net loss), combine them. If the result is a net gain: net STCG is taxed at ordinary rates, net LTCG at preferential rates (0%/15%/20%). When a net STCL offsets a net LTCG, the remaining gain retains its long-term character and qualifies for the preferential rate.',
    reference: 'IRC §1222; §1(h)',
  },
  {
    id: 'reg-d8-020',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-gift-basis',
    topic: 'Basis of Gifted Property',
    subtopic: 'Dual Basis Rule',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A father gives his daughter stock with an adjusted basis of $50,000 and a FMV of $30,000 at the date of the gift. If the daughter later sells the stock for $35,000, her recognized gain or loss is:',
    options: [
      '$5,000 gain',
      '$0 — no gain or loss (the sale price is between the carryover basis and the FMV at the date of gift)',
      '$15,000 loss',
      '$35,000 gain',
    ],
    correctAnswer: 1,
    explanation: 'When property is gifted at a loss (FMV < donor\'s basis), the "dual basis" rule under Treas. Reg. §1.1015-1(a)(2) applies: (1) for gain purposes, basis = donor\'s basis ($50,000), (2) for loss purposes, basis = FMV at date of gift ($30,000). If the sale price is between these two amounts (the "no-man\'s land"), no gain or loss is recognized. Here, $35,000 is between $30,000 and $50,000, so: no gain (because $35,000 < $50,000 gain basis) and no loss (because $35,000 > $30,000 loss basis). Result: $0 gain or loss.',
    reference: 'IRC §1015; Treas. Reg. §1.1015-1(a)(2)',
  },
  {
    id: 'reg-d8-021',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1245',
    topic: 'Depreciation Recapture',
    subtopic: 'Charitable Donation Exception',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When §1245 property is contributed to a charitable organization, the depreciation recapture rules:',
    options: [
      'Require the donor to recognize ordinary income',
      'Do not apply — instead, the charitable deduction is reduced to the property\'s adjusted basis (FMV minus the ordinary income that would have been recognized)',
      'Are completely waived',
      'Apply but at a reduced rate of 50%',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §170(e)(1), when a taxpayer donates §1245 property to charity, recapture gain is not recognized. Instead, the charitable deduction is reduced by the amount of gain that would have been ordinary income (§1245 recapture) if the property had been sold. This effectively limits the deduction to the donor\'s adjusted basis. For example, if equipment with a $10,000 basis and $40,000 FMV is donated, the $30,000 of §1245 recapture reduces the deduction from $40,000 to $10,000. This applies to all property where the FMV exceeds the basis and the appreciation would be ordinary rather than capital gain.',
    reference: 'IRC §170(e)(1)(A)',
  },
  {
    id: 'reg-d8-022',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-inherited-basis',
    topic: 'Basis of Inherited Property',
    subtopic: 'Stepped-Up Basis',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under IRC §1014, the basis of property acquired from a decedent is generally:',
    options: [
      'The decedent\'s adjusted basis (carryover basis)',
      'The fair market value of the property at the date of the decedent\'s death (or the alternate valuation date if elected)',
      'Zero',
      'The original cost to the decedent',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1014(a), the basis of property acquired from a decedent is the fair market value at the date of death. If the executor of the estate elects the alternate valuation date under §2032, the basis is the FMV 6 months after death (or the date of earlier disposition). This "step-up" (or step-down) in basis eliminates any unrealized gain (or loss) that accrued during the decedent\'s lifetime. The holding period of inherited property is automatically long-term, regardless of how long the decedent or heir held the property (§1223(9)).',
    reference: 'IRC §1014(a); §2032',
  },
  {
    id: 'reg-d8-023',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-niit',
    topic: 'Net Investment Income Tax',
    subtopic: 'NIIT Application',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The Net Investment Income Tax (NIIT) under IRC §1411 imposes an additional tax of:',
    options: [
      '1.5% on all capital gains',
      '3.8% on the lesser of net investment income or the excess of MAGI over the threshold ($200,000 single, $250,000 married filing jointly)',
      '5% on investment income above $500,000',
      '2% on all passive income',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1411, the NIIT is a 3.8% tax on the lesser of: (1) net investment income (interest, dividends, capital gains, rents, royalties, passive activity income, minus allocable deductions), or (2) the excess of modified adjusted gross income (MAGI) over the threshold: $200,000 (single), $250,000 (MFJ), $125,000 (MFS). The NIIT does NOT apply to wages, self-employment income, Social Security, tax-exempt interest, or distributions from qualified retirement plans. The thresholds are not indexed for inflation.',
    reference: 'IRC §1411',
  },
  {
    id: 'reg-d8-024',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-1033',
    topic: 'Involuntary Conversions',
    subtopic: 'Condemnation vs Casualty Standards',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The replacement property standard differs between condemned property and property destroyed by casualty. For condemned real property held for business or investment, the standard is:',
    options: [
      '"Similar or related in service or use" (functional use test)',
      '"Like-kind" (the broader §1031 standard applies)',
      'Identical property only',
      'Any property of equal value',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1033(g), for real property held for productive use in a trade or business or for investment that is condemned (or sold under threat of condemnation), the replacement standard is the broader "like-kind" standard of §1031, rather than the narrower "similar or related in service or use" test. This means any real property of a like kind qualifies (e.g., a condemned office building could be replaced with raw land). For casualties, thefts, and other involuntary conversions, the narrower "similar or related in service or use" standard applies under the general §1033 rules and requires a closer functional match.',
    reference: 'IRC §1033(g)',
  },
  {
    id: 'reg-d8-025',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-V',
    topicId: 'reg-capital-gains',
    topic: 'Capital Gains and Losses',
    subtopic: 'Collectibles Gain Rate',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Long-term capital gains from the sale of collectibles (such as art, antiques, stamps, and coins) are taxed at a maximum rate of:',
    options: [
      '15%',
      '28%',
      '20%',
      '25%',
    ],
    correctAnswer: 1,
    explanation: 'Under IRC §1(h)(4), long-term capital gains from the sale of collectibles are taxed at a maximum rate of 28%, which is higher than the regular maximum LTCG rate of 20%. Collectibles include works of art, rugs, antiques, metals (gold, silver), gems, stamps, coins, alcoholic beverages, and any other tangible personal property specified by the IRS. If the taxpayer\'s ordinary income tax bracket is less than 28%, the gain is taxed at the lower rate. The 3.8% NIIT may also apply, bringing the maximum effective rate to 31.8%.',
    reference: 'IRC §1(h)(4); §408(m)(2)',
  },
];
