// REG Depth Questions - Batch 5
// Focus: REG-IV (Entity Taxation)
// Topics: C Corporation Formation, Taxable Income, Tax Liability, Distributions
// Difficulty: balanced easy/medium/hard

import { Question } from '../../../types';

export const REG_QUESTIONS_DEPTH_5: Question[] = [
  {
    id: 'reg-d5-001',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Formation — §351 Rules',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Three individuals transfer property to a newly formed corporation in exchange for all of its stock. One transferor also receives $10,000 in cash (boot). Under §351, the exchange is tax-free if:',
    options: [
      'Any number of transferors participates',
      'The transferors as a group are in control (own at least 80% of total voting power and 80% of each class of nonvoting stock) immediately after the exchange',
      'Each transferor individually owns at least 50%',
      'The corporation has at least $1 million in assets',
    ],
    correctAnswer: 1,
    explanation: '§351 provides nonrecognition treatment when: (1) one or more persons transfer property to a corporation; (2) solely in exchange for stock of the corporation; and (3) the transferors as a group are in "control" (defined under §368(c) as ownership of at least 80% of total combined voting power AND 80% of the total shares of each class of nonvoting stock) immediately after the exchange. The transferor receiving the $10,000 boot must recognize gain to the extent of the boot received (lesser of gain realized or boot received). The corporation recognizes no gain on issuing its own stock. Services rendered do not qualify as "property" for §351 purposes.',
    reference: 'IRC §351; §368(c)',
  },
  {
    id: 'reg-d5-002',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Corporate Taxable Income',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The corporate tax rate for C corporations under the Tax Cuts and Jobs Act (TCJA) is:',
    options: [
      'A graduated rate from 15% to 39%',
      'A flat rate of 21%',
      'A flat rate of 28%',
      'A flat rate of 35%',
    ],
    correctAnswer: 1,
    explanation: 'The TCJA (effective for tax years beginning after December 31, 2017) replaced the prior graduated corporate tax rate structure (15%, 25%, 34%, 35%, with additional surtaxes) with a single flat rate of 21%. This applies to all C corporations regardless of taxable income level. The flat rate simplifies corporate tax computation and eliminates the need for the progressive bracket calculations that existed under prior law. Personal service corporations (PSCs), which were previously taxed at a flat 35%, also benefit from the reduced 21% rate under TCJA.',
    reference: 'IRC §11(b); TCJA §13001',
  },
  {
    id: 'reg-d5-003',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Dividends Received Deduction',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Corp A owns 25% of Corp B and receives $100,000 in dividends from Corp B. The dividends received deduction (DRD) percentage is:',
    options: [
      '50% ($50,000 deduction)',
      '65% ($65,000 deduction)',
      '100% ($100,000 deduction)',
      '0% (no deduction)',
    ],
    correctAnswer: 1,
    explanation: 'The dividends received deduction (DRD) under §243 depends on the ownership percentage: (1) less than 20% ownership → 50% DRD; (2) 20% to less than 80% ownership → 65% DRD; (3) 80% or more ownership (affiliated group member) → 100% DRD. Since Corp A owns 25% (between 20% and 80%), the DRD is 65%, resulting in a $65,000 deduction ($100,000 × 65%). The DRD is generally limited to the applicable percentage of taxable income (before DRD, NOL deduction, and capital loss carryback), unless the DRD creates or increases a net operating loss. This limitation prevents the DRD from creating artificial losses.',
    reference: 'IRC §243; §246(b)',
  },
  {
    id: 'reg-d5-004',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Capital Losses',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A C corporation has $50,000 of net capital losses in the current year. How are these losses treated?',
    options: [
      'Deducted against ordinary income up to $3,000',
      'Capital losses can only offset capital gains — any excess is carried back 3 years and forward 5 years as short-term capital losses',
      'Carried forward indefinitely',
      'Deducted in full against all income',
    ],
    correctAnswer: 1,
    explanation: 'Corporate capital loss treatment differs from individual treatment: (1) corporations CANNOT deduct net capital losses against ordinary income (individuals can deduct up to $3,000); (2) net capital losses are carried back 3 years (to offset capital gains in those years) and then forward 5 years; (3) capital loss carrybacks and carryforwards are treated as short-term capital losses in the carryback/carryforward year; (4) if the losses cannot be used within the 5-year forward period, they expire. The corporation should first carry back to the earliest of the 3 preceding years, then sequentially to the next years. The $50,000 net capital loss would be carried back 3 years; any unused amount carried forward 5 years.',
    reference: 'IRC §1211(a); §1212(a)',
  },
  {
    id: 'reg-d5-005',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Charitable Contribution Limitations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A C corporation\'s charitable contribution deduction is limited to:',
    options: [
      '60% of adjusted gross income',
      '10% of taxable income computed before the charitable contribution deduction, DRD, NOL carryback, and capital loss carryback',
      '50% of taxable income',
      '25% of gross revenue',
    ],
    correctAnswer: 1,
    explanation: 'Under §170(b)(2), corporate charitable contributions are limited to 10% of taxable income, computed before: (1) the charitable contribution deduction itself; (2) the dividends received deduction (DRD); (3) any NOL carryback; and (4) any capital loss carryback. This modified taxable income is the base for the 10% limit. Excess contributions are carried forward 5 years (not carried back). Note: the CARES Act temporarily increased this limit to 25% for cash contributions to qualifying charities in 2020 and 2021, but for 2022 and later the limit reverts to 10%. The accrual basis rule allows a corporation to elect to deduct contributions made within 2½ months after year-end if the board authorizes them before year-end.',
    reference: 'IRC §170(b)(2); §170(d)(2)',
  },
  {
    id: 'reg-d5-006',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Accumulated Earnings Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The accumulated earnings tax (AET) under §531 is imposed when:',
    options: [
      'A corporation has any retained earnings',
      'A corporation accumulates earnings beyond the reasonable needs of the business with the purpose of avoiding the tax on dividends to shareholders — the tax is 20% of accumulated taxable income',
      'A corporation pays dividends',
      'A corporation has gross receipts over $10 million',
    ],
    correctAnswer: 1,
    explanation: 'The accumulated earnings tax (§531-537) is a penalty tax designed to discourage corporations from accumulating earnings to avoid shareholder-level dividend taxes: (1) imposed at 20% on "accumulated taxable income" (taxable income minus income taxes, charitable contributions in excess of the 10% limit, certain adjustments, dividends paid, and the accumulated earnings credit); (2) the accumulated earnings credit is the greater of: (a) $250,000 ($150,000 for personal service corporations) minus accumulated E&P at the beginning of the year, or (b) the amount of E&P retained for reasonable business needs; (3) "reasonable needs" include business expansion, debt retirement, working capital needs (Bardahl formula), investments, or contingencies; (4) the tax applies only when the purpose of the accumulation is to avoid dividend tax — mere accumulation without tax-avoidance purpose is not penalized.',
    reference: 'IRC §531-537',
  },
  {
    id: 'reg-d5-007',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Personal Holding Company Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A corporation is classified as a personal holding company (PHC) if it meets BOTH the stock ownership test AND the income test. The income test requires:',
    options: [
      'More than 50% of ordinary gross income consists of dividends, interest, rents, and royalties',
      'At least 60% of adjusted ordinary gross income (AOGI) consists of PHC income — dividends, interest, rents (unless exceeding 50% of AOGI with other criteria), royalties, and personal service contracts',
      'More than 75% of gross receipts come from investments',
      'Any amount of passive income',
    ],
    correctAnswer: 1,
    explanation: 'Under §542, a personal holding company must meet two tests: (1) Stock ownership test — more than 50% in value of the corporation\'s outstanding stock is owned (directly or constructively under §544) by 5 or fewer individuals at any time during the last half of the tax year; (2) Income test — at least 60% of AOGI consists of PHC income. PHC income includes: dividends, interest, rents (unless they constitute 50%+ of AOGI and other PHC income is ≤10% of OGI), royalties (with similar exceptions for mineral, oil, gas, and copyright royalties), amounts received from personal service contracts (if the individual who performs the services owns 25%+ of the stock), and compensation received for use of corporate property by a 25%+ shareholder. The PHC tax rate is 20% of undistributed PHC income.',
    reference: 'IRC §541-547',
  },
  {
    id: 'reg-d5-008',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Earnings and Profits',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A C corporation distributes $80,000 to its sole shareholder. The corporation has current E&P of $30,000 and accumulated E&P of $20,000. How is the distribution taxed to the shareholder?',
    options: [
      'The entire $80,000 is a dividend',
      '$50,000 is a dividend (current E&P of $30,000 + accumulated E&P of $20,000), $30,000 is a return of capital reducing stock basis, and any remainder is capital gain',
      '$30,000 is a dividend and $50,000 is a return of capital',
      'The entire $80,000 is a return of capital',
    ],
    correctAnswer: 1,
    explanation: 'Under §301 and §316, distributions are taxed in a 3-tier system: (1) Dividend to the extent of E&P — first from current E&P (CE&P), then from accumulated E&P (AE&P). Total E&P available = $30,000 CE&P + $20,000 AE&P = $50,000 treated as a dividend (taxed as ordinary income or qualified dividend rate); (2) Return of capital — the next $30,000 reduces the shareholder\'s stock basis to zero (nontaxable); (3) Capital gain — any amount exceeding both E&P and stock basis is treated as capital gain. Important: CE&P is allocated to distributions on a pro-rata basis regardless of when during the year they are made, while AE&P is allocated in chronological order.',
    reference: 'IRC §301; §316',
  },
  {
    id: 'reg-d5-009',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Stock Redemptions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'For a stock redemption to be treated as a sale or exchange (capital gain treatment) rather than a dividend under §302, the redemption must qualify under one of several tests. The "substantially disproportionate" test requires:',
    options: [
      'Any reduction in ownership is sufficient',
      'After the redemption, the shareholder owns less than 50% of total voting power AND the shareholder\'s post-redemption voting stock percentage is less than 80% of the pre-redemption percentage',
      'A complete termination of interest only',
      'Approval by the IRS',
    ],
    correctAnswer: 1,
    explanation: 'Under §302(b)(2), a substantially disproportionate redemption must meet THREE tests: (1) the shareholder\'s post-redemption voting stock ownership must be less than 80% of the pre-redemption percentage (ratio test); (2) the shareholder must own less than 50% of the total combined voting power after the redemption; (3) the redemption must not be essentially equivalent to a dividend. Example: If a shareholder owns 60% before redemption, the shareholder must own less than 48% (60% × 80%) after redemption AND less than 50% of total voting power. Constructive ownership rules under §318 apply (family attribution, entity attribution). Other qualifying redemptions: §302(b)(1) "not essentially equivalent to a dividend," §302(b)(3) complete termination, §302(b)(4) partial liquidation.',
    reference: 'IRC §302(b)(2)',
  },
  {
    id: 'reg-d5-010',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Corporate Liquidations — §331',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a C corporation completely liquidates and distributes all assets to shareholders, the shareholders:',
    options: [
      'Recognize no gain or loss',
      'Treat the liquidating distribution as payment in exchange for their stock — recognizing gain or loss equal to the difference between the FMV of assets received and their stock basis',
      'Recognize ordinary income on the full FMV received',
      'Carry over the corporation\'s basis in the assets',
    ],
    correctAnswer: 1,
    explanation: 'Under §331, shareholders treat liquidating distributions as full payment in exchange for their stock: (1) gain/loss = FMV of assets received minus adjusted basis of stock surrendered; (2) the gain/loss is typically capital (long-term if stock held more than one year); (3) the shareholder\'s basis in the assets received equals FMV at the date of distribution (§334(a)); (4) holding period for assets received begins on the distribution date. For the corporation: under §336, the corporation recognizes gain or loss on the distribution of assets as if it sold them at FMV (with exceptions for distributions to related persons at a loss under §336(d)). Any remaining E&P of the corporation becomes irrelevant after complete liquidation.',
    reference: 'IRC §331; §334(a); §336',
  },
  {
    id: 'reg-d5-011',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Organizational Expenditures',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under §248, a corporation may elect to deduct organizational expenditures by:',
    options: [
      'Capitalizing them permanently',
      'Deducting up to $5,000 in the first year (reduced by the amount exceeding $50,000) and amortizing any remaining costs over 180 months beginning with the month business begins',
      'Deducting the entire amount in the first year',
      'Amortizing them over 60 months only',
    ],
    correctAnswer: 1,
    explanation: 'Under §248, organizational expenditures (costs of creating the corporation — legal fees for drafting the charter, incorporation fees, costs of organizational meetings, state incorporation fees) are treated as follows: (1) the corporation may deduct up to $5,000 in the tax year the corporation begins business; (2) the $5,000 current deduction is reduced dollar-for-dollar by the amount of organizational costs exceeding $50,000 (fully phased out at $55,000); (3) any remaining costs are amortized ratably over 180 months (15 years) beginning with the month the corporation begins business. Similar treatment applies to startup costs under §195. Costs that do NOT qualify: stock issuance costs (commissions, underwriting expenses), transfer costs for assets to the corporation.',
    reference: 'IRC §248',
  },
  {
    id: 'reg-d5-012',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'NOL Rules for Corporations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the TCJA, C corporation net operating losses (NOLs) arising after December 31, 2017:',
    options: [
      'Can be carried back 2 years and forward 20 years to offset 100% of income',
      'Can only be carried forward indefinitely (no carryback) and can offset no more than 80% of taxable income in the carryforward year',
      'Cannot be used at all',
      'Can only offset passive income',
    ],
    correctAnswer: 1,
    explanation: 'The TCJA significantly changed NOL rules for post-2017 losses: (1) NO carryback — NOLs arising after December 31, 2017 can only be carried forward (the 2-year carryback was eliminated); (2) the carryforward period is indefinite (no longer limited to 20 years); (3) the 80% limitation — NOLs can only offset 80% of taxable income in any carryforward year (meaning a corporation with NOL carryforwards will always pay some tax when it returns to profitability); (4) pre-2018 NOLs follow the old rules (2-year carryback, 20-year carryforward, 100% offset). Note: The CARES Act temporarily allowed a 5-year carryback for NOLs arising in 2018, 2019, and 2020, and suspended the 80% limitation for those years, but these provisions have expired for 2021+ losses.',
    reference: 'IRC §172; TCJA §13302',
  },
  {
    id: 'reg-d5-013',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: '§351 Basis Rules',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Transferor A contributes property with a fair market value of $100,000 and an adjusted basis of $60,000 to a newly formed corporation in a §351 exchange, receiving stock worth $90,000 and $10,000 cash (boot). A\'s recognized gain and basis in the stock received are:',
    options: [
      'No gain; stock basis = $60,000',
      'Recognized gain of $10,000 (lesser of $40,000 realized gain and $10,000 boot); stock basis = $60,000 (transferred basis of $60,000, plus $10,000 gain recognized, minus $10,000 boot received)',
      'Recognized gain of $40,000; stock basis = $100,000',
      'Recognized gain of $10,000; stock basis = $90,000',
    ],
    correctAnswer: 1,
    explanation: 'In a §351 exchange with boot: (1) Gain realized = FMV received ($90,000 stock + $10,000 cash = $100,000) minus basis transferred ($60,000) = $40,000; (2) Gain recognized = lesser of gain realized ($40,000) or boot received ($10,000) = $10,000; (3) Stock basis = transferor\'s basis in property transferred ($60,000) + gain recognized ($10,000) - boot received ($10,000) - FMV of boot (already netted) = $60,000. Formula: Stock basis = transferred basis + gain recognized - boot received. The corporation\'s basis in the property = transferor\'s basis ($60,000) + gain recognized by transferor ($10,000) = $70,000 (§362(a)). Losses are NEVER recognized in a §351 exchange.',
    reference: 'IRC §351; §358; §362(a)',
  },
  {
    id: 'reg-d5-014',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Related Party Losses',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under §267, a loss on a sale between a corporation and a shareholder who owns more than 50% of the stock (by value) is:',
    options: [
      'Fully deductible',
      'Disallowed — the loss is permanently disallowed to the selling party, but the buyer may benefit if the buyer later sells the property at a gain',
      'Deductible as a capital loss',
      'Deferred until the stock is sold',
    ],
    correctAnswer: 1,
    explanation: 'Under §267(a)(1), losses on sales or exchanges between related parties are disallowed. Related parties include: (1) a corporation and a more-than-50% shareholder (by value, applying constructive ownership under §267(c)); (2) two corporations that are members of the same controlled group; (3) a corporation and a partnership if the same persons own more than 50% of each. The disallowed loss is NOT deductible by the seller in any year. However, §267(d) provides a partial benefit to the buyer: if the buyer later resells the property at a gain, the buyer\'s gain is reduced (but not below zero) by the previously disallowed loss. For accrual-basis payor/cash-basis payee related parties, deductions for accrued expenses are also deferred under §267(a)(2) until paid and includible.',
    reference: 'IRC §267',
  },
  {
    id: 'reg-d5-015',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Schedule M-1 Reconciliation',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Schedule M-1 of Form 1120 reconciles:',
    options: [
      'Gross revenue to net revenue',
      'Net income per books (financial accounting) to taxable income per the return, by identifying differences such as tax-exempt income, nondeductible expenses, and timing differences',
      'Cash receipts to accrual income',
      'Current year income to prior year income',
    ],
    correctAnswer: 1,
    explanation: 'Schedule M-1 reconciles book income to taxable income by identifying specific differences: (1) items that increase taxable income relative to book income: expenses recorded on books but not deductible for tax (meals at 50%, fines and penalties, entertainment, excess charitable contributions, federal income tax expense, life insurance premiums on officers — where corporation is beneficiary); (2) income recorded on tax return but not on books (prepaid income taxable per tax rules); (3) items that decrease taxable income relative to book income: income on books not on the return (tax-exempt municipal bond interest, life insurance proceeds) and deductions on the return not on books (depreciation differences, §179 expensing). Larger corporations ($10M+ total assets) file Schedule M-3 instead, providing more detailed reconciliation.',
    reference: 'Form 1120 Schedule M-1',
  },
  {
    id: 'reg-d5-016',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Estimated Tax Payments',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A C corporation must make estimated tax payments if its estimated tax liability is expected to be:',
    options: [
      '$1,000 or more',
      '$500 or more',
      '$10,000 or more',
      'Any amount',
    ],
    correctAnswer: 1,
    explanation: 'Under §6655, a C corporation must make estimated tax payments if the expected tax for the year is $500 or more. Payments are due on the 15th day of the 4th, 6th, 9th, and 12th months of the tax year (April 15, June 15, September 15, December 15 for calendar-year corporations). Each installment must be at least 25% of the required annual payment. The corporation can avoid the underpayment penalty by paying the lesser of: (1) 100% of the current year\'s tax liability (in equal installments), or (2) 100% of the prior year\'s tax liability (not available if the prior year showed zero tax or was less than 12 months). Large corporations ($1M+ taxable income in any of the 3 preceding years) must use current-year estimates after the first installment.',
    reference: 'IRC §6655',
  },
  {
    id: 'reg-d5-017',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Business Interest Limitation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under §163(j) as modified by the TCJA, a corporation\'s deduction for business interest expense is generally limited to:',
    options: [
      'No limitation',
      'The sum of business interest income plus 30% of adjusted taxable income (ATI), plus floor plan financing interest',
      '50% of taxable income',
      '100% of gross receipts',
    ],
    correctAnswer: 1,
    explanation: 'TCJA §163(j) limits the deduction for business interest expense to: (1) business interest income; plus (2) 30% of adjusted taxable income (ATI) — for 2022+, ATI is computed WITHOUT depreciation, amortization, or depletion deductions (making the limit more restrictive than 2018-2021 when ATI was essentially EBITDA); plus (3) floor plan financing interest (for auto dealers). Key points: (a) the excess business interest is carried forward indefinitely; (b) small businesses (average annual gross receipts of $29 million or less for 2024, indexed for inflation, for the 3 prior tax years) are exempt; (c) certain businesses may elect out (real property trade or business under §163(j)(7)(B) — but must use ADS depreciation); (d) the limitation applies at the entity level.',
    reference: 'IRC §163(j); TCJA §13301',
  },
  {
    id: 'reg-d5-018',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Constructive Dividends',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following would likely be treated as a constructive dividend to a shareholder?',
    options: [
      'A salary payment at fair market value for services rendered',
      'An excessive salary, below-market interest rate loan, or personal expenses paid by the corporation for the shareholder — reclassified as a distribution to the extent of the corporation\'s E&P',
      'A dividend formally declared by the board of directors',
      'A distribution from a corporation with no E&P',
    ],
    correctAnswer: 1,
    explanation: 'Constructive dividends are disguised distributions to shareholders that are recharacterized by the IRS. Common examples: (1) excessive compensation — salary paid to a shareholder-employee that exceeds reasonable compensation for services (the excess is reclassified as a nondeductible dividend); (2) below-market interest rate loans — the forgone interest is treated as a distribution; (3) personal expenses — the corporation pays the shareholder\'s personal expenses (travel, housing, vehicles); (4) bargain purchases — the shareholder purchases corporate property below FMV; (5) shareholder use of corporate property — personal use of corporate assets; (6) rent or interest paid to shareholder above fair market value. Constructive dividends are treated as dividends to the extent of E&P and are NOT deductible by the corporation (double tax).',
    reference: 'IRC §301; §316; Reg. §1.301-1',
  },
  {
    id: 'reg-d5-019',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Property Distributions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a C corporation distributes appreciated property (FMV $80,000, basis $30,000) to a shareholder as a dividend, the corporation:',
    options: [
      'Recognizes no gain',
      'Recognizes gain of $50,000 (as if the property were sold at FMV), and E&P is increased by the gain then decreased by the FMV of the distribution',
      'Recognizes a $50,000 loss',
      'Reduces E&P by the basis of the property',
    ],
    correctAnswer: 1,
    explanation: 'Under §311(b), when a corporation distributes appreciated property (FMV > basis): (1) the corporation recognizes gain as if the property were sold at FMV — gain = FMV ($80,000) - basis ($30,000) = $50,000; (2) the character of the gain depends on the type of property (capital gain, §1231 gain, ordinary income); (3) E&P is first increased by the recognized gain ($50,000), then decreased by the FMV of the property distributed ($80,000); (4) the shareholder includes the FMV ($80,000) as dividend income to the extent of E&P and takes a basis in the property equal to FMV ($80,000). If depreciated property were distributed (FMV < basis), the corporation cannot recognize the loss under §311(a) — E&P is reduced only by the adjusted basis of the property.',
    reference: 'IRC §311(b); §312',
  },
  {
    id: 'reg-d5-020',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Filing Requirements',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Form 1120 (C corporation tax return) for a calendar-year corporation is due:',
    options: [
      'March 15 of the following year',
      'April 15 of the following year, with an automatic 6-month extension available by filing Form 7004',
      'June 15 of the following year',
      'September 15 of the following year',
    ],
    correctAnswer: 1,
    explanation: 'Under §6072(b), a C corporation\'s tax return (Form 1120) is due on the 15th day of the 4th month following the close of the tax year. For calendar-year corporations: April 15. An automatic 6-month extension is available by filing Form 7004 on or before the due date, extending the filing deadline to October 15. Important: the extension is for filing only — it does NOT extend the time for payment. Estimated tax payments and any remaining tax must still be paid by the original due date to avoid interest and penalties. Fiscal-year corporations follow the same rule: 15th day of the 4th month after year-end.',
    reference: 'IRC §6072(b); Form 7004',
  },
  {
    id: 'reg-d5-021',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Tax Credits',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The general business credit under §38 available to C corporations includes several component credits. Which is NOT a component of the general business credit?',
    options: [
      'Research and experimentation credit (§41)',
      'Foreign tax credit (§27)',
      'Work opportunity tax credit (§51)',
      'Disabled access credit (§44)',
    ],
    correctAnswer: 1,
    explanation: 'The general business credit (§38) is a collection of business credits including: research and experimentation credit (§41), work opportunity tax credit (§51), disabled access credit (§44), low-income housing credit (§42), rehabilitation credit (§47), employer-provided child care credit (§45F), and many others. The foreign tax credit (§27/§901) is NOT part of the general business credit — it is a separate credit that reduces US tax on foreign-source income. Key differences: (1) the general business credit is subject to a limitation based on tax liability; (2) unused general business credits are carried back 1 year and forward 20 years; (3) the foreign tax credit has its own limitation formula (§904) and separate carryback/carryforward rules (1 year back, 10 years forward).',
    reference: 'IRC §38; §27; §901',
  },
  {
    id: 'reg-d5-022',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Controlled Groups',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A parent-subsidiary controlled group under §1563 exists when:',
    options: [
      'Two corporations have common management',
      'A common parent corporation owns directly at least 80% of the total combined voting power or value of at least one other corporation, and at least 80% of each included corporation is owned within the group (including the parent)',
      'Two corporations share the same office space',
      'Two corporations are in the same industry',
    ],
    correctAnswer: 1,
    explanation: 'Under §1563(a)(1), a parent-subsidiary controlled group exists when: (1) one or more chains of corporations are connected to a common parent through stock ownership; (2) the common parent directly owns at least 80% of the total combined voting power or 80% of the value of at least one other corporation; (3) at least 80% of each included corporation (other than the parent) is owned by one or more of the other member corporations. Controlled group classification is important because: (a) §11 tax brackets, accumulated earnings credit, and §179 limitations are shared/allocated among group members; (b) §267 and §1239 related-party rules apply; (c) §482 allows the IRS to reallocate income between group members. Other types: brother-sister group (§1563(a)(2)) — same 5 or fewer individuals own 80%+ and have more than 50% identical ownership; combined group.',
    reference: 'IRC §1563; §1561',
  },
  {
    id: 'reg-d5-023',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Consolidated Returns',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An affiliated group of corporations may elect to file a consolidated return. Which statement about consolidated returns is correct?',
    options: [
      'Any group of related corporations can file a consolidated return',
      'The common parent must own directly at least 80% (vote and value) of at least one subsidiary, intercompany transactions are eliminated, and once the election is made it is binding for all subsequent years unless the IRS grants permission to discontinue',
      'Each member files separately and combines the results',
      'The election may be changed annually',
    ],
    correctAnswer: 1,
    explanation: 'Under §1501-1504, consolidated return rules: (1) an affiliated group is defined under §1504(a) — the common parent directly owns at least 80% of the voting power AND 80% of the value of at least one includible corporation, and the group collectively meets 80% ownership for each member; (2) intercompany transactions (sales, loans, dividends) between members are eliminated in consolidation; (3) the election is binding — once made, the group must continue filing consolidated returns unless: (a) the affiliation terminates (falling below 80% ownership), or (b) the IRS grants permission to discontinue; (4) certain entities are excluded from the affiliated group: tax-exempt organizations, foreign corporations, insurance companies (except life insurance companies under certain conditions), S corporations, REITs, and RICs.',
    reference: 'IRC §1501-1504',
  },
  {
    id: 'reg-d5-024',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Depreciation — MACRS and Bonus',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under current law, 100% bonus depreciation under §168(k) allows a corporation to:',
    options: [
      'Only depreciate assets over their useful life',
      'Immediately expense the full cost of qualifying new and used property placed in service, though the rate is being phased down (80% in 2023, 60% in 2024, 40% in 2025, 20% in 2026, 0% in 2027)',
      'Only deduct 50% of the cost in year one',
      'Only apply bonus depreciation to real property',
    ],
    correctAnswer: 1,
    explanation: 'The TCJA expanded §168(k) bonus depreciation to 100% for property placed in service after September 27, 2017 and before January 1, 2023. Key features: (1) applies to NEW and USED property (TCJA expanded to include used property); (2) applies to MACRS property with a recovery period of 20 years or less, computer software, water utility property, and qualified film/TV/live productions; (3) the 100% rate is being phased down: 80% for property placed in service in 2023, 60% in 2024, 40% in 2025, 20% in 2026, and 0% in 2027; (4) does NOT apply to property used predominantly outside the US, property required to use ADS, certain property from related parties, or property previously used by the taxpayer. Corporations can elect out of bonus depreciation on a class-by-class, year-by-year basis.',
    reference: 'IRC §168(k); TCJA §13201',
  },
  {
    id: 'reg-d5-025',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'E&P Adjustments',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which of the following requires an ADJUSTMENT from taxable income when computing a C corporation\'s current earnings and profits (E&P)?',
    options: [
      'Deductible salary payments',
      'Federal income tax (subtracted from E&P), tax-exempt municipal bond interest (added to E&P), §179 deduction excess over straight-line depreciation (adjusted), and life insurance proceeds (added to E&P)',
      'Cost of goods sold',
      'Gross receipts from operations',
    ],
    correctAnswer: 1,
    explanation: 'E&P starts with taxable income but requires adjustments to reflect the corporation\'s true economic ability to pay dividends: ADDITIONS to taxable income: (1) tax-exempt income (municipal bond interest, life insurance proceeds on officer policies); (2) DRD (taxable income already reduced by DRD — this is not reversed but is effectively reflected); (3) gain on installment sales (full gain recognized for E&P in year of sale). SUBTRACTIONS from taxable income: (1) federal income taxes paid or accrued; (2) excess charitable contributions (the 10% limit excess already excluded from taxable income); (3) penalties, fines, and political contributions (nondeductible for tax but reduce E&P); (4) life insurance premiums on officer policies. ADJUSTMENTS: (5) depreciation — E&P uses ADS (straight-line) depreciation; (6) §179 — E&P deducts over ADS life rather than immediately.',
    reference: 'IRC §312; Reg. §1.312-6',
  },
];
