// TCP - Tax Compliance & Planning Elite Questions
// 2026 CPA Exam Blueprint Compliant
// World-Class expansion - Elite batch (Final Push)

import { Question } from '../../../types';

export const TCP_QUESTIONS_ELITE: Question[] = [
  {
    id: 'tcp-elite-001',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Roth Conversions',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'A Roth IRA conversion from a traditional IRA results in:',
    options: [
      'Tax-free transfer',
      'Immediate taxation on the converted amount as ordinary income, but qualified distributions are tax-free',
      'Capital gains tax',
      'Penalty tax',
    ],
    correctAnswer: 1,
    explanation: 'Roth conversion: include converted amount in income (ordinary). No 10% penalty. No income limits on conversion. Pro-rata rule if nondeductible contributions exist. 5-year rule for conversions (penalty, not tax).',
    reference: 'IRC §408A - Roth Conversions',
  },
  {
    id: 'tcp-elite-002',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Qualified Opportunity Zones',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'Qualified Opportunity Zone investment benefits include:',
    options: [
      'Immediate tax exclusion',
      'Ordinary income treatment',
      'Capital gain deferral until 2026, basis step-up after 5 years, and exclusion of gain on QOF if held 10+ years',
      'No benefits remain'
    ],
    correctAnswer: 2,
    explanation: 'QOZ benefits (§1400Z-2): defer capital gain by investing in QOF. Gain recognized by 2026. After 5 years: 10% basis increase (expired). 10-year hold: exclude QOF gain. Must invest within 180 days.',
    reference: 'IRC §1400Z-2',
  },
  {
    id: 'tcp-elite-003',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'Corporate Taxation',
    subtopic: 'Type A Reorganization',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Evaluation',
    question: 'A Type A reorganization (statutory merger) requires:',
    options: [
      'Only stock consideration',
      'Cash only',
      'Merger under state law with continuity of interest and business enterprise',
      'SEC approval'
    ],
    correctAnswer: 2,
    explanation: 'Type A: statutory merger/consolidation. Flexibility in consideration (stock + cash). Requirements: state law merger, continuity of interest (40%+ stock), continuity of business enterprise. Boot is taxable.',
    reference: 'IRC §368(a)(1)(A)',
  },
  {
    id: 'tcp-elite-004',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'Corporate Taxation',
    subtopic: 'Corporate Alternative Minimum Tax',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'The Corporate Alternative Minimum Tax (CAMT) under IRA 2022 applies:',
    options: [
      '15% minimum tax on adjusted financial statement income for corporations with average AFSI over $1 billion',
      'To all corporations',
      'Only to S corporations',
      'To foreign corporations only',
    ],
    correctAnswer: 0,
    explanation: 'CAMT (IRA 2022): 15% minimum tax on Adjusted Financial Statement Income (book income). Applies if 3-year average AFSI > $1B. Adjustments for depreciation, NOLs, taxes. Generates minimum tax credit. Effective 2023.',
    reference: 'IRC §55 (as amended by IRA)',
  },
  {
    id: 'tcp-elite-005',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-scorp',
    topic: 'S Corporation',
    subtopic: 'Second Class of Stock',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Evaluation',
    question: 'An S corporation loses its election if it has a second class of stock, which occurs when:',
    options: [
      'Outstanding shares have different rights to distributions and liquidation proceeds',
      'Voting/non-voting differences',
      'Different share prices',
      'More than 100 shareholders',
    ],
    correctAnswer: 0,
    explanation: 'Second class of stock: different rights to distribution or liquidation. Voting differences alone don\'t create second class. Debt safe harbors exist. Operating agreements/bylaws scrutinized. Straight debt exception.',
    reference: 'IRC §1361(b)(1)(D)',
  },
  {
    id: 'tcp-elite-006',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Section 754 Election',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'A Section 754 election allows basis adjustments upon:',
    options: [
      'Transfer of partnership interest (§743) and distribution of property (§734)',
      'Termination only',
      'Formation only',
      'Annual revaluation',
    ],
    correctAnswer: 0,
    explanation: '§754 election: adjust inside basis for (1) §743(b): partnership interest transfer (buyer gets adjusted share of asset basis), (2) §734(b): property distribution (remaining partners adjust). Once made, applies to all future transactions.',
    reference: 'IRC §754',
  },
  {
    id: 'tcp-elite-007',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Disguised Sales',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Evaluation',
    question: 'A disguised sale of property to a partnership occurs when:',
    options: [
      'Services are contributed',
      'Losses are allocated',
      'Any contribution',
      'Property contribution and related distribution of cash/property are treated as a sale based on facts and circumstances',
    ],
    correctAnswer: 3,
    explanation: '§707(a)(2)(B): contribution + distribution within 2 years presumed sale unless facts rebut. Factors: timing, dependence on partnership operations, legal obligation. Exceeds basis = gain recognition.',
    reference: 'IRC §707(a)(2)(B)',
  },
  {
    id: 'tcp-elite-008',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Opportunity Zone Step-Up',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'After holding a Qualified Opportunity Fund investment for 10 years:',
    options: [
      'No additional benefit',
      'Original gain is forgiven',
      'Basis in QOF steps up to FMV, excluding post-acquisition appreciation from tax',
      'Ordinary income treatment',
    ],
    correctAnswer: 2,
    explanation: '10-year exclusion: if QOF held 10+ years, basis stepped to FMV at sale. Appreciation in QOF excluded from income. Original deferred gain still recognized by 2026. Major benefit for patient investors.',
    reference: 'IRC §1400Z-2(c)',
  },
  {
    id: 'tcp-elite-009',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-IV',
    topic: 'International Taxation',
    subtopic: 'Subpart F Income',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A U.S. multinational has a CFC in Country X that earns $2,000,000 and pays $300,000 in foreign income taxes. The CFC has QBAI of $4,000,000. Calculate the GILTI inclusion and the effective U.S. tax rate after the §250 deduction (assuming no other tested income or losses).',
    options: [
      'GILTI inclusion of $1,600,000; effective rate of 10.5% after the 50% §250 deduction, further reduced by foreign tax credits',
      'GILTI inclusion of $2,000,000; effective rate of 21%',
      'GILTI inclusion of $0 because foreign taxes exceed 13.125%',
      'GILTI inclusion of $400,000; effective rate of 21%',
    ],
    correctAnswer: 0,
    explanation: 'GILTI = tested income ($2,000,000) − DTIR (10% × $4,000,000 = $400,000) = $1,600,000. The §250 deduction for C corporations is 50% × $1,600,000 = $800,000, making effectively taxable GILTI = $800,000. At 21%, U.S. tax before FTCs = $168,000 (effective 10.5% on $1,600,000). Foreign tax credits under the GILTI basket (80% inclusion rate) further reduce the liability. The $300,000 foreign taxes provide §960 credits.',
    reference: 'IRC §951-964',
  },
  {
    id: 'tcp-elite-010',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'BEAT',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'The Base Erosion and Anti-Abuse Tax (BEAT) targets:',
    options: [
      'All international payments',
      'Deductible payments to foreign related parties that erode the US tax base',
      'Imports only',
      'Foreign income',
    ],
    correctAnswer: 1,
    explanation: 'BEAT (§59A): minimum tax on base erosion payments to foreign related parties. Applies: gross receipts > $500M, base erosion % > 3%. Tax = 10% of modified taxable income (add back base erosion payments) minus regular tax.',
    reference: 'IRC §59A',
  },
  {
    id: 'tcp-elite-011',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-estate',
    topic: 'Estate & Gift Tax',
    subtopic: 'GRAT',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'A Grantor Retained Annuity Trust (GRAT) is used to:',
    options: [
      'Avoid all taxes',
      'Create income',
      'Defer estate tax',
      'Transfer appreciation above the §7520 rate to beneficiaries with minimal gift tax'
    ],
    correctAnswer: 3,
    explanation: 'GRAT: grantor contributes assets, receives annuity for term. Remainder to beneficiaries. Gift = PV of remainder (can be near zero with "zeroed-out" GRAT). Growth above §7520 rate passes gift-tax free. Mortality risk.',
    reference: 'IRC §2702 - GRATs',
  },
  {
    id: 'tcp-elite-012',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-estate',
    topic: 'Estate & Gift Tax',
    subtopic: 'IDGT',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Evaluation',
    question: 'An Intentionally Defective Grantor Trust (IDGT) provides:',
    options: [
      'Estate freeze with grantor paying income tax on trust income, allowing tax-free growth for beneficiaries',
      'No tax benefits',
      'Income tax deferral',
      'Charitable deduction',
    ],
    correctAnswer: 0,
    explanation: 'IDGT: intentionally "defective" for income tax (grantor trust) but effective for estate/gift tax. Grantor pays income tax (additional gift). Sale to IDGT: no income tax, removes appreciation from estate. Powerful planning tool.',
    reference: 'Grantor Trust Planning',
  },
  {
    id: 'tcp-elite-013',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Section 83(b) Election',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'A Section 83(b) election on restricted stock:',
    options: [
      'Avoids all tax',
      'Defers tax indefinitely',
      'Includes property value in income immediately at grant, converting future appreciation to capital gain',
      'Must be filed within 1 year',
    ],
    correctAnswer: 2,
    explanation: '§83(b) election: include value (minus amount paid) in income at grant, not vesting. File within 30 days. Benefit: future appreciation = capital gain. Risk: forfeit stock, lose tax paid. Can\'t revoke.',
    reference: 'IRC §83(b)',
  },
  {
    id: 'tcp-elite-014',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-qbi',
    topic: 'Qualified Business Income',
    subtopic: 'SSTB Threshold',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Application',
    question: 'Specified Service Trade or Business (SSTB) income phases out QBI deduction when:',
    options: [
      'Any SSTB activity',
      'Revenue exceeds $1 million',
      'Taxable income exceeds threshold ($182,100 single/$364,200 MFJ for 2024) with full phase-out over $50K/$100K',
      'More than 10 employees',
    ],
    correctAnswer: 2,
    explanation: 'SSTB phase-out: below threshold = full deduction. Above threshold: phases out over $50K (S) / $100K (MFJ). Fully phased out = no QBI deduction for SSTB. Non-SSTB uses W-2/UBIA limits above threshold.',
    reference: 'IRC §199A(d)(3)',
  },
  {
    id: 'tcp-elite-015',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'Corporate Taxation',
    subtopic: 'Section 382 Limitation',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'Section 382 limits NOL usage after an ownership change by:',
    options: [
      'Applying an annual limitation equal to FMV of loss corporation times long-term tax-exempt rate',
      'Delaying for 5 years',
      'Eliminating all NOLs',
      'Requiring IRS approval',
    ],
    correctAnswer: 0,
    explanation: '§382 limitation: annual limit = FMV of loss corp × long-term tax-exempt rate. Triggered by 50%+ ownership change in 3-year testing period. NUBIG/NUBIL adjustments. Planning critical in acquisitions.',
    reference: 'IRC §382',
  },
  {
    id: 'tcp-elite-016',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-procedure',
    topic: 'Tax Procedures',
    subtopic: 'Statute of Limitations',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Application',
    question: 'The statute of limitations for IRS assessment is generally:',
    options: [
      'No limit',
      '10 years',
      '1 year',
      '3 years from filing, but 6 years if 25%+ omission, unlimited if fraud',
    ],
    correctAnswer: 3,
    explanation: 'Assessment period: generally 3 years from later of filing or due date. 6 years: 25%+ gross income omission, certain basis overstatements. Unlimited: fraud, failure to file. Can be extended by agreement (Form 872).',
    reference: 'IRC §6501',
  },
  {
    id: 'tcp-elite-017',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-IV',
    topic: 'International Taxation',
    subtopic: 'Foreign Tax Credit Limitation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A U.S. individual shareholder owns 30% of a controlled foreign corporation. The CFC had $1,000,000 of GILTI tested income and $2,000,000 of qualified business asset investment (QBAI). What is the shareholder\'s GILTI inclusion before any deductions?',
    options: [
      '$240,000 — 30% of tested income minus the deemed tangible income return',
      '$300,000 — 30% of total tested income',
      '$600,000 — 30% of QBAI',
      '$0 — individuals are not subject to GILTI',
    ],
    correctAnswer: 0,
    explanation: 'GILTI = tested income − net deemed tangible income return (DTIR). DTIR = 10% × QBAI = 10% × $2,000,000 = $200,000. GILTI at entity level = $1,000,000 − $200,000 = $800,000. Shareholder\'s 30% share = $800,000 × 30% = $240,000. Individual shareholders do not receive the §250 deduction (that benefit is only for C corporation shareholders). The GILTI inclusion is taxed as ordinary income. Foreign tax credits may partially offset the tax under the GILTI basket.',
    reference: 'IRC §904',
  },
  {
    id: 'tcp-elite-018',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Section 1202 QSBS',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'Qualified Small Business Stock (QSBS) exclusion under §1202 allows:',
    options: [
      'Up to 100% exclusion of gain (up to greater of $10M or 10× basis) if held 5+ years',
      '50% exclusion only',
      'Deferral only',
      'No limit'
    ],
    correctAnswer: 0,
    explanation: '§1202 QSBS: 100% exclusion for stock acquired after 9/27/2010. Requirements: C corp, <$50M assets, held 5+ years, active business (not services, finance, etc.). Exclusion = greater of $10M or 10× adjusted basis.',
    reference: 'IRC §1202',
  },
  {
    id: 'tcp-elite-019',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-scorp',
    topic: 'S Corporation',
    subtopic: 'AAA Account',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'The Accumulated Adjustments Account (AAA) for S corporations:',
    options: [
      'Tracks capital contributions',
      'Tracks S corp earnings that can be distributed tax-free, adjusted for income/losses/distributions',
      'Is same as E&P',
      'Only tracks losses',
    ],
    correctAnswer: 1,
    explanation: 'AAA: cumulative S corp income minus losses and distributions. Tax-free distributions from AAA for S corps with C corp E&P. Can go negative (no floor). Ordering: AAA first, then E&P (dividend), then basis.',
    reference: 'IRC §1368(e)(1)',
  },
  {
    id: 'tcp-elite-020',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Itemized Deduction Limits',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Application',
    question: 'Under current law (TCJA), itemized deductions are limited by:',
    options: [
      '$10,000 SALT cap, no overall limit (Pease suspended through 2025)',
      'Pease limitation (3% AGI)',
      'No limits',
      '50% of income',
    ],
    correctAnswer: 0,
    explanation: 'TCJA itemized limits: $10,000 SALT cap (state/local income + property), mortgage interest ($750K acquisition debt), charitable (60% AGI cash), no miscellaneous itemized. Pease limitation suspended. Expires 2026.',
    reference: 'IRC §164(b)(6)',
  },
  {
    id: 'tcp-elite-021',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-credits',
    topic: 'Tax Credits',
    subtopic: 'R&D Credit',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'The Section 41 Research and Development credit calculation uses:',
    options: [
      'Equipment costs only',
      'All R&D spending',
      'Incremental qualified research expenses above base amount, with regular or alternative simplified credit methods',
      'Patent expenses',
    ],
    correctAnswer: 2,
    explanation: '§41 R&D credit: 20% of QREs above base amount (regular), or 14% ASC (simplified). QREs: wages, supplies, contract research (65%). Four-part test: technological uncertainty, process of experimentation, technological in nature, permitted purpose.',
    reference: 'IRC §41',
  },
  {
    id: 'tcp-elite-022',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Partnership Distributions',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'A non-liquidating distribution of property from partnership to partner:',
    options: [
      'Creates immediate gain',
      'Is generally tax-free with carryover basis (limited to partner\'s outside basis)',
      'Uses fair market value basis',
      'Creates loss',
    ],
    correctAnswer: 1,
    explanation: 'Non-liquidating distribution: generally no gain (exception: cash > outside basis, §751 hot assets). Property basis = lesser of partnership basis or partner\'s remaining outside basis. Reduces outside basis.',
    reference: 'IRC §731, §732',
  },
  {
    id: 'tcp-elite-023',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'Corporate Taxation',
    subtopic: 'Worthless Stock Deduction',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'A worthless stock deduction under §165(g) is treated as:',
    options: [
      'Capital loss as if sold on last day of tax year, unless §1244 small business stock',
      'No deduction',
      'Ordinary loss',
      'Itemized deduction',
    ],
    correctAnswer: 0,
    explanation: '§165(g): worthless securities = capital loss on last day of year stock became worthless. §1244: ordinary loss up to $50K/$100K for qualified small business stock. Must prove total worthlessness (difficult).',
    reference: 'IRC §165(g), §1244',
  },
  {
    id: 'tcp-elite-024',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'Form 5471 Requirements',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Application',
    question: 'Form 5471 must be filed by US persons who:',
    options: [
      'Travel abroad',
      'Are officers, directors, or shareholders of certain foreign corporations meeting specific ownership thresholds',
      'Have any foreign investment',
      'Have foreign bank accounts',
    ],
    correctAnswer: 1,
    explanation: 'Form 5471 categories: 1-5 based on US person involvement with foreign corporation. Category 4/5: US shareholders of CFC (10%+ owners). Reports: income, transactions, ownership. Significant penalties for non-filing ($10K+).',
    reference: 'IRC §6038, §6046',
  },
  {
    id: 'tcp-elite-025',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-IV',
    topic: 'Property Transactions',
    subtopic: 'Section 1245 Recapture',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A taxpayer sold business real property in an installment sale for $1,000,000. The adjusted basis was $400,000 and selling expenses were $50,000. The buyer paid $200,000 down and will pay $800,000 over 8 years. What is the gross profit percentage and the gain recognized in year 1?',
    options: [
    'Gross profit percentage is 55%; year 1 gain is $110,000',
    'Gross profit percentage is 60%; year 1 gain is $120,000',
    'Gross profit percentage is 55%; year 1 gain is $55,000',
    'Gross profit percentage is 80%; year 1 gain is $160,000',
    ],
    correctAnswer: 0,
    explanation: 'Gross profit = selling price ($1,000,000) − adjusted basis ($400,000) − selling expenses ($50,000) = $550,000. Contract price = $1,000,000 (selling price less assumed mortgages, if any — none here). Gross profit percentage = $550,000 ÷ $1,000,000 = 55%. Year 1 payment = $200,000 down. Year 1 gain = $200,000 × 55% = $110,000. Each subsequent payment of $100,000/year would recognize $55,000 of gain (55% × $100,000). Interest on the installment payments is reported separately.',
    reference: 'IRC §1245',
  },
  {
    id: 'tcp-elite-026',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Wash Sale - Related Parties',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'The wash sale rule applies to purchases by:',
    options: [
      'Anyone',
      'Taxpayer, spouse, or entities controlled by taxpayer',
      'Taxpayer only',
      'Unrelated parties',
    ],
    correctAnswer: 1,
    explanation: 'Wash sale extends to: taxpayer, spouse (MFJ), IRAs/Roth of taxpayer, entities controlled by taxpayer. Cannot sell at loss in taxable account and buy in IRA within 61 days. Basis adjustment follows rules.',
    reference: 'IRC §1091',
  },
  {
    id: 'tcp-elite-027',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-scorp',
    topic: 'S Corporation',
    subtopic: 'Shareholder Debt Basis',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'An S corporation shareholder receives debt basis from:',
    options: [
      'Third-party loans to corp',
      'Guarantees of corporate debt',
      'Direct loans from shareholder to corporation only',
      'All corporate borrowing'
    ],
    correctAnswer: 2,
    explanation: 'Debt basis: only direct shareholder loans to S corp. Not: loans from third parties (even if guaranteed), loans to related entities. Back-to-back loans may qualify. Restored before stock basis when income flows through.',
    reference: 'IRC §1366(d)(1)(B)',
  },
  {
    id: 'tcp-elite-028',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-procedure',
    topic: 'Tax Procedures',
    subtopic: 'Penalty Abatement',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Application',
    question: 'First-time penalty abatement (FTA) requires:',
    options: [
      'Reasonable cause always',
      'Hardship only',
      'Clean compliance history for prior 3 years, current compliance, and no prior FTA',
      'Payment in full',
    ],
    correctAnswer: 2,
    explanation: 'FTA requirements: no penalties in prior 3 years, filed (or valid extension) all returns, paid or arranged to pay. Administrative waiver - no reasonable cause needed. One-time use. Covers late filing, late payment, FTD.',
    reference: 'IRM 20.1.1.3.6.1',
  },
  {
    id: 'tcp-elite-029',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-estate',
    topic: 'Estate & Gift Tax',
    subtopic: 'GST Tax',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'The generation-skipping transfer (GST) tax applies to:',
    options: [
      'Income transfers',
      'All gifts to grandchildren',
      'Estate tax only',
      'Transfers to skip persons that would otherwise avoid transfer tax at a generation',
    ],
    correctAnswer: 3,
    explanation: 'GST tax (§2601): flat rate (40%) on transfers to skip persons (2+ generations below). Types: direct skip, taxable termination, taxable distribution. GST exemption ($13.61M 2024). No portability. Trust planning critical.',
    reference: 'IRC §2601-2664',
  },
  {
    id: 'tcp-elite-030',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'HSA Advantages',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Application',
    question: 'Health Savings Accounts provide triple tax benefit through:',
    options: [
      'Deductions only',
      'Tax-deductible contributions, tax-free growth, and tax-free qualified medical expense withdrawals',
      'Employer contributions only',
      'State tax benefits only',
    ],
    correctAnswer: 1,
    explanation: 'HSA triple tax benefit: (1) above-the-line deduction for contributions, (2) tax-free investment growth, (3) tax-free withdrawals for qualified medical. No use-it-or-lose-it. Rolls over. Post-65: non-medical taxed as ordinary (no penalty).',
    reference: 'IRC §223',
  },
];
