// TCP Depth Questions - Batch 3
// Focus: International tax (TCP-I/TCP-II), QBI, retirement deep-dive, compensation planning

import { Question } from '../../../types';

export const TCP_QUESTIONS_DEPTH_3: Question[] = [
  // ==========================================
  // TCP-I: INTERNATIONAL INDIVIDUAL TAX
  // ==========================================
  {
    id: 'tcp-d3-001',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'Foreign Tax Credit',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A U.S. citizen working abroad earns $180,000 in foreign wages and pays $36,000 in foreign income taxes. For 2025, the maximum foreign earned income exclusion is approximately $130,000. If the taxpayer elects the exclusion, the foreign tax credit is computed on:',
    options: [
      'Only the taxes attributable to income above the exclusion amount ($50,000)',
      'Zero — the exclusion and credit cannot both be used',
      'The full $36,000 of foreign taxes paid',
      'The lesser of $36,000 or the U.S. tax on $180,000',
    ],
    correctAnswer: 0,
    explanation: 'Under IRC §911 and §901, a taxpayer who elects the foreign earned income exclusion cannot claim the foreign tax credit on the excluded income. The credit is limited to taxes attributable to non-excluded income: ($180,000 - $130,000) / $180,000 × $36,000 = $10,000 eligible for the credit. No double benefit is allowed.',
    reference: 'IRC §911(d)(6); §901',
  },
  {
    id: 'tcp-d3-002',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'FBAR Reporting',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'A U.S. person must file an FBAR (FinCEN Report 114) if the aggregate value of all foreign financial accounts exceeded what threshold at any time during the calendar year?',
    options: [
      '$100,000',
      '$5,000',
      '$10,000',
      '$50,000',
    ],
    correctAnswer: 2,
    explanation: 'The FBAR filing requirement applies when the aggregate value of all foreign financial accounts exceeds $10,000 at any time during the year. The report is filed with FinCEN (not the IRS) by April 15 (auto-extended to October 15). Willful failure to file can result in penalties up to $100,000 or 50% of the account balance per violation.',
    reference: '31 USC §5314; 31 CFR §1010.350',
  },
  {
    id: 'tcp-d3-003',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'FATCA',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under FATCA (Form 8938), a single taxpayer living in the U.S. must report specified foreign financial assets if the total value exceeds:',
    options: [
      '$200,000 at any time during the year',
      '$10,000 at any time during the year',
      '$50,000 on the last day of the year or $75,000 at any time during the year',
      '$100,000 on the last day of the year',
    ],
    correctAnswer: 2,
    explanation: 'FATCA (IRC §6038D) requires Form 8938 when specified foreign financial assets exceed: Single in U.S.: $50,000 (year-end) or $75,000 (any time). MFJ in U.S.: $100,000 / $150,000. Single abroad: $200,000 / $300,000. MFJ abroad: $400,000 / $600,000. This is separate from the FBAR ($10,000 threshold).',
    reference: 'IRC §6038D',
  },
  {
    id: 'tcp-d3-004',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'Controlled Foreign Corporations',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §951A, a U.S. shareholder of a controlled foreign corporation (CFC) must include in gross income their global intangible low-taxed income (GILTI). GILTI is computed as:',
    options: [
      'All foreign income of the CFC',
      'Net CFC tested income minus 10% of qualified business asset investment (QBAI)',
      'Subpart F income plus the CFC\'s effectively connected income',
      'Net CFC tested income minus a foreign tax credit',
    ],
    correctAnswer: 1,
    explanation: 'GILTI = Net CFC Tested Income - (10% × QBAI) - Interest Expense. The 10% return on QBAI (tangible depreciable assets) represents routine returns that are not subject to GILTI. Only the excess (intangible returns) is included. A 50% deduction under §250 (reduced to 37.5% after 2025) effectively reduces the tax rate on GILTI for domestic corporations.',
    reference: 'IRC §951A',
  },

  // ==========================================
  // TCP-I: QBI DEDUCTION DEEP-DIVE
  // ==========================================
  {
    id: 'tcp-d3-005',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-qbi',
    topic: 'Qualified Business Income',
    subtopic: 'Section 199A Basics',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The qualified business income (QBI) deduction under Section 199A allows eligible taxpayers to deduct up to what percentage of qualified business income?',
    options: [
      '10%',
      '15%',
      '25%',
      '20%',
    ],
    correctAnswer: 3,
    explanation: 'Section 199A allows a deduction of up to 20% of qualified business income from pass-through entities (sole proprietorships, partnerships, S corporations, certain trusts). The deduction is limited to the lesser of 20% of QBI or 20% of taxable income (less net capital gain). Made permanent by OBBBA (H.R. 1).',
    reference: 'IRC §199A(a)',
  },
  {
    id: 'tcp-d3-006',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-qbi',
    topic: 'Qualified Business Income',
    subtopic: 'SSTB Limitations',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A CPA firm (specified service trade or business) has QBI of $500,000. The sole owner\'s taxable income before the QBI deduction is $450,000 (filing jointly). What is the QBI deduction?',
    options: [
      '$90,000 (20% of taxable income)',
      '$100,000 (20% of QBI)',
      '$50,000 (partial phase-out)',
      '$0 — SSTBs are fully phased out above $394,600 (MFJ) for 2025',
    ],
    correctAnswer: 3,
    explanation: 'For specified service trades or businesses (SSTBs — accounting, law, health, consulting, athletics, performing arts), the QBI deduction is fully phased out when taxable income exceeds $394,600 + $100,000 = $494,600 (MFJ, 2025 estimate). At $450,000, the deduction is partly phased out. However, the exact calculation shows that with income above $394,600, the SSTB deduction is partially phased out, reducing the QBI and W-2/capital limitations proportionally. At $450,000, the phase-out ratio reduces available QBI significantly. [Note: the specific 2025 thresholds are indexed.]',
    reference: 'IRC §199A(d)',
  },
  {
    id: 'tcp-d3-007',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-qbi',
    topic: 'Qualified Business Income',
    subtopic: 'W-2/Capital Limitation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'For taxpayers above the taxable income threshold, the QBI deduction for a non-SSTB is limited to the greater of:',
    options: [
      '100% of W-2 wages',
      '25% of W-2 wages only',
      '50% of W-2 wages, or 25% of W-2 wages plus 2.5% of the unadjusted basis of qualified property',
      '50% of qualified business income',
    ],
    correctAnswer: 2,
    explanation: 'Above the income threshold ($191,950 single / $383,900 MFJ for 2024, indexed), the 20% QBI deduction is limited to the greater of: (1) 50% of the entity\'s W-2 wages, OR (2) 25% of W-2 wages plus 2.5% of the unadjusted basis immediately after acquisition (UBIA) of qualified property. This limitation phases in over a $50,000/$100,000 range.',
    reference: 'IRC §199A(b)(2)',
  },

  // ==========================================
  // TCP-I: RETIREMENT PLANNING DEPTH
  // ==========================================
  {
    id: 'tcp-d3-008',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-retirement',
    topic: 'Retirement Planning',
    subtopic: '401(k) Contribution Limits',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For 2025, the maximum elective deferral to a 401(k) plan for an employee under age 50 is:',
    options: [
      '$25,000',
      '$22,500',
      '$20,500',
      '$23,500',
    ],
    correctAnswer: 3,
    explanation: 'The 2025 elective deferral limit for 401(k), 403(b), and most 457 plans is $23,500. Catch-up contributions for age 50+ add $7,500 (total $31,000). Under SECURE 2.0, individuals ages 60-63 get an enhanced catch-up of $11,250 (total $34,750). Employer matching and profit sharing are separate from the employee deferral limit.',
    reference: 'IRC §402(g); IRS Notice 2024-80',
  },
  {
    id: 'tcp-d3-009',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-retirement',
    topic: 'Retirement Planning',
    subtopic: 'Roth IRA Eligibility',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For 2025, the MAGI phase-out range for Roth IRA contributions for married filing jointly is:',
    options: [
      '$236,000 - $246,000',
      '$218,000 - $228,000',
      '$150,000 - $160,000',
      '$230,000 - $240,000',
    ],
    correctAnswer: 0,
    explanation: 'For 2025, the Roth IRA contribution phase-out for MFJ is $236,000-$246,000 MAGI. Above $246,000, no direct Roth contribution is allowed (back-door Roth conversion remains available). Single/HoH: $150,000-$165,000. The maximum contribution is $7,000 ($8,000 if age 50+).',
    reference: 'IRC §408A(c)(3); IRS Notice 2024-80',
  },
  {
    id: 'tcp-d3-010',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-retirement',
    topic: 'Retirement Planning',
    subtopic: 'SEP IRA',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A self-employed individual has net self-employment income of $200,000 (after the self-employment tax deduction). What is the maximum SEP-IRA contribution?',
    options: [
      '$50,000',
      '$69,000',
      '$23,500',
      '$66,000',
    ],
    correctAnswer: 0,
    explanation: 'SEP contributions are limited to the lesser of 25% of compensation or $70,000 (2025). For self-employed individuals, "compensation" is net self-employment earnings reduced by 50% of SE tax. At $200,000 net SE income: 25% × $200,000 = $50,000 (within the $70,000 cap). The actual calculation requires reducing by half of SE tax first, but the simplified answer is $50,000.',
    reference: 'IRC §408(k); §404(h)',
  },
  {
    id: 'tcp-d3-011',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-retirement',
    topic: 'Retirement Planning',
    subtopic: 'Early Distribution Penalty',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Which of the following distributions from a traditional IRA before age 59½ is exempt from the 10% early distribution penalty?',
    options: [
      'Distribution to purchase a new car',
      'Distribution to fund a vacation',
      'Distribution for qualified higher education expenses of the taxpayer\'s child',
      'Distribution to pay credit card debt',
    ],
    correctAnswer: 2,
    explanation: 'IRC §72(t) exceptions to the 10% early withdrawal penalty include: death, disability, substantially equal periodic payments (72t/SEPP), qualified higher education expenses (IRA only), first-time home purchase ($10,000 lifetime, IRA only), IRS levy, qualified reservist, and birth/adoption ($5,000). Car purchases and personal expenses are not excepted.',
    reference: 'IRC §72(t)(2)(E)',
  },

  // ==========================================
  // TCP-I: COMPENSATION PLANNING
  // ==========================================
  {
    id: 'tcp-d3-012',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-compensation',
    topic: 'Compensation Planning',
    subtopic: 'Stock Options — ISO',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An employee exercises an incentive stock option (ISO) and holds the stock. At exercise, the stock FMV is $50 and the option price is $20. For regular tax purposes, what is the tax consequence at exercise?',
    options: [
      '$30 per share ordinary income',
      '$50 per share ordinary income',
      'No regular tax consequence, but $30 per share is an AMT preference item',
      '$30 per share capital gain',
    ],
    correctAnswer: 2,
    explanation: 'ISOs under §422 receive favorable treatment: no regular income tax at exercise (unlike NQSOs). However, the spread at exercise ($50 - $20 = $30) is an adjustment for AMT purposes. To receive long-term capital gain treatment on eventual sale, the stock must be held 2+ years from grant date and 1+ year from exercise date. A disqualifying disposition converts the spread to ordinary income.',
    reference: 'IRC §422; §56(b)(3)',
  },
  {
    id: 'tcp-d3-013',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-compensation',
    topic: 'Compensation Planning',
    subtopic: 'Stock Options — NQSO',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An employee exercises a nonqualified stock option (NQSO) when the stock FMV is $80 and the exercise price is $30. What are the tax consequences at exercise?',
    options: [
      '$80 per share of ordinary income',
      'No tax consequence until the stock is sold',
      '$50 per share of ordinary compensation income, and the employer gets a $50 deduction',
      '$50 per share of capital gain',
    ],
    correctAnswer: 2,
    explanation: 'NQSOs create ordinary income at exercise equal to the spread (FMV minus exercise price). The employer receives a corresponding deduction under §83(h). The employee\'s basis in the stock becomes FMV at exercise ($80). Subsequent appreciation/depreciation is capital gain/loss. FICA/FUTA also apply to the spread.',
    reference: 'IRC §83(a); §83(h)',
  },
  {
    id: 'tcp-d3-014',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-compensation',
    topic: 'Compensation Planning',
    subtopic: 'Section 83(b) Election',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An employee receives restricted stock with a FMV of $100,000 subject to a 3-year vesting requirement. The employee files a §83(b) election within 30 days. What is the immediate tax consequence?',
    options: [
      'The $100,000 FMV (minus any amount paid) is included in ordinary income immediately',
      'No tax until the stock vests in 3 years',
      'The employer must withhold 22% of the FMV',
      'The employee recognizes capital gain of $100,000',
    ],
    correctAnswer: 0,
    explanation: 'A §83(b) election includes the FMV of restricted stock (minus any amount paid) in ordinary income at the time of receipt rather than at vesting. The benefit: all future appreciation is taxed as capital gain (not ordinary income). The risk: if the stock is forfeited, no deduction is allowed for the tax previously paid. The election must be filed within 30 days of transfer.',
    reference: 'IRC §83(b)',
  },

  // ==========================================
  // TCP-III: ADDITIONAL ENTITY QUESTIONS
  // ==========================================
  {
    id: 'tcp-d3-015',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Accumulated Earnings Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The accumulated earnings tax under IRC §531 is imposed at what rate on accumulated taxable income beyond reasonable business needs?',
    options: [
      '15%',
      '20%',
      '37%',
      '21% (same as the corporate rate)',
    ],
    correctAnswer: 1,
    explanation: 'The accumulated earnings tax is 20% of accumulated taxable income (ATI). ATI = adjusted taxable income minus dividends paid deduction minus the accumulated earnings credit ($250,000 for most corporations, $150,000 for personal service corporations). The tax targets corporations that accumulate earnings to help shareholders avoid individual income tax on dividends.',
    reference: 'IRC §531; §535',
  },
  {
    id: 'tcp-d3-016',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-c-corp',
    topic: 'C Corporation Taxation',
    subtopic: 'Personal Holding Company',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A corporation is classified as a personal holding company (PHC) if it meets both the stock ownership test and the income test. The income test requires that what percentage of adjusted ordinary gross income consists of PHC income?',
    options: [
      '100%',
      'More than 60%',
      'More than 50%',
      'More than 75%',
    ],
    correctAnswer: 1,
    explanation: 'A personal holding company under §542 must meet: (1) Stock test — more than 50% of outstanding stock is owned (directly or constructively) by 5 or fewer individuals at any time during the last half of the tax year, AND (2) Income test — at least 60% of adjusted ordinary gross income is PHC income (dividends, interest, rents below threshold, royalties, personal service contracts). The PHC tax is 20% on undistributed PHC income.',
    reference: 'IRC §542',
  },

  // ==========================================
  // TCP-II: PARTNERSHIP SPECIAL ALLOCATIONS
  // ==========================================
  {
    id: 'tcp-d3-017',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-partnerships',
    topic: 'Partnership Taxation',
    subtopic: 'Special Allocations',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'For a special allocation of partnership income or loss to be respected for tax purposes, it must:',
    options: [
      'Have substantial economic effect under IRC §704(b) regulations',
      'Be approved by the IRS in advance',
      'Be agreed upon by all partners in writing',
      'Be proportional to each partner\'s capital contribution',
    ],
    correctAnswer: 0,
    explanation: 'IRC §704(b) requires that allocations have "substantial economic effect." This has two prongs: (1) Economic effect — allocations must be consistent with the underlying economic arrangement (partners bear the economic impact), requiring capital account maintenance, liquidation per capital accounts, and deficit restoration or QIO. (2) Substantiality — a reasonable possibility that allocations will substantially affect the dollar amounts received independent of tax consequences.',
    reference: 'IRC §704(b); Treas. Reg. §1.704-1(b)(2)',
  },
  {
    id: 'tcp-d3-018',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-partnerships',
    topic: 'Partnership Taxation',
    subtopic: 'Section 754 Election',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a partnership makes a §754 election and a partner purchases an interest from an existing partner, what adjustment is made?',
    options: [
      'A §743(b) adjustment is made to the basis of partnership assets with respect to the transferee partner only',
      'No adjustment — the election only applies to distributions',
      'The partnership\'s inside basis in all assets is stepped up to FMV',
      'The selling partner\'s capital account is stepped up',
    ],
    correctAnswer: 0,
    explanation: 'A §754 election with a transfer of a partnership interest triggers a §743(b) basis adjustment: the difference between the transferee\'s outside basis (purchase price) and their proportionate share of the partnership\'s inside basis. This adjustment is personal to the transferee partner — other partners are unaffected. For distributions, §734(b) adjustments apply instead.',
    reference: 'IRC §754; §743(b)',
  },

  // ==========================================
  // TCP-V: TAX COURT AND APPEALS
  // ==========================================
  {
    id: 'tcp-d3-019',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-practice-procedures',
    topic: 'Tax Practice',
    subtopic: 'Forums for Tax Disputes',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'In which forum can a taxpayer challenge a tax deficiency WITHOUT first paying the disputed tax?',
    options: [
      'U.S. District Court',
      'U.S. Bankruptcy Court',
      'U.S. Court of Federal Claims',
      'U.S. Tax Court',
    ],
    correctAnswer: 3,
    explanation: 'The U.S. Tax Court is the only forum where a taxpayer can challenge a deficiency without first paying the tax. The taxpayer must file a petition within 90 days of the statutory notice of deficiency (90-day letter). U.S. District Court and Court of Federal Claims are refund forums — the taxpayer must pay first, then sue for a refund.',
    reference: 'IRC §6213(a)',
  },
  {
    id: 'tcp-d3-020',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-practice-procedures',
    topic: 'Tax Practice',
    subtopic: 'Audit Selection',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The IRS uses which scoring system to identify individual returns with the highest likelihood of significant tax changes?',
    options: [
      'Risk Assessment Score (RAS)',
      'Taxpayer Compliance Rating (TCR)',
      'Discriminant Information Function (DIF) score',
      'Audit Priority Index (API)',
    ],
    correctAnswer: 2,
    explanation: 'The IRS uses the Discriminant Information Function (DIF) system to assign numeric scores to returns based on the potential for change. Higher DIF scores indicate greater audit potential. Returns are also selected through information matching (W-2s, 1099s), related examinations, special projects, and random sampling (National Research Program).',
    reference: 'IRM 4.1.3',
  },

  // ==========================================
  // TCP-IV: TRUST TAXATION
  // ==========================================
  {
    id: 'tcp-d3-021',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-trusts',
    topic: 'Trust Taxation',
    subtopic: 'Simple vs Complex Trusts',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A simple trust is required to:',
    options: [
      'Make mandatory charitable contributions',
      'Distribute all income currently, cannot make charitable contributions, and cannot distribute corpus',
      'Accumulate income for future distribution',
      'Distribute income and principal at the trustee\'s discretion',
    ],
    correctAnswer: 1,
    explanation: 'A simple trust: (1) must distribute all income currently, (2) cannot make charitable contributions from trust income, and (3) cannot distribute corpus (principal). It receives a distribution deduction equal to distributable net income (DNI), and beneficiaries are taxed on the distributed income. A complex trust is any trust that does not qualify as simple.',
    reference: 'IRC §651; §652',
  },
  {
    id: 'tcp-d3-022',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-trusts',
    topic: 'Trust Taxation',
    subtopic: 'Compressed Tax Brackets',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'For 2025, trusts and estates reach the highest marginal tax rate (37%) at approximately what taxable income level?',
    options: [
      '$250,000',
      '$15,200',
      '$50,000',
      '$100,000',
    ],
    correctAnswer: 1,
    explanation: 'Trusts and estates have severely compressed tax brackets. For 2025, the 37% bracket begins at approximately $15,200 of taxable income (compared to $609,350 for single individuals). This creates a strong incentive to distribute income to beneficiaries who are typically in lower brackets. Distributable net income (DNI) controls the character and amount of the distribution deduction.',
    reference: 'IRC §1(e); Rev. Proc. 2024-40',
  },

  // ==========================================
  // TCP-I: ADDITIONAL INDIVIDUAL TAX
  // ==========================================
  {
    id: 'tcp-d3-023',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-se-tax',
    topic: 'Individual Taxation',
    subtopic: 'Self-Employment Tax',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Self-employment tax for 2025 consists of:',
    options: [
      '15.3% on all net self-employment income with no cap',
      '12.4% Social Security tax (up to the wage base) plus 2.9% Medicare tax on all net SE income',
      '6.2% Social Security tax plus 1.45% Medicare tax',
      '7.65% on all net self-employment income',
    ],
    correctAnswer: 1,
    explanation: 'Self-employment tax has two components: (1) Social Security: 12.4% on net SE income up to the wage base ($176,100 for 2025), and (2) Medicare: 2.9% on all net SE income with no cap. An additional 0.9% Medicare surtax applies above $200,000 ($250,000 MFJ). The taxpayer may deduct 50% of SE tax as an above-the-line deduction.',
    reference: 'IRC §1401; §1402',
  },
  {
    id: 'tcp-d3-024',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-amt',
    topic: 'Individual Tax Planning',
    subtopic: 'Alternative Minimum Tax',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The AMT exemption amount for a married filing jointly taxpayer for 2025 is approximately:',
    options: [
      '$85,700',
      '$118,100',
      '$137,000',
      '$133,300',
    ],
    correctAnswer: 3,
    explanation: 'For 2025, the AMT exemption amounts are approximately: $88,100 (single), $133,300 (MFJ), and $66,650 (MFS). The exemption phases out at 25 cents per dollar of AMTI above $626,350 (single) / $1,252,700 (MFJ). TCJA significantly increased the exemption and phase-out thresholds, greatly reducing the number of taxpayers affected by AMT. Made permanent by OBBBA.',
    reference: 'IRC §55(d); Rev. Proc. 2024-40',
  },
  {
    id: 'tcp-d3-025',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Section 1250 Recapture',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A taxpayer sells a commercial building for $800,000. The original cost was $600,000, accumulated straight-line depreciation is $150,000, and the adjusted basis is $450,000. What is the maximum tax rate on the gain attributable to the depreciation?',
    options: [
      '20% long-term capital gains rate',
      '0% — depreciation recapture does not apply to real property',
      '28.8% including NIIT',
      '25% unrecaptured Section 1250 gain rate',
    ],
    correctAnswer: 3,
    explanation: 'For real property depreciated using the straight-line method, §1250 does not require ordinary income recapture (only excess depreciation over straight-line is recaptured as ordinary, which is $0 with straight-line). However, "unrecaptured §1250 gain" — the lesser of the depreciation taken ($150,000) or the gain ($350,000) — is taxed at a maximum rate of 25%. The remaining $200,000 gain is taxed at regular LTCG rates (0/15/20%).',
    reference: 'IRC §1(h)(1)(E); §1250',
  },
];
