/**
 * CPA TCP Section - Questions Depth Batch 9
 * Blueprint Area: TCP-II (Entity Tax Compliance)
 * Topics: C Corporation Tax, S Corporation Tax, Partnership Tax, Trust/Estate Tax
 */

import { Question } from '../../../types';

export const TCP_QUESTIONS_DEPTH_9: Question[] = [
  {
    id: 'tcp-d9-001',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Corporate AMT',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the Inflation Reduction Act of 2022, the Corporate Alternative Minimum Tax (CAMT) applies to:',
    options: [
      'All corporations regardless of size',
      'Applicable corporations with average annual adjusted financial statement income (AFSI) exceeding $1 billion over a 3-year period — they must pay the greater of the 15% minimum tax on AFSI or their regular corporate income tax',
      'Only S corporations',
      'Corporations with less than $100 million in revenue',
    ],
    correctAnswer: 1,
    explanation: 'Corporate Alternative Minimum Tax (CAMT) — IRC §55 (as amended by IRA 2022): Applicable corporations: average annual adjusted financial statement income (AFSI) exceeding $1 billion over the 3 tax years ending with the current year. For U.S. members of foreign-parented groups: $100 million U.S. AFSI threshold. AFSI is based on the income reported on the corporation\'s applicable financial statements (typically GAAP financial statements filed with the SEC). Adjustments: (1) add back certain deductions (depreciation differences between book and tax), (2) adjust for CAMT foreign tax credits, (3) adjust for NOLs (limited), (4) financial statement NOL deduction limited to 80% of AFSI. Tax rate: 15% of AFSI minus CAMT foreign tax credits. Corporation pays the GREATER of: (a) regular corporate income tax (21%), or (b) CAMT (15% tentative minimum tax minus regular tax). CAMT credit: excess CAMT over regular tax creates a credit that can offset regular tax liability in future years (when regular tax exceeds CAMT). Effective for tax years beginning after December 31, 2022.',
    reference: 'IRC §55-59 (as amended by IRA 2022)',
  },
  {
    id: 'tcp-d9-002',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Stock Redemption — §302',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A stock redemption under IRC §302 is treated as a sale or exchange (capital gain) rather than a dividend distribution when:',
    options: [
      'Any time the corporation redeems stock',
      'The redemption meets one of the §302(b) tests: substantially disproportionate redemption (the shareholder\'s ownership drops below 50% and their percentage is less than 80% of their pre-redemption percentage), complete termination of interest, or the redemption is not essentially equivalent to a dividend (meaningful reduction test)',
      'The shareholder has held the stock for more than one year',
      'The corporation uses retained earnings for the redemption',
    ],
    correctAnswer: 1,
    explanation: 'IRC §302 stock redemptions — sale vs. dividend treatment: §302(b)(1) — Not essentially equivalent to a dividend: requires a "meaningful reduction" in the shareholder\'s proportionate interest (includes voting power, equity participation, and rights to earnings). Attribution rules (§318) apply. §302(b)(2) — Substantially disproportionate: after the redemption, the shareholder must own: (a) less than 50% of total voting power, AND (b) less than 80% of their pre-redemption voting stock percentage, AND (c) less than 80% of their pre-redemption common stock percentage. §302(b)(3) — Complete termination: all of the shareholder\'s stock is redeemed; family attribution under §318(a)(1) may be waived under §302(c)(2) if shareholder: has no interest in the corporation for 10 years (other than as creditor), does not acquire any interest within 10 years, files an agreement to notify IRS if they do. §302(b)(4) — Partial liquidation (non-corporate shareholders only): genuine contraction of the corporation\'s business. If none of the §302(b) tests are met: treated as §301 distribution (dividend to extent of E&P).',
    reference: 'IRC §302; §318',
  },
  {
    id: 'tcp-d9-003',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Built-In Gains Tax',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'The built-in gains (BIG) tax under IRC §1374 applies when:',
    options: [
      'An S corporation sells any asset at a gain',
      'A C corporation converts to S corporation status, and during the 5-year recognition period following the conversion, the S corporation recognizes gain on assets that had built-in gain at the time of conversion — the tax is imposed at the highest corporate rate (21%) on the net recognized built-in gain',
      'An S corporation has one shareholder',
      'An S corporation has been in existence for more than 10 years',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1374 Built-In Gains (BIG) Tax: Purpose: prevent C corporations from converting to S corporation status to avoid corporate-level tax on unrealized gains. Trigger: C corp converts to S corp (or S corp acquires C corp assets in a tax-free transaction under §381). Recognition period: 5 years from the date of conversion (was 10 years, reduced to 7 years by ARRA 2009, to 5 years permanently by PATH Act 2015). Tax: 21% (highest corporate rate) on the lesser of: (a) net recognized built-in gain (NRBIG) — gains on assets with built-in gain at conversion, reduced by built-in losses recognized during the period, or (b) taxable income as if the corporation were a C corporation. Limitations: the tax applies only to the built-in gain at the conversion date (i.e., FMV minus basis at conversion); any appreciation after conversion is not subject to BIG tax. The BIG tax is a corporate-level tax passed through to shareholders as a reduction in income. After 5 years: BIG tax no longer applies; gains taxed only at the shareholder level.',
    reference: 'IRC §1374',
  },
  {
    id: 'tcp-d9-004',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Excess Net Passive Income Tax',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'An S corporation is subject to the excess net passive income (ENPI) tax under §1375 when:',
    options: [
      'It has any passive income',
      'The S corporation has accumulated earnings and profits (E&P) from prior C corporation years, AND passive investment income (rents, royalties, dividends, interest, annuities, gains from sales of securities) exceeds 25% of gross receipts',
      'The S corporation has losses',
      'The S corporation elects to be taxed at the entity level',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1375 Excess Net Passive Income (ENPI) Tax: Both conditions must exist: (1) The S corporation has accumulated earnings and profits (E&P) from a prior C corporation period (S corporations that have always been S corps cannot have E&P), AND (2) passive investment income exceeds 25% of gross receipts. Passive investment income includes: rents (unless significant services are provided), royalties, dividends, interest, annuities, gains from sales/exchanges of stock or securities. Tax: corporate rate (21%) × excess net passive income. ENPI = net passive income × (passive investment income − 25% of gross receipts) ÷ passive investment income. Termination risk: if passive investment income exceeds 25% of gross receipts for 3 consecutive years AND the corporation has E&P, the S election is automatically terminated (§1362(d)(3)). Solution: distribute the accumulated E&P to shareholders (taxable as dividend) to eliminate one of the two conditions.',
    reference: 'IRC §1375; §1362(d)(3)',
  },
  {
    id: 'tcp-d9-005',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Partnership Termination — §708',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under current law (post-TCJA), a partnership terminates for federal tax purposes only when:',
    options: [
      '50% or more of total interests are sold or exchanged within 12 months',
      'No part of any business, financial operation, or venture of the partnership continues to be carried on by any of its partners (i.e., the partnership ceases all operations)',
      'A new partner joins',
      'The partnership fails to file Form 1065',
    ],
    correctAnswer: 1,
    explanation: 'IRC §708 Partnership Termination (post-TCJA): Before TCJA: a partnership terminated for tax purposes if (1) no business continued to be carried on, OR (2) 50% or more of total interests in partnership capital and profits were sold or exchanged within a 12-month period ("technical termination"). TCJA eliminated the technical termination rule, effective for tax years beginning after December 31, 2017. Current law: a partnership terminates for tax purposes ONLY when no part of any business, financial operation, or venture of the partnership continues to be carried on by any of its partners. Practical effect: a sale of 50%+ of partnership interests no longer triggers termination, meaning the partnership\'s tax year does not close (no short-year return), elections are not affected, and depreciation methods continue unchanged. Mergers and divisions: special rules under §708(b)(2) still apply — in a merger, the resulting partnership is a continuation of the partnership whose members own more than 50% interest.',
    reference: 'IRC §708',
  },
  {
    id: 'tcp-d9-006',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Hot Assets — §751',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a partner sells their partnership interest, IRC §751 requires that gain or loss attributable to "hot assets" be treated as:',
    options: [
      'Capital gain or loss',
      'Ordinary income or loss — hot assets include substantially appreciated inventory and unrealized receivables (which include recapture amounts under §§1245, 1250)',
      'Tax-exempt income',
      'Passive activity income',
    ],
    correctAnswer: 1,
    explanation: 'IRC §751 Hot Assets — sale of partnership interest: Hot assets: (1) Unrealized receivables — includes: accounts receivable for services or goods (cash-basis taxpayer), depreciation recapture amounts (§1245, §1250), mining exploration expenditures, certain farm recapture, market discount bonds. Note: "unrealized receivables" is broadly defined to include recapture amounts even if the underlying asset has been sold. (2) Inventory items — includes substantially appreciated inventory (FMV exceeds 120% of adjusted basis) AND items held primarily for sale to customers. Effect on sale of partnership interest: the portion of gain/loss attributable to hot assets is treated as ordinary income/loss (not capital gain). The remaining gain/loss (attributable to §1231 assets, goodwill, capital assets) retains capital character. Calculation: (1) determine the selling partner\'s share of hot asset value vs. basis, (2) ordinary gain/loss = hot asset share of gain/loss, (3) capital gain/loss = total gain/loss minus ordinary portion. Purpose: prevents partners from converting ordinary income into capital gain through the sale of a partnership interest.',
    reference: 'IRC §751',
  },
  {
    id: 'tcp-d9-007',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Distributable Net Income (DNI)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Distributable net income (DNI) for a trust or estate serves which critical tax function?',
    options: [
      'It determines the estate tax liability',
      'It limits the deduction available to the trust/estate for distributions to beneficiaries AND determines the character of income to be reported by the beneficiaries on their individual returns — it acts as a ceiling on the income distribution deduction',
      'It determines the trust\'s filing status',
      'It has no impact on either the trust or beneficiaries',
    ],
    correctAnswer: 1,
    explanation: 'Distributable Net Income (DNI) — IRC §643(a): DNI serves two critical functions: (1) Limits the trust/estate\'s income distribution deduction (§651/§661) — the trust can deduct distributions to beneficiaries, but only up to DNI. (2) Determines the character and amount of income reportable by beneficiaries — they report their proportionate share of DNI (maintaining the character of the underlying income: ordinary, capital gain, tax-exempt, etc.). DNI calculation: start with Taxable Income, then: add back the personal exemption (§642(b)), add back net tax-exempt interest (minus allocable expenses), subtract capital gains allocated to corpus (unless distributed or used to determine amounts paid/credited to beneficiaries), add back the income distribution deduction itself (avoid circularity). Simple trust (§651-§652): must distribute all income currently, cannot make charitable contributions, cannot distribute corpus → distribution deduction = lesser of DNI or required distribution. Complex trust (§661-§663): may accumulate income, may make charitable contributions, may distribute corpus → distribution deduction = lesser of DNI or actual distributions.',
    reference: 'IRC §643(a); §651-§663',
  },
  {
    id: 'tcp-d9-008',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Trust Tax Rates',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'Trusts and estates reach the highest marginal federal income tax rate (37%) at a taxable income of approximately:',
    options: [
      '$200,000',
      '$14,450 for 2024 — trusts have the most compressed tax brackets of any taxpayer category',
      '$100,000',
      '$600,000',
    ],
    correctAnswer: 1,
    explanation: 'Trust and estate income tax rates (2024): 10% on taxable income up to $3,100; 24% on $3,100-$11,150; 35% on $11,150-$15,200; 37% on taxable income over $15,200. Note: the threshold for the 37% bracket adjusts annually for inflation (approximately $14,450 for 2024). These are the most compressed brackets in the federal tax system — for comparison, individual taxpayers reach 37% at approximately $609,350 (single) or $731,200 (MFJ). This compression creates a strong incentive to: (1) distribute income to beneficiaries in lower brackets (income distribution deduction reduces trust taxable income), (2) time distributions strategically, (3) consider grantor trust treatment where the grantor pays tax at their individual rates. Trusts and estates also pay the 3.8% Net Investment Income Tax (NIIT) on the lesser of: undistributed net investment income or AGI exceeding the threshold ($14,450 for 2024 — same as the 37% bracket). This makes trusts potentially subject to a combined rate of 40.8% (37% + 3.8%) at relatively low income levels.',
    reference: 'IRC §1(e); Rev. Proc. 2023-34',
  },
  {
    id: 'tcp-d9-009',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Accumulated Earnings Tax',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The accumulated earnings tax under IRC §531 is imposed on:',
    options: [
      'All corporations that retain any earnings',
      'C corporations (not S corps, PHCs, or tax-exempt entities) that accumulate earnings beyond the reasonable needs of the business to avoid the individual income tax on dividends — the tax is 20% on accumulated taxable income exceeding the accumulated earnings credit ($250,000 for most corporations, $150,000 for certain personal service corporations)',
      'S corporations that distribute all income',
      'Only public companies',
    ],
    correctAnswer: 1,
    explanation: 'IRC §531-§537 Accumulated Earnings Tax (AET): Tax imposed on C corporations that retain earnings beyond reasonable business needs with the purpose of avoiding shareholder-level tax. Tax rate: 20% (on accumulated taxable income). Accumulated earnings credit: $250,000 for most corporations ($150,000 for personal service corporations) — no AET applies until accumulated E&P exceeds this amount. Reasonable needs of the business: expansion, debt retirement, working capital needs (Bardahl formula — operating cycle method), replacement of plant/equipment, product liability loss reserves. Accumulated taxable income = taxable income minus: federal income taxes, charitable contributions exceeding 10% limit, net capital losses, accumulated earnings credit, dividends-paid deduction. Burden of proof: corporation must justify the retention; IRS must show tax-avoidance purpose (unless accumulation exceeds $250K, which creates a presumption). NOT applicable to: S corporations, personal holding companies (subject to §541 PHC tax instead), tax-exempt organizations, passive foreign investment companies.',
    reference: 'IRC §531-§537',
  },
  {
    id: 'tcp-d9-010',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Personal Holding Company Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A corporation is classified as a Personal Holding Company (PHC) under IRC §542 when:',
    options: [
      'It has only one shareholder',
      'Two tests are met: (1) the stock ownership test — more than 50% of the value of outstanding stock is owned directly or indirectly by 5 or fewer individuals at any time during the last half of the tax year, AND (2) the income test — at least 60% of adjusted ordinary gross income is PHC income (dividends, interest, rents below 50% of AOGI unless certain conditions are met, royalties, personal service contracts income)',
      'It earns any investment income',
      'It has gross receipts exceeding $10 million',
    ],
    correctAnswer: 1,
    explanation: 'IRC §541-§547 Personal Holding Company (PHC) Tax: Two-test classification: (1) Stock ownership test (§542(a)(2)): more than 50% of the value of outstanding stock is owned (directly or constructively under §544) by 5 or fewer individuals at any time during the last half of the tax year. Constructive ownership: family attribution, entity attribution, option attribution. (2) Income test (§542(a)(1)): at least 60% of adjusted ordinary gross income (AOGI) is PHC income — includes: dividends, interest, royalties (unless 50%+ of OGI), rent (unless 50%+ of AOGI and PHC income does not exceed 10% of OGI after rent adjustments), annuities, personal service contracts where someone can designate who performs services. Excludes: tax-exempt corporations, lending companies, certain foreign corporations, S corporations (not subject to PHC tax). PHC tax: 20% of undistributed PHC income. Undistributed PHC income = taxable income minus: federal income taxes, net capital gain (minus taxes thereon), dividends paid (including consent dividends and throwback dividends). Remedy: paying sufficient dividends eliminates the PHC tax.',
    reference: 'IRC §541-§547',
  },
  {
    id: 'tcp-d9-011',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'S Corporation Eligibility',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'To qualify as an S corporation, an entity must meet all of the following requirements EXCEPT:',
    options: [
      'Be a domestic corporation',
      'The corporation may have an unlimited number of shareholders and may include partnerships and C corporations as shareholders',
      'Have only one class of stock (differences in voting rights are permitted)',
      'Have no more than 100 shareholders (family members may elect to be treated as one shareholder)',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1361 S Corporation eligibility requirements: (1) Domestic corporation, (2) Maximum 100 shareholders — family members (within 6 generations) may elect to be treated as a single shareholder under §1361(c)(1), (3) Eligible shareholders only — individuals, estates, certain trusts (grantor trusts, qualified subchapter S trusts (QSSTs), electing small business trusts (ESBTs)), tax-exempt organizations (§401(a) and §501(c)(3)). NOT eligible shareholders: partnerships, C corporations, nonresident aliens. (4) One class of stock — all outstanding shares must have identical rights to distribution and liquidation proceeds. Differences in voting rights are permitted (voting and nonvoting common stock OK). (5) Not an ineligible corporation — certain financial institutions, insurance companies, domestic international sales corporations (DISCs), and certain affiliated groups are ineligible. Election: Form 2553, filed by the 15th day of the 3rd month of the tax year (or at any time during the preceding tax year). Must be signed by all shareholders.',
    reference: 'IRC §1361; §1362',
  },
  {
    id: 'tcp-d9-012',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Guaranteed Payments — §707(c)',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Guaranteed payments to a partner under IRC §707(c):',
    options: [
      'Are treated the same as distributions of partnership income',
      'Are payments to a partner for services or for the use of capital that are determined without regard to the partnership income — they are deductible by the partnership and taxable to the partner as ordinary income (self-employment income for service-related payments)',
      'Are always tax-exempt to the partner',
      'Reduce the partner\'s capital account without any deduction',
    ],
    correctAnswer: 1,
    explanation: 'IRC §707(c) Guaranteed Payments: Definition: payments to a partner for services or use of capital, determined without regard to the income of the partnership. Examples: fixed salary to a managing partner, interest payment on partner\'s capital contribution (fixed rate regardless of profits). Tax treatment — Partnership: (1) deductible in computing partnership ordinary income (similar to salary expense), (2) reported on Form 1065, Schedule K, Line 4, (3) reported to the partner on Schedule K-1, Box 4. Tax treatment — Partner: (1) ordinary income whether or not the partnership has profits, (2) subject to self-employment tax if for services (not for use of capital), (3) included in the partner\'s income for the tax year in which the partnership year ends (§706(a)), (4) NOT subject to income tax withholding (no W-2). Effect on basis: guaranteed payments increase the partner\'s distributive share of income (increasing basis) and are then a draw against income (reducing basis) — net effect on basis depends on total income vs. guaranteed payment. Distinction from §707(a): §707(a) treats the partner as not acting as a partner (e.g., services for a fixed fee); §707(c) treats the payment as a guaranteed minimum.',
    reference: 'IRC §707(c)',
  },
  {
    id: 'tcp-d9-013',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Estimated Tax Payments',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A C corporation must make estimated tax payments if its expected tax liability for the year is:',
    options: [
      '$1,000 or more',
      '$500 or more — quarterly payments are due on the 15th day of the 4th, 6th, 9th, and 12th months of the corporation\'s tax year',
      '$10,000 or more',
      '$100,000 or more',
    ],
    correctAnswer: 1,
    explanation: 'IRC §6655 Corporate Estimated Tax: Required when: expected tax liability is $500 or more for the year. Due dates (calendar-year corporation): April 15, June 15, September 15, December 15 (the 15th day of the 4th, 6th, 9th, and 12th months). Each installment: generally 25% of required annual payment. Safe harbors to avoid penalty: (1) 100% of prior year\'s tax liability (annualized), OR (2) current year\'s tax liability based on annualized income. Large corporations ($1 million+ taxable income in any of the 3 preceding years): can use prior year safe harbor only for the first installment; remaining installments must be based on current-year annualized income. Penalty: underpayment penalty calculated separately for each installment period using the federal short-term rate plus 3 percentage points. No penalty for: tax liability less than $500, new corporations in their first year (no prior year). Payment method: must use EFTPS for deposits of $2,500 or more per quarter.',
    reference: 'IRC §6655',
  },
  {
    id: 'tcp-d9-014',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Partner\'s Basis Computation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A partner\'s outside basis in a partnership interest is increased by all of the following EXCEPT:',
    options: [
      'The partner\'s distributive share of partnership taxable income',
      'Distributions of cash from the partnership to the partner',
      'The partner\'s distributive share of tax-exempt income',
      'Additional capital contributions',
    ],
    correctAnswer: 1,
    explanation: 'IRC §705 Partner\'s Outside Basis: Increases to basis: (1) additional capital contributions (cash at face value, property at adjusted basis), (2) partner\'s distributive share of partnership taxable income (ordinary income, capital gains, §1231 gains), (3) partner\'s distributive share of tax-exempt income (e.g., municipal bond interest), (4) increase in partner\'s share of partnership liabilities (§752 — treated as deemed cash contribution). Decreases to basis: (1) distributions of cash (reduce basis dollar-for-dollar, gain recognized if cash exceeds basis), (2) distributions of property (reduce basis by the partnership\'s adjusted basis in the property), (3) partner\'s distributive share of partnership losses and deductions, (4) partner\'s distributive share of nondeductible, noncapitalized expenditures (e.g., penalties, 50% of meals), (5) decrease in partner\'s share of partnership liabilities (§752 — treated as deemed cash distribution). Ordering: basis increases are applied before decreases. Basis cannot go below zero — losses in excess of basis are suspended under §704(d) and carried forward indefinitely.',
    reference: 'IRC §705; §752',
  },
  {
    id: 'tcp-d9-015',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Shareholder Basis Ordering',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An S corporation shareholder\'s stock basis is adjusted annually in which order?',
    options: [
      'Losses first, then income',
      'Increased for: (1) income items (separately and non-separately stated), (2) excess depletion deduction; then decreased for: (3) non-dividend distributions, (4) non-deductible non-capital expenses, (5) deductible losses and deductions; basis cannot go below zero',
      'No adjustments are ever needed',
      'Distributions first, then income and losses',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1367 S Corporation Shareholder Basis — Annual ordering rules: Step 1 — INCREASES: (a) separately stated income items (capital gains, §1231 gains, tax-exempt income, etc.), (b) non-separately stated income (ordinary business income), (c) excess depletion deduction over basis in the property. Step 2 — DECREASES (after increases): (a) non-dividend distributions (§1368) — reduce basis but not below zero; excess distribution is capital gain, (b) non-deductible, non-capital expenses (e.g., 50% meals disallowance, penalties, expenses related to tax-exempt income), (c) deductible losses and deductions (separately and non-separately stated). Why ordering matters: income items increase basis BEFORE distributions reduce it — this allows more distributions to be received tax-free (return of basis) and provides more basis for deducting losses. Key differences from partnerships: S corp basis is NOT increased by entity-level debt (only shareholder loans to the corporation increase debt basis under §1366(d)(1)(B)). Excess losses: suspended and carried forward indefinitely.',
    reference: 'IRC §1367; §1366(d)',
  },
  {
    id: 'tcp-d9-016',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Grantor Trust Rules',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the grantor trust rules (IRC §§671-679), a trust is treated as a grantor trust (with trust income taxed to the grantor) when:',
    options: [
      'The trust has a corporate trustee',
      'The grantor retains certain powers or interests, including: the power to revoke the trust, the power to control beneficial enjoyment, certain reversionary interests exceeding 5% of the trust value, the power to borrow from the trust without adequate security, or certain administrative powers that benefit the grantor',
      'The trust earns only capital gains',
      'The beneficiaries are all adults',
    ],
    correctAnswer: 1,
    explanation: 'IRC §§671-679 Grantor Trust Rules — a trust is a grantor trust (all or part of trust income taxed to the grantor) when: §673 — Reversionary interests: the grantor retains a reversionary interest whose value exceeds 5% of the value of the trust (or the trust portion). §674 — Power to control beneficial enjoyment: grantor or nonadverse party retains the power to dispose of trust income or corpus without the consent of an adverse party (with exceptions for independent trustees). §675 — Administrative powers: grantor retains: power to deal with trust for less than adequate consideration, power to borrow without adequate security, power to vote stock of closely-held corporation, power to substitute trust property. §676 — Power to revoke: grantor retains the power to revoke the trust and regain the trust corpus. §677 — Income for benefit of grantor: trust income may be distributed to the grantor or grantor\'s spouse, or used to pay premiums on insurance on the grantor\'s life. §679 — Foreign trusts: a U.S. person who transfers property to a foreign trust with a U.S. beneficiary is treated as the grantor. Effect: grantor reports all trust income/deductions on their individual return; trust is a disregarded entity for income tax purposes.',
    reference: 'IRC §§671-679',
  },
  {
    id: 'tcp-d9-017',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Dividends Received Deduction',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The dividends received deduction (DRD) under IRC §243 allows a C corporation to deduct what percentage of dividends received from another domestic corporation in which it owns 20% to less than 80% of the stock?',
    options: [
      '50%',
      '65%',
      '80%',
      '100%',
    ],
    correctAnswer: 1,
    explanation: 'IRC §243 Dividends Received Deduction (DRD): Deduction percentage based on ownership: (1) Less than 20% ownership of the paying corporation: 50% DRD, (2) 20% to less than 80% ownership: 65% DRD, (3) 80% or more ownership (affiliated group member): 100% DRD (§243(a)(3)). Taxable income limitation: the DRD cannot exceed the specified percentage of taxable income (computed without additional NOL deduction, DRD, and other adjustments). Exception to taxable income limitation: if claiming the full DRD would create or increase an NOL, the taxable income limitation does not apply (i.e., full DRD is allowed). Purpose: reduce triple taxation — the paying corporation already paid tax on the income, and the receiving corporation\'s dividend income should not be fully taxed again before flowing to individual shareholders. Qualified dividends from foreign corporations and certain debt-financed portfolio stock have different rules.',
    reference: 'IRC §243; §246',
  },
  {
    id: 'tcp-d9-018',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Substantial Economic Effect — §704(b)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'For a partnership\'s allocation of income, gain, loss, or deduction to be respected for tax purposes, the allocation must have "substantial economic effect" under IRC §704(b), which requires:',
    options: [
      'All partners to share equally',
      'The allocation must have economic effect (capital accounts must be properly maintained, liquidating distributions must be made in accordance with positive capital account balances, and partners with deficit capital accounts must restore them) AND the economic effect must be substantial (there must be a reasonable possibility the allocation will actually affect the dollar amounts received by the partners)',
      'Only that the partners agree in writing',
      'IRS pre-approval of the allocation',
    ],
    correctAnswer: 1,
    explanation: 'IRC §704(b) Substantial Economic Effect — Treasury Regulations §1.704-1(b): Two-part test: Part 1 — Economic Effect: the allocation must affect the actual economic positions of the partners (not just their tax consequences). Three requirements: (a) Capital accounts maintained in accordance with the regulations (contributions increase, distributions decrease, income/loss allocated properly), (b) Liquidating distributions made in accordance with positive capital account balances (partner with positive capital account receives that amount on liquidation), (c) Deficit restoration obligation — partners with negative capital accounts must restore the deficit (OR the alternative economic effect test: qualified income offset provision). Part 2 — Substantiality: the economic effect is substantial — there must be a reasonable possibility that the allocation will substantially affect the dollar amounts to be received by the partners, independent of tax consequences. NOT substantial if: (a) the allocation is a "shifting allocation" (offsetting allocations among partners in the same year), (b) "transitory allocation" (offsetting allocations in different years), if at the time allocation is made, there is strong likelihood of offset and net economic effect is de minimis. If §704(b) is not met: allocation is made in accordance with the partner\'s interest in the partnership (§704(b) default rule — PIP).',
    reference: 'IRC §704(b); Treas. Reg. §1.704-1(b)',
  },
  {
    id: 'tcp-d9-019',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'AAA Ordering',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The Accumulated Adjustments Account (AAA) of an S corporation represents:',
    options: [
      'The corporation\'s retained earnings for GAAP purposes',
      'The cumulative total of S corporation income items that have been taxed to shareholders but not yet distributed — distributions are first applied against AAA (tax-free return of previously taxed income) before being treated as dividends from accumulated E&P',
      'The total of all shareholder loans',
      'The corporation\'s depreciation reserve',
    ],
    correctAnswer: 1,
    explanation: 'Accumulated Adjustments Account (AAA) — IRC §1368(e): Purpose: tracks the cumulative undistributed net income of an S corporation that has already been taxed at the shareholder level. Only relevant for S corporations with accumulated E&P from prior C corporation years. AAA adjustments: Increased by: separately stated income items, non-separately stated income. Decreased by: separately stated loss/deduction items, non-separately stated loss, non-deductible expenses (not related to tax-exempt income), distributions. AAA can go negative (unlike stock basis). Distribution ordering for S corps with accumulated E&P (§1368(c)): (1) From AAA — tax-free return of previously taxed income (reduces AAA), (2) From accumulated E&P — taxable as dividend (reduces E&P), (3) From remaining AAA (if negative AAA was created by losses and then S corp later has income) — tax-free, (4) Additional paid-in capital / return of basis. S corporations with NO accumulated E&P: distributions are return of basis first (reduce stock basis), then capital gain if distributions exceed basis. AAA bypass election: S corporation may elect to distribute accumulated E&P first (§1368(e)(3)).',
    reference: 'IRC §1368',
  },
  {
    id: 'tcp-d9-020',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Income in Respect of a Decedent (IRD)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Income in Respect of a Decedent (IRD) under IRC §691 differs from other inherited property because:',
    options: [
      'It receives a stepped-up basis at death',
      'IRD does NOT receive a stepped-up basis — it retains the same tax character it would have had to the decedent, and must be included in income by whoever receives it (estate or beneficiary), though a deduction may be available for federal estate taxes paid on the IRD amount',
      'It is always tax-exempt',
      'It is only taxable if the estate is probated',
    ],
    correctAnswer: 1,
    explanation: 'IRC §691 Income in Respect of a Decedent (IRD): Definition: income earned by the decedent before death but not properly includible in the decedent\'s final return (cash-basis items not yet received, accrual-basis items earned but not reported). Examples: unpaid salary/wages, accounts receivable of a cash-basis professional, distributions from traditional IRAs and qualified retirement plans (potentially the largest IRD item), deferred compensation, accrued interest and dividends, installment sale payments, partnership income for the period before death. Key rule: NO stepped-up basis (§1014(c) exception) — IRD items retain their character (ordinary income remains ordinary, capital gain remains capital gain). IRD is taxable to the recipient: estate (if received by estate) or beneficiary (if distributed or transferred). IRC §691(c) deduction: the recipient of IRD may deduct the federal estate tax attributable to the net IRD included in the decedent\'s gross estate. This prevents double taxation (estate tax + income tax on the same income). The deduction is a miscellaneous itemized deduction NOT subject to the 2% AGI floor (survives TCJA suspension). Calculation: determine the incremental estate tax attributable to including IRD in the gross estate.',
    reference: 'IRC §691; §1014(c)',
  },
  {
    id: 'tcp-d9-021',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Corporate Formation — §351',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §351, no gain or loss is recognized when property is transferred to a corporation in exchange for stock if:',
    options: [
      'Any shareholder transfers property for stock',
      'The transferor(s), immediately after the exchange, control the corporation — "control" means ownership of at least 80% of the total combined voting power of all voting stock AND at least 80% of the total number of shares of all other classes of stock',
      'The corporation is publicly traded',
      'Only cash is transferred',
    ],
    correctAnswer: 1,
    explanation: 'IRC §351 Tax-Free Formation: Requirements: (1) Transfer of "property" — includes cash, tangible property, intangibles, accounts receivable; services are NOT property (stock received for services is taxable compensation), (2) Solely in exchange for stock — preferred or common (voting or nonvoting), (3) Control immediately after the exchange — transferor(s) must own at least 80% of voting power AND 80% of all other classes of stock (§368(c) control). Multiple transferors can satisfy the 80% test jointly if they are part of the same "exchange" (integrated transaction). Boot: if the transferor receives non-stock consideration ("boot" — cash, debt relief, other property in addition to stock), gain is recognized to the extent of boot received (but loss is never recognized). Basis: Transferor\'s stock basis = adjusted basis of property transferred + gain recognized − boot received. Corporation\'s basis in property = transferor\'s adjusted basis + gain recognized by transferor. Holding period: the corporation tacks the transferor\'s holding period; the transferor tacks the holding period for stock received.',
    reference: 'IRC §351; §358; §362',
  },
  {
    id: 'tcp-d9-022',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Partnership Formation — §721',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §721, the formation of a partnership generally results in:',
    options: [
      'Gain recognition on all property transferred',
      'No gain or loss recognition by either the partner or the partnership when property is contributed in exchange for a partnership interest — with no control requirement (unlike §351 for corporations)',
      'Loss recognition on depreciated property',
      'Gain recognition only for cash contributions',
    ],
    correctAnswer: 1,
    explanation: 'IRC §721 Partnership Formation: General rule: NO gain or loss is recognized by either the partner or the partnership when property is contributed to the partnership in exchange for a partnership interest. Key advantage over §351: no control requirement — even a single person contributing property to an existing 100-partner partnership qualifies (§351 requires 80% control by the transferor group). Partner\'s outside basis (§722): equals the adjusted basis of the property contributed plus cash contributed (substituted basis). Partnership\'s inside basis (§723): equals the contributing partner\'s adjusted basis in the property (carryover basis). Holding period (§1223): the partnership tacks the partner\'s holding period for the contributed property. Exceptions to nonrecognition: (1) contribution of services for a partnership interest (§721(b) exception — the capital interest received is taxable as compensation), (2) investment company exception (§721(b) — diversification of appreciated assets), (3) disguised sale rules (§707(a)(2)(B) — contribution followed by related distribution treated as sale). §704(c): built-in gain/loss at contribution must be allocated to the contributing partner (prevents shifting of pre-contribution gain/loss to other partners).',
    reference: 'IRC §721; §722; §723; §704(c)',
  },
  {
    id: 'tcp-d9-023',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Estate Income Tax — §641',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An estate or trust is required to file Form 1041 when:',
    options: [
      'The estate has any assets',
      'The estate has gross income of $600 or more, OR the trust has any taxable income, OR the trust has gross income of $600 or more regardless of taxable income',
      'Only after the estate is closed',
      'Only if the estate has an executor',
    ],
    correctAnswer: 1,
    explanation: 'IRC §6012(a)(3)-(4) Filing requirements for estates and trusts: Estates: must file Form 1041 if gross income is $600 or more, OR if any beneficiary is a nonresident alien. Trusts: must file if the trust has any taxable income for the year, OR if the trust has gross income of $600 or more (regardless of taxable income). Grantor trusts: if the trust is fully a grantor trust, the grantor reports all income on their individual return; however, the trust may still need to file Form 1041 as an information return (reporting the trust\'s income and identifying the grantor). Estate tax year: an estate may choose a fiscal year ending in any month within the first 12 months after the decedent\'s death. Trusts must generally use a calendar year (§644). Estimated tax payments: estates are exempt from estimated tax requirements for the first 2 tax years. Trusts must make quarterly estimated payments. Form 1041 due date: 15th day of the 4th month after the close of the tax year (April 15 for calendar year), with automatic 5.5-month extension to September 30.',
    reference: 'IRC §6012(a)(3)-(4); §641-§692',
  },
  {
    id: 'tcp-d9-024',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Corporate Charitable Deduction',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A C corporation\'s charitable contribution deduction is limited to:',
    options: [
      '60% of adjusted gross income',
      '10% of taxable income computed before the charitable deduction, DRD, NOL carryback, and capital loss carryback — excess contributions can be carried forward for 5 years',
      '25% of taxable income',
      '50% of gross receipts',
    ],
    correctAnswer: 1,
    explanation: 'IRC §170(b)(2) Corporate Charitable Deduction: Limit: 10% of taxable income computed without regard to: the charitable contribution deduction itself, the dividends received deduction (DRD), any NOL carryback, any capital loss carryback. Carryforward: excess charitable contributions can be carried forward for 5 years (FIFO — oldest excess used first). Special rules for property contributions: appreciated capital gain property: deduct FMV (no reduction for built-in gain) — but 10% limit still applies; ordinary income property: deduct the lesser of FMV or adjusted basis (FMV reduced by ordinary income that would have been recognized); inventory contributions for care of the ill, needy, or infants: enhanced deduction = adjusted basis + 50% of unrealized appreciation (limited to 2× adjusted basis). Accrual method: a C corporation may elect to deduct contributions authorized by the board of directors before year-end if paid within 2.5 months after year-end (§170(a)(2)). Note: these rules differ significantly from individual charitable deduction rules (60%/30%/20% AGI limits, different carryforward period).',
    reference: 'IRC §170(b)(2)',
  },
  {
    id: 'tcp-d9-025',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Reasonable Compensation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The IRS scrutinizes S corporation officer-shareholders who pay themselves no salary or an unreasonably low salary because:',
    options: [
      'Their pay has no tax consequence',
      'Salary is subject to FICA taxes (Social Security and Medicare), while S corporation distributions are not subject to self-employment tax — officer-shareholders who perform services must receive reasonable compensation before taking distributions to avoid underpayment of employment taxes',
      'S corporation distributions are always tax-exempt',
      'The IRS prefers higher salaries for all employees',
    ],
    correctAnswer: 1,
    explanation: 'S Corporation Reasonable Compensation: Employment tax arbitrage: S corporation officer-shareholders performing services may be tempted to minimize salary (subject to 15.3% FICA: 12.4% Social Security up to wage base + 2.9% Medicare) and maximize distributions (NOT subject to self-employment tax). IRS enforcement: officer-shareholders performing services must receive reasonable compensation BEFORE taking distributions. "Reasonable compensation" factors: (1) comparable pay for comparable positions in comparable industries, (2) training and experience, (3) duties and responsibilities, (4) time devoted to the business, (5) dividend history, (6) compensation paid to non-shareholder employees, (7) corporate volume and complexity. Consequences of unreasonable compensation: IRS can reclassify distributions as wages, assess unpaid FICA taxes, penalties, and interest on both the employee and employer share. Key case: David E. Watson, P.C. v. United States (2012) — IRS successfully reclassified distributions as wages. Note: unlike S corporations, partnerships/LLCs taxed as partnerships are subject to self-employment tax on guaranteed payments and distributive share of ordinary income, so this arbitrage opportunity is unique to S corporations.',
    reference: 'IRC §3121; Rev. Rul. 74-44; Watson v. United States',
  },
];
