// TCP - Tax Compliance and Planning Expanded Questions
// 2026 CPA Exam Blueprint Compliant
// World-Class expansion - Second batch

import { Question } from '../../../types';

export const TCP_QUESTIONS_EXPANDED: Question[] = [
  // ==========================================
  // AREA I: Individual Taxation
  // ==========================================
  {
    id: 'tcp-exp-001',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-I',
    topic: 'Individual Taxation',
    subtopic: 'Filing Status',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A taxpayer has the following capital transactions: $25,000 short-term capital gain, $10,000 short-term capital loss, $40,000 long-term capital gain, and $20,000 long-term capital loss. What is the net capital gain or loss and its character?',
    options: [
      '$35,000 net capital gain — $15,000 STCG and $20,000 LTCG',
      '$35,000 net capital gain, all long-term',
      '$55,000 net capital gain',
      '$35,000 net capital gain, all short-term',
    ],
    correctAnswer: 0,
    explanation: 'Capital gains and losses are first netted within each category. Short-term: $25,000 gain − $10,000 loss = $15,000 net STCG. Long-term: $40,000 gain − $20,000 loss = $20,000 net LTCG. Total net capital gain = $15,000 + $20,000 = $35,000. The character distinction matters: STCG is taxed at ordinary income rates, while LTCG receives preferential rates (0%, 15%, or 20% depending on taxable income). If one category had a net loss, it would offset the other.',
    reference: 'IRC §2(b)',
  },
  {
    id: 'tcp-exp-002',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'AMT',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'Common individual alternative minimum tax (AMT) preference items include:',
    options: [
      'Standard deduction',
      'State and local tax deduction, private activity bond interest, and ISO exercise bargain element',
      'Charitable contributions',
      'Medical expenses above floor',
    ],
    correctAnswer: 1,
    explanation: 'AMT preferences/adjustments: SALT deduction disallowed, private activity municipal bond interest added, ISO bargain element at exercise, miscellaneous itemized (pre-TCJA). Exemption phases out at high income.',
    reference: 'IRC §55-59',
  },
  {
    id: 'tcp-exp-003',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-I',
    topic: 'Individual Taxation',
    subtopic: 'Net Investment Income Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A married couple filing jointly had the following: wages of $280,000, qualified business income (QBI) from a sole proprietorship of $60,000, and no specified service trade or business. Their taxable income before the QBI deduction is $300,000. What is their QBI deduction under IRC §199A?',
    options: [
      '$12,000 — 20% of qualified business income',
      '$60,000 — the full QBI amount',
      '$56,000 — 20% of taxable income',
      '$0 — the income exceeds the threshold',
    ],
    correctAnswer: 0,
    explanation: 'The IRC §199A QBI deduction allows eligible taxpayers to deduct up to 20% of qualified business income from pass-through entities and sole proprietorships. For MFJ filers with taxable income below $364,200 (2024), the full 20% deduction applies without W-2 wage or property limitations. QBI deduction = 20% × $60,000 = $12,000. The deduction is the lesser of (1) 20% of QBI or (2) 20% of taxable income (after other deductions). Since it\'s not an SSTB, the phase-out doesn\'t apply.',
    reference: 'IRC §1411',
  },
  {
    id: 'tcp-exp-004',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Estimated Taxes',
    difficulty: 'medium',
    blueprintArea: 'TCP-I',
    skillLevel: 'Application',
    question: 'To avoid the underpayment penalty, an individual generally must pay:',
    options: [
      '80% of current year tax',
      '90% of current year tax or 100% (110% if high income) of prior year tax',
      '50% of current year tax',
      '100% of current year tax only',
    ],
    correctAnswer: 1,
    explanation: 'Safe harbor: pay at least 90% of current year tax OR 100% (110% if prior AGI >$150K) of prior year tax through withholding and estimates. Quarterly estimates: 4/15, 6/15, 9/15, 1/15.',
    reference: 'IRC §6654',
  },

  // ==========================================
  // AREA II: Entity Taxation - C Corps
  // ==========================================
  {
    id: 'tcp-exp-005',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-II',
    topic: 'C Corporation Taxation',
    subtopic: 'Accumulated Earnings Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A C corporation has current-year earnings and profits (E&P) of $60,000 and accumulated E&P of ($20,000) — a deficit. The corporation distributes $100,000 to its sole shareholder, who has a stock basis of $50,000. How is the distribution taxed?',
    options: [
      '$60,000 dividend (from current E&P), $0 from accumulated E&P (deficit), $40,000 return of basis reducing it to $10,000',
      '$100,000 dividend',
      '$80,000 dividend and $20,000 return of basis',
      '$50,000 dividend and $50,000 capital gain',
    ],
    correctAnswer: 0,
    explanation: 'Distribution taxation follows E&P ordering rules. Current E&P ($60,000) is allocated first — $60,000 is taxed as a dividend. Accumulated E&P is a ($20,000) deficit, so no additional dividend treatment. Remaining $40,000 ($100,000 − $60,000) is return of basis: $50,000 basis − $40,000 = $10,000 remaining basis. No capital gain because the return of basis ($40,000) doesn\'t exceed stock basis ($50,000). If total distributions had exceeded both E&P and basis, the excess would be capital gain.',
    reference: 'IRC §531-537',
  },
  {
    id: 'tcp-exp-006',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'C Corporation Taxation',
    subtopic: 'DRD',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'The dividends received deduction (DRD) percentage depends on:',
    options: [
      'Amount of dividend',
      'Type of stock',
      'Date of receipt',
      'Ownership percentage in the distributing corporation (50%, 65%, or 100%)',
    ],
    correctAnswer: 3,
    explanation: 'DRD: <20% ownership = 50%, 20-80% = 65%, ≥80% (affiliated) = 100%. Limited to taxable income (exception if creates/increases NOL). Only dividends from domestic corporations. Reduces effective tax on intercorporate dividends.',
    reference: 'IRC §243',
  },
  {
    id: 'tcp-exp-007',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'C Corporation Taxation',
    subtopic: 'Capital Losses',
    difficulty: 'medium',
    blueprintArea: 'TCP-II',
    skillLevel: 'Application',
    question: 'Corporate capital losses:',
    options: [
      'Can only offset capital gains, with carryback 3 years and forward 5 years',
      'Are fully deductible',
      'Offset ordinary income up to $3,000',
      'Are never deductible',
    ],
    correctAnswer: 0,
    explanation: 'Corporate capital losses: offset only capital gains (not ordinary income like individuals). Carryback 3 years, carryforward 5 years (as short-term capital loss). Different from individual $3,000 deduction against ordinary income.',
    reference: 'IRC §1211(a), §1212(a)',
  },
  {
    id: 'tcp-exp-008',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'C Corporation Taxation',
    subtopic: 'Charitable Contributions',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'The corporate charitable contribution deduction is limited to:',
    options: [
      'No limit',
      '30% of taxable income',
      '50% of taxable income',
      '10% of taxable income (before DRD, charitable deduction, and NOL carryback)',
    ],
    correctAnswer: 3,
    explanation: 'Corporate charitable limit: 10% of taxable income (before DRD, charitable, NOL/capital loss carrybacks). Excess carries forward 5 years. Inventory donations may get enhanced deduction (cost + ½ unrealized appreciation).',
    reference: 'IRC §170(b)(2)',
  },

  // ==========================================
  // AREA II: Entity Taxation - S Corps
  // ==========================================
  {
    id: 'tcp-exp-009',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-scorp',
    topic: 'S Corporation Taxation',
    subtopic: 'Election Requirements',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'To qualify for S corporation status, the corporation must have:',
    options: [
      'At least 5 shareholders',
      'No more than 100 shareholders, one class of stock, and only eligible shareholders',
      'Any number of shareholders',
      'Foreign shareholders allowed',
    ],
    correctAnswer: 1,
    explanation: 'S corp requirements: ≤100 shareholders (family members count as one), domestic corporation, eligible shareholders (individuals, estates, certain trusts - no partnerships, corps, nonresident aliens), one class of stock.',
    reference: 'IRC §1361',
  },
  {
    id: 'tcp-exp-010',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-scorp',
    topic: 'S Corporation Taxation',
    subtopic: 'Distribution Ordering',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'Distributions from an S corp with no E&P are taxed in the following order:',
    options: [
      'Capital gain only',
      'Tax-free return of basis, then capital gain when basis is zero',
      'All taxable as dividends',
      'Ordinary income',
    ],
    correctAnswer: 1,
    explanation: 'No E&P distributions: (1) reduce stock basis (tax-free), (2) excess = capital gain. With E&P: AAA first (tax-free to basis), then E&P (dividend), then remaining stock basis, then capital gain.',
    reference: 'IRC §1368',
  },
  {
    id: 'tcp-exp-011',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-II',
    topic: 'S Corporation Taxation',
    subtopic: 'Built-In Gains Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An S corporation shareholder receives a $50,000 distribution. The shareholder\'s stock basis before the distribution is $35,000, and the S corporation has no accumulated E&P. How is the distribution taxed?',
    options: [
      '$35,000 is a nontaxable return of basis; $15,000 is capital gain',
      'The entire $50,000 is a taxable dividend',
      '$50,000 is nontaxable because there is no E&P',
      '$35,000 is capital gain; $15,000 is ordinary income',
    ],
    correctAnswer: 0,
    explanation: 'For an S corporation with no accumulated E&P, distributions are tax-free to the extent of the shareholder\'s stock basis under IRC §1368(b). The first $35,000 reduces stock basis to zero (nontaxable). The excess $15,000, after basis is exhausted, is treated as gain from the sale of stock — typically long-term capital gain if the stock has been held for more than one year. No portion is treated as a dividend because there is no E&P.',
    reference: 'IRC §1374',
  },

  // ==========================================
  // AREA II: Entity Taxation - Partnerships
  // ==========================================
  {
    id: 'tcp-exp-012',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Formation',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'A partner recognizes gain on contribution of property to a partnership when:',
    options: [
      'Always',
      'Never, unless receiving property or excess liabilities, or contributing to an investment company',
      'Only if FMV exceeds basis',
      'Only for real property',
    ],
    correctAnswer: 1,
    explanation: 'Generally tax-free (§721) even with boot (unlike corporate formation). Gain recognized if: (1) receiving property (disguised sale), (2) debt relief > basis, (3) contribution to investment company (diversification).',
    reference: 'IRC §721',
  },
  {
    id: 'tcp-exp-013',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Basis Adjustments',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'A partner\'s outside basis increases by:',
    options: [
      'Distributions received',
      'Losses allocated',
      'Income allocated, additional contributions, and share of partnership liabilities',
      'Partner salaries',
    ],
    correctAnswer: 2,
    explanation: 'Outside basis increases: capital contributions, share of income (including tax-exempt), share of liabilities. Decreases: distributions, share of losses/deductions, share of nondeductible expenses, liability reductions.',
    reference: 'IRC §705',
  },
  {
    id: 'tcp-exp-014',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Special Allocations',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Evaluation',
    question: 'Partnership special allocations must have:',
    options: [
      'No restrictions',
      'Substantial economic effect to be respected for tax purposes',
      'Equal allocation only',
      'IRS approval',
    ],
    correctAnswer: 1,
    explanation: 'Special allocations respected if substantial economic effect: (1) economic effect (capital account maintenance, liquidation by capital accounts, deficit restoration), (2) substantial (reasonable possibility affects dollar amounts received).',
    reference: 'IRC §704(b)',
  },
  {
    id: 'tcp-exp-015',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Recourse vs Nonrecourse',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'Recourse liabilities are allocated to partners based on:',
    options: [
      'Profit sharing ratios',
      'Capital account balances',
      'Equal shares',
      'Who bears the economic risk of loss',
    ],
    correctAnswer: 3,
    explanation: 'Recourse: allocated to partner(s) bearing economic risk of loss (who must pay if partnership can\'t). Nonrecourse: allocated by profit ratios (generally) plus minimum gain. Affects partner basis and loss deductibility.',
    reference: 'Treas. Reg. §1.752-2, -3',
  },

  // ==========================================
  // AREA III: Property Transactions
  // ==========================================
  {
    id: 'tcp-exp-016',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Like-Kind Exchange',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'Under §1031, boot received in a like-kind exchange is taxed:',
    options: [
      'As ordinary income',
      'Not taxed',
      'As gain to the extent of lesser of boot received or realized gain',
      'At capital gains rates on entire gain',
    ],
    correctAnswer: 2,
    explanation: 'Boot (non-like-kind property/cash) triggers gain recognition = lesser of boot received or realized gain. Loss is NOT recognized in §1031. Character depends on property (usually §1231). Basis = FMV - deferred gain.',
    reference: 'IRC §1031',
  },
  {
    id: 'tcp-exp-017',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Installment Sales',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'The installment method reports gain as:',
    options: [
      'Gross profit percentage times each payment received',
      'Interest income only',
      'All gain in year of sale',
      'Principal payments only',
    ],
    correctAnswer: 0,
    explanation: 'Installment gain: Gross profit % × payment received. GP% = Gross profit / Contract price. Contract price = selling price - assumed liabilities (to extent of basis). Interest taxed separately. Not for inventory, dealer property.',
    reference: 'IRC §453',
  },
  {
    id: 'tcp-exp-018',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Section 1245 Recapture',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'Section 1245 recapture converts gain to ordinary income to the extent of:',
    options: [
      'Lesser of depreciation taken or gain realized',
      'Only accelerated depreciation',
      'All gain',
      'Only straight-line depreciation',
    ],
    correctAnswer: 0,
    explanation: '§1245: recaptures ALL depreciation as ordinary income (lesser of gain or depreciation). Applies to personal property, certain real property (pre-1987), amortizable §197 intangibles. §1250 applies to real property (unrecaptured §1250).',
    reference: 'IRC §1245',
  },
  {
    id: 'tcp-exp-019',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-III',
    topic: 'Property Transactions',
    subtopic: 'Section 1231',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A taxpayer purchased a primary residence in 2018 for $400,000, lived in it for 6 years, and sold it in 2024 for $700,000. The taxpayer is married filing jointly. What are the tax consequences?',
    options: [
      '$0 taxable gain — the $300,000 gain is fully excluded under the $500,000 MFJ exclusion',
      '$50,000 taxable gain',
      '$300,000 taxable gain — no exclusion applies to primary residences',
      '$200,000 taxable gain',
    ],
    correctAnswer: 0,
    explanation: 'Under IRC §121, married taxpayers filing jointly may exclude up to $500,000 of gain on the sale of a principal residence. Both spouses must meet the use test (2 of the prior 5 years), and at least one must meet the ownership test. Gain = $700,000 − $400,000 = $300,000. Since $300,000 < $500,000 exclusion, the entire gain is excluded. The exclusion can be used once every 2 years. No capital improvements or selling expenses are needed to eliminate the gain here.',
    reference: 'IRC §1231',
  },

  // ==========================================
  // AREA IV-V: Tax Planning and Advanced Topics
  // ==========================================
  {
    id: 'tcp-exp-020',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-planning',
    topic: 'Tax Planning',
    subtopic: 'Timing Strategies',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Evaluation',
    question: 'Deferring income recognition is beneficial when:',
    options: [
      'Always beneficial',
      'Tax rates are expected to decrease or taxpayer will be in lower bracket',
      'Tax rates are increasing',
      'Never beneficial',
    ],
    correctAnswer: 1,
    explanation: 'Deferral benefits: time value of money, lower future rates, lower future income. Acceleration better if rates increasing or current low income. Consider: AMT, phase-outs, legislative changes, cash needs.',
    reference: 'Tax Planning Principles',
  },
  {
    id: 'tcp-exp-021',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-planning',
    topic: 'Tax Planning',
    subtopic: 'Entity Selection',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Evaluation',
    question: 'Factors favoring S corporation over partnership include:',
    options: [
      'More allocation flexibility',
      'Inclusion of debt in basis',
      'Self-employment tax savings on distributions and ability to split income between salary and distributions',
      'More than 100 owners'
    ],
    correctAnswer: 2,
    explanation: 'S corp advantages: SE tax applies only to reasonable salary (not distributions), creditor protection. Partnership advantages: flexible allocations, debt increases basis, no shareholder restrictions, no second class of stock issues.',
    reference: 'Entity Selection',
  },
  {
    id: 'tcp-exp-022',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-qbi',
    topic: 'Qualified Business Income',
    subtopic: 'QBI Deduction',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'The §199A QBI deduction is limited by:',
    options: [
      'W-2 wages and qualified property limitations above certain income thresholds',
      'Only taxable income',
      'No limitations',
      'Only for manufacturing'
    ],
    correctAnswer: 0,
    explanation: '§199A: 20% of QBI, limited above threshold to greater of: (1) 50% of W-2 wages, (2) 25% of W-2 wages + 2.5% of unadjusted basis of qualified property. SSTBs phase out at high income. Overall limit: 20% of taxable income minus net capital gain.',
    reference: 'IRC §199A',
  },
  {
    id: 'tcp-exp-023',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-qbi',
    topic: 'Qualified Business Income',
    subtopic: 'SSTB',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'Specified Service Trades or Businesses (SSTBs) include:',
    options: [
      'Real estate',
      'Health, law, accounting, consulting, athletics, financial services, and businesses relying on reputation of owners',
      'Manufacturing',
      'Construction',
    ],
    correctAnswer: 1,
    explanation: 'SSTBs: health, law, accounting, actuarial, performing arts, consulting, athletics, financial services, brokerage, principal asset is reputation/skill. Engineering and architecture excluded. SSTB owners lose §199A deduction above income thresholds.',
    reference: 'IRC §199A(d)(2)',
  },
  {
    id: 'tcp-exp-024',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'GILTI',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'Global Intangible Low-Taxed Income (GILTI) requires U.S. shareholders to:',
    options: [
      'Only report dividends',
      'Ignore foreign income',
      'Include currently their share of CFC income exceeding 10% return on tangible assets',
      'Pay no U.S. tax on foreign income',
    ],
    correctAnswer: 2,
    explanation: 'GILTI: current inclusion of CFC "tested income" minus 10% deemed return on qualified tangible assets (QBAI). 50% deduction for corporations (effective 10.5% rate). Foreign tax credit available. Anti-deferral regime.',
    reference: 'IRC §951A',
  },
  {
    id: 'tcp-exp-025',
    courseId: 'cpa',
    section: 'TCP',
    blueprintArea: 'TCP-IV',
    topic: 'International Taxation',
    subtopic: 'Foreign Tax Credit',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A U.S. corporation owns 100% of a controlled foreign corporation (CFC). The CFC has $500,000 of Subpart F income and $200,000 of tested income under GILTI. What amounts must the U.S. corporation include in its current-year income?',
    options: [
      'Both the $500,000 Subpart F income and the $200,000 GILTI tested income are included in current-year income',
      'Only $500,000 Subpart F income; GILTI does not apply to corporate shareholders',
      'Only $200,000 GILTI; Subpart F was repealed by the TCJA',
      '$700,000 total, but a 100% deduction eliminates the tax',
    ],
    correctAnswer: 0,
    explanation: 'U.S. shareholders of CFCs must include both Subpart F income (IRC §951) and GILTI (IRC §951A) in current-year income, regardless of whether the CFC distributes it. Subpart F captures defined categories of passive and mobile income. GILTI captures remaining active income exceeding a 10% return on tangible assets. Corporate shareholders may claim a 50% GILTI deduction (IRC §250) and foreign tax credits, but both amounts are included in gross income. Subpart F income is not offset by the QBAI deemed return.',
    reference: 'IRC §904',
  },

  // Additional comprehensive coverage
  {
    id: 'tcp-exp-026',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Social Security Benefits',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'Social Security benefits become taxable when:',
    options: [
      'Taxpayer is over 70',
      'Provisional income exceeds base amount ($25K single, $32K MFJ), up to 85% taxable',
      'Any benefits are received',
      'Benefits exceed $50,000',
    ],
    correctAnswer: 1,
    explanation: 'Provisional income = AGI + tax-exempt interest + ½ SS benefits. Inclusion: 0-50% if exceeds first threshold, up to 85% if exceeds second threshold ($34K single, $44K MFJ). Never more than 85% taxable.',
    reference: 'IRC §86',
  },
  {
    id: 'tcp-exp-027',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Passive Activity Rules',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'A taxpayer can deduct up to $25,000 of rental real estate losses if:',
    options: [
      'They are real estate professionals',
      'Losses exceed $25,000',
      'They own any rental property',
      'They actively participate and have MAGI below phase-out threshold',
    ],
    correctAnswer: 3,
    explanation: '$25K allowance: active participation (approve tenants, repairs), >10% ownership, MAGI <$100K (phases out $100K-$150K). Real estate professionals: >750 hours and material participation can treat as non-passive.',
    reference: 'IRC §469(i)',
  },
  {
    id: 'tcp-exp-028',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'C Corporation Taxation',
    subtopic: 'Organizational Costs',
    difficulty: 'medium',
    blueprintArea: 'TCP-II',
    skillLevel: 'Application',
    question: 'Organizational expenditures of a corporation:',
    options: [
      'Are never deductible',
      'May deduct up to $5,000 in first year, remainder amortized over 180 months',
      'Are fully deductible when paid',
      'Must be capitalized permanently',
    ],
    correctAnswer: 1,
    explanation: 'Org costs: deduct $5,000 first year (reduced by amounts over $50,000), amortize remainder over 180 months. Similar rule for start-up costs. Organizational costs: legal fees for organizing, state fees (not stock issuance).',
    reference: 'IRC §248',
  },
  {
    id: 'tcp-exp-029',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-corporate',
    topic: 'C Corporation Taxation',
    subtopic: 'Net Operating Losses',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'Post-2020 corporate NOLs:',
    options: [
      'Can offset 100% of taxable income',
      'Can be carried back 2 years',
      'Can offset only 80% of taxable income with indefinite carryforward',
      'Expire after 20 years'
    ],
    correctAnswer: 2,
    explanation: 'Post-2017 NOLs: no carryback (except farming), indefinite carryforward, 80% taxable income limitation. CARES Act allowed 5-year carryback for 2018-2020 NOLs. Pre-2018 NOLs: 2-year back, 20-year forward, no 80% limit.',
    reference: 'IRC §172',
  },
  {
    id: 'tcp-exp-030',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-scorp',
    topic: 'S Corporation Taxation',
    subtopic: 'Shareholder Basis Ordering',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Evaluation',
    question: 'An S corporation shareholder has stock basis of $80,000 and debt basis of $30,000. The corporation allocates $95,000 of ordinary income, $20,000 of tax-exempt interest, and $130,000 of ordinary losses. What is the shareholder\'s ending stock and debt basis?',
    options: [
      'Stock basis: $65,000; debt basis: $30,000',
      'Stock basis: $0; debt basis: $15,000',
      'Stock basis: $80,000; debt basis: $30,000',
      'Stock basis: $75,000; debt basis: $0'
    ],
    correctAnswer: 0,
    explanation: 'Basis adjustments follow the ordering rules of IRC §1367. Step 1: increase stock basis for income and tax-exempt income: $80,000 + $95,000 + $20,000 = $195,000. Step 2: decrease for losses: $195,000 − $130,000 = $65,000 (stock basis). Since losses don\'t exceed stock basis, debt basis is unaffected. Final: stock basis $65,000, debt basis $30,000.',
    reference: 'IRC §1367',
  },
  {
    id: 'tcp-exp-031',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Nonliquidating Distributions',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'In a nonliquidating partnership distribution, the partner recognizes gain only when:',
    options: [
      'FMV of property exceeds basis',
      'Any property is distributed',
      'Cash distributed exceeds the partner\'s outside basis',
      'Profit allocation is received',
    ],
    correctAnswer: 2,
    explanation: 'Nonliquidating distribution: gain only if cash > outside basis. No gain on property distributions (basis = lesser of inside basis or outside basis). Losses never recognized in nonliquidating distribution.',
    reference: 'IRC §731',
  },
  {
    id: 'tcp-exp-032',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Section 754 Election',
    difficulty: 'hard',
    blueprintArea: 'TCP-II',
    skillLevel: 'Analysis',
    question: 'A Section 754 election allows the partnership to:',
    options: [
      'Ignore partner allocations',
      'Avoid all taxation',
      'Adjust the basis of partnership assets upon transfer or distribution',
      'Convert to corporate status',
    ],
    correctAnswer: 2,
    explanation: '§754 election enables: §743(b) adjustment (basis step-up/down on transfer of partnership interest), §734(b) adjustment (distribution basis adjustments). Eliminates mismatch between inside and outside basis. Applies to all future transfers.',
    reference: 'IRC §754',
  },
  {
    id: 'tcp-exp-033',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Qualified Opportunity Zones',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'Investing capital gains in a Qualified Opportunity Fund provides:',
    options: [
      'Deferral of gain until 2026, reduction if held 5+ years, and exclusion of QOF appreciation if held 10+ years',
      'Tax credit',
      'Immediate deduction',
      'Ordinary loss treatment',
    ],
    correctAnswer: 0,
    explanation: 'QOZ benefits: (1) defer recognized gain until earlier of sale or 12/31/2026, (2) 10% basis step-up if held 5 years (expired), (3) exclude appreciation in QOF if held 10+ years. Must invest in QOF within 180 days.',
    reference: 'IRC §1400Z-2',
  },
  {
    id: 'tcp-exp-034',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'QSBS Exclusion',
    difficulty: 'hard',
    blueprintArea: 'TCP-III',
    skillLevel: 'Analysis',
    question: 'The Qualified Small Business Stock exclusion (§1202) allows:',
    options: [
      'No exclusion',
      'Ordinary income treatment',
      'Only 50% exclusion',
      'Exclusion of up to 100% of gain (for stock acquired after 2010) if held 5+ years',
    ],
    correctAnswer: 3,
    explanation: 'QSBS (§1202): exclude 50%/75%/100% of gain (by acquisition date) if: C corp, ≤$50M assets at issuance, active business (not SSTB), acquired at original issuance, held 5+ years. Exclusion up to greater of $10M or 10× basis.',
    reference: 'IRC §1202',
  },
  {
    id: 'tcp-exp-035',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-retirement',
    topic: 'Retirement Plans',
    subtopic: 'Required Minimum Distributions',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Analysis',
    question: 'Required minimum distributions from traditional IRAs must begin:',
    options: [
      'When employed',
      'At age 65',
      'At age 59½',
      'By April 1 following the year the owner reaches age 73 (SECURE 2.0)',
    ],
    correctAnswer: 3,
    explanation: 'RMD rules: begin by April 1 following year reaching age 73 (SECURE 2.0 increased from 72). Subsequent RMDs by 12/31. Penalty: 25% of required amount not taken (was 50%). Roth IRAs: no RMDs for original owner.',
    reference: 'IRC §401(a)(9)',
  },
  {
    id: 'tcp-exp-036',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-retirement',
    topic: 'Retirement Plans',
    subtopic: 'Roth Conversions',
    difficulty: 'hard',
    blueprintArea: 'TCP-I',
    skillLevel: 'Evaluation',
    question: 'Converting a traditional IRA to Roth IRA results in:',
    options: [
      'Current taxation on the converted amount but future qualified distributions are tax-free',
      'Capital gains treatment',
      'No tax consequences',
      'Penalty for early conversion',
    ],
    correctAnswer: 0,
    explanation: 'Roth conversion: taxable as ordinary income (no 10% penalty). Benefits: tax-free growth and distributions, no RMDs. Favorable when: expect higher future rates, long time horizon, can pay tax from outside funds.',
    reference: 'IRC §408A',
  },
  {
    id: 'tcp-exp-037',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-estate',
    topic: 'Gift and Estate Tax',
    subtopic: 'Annual Exclusion',
    difficulty: 'medium',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Application',
    question: 'The annual gift tax exclusion for 2024 is:',
    options: [
      '$25,000 total',
      '$15,000 per donee',
      '$18,000 per donee, unlimited donees',
      '$1 million lifetime',
    ],
    correctAnswer: 2,
    explanation: 'Annual exclusion: $18,000 (2024) per donee, unlimited donees. Present interest gifts only. Married couples can split gifts ($36,000). Educational/medical payments directly to institution are unlimited and additional.',
    reference: 'IRC §2503(b)',
  },
  {
    id: 'tcp-exp-038',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-estate',
    topic: 'Gift and Estate Tax',
    subtopic: 'Unified Credit',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'The unified gift and estate tax exemption for 2024 is approximately:',
    options: [
      '$1 million',
      '$13.61 million per person (scheduled to decrease to ~$7 million in 2026)',
      '$5 million',
      '$25 million',
    ],
    correctAnswer: 1,
    explanation: '2024 exemption: $13.61 million (inflation adjusted). Scheduled to revert to ~$7 million (inflation adjusted $5M) in 2026. Unused exemption portable to surviving spouse. Taxable gifts reduce available exemption.',
    reference: 'IRC §2010',
  },
  {
    id: 'tcp-exp-039',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'Foreign Tax Credit Limitation',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Analysis',
    question: 'A U.S. individual taxpayer paid $15,000 in foreign income taxes on $80,000 of foreign-source income. The taxpayer\'s worldwide income is $200,000 and U.S. tax liability (before credits) is $40,000. What is the foreign tax credit limitation?',
    options: [
      '$16,000 — the FTC limitation formula yields this amount, so the full $15,000 credit is allowed',
      '$15,000 — foreign taxes paid with no limitation',
      '$6,000 — 40% of foreign taxes',
      '$80,000 — the foreign-source income',
    ],
    correctAnswer: 0,
    explanation: 'The foreign tax credit limitation under IRC §904 = U.S. tax liability × (foreign-source taxable income ÷ worldwide taxable income) = $40,000 × ($80,000 ÷ $200,000) = $40,000 × 0.40 = $16,000. Since the $15,000 of foreign taxes paid is less than the $16,000 limitation, the full $15,000 credit is allowed.',
    reference: 'IRC §904',
  },
  {
    id: 'tcp-exp-040',
    section: 'TCP',
    courseId: 'cpa',
    topicId: 'tcp-international',
    topic: 'International Taxation',
    subtopic: 'FBAR Reporting',
    difficulty: 'hard',
    blueprintArea: 'TCP-IV',
    skillLevel: 'Application',
    question: 'FBAR reporting (FinCEN 114) is required when:',
    options: [
      'Any foreign account exists',
      'Aggregate foreign financial accounts exceed $10,000 at any time during the year',
      'Foreign income exceeds $100,000',
      'Foreign taxes are paid',
    ],
    correctAnswer: 1,
    explanation: 'FBAR: file if aggregate value of foreign financial accounts >$10,000 at any time. Due April 15 (auto extension to October). Separate from FATCA Form 8938 (higher thresholds). Penalties severe for non-filing.',
    reference: '31 USC §5314, 31 CFR 1010.350',
  },
];
