/**
 * CPA TCP Section - Questions Depth Batch 10
 * Blueprint Area: TCP-II (Entity Tax Compliance)
 * Topics: Partnership Tax Compliance, S Corp Compliance, Multi-Entity Structures
 */

import { Question } from '../../../types';

export const TCP_QUESTIONS_DEPTH_10: Question[] = [
  {
    id: 'tcp-d10-001',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Section 754 Election',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A §754 election, once made by a partnership, provides for optional basis adjustments under both §743(b) and §734(b). Under §743(b), when a partnership interest is transferred by sale or exchange or upon the death of a partner:',
    options: [
      'The partnership\'s basis in its assets is unchanged',
      'The partnership adjusts the basis of its assets with respect to the transferee partner only — the adjustment equals the difference between the transferee\'s outside basis (purchase price) and the transferee\'s share of the partnership\'s inside basis in its assets, allocated among the partnership assets under §755',
      'All partners\' bases are adjusted equally',
      'The partnership must revalue all assets at fair market value for all partners',
    ],
    correctAnswer: 1,
    explanation: 'IRC §754/§743(b) Optional Basis Adjustment — Transfer of Partnership Interest: When §754 election is in effect: upon sale/exchange of a partnership interest or death of a partner, the partnership adjusts its basis in partnership assets with respect to the transferee partner only. §743(b) adjustment = transferee\'s outside basis (purchase price or FMV at death) minus the transferee\'s proportionate share of partnership inside basis. The adjustment is personal to the transferee — other partners are not affected. Allocation under §755: the §743(b) adjustment is allocated between two classes: (1) ordinary income assets (inventory, unrealized receivables), and (2) capital/§1231 assets (everything else). Within each class, the adjustment is allocated based on the difference between the transferee\'s share of FMV and share of adjusted basis for each asset. Example: Partner A buys Partner B\'s 50% interest for $500,000. Partnership inside basis = $600,000 (A\'s share = $300,000). §743(b) adjustment = $500,000 − $300,000 = $200,000 increase. This eliminates the "phantom gain" problem: without the election, A would be taxed on built-in gain in partnership assets despite having paid FMV for the interest. Mandatory §743(b) adjustments: required (regardless of §754 election) if the partnership has a substantial built-in loss (>$250,000) under §743(d).',
    reference: 'IRC §754; §743(b); §755',
  },
  {
    id: 'tcp-d10-002',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Section 734(b) Adjustment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under a §754 election, §734(b) provides an adjustment to the basis of remaining partnership assets when a distribution causes:',
    options: [
      'No gain or loss to any partner',
      'Either: (1) gain recognition by the distributee partner (cash distribution exceeding basis), in which case the partnership increases its inside basis in remaining assets by the gain recognized, OR (2) the distributee partner takes a lower basis in distributed property than the partnership\'s basis, in which case the partnership increases its basis in remaining assets by the excess',
      'A partner\'s capital account to become negative',
      'The partnership to issue additional partnership interests',
    ],
    correctAnswer: 1,
    explanation: 'IRC §734(b) Optional Basis Adjustment — Distribution: When §754 election is in effect and a distribution occurs: Positive adjustments (increase inside basis of remaining assets): (1) distributee partner recognizes gain (cash distribution exceeds outside basis, §731(a)(1)) — partnership increases basis of remaining assets by gain recognized, OR (2) distributed property takes a lower basis in the distributee partner\'s hands than its partnership basis (because the distributee\'s outside basis is insufficient to absorb the full carryover basis, §732). Negative adjustments (decrease inside basis of remaining assets): (1) distributed property takes a higher basis in the distributee partner\'s hands than its partnership basis (§732(b) — liquidating distribution where outside basis exceeds inside basis of distributed property), OR (2) distributee partner recognizes a loss under §731(a)(2). Allocation under §755: positive adjustments allocated among remaining assets in the same class (ordinary or capital) as the assets that gave rise to the adjustment. Mandatory §734(b) adjustments: required (regardless of §754 election) if the partnership has a substantial basis reduction exceeding $250,000 (§734(d)).',
    reference: 'IRC §734(b); §754; §755',
  },
  {
    id: 'tcp-d10-003',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Corporate Liquidation — §331',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a C corporation completely liquidates and distributes its assets to shareholders, the tax consequences to the shareholders include:',
    options: [
      'All distributions are tax-free',
      'Shareholders treat amounts received in complete liquidation as full payment in exchange for their stock — capital gain or loss is recognized equal to the difference between the FMV of assets received and the shareholder\'s adjusted basis in the stock surrendered',
      'Shareholders recognize ordinary income on all distributions',
      'No basis adjustment is required',
    ],
    correctAnswer: 1,
    explanation: 'IRC §331 Complete Liquidation — Shareholder-Level Treatment: Shareholders treat liquidating distributions as payment in exchange for stock (sale or exchange treatment). Capital gain or loss = FMV of property received + cash received − adjusted basis of stock surrendered. Character: long-term or short-term capital gain/loss depending on holding period of the stock. Basis: shareholders take a FMV basis in property received (§334(a) — cost basis). Holding period: begins on the distribution date (new holding period). §336 — Corporation-level: the liquidating corporation recognizes gain or loss on distributions of property AS IF the property were sold at FMV. Exceptions under §336(d): (1) limitations on recognition of losses for certain related-party distributions, (2) distributions of property acquired in §351 transactions within 5 years (if principal purpose was tax avoidance), losses may be disallowed. §332 — Special rule for subsidiary liquidations: no gain or loss to an 80%+ parent corporation on complete liquidation of a subsidiary (§332); parent takes carryover basis in assets (§334(b)(1)); subsidiary recognizes no gain or loss on distributions to the parent (§337).',
    reference: 'IRC §331; §334; §336',
  },
  {
    id: 'tcp-d10-004',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'S Corp Termination Events',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An S corporation election is involuntarily terminated when:',
    options: [
      'The corporation files Form 1120-S late',
      'Any of the eligibility requirements cease to be met — including exceeding 100 shareholders, having an ineligible shareholder (partnership, C corporation, nonresident alien), creating a second class of stock, or having excess passive investment income for 3 consecutive years while holding accumulated C corporation E&P',
      'The corporation earns a profit',
      'A shareholder sells stock to another individual',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1362(d) Termination of S Corporation Election: Voluntary revocation (§1362(d)(1)): shareholders holding more than 50% of issued and outstanding shares consent to revocation; effective date can be specified or defaults to beginning of next tax year (or current year if filed on or before the 15th day of the 3rd month). Involuntary termination (§1362(d)(2)): election terminates automatically if any §1361 requirement is violated — exceeds 100 shareholders, ineligible shareholder acquires stock (partnership, C corporation, nonresident alien, certain trusts), second class of stock is created (stock with different distribution or liquidation rights), or the corporation becomes an ineligible corporation type. Effective date: the day the terminating event occurs; the S corporation has two short tax years (S corporation short year + C corporation short year). Passive income termination (§1362(d)(3)): if the S corporation has accumulated E&P from C corporation years AND passive investment income exceeds 25% of gross receipts for 3 consecutive tax years. Inadvertent termination relief (§1362(f)): IRS may waive a termination if it was inadvertent, steps were taken promptly to correct the problem, and the corporation and shareholders agree to treatment as if the election had been continuously in effect. Waiting period: if S election is terminated (voluntary or involuntary), the corporation generally cannot re-elect S status for 5 years without IRS consent (§1362(g)).',
    reference: 'IRC §1362(d); §1361',
  },
  {
    id: 'tcp-d10-005',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Disproportionate Distributions — §751(b)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'IRC §751(b) applies when a partnership makes a disproportionate distribution, meaning:',
    options: [
      'A partner receives more cash than other partners',
      'A distributee partner receives more or less than their proportionate share of the partnership\'s hot assets (unrealized receivables and substantially appreciated inventory) — triggering deemed exchange treatment where the partner is treated as exchanging the disproportionate hot or cold assets with the partnership, resulting in gain or loss recognition',
      'The partnership distributes property unequally among all partners',
      'A partner contributes additional capital',
    ],
    correctAnswer: 1,
    explanation: 'IRC §751(b) Disproportionate Distributions: Trigger: a distribution causes a shift between the distributee partner\'s interest in §751 assets (hot assets: unrealized receivables and substantially appreciated inventory) and non-§751 assets (capital/§1231 assets, cash). Two-step analysis: Step 1 — Compare the distributee partner\'s proportionate share of hot assets before the distribution with their share of hot assets after the distribution. If there is a change (increase or decrease) in the partner\'s share of hot assets, a disproportionate distribution has occurred. Step 2 — Deemed exchange: the distribution is bifurcated into (a) a proportionate distribution (nonrecognition under §731/§732), and (b) a deemed exchange of hot assets for cold assets (or vice versa). Recognition on the deemed exchange: ordinary income/loss on the hot asset portion, capital gain/loss on the cold asset portion. Example: Partner A (1/3 interest) receives $100,000 cash distributing out their interest. Partnership has $150,000 in unrealized receivables and $150,000 in other assets. A\'s share of hot assets was $50,000 (1/3 × $150,000). By receiving only cash (cold), A gave up $50,000 of hot asset share — treated as exchanging $50,000 of unrealized receivables for $50,000 of cash (ordinary income to A). Complex in practice — IRS and practitioners have long debated simplification of §751(b).',
    reference: 'IRC §751(b)',
  },
  {
    id: 'tcp-d10-006',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Net Operating Loss (Corporate)',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under current law (post-TCJA, as modified by the CARES Act), a C corporation\'s net operating loss (NOL):',
    options: [
      'Can be carried back 2 years and forward 20 years with no limitation',
      'For tax years beginning after December 31, 2020: NOLs can be carried forward indefinitely (no carryback) and are limited to 80% of taxable income in the carryforward year — NOLs arising in 2018-2020 received special 5-year carryback treatment under the CARES Act',
      'Is permanently lost if not used in the current year',
      'Can only offset passive income',
    ],
    correctAnswer: 1,
    explanation: 'Corporate Net Operating Losses (post-TCJA and CARES Act): Pre-TCJA (before 2018): 2-year carryback, 20-year carryforward, no limitation on amount. TCJA (for NOLs arising after 2017): no carryback (with exceptions), indefinite carryforward, 80% taxable income limitation on deduction. CARES Act modification (2020): for NOLs arising in 2018, 2019, and 2020: 5-year carryback allowed (electable), 80% limitation suspended for tax years beginning before January 1, 2021. Current law (tax years beginning after December 31, 2020): Carryforward: indefinite (no expiration). Carryback: generally not allowed (exceptions: farming losses — 2-year carryback, certain insurance company losses). 80% limitation: NOL deduction limited to 80% of taxable income (computed without the NOL deduction). This means 20% of taxable income is always exposed to tax, even with significant NOL carryforwards. Ordering: oldest NOLs used first (FIFO). Book-tax difference: NOLs create a deferred tax asset on financial statements (ASC 740); valuation allowance may be needed if it is more likely than not that the DTA will not be realized.',
    reference: 'IRC §172 (as amended by TCJA §13302 and CARES Act §2303)',
  },
  {
    id: 'tcp-d10-007',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Nonrecourse Liabilities — §752',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under IRC §752 and the regulations, a partner\'s share of nonrecourse partnership liabilities is allocated based on:',
    options: [
      'Equal sharing among all partners',
      'A three-tier approach: (1) first, to partners who would recognize gain on a constructive disposition of all partnership assets for no consideration (§704(c) minimum gain), (2) next, to partners to the extent of partnership minimum gain allocable to them under §1.704-2, (3) finally, in accordance with profit-sharing ratios',
      'Each partner\'s capital account balance',
      'Each partner\'s guaranteed payment amount',
    ],
    correctAnswer: 1,
    explanation: 'IRC §752 and Treas. Reg. §1.752-3 — Nonrecourse Liabilities: Background: a partner\'s share of partnership liabilities increases their outside basis (§752(a) — treated as contribution), which enables deductions for losses and tax-free distributions. Nonrecourse liabilities (no personal liability): allocated under a three-tier approach: Tier 1 — §704(c) minimum gain: to the contributing partner to the extent of the built-in gain that would be recognized if the partnership disposed of all §704(c) property for no consideration. Example: if Partner A contributes property with FMV $100 and basis $60, secured by a $70 nonrecourse mortgage, A\'s Tier 1 share = $10 (built-in §704(c) gain, limited to the nonrecourse liability). Tier 2 — Partnership minimum gain (§1.704-2): to partners to the extent of the minimum gain (nonrecourse liability exceeds book value of encumbered property) allocated to them under the minimum gain chargeback provisions. Tier 3 — Profit sharing ratios: the remaining nonrecourse liabilities are allocated based on the partners\' shares of profits (generally specified in the partnership agreement). Recourse liabilities: allocated to the partner(s) who bear the economic risk of loss (§1.752-2) — typically the partner who is personally liable or who would be required to make a payment with no right of reimbursement.',
    reference: 'IRC §752; Treas. Reg. §1.752-3',
  },
  {
    id: 'tcp-d10-008',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'S Corp Debt Basis',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An S corporation shareholder may deduct losses only to the extent of their stock basis plus debt basis. Debt basis arises from:',
    options: [
      'Any debt of the S corporation, including bank loans and trade payables',
      'Direct loans from the shareholder to the S corporation (or the shareholder\'s guarantees if the shareholder makes actual economic outlay) — unlike partnerships, entity-level third-party debt does not increase an S corporation shareholder\'s basis',
      'Accounts payable owed by the corporation to vendors',
      'Distributions received from the corporation',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1366(d) — S Corporation Loss Deduction Limitations: Two-tier basis limitation: (1) stock basis (IRC §1367), (2) debt basis — direct loans from the shareholder to the S corporation. Key distinction from partnerships: S corporation shareholders do NOT get basis for entity-level third-party debt. Only direct shareholder loans to the corporation create debt basis. Guarantee alone is insufficient: a shareholder guaranteeing a bank loan to the S corporation does NOT get basis unless the shareholder actually makes a payment on the guarantee (economic outlay doctrine — Selfe v. United States). Back-to-back loan: shareholder borrows from the bank and re-lends to the S corporation — creates debt basis (because the shareholder has direct loans to the corp). Loss deduction ordering: losses first reduce stock basis to zero, then reduce debt basis to zero. Excess losses are suspended and carried forward indefinitely. Basis restoration ordering: income first restores debt basis (before increasing stock basis) to allow the corporation to repay the shareholder loan tax-free. Then excess income increases stock basis. This ordering protects the shareholder from recognizing gain when the corporation repays shareholder loans.',
    reference: 'IRC §1366(d); §1367',
  },
  {
    id: 'tcp-d10-009',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Qualified Subchapter S Trust (QSST)',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'A Qualified Subchapter S Trust (QSST) may be an S corporation shareholder if:',
    options: [
      'The trust has multiple beneficiaries',
      'The trust has exactly one current income beneficiary (who must be a U.S. citizen or resident), all trust income must be distributed currently to that beneficiary, corpus distributions can only be made to the current income beneficiary, the income interest must end at the earlier of the beneficiary\'s death or trust termination, and the beneficiary must elect QSST status',
      'The trust is a grantor trust',
      'The trustee is a financial institution',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1361(d)(3) Qualified Subchapter S Trust (QSST): Requirements: (1) One current income beneficiary — must be a U.S. citizen or resident individual, (2) All income distributed currently — trust must distribute all income (net accounting income) at least annually, (3) Corpus distributions limited — during the income beneficiary\'s life, corpus may be distributed only to that beneficiary, (4) Income interest terminates — at the earlier of the beneficiary\'s death or trust termination, (5) Upon termination during the beneficiary\'s life — all trust assets must be distributed to the beneficiary. Election: the current income beneficiary (not the trustee) must elect QSST status. The election is irrevocable without IRS consent. Treatment: the income beneficiary is treated as the shareholder for §1366 pass-through purposes. The beneficiary is treated as the owner of the S corporation stock under grantor trust rules (§678) — all S corporation income items pass through to the beneficiary. Alternative: Electing Small Business Trust (ESBT) — §1361(e): more flexible than QSST (allows multiple beneficiaries, allows income accumulation), but the S corporation income is taxed at the trust level at the highest individual rate (37%).',
    reference: 'IRC §1361(d)(3); §678',
  },
  {
    id: 'tcp-d10-010',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Earnings and Profits (E&P)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Earnings and profits (E&P) of a C corporation is a tax concept (not a GAAP concept) that determines:',
    options: [
      'The corporation\'s taxable income',
      'Whether distributions to shareholders are taxable as dividends (to the extent of current and accumulated E&P), return of capital (reducing stock basis), or capital gain (after basis is exhausted) — E&P is computed by starting with taxable income and making specific adjustments to reflect the corporation\'s true economic ability to pay dividends',
      'The corporation\'s book value',
      'The amount of depreciation deduction',
    ],
    correctAnswer: 1,
    explanation: 'Earnings and Profits (E&P) — IRC §312: Purpose: E&P measures the corporation\'s capacity to make distributions out of earnings (not just capital). It determines dividend treatment under §301(c). Distribution ordering (§301(c)): (1) Dividend — to the extent of current + accumulated E&P (ordinary income to shareholder; qualified dividend rate if holding period met), (2) Return of capital — nontaxable reduction of stock basis (after E&P exhausted), (3) Capital gain — after stock basis is reduced to zero. Computing E&P — adjustments to taxable income: ADD BACK: federal income tax, excess charitable contributions, penalties/fines, related-party losses deferred under §267, excess capital losses, life insurance premiums (where corp is beneficiary). SUBTRACT: life insurance proceeds received (already excluded from taxable income, but increase E&P — actually, proceeds are tax-free and INCREASE E&P by the excess over premiums paid), federal income tax (reduces E&P). KEY ADJUSTMENTS: Depreciation: use ADS straight-line (not MACRS accelerated or bonus depreciation), resulting in higher E&P than taxable income when accelerated depreciation is used. §179 expense: spread over the asset\'s useful life for E&P. Installment sales: include full gain in E&P in year of sale (not spread over installment period). Municipal bond interest: added to E&P (tax-exempt income increases E&P). Current vs. accumulated E&P: distributions first come from current E&P (allocated pro-rata to distributions during the year), then from accumulated E&P (chronological — FIFO).',
    reference: 'IRC §312; §301(c)',
  },
  {
    id: 'tcp-d10-011',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Partnership Anti-Abuse Rules',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The partnership anti-abuse rules under Treas. Reg. §1.701-2 allow the IRS to:',
    options: [
      'Disallow all partnership deductions',
      'Recast a partnership transaction if the partnership is formed or availed of with a principal purpose of substantially reducing the present value of the partners\' aggregate federal tax liability in a manner inconsistent with the intent of Subchapter K — the IRS can treat the partnership as an aggregate of its partners or recharacterize the transaction',
      'Convert all partnerships to C corporations',
      'Require all partnerships to use the accrual method',
    ],
    correctAnswer: 1,
    explanation: 'Treas. Reg. §1.701-2 Partnership Anti-Abuse Rules: General rule: Subchapter K is intended to permit taxpayers to conduct joint business activities through a flexible arrangement that accurately reflects the partners\' economic agreement. If a partnership is formed or availed of for a principal purpose of substantially reducing the aggregate tax liability of its partners, and that reduction is inconsistent with the intent of Subchapter K, the IRS may recast the transaction. Powers: (1) treat the partnership as an aggregate of its partners (rather than an entity) for the relevant transaction, (2) recast the transaction to conform with the partners\' economic arrangement, (3) disregard the partnership form entirely, (4) modify the allocation of income/deductions. Abuse indicators: (a) the present value of the partners\' aggregate tax liability is substantially less than it would be without the partnership, (b) the tax results are inconsistent with Subchapter K\'s intent, (c) the partnership is used primarily for tax avoidance (e.g., exploiting basis shifting, loss trafficking, allocation gaming). Related rule: §1.704-1(b)(2)(iii) — abusive allocations where the allocation\'s substantiality requirement is not met because of transitory or shifting allocations with a tax-avoidance purpose. The partnership anti-abuse rules are rarely invoked but serve as a background anti-avoidance principle.',
    reference: 'Treas. Reg. §1.701-2',
  },
  {
    id: 'tcp-d10-012',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Tax-Free Reorganizations — §368',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Which of the following is a Type A reorganization under IRC §368(a)(1)(A)?',
    options: [
      'A stock purchase by one corporation of another corporation\'s shares',
      'A statutory merger or consolidation under state law in which one corporation absorbs another (or two corporations combine into a new entity) — shareholders of the acquired corporation exchange their stock for stock (and potentially limited boot) of the acquiring corporation on a tax-deferred basis',
      'A sale of assets for cash',
      'A complete liquidation of a corporation',
    ],
    correctAnswer: 1,
    explanation: 'IRC §368(a)(1)(A) Type A Reorganization — Statutory Merger or Consolidation: Definition: a statutory merger (one corp absorbs another) or consolidation (two corps form a new entity) under applicable state, federal, or foreign law. Requirements: (1) must qualify under state merger statute, (2) must meet the judicial doctrines: continuity of interest (COI) — a substantial portion (typically 40%+) of the acquired corporation\'s shareholders must receive stock consideration (Treas. Reg. §1.368-1(e)), continuity of business enterprise (COBE) — acquirer must continue the target\'s historic business or use a significant portion of the target\'s historic business assets (Treas. Reg. §1.368-1(d)), business purpose — the reorganization must have a legitimate business purpose (Gregory v. Helvering). Advantages of Type A: most flexible — permits payment of cash or other boot (unlike Type B which requires solely voting stock), no asset-by-asset transfer required (occurs by operation of law), all liabilities transfer by operation of law. Tax consequences: target shareholders: non-recognition on stock-for-stock exchange (§354); boot taxed but not in excess of realized gain (§356). Target corporation: no gain/loss on transfer of assets (§361); but gains on boot property distributed to shareholders. Acquiring corporation: carryover basis in acquired assets (§362(b)); tacks target\'s holding period. Related types: forward triangular merger (§368(a)(2)(D)), reverse triangular merger (§368(a)(2)(E)).',
    reference: 'IRC §368(a)(1)(A); §354; §361; §362',
  },
  {
    id: 'tcp-d10-013',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Separately Stated Items',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'S corporation items that must be separately stated on Schedule K-1 include all of the following EXCEPT:',
    options: [
      'Net long-term capital gain or loss',
      'Cost of goods sold',
      'Charitable contributions',
      'Section 179 expense deduction',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1366 — S Corporation Separately Stated Items: Items that must be separately stated are those that could have a different tax effect at the shareholder level depending on the shareholder\'s particular circumstances. Must be separately stated: (1) net short-term and long-term capital gains/losses (§1(h) rates, §1211 limitations), (2) §1231 gains/losses, (3) charitable contributions (§170 percentage limitations at shareholder level), (4) §179 expense deduction (dollar and income limitations at shareholder level), (5) interest income, dividend income, royalties, (6) rental income/loss (passive activity rules), (7) tax-exempt income, (8) investment interest expense (§163(d) limitation), (9) foreign taxes paid (credit vs. deduction election at shareholder level), (10) portfolio income items, (11) AMT preference items. NOT separately stated (combined in non-separately stated income/loss): ordinary business income/loss (gross receipts minus COGS, minus ordinary business deductions like salaries, rent, depreciation, supplies, utilities). Cost of goods sold is a component of computing non-separately stated ordinary business income — it is netted within the income computation on Form 1120-S page 1, not reported separately on Schedule K-1.',
    reference: 'IRC §1366(a); Form 1120-S Instructions',
  },
  {
    id: 'tcp-d10-014',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Simple vs. Complex Trusts',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'A trust is classified as a "simple trust" for a given tax year when:',
    options: [
      'The trust has only one beneficiary',
      'The trust instrument requires that all income must be distributed currently, the trust does not make any distributions of corpus, and the trust does not make any payments for charitable purposes — otherwise it is classified as a complex trust for that year',
      'The trust has less than $100,000 in assets',
      'The trust was created by a will',
    ],
    correctAnswer: 1,
    explanation: 'Simple Trust vs. Complex Trust: Simple trust (IRC §§651-652) — three requirements for that tax year: (1) The trust instrument requires distribution of all fiduciary accounting income (FAI) currently to the beneficiaries, (2) No distribution of trust corpus (principal) is made during the year, (3) No amounts are paid, permanently set aside, or to be used for charitable purposes. Personal exemption: $300 for a simple trust. Taxation: the trust receives a deduction for income required to be distributed (income distribution deduction — §651), limited to DNI. Beneficiaries include their proportionate share of DNI in income (§652). Complex trust (IRC §§661-663) — any trust that is NOT simple for the tax year: may accumulate income, may distribute corpus, may make charitable contributions. Personal exemption: $100 for a complex trust ($0 for certain trusts required to distribute all income). Trust can be simple one year and complex the next (e.g., if it distributes corpus in year 2 but not year 1). Distributions in excess of DNI: tax-free to beneficiaries (return of capital/prior accumulated income already taxed to the trust). Tier system for complex trusts: Tier 1 — income required to be distributed currently (first claim on DNI), Tier 2 — all other amounts properly paid or credited to beneficiaries (share remaining DNI).',
    reference: 'IRC §§651-652 (simple); §§661-663 (complex)',
  },
  {
    id: 'tcp-d10-015',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Partnership Distributions — §731',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the general distribution rules of IRC §731, a partner recognizes gain on a current (non-liquidating) distribution only when:',
    options: [
      'The partner receives any property',
      'The amount of cash (including deemed cash from liability relief) distributed exceeds the partner\'s outside basis in the partnership interest — gain is capital gain (assuming the partnership interest is a capital asset)',
      'The partner receives property with a FMV greater than its basis',
      'The distribution is of hot assets',
    ],
    correctAnswer: 1,
    explanation: 'IRC §731 Partnership Distributions — General Rules: Current (non-liquidating) distributions: Gain recognition: only when cash distributed (including deemed cash under §752 — reduction in partner\'s share of liabilities) exceeds the partner\'s outside basis. The gain = excess cash over basis. Character: capital gain (assuming partnership interest is a capital asset — §741). Loss recognition: NEVER on a current distribution (loss can only be recognized on a liquidating distribution, and only if the partner receives only cash, unrealized receivables, and/or inventory — §731(a)(2)). Basis of distributed property (§732(a)): carryover basis (partnership\'s basis transfers to the partner), BUT limited to the partner\'s remaining outside basis (after reduction for cash). If multiple properties distributed and partner\'s basis is insufficient: allocate basis first to unrealized receivables and inventory (up to partnership basis), then remaining basis to other property. Partner\'s outside basis after distribution (§733): reduced by cash received and the basis of property received. Exceptions to nonrecognition: (1) §751(b) — disproportionate distributions involving hot assets may trigger ordinary income, (2) §737 — distribution of property when partner had previously contributed appreciated property (may trigger recognition of pre-contribution gain).',
    reference: 'IRC §731; §732; §733',
  },
  {
    id: 'tcp-d10-016',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Section 1202 — QSBS Exclusion',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under IRC §1202, a non-corporate taxpayer may exclude gain from the sale of Qualified Small Business Stock (QSBS) acquired after September 27, 2010, up to:',
    options: [
      '50% of the gain',
      '100% of the gain (up to the greater of $10 million or 10 times the adjusted basis of the QSBS), provided the stock was held for more than 5 years and was acquired at original issuance from a qualified small business (domestic C corporation with gross assets not exceeding $50 million)',
      '75% of the gain with no holding period requirement',
      'Only gains up to $1 million',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1202 Qualified Small Business Stock (QSBS) Exclusion: Exclusion percentage: 100% for stock acquired after September 27, 2010 (75% for stock acquired 2/18/2009 – 9/27/2010; 50% for stock acquired before 2/18/2009). Requirements: (1) Stock of a domestic C corporation (S corporations do not qualify), (2) Acquired at original issuance (from the corporation directly, not in the secondary market) in exchange for money, property (not stock), or services, (3) Corporation is a qualified small business — aggregate gross assets did not exceed $50 million at any time before or immediately after the issuance (includes assets of predecessor corporations), (4) Active business requirement — at least 80% of assets used in the active conduct of a qualified trade or business (excludes: professional services, banking, insurance, farming, mining, hospitality, real estate), (5) More than 5 years holding period. Limitation: greater of (a) $10 million per issuer (lifetime, per taxpayer), or (b) 10 times the adjusted basis of QSBS disposed of during the tax year. Stacking: per-issuer limit — taxpayer can exclude $10M from each qualifying company. No AMT add-back for 100% exclusion stock. §1045 rollover: if held less than 5 years, can roll gain into new QSBS within 60 days.',
    reference: 'IRC §1202',
  },
  {
    id: 'tcp-d10-017',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: 'Electing Small Business Trust (ESBT)',
    difficulty: 'hard',
    skillLevel: 'Application',
    question: 'An Electing Small Business Trust (ESBT) differs from a QSST in which significant way?',
    options: [
      'An ESBT cannot hold S corporation stock',
      'An ESBT may have multiple current beneficiaries and may accumulate income — however, the S corporation income portion is taxed at the trust level at the highest individual tax rate (37%) rather than flowing through to beneficiaries',
      'An ESBT must distribute all income currently',
      'An ESBT may only have corporate beneficiaries',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1361(e) Electing Small Business Trust (ESBT): Key differences from QSST: (1) Multiple beneficiaries permitted — can have many individual beneficiaries (must be individuals, estates, or charities), (2) Income accumulation allowed — no requirement to distribute income currently, (3) Corpus distributions — may be made to any beneficiary. ESBT tax treatment: the trust is bifurcated into two portions: (a) S corporation portion — all S corporation income items are taxed within the trust at the highest individual marginal rate (currently 37%); no deductions are allowed against this portion except state and local income taxes and administrative expenses directly related to the S corporation stock; capital gains from sale of S corp stock are included in this portion, (b) Non-S corporation portion — all other trust income taxed under normal trust rules (compressed brackets, income distribution deduction available). Each potential current beneficiary counts as one shareholder for the 100-shareholder limit. Election: trustee makes the election (not the beneficiary, unlike QSST). ESBT cannot have a nonresident alien as a potential current beneficiary. No exempt organizations as beneficiaries (except charitable organizations). ESBT is preferred when: grantor wants flexibility in distributions, multiple beneficiaries exist, or income accumulation is desired — at the cost of being taxed at the highest rate.',
    reference: 'IRC §1361(e); §641(c)',
  },
  {
    id: 'tcp-d10-018',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Partnership Interest Classification',
    difficulty: 'medium',
    skillLevel: 'Remembering and Understanding',
    question: 'A partnership interest is classified as either a capital interest or a profits interest. Which statement correctly describes a profits interest?',
    options: [
      'It entitles the partner to a share of the partnership\'s existing capital',
      'A profits interest entitles the holder only to a share of future partnership profits and appreciation — not to any share of existing capital on immediate liquidation; under Rev. Proc. 93-27, receipt of a profits interest for services is generally not a taxable event',
      'It is the same as a capital interest',
      'It can only be received in exchange for property contributions',
    ],
    correctAnswer: 1,
    explanation: 'Partnership Capital Interest vs. Profits Interest: Capital interest: entitles the partner to a share of the partnership\'s assets on immediate liquidation — the partner would receive a distribution based on the current value of partnership assets. Receipt of a capital interest for services is taxable as compensation (the partner has received something of current value). Profits interest: entitles the partner only to a share of future income, gains, and appreciation — if the partnership liquidated immediately after the grant, the profits interest holder would receive nothing. Tax treatment of profits interest (Rev. Proc. 93-27, clarified by Rev. Proc. 2001-43): generally NOT a taxable event when received for services, provided three conditions are met: (1) the interest is not related to a substantially certain and predictable stream of income, (2) the partner does not dispose of the interest within 2 years, and (3) the interest is not a limited partnership interest in a publicly traded partnership. Rationale: a profits interest has no current liquidation value, so there is nothing to tax — the partner will be taxed as profits are earned and allocated. This makes profits interests an attractive tool for compensating service partners (managers, key employees) in partnerships and LLCs without triggering immediate tax. Proposed regulations (2005): would have required partnerships to treat a profits interest valued at $0 at grant date, consistently with Rev. Proc. 93-27.',
    reference: 'Rev. Proc. 93-27; Rev. Proc. 2001-43',
  },
  {
    id: 'tcp-d10-019',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Section 382 Limitation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'IRC §382 limits the use of a loss corporation\'s pre-change NOLs after an ownership change. An "ownership change" occurs when:',
    options: [
      'Any change in the corporation\'s management',
      'One or more 5-percent shareholders increase their aggregate ownership in the loss corporation by more than 50 percentage points during a 3-year testing period — the annual §382 limitation equals the value of the loss corporation immediately before the change multiplied by the long-term tax-exempt rate',
      'The corporation changes its state of incorporation',
      'The corporation issues preferred stock',
    ],
    correctAnswer: 1,
    explanation: 'IRC §382 — NOL Limitation After Ownership Change: Ownership change: one or more "5-percent shareholders" increase their aggregate stock ownership by more than 50 percentage points during the "testing period" (generally a rolling 3-year period). 5-percent shareholders: individuals or entities owning 5% or more of the loss corporation\'s stock. All shareholders owning less than 5% are treated as a single 5-percent shareholder (public group). §382 limitation = FMV of the loss corporation\'s stock immediately before the ownership change × the long-term tax-exempt rate (published monthly by IRS — approximately 4-5% in 2024). Example: loss corporation worth $10 million, long-term tax-exempt rate 5% → annual §382 limitation = $500,000. The loss corporation can use only $500,000 of pre-change NOLs per year (unused limitation carries forward). Built-in gains: if the loss corporation has net unrealized built-in gains (NUBIG) at the time of the ownership change, recognized built-in gains during the 5-year recognition period increase the §382 limitation. Built-in losses: if net unrealized built-in losses (NUBIL) exist, built-in losses recognized post-change are also subject to the §382 limitation. Continuity of business enterprise: if the loss corporation does not continue its business enterprise for 2 years after the change, the §382 limitation is reduced to zero (complete loss of pre-change NOLs). Purpose: prevent trafficking in NOLs by acquiring loss corporations solely to use their tax losses.',
    reference: 'IRC §382; §383',
  },
  {
    id: 'tcp-d10-020',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Late S Election Relief',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A corporation that fails to file a timely S election (Form 2553 by the 15th day of the 3rd month of the tax year) may obtain relief through:',
    options: [
      'Filing an amended Form 1120',
      'Rev. Proc. 2013-30 — which provides simplified relief for late S corporation elections, late QSST/ESBT elections, and late corporate classification (entity classification) elections if the entity can demonstrate reasonable cause, has operated as if the election were in effect, and files within 3 years and 75 days of the intended effective date',
      'Paying a penalty of $10,000',
      'There is no relief available',
    ],
    correctAnswer: 1,
    explanation: 'Late S Election Relief — Rev. Proc. 2013-30: Provides simplified procedures for obtaining relief for late elections. Eligibility requirements: (1) The entity intended to be classified as the elected entity type (S corp), (2) The entity failed to timely file the election solely because of reasonable cause, (3) The entity has not filed a return inconsistent with the intended election for any year (it has filed Form 1120-S, not Form 1120), (4) Less than 3 years and 75 days have elapsed since the intended effective date of the election. How to file: attach a statement to Form 2553 explaining the reasonable cause for the late filing, and submit it along with the completed Form 2553. If the entity has already been filing S corporation returns: no user fee required (unlike Private Letter Ruling requests). Also covers: late QSST elections (§1361(d)(2)), late ESBT elections (§1361(e)(3)), late entity classification elections (Form 8832). If outside the 3 year and 75-day window: taxpayer must request a Private Letter Ruling from the IRS (user fee required — approximately $10,000+), demonstrating reasonable cause under §1362(b)(5) or §9100 relief (Treas. Reg. §301.9100). Alternative: §1362(b)(5) — IRS may treat a late election as timely if there is reasonable cause for the failure.',
    reference: 'Rev. Proc. 2013-30; IRC §1362(b)(5)',
  },
  {
    id: 'tcp-d10-021',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Trust and Estate Taxation',
    subtopic: '65-Day Election — §663(b)',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the §663(b) "65-day election," a trust or estate:',
    options: [
      'Must wait 65 days before making any distributions',
      'May elect to treat distributions made within the first 65 days of the following tax year as if they were made on the last day of the preceding tax year — allowing the trust to claim the income distribution deduction for the prior year and shift income tax liability to the beneficiaries',
      'Must file its return within 65 days',
      'Receives a 65-day extension to pay taxes',
    ],
    correctAnswer: 1,
    explanation: 'IRC §663(b) — 65-Day Election: Available to: complex trusts and estates (not simple trusts — they must distribute all income currently anyway). Election: the trustee may elect to treat distributions made within the first 65 days of the following tax year as if they were made on the last day of the preceding tax year. Effect: the trust/estate claims the income distribution deduction (§661) for the prior tax year, reducing trust-level taxable income. The beneficiaries include the distribution in their income for the year of actual receipt (the following year — but the distribution carries out DNI of the prior year). Why use it: (1) tax rate compression — trusts reach the highest bracket at ~$14,450 vs. ~$609,350 for single individuals, so distributing income to beneficiaries in lower brackets saves tax; (2) flexibility — trustee can wait until after year-end to determine optimal distribution amount based on actual income; (3) timing — trustee may not be able to determine exact income until after year-end. How to elect: statement attached to the trust/estate\'s Form 1041 for the preceding tax year, filed by the due date (including extensions). The election is irrevocable for that year. Limitation: only applies to distributions actually made within the 65-day window — the trust cannot simply declare a distribution without actually paying it. Distributions exceeding DNI: excess is tax-free to beneficiaries (treated as distribution of corpus/accumulated income already taxed).',
    reference: 'IRC §663(b)',
  },
  {
    id: 'tcp-d10-022',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Partnership Taxation',
    subtopic: 'Centralized Partnership Audit Regime',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the Bipartisan Budget Act of 2015 (BBA) centralized partnership audit regime (effective for tax years beginning after 2017), the default treatment when the IRS adjusts partnership items is:',
    options: [
      'Each partner files an amended return',
      'The partnership itself pays an "imputed underpayment" at the highest individual or corporate tax rate applicable — the partnership representative (who replaces the former tax matters partner) has sole authority to act on behalf of the partnership during exam',
      'No tax is owed by anyone',
      'The IRS directly contacts each partner individually',
    ],
    correctAnswer: 1,
    explanation: 'BBA Centralized Partnership Audit Regime (IRC §§6221-6241): Effective: tax years beginning after December 31, 2017. Default rule: IRS audits the partnership (not individual partners). Adjustments are assessed and collected at the partnership level as an "imputed underpayment." Imputed underpayment calculation: net adjustment amount × highest tax rate (37% for individuals, 21% for C corporations) = imputed underpayment. Partnership representative (§6223): replaces the tax matters partner (TEFRA regime). Sole authority to bind the partnership during audit — partners have no independent rights to participate. Does not need to be a partner. Alternatives to entity-level payment: (1) Push-out election (§6226): partnership elects to push out adjustments to the reviewed-year partners. Partners file amended returns or receive adjusted K-1s. Partners pay additional tax plus interest. (2) Modification (§6225(c)): partnership can request modification of the imputed underpayment — partners file amended returns (and pay additional tax) to reduce the imputed underpayment proportionally. (3) Election out (§6221(b)): eligible partnerships may elect out entirely — available to partnerships with 100 or fewer qualifying partners (individuals, C corporations, S corporations, estates of deceased partners) and no partners that are partnerships, disregarded entities, or trusts. Annual election on timely-filed Form 1065. Small partnerships (≤100 eligible partners): most advantageous to elect out.',
    reference: 'IRC §§6221-6241; BBA 2015',
  },
  {
    id: 'tcp-d10-023',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'C Corporation Taxation',
    subtopic: 'Consolidated Returns — §1501',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An affiliated group of C corporations may elect to file a consolidated return under IRC §1501. Which of the following is an advantage of filing a consolidated return?',
    options: [
      'Each member corporation retains its own separate tax liability',
      'Losses of one member corporation can offset income of another member corporation within the group — intercompany transactions are deferred until the item is recognized outside the group, and the parent can use subsidiary losses as they arise rather than waiting for liquidation or sale',
      'The consolidated group pays tax at a lower rate',
      'Each member can elect a different tax year',
    ],
    correctAnswer: 1,
    explanation: 'IRC §1501-§1504 Consolidated Returns: Affiliated group: parent corporation owns at least 80% of voting power AND 80% of value of at least one subsidiary (directly), and the group includes all corporations connected through 80% ownership chain. Advantages: (1) losses of one member offset income of another (intragroup loss utilization), (2) intercompany gains are deferred until triggered by a disposition outside the group, (3) intercompany dividends are eliminated (not subject to DRD limitations), (4) single return simplifies compliance. Disadvantages: (1) binding election — once made, cannot revoke without IRS consent (must include all eligible members), (2) SRLY rules — Separate Return Limitation Year rules limit use of pre-affiliation NOLs of a member that joins the group, (3) consolidated return change of ownership (CRCO) rules may limit NOLs, (4) intercompany transaction regulations are complex. Excluded entities: S corporations, certain foreign corporations, tax-exempt organizations, REITs, RICs, and life insurance companies (with exceptions) cannot be included. Consolidated taxable income: computed by aggregating all members\' separate taxable incomes, then making consolidation adjustments (eliminate intercompany items, apply consolidated limitations on charitable deductions, §382 limitations, etc.).',
    reference: 'IRC §1501-§1504; Treas. Reg. §1.1502-*',
  },
  {
    id: 'tcp-d10-024',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Tax-Exempt Organizations',
    subtopic: 'UBIT — §511',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A tax-exempt organization under IRC §501(c)(3) is subject to unrelated business income tax (UBIT) on income from:',
    options: [
      'All sources',
      'A trade or business that is regularly carried on and not substantially related to the organization\'s exempt purpose — subject to the corporate tax rate (21%) for exempt corporations or trust tax rates for exempt trusts, with a $1,000 specific deduction',
      'Donations and grants',
      'Investment income only',
    ],
    correctAnswer: 1,
    explanation: 'IRC §§511-514 Unrelated Business Income Tax (UBIT): Three-part test: (1) Trade or business — any activity carried on for the production of income from selling goods or performing services (§513(c)), (2) Regularly carried on — frequency and continuity comparable to commercial activities of for-profit organizations (not occasional fundraisers like annual bake sales), (3) Not substantially related — the activity does not contribute importantly to the organization\'s exempt purpose (the fact that income is used for exempt activities is not sufficient). Tax rate: 21% corporate rate for exempt corporations; trust rates for exempt trusts. $1,000 specific deduction. Exclusions from UBIT: (1) passive income: dividends, interest, royalties, rents from real property (not personal property unless incidental), annuities, capital gains from sale of property, (2) income from activities where substantially all work is performed by volunteers, (3) income from sale of donated merchandise, (4) certain bingo games, (5) qualified sponsorship payments. Debt-financed income (§514): passive income (otherwise excluded) is taxable as UBIT to the extent the property generating the income is financed with acquisition indebtedness (debt-financed property × income allocation = UBIT). Siloing rule (2017 TCJA): each unrelated trade or business must be reported separately (losses from one UBI activity cannot offset income from another — but this was later modified by regulations requiring separate tracking).',
    reference: 'IRC §§511-514',
  },
  {
    id: 'tcp-d10-025',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'S Corporation Taxation',
    subtopic: 'Schedule M-2 / AAA',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An S corporation with accumulated E&P from prior C corporation years must maintain the Accumulated Adjustments Account (AAA) and report it on:',
    options: [
      'Schedule K-1',
      'Schedule M-2 of Form 1120-S, which reconciles the beginning and ending AAA, Other Adjustments Account (OAA), and shareholders\' undistributed taxable income previously taxed (PTI)',
      'Schedule L',
      'Schedule M-1',
    ],
    correctAnswer: 1,
    explanation: 'Form 1120-S Schedule M-2 — Analysis of Accumulated Adjustments Account, Shareholders\' Undistributed Taxable Income Previously Taxed, Accumulated E&P, and Other Adjustments Account: AAA (Column a): tracks cumulative S corporation income minus losses, deductions, and distributions. Increased by: separately and non-separately stated income items. Decreased by: distributions, separately and non-separately stated losses and deductions, nondeductible expenses not chargeable to capital (but NOT decreased by tax-exempt income or its related expenses — those go to OAA). Can be negative. OAA — Other Adjustments Account (Column b): tracks tax-exempt income and related expenses. Increased by tax-exempt income (e.g., municipal bond interest). Decreased by: nondeductible expenses related to tax-exempt income, distributions from OAA. PTI — Previously Taxed Income (Column c): pre-1983 S corporation income that was taxed to shareholders but not distributed. Rare in modern practice. Only applies to corps that were S corps pre-1983. Accumulated E&P (Column d): E&P from C corporation years, reduced by dividends paid from E&P. S corporation operations do NOT create or add to E&P. Schedule M-2 is required for S corporations with accumulated E&P; optional but recommended for all S corporations for tracking purposes.',
    reference: 'Form 1120-S Instructions; IRC §1368(e)',
  },
];
