// TCP Depth Questions - Batch 7
// Focus: TCP-I/II/III advanced topics, cross-cutting issues
// Difficulty: balanced

import { Question } from '../../../types';

export const TCP_QUESTIONS_DEPTH_7: Question[] = [
  {
    id: 'tcp-d7-001',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Alternative Minimum Tax (AMT)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'For individual taxpayers, the AMT exemption amount for 2025 (MFJ) is approximately $137,000. Which of the following is a common AMT preference or adjustment item?',
    options: [
      'Mortgage interest on a primary residence (acquisition debt)',
      'Charitable contributions',
      'Standard deduction',
      'State and local tax (SALT) deductions — SALT is added back for AMT purposes because it is not deductible under the AMT system (one of the largest adjustment items for many taxpayers)',
    ],
    correctAnswer: 3,
    explanation: 'IRC §55-59 (AMT): Calculation: AMTI (regular taxable income + preferences/adjustments) − AMT exemption → tentative minimum tax at 26%/28% rates → AMT = excess over regular tax. Key adjustments/preferences: (1) SALT deduction: add back (largest item for many). (2) Tax-exempt interest on private activity bonds: add back. (3) Excess depreciation (MACRS vs. ADS for pre-2018 property). (4) Exercise of ISOs: bargain element is AMT preference. (5) Medical expenses: 7.5% floor applies (same as regular tax post-TCJA). NOT adjustments post-TCJA: personal exemptions (eliminated), miscellaneous itemized deductions (eliminated). AMT exemption phases out at 25% of AMTI exceeding $1,252,700 (MFJ, 2025). AMT credit (§53): AMT paid from timing items (ISO exercise, depreciation) creates a credit usable in future years against regular tax.',
    reference: 'IRC §55-59',
  },
  {
    id: 'tcp-d7-002',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'Accumulated Earnings Tax — §531',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The accumulated earnings tax (AET) under §531 is imposed on C corporations that:',
    options: [
      'Make any distributions to shareholders',
      'Have more than 100 shareholders',
      'Have earnings over $1 million',
      'Accumulate earnings and profits beyond reasonable business needs to avoid shareholder-level tax on dividends — the tax is 20% of accumulated taxable income and applies in addition to the regular corporate income tax',
    ],
    correctAnswer: 3,
    explanation: 'IRC §531-537 (AET): Tax rate: 20% (matches qualified dividend rate) on accumulated taxable income. Purpose: prevent C corps from accumulating E&P to avoid shareholder-level dividend tax. Accumulated taxable income = adjusted taxable income − dividends paid deduction − accumulated earnings credit. Accumulated earnings credit: greater of (1) $250,000 ($150,000 for personal service corps) minus accumulated E&P at prior year-end, or (2) reasonable business needs. Reasonable business needs: business expansion, debt retirement, working capital (Bardahl formula), self-insurance, specific/definite plans. NOT reasonable: stock investments for portfolio purposes, loans to shareholders, personal expenses. Burden of proof: IRS must show accumulation was beyond reasonable needs (shifts to taxpayer if §534 notice is served). Does not apply to: S corps, personal holding companies, tax-exempt organizations, passive foreign investment companies.',
    reference: 'IRC §531-537',
  },
  {
    id: 'tcp-d7-003',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Installment Sales — §453',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the installment method (§453), a seller reports gain:',
    options: [
      'Only when the final payment is received',
      'Based on the buyer\'s payment schedule regardless of actual receipt',
      'Entirely in the year of sale',
      'Proportionally as payments are received — each payment includes a return of basis, gain, and interest; the gross profit ratio determines the taxable gain portion of each installment received',
    ],
    correctAnswer: 3,
    explanation: 'IRC §453 (Installment Sales): Gross profit ratio = gross profit ÷ contract price. Each principal payment × gross profit ratio = recognized gain. Contract price = selling price − seller\'s mortgage assumed by buyer (to the extent it doesn\'t exceed basis). Interest: reported separately as ordinary income (under §483 or §1274 rules). Cannot use installment method for: (1) dealer dispositions (inventory), (2) stocks/securities traded on established markets, (3) depreciation recapture (§1245/§1250 — recognized in full in year of sale). Related party rules (§453(e)): if related buyer resells within 2 years, original seller accelerates remaining gain. Pledging installment notes: treated as payment received (§453A). Electing out: taxpayer can elect to recognize all gain in year of sale. §453A: for installment obligations > $5 million — interest charge on deferred tax.',
    reference: 'IRC §453',
  },
  {
    id: 'tcp-d7-004',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Health Savings Account (HSA)',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Contributions to a Health Savings Account (HSA) for 2025 are limited to:',
    options: [
      '$1,500 individual / $3,000 family',
      '$6,000 individual / $12,000 family',
      '$2,000 individual / $5,000 family',
      '$4,300 for self-only coverage / $8,550 for family coverage — with a $1,000 catch-up contribution for age 55+; contributions are above-the-line deductions',
    ],
    correctAnswer: 3,
    explanation: 'IRC §223 (HSA): 2025 limits: $4,300 self-only, $8,550 family. Catch-up (age 55+): additional $1,000. Must have HDHP (High-Deductible Health Plan): 2025 minimums: $1,650 self-only / $3,300 family deductible. Out-of-pocket maximums: $8,300 self-only / $16,600 family. Triple tax benefit: (1) Contributions deductible above-the-line (or pre-tax through employer). (2) Earnings grow tax-free. (3) Distributions tax-free for qualified medical expenses. Non-qualified distributions: taxable + 20% penalty (no penalty after age 65, but still taxable). No "use it or lose it": funds roll over indefinitely (unlike FSAs). Cannot contribute if enrolled in Medicare. Last-month rule: if eligible on December 1, can contribute full annual amount (but must maintain eligibility through following year\'s testing period).',
    reference: 'IRC §223',
  },
  {
    id: 'tcp-d7-005',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'Trust Classification — Simple vs. Complex',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A "simple trust" under Subchapter J is one that:',
    options: [
      'Pays all taxes at the trust level',
      'Has no beneficiaries',
      'Never terminates',
      'Is required to distribute all income currently, does NOT make charitable contributions, and does NOT distribute corpus (principal) — income is taxed to the beneficiaries, and the trust gets a distribution deduction',
    ],
    correctAnswer: 3,
    explanation: 'IRC §651-652 (Simple Trusts) vs. §661-663 (Complex Trusts): Simple trust: (1) Must distribute all fiduciary accounting income (FAI) currently, (2) No charitable contributions from trust income, (3) No distributions of corpus. Gets a $300 personal exemption. Complex trust: everything else — may accumulate income, may distribute corpus, may make charitable contributions. Gets a $100 personal exemption ($0 if required to distribute all income). Distribution deduction: the trust deducts amounts distributed (limited to DNI — distributable net income). DNI is the ceiling on: (1) the trust\'s distribution deduction, and (2) the amount taxable to beneficiaries. Tier system (complex trusts): Tier 1 (required distributions) → absorb DNI first; Tier 2 (discretionary distributions) → remaining DNI. Trust compressed tax rates: 37% bracket reached at ~$15,200 (2025) — incentive to distribute.',
    reference: 'IRC §651-652; §661-663',
  },
  {
    id: 'tcp-d7-006',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Passive Activity Loss Rules — Material Participation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under §469, a taxpayer materially participates in an activity if the taxpayer satisfies one of 7 tests. Which is the MOST commonly used test?',
    options: [
      'The taxpayer invests at least $100,000',
      'The taxpayer owns more than 50% of the entity',
      'The taxpayer delegates management to a third party',
      'The taxpayer participates in the activity for more than 500 hours during the tax year — other tests include being the only participant, 100+ hours and not less than any other individual, and significant participation activities aggregating > 500 hours',
    ],
    correctAnswer: 3,
    explanation: 'Reg. §1.469-5T — 7 Material Participation Tests: (1) > 500 hours participation during the year (most common). (2) Substantially all participation in the activity. (3) > 100 hours AND not less than any other individual. (4) Significant participation activities: 100-500 hours in each of multiple activities that aggregate > 500 hours. (5) Material participation in any 5 of the prior 10 years. (6) Personal service activity: material participation in any 3 prior years. (7) Facts and circumstances (> 100 hours + regular, continuous, substantial involvement). Passive activity = trade/business in which the taxpayer does NOT materially participate. Rental activities: generally passive regardless of participation (exception: real estate professionals — §469(c)(7)). Passive losses can only offset passive income. Suspended losses: released on full taxable disposition. Limited partners: can only use tests 1, 5, and 6.',
    reference: 'IRC §469; Reg. §1.469-5T',
  },
  {
    id: 'tcp-d7-007',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'IRA Distribution Rules',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the SECURE Act, the required minimum distribution (RMD) age for individuals turning 73 in 2025 is:',
    options: [
      '70½',
      '59½',
      '65',
      '73 — the SECURE Act of 2019 raised the age from 70½ to 72, and SECURE 2.0 raised it to 73 (effective 2023) and will raise it to 75 (effective 2033)',
    ],
    correctAnswer: 3,
    explanation: 'IRC §401(a)(9) (RMD Rules — post-SECURE 2.0): RMD beginning age: Born before 1951: 70½. Born 1951-1959: 73 (SECURE 2.0, effective 2023). Born 1960+: 75 (effective 2033). First RMD deadline: April 1 of the year following the year the individual reaches the applicable age (but then must also take the second RMD by 12/31 of that same year → potential double distribution). Penalty for missed RMD: 25% of the shortfall (reduced from 50% by SECURE 2.0). Further reduced to 10% if corrected within 2 years. RMD calculation: account balance (12/31 of prior year) ÷ life expectancy factor (Uniform Lifetime Table, or Joint and Last Survivor Table if sole beneficiary is spouse > 10 years younger). Roth IRAs: NO RMDs during owner\'s lifetime. Inherited IRAs: 10-year rule for most non-spouse beneficiaries (SECURE Act).',
    reference: 'IRC §401(a)(9); SECURE 2.0 Act',
  },
  {
    id: 'tcp-d7-008',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'Partnership — Varying Interests Rule',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When a partner\'s interest in a partnership changes during the year (e.g., a new partner is admitted), the partnership allocates income using:',
    options: [
      'Equal allocation regardless of ownership dates',
      'Only year-end percentages',
      'Only beginning-of-year percentages',
      'Either the interim closing of the books method or the proration method — the proration method assigns income based on the percentage of the year each partner held their interest; interim closing allocates based on actual results before and after the change',
    ],
    correctAnswer: 3,
    explanation: 'IRC §706(d) / Reg. §1.706-4 (Varying Interests Rule): When a partner\'s interest varies during the year: (1) Interim closing of the books: treats the partnership year as two (or more) segments. Actual income/loss for each segment is allocated to the partners based on their ownership during that segment. More precise but more complex. (2) Proration method (convention-based): assumes income is earned ratably throughout the year. Allocates based on weighted average of ownership percentages over the year. Simpler but less accurate. The partnership agreement can specify which method to use. Cash-basis items (interest, rent): generally must use proration (cannot be allocated based on interim closing, except for extraordinary items). Extraordinary items (§1.706-4(e)): capital gains/losses, §1231, unusual income — must be allocated to the date they occur regardless of the overall method chosen.',
    reference: 'IRC §706(d); Reg. §1.706-4',
  },
  {
    id: 'tcp-d7-009',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Depreciation Recapture — §1250',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under §1250, gain on the sale of depreciable real property (placed in service after 1986) is subject to unrecaptured §1250 gain taxed at:',
    options: [
      '28% collectibles rate',
      'Ordinary income rates',
      '15% capital gains rate',
      'A maximum rate of 25% — to the extent of straight-line depreciation previously allowed; additional depreciation (excess over straight-line) is rare for post-1986 property since MACRS uses straight-line for real property',
    ],
    correctAnswer: 3,
    explanation: 'IRC §1250 / §1(h)(1)(E): Unrecaptured §1250 gain: for real property (post-1986 — depreciated using straight-line under MACRS), the gain attributable to depreciation previously taken is taxed at a maximum rate of 25%. Calculation: gain on sale (total) → first, allocate gain to §1250 recapture (up to total depreciation taken) taxed at max 25% → remaining gain taxed at regular LTCG rates (0%/15%/20%). For pre-1987 property with accelerated depreciation: §1250 ordinary income recapture applies to the excess of accelerated over straight-line depreciation. §1245 recapture (personal property): ALL depreciation recaptured as ordinary income — more aggressive than §1250. Bonus depreciation/§179 amounts: create §1245 recapture on personal property. Note: §1250 does not fully recapture at ordinary rates — Congress chose the 25% compromise for real property.',
    reference: 'IRC §1250; §1(h)(1)(E)',
  },
  {
    id: 'tcp-d7-010',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Earned Income Credit (EIC)',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'The Earned Income Credit (EIC) is:',
    options: [
      'A nonrefundable credit for high-income taxpayers',
      'Available only to self-employed individuals',
      'A deduction from gross income',
      'A refundable credit for low-to-moderate income workers — the credit amount increases with earned income up to a maximum, plateaus, then phases out; the amount varies by number of qualifying children (0, 1, 2, or 3+)',
    ],
    correctAnswer: 3,
    explanation: 'IRC §32 (EIC): Refundable credit — taxpayer can receive a refund even if no tax liability. Structure: phase-in range (credit increases as earned income rises), plateau (maximum credit), phase-out range (credit decreases). 2025 approximate maximums: 0 children: ~$632. 1 child: ~$4,213. 2 children: ~$6,960. 3+ children: ~$7,830. Requirements: must have earned income (wages, self-employment). Investment income must be ≤ $11,600 (2025). Cannot file MFS (unless certain exceptions apply post-ARPA extension). Must be US citizen/resident alien for entire year. Age requirements (no children): 25-64 (expanded under ARPA but reverted). SSN required for taxpayer and qualifying children. Cannot be a qualifying child of another person. Due diligence: preparers must exercise due diligence (§6695(g)) — $560 penalty per failure.',
    reference: 'IRC §32',
  },
  {
    id: 'tcp-d7-011',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'C Corp — Personal Holding Company Tax',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The personal holding company (PHC) tax under §541 applies when:',
    options: [
      'Any corporation pays dividends',
      'A corporation has any passive income',
      'A corporation is publicly traded',
      'More than 50% of stock is owned by 5 or fewer individuals AND at least 60% of adjusted ordinary gross income is personal holding company income (dividends, interest, rents below threshold, royalties, certain personal service contracts) — the tax is 20% on undistributed PHC income',
    ],
    correctAnswer: 3,
    explanation: 'IRC §541-547 (PHC Tax): Two tests (BOTH must be met): (1) Ownership test: > 50% of outstanding stock owned (directly/constructively) by 5 or fewer individuals at any time during the last half of the tax year. (2) Income test: ≥ 60% of AOGI (adjusted ordinary gross income) is PHC income. PHC income: dividends, interest, adjusted rents (< 50% of AOGI and not enough rent to avoid PHC status after testing), royalties (with exceptions), certain personal service contract income (if 25%+ shareholder performs services AND contract names the person). Tax: 20% on undistributed PHC income (UPHCI). UPHCI = taxable income (with adjustments) − dividends paid deduction. Avoid the tax: pay dividends (including consent dividends — §565, or deficiency dividends — §547). Exempt entities: tax-exempt organizations, banks, S corps, foreign PHCs (separate rules under §551-558).',
    reference: 'IRC §541-547',
  },
  {
    id: 'tcp-d7-012',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'At-Risk Rules — §465',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under the at-risk rules (§465), a taxpayer can deduct losses from an activity only to the extent of:',
    options: [
      'The partnership\'s total debt',
      'The FMV of the taxpayer\'s investment',
      'Total investment regardless of liability type',
      'The amount the taxpayer has "at risk" — which includes cash contributed, adjusted basis of property contributed, amounts borrowed for which the taxpayer is personally liable (recourse debt), and qualified nonrecourse financing for real estate secured by the property',
    ],
    correctAnswer: 3,
    explanation: 'IRC §465 (At-Risk Rules): Amount at risk includes: (1) Cash invested, (2) Adjusted basis of contributed property, (3) Recourse borrowings (personally liable), (4) Qualified nonrecourse financing (ONLY for real estate): loans from qualified lenders (banks, government entities, related parties in certain cases) secured by real property used in the activity. NOT at risk: nonrecourse debt (except qualified nonrecourse for real estate), amounts protected against loss by guarantees/insurance/stop-loss agreements, amounts borrowed from persons with an interest in the activity (other than as a creditor). Ordering: at-risk rules apply BEFORE passive activity rules (§469) — losses must pass both gates. If at-risk amount goes below zero (e.g., debt relief): recapture of previously deducted losses (§465(e)). Suspended losses: carried forward indefinitely, deductible when at-risk amount increases.',
    reference: 'IRC §465',
  },
  {
    id: 'tcp-d7-013',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Excess Business Loss Limitation — §461(l)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under §461(l), noncorporate taxpayers cannot deduct excess business losses exceeding:',
    options: [
      'Any amount of business losses',
      '$500,000 flat limit',
      '$100,000 annually',
      '$305,000 ($610,000 MFJ) for 2025 (indexed) — excess business losses above this threshold are disallowed and treated as a net operating loss carryforward; this rule applies AFTER the passive activity loss rules',
    ],
    correctAnswer: 3,
    explanation: 'IRC §461(l) (Excess Business Loss Limitation): Applies to noncorporate taxpayers (individuals, trusts, estates). Threshold: $305,000 ($610,000 MFJ) for 2025 (indexed for inflation). Calculation: aggregate business deductions minus aggregate business income. If the net business loss exceeds the threshold: excess is disallowed and treated as an NOL carryforward (§172). Ordering: passive activity rules (§469) apply first → then at-risk rules (§465) → then §461(l). Originally enacted by TCJA (2018-2025), extended through 2028 by the Inflation Reduction Act. Interplay with QBI deduction (§199A): §461(l) reduces the loss available for QBI purposes. Business income for §461(l) includes: wages, SE income, passthrough income, capital gains from business assets. Does NOT include: investment income, portfolio income unless from a trade or business.',
    reference: 'IRC §461(l)',
  },
  {
    id: 'tcp-d7-014',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'Estate Tax — Unified Credit',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'For 2025, the federal estate tax exemption (basic exclusion amount) is approximately:',
    options: [
      '$3.5 million',
      '$5 million flat',
      '$1 million per individual',
      '$13.99 million per individual ($27.98 million for a married couple with portability) — set to revert to approximately $7 million (indexed) after 2025 when TCJA sunsets',
    ],
    correctAnswer: 3,
    explanation: 'IRC §2010 (Unified Credit / Basic Exclusion Amount): 2025: ~$13.99 million per individual (indexed). TCJA doubled the amount from ~$5.5M to ~$11.2M (2018), indexed annually. Sunset: after December 31, 2025, reverts to pre-TCJA level (~$7M indexed). Portability (§2010(c)(4)): surviving spouse can use the deceased spouse\'s unused exclusion amount (DSUE). Must file Form 706 to elect portability (even if no tax due). Tax rate: flat 40% on amounts exceeding the exclusion. Annual gift exclusion: $19,000 per donee (2025, separate from lifetime exclusion). Gift/estate system is unified: lifetime gifts above the annual exclusion reduce the available estate tax exclusion. State estate taxes: separate — several states have lower exemptions ($1M-$6.5M). Generation-skipping transfer (GST) tax: 40% with its own $13.99M exemption.',
    reference: 'IRC §2010; §2001',
  },
  {
    id: 'tcp-d7-016',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Qualified Education Expenses — §529',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Distributions from a §529 plan are tax-free when used for:',
    options: [
      'Any personal expenses',
      'Only college tuition',
      'Only expenses at in-state public schools',
      'Qualified higher education expenses (tuition, fees, books, supplies, room & board for at least half-time students, computers) AND up to $10,000 per year for K-12 tuition — plus up to $10,000 for student loan repayment (lifetime, per beneficiary)',
    ],
    correctAnswer: 3,
    explanation: 'IRC §529 (Qualified Tuition Programs): Contributions: not deductible for federal tax (but many states offer a state income tax deduction). Growth: tax-free. Distributions: tax-free for qualified education expenses. Qualified expenses: (1) Higher education: tuition, fees, books, supplies, equipment, room & board (if at least half-time enrollment — limited to the school\'s cost of attendance), computers/internet. (2) K-12 tuition: up to $10,000/year (TCJA addition). (3) Student loan repayment: up to $10,000 lifetime per beneficiary plus $10,000 for each sibling (SECURE Act). (4) Apprenticeship programs (SECURE Act). Non-qualified distributions: earnings taxed + 10% penalty. Superfunding: 5-year gift tax averaging — contribute up to 5× the annual exclusion ($95,000 in 2025) and spread the gift over 5 years. SECURE 2.0 (2024+): rollover from §529 to Roth IRA (up to $35,000 lifetime, subject to conditions).',
    reference: 'IRC §529; SECURE 2.0 §126',
  },
  {
    id: 'tcp-d7-017',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'S Corp — Reasonable Compensation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An S corporation shareholder-employee must receive reasonable compensation because:',
    options: [
      'It is an optional best practice',
      'Distributions are subject to higher tax than wages',
      'The IRS requires maximum salary with no distributions',
      'Distributions are not subject to FICA/SE tax, so paying below-market wages to maximize distributions is a common IRS audit target — wages must reflect the value of services actually performed, considering similar industries and positions',
    ],
    correctAnswer: 3,
    explanation: 'IRC §3121 / IRS guidance on S corp reasonable compensation: S corp flow-through income is NOT subject to self-employment tax (unlike partnerships/sole proprietorships). Distributions from S corps: no FICA, no SE tax. This creates an incentive to minimize wages and maximize distributions. IRS scrutiny: if compensation is unreasonably low, IRS can reclassify distributions as wages → FICA and income tax withholding apply, plus penalties and interest. Factors used to determine reasonable compensation: (1) Training and experience, (2) Duties and responsibilities, (3) Time devoted to the business, (4) Comparable salaries in similar companies, (5) Distribution history, (6) Amounts paid to non-shareholder employees for similar work, (7) Use of a compensation formula. Key cases: Watson v. Commissioner (8th Cir.), Radtke v. U.S. — courts have consistently required reasonable compensation. Rule of thumb: no specific percentage, but 100% distributions with $0 salary will be challenged.',
    reference: 'IRC §3121; Watson v. Commissioner',
  },
  {
    id: 'tcp-d7-019',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Foreign Earned Income Exclusion — §911',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under §911, a U.S. citizen living abroad may exclude from gross income foreign earned income up to:',
    options: [
      'Unlimited amount with proper documentation',
      '$200,000',
      '$50,000',
      '$130,000 (2025, indexed) — the taxpayer must meet either the bona fide residence test or the physical presence test (330 days in a 12-month period), and may also exclude or deduct a foreign housing amount',
    ],
    correctAnswer: 3,
    explanation: 'IRC §911 (Foreign Earned Income Exclusion — FEIE): 2025: ~$130,000 maximum exclusion (indexed). Qualification tests (must meet ONE): (1) Bona fide residence test: bona fide resident of a foreign country for an uninterrupted period that includes a full tax year (intent to reside, not just physical presence). (2) Physical presence test: present in a foreign country for 330 full days during any 12-month period. Covered income: earned income from personal services (wages, salaries, professional fees). NOT covered: passive income (dividends, interest, rental income, capital gains). Foreign housing exclusion/deduction: amounts paid for qualified housing expenses in excess of a base amount (~16% of the FEIE limit). Limitation: cannot use both FEIE and foreign tax credit on the same income. Election: must be affirmative (Form 2555). Revocation: cannot re-elect for 5 years without IRS approval. Still must file a U.S. return and report worldwide income.',
    reference: 'IRC §911',
  },
  {
    id: 'tcp-d7-020',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'C Corp — Earnings and Profits (E&P)',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A C corporation\'s current earnings and profits (E&P) are important because they determine:',
    options: [
      'Executive compensation limits',
      'The corporation\'s tax liability',
      'The corporation\'s net worth',
      'Whether distributions to shareholders are taxable dividends — distributions are dividends to the extent of current E&P (pro rata, regardless of timing) plus accumulated E&P; excess is return of capital, then capital gain',
    ],
    correctAnswer: 3,
    explanation: 'IRC §301/§316 (E&P and Distributions): Distribution ordering: (1) Current E&P (allocated pro rata to all distributions during the year, regardless of chronological order). (2) Accumulated E&P (chronological order — FIFO). (3) Return of capital (reduce stock basis). (4) Capital gain (after basis is reduced to zero). Current E&P calculation: start with taxable income, then adjust (add back: tax-exempt income, DRD, federal tax, excess depreciation; subtract: nondeductible expenses, federal taxes paid, excess capital losses). Accumulated E&P: running balance — increased by current E&P, decreased by distributions and accumulated losses. Deficit in current E&P: net current E&P with accumulated E&P. If both are negative: no dividend treatment. If current is positive but accumulated is negative: distribution is a dividend to the extent of current E&P. Key: E&P is an economic concept, not a tax or GAAP concept.',
    reference: 'IRC §301; §312; §316',
  },
  {
    id: 'tcp-d7-021',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Wash Sale Rule — §1091',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Under the wash sale rule, a loss on the sale of stock or securities is disallowed if:',
    options: [
      'The stock was held for less than one year',
      'The loss is less than $3,000',
      'The stock is sold at a loss more than once in a year',
      'Substantially identical stock or securities are acquired within 30 days before or after the sale — the disallowed loss is added to the basis of the replacement shares',
    ],
    correctAnswer: 3,
    explanation: 'IRC §1091 (Wash Sale Rule): A loss deduction is disallowed if the taxpayer acquires "substantially identical" stock or securities within 30 days before or 30 days after the sale (61-day window). Substantially identical: same corporation, same class. NOT substantially identical: different corporations, bonds vs. stock of the same company (generally). Effect on basis: the disallowed loss is added to the cost basis of the replacement stock. The holding period of the original stock tacks onto the replacement stock. Applies to: stocks, bonds, options/warrants on substantially identical securities, mutual fund shares of the same fund. Does NOT apply to: gains (only losses), sales at a gain, real property, commodities (though other anti-loss rules may apply). IRA purchases: buying the same stock in an IRA during the wash sale period → loss disallowed AND NOT added to IRA basis (worst outcome). Post-2025 potential change: legislation may expand wash sale rules to cryptocurrency.',
    reference: 'IRC §1091',
  },
  {
    id: 'tcp-d7-022',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Taxation',
    subtopic: 'Premium Tax Credit — §36B',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The Premium Tax Credit (PTC) under §36B is available to individuals who:',
    options: [
      'Have employer-sponsored insurance',
      'Are enrolled in Medicare',
      'Have any type of health insurance',
      'Purchase health insurance through a Health Insurance Marketplace with household income between 100% and 400% of the Federal Poverty Level — the credit reduces the cost of premiums and may be received in advance; excess advance credits must be repaid if income exceeds projections',
    ],
    correctAnswer: 3,
    explanation: 'IRC §36B (PTC): Refundable credit for purchasing qualified health plan through the Marketplace (Exchanges). Income range: generally 100%-400% of FPL (Federal Poverty Level). IRA/ARPA/IRA extension (through 2025): enhanced PTC removes the 400% FPL cliff — premium contributions capped at 8.5% of household income for all income levels above 150% FPL. Advance PTC: credit can be paid directly to the insurer monthly (reduces premium). Reconciliation on Form 8962: if advance PTC exceeded actual PTC → repay excess (subject to repayment caps if income < 400% FPL). If actual PTC exceeds advance PTC → additional refund. Not eligible if: affordable employer coverage is available (< 9.02% of household income for employee-only coverage), eligible for Medicare/Medicaid, filing MFS (with exceptions), or dependent of another taxpayer.',
    reference: 'IRC §36B; IRA §12001',
  },
  {
    id: 'tcp-d7-023',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Taxation',
    subtopic: 'Tax-Exempt Organizations — §501(c)(3)',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'To maintain §501(c)(3) tax-exempt status, an organization must NOT:',
    options: [
      'Employ paid staff',
      'Accept donations',
      'Generate any revenue',
      'Participate in political campaign activities on behalf of or in opposition to any candidate for public office — and its lobbying activities must be insubstantial; violation can result in loss of exemption and excise taxes',
    ],
    correctAnswer: 3,
    explanation: 'IRC §501(c)(3) (Charitable Exempt Organizations): Organizational test: must be organized and operated exclusively for exempt purposes (charitable, religious, educational, scientific, literary, testing for public safety, fostering amateur sports, prevention of cruelty). Operational test: no private benefit/inurement — earnings must not inure to insiders. Political activity: ABSOLUTE prohibition on campaign intervention (supporting or opposing candidates). Lobbying: must be "insubstantial" (safe harbor under §501(h) election: 5%-20% of exempt purpose expenditures based on a sliding scale). Penalties: loss of exemption, §4955 excise tax on political expenditures (10% on the organization + 2.5% on the manager). UBIT (§511-514): tax-exempt but must pay tax on unrelated business taxable income (regularly carried on trade or business not substantially related to exempt purpose). Form 990: annual information return (public disclosure required).',
    reference: 'IRC §501(c)(3); §4955',
  },
  {
    id: 'tcp-d7-024',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-property',
    topic: 'Property Transactions',
    subtopic: 'Charitable Contribution of Appreciated Property',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When a taxpayer donates long-term capital gain property to a public charity, the deduction is generally:',
    options: [
      'Not allowed for appreciated property',
      'Limited to the property\'s adjusted basis',
      'FMV with no AGI limitation',
      'Equal to the fair market value of the property, limited to 30% of AGI — compared to 60% of AGI for cash contributions; the 5-year carryforward applies to unused deductions',
    ],
    correctAnswer: 3,
    explanation: 'IRC §170 (Charitable Contributions): Long-term capital gain property to a public charity: deduction = FMV, limited to 30% of AGI. Election: can elect to deduct at basis instead → 50%/60% AGI limit. Cash to public charity: 60% of AGI (TCJA — was 50% pre-TCJA; 60% sunsets after 2025). Ordinary income property: deduction = lesser of FMV or basis (general rule). Tangible personal property: if unrelated use by the charity → basis deduction. Short-term capital gain property: basis deduction. Private foundations (non-operating): FMV property → 20% of AGI; cash → 30% of AGI. Qualified appreciated stock to private foundation: FMV deduction (10% of outstanding stock limit). Carryforward: 5 years for unused contributions. Substantiation: cash ≥ $250 → written acknowledgment; noncash > $500 → Form 8283; noncash > $5,000 → qualified appraisal. TCJA suspended: percentage limits → cash to 60%; suspended Pease limitation.',
    reference: 'IRC §170',
  },
  {
    id: 'tcp-d7-025',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-ethics',
    topic: 'Tax Research and Ethics',
    subtopic: 'Circular 230 — Written Tax Advice',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under Circular 230, a practitioner providing written tax advice must:',
    options: [
      'Only provide advice verbally to avoid documentation',
      'Guarantee a specific tax outcome',
      'Only cite IRS Publications as authority',
      'Base the advice on reasonable factual and legal assumptions, exercise reasonable diligence, and not take into account the possibility that a return will not be audited — the advice must consider all relevant facts and applicable law, not rely on unreasonable assumptions',
    ],
    correctAnswer: 3,
    explanation: 'Circular 230 §10.37 (Written Tax Advice — revised 2014): Requirements for ALL written tax advice: (1) Base on reasonable factual assumptions (have reasonable grounds to believe facts relied upon). (2) Reasonably consider all relevant facts the practitioner knows or reasonably should know. (3) Relate applicable law to the relevant facts. (4) NOT take into account the possibility that a return will NOT be audited or that an issue will NOT be raised on audit. (5) NOT take into account the possibility of settlement. (6) Exercise reasonable diligence. No de minimis exception: all written advice must meet these standards (the prior "covered opinion" vs. "other written advice" distinction was eliminated in 2014). Competence: must possess the necessary competence (§10.35). Best practices (§10.33): communicate clearly, ensure client understands the engagement, act fairly and with integrity. These requirements apply to all practitioners: CPAs, attorneys, enrolled agents, enrolled actuaries.',
    reference: '31 CFR §10.37; Circular 230',
  },
];
