// World-Class Questions Batch 22 - Exam Quality MCQs
// 25 questions across all CPA exam sections

import { Question } from '../../../types';

export const WORLD_CLASS_BATCH_22: Question[] = [
  // FAR (4 questions)
  {
    id: 'far-wc-123',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-inventory',
    topic: 'Inventory',
    subtopic: 'Net Realizable Value',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under ASC 330 (post-2017), inventory is measured at:',
    options: [
      'Replacement cost',
      'Market value always',
      'Lower of cost and net realizable value',
      'Historical cost only',
    ],
    correctAnswer: 2,
    explanation: 'ASC 330 (as amended by ASU 2015-11): inventory measured at lower of cost or NRV. NRV = estimated selling price - estimated costs to complete and sell. Simplified from previous lower of cost or market with ceiling/floor.',
    reference: 'ASC 330-10-35',
  },
  {
    id: 'far-wc-124',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-I',
    topicId: 'far-receivables',
    topic: 'Receivables',
    subtopic: 'Factoring',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A transfer of receivables qualifies as a sale if the transferor:',
    options: [
      'Guarantees collection',
      'Receives less than fair value',
      'Surrenders control under the legal isolation, transferee control, and no repurchase criteria',
      'Retains servicing rights',
    ],
    correctAnswer: 2,
    explanation: 'ASC 860 sale criteria: (1) legal isolation - transferor\'s creditors cannot reach assets, (2) transferee has right to pledge/exchange, (3) no agreement to repurchase/redeem. Otherwise, treat as secured borrowing.',
    reference: 'ASC 860-10-40',
  },
  {
    id: 'far-wc-125',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-intangibles',
    topic: 'Intangibles',
    subtopic: 'Goodwill Impairment',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under the simplified goodwill impairment test (ASU 2017-04), impairment loss equals:',
    options: [
      'Amount by which reporting unit\'s carrying value exceeds its fair value, limited to goodwill carrying amount',
      'Book value of all intangibles',
      'Historical cost minus accumulated amortization',
      'Carrying amount minus implied fair value of goodwill',
    ],
    correctAnswer: 0,
    explanation: 'One-step test: if carrying amount > fair value of reporting unit, recognize impairment equal to the excess, not to exceed goodwill carrying amount. Eliminated previous Step 2 (hypothetical purchase price allocation).',
    reference: 'ASC 350-20-35',
  },
  {
    id: 'far-wc-126',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-V',
    topicId: 'far-nfp',
    topic: 'Not-for-Profit',
    subtopic: 'Statement Requirements',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Not-for-profit entities must present which financial statements?',
    options: [
      'Only statement of activities',
      'Statement of financial position, statement of activities, statement of functional expenses, and statement of cash flows',
      'Income statement and statement of stockholders\' equity',
      'Balance sheet, income statement, and statement of cash flows only',
    ],
    correctAnswer: 1,
    explanation: 'NFP required statements: (1) Statement of financial position (balance sheet), (2) Statement of activities, (3) Statement of functional expenses (if not shown elsewhere), (4) Statement of cash flows. Terminology differs from for-profit.',
    reference: 'ASC 958-205',
  },

  // AUD (4 questions)
  {
    id: 'aud-wc-123',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-procedures',
    topic: 'Audit Procedures',
    subtopic: 'Audit Documentation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Audit documentation should be sufficient to enable:',
    options: [
      'Regulators to complete the audit',
      'Only the engagement partner to understand the work',
      'The client to prepare adjusted financial statements',
      'An experienced auditor with no connection to the audit to understand the audit',
    ],
    correctAnswer: 3,
    explanation: 'Documentation standard: experienced auditor, having no previous connection with the audit, should be able to understand nature, timing, extent of procedures performed, evidence obtained, and conclusions reached.',
    reference: 'AU-C 230.08',
  },
  {
    id: 'aud-wc-124',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-inventories',
    topic: 'Inventories',
    subtopic: 'Observation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'When inventory is material, the auditor must:',
    options: [
      'Accept management representations only',
      'Always take complete physical count',
      'Rely entirely on perpetual records',
      'Observe physical inventory counting and perform test counts',
    ],
    correctAnswer: 3,
    explanation: 'Auditor performs: observation of inventory counting, test counts, inspection of condition, documentation review. For count dates other than year-end, perform rollforward/rollback procedures. Perpetual records require additional testing.',
    reference: 'AU-C 501.05',
  },
  {
    id: 'aud-wc-125',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-II',
    topic: 'Fraud',
    subtopic: 'Fraud Triangle',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Which element of the fraud triangle is typically the most difficult for an auditor to observe directly?',
    options: [
      'Opportunity — because management can always conceal weak controls',
      'Incentive/Pressure — because personal financial pressures are private',
      'Rationalization — because it exists in the fraudster\'s mind and is rarely documented',
      'All three elements are equally difficult to observe',
    ],
    correctAnswer: 2,
    explanation: 'Rationalization (the fraudster\'s self-justification, such as \'I deserve it\' or \'I\'ll put the money back\') occurs internally and is rarely documented or communicated. Incentive/pressure can often be identified through financial analysis and personnel records. Opportunity can be assessed through controls evaluation. Rationalization is typically inferred from known attitudes or ethical culture, making it the hardest to directly observe.',
    reference: 'AU-C 240.A1',
  },
  {
    id: 'aud-wc-126',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-attest',
    topic: 'Attestation',
    subtopic: 'Compliance Attestation',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An examination of compliance with laws and regulations results in:',
    options: [
      'A review report with limited assurance',
      'An agreed-upon procedures report',
      'A guarantee of no violations',
      'An opinion on whether the entity complied in all material respects',
    ],
    correctAnswer: 3,
    explanation: 'Compliance examination: opinion that entity complied in all material respects with specified requirements. Based on sufficient evidence obtained through procedures. Higher level assurance than review (limited assurance).',
    reference: 'AT-C Section 315',
  },

  // REG (4 questions)
  {
    id: 'reg-wc-123',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-II',
    topicId: 'reg-individual',
    topic: 'Individual Taxation',
    subtopic: 'Self-Employment Tax',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Self-employment tax applies to net self-employment income exceeding:',
    options: [
      '$400',
      '$1,000',
      '$10,000',
      '$500',
    ],
    correctAnswer: 0,
    explanation: 'SE tax due if net SE income ≥ $400. Rate: 15.3% (12.4% Social Security + 2.9% Medicare). SS wage base limits apply. Additional 0.9% Medicare on earnings over $200K/$250K. 50% of SE tax deductible above-the-line.',
    reference: 'IRC Section 1402',
  },
  {
    id: 'reg-wc-124',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    topicId: 'reg-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Hot Assets',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Section 751 "hot assets" include:',
    options: [
      'Unrealized receivables and inventory items',
      'Capital assets held over 1 year',
      'Real property used in business',
      'Cash and marketable securities',
    ],
    correctAnswer: 0,
    explanation: 'Section 751: "hot assets" = unrealized receivables (including potential 1245/1250 recapture) + inventory. Sale of partnership interest triggers ordinary income to extent attributable to hot assets. Prevents conversion of ordinary to capital gain.',
    reference: 'IRC Section 751',
  },
  {
    id: 'reg-wc-125',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-I',
    topicId: 'reg-business-law',
    topic: 'Business Law',
    subtopic: 'Insurance',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The concept of insurable interest requires:',
    options: [
      'Pre-approval from government agencies',
      'Only ownership of the insured property',
      'That the insured suffer financial loss if the insured event occurs',
      'That insurance be purchased for speculative purposes',
    ],
    correctAnswer: 2,
    explanation: 'Insurable interest: policyholder must suffer financial loss if insured event occurs. For property: at time of loss. For life insurance: at time policy issued. Prevents speculation and moral hazard.',
    reference: 'Insurance Law',
  },
  {
    id: 'reg-wc-126',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-property',
    topic: 'Property Transactions',
    subtopic: 'Hobby Losses',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Hobby loss rules limit deductions to:',
    options: [
      'Standard deduction amount',
      'Only depreciation',
      'The amount of hobby income (under TCJA, no deductions for 2018-2025)',
      'Unlimited losses against other income',
    ],
    correctAnswer: 2,
    explanation: 'Section 183: activity not for profit deductions limited to income. Under TCJA (2018-2025), hobby deductions are miscellaneous itemized deductions, which are suspended - effectively no deduction allowed against hobby income.',
    reference: 'IRC Section 183',
  },

  // BAR (5 questions)
  {
    id: 'bar-wc-142',
    courseId: 'cpa',
    section: 'BAR',
    blueprintArea: 'BAR-I',
    topic: 'Financial Statement Analysis',
    subtopic: 'Trend Analysis',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'In horizontal analysis, each line item is expressed as a percentage of which figure?',
    options: [
      'Total revenue for the same period',
      'Total assets for the same period',
      'The same line item from a base period',
      'Net income for the same period',
    ],
    correctAnswer: 2,
    explanation: 'Horizontal analysis (also called trend analysis) compares each line item across time periods by expressing current-period amounts as a percentage of the corresponding base-period amount. This differs from vertical analysis, which expresses items as a percentage of a base amount within the same period (e.g., total assets or total revenue).',
    reference: 'Financial Statement Analysis',
  },
  {
    id: 'bar-wc-143',
    courseId: 'cpa',
    section: 'BAR',
    blueprintArea: 'BAR-II',
    topic: 'Valuation',
    subtopic: 'Enterprise Value',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A company has a market capitalization of $50 million, total debt of $15 million, preferred stock of $5 million, minority interest of $2 million, and cash of $8 million. What is its enterprise value?',
    options: [
      '$72 million',
      '$64 million',
      '$80 million',
      '$58 million',
    ],
    correctAnswer: 1,
    explanation: 'Enterprise Value = Market Cap + Total Debt + Preferred Stock + Minority Interest − Cash = $50M + $15M + $5M + $2M − $8M = $64 million. EV represents the total value to acquire all claims on the business. Cash is subtracted because an acquirer would effectively receive the target\'s cash, reducing the net cost of acquisition.',
    reference: 'Enterprise Valuation',
  },
  {
    id: 'bar-wc-144',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-III',
    topicId: 'bar-technical',
    topic: 'Technical Accounting',
    subtopic: 'Revenue Variable Consideration',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Variable consideration in revenue recognition is estimated using:',
    options: [
      'Historical cost only',
      'Expected value or most likely amount method',
      'Fair market value',
      'Nominal amount'
    ],
    correctAnswer: 1,
    explanation: 'ASC 606: estimate variable consideration using: (1) Expected value - probability-weighted amounts, or (2) Most likely amount - single most likely outcome. Choose method most predictive. Constrained to avoid significant reversal.',
    reference: 'ASC 606-10-32',
  },
  {
    id: 'bar-wc-145',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-III',
    topicId: 'bar-cost',
    topic: 'Cost Accounting',
    subtopic: 'Process Costing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Process costing differs from job costing in that:',
    options: [
      'Costs are accumulated by department or process for homogeneous products',
      'Direct materials are not tracked',
      'Costs are accumulated for individual jobs',
      'Overhead is not allocated',
    ],
    correctAnswer: 0,
    explanation: 'Process costing: continuous production of homogeneous units, costs accumulated by department/process, cost per unit = total costs ÷ equivalent units. Job costing: unique products, costs traced to specific jobs.',
    reference: 'Costing Methods',
  },
  {
    id: 'bar-wc-146',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-analysis',
    topic: 'Financial Statement Analysis',
    subtopic: 'Limitations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A key limitation of financial statement analysis is:',
    options: [
      'Different accounting policies can affect comparability',
      'All companies use identical methods',
      'Too much information is provided',
      'Ratios are always accurate',
    ],
    correctAnswer: 0,
    explanation: 'Limitations: different accounting policies/estimates, historical cost basis, management discretion, industry differences, off-balance-sheet items, one-time items, inflation effects. Context and adjustments needed for meaningful analysis.',
    reference: 'Ratio Analysis Limitations',
  },

  // ISC (4 questions)
  {
    id: 'isc-wc-123',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-governance',
    topic: 'IT Governance',
    subtopic: 'Risk Assessment',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Qualitative risk assessment differs from quantitative in that it:',
    options: [
      'Is always more accurate',
      'Requires specialized software',
      'Uses descriptive categories (high, medium, low) rather than numerical values',
      'Uses precise dollar amounts for all risks',
    ],
    correctAnswer: 2,
    explanation: 'Qualitative: relative ratings (H/M/L) based on judgment. Faster, useful when data scarce. Quantitative: numerical values ($, ALE = SLE × ARO). More precise but requires historical data and expertise.',
    reference: 'Risk Assessment',
  },
  {
    id: 'isc-wc-124',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-II',
    topicId: 'isc-security',
    topic: 'Security Controls',
    subtopic: 'SIEM',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Security Information and Event Management (SIEM) systems provide:',
    options: [
      'Automatic firewall configuration',
      'Employee training modules',
      'Real-time monitoring, log aggregation, correlation, and alerting',
      'Physical access control only',
    ],
    correctAnswer: 2,
    explanation: 'SIEM: aggregates logs from multiple sources, correlates events, detects patterns indicating threats, generates alerts, supports forensics. Central platform for security monitoring and incident response.',
    reference: 'Security Operations',
  },
  {
    id: 'isc-wc-125',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-III',
    topicId: 'isc-systems',
    topic: 'Information Systems',
    subtopic: 'Containerization',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Containers differ from virtual machines in that containers:',
    options: [
      'Are less secure than VMs',
      'Cannot run in the cloud',
      'Share the host OS kernel and are more lightweight',
      'Require more resources than VMs',
    ],
    correctAnswer: 2,
    explanation: 'Containers: share host OS kernel, lightweight, fast startup, portable. VMs: include full guest OS, heavier, better isolation. Docker is common container platform. Containers revolutionized microservices deployment.',
    reference: 'Virtualization',
  },
  {
    id: 'isc-wc-126',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-III',
    topicId: 'isc-audit',
    topic: 'IT Audit',
    subtopic: 'Input Controls',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A check digit verification is an example of:',
    options: [
      'Physical control',
      'Input validation control',
      'Processing control',
      'Output control',
    ],
    correctAnswer: 1,
    explanation: 'Check digit: mathematical digit added to a code that validates data entry accuracy. Examples: UPC codes, credit card numbers (Luhn algorithm). Detects transposition and transcription errors at input. Input validation control.',
    reference: 'Application Controls',
  },

  // TCP (4 questions)
  {
    id: 'tcp-wc-123',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Tax Compliance',
    subtopic: 'Moving Expenses',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'For tax years 2018-2025, moving expense deductions are:',
    options: [
      'Available to all taxpayers meeting distance and time tests',
      'A below-the-line itemized deduction',
      'Deductible without any restrictions',
      'Limited to members of the Armed Forces on active duty',
    ],
    correctAnswer: 3,
    explanation: 'TCJA suspended moving expense deduction (2018-2025) except for active duty military members. Previously available if move related to job, met 50-mile and time tests. Military exception remains above-the-line.',
    reference: 'IRC Section 217',
  },
  {
    id: 'tcp-wc-124',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Tax Compliance',
    subtopic: 'C Corp vs S Corp',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A key disadvantage of C corporation status compared to S corporation is:',
    options: [
      'Limited liability protection',
      'Inability to have employees',
      'Requirement to distribute all earnings',
      'Double taxation of corporate earnings',
    ],
    correctAnswer: 3,
    explanation: 'C corp: taxed at corporate level (21%), then shareholders taxed on dividends = double taxation. S corp: pass-through (no entity-level tax). But C corp offers more flexibility in ownership, classes of stock, fringe benefits.',
    reference: 'Entity Selection',
  },
  {
    id: 'tcp-wc-125',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-planning',
    topic: 'Tax Planning',
    subtopic: 'Roth Conversions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'When converting a traditional IRA to Roth IRA:',
    options: [
      'Only the earnings portion is taxed',
      'No taxes are ever due',
      'Capital gains rates apply',
      'The converted amount is taxable as ordinary income in the year of conversion',
    ],
    correctAnswer: 3,
    explanation: 'Roth conversion: converted amount (less any after-tax basis) is ordinary income in conversion year. No 10% penalty regardless of age. Future qualified distributions tax-free. Strategic in low-income years.',
    reference: 'IRC Section 408A',
  },
  {
    id: 'tcp-wc-126',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-representation',
    topic: 'Tax Representation',
    subtopic: 'Accuracy-Related Penalties',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The accuracy-related penalty under IRC Section 6662 is:',
    options: [
      '75% of the underpayment',
      '50% of the underpayment',
      '10% of the underpayment',
      '20% of the underpayment due to negligence or substantial understatement',
    ],
    correctAnswer: 3,
    explanation: 'Section 6662: 20% penalty for negligence, substantial understatement (greater of $5,000 or 10% of tax), substantial valuation misstatement, etc. Defense: reasonable cause and good faith. Can stack with fraud penalty in egregious cases.',
    reference: 'IRC Section 6662',
  },
];
