// World-Class Questions Batch 32 - Exam Quality MCQs
// 25 questions across all CPA exam sections

import { Question } from '../../../types';

export const WORLD_CLASS_BATCH_32: Question[] = [
  // FAR (4 questions)
  {
    id: 'far-wc-163',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-II',
    topicId: 'far-revenue',
    topic: 'Revenue Recognition',
    subtopic: 'Principal vs Agent',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An entity is acting as a principal (vs agent) if it:',
    options: [
      'Controls the good or service before transfer to customer',
      'Always earns a commission',
      'Has no pricing discretion',
      'Never takes inventory risk',
    ],
    correctAnswer: 0,
    explanation: 'ASC 606 principal indicators: controls good/service before transfer (primary responsibility, inventory risk, pricing discretion). Principal: gross revenue. Agent: net (commission only). Control assessment key.',
    reference: 'ASC 606-10-55-36',
  },
  {
    id: 'far-wc-164',
    courseId: 'cpa',
    section: 'FAR',
    blueprintArea: 'FAR-I',
    topic: 'Accounting Changes',
    subtopic: 'Change in Estimate Prospectively',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Nexus Corp. originally estimated its warranty obligation at 2% of sales. In the current year, based on actual experience, it revised the estimate to 3% of sales. The current year\'s sales are $8 million. Under ASC 250, what is the warranty expense for the current year?',
    options: [
      '$160,000',
      '$240,000',
      '$80,000',
      '$320,000',
    ],
    correctAnswer: 1,
    explanation: 'A change in the estimated warranty rate from 2% to 3% is a change in accounting estimate under ASC 250-10-45. Changes in estimates are applied prospectively. Current year warranty expense = 3% × $8,000,000 = $240,000. There is no retroactive adjustment to prior years\' warranty expense. The new estimate simply applies to the current and future periods. Prior period financial statements are not restated.',
    reference: 'ASC 250-10-45',
  },
  {
    id: 'far-wc-165',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-III',
    topicId: 'far-discontinued',
    topic: 'Discontinued Operations',
    subtopic: 'Held for Sale Criteria',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A component is classified as held for sale when:',
    options: [
      'Board approval received',
      'Criteria met: committed plan, available for sale, actively marketed, probable sale within one year, unlikely plan changes',
      'A buyer is identified',
      'Management considers selling',
    ],
    correctAnswer: 1,
    explanation: 'ASC 205-20 held for sale: (1) management commits to plan, (2) available for immediate sale, (3) active marketing at reasonable price, (4) sale probable within 1 year, (5) unlikely significant changes or withdrawal.',
    reference: 'ASC 205-20-45',
  },
  {
    id: 'far-wc-166',
    section: 'FAR',
    courseId: 'cpa',
    blueprintArea: 'FAR-IV',
    topicId: 'far-government',
    topic: 'Government Accounting',
    subtopic: 'Encumbrances',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Encumbrances in governmental accounting represent:',
    options: [
      'Revenue accruals',
      'Commitments for goods/services ordered but not yet received',
      'Cash disbursements',
      'Actual expenditures',
    ],
    correctAnswer: 1,
    explanation: 'Encumbrances: budgetary control mechanism for outstanding commitments (POs, contracts). Not GAAP expenditures but track budget usage. Reversed when goods/services received and actual expenditure recorded. Fund balance disclosure.',
    reference: 'GASB Encumbrances',
  },

  // AUD (4 questions)
  {
    id: 'aud-wc-163',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-IV',
    topicId: 'aud-analytical',
    topic: 'Analytical Procedures',
    subtopic: 'Substantive Analytics',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'For substantive analytical procedures to be effective, the auditor needs:',
    options: [
      'Management estimates only',
      'Only industry benchmarks',
      'Any trend data',
      'Reliable data, precise expectation, plausible relationship, and low threshold for investigation',
    ],
    correctAnswer: 3,
    explanation: 'Substantive analytics requirements: reliable underlying data, plausible/predictable relationship, sufficiently precise expectation, appropriate investigation threshold. More effective when relationship more predictable.',
    reference: 'AU-C 520.05',
  },
  {
    id: 'aud-wc-164',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-II',
    topicId: 'aud-it',
    topic: 'IT Considerations',
    subtopic: 'Application Controls',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Application controls include:',
    options: [
      'Only network security',
      'General IT policies only',
      'Only physical access controls',
      'Input, processing, and output controls within specific applications',
    ],
    correctAnswer: 3,
    explanation: 'Application controls: edit checks (input validation), processing controls (calculations, posting), output controls (reconciliations, distribution). Automated within apps. Depend on ITGCs. Can be preventive or detective.',
    reference: 'Application Controls',
  },
  {
    id: 'aud-wc-165',
    courseId: 'cpa',
    section: 'AUD',
    blueprintArea: 'AUD-IV',
    topic: 'Audit Reports',
    subtopic: 'Qualified Opinion',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A client restricts the auditor from confirming a material accounts receivable balance representing 35% of total receivables. Alternative procedures are insufficient to obtain adequate evidence. What opinion should the auditor issue?',
    options: [
    'Unqualified opinion with an other-matter paragraph',
    'Qualified opinion or disclaimer of opinion, depending on pervasiveness',
    'Adverse opinion because receivables are misstated',
    'Unqualified opinion because alternative procedures were attempted',
    ],
    correctAnswer: 1,
    explanation: 'A client-imposed scope limitation requires the auditor to consider whether to qualify the opinion or disclaim. If the potential effect is material but not pervasive, a qualified opinion is appropriate. If the restricted area is so significant that insufficient evidence undermines the ability to form an opinion on the financial statements as a whole, a disclaimer is required. With 35% of receivables unconfirmed and alternatives insufficient, a disclaimer may be warranted.',
    reference: 'AU-C 705.08',
  },
  {
    id: 'aud-wc-166',
    section: 'AUD',
    courseId: 'cpa',
    blueprintArea: 'AUD-III',
    topicId: 'aud-evidence',
    topic: 'Audit Evidence',
    subtopic: 'Management Representations',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Written management representations:',
    options: [
      'Are optional',
      'Replace other audit evidence',
      'Are obtained verbally only',
      'Are required but cannot be sole source of evidence for significant matters',
    ],
    correctAnswer: 3,
    explanation: 'Written reps: required, dated as of report date, signed by CEO/CFO. Can\'t be sole evidence for matters capable of independent verification. Refusal/limitation = scope limitation (qualified or disclaimer).',
    reference: 'AU-C 580.10',
  },

  // REG (4 questions)
  {
    id: 'reg-wc-163',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-III',
    topicId: 'reg-partnership',
    topic: 'Partnership Taxation',
    subtopic: 'Tax Basis Capital Accounts',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Tax basis capital accounts report:',
    options: [
      'Fair market value',
      'Section 704(b) book capital',
      'Partner\'s share of partnership assets and liabilities using tax basis, not GAAP',
      'Book capital per GAAP',
    ],
    correctAnswer: 2,
    explanation: 'Tax basis capital: differs from 704(b) book and GAAP. Schedule K-1 reports tax basis capital. Differences arise from: Section 704(c) allocations, timing differences, different basis adjustments. Required reporting on K-1.',
    reference: 'Schedule K-1',
  },
  {
    id: 'reg-wc-164',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-II',
    topicId: 'reg-individual',
    topic: 'Individual Taxation',
    subtopic: 'Dependent Care Credit',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The dependent care credit is a:',
    options: [
      'Deduction from AGI',
      'Fully refundable credit',
      'Nonrefundable credit based on qualifying expenses, income percentage, and employment requirement',
      'Deduction from gross income',
    ],
    correctAnswer: 2,
    explanation: 'Dependent care credit: nonrefundable (was refundable in 2021), expenses up to $3K (1 dependent) or $6K (2+) × 20-35% based on AGI. Both spouses must work (or be students/disabled). For children <13 or disabled dependents.',
    reference: 'IRC Section 21',
  },
  {
    id: 'reg-wc-165',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-I',
    topicId: 'reg-professionalethics',
    topic: 'Professional Responsibility',
    subtopic: 'Tax Return Positions',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'A tax return position must have at least:',
    options: [
      'IRS advance approval',
      'Realistic possibility of success on merits (one in three) or substantial authority for disclosed positions',
      '100% certainty',
      'Any legal support',
    ],
    correctAnswer: 1,
    explanation: 'Standards: realistic possibility (≈1/3 chance) standard, or substantial authority for positions. Disclosure lowers standard to reasonable basis. Frivolous positions prohibited. Circular 230 and AICPA standards apply.',
    reference: 'Circular 230, §10.34',
  },
  {
    id: 'reg-wc-166',
    section: 'REG',
    courseId: 'cpa',
    blueprintArea: 'REG-IV',
    topicId: 'reg-property',
    topic: 'Property Transactions',
    subtopic: 'Involuntary Conversion',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Gain from involuntary conversion may be deferred when:',
    options: [
      'Similar or related use property is acquired within the replacement period (2 years, 3 for condemnation)',
      'Loss is realized',
      'Cash is received',
      'Any property is purchased',
    ],
    correctAnswer: 0,
    explanation: 'Section 1033: defer gain if reinvest in similar/related property within replacement period. 2 years (3 years for condemned real property for business/investment). Must elect. Basis reduction = deferred gain.',
    reference: 'IRC Section 1033',
  },

  // BAR (5 questions)
  {
    id: 'bar-wc-192',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-analysis',
    topic: 'Financial Statement Analysis',
    subtopic: 'DuPont Analysis Extended',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The extended DuPont formula decomposes ROE into:',
    options: [
      'Profit margin × asset turnover × equity multiplier (financial leverage)',
      'Only asset turnover',
      'Only profit margin',
      'Only leverage',
    ],
    correctAnswer: 0,
    explanation: 'Extended DuPont: ROE = (NI/Sales) × (Sales/Assets) × (Assets/Equity). Three drivers: operating efficiency (margin), asset efficiency (turnover), financial leverage. Diagnose ROE changes by component.',
    reference: 'DuPont Analysis',
  },
  {
    id: 'bar-wc-193',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-II',
    topicId: 'bar-valuation',
    topic: 'Valuation',
    subtopic: 'Dividend Discount Model',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'The Gordon Growth Model calculates equity value as:',
    options: [
      'Next year dividend / (required return - growth rate)',
      'Book value × multiple',
      'Dividends × P/E ratio',
      'EBITDA / WACC',
    ],
    correctAnswer: 0,
    explanation: 'Gordon Growth: P = D1 / (r - g). D1 = next expected dividend. r = required return. g = constant growth rate. Assumes perpetual growth. r > g required. Best for stable, dividend-paying firms.',
    reference: 'Dividend Discount Model',
  },
  {
    id: 'bar-wc-194',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-III',
    topicId: 'bar-technical',
    topic: 'Technical Accounting',
    subtopic: 'Noncontrolling Interest',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Noncontrolling interest in consolidated financial statements is:',
    options: [
      'Excluded entirely',
      'Reported in equity, separate from parent\'s equity, with attribution of net income',
      'Reported as a liability',
      'Combined with parent equity',
    ],
    correctAnswer: 1,
    explanation: 'NCI: portion of equity/earnings not attributable to parent. Report in equity section, separately. Attribute consolidated NI between parent and NCI. NCI measured at FV or proportionate share at acquisition.',
    reference: 'ASC 810-10-45',
  },
  {
    id: 'bar-wc-195',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-III',
    topicId: 'bar-cost',
    topic: 'Cost Accounting',
    subtopic: 'Absorption vs Variable Costing',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Under absorption costing, fixed manufacturing overhead is:',
    options: [
      'Expensed as incurred',
      'Never recorded',
      'Included in product cost and inventoried until sold',
      'Treated as selling expense',
    ],
    correctAnswer: 2,
    explanation: 'Absorption: fixed MOH ∈ product cost (required for GAAP). Variable: fixed MOH = period expense. When inventory increases, absorption NI > variable NI (fixed MOH stays in inventory). Required for external reporting.',
    reference: 'Costing Methods',
  },
  {
    id: 'bar-wc-196',
    section: 'BAR',
    courseId: 'cpa',
    blueprintArea: 'BAR-I',
    topicId: 'bar-analysis',
    topic: 'Financial Statement Analysis',
    subtopic: 'Cash Flow Quality',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'High-quality cash flows are characterized by:',
    options: [
      'Heavy reliance on financing',
      'Large one-time gains',
      'Sustainable operating cash flows exceeding net income with minimal non-cash adjustments',
      'Decreasing operating cash',
    ],
    correctAnswer: 2,
    explanation: 'Quality CFO: exceeds net income (accruals quality), sustainable sources (core operations), minimal unusual items, consistent with earnings, positive FCF. Analyze: CFO/NI ratio, trend, composition.',
    reference: 'Cash Flow Analysis',
  },

  // ISC (4 questions)
  {
    id: 'isc-wc-163',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-I',
    topicId: 'isc-governance',
    topic: 'IT Governance',
    subtopic: 'IT Steering Committee',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'An IT steering committee should include:',
    options: [
      'Only auditors',
      'Only external consultants',
      'Senior business executives and IT leadership for strategic IT decision-making',
      'Only IT staff',
    ],
    correctAnswer: 2,
    explanation: 'IT steering committee: cross-functional senior leadership. Sets IT strategy, prioritizes investments, monitors performance. Ensures business-IT alignment. Reports to board or executive team. Governance mechanism.',
    reference: 'IT Governance',
  },
  {
    id: 'isc-wc-164',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-II',
    topicId: 'isc-security',
    topic: 'Security Controls',
    subtopic: 'Intrusion Prevention',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'An Intrusion Prevention System (IPS) differs from IDS in that it:',
    options: [
      'Only monitors traffic',
      'Actively blocks detected threats rather than just alerting',
      'Is purely passive',
      'Only logs events',
    ],
    correctAnswer: 1,
    explanation: 'IPS: active blocking (in-line, can drop packets). IDS: passive detection (alerts only). Both use signature and anomaly detection. IPS risk: blocking legitimate traffic. Deploy based on risk tolerance.',
    reference: 'Network Security',
  },
  {
    id: 'isc-wc-165',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-III',
    topicId: 'isc-systems',
    topic: 'Information Systems',
    subtopic: 'Blockchain',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Blockchain technology provides:',
    options: [
      'Distributed, immutable ledger with cryptographic verification and consensus mechanisms',
      'Single point of failure',
      'Easy modification of records',
      'Centralized control',
    ],
    correctAnswer: 0,
    explanation: 'Blockchain: distributed ledger, cryptographic linking (hash chains), consensus for validation, immutability (hard to alter). Use cases: cryptocurrency, supply chain, smart contracts. Not suitable for all applications.',
    reference: 'Blockchain Technology',
  },
  {
    id: 'isc-wc-166',
    section: 'ISC',
    courseId: 'cpa',
    blueprintArea: 'ISC-III',
    topicId: 'isc-audit',
    topic: 'IT Audit',
    subtopic: 'Access Review',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Periodic user access reviews should:',
    options: [
      'Verify continued appropriateness of access rights, identify terminated users, and address segregation violations',
      'Only review administrator accounts',
      'Occur after incidents only',
      'Only check new users',
    ],
    correctAnswer: 0,
    explanation: 'Access review: compare access to job requirements, identify orphan accounts (terminated employees), segregation of duties conflicts, excessive privileges, admin account justification. Quarterly or semi-annual. Manager attestation.',
    reference: 'Access Control Audit',
  },

  // TCP (4 questions)
  {
    id: 'tcp-wc-163',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-II',
    topicId: 'tcp-entity',
    topic: 'Entity Tax Compliance',
    subtopic: 'Check-the-Box Regulations',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Under check-the-box regulations, an eligible entity may elect to be taxed as:',
    options: [
      'A nonprofit',
      'Only its legal form',
      'A trust only',
      'A partnership or disregarded entity (default) or as a corporation (by election)',
    ],
    correctAnswer: 3,
    explanation: 'Check-the-box: eligible entities (not per se corporations) choose classification. Default: single member = disregarded, multiple = partnership. Elect corporation by Form 8832. Applies to domestic and foreign entities.',
    reference: 'Reg. Section 301.7701',
  },
  {
    id: 'tcp-wc-164',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-I',
    topicId: 'tcp-individual',
    topic: 'Individual Tax Compliance',
    subtopic: 'Social Security Taxation',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Social Security benefits are taxable when:',
    options: [
      'Only for high earners',
      'Never taxable',
      'Always 100% taxable',
      'Provisional income exceeds thresholds, with up to 85% potentially taxable',
    ],
    correctAnswer: 3,
    explanation: 'SS taxation: provisional income = AGI + tax-exempt interest + 50% SS benefits. Thresholds trigger 50% or 85% taxation (never 100%). Base amounts vary by filing status. Many low-income retirees pay no tax on SS.',
    reference: 'IRC Section 86',
  },
  {
    id: 'tcp-wc-165',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-III',
    topicId: 'tcp-planning',
    topic: 'Tax Planning',
    subtopic: 'Loss Harvesting',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Tax-loss harvesting involves:',
    options: [
      'Never selling losers',
      'Waiting for recovery',
      'Selling only winners',
      'Selling investments at a loss to offset gains, then reinvesting in non-identical securities',
    ],
    correctAnswer: 3,
    explanation: 'Loss harvesting: realize losses to offset gains (+ $3K ordinary income). Avoid wash sale (can\'t buy substantially identical within 30 days). Reinvest in similar but not identical. Year-end strategy.',
    reference: 'Tax Planning',
  },
  {
    id: 'tcp-wc-166',
    section: 'TCP',
    courseId: 'cpa',
    blueprintArea: 'TCP-IV',
    topicId: 'tcp-representation',
    topic: 'Tax Representation',
    subtopic: 'Taxpayer Bill of Rights',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'The Taxpayer Bill of Rights includes the right to:',
    options: [
      'Unlimited time to file',
      'No audit',
      'Ignore IRS notices',
      'Be informed, quality service, privacy, confidentiality, retain representation, and appeal',
    ],
    correctAnswer: 3,
    explanation: 'Taxpayer rights: be informed, quality service, pay no more than correct amount, challenge IRS position, appeal, privacy, confidentiality, representation, fair/just tax system, a final decision. Codified in IRC Section 7803.',
    reference: 'IRC Section 7803',
  },
];
