/**
 * SEO Automation Service — Technical SEO monitoring and optimization
 * 
 * Handles:
 * - Dynamic sitemap generation from route registry + content database
 * - Internal link graph analysis (ensures every page has 3+ internal links)
 * - Structured data (JSON-LD) validation
 * - Index coverage monitoring
 * - Core Web Vitals tracking
 * - Broken link detection
 * 
 * Runs via Cloud Functions (scheduled) and admin dashboard (on-demand).
 */

import type { CourseId } from '../../types/course';
import type { GrowthActionItem } from '../../types/growth';

// ============================================================================
// Sitemap Generation
// ============================================================================

/** Route entry for sitemap generation */
export interface SitemapEntry {
  loc: string;                    // full URL
  lastmod: string;                // 'YYYY-MM-DD'
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: number;               // 0.0 - 1.0
}

/** All static routes that should be in the sitemap */
const STATIC_ROUTES: SitemapEntry[] = [
  // Homepage
  { loc: 'https://voraprep.com/', lastmod: '', changefreq: 'weekly', priority: 1.0 },

  // Exam landing pages
  { loc: 'https://voraprep.com/cpa', lastmod: '', changefreq: 'weekly', priority: 0.9 },
  { loc: 'https://voraprep.com/ea-prep', lastmod: '', changefreq: 'weekly', priority: 0.9 },
  { loc: 'https://voraprep.com/cma', lastmod: '', changefreq: 'weekly', priority: 0.9 },
  { loc: 'https://voraprep.com/cia', lastmod: '', changefreq: 'weekly', priority: 0.9 },
  { loc: 'https://voraprep.com/cfp', lastmod: '', changefreq: 'weekly', priority: 0.9 },
  { loc: 'https://voraprep.com/cisa', lastmod: '', changefreq: 'weekly', priority: 0.9 },

  // Exam info pages
  { loc: 'https://voraprep.com/cpa/info', lastmod: '', changefreq: 'monthly', priority: 0.7 },
  { loc: 'https://voraprep.com/cma/info', lastmod: '', changefreq: 'monthly', priority: 0.7 },
  { loc: 'https://voraprep.com/cia/info', lastmod: '', changefreq: 'monthly', priority: 0.7 },
  { loc: 'https://voraprep.com/cfp/info', lastmod: '', changefreq: 'monthly', priority: 0.7 },
  { loc: 'https://voraprep.com/ea/info', lastmod: '', changefreq: 'monthly', priority: 0.7 },
  { loc: 'https://voraprep.com/cisa/info', lastmod: '', changefreq: 'monthly', priority: 0.7 },

  // Auth & conversion pages
  { loc: 'https://voraprep.com/register', lastmod: '', changefreq: 'monthly', priority: 0.8 },
  { loc: 'https://voraprep.com/login', lastmod: '', changefreq: 'monthly', priority: 0.6 },

  // Utility pages
  { loc: 'https://voraprep.com/about', lastmod: '', changefreq: 'monthly', priority: 0.6 },
  { loc: 'https://voraprep.com/faq', lastmod: '', changefreq: 'monthly', priority: 0.6 },
  { loc: 'https://voraprep.com/compare', lastmod: '', changefreq: 'monthly', priority: 0.7 },
  { loc: 'https://voraprep.com/terms', lastmod: '', changefreq: 'yearly', priority: 0.3 },
  { loc: 'https://voraprep.com/privacy', lastmod: '', changefreq: 'yearly', priority: 0.3 },
  { loc: 'https://voraprep.com/help', lastmod: '', changefreq: 'monthly', priority: 0.5 },
  { loc: 'https://voraprep.com/pass-guarantee', lastmod: '', changefreq: 'monthly', priority: 0.6 },

  // Blog index
  { loc: 'https://voraprep.com/blog', lastmod: '', changefreq: 'weekly', priority: 0.8 },
];

/**
 * Generate a complete sitemap XML from static routes + published articles.
 * Called by Cloud Function or build script.
 */
export function generateSitemapXML(
  publishedArticleSlugs: string[] = [],
  customLastmod?: string,
): string {
  const today = customLastmod || new Date().toISOString().split('T')[0];

  // Combine static routes with article routes
  const allEntries: SitemapEntry[] = [
    ...STATIC_ROUTES.map(r => ({ ...r, lastmod: today })),
    ...publishedArticleSlugs.map(slug => ({
      loc: `https://voraprep.com/blog/${slug}`,
      lastmod: today,
      changefreq: 'monthly' as const,
      priority: 0.7,
    })),
  ];

  const urls = allEntries
    .map(entry => `  <url>
    <loc>${entry.loc}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
}

/**
 * Generate robots.txt dynamically.
 */
export function generateRobotsTxt(sitemapUrl = 'https://voraprep.com/sitemap.xml'): string {
  return `# VoraPrep robots.txt
# https://voraprep.com
# Auto-generated by Growth Engine

User-agent: *
Allow: /
Allow: /cpa
Allow: /ea-prep
Allow: /cma
Allow: /cia
Allow: /cfp
Allow: /cisa
Allow: /cpa/info
Allow: /cma/info
Allow: /cia/info
Allow: /cfp/info
Allow: /ea/info
Allow: /cisa/info
Allow: /login
Allow: /register
Allow: /terms
Allow: /privacy
Allow: /help
Allow: /pass-guarantee
Allow: /about
Allow: /faq
Allow: /compare
Allow: /blog
Allow: /blog/*

# Disallow app routes (require authentication)
Disallow: /dashboard
Disallow: /home
Disallow: /study
Disallow: /practice
Disallow: /flashcards
Disallow: /quiz
Disallow: /exam
Disallow: /tbs
Disallow: /lessons/*
Disallow: /progress
Disallow: /achievements
Disallow: /tutor
Disallow: /ai-tutor
Disallow: /settings
Disallow: /onboarding
Disallow: /admin
Disallow: /journey
Disallow: /resources
Disallow: /community
Disallow: /you
Disallow: /learn
Disallow: /checkout-success
Disallow: /checkout-cancel

# Crawl rate
Crawl-delay: 1

# Sitemap location
Sitemap: ${sitemapUrl}
`;
}

// ============================================================================
// Internal Link Graph
// ============================================================================

export interface PageNode {
  path: string;
  title: string;
  incomingLinks: string[];       // pages linking TO this page
  outgoingLinks: string[];       // pages this page links TO
  courseId?: CourseId;
  isOrphan: boolean;             // no incoming links
  linkScore: number;             // 0-100, higher = more connected
}

/**
 * Build an internal link graph from page data.
 * Identifies orphan pages and suggests new links.
 */
export function buildLinkGraph(
  pages: { path: string; title: string; courseId?: CourseId; outgoingLinks: string[] }[],
): PageNode[] {
  const graph: Map<string, PageNode> = new Map();

  // Initialize all nodes
  for (const page of pages) {
    graph.set(page.path, {
      path: page.path,
      title: page.title,
      courseId: page.courseId,
      incomingLinks: [],
      outgoingLinks: page.outgoingLinks,
      isOrphan: true,
      linkScore: 0,
    });
  }

  // Build incoming links
  for (const page of pages) {
    for (const link of page.outgoingLinks) {
      const target = graph.get(link);
      if (target) {
        target.incomingLinks.push(page.path);
        target.isOrphan = false;
      }
    }
  }

  // Calculate link scores
  for (const node of graph.values()) {
    const incoming = node.incomingLinks.length;
    const outgoing = node.outgoingLinks.length;
    node.linkScore = Math.min(100, (incoming * 15) + (outgoing * 5));
    node.isOrphan = incoming === 0 && node.path !== '/';
  }

  return Array.from(graph.values());
}

/**
 * Suggest internal links to add for orphan pages and under-linked pages.
 */
export function suggestInternalLinks(
  graph: PageNode[],
  minIncomingLinks = 3,
): { page: string; suggestedLinksFrom: string[]; reason: string }[] {
  const suggestions: { page: string; suggestedLinksFrom: string[]; reason: string }[] = [];

  for (const node of graph) {
    if (node.incomingLinks.length < minIncomingLinks) {
      // Find pages that could link to this one (same course or related)
      const candidates = graph
        .filter(other =>
          other.path !== node.path &&
          !other.outgoingLinks.includes(node.path) &&
          (other.courseId === node.courseId || !other.courseId || !node.courseId)
        )
        .sort((a, b) => b.linkScore - a.linkScore)
        .slice(0, minIncomingLinks - node.incomingLinks.length)
        .map(c => c.path);

      if (candidates.length > 0) {
        suggestions.push({
          page: node.path,
          suggestedLinksFrom: candidates,
          reason: node.isOrphan
            ? 'Orphan page — no incoming links'
            : `Under-linked — only ${node.incomingLinks.length} incoming links (target: ${minIncomingLinks}+)`,
        });
      }
    }
  }

  return suggestions;
}

// ============================================================================
// Technical SEO Audit
// ============================================================================

export interface SEOAuditResult {
  score: number;                  // 0-100
  issues: SEOAuditIssue[];
  passedChecks: string[];
  timestamp: Date;
}

export interface SEOAuditIssue {
  severity: 'critical' | 'warning' | 'info';
  category: 'meta' | 'structure' | 'performance' | 'mobile' | 'content' | 'links';
  page?: string;
  message: string;
  recommendation: string;
}

/**
 * Run a technical SEO audit on a page.
 * Client-side version — checks what's visible in the DOM.
 */
export function auditPage(url: string): SEOAuditIssue[] {
  const issues: SEOAuditIssue[] = [];

  // Check meta title
  const title = document.title;
  if (!title) {
    issues.push({ severity: 'critical', category: 'meta', page: url, message: 'Missing page title', recommendation: 'Add a unique title tag' });
  } else if (title.length > 60) {
    issues.push({ severity: 'warning', category: 'meta', page: url, message: `Title too long (${title.length} chars)`, recommendation: 'Keep title under 60 characters' });
  } else if (title.length < 30) {
    issues.push({ severity: 'info', category: 'meta', page: url, message: `Title short (${title.length} chars)`, recommendation: 'Consider a more descriptive title (30-60 chars)' });
  }

  // Check meta description
  const metaDesc = document.querySelector('meta[name="description"]')?.getAttribute('content');
  if (!metaDesc) {
    issues.push({ severity: 'critical', category: 'meta', page: url, message: 'Missing meta description', recommendation: 'Add a meta description (120-155 chars)' });
  } else if (metaDesc.length > 160) {
    issues.push({ severity: 'warning', category: 'meta', page: url, message: `Meta description too long (${metaDesc.length} chars)`, recommendation: 'Keep under 155 characters' });
  }

  // Check canonical
  const canonical = document.querySelector('link[rel="canonical"]')?.getAttribute('href');
  if (!canonical) {
    issues.push({ severity: 'warning', category: 'meta', page: url, message: 'Missing canonical URL', recommendation: 'Add a canonical link tag' });
  }

  // Check Open Graph
  const ogTitle = document.querySelector('meta[property="og:title"]')?.getAttribute('content');
  const ogDesc = document.querySelector('meta[property="og:description"]')?.getAttribute('content');
  const ogImage = document.querySelector('meta[property="og:image"]')?.getAttribute('content');
  if (!ogTitle) issues.push({ severity: 'info', category: 'meta', page: url, message: 'Missing og:title', recommendation: 'Add Open Graph title for social sharing' });
  if (!ogDesc) issues.push({ severity: 'info', category: 'meta', page: url, message: 'Missing og:description', recommendation: 'Add Open Graph description' });
  if (!ogImage) issues.push({ severity: 'info', category: 'meta', page: url, message: 'Missing og:image', recommendation: 'Add Open Graph image (1200x630px recommended)' });

  // Check heading structure
  const h1s = document.querySelectorAll('h1');
  if (h1s.length === 0) {
    issues.push({ severity: 'critical', category: 'structure', page: url, message: 'No H1 tag found', recommendation: 'Add exactly one H1 with the primary keyword' });
  } else if (h1s.length > 1) {
    issues.push({ severity: 'warning', category: 'structure', page: url, message: `Multiple H1 tags (${h1s.length})`, recommendation: 'Use only one H1 per page' });
  }

  // Check images for alt text
  const images = document.querySelectorAll('img');
  let imagesWithoutAlt = 0;
  images.forEach(img => {
    if (!img.getAttribute('alt')) imagesWithoutAlt++;
  });
  if (imagesWithoutAlt > 0) {
    issues.push({ severity: 'warning', category: 'content', page: url, message: `${imagesWithoutAlt} images missing alt text`, recommendation: 'Add descriptive alt text to all images' });
  }

  // Check structured data
  const jsonLd = document.querySelectorAll('script[type="application/ld+json"]');
  if (jsonLd.length === 0) {
    issues.push({ severity: 'warning', category: 'structure', page: url, message: 'No JSON-LD structured data', recommendation: 'Add Schema.org structured data (Organization, Course, FAQ, Article)' });
  }

  // Check internal links
  const internalLinks = document.querySelectorAll('a[href^="/"], a[href^="https://voraprep.com"]');
  if (internalLinks.length < 3) {
    issues.push({ severity: 'warning', category: 'links', page: url, message: `Only ${internalLinks.length} internal links`, recommendation: 'Add 3+ internal links to related content' });
  }

  return issues;
}

// ============================================================================
// Growth Action Items Generator
// ============================================================================

/**
 * Generate action items from various audit sources.
 * These appear on the admin Growth Engine dashboard.
 */
export function generateActionItems(
  auditIssues: SEOAuditIssue[],
  contentGapCount: number,
  orphanPageCount: number,
  keywordsDroppedFromPage1: number,
): GrowthActionItem[] {
  const items: GrowthActionItem[] = [];
  let idCounter = 0;

  // Critical SEO issues
  const criticalIssues = auditIssues.filter(i => i.severity === 'critical');
  if (criticalIssues.length > 0) {
    items.push({
      id: `action-${++idCounter}`,
      type: 'technical',
      severity: 'critical',
      title: `${criticalIssues.length} critical SEO issues found`,
      description: criticalIssues.map(i => `${i.page}: ${i.message}`).join('; '),
      autoResolvable: false,
      createdAt: new Date(),
    });
  }

  // Content gaps
  if (contentGapCount > 0) {
    items.push({
      id: `action-${++idCounter}`,
      type: 'content',
      severity: contentGapCount > 20 ? 'warning' : 'info',
      title: `${contentGapCount} content gaps identified`,
      description: `${contentGapCount} high-volume keywords have no assigned page. Generate content briefs to capture this traffic.`,
      autoResolvable: true,
      createdAt: new Date(),
    });
  }

  // Orphan pages
  if (orphanPageCount > 0) {
    items.push({
      id: `action-${++idCounter}`,
      type: 'seo',
      severity: 'warning',
      title: `${orphanPageCount} orphan pages detected`,
      description: `${orphanPageCount} pages have no incoming internal links. Add links from related content.`,
      autoResolvable: true,
      createdAt: new Date(),
    });
  }

  // Ranking drops
  if (keywordsDroppedFromPage1 > 0) {
    items.push({
      id: `action-${++idCounter}`,
      type: 'seo',
      severity: 'critical',
      title: `${keywordsDroppedFromPage1} keywords dropped from page 1`,
      description: `${keywordsDroppedFromPage1} previously page-1 keywords have dropped to page 2+. Investigate and refresh content.`,
      autoResolvable: false,
      createdAt: new Date(),
    });
  }

  return items;
}

// ============================================================================
// Schema.org Validation
// ============================================================================

/**
 * Validate JSON-LD structured data on the current page.
 * Returns issues found.
 */
export function validateStructuredData(): SEOAuditIssue[] {
  const issues: SEOAuditIssue[] = [];
  const scripts = document.querySelectorAll('script[type="application/ld+json"]');

  if (scripts.length === 0) {
    issues.push({
      severity: 'warning',
      category: 'structure',
      message: 'No JSON-LD structured data found',
      recommendation: 'Add Schema.org markup for Organization, Course, or Article',
    });
    return issues;
  }

  scripts.forEach((script, index) => {
    try {
      const data = JSON.parse(script.textContent || '');

      // Check @context
      if (!data['@context'] || data['@context'] !== 'https://schema.org') {
        issues.push({
          severity: 'warning',
          category: 'structure',
          message: `Schema #${index + 1}: Missing or invalid @context`,
          recommendation: 'Set @context to "https://schema.org"',
        });
      }

      // Check @type
      if (!data['@type']) {
        issues.push({
          severity: 'critical',
          category: 'structure',
          message: `Schema #${index + 1}: Missing @type`,
          recommendation: 'Specify a Schema.org type (Organization, Course, Article, FAQPage, etc.)',
        });
      }

      // Type-specific validation
      if (data['@type'] === 'Course') {
        if (!data.name) issues.push({ severity: 'warning', category: 'structure', message: 'Course schema: missing name', recommendation: 'Add course name' });
        if (!data.description) issues.push({ severity: 'warning', category: 'structure', message: 'Course schema: missing description', recommendation: 'Add course description' });
        if (!data.provider) issues.push({ severity: 'warning', category: 'structure', message: 'Course schema: missing provider', recommendation: 'Add provider Organization' });
        if (!data.offers) issues.push({ severity: 'info', category: 'structure', message: 'Course schema: missing offers', recommendation: 'Add pricing offers for rich results' });
      }

      if (data['@type'] === 'Article' || data['@type'] === 'BlogPosting') {
        if (!data.headline) issues.push({ severity: 'warning', category: 'structure', message: 'Article schema: missing headline', recommendation: 'Add article headline' });
        if (!data.author) issues.push({ severity: 'warning', category: 'structure', message: 'Article schema: missing author', recommendation: 'Add article author' });
        if (!data.datePublished) issues.push({ severity: 'warning', category: 'structure', message: 'Article schema: missing datePublished', recommendation: 'Add publication date' });
        if (!data.image) issues.push({ severity: 'info', category: 'structure', message: 'Article schema: missing image', recommendation: 'Add article image for rich results' });
      }

      if (data['@type'] === 'FAQPage') {
        if (!data.mainEntity || !Array.isArray(data.mainEntity) || data.mainEntity.length === 0) {
          issues.push({ severity: 'warning', category: 'structure', message: 'FAQPage schema: missing or empty mainEntity', recommendation: 'Add FAQ items as mainEntity array' });
        }
      }
    } catch {
      issues.push({
        severity: 'critical',
        category: 'structure',
        message: `Schema #${index + 1}: Invalid JSON`,
        recommendation: 'Fix JSON syntax in the structured data',
      });
    }
  });

  return issues;
}

// ============================================================================
// Page Performance Tracking
// ============================================================================

/**
 * Measure Core Web Vitals for the current page.
 * Returns metrics that the Growth Engine tracks over time.
 */
export function measureCoreWebVitals(): Promise<{
  lcp: number | null;
  fid: number | null;
  cls: number | null;
  ttfb: number | null;
  inp: number | null;
}> {
  return new Promise((resolve) => {
    const metrics = {
      lcp: null as number | null,
      fid: null as number | null,
      cls: null as number | null,
      ttfb: null as number | null,
      inp: null as number | null,
    };

    // TTFB
    const navEntries = performance.getEntriesByType('navigation') as PerformanceNavigationTiming[];
    if (navEntries.length > 0) {
      metrics.ttfb = navEntries[0].responseStart - navEntries[0].requestStart;
    }

    // LCP via PerformanceObserver
    try {
      const lcpObserver = new PerformanceObserver((list) => {
        const entries = list.getEntries();
        if (entries.length > 0) {
          metrics.lcp = entries[entries.length - 1].startTime;
        }
      });
      lcpObserver.observe({ type: 'largest-contentful-paint', buffered: true });
    } catch {
      // Observer not supported
    }

    // CLS via PerformanceObserver
    try {
      let clsValue = 0;
      const clsObserver = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          if (!(entry as any).hadRecentInput) {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            clsValue += (entry as any).value;
          }
        }
        metrics.cls = clsValue;
      });
      clsObserver.observe({ type: 'layout-shift', buffered: true });
    } catch {
      // Observer not supported
    }

    // Resolve after a short delay to collect metrics
    setTimeout(() => resolve(metrics), 3000);
  });
}
