/**
 * EA SEE Part 1: Expanded Flashcards Batch 3
 * Individual Taxation - Additional High-Value Cards
 * 7 flashcards covering key 2024-2025 SEE1 topics
 */

import { EAFlashcard } from './types';

export const SEE1_BATCH3: EAFlashcard[] = [
  {
    id: 'see1-b3-001',
    section: 'SEE1',
    type: 'threshold',
    topic: 'Filing Requirements',
    subtopic: '2024 Thresholds',
    blueprintArea: 'SEE1-1',
    front: 'What are the 2024 gross income filing thresholds?',
    back: '**Single:** $14,600\n**MFJ (both <65):** $29,200\n**MFJ (one ≥65):** $30,750\n**MFS:** $5\n**HOH:** $21,900\n**QSS:** $29,200\n\n**Self-employed:** Must file if net SE income ≥ $400\n\n**Dependents:** Earned income > $14,600 OR unearned income > $1,300',
    difficulty: 'medium',
    tags: ['filing thresholds', '2024'],
    irsReference: 'Pub. 501',
  },
  {
    id: 'see1-b3-002',
    section: 'SEE1',
    type: 'formula',
    topic: 'Basis Calculations',
    subtopic: 'Like-Kind Exchange',
    blueprintArea: 'SEE1-3',
    front: 'How do you calculate the basis in property received in a §1031 like-kind exchange?',
    back: '**Formula:**\nBasis of property received =\n(Basis of property given) - (Boot received) + (Gain recognized) + (Boot paid)\n\n**OR:** FMV of new property - Deferred gain\n\n**Boot = cash + FMV of non-like-kind property**\n\nGain recognized = Lesser of: (1) Gain realized or (2) Boot received',
    difficulty: 'hard',
    tags: ['1031', 'like-kind', 'basis'],
    irsReference: 'IRC §1031',
    formula: 'New Basis = Old Basis - Boot Received + Gain Recognized + Boot Paid',
  },
  {
    id: 'see1-b3-003',
    section: 'SEE1',
    type: 'mnemonic',
    topic: 'Education Credits',
    subtopic: 'AOTC vs LLC',
    blueprintArea: 'SEE1-5',
    front: 'How to remember the key differences between AOTC and Lifetime Learning Credit?',
    back: '**AOTC = 4-A Rule:**\n- First **4** years\n- **$4**0% refundable\n- Max **$2,500** (2+5-0.5=4-ish)\n- **A**mericans only (citizenship req)\n\n**LLC = Lifetime = LESS:**\n- **L**ifetime availability\n- **E**veryone eligible (no felony restriction)\n- **S**maller amount (20% of $10K)\n- **S**ingle or part-time OK\n\n**AOTC stricter; LLC more flexible**',
    difficulty: 'medium',
    tags: ['education', 'AOTC', 'LLC'],
    irsReference: 'IRC §25A',
    mnemonic: 'AOTC = 4 A Rule; LLC = LESS restrictions',
  },
  {
    id: 'see1-b3-004',
    section: 'SEE1',
    type: 'comparison',
    topic: 'Retirement Distributions',
    subtopic: 'Traditional vs Roth',
    blueprintArea: 'SEE1-2',
    front: 'What are the key tax differences between Traditional and Roth IRA withdrawals?',
    back: '**Traditional IRA:**\n- Contributions may be deductible\n- All distributions taxed as ordinary income\n- RMDs required starting at 73\n- 10% early withdrawal penalty <59½\n\n**Roth IRA:**\n- Contributions never deductible\n- Qualified distributions tax-FREE\n- NO RMDs during owner\'s lifetime\n- Can withdraw contributions anytime tax-free\n\n**5-year rule applies to Roth earnings**',
    difficulty: 'medium',
    tags: ['IRA', 'Traditional', 'Roth'],
    irsReference: 'IRC §408, §408A',
    comparison: {
      itemA: 'Traditional IRA',
      itemB: 'Roth IRA',
      differences: ['Tax treatment', 'RMD rules', 'Contribution deductibility']
    },
  },
  {
    id: 'see1-b3-005',
    section: 'SEE1',
    type: 'rule',
    topic: 'Passive Activities',
    subtopic: 'Real Estate Professional',
    blueprintArea: 'SEE1-4',
    front: 'What qualifies a taxpayer as a Real Estate Professional for passive activity purposes?',
    back: '**Requirements (meet BOTH):**\n1. More than 750 hours in real estate activities during the year\n2. More than 50% of personal services in real estate\n\n**Real estate activities include:**\n- Development\n- Construction\n- Acquisition\n- Management\n- Leasing\n- Brokerage\n\n**Effect:** Rental real estate is NOT passive\n\n**Each spouse tested separately (except MFJ election)**',
    difficulty: 'hard',
    tags: ['passive', 'real estate', 'REP'],
    irsReference: 'IRC §469(c)(7)',
  },
  {
    id: 'see1-b3-006',
    section: 'SEE1',
    type: 'penalty',
    topic: 'Penalties',
    subtopic: 'Estimated Tax Penalty',
    blueprintArea: 'SEE1-6',
    front: 'How is the estimated tax penalty calculated and what are the safe harbors?',
    back: '**Penalty = Interest on underpayment**\n\n**Safe Harbors (No penalty if paid):**\n- 100% of prior year tax (110% if AGI >$150K)\n- 90% of current year tax\n- Balance due <$1,000\n\n**Quarterly Due Dates:**\n- Q1: April 15\n- Q2: June 15\n- Q3: Sept 15\n- Q4: Jan 15\n\n**Annualized income installment method available for uneven income**',
    difficulty: 'medium',
    tags: ['estimated tax', 'penalty', 'safe harbor'],
    irsReference: 'IRC §6654',
  },
  {
    id: 'see1-b3-007',
    section: 'SEE1',
    type: 'concept',
    topic: 'Capital Gains',
    subtopic: 'Net Investment Income Tax',
    blueprintArea: 'SEE1-3',
    front: 'What is the Net Investment Income Tax (NIIT) and when does it apply?',
    back: '**Rate:** 3.8% surtax\n\n**Applies when:**\n- MAGI exceeds threshold\n- Taxpayer has net investment income\n\n**Thresholds:**\n- MFJ/QSS: $250,000\n- Single/HOH: $200,000\n- MFS: $125,000\n\n**Investment Income includes:**\n- Interest, dividends, capital gains\n- Rental income\n- Royalties\n- Passive activity income\n\n**Tax = 3.8% × Lesser of: NII or (MAGI - threshold)**',
    difficulty: 'hard',
    tags: ['NIIT', 'investment', 'surtax'],
    irsReference: 'IRC §1411',
  },
];
