/**
 * EA SEE Part 2: Expanded Flashcards Batch 3
 * Business Taxation - Additional High-Value Cards
 * 7 flashcards covering key 2024-2025 SEE2 topics
 */

import { EAFlashcard } from './types';

export const SEE2_BATCH3: EAFlashcard[] = [
  {
    id: 'see2-b3-001',
    section: 'SEE2',
    type: 'formula',
    topic: 'Partnership Taxation',
    subtopic: 'Partner Basis',
    blueprintArea: 'SEE2-1',
    front: 'How do you calculate a partner\'s outside basis throughout the year?',
    back: '**Starting Basis:**\nInitial contribution (cash + FMV property) + Share of liabilities\n\n**Annual Adjustments:**\n**INCREASES:**\n+ Distributive share of income\n+ Tax-exempt income\n+ Additional contributions\n+ Increased share of liabilities\n\n**DECREASES:**\n- Distributions received\n- Distributive share of losses\n- Nondeductible expenses\n- Decreased share of liabilities\n\n**Basis cannot go below zero**',
    difficulty: 'hard',
    tags: ['partnership', 'basis', 'outside basis'],
    irsReference: 'IRC §705',
    formula: 'Ending Basis = Beginning + Income + Contributions + Liability↑ - Distributions - Losses - Liability↓',
  },
  {
    id: 'see2-b3-002',
    section: 'SEE2',
    type: 'comparison',
    topic: 'Entity Selection',
    subtopic: 'S Corp vs Partnership',
    blueprintArea: 'SEE2-1',
    front: 'What are the key tax differences between S Corporations and Partnerships?',
    back: '**S CORPORATION:**\n- Limited to 100 shareholders\n- One class of stock\n- Shareholder basis NOT increased by entity debt\n- Reasonable salary required for owner-employees\n- Distributions generally not subject to SE tax\n\n**PARTNERSHIP:**\n- Unlimited partners\n- Flexible allocations allowed\n- Partner basis INCLUDES share of debt\n- Guaranteed payments = SE income\n- Distributions reduce basis\n\n**Both: Pass-through taxation, no entity-level tax**',
    difficulty: 'hard',
    tags: ['S corp', 'partnership', 'entity'],
    irsReference: 'IRC §701, §1361',
    comparison: {
      itemA: 'S Corporation',
      itemB: 'Partnership',
      differences: ['Debt basis', 'SE tax treatment', 'Allocation flexibility']
    },
  },
  {
    id: 'see2-b3-003',
    section: 'SEE2',
    type: 'threshold',
    topic: 'Depreciation',
    subtopic: 'Section 179 Limits',
    blueprintArea: 'SEE2-2',
    front: 'What are the 2024 Section 179 expensing limits?',
    back: '**Maximum Deduction:** $1,220,000\n\n**Phase-out Threshold:** Begins at $3,050,000\n- Reduces dollar-for-dollar above threshold\n- Completely eliminated at $4,270,000\n\n**Limitations:**\n- Cannot exceed business income\n- Per asset limits for vehicles\n- Excess carries forward\n\n**Qualifying Property:**\n- Tangible personal property\n- Qualified improvement property\n- Certain real property (roofs, HVAC, fire protection, security)\n\n**SUV limit: $30,500**',
    difficulty: 'medium',
    tags: ['Section 179', 'depreciation', '2024'],
    irsReference: 'IRC §179',
  },
  {
    id: 'see2-b3-004',
    section: 'SEE2',
    type: 'mnemonic',
    topic: 'Corporation Distributions',
    subtopic: 'E&P Ordering',
    blueprintArea: 'SEE2-1',
    front: 'How to remember the order of corporate distribution taxation?',
    back: '**D-R-C = Dividend, Return, Capital Gain**\n\n**Distribution Treatment Order:**\n1. **D**ividend - To extent of E&P (current then accumulated)\n2. **R**eturn of capital - Tax-free reduction of stock basis\n3. **C**apital gain - After basis reduced to zero\n\n**E&P Layers:**\n- Current E&P allocated pro-rata to all distributions\n- Then accumulated E&P (chronologically)\n\n**Remember: "DRC" - like Democratic Republic... of Cash!**',
    difficulty: 'medium',
    tags: ['distributions', 'E&P', 'dividends'],
    irsReference: 'IRC §301, §316',
    mnemonic: 'DRC = Dividend, Return, Capital Gain',
  },
  {
    id: 'see2-b3-005',
    section: 'SEE2',
    type: 'rule',
    topic: 'Employment Taxes',
    subtopic: 'Trust Fund Recovery',
    blueprintArea: 'SEE2-3',
    front: 'What is the Trust Fund Recovery Penalty and who is liable?',
    back: '**Trust Fund Taxes:**\n- Withheld income tax\n- Employee portion of FICA\n- NOT employer FICA portion\n\n**Penalty = 100%** of unpaid trust fund taxes\n\n**Responsible Persons:**\n- Officers, directors\n- Employees with financial control\n- Anyone who can decide which creditors to pay\n\n**Requirements:**\n1. **Responsibility** - Authority over finances\n2. **Willfulness** - Knew taxes unpaid, chose to pay others\n\n**Multiple persons can be liable for same tax**',
    difficulty: 'hard',
    tags: ['TFRP', 'payroll', 'penalty'],
    irsReference: 'IRC §6672',
  },
  {
    id: 'see2-b3-006',
    section: 'SEE2',
    type: 'concept',
    topic: 'S Corporation',
    subtopic: 'AAA vs Stock Basis',
    blueprintArea: 'SEE2-1',
    front: 'What is the difference between AAA and shareholder stock basis?',
    back: '**AAA (Accumulated Adjustments Account):**\n- Corporate-level account\n- Tracks S corp earnings since election\n- Used to determine dividend treatment\n- CAN go negative (but not for tax-free distrib.)\n- Reduced by distributions\n\n**Stock Basis:**\n- Shareholder-level\n- Limits loss deductions\n- CANNOT go below zero\n- Determines gain on sale\n- Includes debt basis (if applicable)\n\n**Key:** Distributions tax-free to extent of AAA but limited by stock basis',
    difficulty: 'hard',
    tags: ['S corp', 'AAA', 'basis'],
    irsReference: 'IRC §1368',
  },
  {
    id: 'see2-b3-007',
    section: 'SEE2',
    type: 'rule',
    topic: 'Accounting Methods',
    subtopic: 'Cash vs Accrual',
    blueprintArea: 'SEE2-2',
    front: 'When must a business use the accrual method of accounting?',
    back: '**Accrual Required for:**\n- C corporations* with avg gross receipts >$30M\n- Tax shelters\n- Certain farming operations\n\n***Exception:** Small business ($30M test) can use cash\n\n**Cash Method Allowed if:**\n- Average gross receipts ≤$30M (3-yr avg)\n- Not a tax shelter\n- Sole proprietors, S corps, partnerships generally qualify\n\n**Inventory Exception:**\n- Small businesses can treat inventory as non-incidental supplies if <$30M test met\n\n**Gross receipts test is per-entity**',
    difficulty: 'medium',
    tags: ['accounting method', 'cash', 'accrual'],
    irsReference: 'IRC §448',
  },
];
