import { Question } from '../../../types';

export const SEE3_QUESTIONS_CIRCULAR230: Question[] = [
  {
    id: 'see3-c230-001',
    courseId: 'ea',
    section: 'SEE3',
    blueprintArea: 'SEE3-1', 
    topic: 'Practices and Procedures',
    subtopic: 'Conflict of Interest',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Enrolled Agent Jane is asked to represent both Husband and Wife in an examination of their jointly filed return. The couple is now undergoing a bitter divorce. Jane determines there is a significant conflict of interest. Under Circular 230, which of the following is true regarding Jane’s ability to represent both parties?',
    options: [
      'She may not represent both parties under any circumstances.',
      'She may represent both if she reasonably believes she can provide competent and diligent representation to each, and each client gives informed written consent.',
      'She may represent both provided the divorce is not yet final.',
      'She may represent both only if she obtains a waiver from the IRS Office of Professional Responsibility.'
    ],
    correctAnswer: 1,
    explanation: 'Under Circular 230 §10.29, a practitioner may represent clients despite a conflict of interest if the practitioner reasonably believes that they will be able to provide competent and diligent representation to each affected client, and each affected client waives the conflict of interest and gives informed consent, confirmed in writing.',
    reference: 'Circular 230, §10.29',
  },
  {
    id: 'see3-c230-002',
    courseId: 'ea',
    section: 'SEE3',
    blueprintArea: 'SEE3-1', 
    topic: 'Practices and Procedures',
    subtopic: 'Contingent Fees',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'Practitioner Bob prepares an original tax return for Client C. Client C wants to pay Bob a fee based on a percentage of the refund generated by the return. Which of the following statements is correct regarding this fee arrangement?',
    options: [
      'This is allowable if the refund exceeds $10,000.',
      'This is allowable as long as it is disclosed on the return.',
      'This is a prohibited contingent fee arrangement.',
      'This is allowable because it incentivizes the practitioner to find legal deductions.'
    ],
    correctAnswer: 2,
    explanation: 'Circular 230 §10.27 generally prohibits contingent fees for preparing an original tax return. Contingent fees are only allowed in specific situations such as an examination of an original tax return, a claim for refund filed in connection with a statutory interest or penalty determination, or judicial proceedings.',
    reference: 'Circular 230, §10.27',
  },
  {
    id: 'see3-c230-003',
    courseId: 'ea',
    section: 'SEE3',
    blueprintArea: 'SEE3-1', 
    topic: 'Practices and Procedures',
    subtopic: 'Client Records',
    difficulty: 'hard',
    skillLevel: 'Analysis',
    question: 'Client D terminates the services of Enrolled Agent Sarah and requests the return of all records. D has not paid Sarah for the preparation of the current year’s return. State law allows a lien on records for unpaid fees. Under Circular 230, what is Sarah required to do?',
    options: [
      'She must return all records immediately, regardless of fees owed.',
      'She may withhold all records until the fee is paid.',
      'She must return those records necessary for the client to comply with federal tax obligations, but may withhold her own work product if state law permits.',
      'She must return the original records provided by the client but may withhold the return she prepared.'
    ],
    correctAnswer: 3,
    explanation: 'Under §10.28, a practitioner must return all client records necessary for the client to comply with Federal tax obligations. However, if state law allows a lien for unpaid fees, the practitioner is only required to return documents that must be attached to the return, but must provide the client access to review and copy other necessary records. The term "client records" includes materials provided by the client, but generally not the practitioner\'s own work product unless payment has been made.',
    reference: 'Circular 230, §10.28',
  },
  {
    id: 'see3-c230-004',
    courseId: 'ea',
    section: 'SEE3',
    blueprintArea: 'SEE3-1', 
    topic: 'Practices and Procedures',
    subtopic: 'Due Diligence',
    difficulty: 'medium',
    skillLevel: 'Application',
    question: 'A new client provides Enrolled Agent Mike with a list of charitable deductions totaling exactly $10,000, all in cash. Mike knows this is statistically improbable and typically triggers flags. The client confirms the amount verbally. Mike signs the return without asking for documentation or further questions. Has Mike violated Circular 230?',
    options: [
        'Yes, because he is required to audit all cash contributions.',
        'No, because a practitioner may always rely on the client\'s oral representation.',
        'Yes, because the information appeared incorrect or incomplete, and he failed to make reasonable inquiries.',
        'No, because the amount was not material.'
    ],
    correctAnswer: 2,
    explanation: 'Under §10.34, a practitioner cannot ignore the implications of information provided. Suspiciously round numbers or inconsistent data require the practitioner to make reasonable inquiries. Accepting such data without further questioning violates the due diligence requirement.',
    reference: 'Circular 230, §10.34'
  },
  {
    id: 'see3-c230-005',
    courseId: 'ea',
    section: 'SEE3',
    blueprintArea: 'SEE3-1', 
    topic: 'Practices and Procedures',
    subtopic: 'Advertising',
    difficulty: 'easy',
    skillLevel: 'Remembering and Understanding',
    question: 'Enrolled Agent Tom runs a radio ad stating: "I guarantee I will get you a refund, or my services are free!" Under Circular 230, is this advertisement permissible?',
    options: [
      'Yes, as long as he honestly intends to waive the fee.',
      'No, because it implies a guaranteed result which is prohibited.',
      'Yes, because it is commercial speech protected by the First Amendment.',
      'No, because radio advertising is not allowed for Enrolled Agents.'
    ],
    correctAnswer: 1,
    explanation: 'Circular 230 §10.30 prohibits any form of public communication containing a false, fraudulent, coercive, misleading, or deceptive statement or claim. Guaranteeing a refund implies a result that cannot be controlled (as refunds depend on the facts and law), and is considered misleading.',
    reference: 'Circular 230, §10.30'
  }
];
