/**
 * Article Review — Review and approve AI-generated blog articles
 * 
 * Shows articles in 'review' status, allows preview, edit, approve, or reject.
 * This is the human review gate before publishing AI-generated content.
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import { Link } from 'react-router-dom';
import {
  collection, query, where, orderBy, getDocs, doc, updateDoc, deleteDoc,
  Timestamp, limit,
} from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { db, functions } from '../../../config/firebase';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  FileText, Check, X, Eye, ChevronLeft,
  Calendar, RefreshCw, ExternalLink,
  Filter, BookOpen, Trash2, MessageSquare, Send, Sparkles, Copy, CheckCircle, FileEdit,
  Rss, Linkedin, Globe,
} from 'lucide-react';
import { Card } from '../../common/Card';
import { Button } from '../../common/Button';
import logger from '../../../utils/logger';

// ============================================================================
// AI Chat Types
// ============================================================================

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

// ============================================================================
// Types
// ============================================================================

interface ChannelDistribution {
  status: 'pending' | 'posted' | 'skipped' | 'failed';
  publishedAt?: Timestamp;
  postedAt?: Timestamp;
  url?: string;
  postUrl?: string;
}

interface ArticleDistribution {
  blog?: ChannelDistribution;
  rss?: ChannelDistribution;
  linkedin?: ChannelDistribution;
}

interface Article {
  id: string;
  title: string;
  slug: string;
  courseId: string;
  contentType: string;
  status: 'brief' | 'review' | 'approved' | 'published' | 'rejected';
  generatedContent?: string;
  metaDescription?: string;
  wordCount?: number;
  generatedAt?: Timestamp;
  publishedAt?: Timestamp;
  reviewedAt?: Timestamp;
  targetKeywords?: string[];
  autoGenerated?: boolean;
  distribution?: ArticleDistribution;
}

type FilterStatus = 'all' | 'review' | 'approved' | 'published' | 'brief' | 'rejected';

// ============================================================================
// Main Component
// ============================================================================

export default function ArticleReview() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);
  const [filterStatus, setFilterStatus] = useState<FilterStatus>('review');
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const loadRequestRef = useRef(0);

  const loadArticles = useCallback(async () => {
    const requestId = ++loadRequestRef.current;
    setLoading(true);
    try {
      let q;
      if (filterStatus === 'all') {
        q = query(
          collection(db, 'growth_content'),
          orderBy('generatedAt', 'desc'),
          limit(100),
        );
      } else {
        q = query(
          collection(db, 'growth_content'),
          where('status', '==', filterStatus),
          limit(100),
        );
      }

      const snapshot = await getDocs(q);
      const items: Article[] = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data(),
      } as Article));

      // Keep newest items first without requiring a composite index.
      items.sort((a, b) => {
        const aTs = a.generatedAt?.toMillis?.() || a.publishedAt?.toMillis?.() || 0;
        const bTs = b.generatedAt?.toMillis?.() || b.publishedAt?.toMillis?.() || 0;
        return bTs - aTs;
      });

      // Ignore stale responses if the user switched tabs mid-request.
      if (requestId !== loadRequestRef.current) return;
      setArticles(items);
    } catch (err) {
      logger.error('[ArticleReview] Failed to load articles:', err);
      // Clear stale list when current tab query fails so tabs don't show old results.
      if (requestId === loadRequestRef.current) {
        setArticles([]);
      }
    } finally {
      if (requestId === loadRequestRef.current) {
        setLoading(false);
      }
    }
  }, [filterStatus]);

  useEffect(() => {
    loadArticles();
  }, [loadArticles]);

  const handleApprove = async (article: Article) => {
    setActionLoading(article.id);
    try {
      await updateDoc(doc(db, 'growth_content', article.id), {
        status: 'approved',
        approvedAt: Timestamp.now(),
        reviewedAt: Timestamp.now(),
      });
      setArticles(prev => prev.filter(a => a.id !== article.id));
      setSelectedArticle(null);
      logger.info(`[ArticleReview] Approved (queued for publish): ${article.slug}`);
    } catch (err) {
      logger.error('[ArticleReview] Approve failed:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const handlePublishNow = async (article: Article) => {
    setActionLoading(article.id);
    try {
      await updateDoc(doc(db, 'growth_content', article.id), {
        status: 'published',
        publishedAt: Timestamp.now(),
        reviewedAt: article.reviewedAt ?? Timestamp.now(),
      });
      setArticles(prev => prev.filter(a => a.id !== article.id));
      setSelectedArticle(null);
      logger.info(`[ArticleReview] Published immediately: ${article.slug}`);
    } catch (err) {
      logger.error('[ArticleReview] Publish failed:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const handleReject = async (article: Article) => {
    if (!confirm(`Reject "${article.title}"? This will mark it as rejected.`)) return;
    
    setActionLoading(article.id);
    try {
      await updateDoc(doc(db, 'growth_content', article.id), {
        status: 'rejected',
        rejectedAt: Timestamp.now(),
      });
      setArticles(prev => prev.filter(a => a.id !== article.id));
      setSelectedArticle(null);
      logger.info(`[ArticleReview] Rejected: ${article.slug}`);
    } catch (err) {
      logger.error('[ArticleReview] Reject failed:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const handleDelete = async (article: Article) => {
    if (!confirm(`Delete "${article.title}" permanently? This cannot be undone.`)) return;
    
    setActionLoading(article.id);
    try {
      await deleteDoc(doc(db, 'growth_content', article.id));
      setArticles(prev => prev.filter(a => a.id !== article.id));
      setSelectedArticle(null);
      logger.info(`[ArticleReview] Deleted: ${article.slug}`);
    } catch (err) {
      logger.error('[ArticleReview] Delete failed:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const handleRegenerate = async (article: Article) => {
    // Reset to brief status so auto-publisher can regenerate
    setActionLoading(article.id);
    try {
      await updateDoc(doc(db, 'growth_content', article.id), {
        status: 'brief',
        generatedContent: null,
        metaDescription: null,
        wordCount: null,
        generatedAt: null,
      });
      setArticles(prev => prev.filter(a => a.id !== article.id));
      setSelectedArticle(null);
      logger.info(`[ArticleReview] Reset to brief: ${article.slug}`);
    } catch (err) {
      logger.error('[ArticleReview] Reset failed:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const handleUpdateContent = async (article: Article, newContent: string) => {
    setActionLoading(article.id);
    try {
      // Keep the full content including H1 title - the H1 is the source of truth
      // Extract H1 title to sync to the title field (for SEO/meta purposes)
      const cleanedContent = newContent.trim();
      
      // Extract title from H1 heading (if present) to sync to title field
      let extractedTitle: string | null = null;
      const h1Match = cleanedContent.match(/^#\s+(.+?)(?:\n|$)/);
      if (h1Match) {
        extractedTitle = h1Match[1].trim();
      }
      
      const wordCount = cleanedContent.split(/\s+/).filter(w => w.length > 0).length;
      
      // Build update object - sync title from H1 if present
      const updateData: Record<string, unknown> = {
        generatedContent: cleanedContent,
        wordCount,
        editedAt: Timestamp.now(),
      };
      
      if (extractedTitle) {
        updateData.title = extractedTitle;
        // Also update slug if title changed significantly
        const newSlug = extractedTitle
          .toLowerCase()
          .replace(/[®©™]/g, '')
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '');
        if (newSlug && newSlug !== article.slug) {
          updateData.slug = newSlug;
        }
      }
      
      await updateDoc(doc(db, 'growth_content', article.id), updateData);
      
      // Update the selected article in state
      setSelectedArticle(prev => prev ? { 
        ...prev, 
        generatedContent: cleanedContent, 
        wordCount,
        title: extractedTitle || prev.title,
        slug: (updateData.slug as string) || prev.slug,
      } : null);
      
      // Update in the articles list too
      setArticles(prev => prev.map(a => 
        a.id === article.id ? { 
          ...a, 
          generatedContent: cleanedContent, 
          wordCount,
          title: extractedTitle || a.title,
          slug: (updateData.slug as string) || a.slug,
        } : a
      ));
      
      logger.info(`[ArticleReview] Content updated: ${article.slug}${extractedTitle ? ` (new title: ${extractedTitle})` : ''}`);
    } catch (err) {
      logger.error('[ArticleReview] Content update failed:', err);
      throw err;
    } finally {
      setActionLoading(null);
    }
  };

  // Count by status
  const counts = {
    review: articles.filter(a => a.status === 'review').length,
    published: articles.filter(a => a.status === 'published').length,
    brief: articles.filter(a => a.status === 'brief').length,
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <Link
                to="/admin"
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
              >
                <ChevronLeft className="w-5 h-5" />
              </Link>
              <h1 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                <FileText className="w-5 h-5 text-blue-500" />
                Article Review
              </h1>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400 ml-8">
              Review AI-generated articles before publishing to the blog
            </p>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={loadArticles}
            leftIcon={RefreshCw}
          >
            Refresh
          </Button>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-6">
        {/* Status Filter */}
        <div className="flex items-center gap-2 mb-6">
          <Filter className="w-4 h-4 text-gray-400" />
          {(['review', 'approved', 'published', 'brief', 'all'] as FilterStatus[]).map(status => (
            <button
              key={status}
              onClick={() => setFilterStatus(status)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                filterStatus === status
                  ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'
                  : 'text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700'
              }`}
            >
              {status === 'review' ? `Pending Review (${counts.review})` :
               status === 'approved' ? 'Queued to Publish' :
               status === 'published' ? 'Published' :
               status === 'brief' ? 'Briefs' : 'All'}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500" />
          </div>
        ) : selectedArticle ? (
          /* Article Preview */
          <ArticlePreview
            article={selectedArticle}
            onBack={() => setSelectedArticle(null)}
            onApprove={() => handleApprove(selectedArticle)}
            onPublishNow={() => handlePublishNow(selectedArticle)}
            onReject={() => handleReject(selectedArticle)}
            onDelete={() => handleDelete(selectedArticle)}
            onRegenerate={() => handleRegenerate(selectedArticle)}
            onUpdateContent={(newContent) => handleUpdateContent(selectedArticle, newContent)}
            loading={actionLoading === selectedArticle.id}
          />
        ) : (
          /* Article List */
          <div className="space-y-3">
            {articles.length === 0 ? (
              <Card className="p-12 text-center">
                <FileText className="w-12 h-12 text-gray-300 dark:text-gray-600 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                  {filterStatus === 'review' ? 'No articles pending review' : 'No articles found'}
                </h3>
                <p className="text-gray-500 dark:text-gray-400">
                  {filterStatus === 'review'
                    ? 'The auto-publish engine will generate articles daily. Check back later!'
                    : 'Try a different filter or seed content briefs.'}
                </p>
              </Card>
            ) : (
              articles.map(article => (
                <ArticleRow
                  key={article.id}
                  article={article}
                  onClick={() => setSelectedArticle(article)}
                  onApprove={() => handleApprove(article)}
                  loading={actionLoading === article.id}
                />
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ============================================================================
// Article Row
// ============================================================================

function ArticleRow({
  article,
  onClick,
  onApprove,
  loading,
}: {
  article: Article;
  onClick: () => void;
  onApprove: () => void;
  loading: boolean;
}) {
  const date = article.generatedAt?.toDate?.() || article.publishedAt?.toDate?.();
  
  return (
    <Card className="p-4 hover:border-gray-300 dark:hover:border-gray-600 transition-colors">
      <div className="flex items-start justify-between gap-4">
        <button
          onClick={onClick}
          className="flex-1 text-left"
        >
          <div className="flex items-center gap-2 mb-1">
            <span className={`inline-flex px-2 py-0.5 rounded text-xs font-medium ${
              article.status === 'review'
                ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
                : article.status === 'published'
                ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                : article.status === 'rejected'
                ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-400'
            }`}>
              {article.status}
            </span>
            <span className="text-xs text-gray-400 uppercase font-medium">
              {article.courseId || 'exam'}
            </span>
            <span className="text-xs text-gray-400">
              {article.contentType?.replace(/-/g, ' ')}
            </span>
          </div>
          <h3 className="font-semibold text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
            {article.title}
          </h3>
          <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
            {article.wordCount && (
              <span className="flex items-center gap-1">
                <BookOpen className="w-3 h-3" />
                {article.wordCount.toLocaleString()} words
              </span>
            )}
            {date && (
              <span className="flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {date.toLocaleDateString()}
              </span>
            )}
            <span className="text-gray-400">/blog/{article.slug}</span>
          </div>
          {/* Distribution Badges */}
          {article.status === 'published' && article.distribution && (
            <div className="flex items-center gap-1.5 mt-2">
              {article.distribution.blog?.status === 'posted' && (
                <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400 text-xs">
                  <Globe className="w-3 h-3" /> Blog
                </span>
              )}
              {article.distribution.rss?.status === 'posted' && (
                <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400 text-xs">
                  <Rss className="w-3 h-3" /> RSS
                </span>
              )}
              {article.distribution.linkedin?.status === 'posted' && (
                <a
                  href={article.distribution.linkedin.postUrl || article.distribution.linkedin.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-400 text-xs hover:bg-sky-200 dark:hover:bg-sky-900/50 transition-colors"
                  onClick={(e) => e.stopPropagation()}
                >
                  <Linkedin className="w-3 h-3" /> LinkedIn
                </a>
              )}
            </div>
          )}
        </button>

        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={onClick}
            leftIcon={Eye}
          >
            Preview
          </Button>
          {article.status === 'review' && (
            <Button
              variant="primary"
              size="sm"
              onClick={(e) => { e.stopPropagation(); onApprove(); }}
              leftIcon={Check}
              loading={loading}
            >
              Approve
            </Button>
          )}
          {article.status === 'published' && (
            <a
              href={`/blog/${article.slug}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 px-3 py-1.5 text-sm font-medium text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
            >
              View <ExternalLink className="w-3 h-3" />
            </a>
          )}
        </div>
      </div>
    </Card>
  );
}

// ============================================================================
// Article Preview with AI Chat
// ============================================================================

function ArticlePreview({
  article,
  onBack,
  onApprove,
  onPublishNow,
  onReject,
  onDelete,
  onRegenerate,
  loading,
  onUpdateContent,
}: {
  article: Article;
  onBack: () => void;
  onApprove: () => void;
  onPublishNow: () => void;
  onReject: () => void;
  onDelete: () => void;
  onRegenerate: () => void;
  loading: boolean;
  onUpdateContent: (newContent: string) => Promise<void>;
}) {
  const [showRaw, setShowRaw] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const [editedContent, setEditedContent] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editDraft, setEditDraft] = useState('');
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Clean the content (remove "Meta Description: ..." line if present)
  const originalContent = article.generatedContent?.replace(/^Meta\s*Description:.*\n?/im, '').trim() || '';
  const content = editedContent ?? originalContent;

  // Scroll to bottom when new messages arrive
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  const handleSendMessage = async () => {
    if (!chatInput.trim() || chatLoading) return;

    const userMessage = chatInput.trim();
    setChatInput('');
    
    // Add user message
    const newUserMessage: ChatMessage = {
      role: 'user',
      content: userMessage,
      timestamp: new Date(),
    };
    setChatMessages(prev => [...prev, newUserMessage]);
    setChatLoading(true);

    try {
      // Build system prompt for article review assistant
      const systemPrompt = `You are an expert content editor reviewing a blog article for VoraPrep, an AI-powered exam prep platform.

ARTICLE BEING REVIEWED:
Title: ${article.title}
Course: ${article.courseId?.toUpperCase() || 'Exam Prep'}
Type: ${article.contentType}

FULL ARTICLE CONTENT:
${content}

YOUR ROLE:
- Answer questions about the article content, structure, and quality
- Identify issues like redundancy, factual errors, or unclear sections
- When asked to fix issues, provide the COMPLETE updated article content
- Be specific about what changes you're making and why

IMPORTANT FORMATTING FOR EDITED ARTICLES:
- Start your response by briefly stating what you changed (1-2 sentences)
- Then add a blank line and the full corrected article
- The article MUST start with \`# Title\` (markdown H1) on its own line - this becomes the page title
- Do NOT repeat the title as plain text anywhere in the article body
- Do NOT include phrases like "Here's the corrected article:" in the article content itself
- Keep the same markdown format as the original
- Maintain SEO structure (H1, H2, H3 headings)

EXAMPLE FORMAT:
I fixed the duplicate title and corrected the exam name.

# Free CFP Practice Questions (2026)

Preparing for the CFP® exam is a significant undertaking...`;

      const messages = [
        ...chatMessages.map(m => ({
          role: m.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: m.content }],
        })),
        { role: 'user', parts: [{ text: userMessage }] },
      ];

      // Call geminiProxy
      const geminiProxy = httpsCallable<
        { messages: typeof messages; systemPrompt: string; generationConfig?: Record<string, unknown> },
        { text: string }
      >(functions, 'geminiProxy');

      const result = await geminiProxy({
        messages,
        systemPrompt,
        generationConfig: {
          temperature: 0.4,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 8192,
        },
      });

      const assistantResponse = result.data.text;
      
      // Add assistant message
      const newAssistantMessage: ChatMessage = {
        role: 'assistant',
        content: assistantResponse,
        timestamp: new Date(),
      };
      setChatMessages(prev => [...prev, newAssistantMessage]);

      // Check if the response contains edited content - look for common patterns
      const editPatterns = [
        /(?:here'?s?|here is) the (?:corrected|updated|revised|fixed|edited|new) (?:article|content|version)/i,
        /(?:updated|corrected|revised|fixed) article:?/i,
        /^#\s+.+\n/m, // Starts with a markdown H1 heading (likely full article)
      ];
      
      const hasEditContent = editPatterns.some(pattern => pattern.test(assistantResponse));
      
      if (hasEditContent) {
        // Try to extract markdown content - look for code blocks or full article structure
        let extractedContent: string | null = null;
        
        // Pattern 1: Content in markdown code block
        const codeBlockMatch = assistantResponse.match(/```(?:markdown)?\s*\n([\s\S]+?)\n```/);
        if (codeBlockMatch) {
          extractedContent = codeBlockMatch[1].trim();
        }
        
        // Pattern 2: Content after a header phrase (everything after "Here's the corrected article:")
        // Allow for zero or more newlines/spaces after the colon
        if (!extractedContent) {
          const afterHeaderMatch = assistantResponse.match(/(?:here'?s?|here is) the (?:corrected|updated|revised|fixed|edited|new) (?:article|content|version):?\s*([\s\S]+)/i);
          if (afterHeaderMatch) {
            let extracted = afterHeaderMatch[1].trim();
            // If the extraction doesn't start with # but the title is on the first line, add # prefix
            if (!/^#\s/.test(extracted)) {
              // Check if first line looks like a title (short line before double newline)
              const firstLineMatch = extracted.match(/^(.+?)(?:\n\n|\n(?=[A-Z]))/);
              if (firstLineMatch && firstLineMatch[1].length < 100) {
                // Convert first line to H1
                extracted = `# ${firstLineMatch[1].trim()}\n\n${extracted.slice(firstLineMatch[0].length).trim()}`;
              }
            }
            extractedContent = extracted;
          }
        }
        
        // Pattern 3: If response starts with H1, it's likely the full article
        if (!extractedContent && /^#\s+.+\n/.test(assistantResponse)) {
          extractedContent = assistantResponse.trim();
        }
        
        // Pattern 4: Find H1 heading after a preamble sentence (e.g., "I fixed the title.\n\n# Article Title")
        if (!extractedContent) {
          const h1InTextMatch = assistantResponse.match(/\n\n(#\s+.+[\s\S]*)/);
          if (h1InTextMatch) {
            extractedContent = h1InTextMatch[1].trim();
          }
        }
        
        if (extractedContent && extractedContent.length > 200) {
          setEditedContent(extractedContent);
        }
      }
    } catch (error) {
      logger.error('[ArticleReview] AI chat error:', error);
      const errorMessage: ChatMessage = {
        role: 'assistant',
        content: 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
      };
      setChatMessages(prev => [...prev, errorMessage]);
    } finally {
      setChatLoading(false);
    }
  };

  const handleApplyEdits = async () => {
    if (!editedContent) return;
    await onUpdateContent(editedContent);
    setEditedContent(null);
    setChatMessages(prev => [...prev, {
      role: 'assistant',
      content: '✅ Changes applied to the article!',
      timestamp: new Date(),
    }]);
  };

  const handleDiscardEdits = () => {
    setEditedContent(null);
    setChatMessages(prev => [...prev, {
      role: 'assistant',
      content: 'Changes discarded. The original content has been restored.',
      timestamp: new Date(),
    }]);
  };

  const handleCopyContent = async () => {
    await navigator.clipboard.writeText(content);
    setCopySuccess(true);
    setTimeout(() => setCopySuccess(false), 2000);
  };

  const quickPrompts = [
    'What issues do you see with this article?',
    'Fix the title redundancy (remove duplicate course name)',
    'Improve the meta description for SEO',
    'Check for factual accuracy',
    'Make the content more engaging',
  ];

  // Extract markdown content from an AI message
  const extractContentFromMessage = (message: string): string | null => {
    // Try code block first
    const codeBlockMatch = message.match(/```(?:markdown)?\s*\n([\s\S]+?)\n```/);
    if (codeBlockMatch) {
      return codeBlockMatch[1].trim();
    }
    
    // Try after header phrase - allow zero or more newlines after colon
    const afterHeaderMatch = message.match(/(?:here'?s?|here is) the (?:corrected|updated|revised|fixed|edited|new) (?:article|content|version):?\s*([\s\S]+)/i);
    if (afterHeaderMatch) {
      let extracted = afterHeaderMatch[1].trim();
      // If the extraction doesn't start with # but has a title-like first line, convert to H1
      if (!/^#\s/.test(extracted)) {
        const firstLineMatch = extracted.match(/^(.+?)(?:\n\n|\n(?=[A-Z]))/);
        if (firstLineMatch && firstLineMatch[1].length < 100) {
          extracted = `# ${firstLineMatch[1].trim()}\n\n${extracted.slice(firstLineMatch[0].length).trim()}`;
        }
      }
      return extracted;
    }
    
    // If starts with H1 heading, it's likely the full article
    if (/^#\s+.+\n/.test(message)) {
      return message.trim();
    }
    
    // Find H1 heading after a preamble sentence (e.g., "I fixed the title.\n\n# Article Title")
    const h1InTextMatch = message.match(/\n\n(#\s+.+[\s\S]*)/);
    if (h1InTextMatch) {
      return h1InTextMatch[1].trim();
    }
    
    return null;
  };

  // Check if a message looks like it contains article content
  const messageHasExtractableContent = (message: string): boolean => {
    // Show button if message contains article-like content phrases
    const hasArticlePhrase = /(?:here'?s?|here is) the (?:corrected|updated|revised|fixed|edited|new)/i.test(message);
    const hasMarkdownHeading = /^#\s+.+/m.test(message);
    const hasCodeBlock = /```(?:markdown)?/.test(message);
    
    // Lower threshold - if it has article phrases, show button even for shorter messages
    if (hasArticlePhrase || hasCodeBlock) {
      return message.length > 200;
    }
    // For messages with just headings, require more content
    if (hasMarkdownHeading) {
      return message.length > 400;
    }
    return false;
  };

  const handleExtractFromMessage = (message: string) => {
    const extracted = extractContentFromMessage(message);
    if (extracted && extracted.length > 200) {
      setEditedContent(extracted);
    } else {
      // If extraction failed, just use the whole message (user can edit manually)
      setEditedContent(message);
    }
  };

  return (
    <div className="flex gap-6">
      {/* Main Content */}
      <div className={`flex-1 min-w-0 ${showChat ? 'max-w-[60%]' : ''}`}>
        {/* Back & Actions */}
        <div className="flex items-center justify-between mb-6">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
            Back to list
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowChat(!showChat)}
              className={`px-3 py-1.5 text-sm rounded-lg flex items-center gap-1.5 transition-colors ${
                showChat 
                  ? 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400'
                  : 'text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-700'
              }`}
            >
              <Sparkles className="w-4 h-4" />
              AI Review
            </button>
            <button
              onClick={handleCopyContent}
              className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white flex items-center gap-1.5"
            >
              {copySuccess ? <CheckCircle className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
              {copySuccess ? 'Copied!' : 'Copy'}
            </button>
            <button
              onClick={() => setShowRaw(!showRaw)}
              className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
              disabled={isEditing}
            >
              {showRaw ? 'Preview' : 'Raw Markdown'}
            </button>
            {article.status === 'review' && (
              <button
                onClick={() => {
                  setIsEditing(true);
                  setEditDraft(content);
                }}
                className="px-3 py-1.5 text-sm text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 flex items-center gap-1.5 font-medium"
                disabled={isEditing}
              >
                <FileEdit className="w-4 h-4" />
                Edit
              </button>
            )}
          
            {article.status === 'review' && !isEditing && (
              <>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onRegenerate}
                  leftIcon={RefreshCw}
                  disabled={loading}
                >
                  Regenerate
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onReject}
                  leftIcon={X}
                  disabled={loading}
                  className="text-red-600 hover:text-red-700 dark:text-red-400"
                >
                  Reject
                </Button>
                <Button
                  variant="primary"
                  size="sm"
                  onClick={onApprove}
                  leftIcon={Check}
                  loading={loading}
                >
                  Queue for Publish
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onPublishNow}
                  leftIcon={Send}
                  disabled={loading}
                  title="Publish immediately (bypasses queue)"
                >
                  Publish Now
                </Button>
              </>
            )}
          
            {article.status === 'published' && (
              <a
                href={`/blog/${article.slug}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors"
              >
                View Live <ExternalLink className="w-4 h-4" />
              </a>
            )}

            {(article.status === 'rejected' || article.status === 'brief') && (
              <Button
                variant="ghost"
                size="sm"
                onClick={onDelete}
                leftIcon={Trash2}
                disabled={loading}
                className="text-red-600 hover:text-red-700 dark:text-red-400"
              >
                Delete
              </Button>
            )}
          </div>
        </div>

        {/* Pending Edits Banner */}
        {editedContent && (
          <div className="mb-4 p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg flex items-center justify-between">
            <div className="flex items-center gap-2 text-amber-700 dark:text-amber-400">
              <Sparkles className="w-4 h-4" />
              <span className="text-sm font-medium">AI has suggested edits for this article</span>
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDiscardEdits}
              >
                Discard
              </Button>
              <Button
                variant="primary"
                size="sm"
                onClick={handleApplyEdits}
                leftIcon={Check}
              >
                Apply Changes
              </Button>
            </div>
          </div>
        )}

        {/* Article Metadata */}
        <Card className="p-4 mb-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div>
              <div className="text-gray-500 dark:text-gray-400">Status</div>
              <div className={`font-medium ${
                article.status === 'review' ? 'text-amber-600' :
                article.status === 'published' ? 'text-green-600' :
                article.status === 'rejected' ? 'text-red-600' : 'text-gray-600'
              }`}>
                {article.status.charAt(0).toUpperCase() + article.status.slice(1)}
              </div>
            </div>
            <div>
              <div className="text-gray-500 dark:text-gray-400">Exam</div>
              <div className="font-medium text-gray-900 dark:text-white uppercase">{article.courseId}</div>
            </div>
            <div>
              <div className="text-gray-500 dark:text-gray-400">Type</div>
              <div className="font-medium text-gray-900 dark:text-white capitalize">{article.contentType?.replace(/-/g, ' ')}</div>
            </div>
            <div>
              <div className="text-gray-500 dark:text-gray-400">Words</div>
              <div className="font-medium text-gray-900 dark:text-white">{article.wordCount?.toLocaleString() || '—'}</div>
            </div>
          </div>
          {article.metaDescription && (
            <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
              <div className="text-xs text-gray-500 dark:text-gray-400 mb-1">Meta Description</div>
              <div className="text-sm text-gray-700 dark:text-gray-300">{article.metaDescription}</div>
            </div>
          )}
          <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
            <div className="text-xs text-gray-500 dark:text-gray-400 mb-1">URL Slug</div>
            <div className="text-sm font-mono text-blue-600 dark:text-blue-400">/blog/{article.slug}</div>
          </div>
        </Card>

        {/* Content Preview */}
        <Card className="p-6">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 pb-4 border-b border-gray-200 dark:border-gray-700">
            {article.title}
          </h1>
        
          {isEditing ? (
            <div className="space-y-3">
              <textarea
                value={editDraft}
                onChange={(e) => setEditDraft(e.target.value)}
                className="w-full h-[600px] font-mono text-sm p-4 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-y"
                placeholder="Edit the article content in Markdown..."
              />
              <div className="flex items-center justify-end gap-3">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setIsEditing(false);
                    setEditDraft('');
                  }}
                >
                  Cancel
                </Button>
                <Button
                  variant="primary"
                  size="sm"
                  onClick={async () => {
                    await onUpdateContent(editDraft);
                    setIsEditing(false);
                    setEditDraft('');
                  }}
                  leftIcon={Check}
                  loading={loading}
                >
                  Save Changes
                </Button>
              </div>
            </div>
          ) : showRaw ? (
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-700 dark:text-gray-300 bg-gray-50 dark:bg-gray-800 p-4 rounded-lg overflow-x-auto">
              {content}
            </pre>
          ) : (
            <div className="prose prose-lg prose-slate dark:prose-invert max-w-none
              prose-headings:font-bold prose-headings:tracking-tight
              prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-4
              prose-h3:text-lg prose-h3:mt-6 prose-h3:mb-3
              prose-p:leading-relaxed prose-p:text-gray-700 dark:prose-p:text-gray-300
              prose-a:text-blue-600 dark:prose-a:text-blue-400 prose-a:font-medium
              prose-li:text-gray-700 dark:prose-li:text-gray-300
              prose-strong:text-gray-900 dark:prose-strong:text-white"
            >
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {content}
              </ReactMarkdown>
            </div>
          )}
        </Card>
      </div>

      {/* AI Chat Sidebar */}
      {showChat && (
        <div className="w-[400px] flex-shrink-0">
          <Card className="sticky top-6 flex flex-col h-[calc(100vh-120px)]">
            {/* Chat Header */}
            <div className="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-purple-500" />
                <h3 className="font-semibold text-gray-900 dark:text-white">AI Review Assistant</h3>
              </div>
              <button
                onClick={() => setShowChat(false)}
                className="p-1 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 rounded"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {chatMessages.length === 0 ? (
                <div className="text-center py-8">
                  <MessageSquare className="w-10 h-10 text-gray-300 dark:text-gray-600 mx-auto mb-3" />
                  <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
                    Ask questions about this article or request edits
                  </p>
                  {/* Quick Prompts */}
                  <div className="space-y-2">
                    {quickPrompts.map((prompt, i) => (
                      <button
                        key={i}
                        onClick={() => {
                          setChatInput(prompt);
                          setTimeout(handleSendMessage, 0);
                        }}
                        className="block w-full text-left px-3 py-2 text-sm bg-gray-50 dark:bg-gray-800 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 transition-colors"
                      >
                        {prompt}
                      </button>
                    ))}
                  </div>
                </div>
              ) : (
                chatMessages.map((msg, i) => (
                  <div
                    key={i}
                    className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div
                      className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${
                        msg.role === 'user'
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-gray-100'
                      }`}
                    >
                      <div className="prose prose-sm dark:prose-invert max-w-none prose-p:my-1 prose-ul:my-1 prose-li:my-0">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                          {msg.content}
                        </ReactMarkdown>
                      </div>
                      {/* Show "Use This Content" button for AI messages with article content */}
                      {msg.role === 'assistant' && messageHasExtractableContent(msg.content) && (
                        <button
                          onClick={() => handleExtractFromMessage(msg.content)}
                          className="mt-2 flex items-center gap-1.5 px-2 py-1 text-xs font-medium bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 rounded hover:bg-purple-200 dark:hover:bg-purple-900/50 transition-colors"
                        >
                          <Sparkles className="w-3 h-3" />
                          Use This Content
                        </button>
                      )}
                    </div>
                  </div>
                ))
              )}
              {chatLoading && (
                <div className="flex justify-start">
                  <div className="bg-gray-100 dark:bg-gray-800 rounded-lg px-4 py-2">
                    <div className="flex items-center gap-2">
                      <div className="animate-spin rounded-full h-4 w-4 border-2 border-gray-300 border-t-purple-500" />
                      <span className="text-sm text-gray-500">Thinking...</span>
                    </div>
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Chat Input */}
            <div className="p-4 border-t border-gray-200 dark:border-gray-700">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSendMessage()}
                  placeholder="Ask about the article..."
                  className="flex-1 px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  disabled={chatLoading}
                />
                <button
                  onClick={handleSendMessage}
                  disabled={!chatInput.trim() || chatLoading}
                  className="px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
}
