"""
Course Factory Templates & Auto-Registration

Template generators produce TypeScript source code for per-course files.
Auto-registration helpers modify existing source files to wire in the new course.
"""

import re
import json
from pathlib import Path


# =============================================================================
# TEMPLATE GENERATORS — produce TypeScript source code strings
# =============================================================================

def tpl_lessons_index(job: dict) -> str:
    """Generate src/data/{course}/lessons/index.ts template."""
    bp = job['blueprint']
    course_id = job['courseId']
    exam = job['examName']
    sections = bp['sections']

    imports = []
    exports_per = []
    spread = []

    for s in sections:
        sec_key = s['id'].lower().replace('-', '')
        var_name = f"{course_id}{sec_key.capitalize()}Lessons"
        imports.append(f"import {sec_key}Data from './json/{sec_key}-batch1.json';")
        exports_per.append(f"export const {var_name}: Lesson[] = {sec_key}Data as Lesson[];")
        exports_per.append(f"export const get{sec_key.upper()}Lessons = () => {var_name};")
        exports_per.append(f"export const get{sec_key.upper()}LessonCount = () => {var_name}.length;")
        spread.append(f"  ...{var_name},")

    return f"""// {exam} Lessons Index — Auto-generated by Course Factory
import type {{ Lesson }} from '../../../types';

{chr(10).join(imports)}

{chr(10).join(exports_per)}

export const all{exam}Lessons: Lesson[] = [
{chr(10).join(spread)}
];

export const get{exam}LessonById = (id: string): Lesson | undefined =>
  all{exam}Lessons.find(lesson => lesson.id === id);

export const get{exam}LessonsBySection = (section: string): Lesson[] =>
  all{exam}Lessons.filter(lesson => lesson.section === section);

export const get{exam}LessonCount = () => ({{
  total: all{exam}Lessons.length,
{chr(10).join(f"  {s['id']}: get{s['id'].lower().replace('-', '').upper()}LessonCount()," for s in sections)}
}});

export default all{exam}Lessons;
"""


def tpl_data_index(job: dict) -> str:
    """Generate src/data/{course}/index.ts — COURSE_DATA export for courseDataLoader."""
    bp = job['blueprint']
    exam = job['examName']
    course_id = job['courseId']

    return f"""/**
 * {exam} Course Data Index
 * {bp.get('fullName', exam)}
 * Auto-generated by Course Factory
 */
import type {{ CourseData }} from '../../types/courseData';
import type {{ CourseId }} from '../../types/course';
import {{ {exam}_QUESTIONS }} from './questions';
import {{ {exam}_FLASHCARDS }} from './flashcards';
import {{ all{exam}Lessons }} from './lessons';

/** Standard course data export — required by courseDataLoader */
export const COURSE_DATA: CourseData = {{
  courseId: '{course_id}' as CourseId,
  questions: {exam}_QUESTIONS,
  flashcards: {exam}_FLASHCARDS,
  lessons: all{exam}Lessons,
}};

export default COURSE_DATA;
"""


def tpl_courses_barrel(job: dict) -> str:
    """Generate src/courses/{course}/index.ts barrel file."""
    exam = job['examName']
    return f"""/**
 * {exam} Course Module
 * Auto-generated by Course Factory
 */
export {{
  {exam}_COURSE,
  {exam}_SECTION_CONFIG,
  default as {exam}CourseConfig,
}} from './config';

export type {{ {exam}SectionId, {exam}SectionConfig }} from './config';
"""


def tpl_adaptive_engine(job: dict) -> str:
    """Generate per-course adaptive engine that wraps adaptiveEngineCore."""
    bp = job['blueprint']
    exam = job['examName']
    course_id = job['courseId']
    sections = bp['sections']

    weight_lines = []
    for s in sections:
        weight_lines.append(f"  '{s['id']}': {s.get('weight', 10)},")

    section_list = ', '.join(f"'{s['id']}'" for s in sections)
    target_qs = job['plan'].get('mcqTarget', 2500)

    return f"""/**
 * {exam} Adaptive Question Engine
 * Auto-generated by Course Factory — wraps shared adaptiveEngineCore
 */
import {{ {exam}SectionId }} from '../courses/{course_id}/config';
import {{
  type CoreAdaptiveState,
  type BaseSelectionCriteria,
  type SelectionReason,
  createEngineConfig,
  loadState,
  saveState,
  initializeState,
  recordAnswerCore,
  getQuestionsDueForReview as coreGetQuestionsDueForReview,
  getWeakSections as coreGetWeakSections,
  selectQuestionsCore,
  getPerformanceSummaryCore,
  startSessionCore,
  endSessionCore,
  syncToFirestore,
  loadStateWithFirestoreFallback,
}} from './adaptiveEngineCore';

export type {exam}AdaptiveState = CoreAdaptiveState;

export interface SelectionCriteria extends BaseSelectionCriteria {{
  sections?: {exam}SectionId[];
}}

export interface SelectedQuestion {{
  id: string;
  section: {exam}SectionId;
  difficulty: 'easy' | 'medium' | 'hard';
  selectionReason: SelectionReason;
  priority: number;
}}

const DOMAIN_WEIGHTS: Record<string, number> = {{
{chr(10).join(weight_lines)}
}};

const SECTIONS: string[] = [{section_list}];

const ENGINE_CONFIG = createEngineConfig({{
  storageKey: '{course_id}-adaptive-state',
  sections: SECTIONS,
  sectionWeights: DOMAIN_WEIGHTS,
  readinessTargetQuestions: {target_qs},
}});

let adaptiveState: {exam}AdaptiveState = loadState(ENGINE_CONFIG);

async function syncStateToCloud(): Promise<void> {{
  try {{
    const {{ auth }} = await import('../config/firebase');
    const user = auth.currentUser;
    if (user) await syncToFirestore(adaptiveState, user.uid, '{course_id}');
  }} catch {{ /* fire-and-forget */ }}
}}

export async function loadWithFirestoreFallback(): Promise<{exam}AdaptiveState> {{
  try {{
    const {{ auth }} = await import('../config/firebase');
    const user = auth.currentUser;
    if (user) {{
      adaptiveState = await loadStateWithFirestoreFallback(ENGINE_CONFIG, user.uid, '{course_id}');
      return adaptiveState;
    }}
  }} catch {{}}
  return loadState(ENGINE_CONFIG);
}}

export function initializeAdaptiveState() {{ return initializeState(ENGINE_CONFIG); }}
export function loadAdaptiveState() {{ return loadState(ENGINE_CONFIG); }}
export function saveAdaptiveState(state: {exam}AdaptiveState) {{ saveState(state, ENGINE_CONFIG.storageKey); }}
export function getAdaptiveState() {{ return adaptiveState; }}
export function getEngineConfig() {{ return ENGINE_CONFIG; }}
export function resetAdaptiveState() {{
  adaptiveState = initializeAdaptiveState();
  saveState(adaptiveState, ENGINE_CONFIG.storageKey);
}}

export function recordAnswer(
  questionId: string,
  section: {exam}SectionId,
  domain: string | undefined,
  isCorrect: boolean,
  concepts: string[] = [],
  responseTimeMs?: number,
): void {{
  adaptiveState = recordAnswerCore(adaptiveState, ENGINE_CONFIG, questionId, section, isCorrect, {{
    subSectionId: domain, concepts, responseTimeMs,
  }});
  saveState(adaptiveState, ENGINE_CONFIG.storageKey);
}}

export function getQuestionsDueForReview(): string[] {{
  return coreGetQuestionsDueForReview(adaptiveState.questionHistory);
}}

export function getWeakSections(): {exam}SectionId[] {{
  return coreGetWeakSections(adaptiveState, ENGINE_CONFIG) as {exam}SectionId[];
}}

export function selectQuestions(allQuestions: any[], criteria: SelectionCriteria): SelectedQuestion[] {{
  const coreCriteria: BaseSelectionCriteria = {{
    ...criteria,
    sections: criteria.sections as unknown as string[],
  }};
  return selectQuestionsCore(
    allQuestions, adaptiveState, ENGINE_CONFIG, coreCriteria,
    (q: any) => q.section, (q: any) => q.blueprintArea,
  ) as SelectedQuestion[];
}}

export function getPerformanceSummary() {{
  const summary = getPerformanceSummaryCore(adaptiveState, ENGINE_CONFIG);
  return {{
    ...summary,
    sectionBreakdown: summary.sectionBreakdown.map((s: any) => ({{
      section: s.section as {exam}SectionId,
      accuracy: s.accuracy,
      questionsAttempted: s.questionsAttempted,
    }})),
    weakSections: summary.weakSections as {exam}SectionId[],
    strongSections: summary.strongSections as {exam}SectionId[],
  }};
}}

export function startSession(): void {{
  adaptiveState = startSessionCore(adaptiveState);
  saveState(adaptiveState, ENGINE_CONFIG.storageKey);
}}

export function endSession() {{
  const result = endSessionCore(adaptiveState);
  adaptiveState = result.state;
  saveState(adaptiveState, ENGINE_CONFIG.storageKey);
  syncStateToCloud();
  return result.summary;
}}
"""


def tpl_progress_service(job: dict) -> str:
    """Generate per-course progress service."""
    bp = job['blueprint']
    exam = job['examName']
    course_id = job['courseId']
    sections = bp['sections']
    passing = bp.get('passingScore', 70)
    passing_max = bp.get('passingScoreMax', 100)
    passing_pct = round(passing / passing_max * 100) if passing_max else passing

    section_type = f"{exam}SectionId"
    default_sections = ""
    for s in sections:
        default_sections += f"      {s['id']}: defaultSectionProgress('{s['id']}'),\n"
    section_list_str = ', '.join(f"'{s['id']}'" for s in sections)

    return f"""/**
 * {exam} Progress Service
 * Auto-generated by Course Factory
 */
import {{ db }} from '../config/firebase';
import {{ doc, getDoc, setDoc, Timestamp }} from 'firebase/firestore';
import {{ {section_type} }} from '../courses/{course_id}/config';
import logger from '../utils/logger';

export interface {exam}SectionProgress {{
  sectionId: {section_type};
  questionsAttempted: number;
  questionsCorrect: number;
  accuracy: number;
  lessonsCompleted: number;
  totalLessons: number;
  flashcardsReviewed: number;
  examsTaken: number;
  lastStudied: Date | null;
  progressPercent: number;
  readinessScore: number;
}}

export interface {exam}OverallProgress {{
  overall: {{
    readinessScore: number;
    progressPercent: number;
    totalQuestionsAttempted: number;
    overallAccuracy: number;
    totalStudyTimeMinutes: number;
    streakDays: number;
  }};
  sections: Record<{section_type}, {exam}SectionProgress>;
  recommendations: string[];
}}

const {exam}_PASSING_PERCENT = {passing_pct};
const {exam}_SECTIONS: {section_type}[] = [{section_list_str}] as {section_type}[];

function defaultSectionProgress(sectionId: {section_type}): {exam}SectionProgress {{
  return {{
    sectionId, questionsAttempted: 0, questionsCorrect: 0, accuracy: 0,
    lessonsCompleted: 0, totalLessons: 10, flashcardsReviewed: 0,
    examsTaken: 0, lastStudied: null, progressPercent: 0, readinessScore: 0,
  }};
}}

export async function get{exam}Progress(userId: string): Promise<{exam}OverallProgress> {{
  const progress: {exam}OverallProgress = {{
    overall: {{
      readinessScore: 0, progressPercent: 0, totalQuestionsAttempted: 0,
      overallAccuracy: 0, totalStudyTimeMinutes: 0, streakDays: 0,
    }},
    sections: {{
{default_sections}    }} as Record<{section_type}, {exam}SectionProgress>,
    recommendations: [],
  }};

  try {{
    const progressRef = doc(db, 'users', userId, '{course_id}_progress', 'current');
    const snap = await getDoc(progressRef);
    if (snap.exists()) {{
      const data = snap.data();
      if (data.sections) {{
        for (const sid of {exam}_SECTIONS) {{
          if (data.sections[sid]) {{
            progress.sections[sid] = {{ ...progress.sections[sid], ...data.sections[sid] }};
          }}
        }}
      }}
      if (data.overall) progress.overall = {{ ...progress.overall, ...data.overall }};
    }}

    let total = 0, correct = 0;
    for (const sid of {exam}_SECTIONS) {{
      const s = progress.sections[sid];
      s.accuracy = s.questionsAttempted > 0 ? Math.round((s.questionsCorrect / s.questionsAttempted) * 100) : 0;
      s.progressPercent = Math.min(100, Math.round((s.questionsAttempted / 500) * 100));
      s.readinessScore = Math.round(s.accuracy * 0.6 + s.progressPercent * 0.4);
      total += s.questionsAttempted;
      correct += s.questionsCorrect;
    }}

    progress.overall.totalQuestionsAttempted = total;
    progress.overall.overallAccuracy = total > 0 ? Math.round((correct / total) * 100) : 0;
    const sectionList = Object.values(progress.sections);
    progress.overall.progressPercent = Math.round(sectionList.reduce((a: number, s: any) => a + s.progressPercent, 0) / sectionList.length);
    progress.overall.readinessScore = Math.round(sectionList.reduce((a: number, s: any) => a + s.readinessScore, 0) / sectionList.length);

    const weakest = sectionList.reduce((min: any, s: any) => s.readinessScore < min.readinessScore ? s : min);
    if (weakest.readinessScore < 60) {{
      progress.recommendations.push(`Focus on ${{weakest.sectionId}} — weakest at ${{weakest.readinessScore}}%`);
    }}
    if (progress.overall.overallAccuracy > 0 && progress.overall.overallAccuracy < {exam}_PASSING_PERCENT) {{
      progress.recommendations.push(`Improve accuracy from ${{progress.overall.overallAccuracy}}% to {passing_pct}%+`);
    }}
    if (progress.recommendations.length === 0) {{
      progress.recommendations.push(progress.overall.readinessScore >= 80
        ? 'Excellent progress! Consider taking a full practice exam.'
        : 'Keep up the consistent practice!');
    }}
    return progress;
  }} catch (error) {{
    logger.error('Error fetching {exam} progress:', error);
    throw error;
  }}
}}

export async function update{exam}SectionProgress(
  userId: string, sectionId: {section_type}, updates: Partial<{exam}SectionProgress>,
): Promise<void> {{
  try {{
    const ref = doc(db, 'users', userId, '{course_id}_progress', 'current');
    await setDoc(ref, {{ sections: {{ [sectionId]: {{ ...updates, lastStudied: Timestamp.now() }} }}, updatedAt: Timestamp.now() }}, {{ merge: true }});
  }} catch (error) {{
    logger.error('Error updating {exam} section progress:', error);
    throw error;
  }}
}}

export function get{exam}ReadinessStatus(score: number) {{
  if (score === 0) return {{ status: 'not-started' as const, text: 'Not Started', color: 'text-slate-500' }};
  if (score < 40) return {{ status: 'needs-work' as const, text: 'Needs Work', color: 'text-error-500' }};
  if (score < 60) return {{ status: 'progressing' as const, text: 'Progressing', color: 'text-warning-500' }};
  if (score < 80) return {{ status: 'almost-ready' as const, text: 'Almost Ready', color: 'text-primary-500' }};
  return {{ status: 'ready' as const, text: 'Exam Ready', color: 'text-success-500' }};
}}

export default {{ get{exam}Progress, update{exam}SectionProgress, get{exam}ReadinessStatus }};
"""


def tpl_score_predictor(job: dict) -> str:
    """Generate per-course score predictor."""
    bp = job['blueprint']
    exam = job['examName']
    course_id = job['courseId']
    sections = bp['sections']
    passing = bp.get('passingScore', 70)
    passing_max = bp.get('passingScoreMax', 100)

    weight_entries = []
    for s in sections:
        weight_entries.append(f"  '{s['id']}': {s.get('weight', 10)} / 100,")

    return f"""/**
 * {exam} Score Predictor
 * Auto-generated by Course Factory
 */
import {{ getPerformanceSummary }} from './{course_id}AdaptiveEngine';
import logger from '../utils/logger';

const SECTION_WEIGHTS: Record<string, number> = {{
{chr(10).join(weight_entries)}
}};

const PASSING_SCORE = {passing};
const MAX_SCORE = {passing_max};

export interface ScorePrediction {{
  predictedScore: number;
  maxScore: number;
  passingScore: number;
  passProbability: number;
  confidence: 'low' | 'medium' | 'high';
  sectionPredictions: {{ section: string; score: number; weight: number }}[];
}}

export function predict{exam}Score(): ScorePrediction {{
  try {{
    const perf = getPerformanceSummary();
    let totalWeighted = 0;
    const sectionPredictions: ScorePrediction['sectionPredictions'] = [];

    for (const sb of perf.sectionBreakdown) {{
      const weight = SECTION_WEIGHTS[sb.section] || (1 / perf.sectionBreakdown.length);
      const sectionScore = Math.round(sb.accuracy * MAX_SCORE / 100);
      totalWeighted += sectionScore * weight;
      sectionPredictions.push({{ section: sb.section, score: sectionScore, weight }});
    }}

    const predictedScore = Math.round(totalWeighted);
    const passProbability = Math.min(100, Math.max(0,
      predictedScore >= PASSING_SCORE ? Math.min(99, 60 + (predictedScore - PASSING_SCORE) * 2) :
      Math.max(1, 50 - (PASSING_SCORE - predictedScore) * 3)
    ));

    const totalQ = perf.totalQuestions;
    const confidence = totalQ >= 500 ? 'high' : totalQ >= 200 ? 'medium' : 'low';

    return {{ predictedScore, maxScore: MAX_SCORE, passingScore: PASSING_SCORE, passProbability, confidence, sectionPredictions }};
  }} catch (error) {{
    logger.error('{exam} score prediction failed:', error);
    return {{ predictedScore: 0, maxScore: MAX_SCORE, passingScore: PASSING_SCORE, passProbability: 0, confidence: 'low', sectionPredictions: [] }};
  }}
}}

export default {{ predict{exam}Score }};
"""


def tpl_analytics(job: dict) -> str:
    """Generate per-course analytics service."""
    bp = job['blueprint']
    exam = job['examName']
    course_id = job['courseId']
    sections = bp['sections']
    section_list = ', '.join(f"'{s['id']}'" for s in sections)

    return f"""/**
 * {exam} Analytics Service
 * Auto-generated by Course Factory — wraps shared analyticsCore
 */
import {{
  updateOverallStats,
  updateSectionMastery,
  processStudySession,
  getOverallStats,
  getSectionMastery,
}} from './analyticsCore';
import logger from '../utils/logger';

const SECTIONS = [{section_list}];

export interface {exam}QuestionAttempt {{
  questionId: string;
  section: string;
  isCorrect: boolean;
  timeSpentSeconds: number;
  difficulty: string;
  blueprintArea?: string;
}}

export async function record{exam}QuestionAttempt(userId: string, attempt: {exam}QuestionAttempt): Promise<void> {{
  try {{
    await updateOverallStats(userId, '{course_id}', {{
      questionsAttempted: 1,
      questionsCorrect: attempt.isCorrect ? 1 : 0,
      timeSpentSeconds: attempt.timeSpentSeconds,
    }});
    await updateSectionMastery(userId, '{course_id}', attempt.section, {{
      questionsAttempted: 1,
      questionsCorrect: attempt.isCorrect ? 1 : 0,
    }});
  }} catch (error) {{
    logger.error('{exam} analytics record failed:', error);
  }}
}}

export async function record{exam}StudySession(userId: string, session: {{
  startTime: Date; endTime: Date; section?: string; questionsAnswered: number; accuracy: number;
}}): Promise<void> {{
  try {{
    await processStudySession(userId, '{course_id}', session);
  }} catch (error) {{
    logger.error('{exam} study session record failed:', error);
  }}
}}

export async function get{exam}Analytics(userId: string) {{
  try {{
    const [overall, ...sectionData] = await Promise.all([
      getOverallStats(userId, '{course_id}'),
      ...SECTIONS.map(s => getSectionMastery(userId, '{course_id}', s)),
    ]);
    return {{
      overall,
      sections: Object.fromEntries(SECTIONS.map((s, i) => [s, sectionData[i]])),
    }};
  }} catch (error) {{
    logger.error('{exam} analytics fetch failed:', error);
    return {{ overall: null, sections: {{}} }};
  }}
}}

export default {{ record{exam}QuestionAttempt, record{exam}StudySession, get{exam}Analytics }};
"""


def tpl_cram_mode(job: dict) -> str:
    """Generate per-course cram mode with blueprint-derived content."""
    bp = job['blueprint']
    exam = job['examName']
    sections = bp['sections']

    topic_entries = []
    for s in sections:
        for t in s.get('topics', [])[:3]:
            safe_topic = t.replace("'", "")
            topic_entries.append(
                f"  {{ section: '{s['id']}', topic: '{safe_topic}', "
                f"weight: {s.get('weight', 10)}, priority: 'high' as const }},"
            )

    return f"""/**
 * {exam} Cram Mode
 * Auto-generated by Course Factory
 */

export interface CramTopic {{
  section: string;
  topic: string;
  weight: number;
  priority: 'high' | 'medium' | 'low';
}}

export interface CramState {{
  currentDay: number;
  totalDays: number;
  completedTopics: string[];
  weakAreas: string[];
}}

export const {exam}_HIGH_YIELD_TOPICS: CramTopic[] = [
{chr(10).join(topic_entries)}
];

export function create{exam}CramPlan(daysUntilExam: number) {{
  const totalDays = Math.min(daysUntilExam, 7);
  const topicsPerDay = Math.ceil({exam}_HIGH_YIELD_TOPICS.length / totalDays);
  const days = [];

  for (let d = 0; d < totalDays; d++) {{
    const dayTopics = {exam}_HIGH_YIELD_TOPICS.slice(d * topicsPerDay, (d + 1) * topicsPerDay);
    const focus = dayTopics.length > 0 ? dayTopics[0].section : 'Review';
    days.push({{
      day: d + 1,
      focus,
      topics: dayTopics,
      targetQuestions: Math.round(50 + (d / totalDays) * 50),
    }});
  }}

  return {{ days }};
}}

export function get{exam}CramRecommendation(weakSections: string[]): string {{
  if (weakSections.length === 0) return 'Focus on high-weight domains for maximum impact.';
  return `Priority: ${{weakSections.slice(0, 3).join(', ')}}. These need the most work.`;
}}

export default {{ {exam}_HIGH_YIELD_TOPICS, create{exam}CramPlan, get{exam}CramRecommendation }};
"""


def tpl_progress_hook(job: dict) -> str:
    """Generate per-course React progress hook."""
    exam = job['examName']
    course_id = job['courseId']

    return f"""/**
 * use{exam}Progress — React hook for {exam} progress data
 * Auto-generated by Course Factory
 */
import {{ useState, useEffect, useCallback }} from 'react';
import {{ useAuth }} from './useAuth';
import {{
  get{exam}Progress,
  type {exam}OverallProgress,
}} from '../services/{course_id}ProgressService';
import logger from '../utils/logger';

export function use{exam}Progress() {{
  const {{ user }} = useAuth();
  const [progress, setProgress] = useState<{exam}OverallProgress | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const refresh = useCallback(async () => {{
    if (!user?.uid) return;
    try {{
      setLoading(true);
      const data = await get{exam}Progress(user.uid);
      setProgress(data);
      setError(null);
    }} catch (err) {{
      logger.error('{exam} progress fetch failed:', err);
      setError(err instanceof Error ? err : new Error('Failed to load progress'));
    }} finally {{
      setLoading(false);
    }}
  }}, [user?.uid]);

  useEffect(() => {{
    refresh();
  }}, [refresh]);

  return {{ progress, loading, error, refresh }};
}}

export default use{exam}Progress;
"""


# =============================================================================
# AUTO-REGISTRATION — modify existing TypeScript source files
# =============================================================================

def auto_update_course_id_type(course_id: str) -> bool:
    """Add new courseId to the CourseId union type in src/types/course.ts."""
    filepath = Path('src/types/course.ts')
    if not filepath.exists():
        print(f"    ⚠ {filepath} not found, skipping CourseId update")
        return False

    content = filepath.read_text()

    if f"'{course_id}'" in content:
        print(f"    ✅ '{course_id}' already in CourseId type")
        return True

    # Find the CourseId type union and append
    pattern = r"(export type CourseId = [^;]+);"
    match = re.search(pattern, content)
    if match:
        old = match.group(0)
        new = old.replace(';', f" | '{course_id}';")
        content = content.replace(old, new)

        # Also update isValidCourseId array
        valid_pattern = r"return \[([^\]]+)\]\.includes\(id\);"
        valid_match = re.search(valid_pattern, content)
        if valid_match:
            old_list = valid_match.group(0)
            new_list = old_list.replace('].includes(id);', f", '{course_id}'].includes(id);")
            content = content.replace(old_list, new_list)

        filepath.write_text(content)
        print(f"    ✅ Added '{course_id}' to CourseId type")
        return True

    print(f"    ⚠ Could not find CourseId pattern in {filepath}")
    return False


def auto_update_course_registry(course_id: str, exam: str) -> bool:
    """Add import + entry to src/courses/index.ts."""
    filepath = Path('src/courses/index.ts')
    if not filepath.exists():
        return False

    content = filepath.read_text()

    if f"  {course_id}:" in content and f"{exam}_COURSE" in content:
        print(f"    ✅ '{course_id}' already in course registry")
        return True

    # Add import
    import_line = f"import {{ {exam}_COURSE }} from './{course_id}';"
    if import_line not in content:
        last_import_match = list(re.finditer(r"import .+ from '\.\/.+';", content))
        if last_import_match:
            insert_pos = last_import_match[-1].end()
            content = content[:insert_pos] + f"\n{import_line}" + content[insert_pos:]

    # Add to COURSES record
    courses_pattern = r"(} as Record<CourseId, Course>)"
    match = re.search(courses_pattern, content)
    if match:
        content = content[:match.start()] + f"  {course_id}: {exam}_COURSE,\n" + content[match.start():]

    filepath.write_text(content)
    print(f"    ✅ Added '{course_id}' to course registry")
    return True


def auto_update_content_registry(job: dict) -> bool:
    """Add section content entries + exam info to src/services/contentRegistry.ts."""
    filepath = Path('src/services/contentRegistry.ts')
    if not filepath.exists():
        return False

    content = filepath.read_text()
    bp = job['blueprint']
    course_id = job['courseId']
    exam = job['examName']
    sections = bp['sections']

    if f"courseId: '{course_id}'" in content:
        print(f"    ✅ '{course_id}' sections already in content registry")
        return True

    # Build section entries
    section_entries = []
    total_lesson_minutes = 0
    section_ids = []

    for s in sections:
        mcq_count = max(10, round(job['plan']['mcqTarget'] * s.get('weight', 10) / 100))
        lesson_count = max(2, round(job['plan']['lessonTarget'] * s.get('weight', 10) / 100))
        fc_count = max(5, round(job['plan']['flashcardTarget'] * s.get('weight', 10) / 100))
        tbs_count = max(1, round(job['plan'].get('tbsTarget', 30) * s.get('weight', 10) / 100))
        lesson_minutes = lesson_count * 45
        total_lesson_minutes += lesson_minutes
        section_ids.append(s['id'])

        safe_name = s['name'].replace("'", "\\'")
        section_entries.append(f"""  '{s['id']}': {{
    courseId: '{course_id}' as CourseId,
    section: '{s['id']}',
    sectionName: '{safe_name}',
    counts: {{
      lessons: {lesson_count},
      lessonMinutes: {lesson_minutes},
      mcqs: {mcq_count},
      tbs: {tbs_count},
      simulations: 0,
      flashcards: {fc_count},
      caseStudies: 0,
    }},
    contentTypes: ['lesson', 'mcq', 'flashcard', 'mockExam'] as ContentType[],
    blueprintWeight: {s.get('weight', 10)},
    industryHoursMin: {max(20, s.get('weight', 10) * 2)},
    industryHoursMax: {max(30, s.get('weight', 10) * 3)},
  }},""")

    # Find insertion point: before the closing of SECTION_CONTENT
    # We look for '}' followed by the type annotation
    close_pattern = r"\n}: Record<string, SectionContentInfo>"
    close_match = re.search(close_pattern, content)
    if close_match:
        insert_pos = close_match.start()
        insert_text = f"""
  // =========================================================================
  // {exam} SECTIONS ({bp.get('fullName', exam)})
  // =========================================================================
{chr(10).join(section_entries)}
"""
        content = content[:insert_pos] + insert_text + content[insert_pos:]

    # Also add to EXAM_CONTENT_INFO
    hours_min = max(100, len(sections) * 30)
    hours_max = max(200, len(sections) * 50)
    plan_mode = 'full-exam' if len(sections) > 3 else 'per-section'
    sections_str = ', '.join(f"'{sid}'" for sid in section_ids)
    safe_full_name = bp.get('fullName', exam).replace("'", "\\'")

    exam_entry = f"""  {course_id}: {{
    courseId: '{course_id}' as CourseId,
    examName: '{safe_full_name}',
    sections: [{sections_str}],
    totalContentTime: {total_lesson_minutes},
    industryTotalHours: {{ min: {hours_min}, max: {hours_max} }},
    studyPlanMode: '{plan_mode}',
  }},"""

    # Insert into EXAM_CONTENT_INFO before its closing
    exam_close_pattern = r"\n};\n\n// =+"
    exam_close_match = re.search(exam_close_pattern, content)
    if exam_close_match and f"  {course_id}:" not in content[exam_close_match.start():]:
        # Find the last exam entry position to insert after
        last_closing_brace = content.rfind("},\n};", 0, exam_close_match.start() + 5)
        if last_closing_brace > 0:
            insert_pos = last_closing_brace + 2  # After the comma
            content = content[:insert_pos] + "\n" + exam_entry + content[insert_pos:]

    filepath.write_text(content)
    print(f"    ✅ Added {len(sections)} sections to content registry")
    return True


def auto_update_question_service(job: dict) -> bool:
    print(f"    ✅ questionService now resolves routes dynamically (no update needed)")
    return True

def auto_update_adaptive_engine_adapter(job: dict) -> bool:
    print(f"    ✅ adaptiveEngineAdapter now uses dynamic imports (no update needed)")
    return True


def auto_update_exam_service(job: dict) -> bool:
    """Add exam config builder to src/services/examService.ts."""
    filepath = Path('src/services/examService.ts')
    if not filepath.exists():
        return False

    content = filepath.read_text()
    bp = job['blueprint']
    course_id = job['courseId']
    exam = job['examName']

    if f"get{exam}ExamConfig" in content:
        print(f"    ✅ '{course_id}' already in examService")
        return True

    total_questions = bp.get('totalQuestions', 150)
    time_minutes = bp.get('timeAllowedMinutes', 240)
    time_seconds = time_minutes * 60
    num_testlets = 2 if total_questions <= 100 else 3
    qs_per = total_questions // num_testlets
    time_per = time_seconds // num_testlets
    safe_name = bp.get('fullName', exam).replace("'", "\\'")

    testlets = ', '.join(
        f"{{ type: 'mcq' as const, questions: {qs_per}, time: {time_per} }}"
        for _ in range(num_testlets)
    )

    builder_fn = f"""
// {exam} Exam Configuration ({safe_name})
function get{exam}ExamConfig(_sectionId: string, passingScore: number): ExamConfig {{
  return {{
    testlets: [{testlets}],
    totalTime: {time_seconds},
    passingScore,
    description: '{safe_name}',
  }};
}}

"""

    # Insert the function before examConfigBuilders
    marker = "const examConfigBuilders"
    if marker in content:
        content = content.replace(marker, builder_fn + marker)

    # Add to examConfigBuilders record
    builder_entry = f"  {course_id}: get{exam}ExamConfig,"
    closing = "};\n\n/**\n * Load TBS"
    if closing in content and f"  {course_id}:" not in content:
        content = content.replace(closing, builder_entry + "\n" + closing)

    filepath.write_text(content)
    print(f"    ✅ Added '{course_id}' exam config builder")
    return True
