#!/bin/bash
# Setup script for Daily CPA SMS - Configure Telnyx credentials

echo ""
echo "=========================================="
echo "Daily CPA SMS - Telnyx Setup"
echo "=========================================="
echo ""
echo "To enable SMS delivery, you need to configure Telnyx credentials"
echo "in Firebase Cloud Functions."
echo ""
echo "Step 1: Get your Telnyx credentials"
echo "  • Go to https://portal.telnyx.com/#/app/api-keys"
echo "  • Copy your API Key"
echo "  • Go to https://portal.telnyx.com/#/app/sms"
echo "  • Note your Messaging Profile phone number (e.g., +1234567890)"
echo ""
echo "Step 2: Set Firebase secrets (requires Firebase CLI)"
echo ""
echo "  firebase functions:secrets:set TELNYX_API_KEY --project=passcpa"
echo "  # Then paste your API key and press Enter"
echo ""
echo "  firebase functions:secrets:set TELNYX_PHONE_NUMBER --project=passcpa"
echo "  # Then paste your phone number and press Enter"
echo ""
echo "Step 3: Deploy Cloud Functions"
echo ""
echo "  firebase deploy --only functions --project=passcpa"
echo ""
echo "Step 4: Verify deployment"
echo ""
echo "  firebase functions:list --project=passcpa"
echo ""
echo "=========================================="
echo ""
echo "Current status:"
firebase functions:log --limit 10 2>/dev/null | grep -i telnyx || echo "  (no recent Telnyx-related logs)"
echo ""
