
import os
import json

# Data based on user's aligned Blueprint 2026
# I will put the data here.

lessons_data = {
    "PREP": [
        ("PREP-001", "CPA Evolution 2026: Your Complete Roadmap", 45, "beginner", ["Exam Structure", "CPA Evolution"], "3 Core + 1 Discipline, 30-month window"),
        ("PREP-002", "Anatomy of the Exam: Testlets, Timing, Scoring", 45, "beginner", ["Exam Structure", "Timing"], "Exam structure by section"),
        ("PREP-003", "Adaptive Testing: What It Means for You", 35, "beginner", ["Adaptive Testing", "MCQ"], "MCQ difficulty changes"),
        ("PREP-004", "How the CPA Exam is Scored", 40, "beginner", ["Scoring"], "Raw to scaled scores"),
        ("PREP-005", "Strategic Section Order", 35, "beginner", ["Strategy", "Planning"], "FAR first? Planning your path"),
        ("PREP-006", "The 90-Second Rule: MCQ Time Management", 30, "intermediate", ["Strategy", "MCQ"], "Don't get stuck"),
        ("PREP-007", "Reading MCQs Effectively", 25, "intermediate", ["Strategy", "MCQ"], "Stem first or options first"),
        ("PREP-008", "Process of Elimination (POE)", 35, "intermediate", ["Strategy", "MCQ"], "Eliminating wrong answers"),
        ("PREP-009", "Recognizing Distractor Patterns", 40, "intermediate", ["Strategy", "MCQ"], "How test writers trick you"),
        ("PREP-010", "Calculation MCQs: Set Up First", 35, "intermediate", ["Strategy", "MCQ"], "Avoiding traps"),
        ("PREP-011", "The \"I Have No Idea\" Protocol", 25, "intermediate", ["Strategy", "Guessing"], "When completely stumped"),
        ("PREP-012", "TBS Overview: Types & Weighting", 35, "intermediate", ["Strategy", "TBS"], "50% of your score"),
        ("PREP-013", "TBS Time Management: 15-Minute Rule", 30, "intermediate", ["Strategy", "TBS"], "When to move on"),
        ("PREP-014", "Research TBS: Guaranteed Points", 40, "intermediate", ["Strategy", "TBS"], "Codification navigation"),
        ("PREP-015", "Document Review TBS", 45, "intermediate", ["Strategy", "TBS"], "Finding facts in exhibits"),
        ("PREP-016", "Journal Entry TBS", 40, "intermediate", ["Strategy", "TBS"], "Dr/Cr under pressure"),
        ("PREP-017", "Spreadsheet TBS: Excel for CPAs", 45, "intermediate", ["Strategy", "TBS"], "Formulas that work"),
        ("PREP-018", "Written Communication: What Graders Want", 35, "intermediate", ["Strategy", "WC"], "The rubric revealed"),
        ("PREP-019", "IRAC Method for Tax Memos", 40, "intermediate", ["Strategy", "WC"], "Issue, Rule, Analysis, Conclusion"),
        ("PREP-020", "Common WC Mistakes", 30, "intermediate", ["Strategy", "WC"], "Don't lose easy points"),
        ("PREP-021", "Building Your Study Schedule", 45, "beginner", ["Strategy", "Planning"], "Hours by section"),
        ("PREP-022", "Active vs Passive Studying", 35, "beginner", ["Strategy", "Habits"], "70% practice, 30% learning"),
        ("PREP-023", "Final Review: Last 2 Weeks", 40, "advanced", ["Strategy", "Review"], "The home stretch"),
        ("PREP-024", "Test Day Protocol", 35, "beginner", ["Logistics"], "Morning to score release"),
        ("PREP-025", "Managing Test Anxiety", 40, "beginner", ["Mental Game"], "Mental strategies")
    ],
    "FAR": [
        ("FAR-I-001", "FASB Conceptual Framework: Foundation of GAAP", 45, "intermediate", ["Conceptual Framework"], "FAR-I-A-1, FAR-I-A-2, FAR-I-A-3"),
        ("FAR-I-002", "Financial Statements: Components & Presentation", 55, "intermediate", ["Financial Statements"], "FAR-I-A-1"),
        ("FAR-I-003", "GAAP Hierarchy & Standard-Setting Process", 40, "intermediate", ["GAAP Hierarchy"], "FAR-I-B-1"),
        ("FAR-I-004", "SEC Reporting: 10-K, 10-Q, 8-K", 45, "intermediate", ["SEC Reporting"], "FAR-I-B-2"),
        ("FAR-I-005", "GAAP vs IFRS: Key Differences", 50, "intermediate", ["IFRS"], "FAR-I-B-1"),
        ("FAR-II-001", "Cash & Cash Equivalents: Recognition & Measurement", 35, "intermediate", ["Assets", "Cash"], "FAR-II-A-1, FAR-II-A-2"),
        ("FAR-II-002", "Bank Reconciliations: The Complete Process", 40, "intermediate", ["Assets", "Cash"], "FAR-II-A-1"),
        ("FAR-II-003", "Accounts Receivable & Allowance Methods", 50, "intermediate", ["Assets", "Receivables"], "FAR-II-B-1, FAR-II-B-2"),
        ("FAR-II-004", "CECL: Current Expected Credit Losses (ASU 2016-13)", 60, "advanced", ["Assets", "CECL"], "FAR-II-B-2"),
        ("FAR-II-005", "Notes Receivable & Impairment", 45, "intermediate", ["Assets", "Receivables"], "FAR-II-B-3"),
        ("FAR-II-006", "Factoring, Pledging & Transfers of Receivables", 50, "advanced", ["Assets", "Receivables"], "FAR-II-B-4"),
        ("FAR-II-007", "Inventory Cost Flow: FIFO, LIFO, Weighted Average", 55, "intermediate", ["Assets", "Inventory"], "FAR-II-C-1"),
        ("FAR-II-008", "Lower of Cost or Net Realizable Value", 45, "intermediate", ["Assets", "Inventory"], "FAR-II-C-2"),
        ("FAR-II-009", "Dollar-Value LIFO", 70, "advanced", ["Assets", "Inventory"], "FAR-II-C-3"),
        ("FAR-II-010", "Inventory Errors & Period Corrections", 40, "intermediate", ["Assets", "Inventory"], "FAR-II-C-1"),
        ("FAR-II-011", "PP&E Acquisition & Capitalization", 50, "intermediate", ["Assets", "PPE"], "FAR-II-D-1"),
        ("FAR-II-012", "Depreciation Methods: SL, DDB, Units, SYD", 55, "intermediate", ["Assets", "PPE"], "FAR-II-D-2"),
        ("FAR-II-013", "Asset Impairment: Long-Lived Assets", 55, "advanced", ["Assets", "PPE"], "FAR-II-D-3"),
        ("FAR-II-014", "Disposals & Nonmonetary Exchanges", 50, "advanced", ["Assets", "PPE"], "FAR-II-D-4"),
        ("FAR-II-015", "Debt Securities: HTM, AFS, Trading", 60, "intermediate", ["Assets", "Investments"], "FAR-II-E-1"),
        ("FAR-II-016", "Equity Securities: Fair Value Measurement", 50, "intermediate", ["Assets", "Investments"], "FAR-II-E-2"),
        ("FAR-II-017", "Equity Method Investments", 65, "advanced", ["Assets", "Investments"], "FAR-II-E-3"),
        ("FAR-II-018", "Fair Value Hierarchy: Levels 1, 2, 3", 45, "intermediate", ["Measurements"], "FAR-II-E-4"),
        ("FAR-II-019", "Intangible Assets: R&D & Software Costs", 50, "intermediate", ["Assets", "Intangibles"], "FAR-II-F-1"),
        ("FAR-II-020", "Acquired Intangibles & Amortization", 45, "intermediate", ["Assets", "Intangibles"], "FAR-II-F-2"),
        ("FAR-II-021", "Goodwill Impairment Testing", 55, "advanced", ["Assets", "Intangibles"], "FAR-II-F-3"),
        ("FAR-II-022", "Accounts Payable & Accrued Liabilities", 35, "intermediate", ["Liabilities"], "FAR-II-G-1, FAR-II-G-2"),
        ("FAR-II-023", "Asset Retirement Obligations", 50, "advanced", ["Liabilities"], "FAR-II-G-3"),
        ("FAR-II-024", "Notes Payable & Interest", 40, "intermediate", ["Liabilities"], "FAR-II-H-1"),
        ("FAR-II-025", "Bonds Payable: Issuance, Premium, Discount", 65, "intermediate", ["Liabilities", "Bonds"], "FAR-II-H-2"),
        ("FAR-II-026", "Debt Modifications & Extinguishments", 55, "advanced", ["Liabilities", "Bonds"], "FAR-II-H-3"),
        ("FAR-II-027", "Stock Issuances: Common & Preferred", 45, "intermediate", ["Equity"], "FAR-II-I-1"),
        ("FAR-II-028", "Treasury Stock: Cost & Par Value Methods", 40, "intermediate", ["Equity"], "FAR-II-I-2"),
        ("FAR-II-029", "Dividends: Cash, Property, Stock, Liquidating", 50, "intermediate", ["Equity"], "FAR-II-I-3"),
        ("FAR-II-030", "Stock Compensation: Options, RSUs, ESPPs", 60, "advanced", ["Equity"], "FAR-II-I-4"),
        ("FAR-III-001", "ASC 606: Five-Step Revenue Model", 75, "advanced", ["Revenue Recognition"], "FAR-III-A-1"),
        ("FAR-III-002", "Identifying Performance Obligations", 50, "intermediate", ["Revenue Recognition"], "FAR-III-A-2"),
        ("FAR-III-003", "Variable Consideration & Constraints", 55, "advanced", ["Revenue Recognition"], "FAR-III-A-3"),
        ("FAR-III-004", "Contract Costs: Obtain & Fulfill", 45, "intermediate", ["Revenue Recognition"], "FAR-III-A-4"),
        ("FAR-III-005", "ASC 842: Lease Classification", 60, "intermediate", ["Leases"], "FAR-III-B-1"),
        ("FAR-III-006", "Lessee Accounting: Finance & Operating", 65, "advanced", ["Leases"], "FAR-III-B-2"),
        ("FAR-III-007", "Lessor Accounting: Sales-Type, Direct, Operating", 60, "advanced", ["Leases"], "FAR-III-B-3"),
        ("FAR-III-008", "Sale-Leaseback Transactions", 50, "advanced", ["Leases"], "FAR-III-B-4"),
        ("FAR-III-009", "ASC 740: Deferred Taxes Overview", 70, "advanced", ["Income Taxes"], "FAR-III-C-1"),
        ("FAR-III-010", "Temporary vs Permanent Differences", 50, "intermediate", ["Income Taxes"], "FAR-III-C-1"),
        ("FAR-III-011", "Valuation Allowance & DTA Realization", 55, "advanced", ["Income Taxes"], "FAR-III-C-2"),
        ("FAR-III-012", "Uncertain Tax Positions (FIN 48)", 50, "advanced", ["Income Taxes"], "FAR-III-C-3"),
        ("FAR-III-013", "Defined Benefit Pensions: Expense Components", 75, "advanced", ["Pensions"], "FAR-III-D-1, FAR-III-D-2"),
        ("FAR-III-014", "OPEB: Other Post-Employment Benefits", 50, "advanced", ["Pensions"], "FAR-III-D-3"),
        ("FAR-III-015", "Contingencies & Commitments", 45, "intermediate", ["Contingencies"], "FAR-III-E-1, FAR-III-E-2, FAR-III-E-3"),
        ("FAR-III-016", "Earnings Per Share: Basic & Diluted", 55, "advanced", ["EPS"], "FAR-III-F-1, FAR-III-F-2, FAR-III-F-3"),
        ("FAR-III-017", "Statement of Cash Flows", 60, "intermediate", ["Cash Flows"], "FAR-III-A (related)"),
        ("FAR-IV-001", "Government Accounting: Measurement Focus & Basis", 55, "intermediate", ["Governmental"], "FAR-IV-A-1"),
        ("FAR-IV-002", "Fund Accounting: Types & Purposes", 60, "intermediate", ["Governmental"], "FAR-IV-A-2"),
        ("FAR-IV-003", "Budgetary Accounting & Encumbrances", 50, "intermediate", ["Governmental"], "FAR-IV-A-3"),
        ("FAR-IV-004", "Government-Wide: Statement of Net Position", 55, "intermediate", ["Governmental"], "FAR-IV-B-1"),
        ("FAR-IV-005", "Government-Wide: Statement of Activities", 50, "intermediate", ["Governmental"], "FAR-IV-B-2"),
        ("FAR-IV-006", "Governmental Fund Financial Statements", 60, "intermediate", ["Governmental"], "FAR-IV-C-1"),
        ("FAR-IV-007", "Proprietary Fund Financial Statements", 50, "intermediate", ["Governmental"], "FAR-IV-C-2"),
        ("FAR-IV-008", "Fiduciary Fund Financial Statements", 45, "intermediate", ["Governmental"], "FAR-IV-C-3"),
        ("FAR-V-001", "NFP Statement of Financial Position", 45, "intermediate", ["Not-for-Profit"], "FAR-V-A-1"),
        ("FAR-V-002", "NFP Statement of Activities", 50, "intermediate", ["Not-for-Profit"], "FAR-V-A-2"),
        ("FAR-V-003", "NFP Statement of Cash Flows", 40, "intermediate", ["Not-for-Profit"], "FAR-V-A-3"),
        ("FAR-V-004", "Contributions, Pledges & Net Assets", 55, "intermediate", ["Not-for-Profit"], "FAR-V-B-1, FAR-V-B-2"),
        ("FAR-V-005", "Split-Interest Agreements", 45, "advanced", ["Not-for-Profit"], "FAR-V-B-3")
    ],
    "AUD": [
        ("AUD-I-001", "Nature & Scope of Audit Engagements", 45, "beginner", ["Engagements"], "AUD-I-A-1, AUD-I-A-2, AUD-I-A-3"),
        ("AUD-I-002", "AICPA Code of Professional Conduct", 55, "intermediate", ["Ethics"], "AUD-I-B-1"),
        ("AUD-I-003", "Independence: Conceptual Framework", 50, "intermediate", ["Ethics", "Independence"], "AUD-I-B-2"),
        ("AUD-I-004", "SEC & PCAOB Independence Rules", 55, "intermediate", ["Ethics", "Independence"], "AUD-I-B-3"),
        ("AUD-I-005", "Conflicts of Interest & Threats", 45, "intermediate", ["Ethics"], "AUD-I-B-4"),
        ("AUD-I-006", "Engagement Letters & Acceptance", 40, "intermediate", ["Planning"], "AUD-I-C-1"),
        ("AUD-I-007", "Communications with Governance", 50, "intermediate", ["Communication"], "AUD-I-C-2"),
        ("AUD-I-008", "Quality Management Standards (SQMS)", 55, "advanced", ["Quality Control"], "AUD-I-A-2"),
        ("AUD-I-009", "Professional Skepticism & Judgment", 40, "beginner", ["Concepts"], "AUD-I-B-1"),
        ("AUD-I-010", "Documentation Requirements", 45, "intermediate", ["Documentation"], "AUD-I-A-1"),
        ("AUD-II-001", "Preliminary Engagement Activities", 40, "intermediate", ["Planning"], "AUD-II-A-1"),
        ("AUD-II-002", "Materiality: Planning & Performance", 55, "intermediate", ["Planning", "Materiality"], "AUD-II-A-2"),
        ("AUD-II-003", "Audit Risk Model: AR = IR × CR × DR", 60, "advanced", ["Risk Assessment"], "AUD-II-A-3"),
        ("AUD-II-004", "Understanding the Entity: Industry Factors", 50, "intermediate", ["Risk Assessment"], "AUD-II-B-1"),
        ("AUD-II-005", "Business Operations & Strategy", 45, "intermediate", ["Risk Assessment"], "AUD-II-B-2"),
        ("AUD-II-006", "Financial Performance Measures", 40, "intermediate", ["Risk Assessment"], "AUD-II-B-3"),
        ("AUD-II-007", "Internal Control: COSO Framework", 65, "intermediate", ["Internal Control", "COSO"], "AUD-II-C-1"),
        ("AUD-II-008", "Evaluating Control Design & Implementation", 55, "advanced", ["Internal Control"], "AUD-II-C-2"),
        ("AUD-II-009", "IT Controls: General & Application", 60, "advanced", ["Internal Control", "IT"], "AUD-II-C-3"),
        ("AUD-II-010", "Identifying & Assessing RMM", 55, "advanced", ["Risk Assessment"], "AUD-II-D-1"),
        ("AUD-II-011", "Significant Risks", 45, "advanced", ["Risk Assessment"], "AUD-II-D-2"),
        ("AUD-II-012", "Fraud Risk Assessment", 60, "intermediate", ["Risk Assessment", "Fraud"], "AUD-II-D-3"),
        ("AUD-III-001", "Audit Evidence: Sufficiency & Appropriateness", 50, "intermediate", ["Evidence"], "AUD-III-A-1"),
        ("AUD-III-002", "External Confirmations", 45, "intermediate", ["Evidence"], "AUD-III-A-2"),
        ("AUD-III-003", "Analytical Procedures", 50, "intermediate", ["Evidence"], "AUD-III-A-3"),
        ("AUD-III-004", "Audit Sampling: Statistical & Non-Statistical", 65, "advanced", ["Sampling"], "AUD-III-B-1, AUD-III-B-2"),
        ("AUD-III-005", "Sample Design & Selection", 50, "advanced", ["Sampling"], "AUD-III-B-2"),
        ("AUD-III-006", "Evaluating Sample Results", 45, "advanced", ["Sampling"], "AUD-III-B-3"),
        ("AUD-III-007", "Auditing Accounting Estimates", 55, "advanced", ["Evidence"], "AUD-III-C-1"),
        ("AUD-III-008", "Related Party Transactions", 45, "intermediate", ["Evidence"], "AUD-III-C-2"),
        ("AUD-III-009", "Going Concern Evaluation", 55, "advanced", ["Reporting"], "AUD-III-C-3"),
        ("AUD-III-010", "Subsequent Events: Type I & Type II", 45, "intermediate", ["Reporting"], "AUD-III-C-4"),
        ("AUD-III-011", "Using Internal Auditors' Work", 40, "intermediate", ["Evidence"], "AUD-III-D-1"),
        ("AUD-III-012", "Component Auditors & Group Audits", 55, "advanced", ["Evidence"], "AUD-III-D-2"),
        ("AUD-III-013", "Using Specialists & Experts", 45, "intermediate", ["Evidence"], "AUD-III-D-3"),
        ("AUD-III-014", "Substantive Testing: Revenue & Receivables", 55, "intermediate", ["Testing"], "AUD-III-A"),
        ("AUD-III-015", "Substantive Testing: Inventory & PP&E", 55, "intermediate", ["Testing"], "AUD-III-A"),
        ("AUD-IV-001", "Unmodified Audit Opinion", 50, "intermediate", ["Reporting"], "AUD-IV-A-1"),
        ("AUD-IV-002", "Modified Opinions: Qualified, Adverse, Disclaimer", 60, "advanced", ["Reporting"], "AUD-IV-A-2"),
        ("AUD-IV-003", "Emphasis of Matter & Other Matter Paragraphs", 45, "intermediate", ["Reporting"], "AUD-IV-A-3"),
        ("AUD-IV-004", "Comparative Financial Statements", 40, "intermediate", ["Reporting"], "AUD-IV-A-4"),
        ("AUD-IV-005", "Key Audit Matters (KAM) / Critical Audit Matters (CAM)", 50, "advanced", ["Reporting"], "AUD-IV-A-1"),
        ("AUD-IV-006", "Attestation: Examination Engagements", 50, "average", ["Attestation"], "AUD-IV-B-1"),
        ("AUD-IV-007", "Attestation: Review Engagements", 45, "intermediate", ["Attestation"], "AUD-IV-B-2"),
        ("AUD-IV-008", "Agreed-Upon Procedures (AUP)", 40, "intermediate", ["Attestation"], "AUD-IV-B-3"),
        ("AUD-IV-009", "SSARS: Compilation Engagements", 45, "intermediate", ["SSARS"], "AUD-IV-C-1"),
        ("AUD-IV-010", "SSARS: Review Engagements", 50, "intermediate", ["SSARS"], "AUD-IV-C-2"),
        ("AUD-IV-011", "SSARS: Preparation Engagements", 35, "beginner", ["SSARS"], "AUD-IV-C-3"),
        ("AUD-IV-012", "SOC 1 & SOC 2 Reports", 55, "advanced", ["Reporting"], "AUD-IV-B (related)"),
        ("AUD-IV-013", "Single Audit & Government Auditing", 55, "advanced", ["Governmental"], "AUD-IV-B (related)")
    ],
    "REG": [
        ("REG-I-001", "Treasury Circular 230: Practice Before IRS", 55, "intermediate", ["Ethics"], "REG-I-A-1"),
        ("REG-I-002", "AICPA Statements on Standards for Tax Services", 45, "intermediate", ["Ethics"], "REG-I-A-2"),
        ("REG-I-003", "Tax Preparer Penalties", 50, "intermediate", ["Ethics"], "REG-I-A-3"),
        ("REG-I-004", "Filing Requirements & Deadlines", 40, "beginner", ["Procedures"], "REG-I-B-1"),
        ("REG-I-005", "Statute of Limitations: Assessment & Collection", 50, "intermediate", ["Procedures"], "REG-I-B-2"),
        ("REG-I-006", "IRS Audit Process & Appeals", 55, "intermediate", ["Procedures"], "REG-I-B-3"),
        ("REG-I-007", "Taxpayer Penalties: Civil & Criminal", 50, "intermediate", ["Procedures"], "REG-I-B-4"),
        ("REG-I-008", "Power of Attorney & Authorizations", 35, "intermediate", ["Procedures"], "REG-I-A-1"),
        ("REG-II-001", "Agency: Formation & Authority", 50, "intermediate", ["Business Law"], "REG-II-A-1"),
        ("REG-II-002", "Agency: Duties & Liabilities", 45, "intermediate", ["Business Law"], "REG-II-A-2"),
        ("REG-II-003", "Contracts: Formation & Enforceability", 60, "intermediate", ["Business Law"], "REG-II-B-1"),
        ("REG-II-004", "Contracts: Performance & Remedies", 55, "intermediate", ["Business Law"], "REG-II-B-2"),
        ("REG-II-005", "Contracts: Third-Party Rights", 45, "intermediate", ["Business Law"], "REG-II-B-3"),
        ("REG-II-006", "Business Structures: Overview", 50, "intermediate", ["Business Law"], "REG-II-C-1 through REG-II-C-4"),
        ("REG-II-007", "Partnerships & LLCs: Legal Aspects", 55, "intermediate", ["Business Law"], "REG-II-C-2, REG-II-C-4"),
        ("REG-II-008", "Corporations: Formation & Governance", 50, "intermediate", ["Business Law"], "REG-II-C-3"),
        ("REG-II-009", "Secured Transactions: UCC Article 9", 60, "advanced", ["Business Law"], "REG-II-D-1"),
        ("REG-II-010", "Bankruptcy: Chapters 7, 11, 13", 55, "advanced", ["Business Law"], "REG-II-D-2"),
        ("REG-III-001", "Gross Income: Inclusions", 60, "intermediate", ["Individual Tax"], "REG-III-A-1"),
        ("REG-III-002", "Gross Income: Exclusions", 55, "intermediate", ["Individual Tax"], "REG-III-A-2"),
        ("REG-III-003", "🆕 H.R. 1: Tip Income Exclusion", 40, "intermediate", ["Individual Tax", "H.R. 1"], "REG-III-A-3"),
        ("REG-III-004", "Above-the-Line Deductions", 50, "intermediate", ["Individual Tax"], "REG-III-B-1"),
        ("REG-III-005", "Standard vs Itemized Deductions", 55, "intermediate", ["Individual Tax"], "REG-III-B-2"),
        ("REG-III-006", "Qualified Business Income Deduction (199A)", 65, "advanced", ["Individual Tax"], "REG-III-B-3"),
        ("REG-III-007", "🆕 H.R. 1: SALT Deduction Changes", 45, "intermediate", ["Individual Tax", "H.R. 1"], "REG-III-B-4"),
        ("REG-III-008", "Filing Status Determination", 45, "beginner", ["Individual Tax"], "REG-III-C-1"),
        ("REG-III-009", "Dependency: Qualifying Child & Relative", 50, "intermediate", ["Individual Tax"], "REG-III-C-2"),
        ("REG-III-010", "Child Tax Credit", 45, "intermediate", ["Individual Tax"], "REG-III-D-1"),
        ("REG-III-011", "Earned Income Credit", 50, "intermediate", ["Individual Tax"], "REG-III-D-2"),
        ("REG-III-012", "Education Credits: AOTC & LLC", 45, "intermediate", ["Individual Tax"], "REG-III-D-3"),
        ("REG-III-013", "🆕 H.R. 1: Enhanced Child Tax Credit", 40, "intermediate", ["Individual Tax", "H.R. 1"], "REG-III-D-4"),
        ("REG-III-014", "Basis Determination", 55, "advanced", ["Property Tax"], "REG-III-E-1"),
        ("REG-III-015", "Capital Gains & Losses", 60, "advanced", ["Property Tax"], "REG-III-E-2"),
        ("REG-III-016", "Section 1231 Assets & Recapture", 55, "advanced", ["Property Tax"], "REG-III-E-3"),
        ("REG-III-017", "Like-Kind Exchanges (Section 1031)", 55, "advanced", ["Property Tax"], "REG-III-E-4"),
        ("REG-III-018", "Home Sale Exclusion (Section 121)", 40, "intermediate", ["Property Tax"], "REG-III-E-5"),
        ("REG-IV-001", "C Corps: Formation (Section 351)", 55, "advanced", ["Entity Tax"], "REG-IV-A-1"),
        ("REG-IV-002", "C Corps: Taxable Income Computation", 60, "advanced", ["Entity Tax"], "REG-IV-A-2"),
        ("REG-IV-003", "C Corps: Distributions & E&P", 60, "advanced", ["Entity Tax"], "REG-IV-A-3"),
        ("REG-IV-004", "C Corps: Accumulated Earnings Tax", 45, "intermediate", ["Entity Tax"], "REG-IV-A-4"),
        ("REG-IV-005", "C Corps: Personal Holding Company Tax", 45, "intermediate", ["Entity Tax"], "REG-IV-A-5"),
        ("REG-IV-006", "S Corps: Eligibility & Election", 55, "intermediate", ["Entity Tax"], "REG-IV-B-1"),
        ("REG-IV-007", "S Corps: Shareholder Basis", 60, "advanced", ["Entity Tax"], "REG-IV-B-2"),
        ("REG-IV-008", "S Corps: Built-In Gains Tax", 50, "advanced", ["Entity Tax"], "REG-IV-B-3"),
        ("REG-IV-009", "S Corps: Distributions & AAA", 55, "advanced", ["Entity Tax"], "REG-IV-B-4"),
        ("REG-IV-010", "Partnerships: Formation & Contributions", 60, "advanced", ["Entity Tax"], "REG-IV-C-1"),
        ("REG-IV-011", "Partnerships: Partner Basis Calculations", 65, "advanced", ["Entity Tax"], "REG-IV-C-2"),
        ("REG-IV-012", "Partnerships: Allocations & Distributions", 60, "advanced", ["Entity Tax"], "REG-IV-C-3"),
        ("REG-IV-013", "Partnerships: Sales & Liquidations", 55, "advanced", ["Entity Tax"], "REG-IV-C-4"),
        ("REG-IV-014", "Trusts & Estates: Fiduciary Income Tax", 60, "advanced", ["Entity Tax"], "REG-IV-D-1"),
        ("REG-IV-015", "Distributable Net Income (DNI)", 50, "advanced", ["Entity Tax"], "REG-IV-D-2"),
        ("REG-IV-016", "Simple vs Complex Trusts", 45, "intermediate", ["Entity Tax"], "REG-IV-D-3"),
        ("REG-IV-017", "Tax-Exempt Entities: 501(c)(3)", 50, "intermediate", ["Entity Tax"], "REG-IV-E-1"),
        ("REG-IV-018", "Unrelated Business Income (UBTI)", 45, "intermediate", ["Entity Tax"], "REG-IV-E-2")
    ],
    "BAR": [
        ("BAR-I-001", "Acquisition Method: Overview", 55, "advanced", ["Business Combinations"], "BAR-I-A-1"),
        ("BAR-I-002", "Measuring Consideration Transferred", 50, "advanced", ["Business Combinations"], "BAR-I-A-2"),
        ("BAR-I-003", "Goodwill & Bargain Purchases", 55, "advanced", ["Business Combinations"], "BAR-I-A-3"),
        ("BAR-I-004", "Consolidation Procedures", 70, "advanced", ["Business Combinations"], "BAR-I-B-1"),
        ("BAR-I-005", "Intercompany Transactions: Inventory", 55, "advanced", ["Business Combinations"], "BAR-I-B-2"),
        ("BAR-I-006", "Intercompany Transactions: Fixed Assets", 55, "advanced", ["Business Combinations"], "BAR-I-B-2"),
        ("BAR-I-007", "Noncontrolling Interests", 55, "advanced", ["Business Combinations"], "BAR-I-B-3"),
        ("BAR-I-008", "Variable Interest Entities: Identification", 50, "advanced", ["Business Combinations"], "BAR-I-C-1"),
        ("BAR-I-009", "VIE: Primary Beneficiary", 50, "advanced", ["Business Combinations"], "BAR-I-C-2"),
        ("BAR-I-010", "Disposal of Subsidiaries", 45, "advanced", ["Business Combinations"], "BAR-I-B"),
        ("BAR-II-001", "Complex Contract Modifications", 50, "advanced", ["Technical Accounting"], "BAR-II-A-1"),
        ("BAR-II-002", "Principal vs Agent Considerations", 50, "intermediate", ["Technical Accounting"], "BAR-II-A-2"),
        ("BAR-II-003", "Licenses of Intellectual Property", 55, "advanced", ["Technical Accounting"], "BAR-II-A-3"),
        ("BAR-II-004", "Lease Modifications & Reassessments", 50, "advanced", ["Technical Accounting"], "BAR-II-B-1"),
        ("BAR-II-005", "Subleases", 45, "advanced", ["Technical Accounting"], "BAR-II-B-2"),
        ("BAR-II-006", "Build-to-Suit Arrangements", 45, "advanced", ["Technical Accounting"], "BAR-II-B-3"),
        ("BAR-II-007", "Derivatives: Forwards, Futures, Options, Swaps", 65, "advanced", ["Technical Accounting"], "BAR-II-C-1"),
        ("BAR-II-008", "Hedge Accounting: Fair Value Hedges", 60, "advanced", ["Technical Accounting"], "BAR-II-C-2, BAR-II-C-3"),
        ("BAR-II-009", "Hedge Accounting: Cash Flow Hedges", 60, "advanced", ["Technical Accounting"], "BAR-II-C-3"),
        ("BAR-II-010", "Foreign Currency Transactions", 55, "advanced", ["Technical Accounting"], "BAR-II-D-1"),
        ("BAR-II-011", "Translation of Foreign Operations", 60, "advanced", ["Technical Accounting"], "BAR-II-D-2"),
        ("BAR-II-012", "Remeasurement", 50, "advanced", ["Technical Accounting"], "BAR-II-D-3"),
        ("BAR-III-001", "Capital Assets & Infrastructure (GASB)", 55, "advanced", ["Governmental"], "BAR-III-A-1"),
        ("BAR-III-002", "Long-Term Liabilities: Governmental", 50, "advanced", ["Governmental"], "BAR-III-A-2"),
        ("BAR-III-003", "Pension Accounting: GASB 68", 65, "advanced", ["Governmental"], "BAR-III-A-3"),
        ("BAR-III-004", "OPEB: GASB 75", 55, "advanced", ["Governmental"], "BAR-III-A-3"),
        ("BAR-III-005", "ACFR Components", 50, "intermediate", ["Governmental"], "BAR-III-B-1"),
        ("BAR-III-006", "RSI & Supplementary Information", 45, "intermediate", ["Governmental"], "BAR-III-B-2"),
        ("BAR-III-007", "Government-Wide to Fund Reconciliations", 55, "advanced", ["Governmental"], "BAR-III-B-3"),
        ("BAR-III-008", "Fiduciary Activities: GASB 84", 45, "intermediate", ["Governmental"], "BAR-III-B"),
        ("BAR-III-009", "Leases: GASB 87", 50, "advanced", ["Governmental"], "BAR-III-A"),
        ("BAR-IV-001", "Ratio Analysis: Liquidity, Solvency, Profitability", 55, "intermediate", ["Financial Analysis"], "BAR-IV-A-1"),
        ("BAR-IV-002", "Trend Analysis & Benchmarking", 45, "intermediate", ["Financial Analysis"], "BAR-IV-A-2"),
        ("BAR-IV-003", "Prospective Financial Statements", 50, "intermediate", ["Financial Analysis"], "BAR-IV-A-3"),
        ("BAR-IV-004", "Cost-Volume-Profit Analysis", 55, "intermediate", ["Financial Analysis"], "BAR-IV-B-1"),
        ("BAR-IV-005", "Budgeting & Forecasting", 50, "intermediate", ["Financial Analysis"], "BAR-IV-B-2"),
        ("BAR-IV-006", "Variance Analysis", 55, "advanced", ["Financial Analysis"], "BAR-IV-B-3"),
        ("BAR-IV-007", "Cost Accounting: Job & Process", 50, "intermediate", ["Financial Analysis"], "BAR-IV-B"),
        ("BAR-IV-008", "Activity-Based Costing", 45, "intermediate", ["Financial Analysis"], "BAR-IV-B"),
        ("BAR-IV-009", "Capital Budgeting: NPV, IRR, Payback", 60, "advanced", ["Financial Analysis"], "BAR-IV-B")
    ],
    "ISC": [
        ("ISC-I-001", "Database Fundamentals", 50, "intermediate", ["Information Systems"], "ISC-I-A-1"),
        ("ISC-I-002", "Data Modeling & Normalization", 55, "advanced", ["Information Systems"], "ISC-I-A-2"),
        ("ISC-I-003", "Data Governance & Quality", 45, "intermediate", ["Information Systems"], "ISC-I-A-3"),
        ("ISC-I-004", "SQL for Auditors", 60, "intermediate", ["Information Systems"], "ISC-I-A-1"),
        ("ISC-I-005", "Hardware & Infrastructure", 45, "beginner", ["Information Systems"], "ISC-I-B-1"),
        ("ISC-I-006", "Cloud Computing: IaaS, PaaS, SaaS", 55, "intermediate", ["Information Systems"], "ISC-I-B-2"),
        ("ISC-I-007", "Network Fundamentals", 50, "intermediate", ["Information Systems"], "ISC-I-B-3"),
        ("ISC-I-008", "System Development Life Cycle", 55, "intermediate", ["Information Systems"], "ISC-I-C-1"),
        ("ISC-I-009", "Change Management Controls", 50, "intermediate", ["Information Systems"], "ISC-I-C-2"),
        ("ISC-I-010", "Disaster Recovery & BCP", 55, "intermediate", ["Information Systems"], "ISC-I-C-3"),
        ("ISC-I-011", "IT Governance: COBIT & ITIL", 50, "intermediate", ["Information Systems"], "ISC-I-C"),
        ("ISC-I-012", "Big Data & Data Analytics", 50, "intermediate", ["Information Systems"], "ISC-I-A"),
        ("ISC-II-001", "Cybersecurity Threat Landscape", 55, "intermediate", ["Security"], "ISC-II-A-1"),
        ("ISC-II-002", "Security Controls: Preventive, Detective, Corrective", 50, "intermediate", ["Security"], "ISC-II-A-2"),
        ("ISC-II-003", "Encryption & Cryptography", 55, "advanced", ["Security"], "ISC-II-A-3"),
        ("ISC-II-004", "Logical Access Controls", 50, "intermediate", ["Security"], "ISC-II-B-1"),
        ("ISC-II-005", "Physical Access Controls", 40, "beginner", ["Security"], "ISC-II-B-2"),
        ("ISC-II-006", "Identity & Access Management", 50, "intermediate", ["Security"], "ISC-II-B-3"),
        ("ISC-II-007", "Privacy Principles & GAPP", 50, "intermediate", ["Security"], "ISC-II-C-1"),
        ("ISC-II-008", "HIPAA Requirements", 50, "intermediate", ["Security"], "ISC-II-C-2"),
        ("ISC-II-009", "GDPR & Global Privacy", 50, "intermediate", ["Security"], "ISC-II-C-3"),
        ("ISC-II-010", "Incident Response & Breach Handling", 50, "intermediate", ["Security"], "ISC-II-A"),
        ("ISC-II-011", "Vulnerability Assessment & Penetration Testing", 45, "intermediate", ["Security"], "ISC-II-A"),
        ("ISC-III-001", "SOC 1: Overview & Scope", 55, "intermediate", ["SOC"], "ISC-III-A-1"),
        ("ISC-III-002", "SOC 1: Type 1 vs Type 2 Reports", 50, "intermediate", ["SOC"], "ISC-III-A-2"),
        ("ISC-III-003", "SOC 1: Control Objectives", 50, "advanced", ["SOC"], "ISC-III-A-3"),
        ("ISC-III-004", "SOC 2: Trust Services Criteria", 60, "advanced", ["SOC"], "ISC-III-B-1"),
        ("ISC-III-005", "SOC 2: Examination & Reporting", 55, "advanced", ["SOC"], "ISC-III-B-2"),
        ("ISC-III-006", "SOC 3: Public Reports", 35, "beginner", ["SOC"], "ISC-III-C-1"),
        ("ISC-III-007", "SOC for Cybersecurity", 55, "intermediate", ["SOC"], "ISC-III-C-2"),
        ("ISC-III-008", "Using SOC Reports in Financial Audits", 50, "advanced", ["SOC"], "ISC-III-A"),
        ("ISC-III-009", "Subservice Organizations: Carve-Out vs Inclusive", 45, "advanced", ["SOC"], "ISC-III-A"),
        ("ISC-III-010", "SOC for Supply Chain", 45, "intermediate", ["SOC"], "ISC-III-C")
    ],
    "TCP": [
        ("TCP-I-001", "Income Timing Strategies", 55, "advanced", ["Tax Planning"], "TCP-I-A-1"),
        ("TCP-I-002", "Income Shifting Strategies", 50, "advanced", ["Tax Planning"], "TCP-I-A-2"),
        ("TCP-I-003", "🆕 H.R. 1: New Income Exclusions", 45, "intermediate", ["Tax Planning", "H.R. 1"], "TCP-I-A-3"),
        ("TCP-I-004", "Deduction Timing & Bunching", 55, "advanced", ["Tax Planning"], "TCP-I-B-1, TCP-I-B-2"),
        ("TCP-I-005", "🆕 H.R. 1: Updated Deduction Limits", 45, "intermediate", ["Tax Planning", "H.R. 1"], "TCP-I-B-3"),
        ("TCP-I-006", "Capital Gains Strategies", 55, "advanced", ["Tax Planning"], "TCP-I-C-1"),
        ("TCP-I-007", "Qualified Opportunity Zones", 50, "advanced", ["Tax Planning"], "TCP-I-C-2"),
        ("TCP-I-008", "Net Investment Income Tax Planning", 50, "advanced", ["Tax Planning"], "TCP-I-C-3"),
        ("TCP-I-009", "Retirement Planning: Roth vs Traditional", 55, "intermediate", ["Tax Planning"], "TCP-I-A"),
        ("TCP-I-010", "Charitable Giving Strategies", 50, "intermediate", ["Tax Planning"], "TCP-I-B"),
        ("TCP-II-001", "Entity Selection: Comprehensive Comparison", 65, "advanced", ["Entity Planning"], "TCP-II-A-1"),
        ("TCP-II-002", "Check-the-Box Regulations", 50, "intermediate", ["Entity Planning"], "TCP-II-A-2"),
        ("TCP-II-003", "State Tax Considerations: Nexus", 55, "intermediate", ["Entity Planning"], "TCP-II-A-3"),
        ("TCP-II-004", "State Apportionment Formulas", 50, "intermediate", ["Entity Planning"], "TCP-II-A-3"),
        ("TCP-II-005", "Reasonable Compensation Planning", 55, "advanced", ["Entity Planning"], "TCP-II-B-1"),
        ("TCP-II-006", "Retirement Plan Selection", 60, "advanced", ["Entity Planning"], "TCP-II-B-2"),
        ("TCP-II-007", "Fringe Benefits Tax Planning", 50, "intermediate", ["Entity Planning"], "TCP-II-B-3"),
        ("TCP-II-008", "Section 199A Planning Strategies", 60, "advanced", ["Entity Planning"], "TCP-II-B"),
        ("TCP-II-009", "International Tax: GILTI", 55, "advanced", ["International Tax"], "TCP-II-C-1, TCP-II-C-2"),
        ("TCP-II-010", "International Tax: FDII & BEAT", 55, "advanced", ["International Tax"], "TCP-II-C-2"),
        ("TCP-II-011", "Transfer Pricing Concepts", 55, "advanced", ["International Tax"], "TCP-II-C-3"),
        ("TCP-II-012", "Business Succession Planning", 55, "advanced", ["Entity Planning"], "TCP-II-A"),
        ("TCP-II-013", "Equity Compensation Planning", 50, "advanced", ["Entity Planning"], "TCP-II-B"),
        ("TCP-II-014", "Partnership Advanced Planning", 55, "advanced", ["Entity Planning"], "TCP-II-A"),
        ("TCP-III-001", "Installment Sale Planning", 55, "advanced", ["Property Transactions"], "TCP-III-A-1"),
        ("TCP-III-002", "Related Party Transactions", 50, "advanced", ["Property Transactions"], "TCP-III-A-2"),
        ("TCP-III-003", "Like-Kind Exchange Planning: Advanced", 60, "advanced", ["Property Transactions"], "TCP-III-A-3"),
        ("TCP-III-004", "Stock vs Asset Sales", 55, "advanced", ["Property Transactions"], "TCP-III-B-1"),
        ("TCP-III-005", "Section 338 Elections", 50, "advanced", ["Property Transactions"], "TCP-III-B-2"),
        ("TCP-III-006", "Corporate Liquidations Planning", 55, "advanced", ["Property Transactions"], "TCP-III-B-3"),
        ("TCP-IV-001", "Gift Tax: Annual Exclusion & Lifetime", 55, "intermediate", ["Gift & Estate"], "TCP-IV-A-1"),
        ("TCP-IV-002", "Gift-Splitting Strategies", 45, "intermediate", ["Gift & Estate"], "TCP-IV-A-2"),
        ("TCP-IV-003", "Valuation Discounts: FLPs & LLCs", 55, "advanced", ["Gift & Estate"], "TCP-IV-A-3"),
        ("TCP-IV-004", "Estate Tax: Valuation & Deductions", 60, "advanced", ["Gift & Estate"], "TCP-IV-B-1, TCP-IV-B-2"),
        ("TCP-IV-005", "Estate Tax: Portability Election", 45, "intermediate", ["Gift & Estate"], "TCP-IV-B-3"),
        ("TCP-IV-006", "Generation-Skipping Transfer Tax", 50, "advanced", ["Gift & Estate"], "TCP-IV-B")
    ]
}

def generate_typescript_file(section, lessons):
    variable_name = f"{section.lower()}Lessons"
    
    content = f"import {{ Lesson }} from '../../types';\n\n"
    content += f"export const {variable_name}: Lesson[] = [\n"
    
    for i, (id, title, duration, difficulty, topics, blueprint) in enumerate(lessons):
        # Create a simple generic content block for now
        lesson_content = f"{title}. {blueprint}. This lesson covers {', '.join(topics)}."
        
        content += "  {\n"
        content += f"    id: '{id}',\n"
        content += f"    section: '{section}',\n"
        content += f"    title: \"{title}\",\n"
        content += f"    description: \"{blueprint}\",\n"
        content += f"    order: {i + 1},\n"
        content += f"    duration: {duration},\n"
        content += f"    difficulty: '{difficulty}',\n"
        content += f"    topics: {json.dumps(topics)},\n"
        content += "    content: {\n"
        content += "      sections: [\n"
        content += "        {\n"
        content += f"          title: 'Overview',\n"
        content += "          type: 'text',\n"
        content += f"          content: \"{lesson_content}\"\n"
        content += "        }\n"
        content += "      ]\n"
        content += "    }\n"
        content += "  }"
        if i < len(lessons) - 1:
            content += ",\n"
        else:
            content += "\n"
            
    content += "];\n"
    return content

for section, lessons in lessons_data.items():
    file_path = f"/workspaces/passcpa/src/data/lessons/{section.lower()}.ts"
    with open(file_path, "w") as f:
        f.write(generate_typescript_file(section, lessons))
    print(f"Generated {file_path}")
