/**
 * Article fetching for Astro static build
 * 
 * Reads from pre-exported JSON file (generated by scripts/export-articles.cjs)
 * This avoids needing Firebase credentials during the Astro build.
 */

import articlesData from '../data/articles.json';

// Types matching the main app
export interface Article {
  id: string;
  slug: string;
  title: string;
  metaTitle?: string;
  metaDescription?: string;
  courseId: string;
  section?: string;
  contentType: string;
  primaryKeyword?: string;
  generatedContent?: string;
  publishedAt: Date;
  updatedAt?: Date;
  ogImage?: string;
  author?: string;
}

// Parse JSON dates to Date objects
function parseArticle(raw: any): Article {
  return {
    ...raw,
    publishedAt: new Date(raw.publishedAt),
    updatedAt: raw.updatedAt ? new Date(raw.updatedAt) : undefined,
  };
}

/**
 * Get all published articles
 */
export async function getPublishedArticles(): Promise<Article[]> {
  return (articlesData as any[]).map(parseArticle);
}

/**
 * Get a single article by slug
 */
export async function getArticleBySlug(slug: string): Promise<Article | null> {
  const article = (articlesData as any[]).find(a => a.slug === slug);
  return article ? parseArticle(article) : null;
}

/**
 * Get related articles for internal-linking blocks.
 */
export async function getRelatedArticles(currentArticle: Article, limit = 3): Promise<Article[]> {
  const articles = await getPublishedArticles();

  return articles
    .filter(article => article.slug !== currentArticle.slug)
    .sort((a, b) => {
      const score = (article: Article) => {
        let value = 0;
        if (article.courseId === currentArticle.courseId) value += 2;
        if (article.section && currentArticle.section && article.section === currentArticle.section) value += 1;
        return value;
      };

      const scoreDiff = score(b) - score(a);
      if (scoreDiff !== 0) return scoreDiff;

      return b.publishedAt.getTime() - a.publishedAt.getTime();
    })
    .slice(0, limit);
}

/**
 * Get all article slugs (for static path generation)
 */
export async function getAllSlugs(): Promise<string[]> {
  return (articlesData as any[]).map(a => a.slug).filter(Boolean);
}

/**
 * Get exam display name
 */
export function getExamName(courseId: string): string {
  const names: Record<string, string> = {
    cpa: 'CPA Exam',
    ea: 'EA Exam',
    cma: 'CMA Exam',
    cia: 'CIA Exam',
    cfp: 'CFP Exam',
    cisa: 'CISA Exam',
  };
  return names[courseId] || courseId.toUpperCase();
}

/**
 * Get exam color class
 */
export function getExamColor(courseId: string): string {
  const colors: Record<string, string> = {
    cpa: 'bg-blue-500',
    ea: 'bg-emerald-500',
    cma: 'bg-purple-500',
    cia: 'bg-amber-500',
    cfp: 'bg-green-500',
    cisa: 'bg-cyan-500',
  };
  return colors[courseId] || 'bg-gray-500';
}
